### ISSUE TITLE
ImportError: DLL load failed: %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by drno-reg** [oracle/python-cx_Oracle#10]
Hello,

I have 
- Python 3.6.1 64 bit,
- Oracle client 12.2 x64 (instantclient-sdk-windows.x64-12.2.0.1.0.zip (1,801,992 bytes) (cksum - 3191784704) and instantclient-basic-windows.x64-12.2.0.1.0.zip (75,062,441 bytes) (cksum - 1462971172) wrote path in Windows OS Environment ORACLE_HOME = C:\DataBases\Oracle\instantclient),
- OS windows 2012 x64,
- compiler MS C/C++ 19.10.25017 x64
               MS Visual C++ 2015

Tried to execute this code

```
#!/usr/bin/python
import cx_Oracle
ip='192.168.0.2'
port = 1521
SID = 'dboracle'
USERNAME='dboracle'
PASSWORD='pwd'
sql_script="""
SELECT sysdate from dual
"""
dsn_tns = cx_Oracle.makedsn(ip, port, SID)
print (dsn_tns)
conn = cx_Oracle.connect(USERNAME, PASSWORD, dsn_tns)
c = conn.cursor()
c.execute(sql_script)
for row in c:
    print (row[0], row[1])
conn.close()

```
end got error
```
C:\Python36\python.exe C:/templates/DB/Oracle/Jobs.py
Traceback (most recent call last):
  File "C:/templates/DB/Oracle/Jobs.py", line 2, in <module>
    import cx_Oracle
ImportError: DLL load failed: %1 is not a valid Win32 application.
```

How to solve this problem?

**Comment by drno-reg** [comment]
On windows 2012 r2 I found folder Oracle with installed Oracle Client 11.0.1 32 bit.
After uninstalled this version Oracle client python interpreter executed script OK.

Problem solved.

**Comment by aattaran** [comment]
HI, I have python 3.6 and 2.7. I installed anaconda 3 4.4.0 but it gives this error:
C:\Anaconda3\Scripts>conda
Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 178, in main
    from ..exceptions import conda_exception_handler
  File "C:\Anaconda3\lib\site-packages\conda\exceptions.py", line 16, in <module>
    from .common.url import maybe_unquote
  File "C:\Anaconda3\lib\site-packages\conda\common\url.py", line 8, in <module>
    import socket
  File "C:\Anaconda3\lib\socket.py", line 49, in <module>
    import _socket
ImportError: DLL load failed: %1 is not a valid Win32 application.

**Comment by cjbj** [comment]
@aattaran If this is related to cx_Oracle can you check http://cx-oracle.readthedocs.io/en/latest/installation.html#installing-cx-oracle-on-windows and start a new issue if you still have problems?
