### ISSUE TITLE
[Question]Behavior in multithread

### ISSUE THREAD

**Issue by zeruitle** [oracle/python-cx_Oracle#100]
Hi everyone,

I wish to ask about the behavior of 2 thread related function of cx_oracl

1. cx_Oracle.connect(threaded = True), how exactly this will behave? is this function means, it will create a SINGLE connection object, and its thread safe, but its still a SINGLE resource that if one thread acquire it others are blocked?

2.cx_Oracle.SessionPool(threaded = True), how about this one? it this function also means it will create a SINGLE thread safe pool object?

Thank You

**Comment by anthony-tuininga** [comment]
Connections can be shared between threads but only ONE statement can be executed against the database at the same time. The other statements will block until the first one has completed its work against the database. To execute multiple statements at once you need multiple connections. And this is where the session pool comes into play. It allows you to acquire/release multiple connections quickly and easily from a pool of them. And each connection can perform its own work concurrently with other connections to the database. Yes, you can create multiple standalone connections and do the same thing but usually a session pool is the right answer to this sort of question!

Hope that explains things!

**Comment by zeruitle** [comment]
Anthony thank you so much for explain!

But " It allows you to acquire/release multiple connections quickly and easily from a pool of them", isn't this the behavior of connection pool?

**Comment by anthony-tuininga** [comment]
> But " It allows you to acquire/release multiple connections quickly and easily from a pool of them", isn't this the behavior of connection pool?

Yes! And that is what cx_Oracle.SessionPool is. It is called SessionPool because it is based off OCISessionPool, that's all.

**Comment by zeruitle** [comment]
hahaha, the name is so missleading... Thant's why in the document, its say acquire and release give you and return a connection object...

Thank you so much for explain!!!

**Comment by zeruitle** [comment]
anthony, I forgot one more question...

For cx_Oracle.connect(threaded = True), so when threads try to make statements at same time, does the connection object wrap all statements and send to DB at one time, then DB execute each statement one by one, then wrap the results send back?

**Comment by anthony-tuininga** [comment]
Essentially, yes. This is not just for connection.execute() but also for cursor.fetch*() and any other operation which requires a round trip to the database.

**Comment by zeruitle** [comment]
so how does cx_oracle knows those threads should be in one round trip and other threads should wait for next ticket?

**Comment by anthony-tuininga** [comment]
The underlying Oracle client library handles this internally by means of mutexes.

**Comment by zeruitle** [comment]
hmmm... interesting.

I believe this is all my question! thank you so much Anthony!
