### ISSUE TITLE
Feature request: 12c connect as SYSDG not supported

### ISSUE THREAD

**Issue by danidorbek** [oracle/python-cx_Oracle#101]
### For general questions:
From 12c onwards Oracle introduced new ways of connecting ([Oracle Docs](https://docs.oracle.com/database/122/ADMIN/getting-started-with-database-administration.htm#ADMIN11013)) :
 - AS **SYSDG**, 
 - AS **SYSBACKUP**, 
 - AS **SYSKM**
 - AS **SYSRAC**

This is created to support "least privileges" logic. 

Is it possible to introduce the roles above?

#### Answer the following questions:

1. What is your version of Python? Is it 32-bit or 64-bit?
64

2. What is your version of cx_Oracle?
6.0.2

3. What is your version of the Oracle client (e.g. Instant Client)?  How was it
   installed?  Where is it installed?
Full administrative clients 12,1 and 12.2

4. What is your version of the Oracle Database?
12c

5. What is your OS and version?
n/a

6. What compiler version did you use?  For example, with GCC, run
   `gcc --version`.
n/a

7. What environment variables did you set?  How *exactly* did you set them?
n/a

8. What *exact* command caused the problem (e.g. what command did you try to
   install with)?  Who were you logged in as?
n/a

9. What error(s) you are seeing?
n/a

**Comment by anthony-tuininga** [comment]
It is definitely possible and shouldn't be too much work to implement. :-)

**Comment by anthony-tuininga** [comment]
This has now been implemented.
