### ISSUE TITLE
Problems with callproc() in Python with Oracle DB

### ISSUE THREAD

**Issue by noldini** [oracle/python-cx_Oracle#104]
Hello! I have a question,
I created a procedure and stored it in my OracleDB.
Now I want to execute the procedure, but its not working. There is no Error-Message Occuring, it just stops and dont continue after the first **callproc** call. Anybody any ideas?

!Autoincrement is enabled for the whole script!
`
import cx_Oracle
dsn= cx_Oracle.makedsn("**********,1521,"orcl")
db= cx_Oracle.connect('******','*******',dsn)
db.autocommit = True
cur = db.cursor()
cur.callproc("UPDATE_MISSING_VALUES", ['GENDER','SDV_PRE',1])
`

The Procedure is found and if I change the parameters, an SQL Error occurs. But if I let it like that, nothing happens.

If I run that query in SQL-Developer, it works just fine

**Comment by anthony-tuininga** [comment]
What were you expecting to happen? Is that the entire script? Can you clean up the formatting so that it is readable?

**Comment by noldini** [comment]
Hey thanks for your quick response. No its not the entire script. I expect the Procedure "UPDATE_MISSING_Value" to start with the Parameters. But in reality I think it starts but then it get stuck somewhere. It should iterate with a for loop and excecute the procedure multiple times. Later I want to replace the fixed values with parameters, but first I want it to work for fixed values :)

Here is more lines of the code

```python
#coding=utf-8
import cx_Oracle
dsn= cx_Oracle.makedsn("******",1521,"orcl")
db= cx_Oracle.connect('*****','*****',dsn)
db.autocommit = True
tabelle ='*****_PRE'


cur = db.cursor()
cur.execute("(SELECT column_name,data_type FROM USER_TAB_COLUMNS WHERE table_name = '%s' ) " % tabelle )
results1 = cur.fetchall()
results_as_list = [i[0] for i in results1]
datentypen_columns = [i[1] for i in results1]
missing_columns = []
for column in results_as_list:
    t= (column,tabelle,column)
    cur.execute("Select % s From % s Where % s IS NULL " % t)

    result = cur.fetchall()
    if  result:
        missing_columns.append(column)


for column in missing_columns:
    missing2=(tabelle,column)
    cur.execute("Select ID From % s Where % s IS NULL " % missing2)
    id_missing_cells = cur.fetchall()

    for ID in id_missing_cells:
         cur.callproc("UPDATE_MISSING_VALUES", ['GENDER','SDV_PRE',1])
   ```

**Comment by anthony-tuininga** [comment]
Looks like you need to add a few judicious print statements to see whether there are any missing columns and missing cells, and whether your procedure is even being called at all! If it is called, what does it do in the database? Can you look in there? It seems to me you need to do some debugging. :-)

**Comment by noldini** [comment]
Thank you, I tried already. I dont know why, but now it works. Is it possible, that sometimes its not working, if you try it 1 hour later, suddenly its working? HAHA

**Comment by anthony-tuininga** [comment]
Generally, no. :-) But in your case the code is dependent on the data, so perhaps the data changed? In any case, your problem appears to be resolved!

**Comment by noldini** [comment]
Yes thank you!

**Comment by noldini** [comment]
It works now, I have actually now idea why, but the most important thing is that it works.
Is it possible, that the reason is that I made a 

    COMMIT;

Statement in my DB?? After that it worked suddenly.

**Comment by anthony-tuininga** [comment]
Possibly. Although you also have autocommit enabled. You can always take it back out and see if the problem recurs. :-)

**Comment by Rohith-Scalers** [comment]
hey , having same issue , is there any explanation why this is occurring, does adding COMMIT will fix it fully or is it a temporary fix.
Thank you :)

**Comment by anthony-tuininga** [comment]
This issue has been closed for almost 7 years! If you are experiencing an issue, please open a **new** issue in [python-oracledb](https://github.com/oracle/python-oracledb/issues) which is the replacement for cx_Oracle.
