### ISSUE TITLE
AttributeError: module 'cx_Oracle' has no attribute 'makedns'

### ISSUE THREAD

**Issue by NyxmeFy** [oracle/python-cx_Oracle#105]
Hello,

I have one sample application It is called "python.py".
I would like to connect to my database

import cx_Oracle

host = 'address.oraclecloud.internal'
port = 1521
serviceName = 'PDB1'
user = 'developer1'
password = 'password123@'

dns = cx_Oracle.makedns(host,port,serviceName)
conn = cx_Oracle.connect(user, password, dns)
cur = conn.cursor()
cur.execute('SELECT * FROM TABLE1')
print(cur.fetchall())
cur.close

But when I try to execute this application, it appears to me:

**Traceback (most recent call last):
  File "test-oracle/python.py", line 31, in <module>
    dns = cx_Oracle.makedns(host,port,serviceName)
AttributeError: module 'cx_Oracle' has no attribute 'makedns'**

What am I doing wrong?

**Comment by anthony-tuininga** [comment]
That's probably because you're looking for makedsn()??? :-)

**Comment by cjbj** [comment]
If you really do have a Service Name (which most people nowadays do have), you'll need to do:
```
dsn = cx_Oracle.makedsn(host,port,service_name=serviceName)
```
otherwise the 3rd parameter is treated as the old-style SID instead of a service name.

**Comment by NyxmeFy** [comment]
Thank you guys,
I've written 'dns' instead of 'dsn'. but even so my code was not working.
I did what cjbj told me to do and it worked!
