### ISSUE TITLE
6.0.2 memory footprint

### ISSUE THREAD

**Issue by bschwab003** [oracle/python-cx_Oracle#107]
Not necessarily an issue per say, but wanted to get your thoughts on the matter......

I posted recently about upgrading from 5.2.1 to 6.0.2 to fix truncation issues when encountering large numbers.  We did the upgrade and learned we also had to add a handler for coercing NUMBER data types to decimal.Decimal.  We did that as well....

The upgrade and the additional handler worked as planned.  However, I have noticed a pretty significant jump in the memory footprint.  If you consider the handler, it may make sense because I am sure there is some overhead associated with the additional Handler and using Decimals instead of floats.  But even w/out the handler, we still saw upwards of 3X the memory footprint from 5.2.1 to 6.0.2. 

Basic test we performed.  We ran the same three (94K records, 134K records, 3.1M records) queries.  

chunk_size=500K
cursor.arraysize = chunk_size / 2

....and monitored the memory footprint of each extraction and saw the following....

5.2.1 w/out handler...consumed at most (approx) 780MB of memory
6.0.2 w/out handler...consumed at most (approx) 2,190MB of memory

5.2.1 w/handler...consumed at most (approx) 2,200MB of memory
6.0.2 w/handler...consumed at most (approx) 2,600MB of memory

Is this expected or is there anything else we can do to control the increase in memory consumption?

**Comment by anthony-tuininga** [comment]
Can you create some sample code that demonstrates the problem? I hadn't noticed the difference myself, but there might be certain circumstances that cause this to happen -- and if so, I'd love to eliminate it, if possible!

6.x changed the default arraysize to 100 (it was 50 in 5.x) but since you're setting the arraysize directly, that can't be the source of the changes in memory usage. Nothing else immediately jumps to mind, so if you can provide the test case that demonstrates the problem I can see if I can replicate it here. Thanks!

**Comment by cjbj** [comment]
It would also be useful to know what tool you are measuring memory usage with.

**Comment by bschwab003** [comment]
I will admit...I am using the rather rudimentary approach of leveraging Task Manager/Resource Monitor to monitor memory usage. 

So cx_Oracle is being used as part of a 'larger' program.  I will also say that I am monitoring the memory usage of the entire program....not just cx_Oracle.  But data extraction/cx_Oracle is the focus/purpose of the program.   The only reason I am attributing the bump in memory to cx_Oracle was the fact that upgrading the cx_Oracle version/adding handler were the only two changes that were made.

I can try to pull out just the cx_Oracle bit but its pretty straight forward...create connection, get cursor, execute statement use fetchmany with a chunk size of 500K.

Let me try to get you something....

**Comment by bschwab003** [comment]
So here is my test snippet with all the non-cx_Oracle code removed.....I just commented on/off the line that adds the handler. 

Obviously, you will have to enter your own connection information and SQL statement.

```
import cx_Oracle
import decimal


def NumbersAsDecimal(cursor, name, defaultType, size, precision,
        scale):
    if defaultType == cx_Oracle.NUMBER:
        return cursor.var(str, 100, cursor.arraysize,
                outconverter=decimal.Decimal)


def connect_to_oracle(host, user, port, password=None,
                      system_id=None, service_name=None,
                      tnsname=None):

    if tnsname:
        return cx_Oracle.connect(user, password, tnsname)
    elif system_id:
        dsn = cx_Oracle.makedsn(host=host, port=port, sid=system_id)
        return cx_Oracle.connect(user, password, dsn, threaded=True)
    elif service_name:
        dsn = cx_Oracle.makedsn(host=host, port=port, service_name=service_name)
        return cx_Oracle.connect(user, password, dsn)

if __name__ == '__main__':
    print(cx_Oracle.__version__)
    chunk_size = 500000
    conn = connect_to_oracle(host='<tbd>', user='<tbd>', port='<tbd>', password='<tbd>', system_id='<tbd>')
    # conn.outputtypehandler = NumbersAsDecimal
    curs = conn.cursor()
    curs.arraysize = chunk_size/2
    curs.execute("SELECT GL_JE_LINES.JE_HEADER_ID,GL_JE_LINES.ACCOUNTED_DR,GL_JE_LINES.JE_LINE_NUM,GL_JE_LINES.ACCOUNTED_CR,GL_JE_LINES.LEDGER_ID,GL_JE_LINES.CODE_COMBINATION_ID,GL_JE_LINES.EFFECTIVE_DATE,GL_JE_LINES.ENTERED_DR,GL_JE_LINES.ENTERED_CR,GL_JE_LINES.DESCRIPTION,GL_JE_LINES.GL_SL_LINK_ID,GL_JE_LINES.GL_SL_LINK_TABLE,GL_JE_LINES.STATUS,GL_JE_LINES.CREATED_BY,GL_JE_LINES.PERIOD_NAME FROM GL.GL_JE_LINES INNER JOIN GL.GL_JE_HEADERS on GL_JE_LINES.JE_HEADER_ID = GL_JE_HEADERS.JE_HEADER_ID WHERE GL_JE_HEADERS.ACTUAL_FLAG = 'A' AND (GL_JE_HEADERS.DEFAULT_EFFECTIVE_DATE BETWEEN '01-JAN-00' AND '31-DEC-16') AND GL_JE_HEADERS.LEDGER_ID IN('1','42','62','102','103','104','122','123','124','125','126','142','143','162','163','165','186','187','205','207','208','268','288','289','290','332','393','454','477','609','650','670','874','875','876','914','916','956')")
    while True:
        data = curs.fetchmany(chunk_size)
        if data:
            print(len(data))
        else:
            break
```


And here are the max memory footprints I observed...

6.0.2 w/handler ~1,500MB
6.0.2 w/out handler  ~1,200MB
5.2.1 w/handler ~1,200MB
5.2.1  w/out handler ~600MB

**Comment by cjbj** [comment]
To complete the picture, what are the versions of Oracle client & database?  And what are the datatypes in the tables?

**Comment by bschwab003** [comment]
I'll defer to Oracle's documentation for data types...
https://docs.oracle.com/cloud/latest/financialscs_gs/OEDMF/GL_JE_LINES_tbl.htm

I would need to get confirmation from my team but I think its Oracle Database 12c.....I know the ERP version is EBS R12.   I'll see if I can track it down.

**Comment by anthony-tuininga** [comment]
This *may* be related to the OCI prefetch change that I just pushed to GitHub. Could you try with the latest code on master and let me know if that changes things for you? Earlier OCI prefetch was set to the number of rows in your arraysize value -- which reduces the number of round trips by one, but also dramatically increases memory usage. Please advise! Thanks.

**Comment by anthony-tuininga** [comment]
The cx_Oracle 6.1 release has been made which includes the changes I mentioned in my last post. I am going to assume this addresses your concerns, but feel free to re-open if it does not. Thanks!
