### ISSUE TITLE
Can't close connection after query with LOB result

### ISSUE THREAD

**Issue by mcs07** [oracle/python-cx_Oracle#108]
With cx_Oracle 6.0.3, I can't figure out how to close a connection after making a query with a LOB result. Even if I make sure to close the cursor, and delete the LOB object or call `close()` on it, I still get `DPI-1054: connection cannot be closed when open statements or LOBs exist`.

What's the best way to ensure everything is closed so the connection can be closed?

```
conn = cx_Oracle.connect(dsn)
cursor = conn.cursor()
id, my_lob = cursor.execute(...).fetchone()
result_string = my_lob.read()
# Need to close LOB. How?
del my_lob
cursor.close()
conn.close()  # Always fails
```

Python 2.7 64bit
cx_Oracle 6.0.3
oracle-instantclient 11.2.0.4.0
Windows 10

**Comment by anthony-tuininga** [comment]
Yes, you can close the LOB using del, as you indicated in your code. Generally you can avoid the close calls and cx_Oracle will close everything for you when the variables reach end of scope. Is that all of your code?

**Comment by mcs07** [comment]
My bad. My actual code was more like:

```
result = cursor.execute(query, id='...').fetchone()
if result:
    id, my_lob = result
    result_string = my_lob.read()
    del my_lob
cursor.close()
conn.close()
```

But of course the `result` variable still has a reference to the LOB. So I need to `del result` as well and everything works fine. Thanks!

**Comment by robbyturnip** [comment]
cx_Oracle.DatabaseError: DPI-1040: LOB was already closed

cx_Oracle 7.3.2

**Comment by anthony-tuininga** [comment]
If you have a test case that demonstrates the problem, please open a *NEW* issue and post it there instead of simply tacking on a comment to a long closed issue!
