### ISSUE TITLE
python insert gis data into oracle，thrown exception ORA-00939

### ISSUE THREAD

**Issue by zjl767864079zjl** [oracle/python-cx_Oracle#109]
When I use python to insert gis data(coordinate number is more than 1000) into oracle,throw an exception ORA-00939.
I kown the exception is oracle's restrict,the way to solve the problem is use procedure function.

create or replace procedure pyproc(gid number,geodata sdo_geometry) AS
BEGIN
  DECLARE geom sdo_geometry;
  BEGIN 
      geom:=geodata; 
      INSERT INTO test_table (GID, GEOMETRY) values(gid, geom);
  END;
END pyproc;

If I call the procedure function in oracle,the result is right.But I want to call in Python.I don't kown how to transmit the geodata,beacuse python has not a type is sdo_geometry.
Please help me, thanks!

**Comment by anthony-tuininga** [comment]
There is an example in the cx_Oracle repository that does this for you. Take a look [here](https://github.com/oracle/python-cx_Oracle/blob/master/samples/InsertGeometry.py).

**Comment by zjl767864079zjl** [comment]
Thanks,let me try it first.

**Comment by zjl767864079zjl** [comment]
Great, the problem is solved. Thanks very much!
