### ISSUE TITLE
Place a Client Call without internet

### ISSUE THREAD

**Issue by KrupaSuchak** [oracle/python-cx_Oracle#110]
Managed to establish a client call to oracle database via cx_Oracle but looking for an alternative which would run only on LAN and not require any internet connection. Any suggestions?

1. What is your version of Python? Is it 32-bit or 64-bit?
Anaconda python version 3.6.3 on 32-bit

2. What is your version of cx_Oracle?
6.0.2

3. What is your version of the Oracle client (e.g. Instant Client)?  How was it
   installed?  Where is it installed?
Instant Client version 12c. Installed as Administrator and instant client and created a tnsnames.ora file in D:\app\krupa.suchak\product\12.2.0\client_1\network\admin\.
Tnsnames.ora file has these credentials:
TESTUAT =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = …..)(PORT = ….))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = TESTLIVE)
    )
  )

4. What is your version of the Oracle Database?
12.1.0.2.0

5. What is your OS and version?
Windows 7

6. What compiler version did you use?  For example, with GCC, run
   `gcc --version`.
n/a

7. What environment variables did you set?  How *exactly* did you set them?
Set Anaconda python path and instant client path as system environment variable. 

8. What *exact* command caused the problem (e.g. what command did you try to
   install with)?  Who were you logged in as?
ora_conn = cx_Oracle.connect('USERNAME/PASSWORD@TESTLIVE')
df_daily = pd.read_sql('''SELECT * FROM TABLE ''', con=ora_conn)
ora_conn.close()

9. What error(s) you are seeing?
DatabaseError: ORA-12543: TNS:destination host unreachable
Error is caused when out of internet connection but works fine with internet.

**Comment by anthony-tuininga** [comment]
> Error is caused when out of internet connection but works fine with internet.

Can you clarify that statement? You can use a client on the same machine as the database, on the local are network or wide area network. It all depends on your configuration.

**Comment by cjbj** [comment]
Depending what you put here:
```
(ADDRESS = (PROTOCOL = TCP)(HOST = …..)(PORT = ….))
```
maybe your DNS server isn't reachable.   You can google to see whether your error message matches that scenario.  If so, you could use IP addresses instead of hostnames - if your IP addresses don't change.

**Comment by KrupaSuchak** [comment]
Thank you! I reconnected with an IP address and it works just fine.
