### ISSUE TITLE
sys_refcursor to use cursor class

### ISSUE THREAD

**Issue by ancc** [oracle/python-cx_Oracle#111]
Any plans to change the sys_refcursor so that it's from the same Cursor class as regular cursor?

https://stackoverflow.com/questions/41041110/how-to-extend-cx-oracle-sys-refcursor-curor-class

Tested on version 6.0.3 and it was not possible.

**Comment by anthony-tuininga** [comment]
I just tested with version 6.0.3 and it worked as expected! Can you retest and ensure you are using the version you think you are using? Thanks.

**Comment by ancc** [comment]
Great! It works. There's a typo in stackoverflow example, helloWorld() not hellowWorld().
