### ISSUE TITLE
subscribe doesn't obey port parameter

### ISSUE THREAD

**Issue by markfinn** [oracle/python-cx_Oracle#115]
cx_oracle 6.1.0, 11xe database, 12.2 client, 64 bit linux.

`sub = con.subscribe(callback = cb, port=9999, qos = cx_Oracle.SUBSCR_QOS_ROWIDS)`
ignores the port parameter as seen through `netstat -nlp | grep <pid goes here>`

If I test `sub.port` it is correctly set to 9999, but the bind actually happens on some random port.

**Comment by anthony-tuininga** [comment]
I'm not sure what the correct behaviour is supposed to be but I see the same behaviour. I'll ask internally.

**Comment by markfinn** [comment]
Any update on being able to use the port parameter?

**Comment by anthony-tuininga** [comment]
Not yet. Still waiting on internal resources.

**Comment by anthony-tuininga** [comment]
So the subscription port number was being set on the wrong handle. That has now been corrected and it works for me. If you're able to build and test yourself, let me know; otherwise, a new release should be coming soon.

**Comment by anthony-tuininga** [comment]
The cx_Oracle 6.1 release has been made which includes this fix, so I am going to close this under the assumption it works for you, too!
