### ISSUE TITLE
cx_Oracle.NotSupportedError: Object_ConvertToPython()

### ISSUE THREAD

**Issue by SnurnicynKonstantin** [oracle/python-cx_Oracle#116]
I have code on Python:

    def get_same_value(self):
        cursor = self.con.cursor()
        try:
            obj_type = self.con.gettype('MY_PKG.MY_TYPE')
            obj = obj_type.newobject()
            cursor.callproc('MY_PKG.getSameValue', [obj])
            return obj.aslist()
        finally:
            cursor.close()

In DB MY_TYPE is IS TABLE OF OBJECT. On cx_Oracle 6... version it worked.

On string return obj.aslist() I get error on version of cx_Oracle 5.3:

    cx_Oracle.NotSupportedError: Object_ConvertToPython(): unhandled data type 250

What can be wrong?
cx_Oracle backward compatible (if i update to 6 version, it not break old worked scripts)?

**Comment by anthony-tuininga** [comment]
Yes, cx_Oracle 6 is backwards compatible except as noted in [what's new](http://cx-oracle.readthedocs.io/en/latest/whatsnew.html).

**Comment by SnurnicynKonstantin** [comment]
@anthony-tuininga i updated cx_Oracle to latest version and geted "cx_Oracle.DatabaseError: DPI-1047: 64-bit Oracle Client library cannot be loaded: "libclntsh.so: cannot open shared object file: No such file or directory"
I pointed the way to libclntsh.so in LD_LIBRARY_PATH, but this did not solve the problem.....

**Comment by cjbj** [comment]
Try again: and check you really do have the 64 bit and not the 32 bit Instant Client.  Check the directory is accessible etc.

**Comment by SnurnicynKonstantin** [comment]
@cjbj I did the following
export ORACLE_HOME=/usr/lib/oracle/12.2/client64
export LD_LIBRARY_PATH=$ORACLE_HOME/lib

**Comment by SnurnicynKonstantin** [comment]
I decided it, thanks

**Comment by cjbj** [comment]
Do not set ORACLE_HOME when you have Instant Client.

Install instructions are [here](http://cx-oracle.readthedocs.io/en/latest/installation.html).

**Comment by cjbj** [comment]
PS can you close this if you fixed it?  I wasn't sure if you still needed help.
