### ISSUE TITLE
import cx_oracle 5.1.2 fails on python 2.7.8 in rehdat linux

### ISSUE THREAD

**Issue by veerabose** [oracle/python-cx_Oracle#118]
*Delete irrelevant parts of this template.*

### For general questions:

Describe exactly what you did and what you want to happen.
Use the questions at the bottom of this template as a guide.

Use Markdown syntax, particularly for code blocks: see https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

### For security issues:

See https://www.oracle.com/support/assurance/vulnerability-remediation/reporting-security-vulnerabilities.html for how to report security issues.

### For installation issues:

Use a gist for screen output and logs: see https://gist.github.com/
**Do not paste long output into this issue**

Review the install instructions at
https://github.com/oracle/python-cx_Oracle#installation

Review your output and logs.  **Google any errors**

#### Answer the following questions:

1. What is your version of Python? Is it 32-bit or 64-bit?
2.7.8 and 2.6.6 and version is 64 bit
2. What is your version of cx_Oracle?

3. What is your version of the Oracle client (e.g. Instant Client)?  How was it
   installed?  Where is it installed?
11.2.0.4.0
4. What is your version of the Oracle Database?
11.2.0.4.0
5. What is your OS and version?
RHEL and 6.8

6. What compiler version did you use?  For example, with GCC, run
   `gcc --version`.
gcc (GCC) 4.4.7 20120313
7. What environment variables did you set?  How *exactly* did you set them?
$scl enable python27 bash
$ python
Python 2.7.8 (default, May 19 2015, 02:50:14)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cx_Oracle
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
ImportError: No module named cx_Oracle

The same is working on 2.6.6 version

$ python
Python 2.6.6 (r266:84292, Aug  9 2016, 06:11:56)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cx_Oracle
>>>

8. What *exact* command caused the problem (e.g. what command did you try to
   install with)?  Who were you logged in as?
import cx_Oracle on python 2.7.8

9. What error(s) you are seeing?
>>> import cx_Oracle
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
ImportError: No module named cx_Oracle

**Comment by anthony-tuininga** [comment]
Did you build cx_Oracle for Python 2.7? Check the contents of sys.path and ensure that cx_Oracle.so (for Python 2.7) is found within one of those paths.

**Comment by veerabose** [comment]
Hi Anthony,

Thanks for response, I will try and update you in case of issue.

Thanks
Veera.

**Comment by veerabose** [comment]
can you please guide me, how to build cx_Oracle for Python 2.7?

Thanks
Veera.

**Comment by cjbj** [comment]
@veerabose check the installation doc http://cx-oracle.readthedocs.io/en/latest/installation.html# and let us know if you have questions.
