### ISSUE TITLE
alter system kill session command in cx_Oracle not working:Give illegal name/variable

### ISSUE THREAD

**Issue by nisha235** [oracle/python-cx_Oracle#130]
1) I have three variables which have value set as 
Psid=12
Pserial=23
 sql="alter system kill session '\'||:psid||','||:pserial||'\''"
 cursor.execute(sql,psid=Psid,pserial=Pserial)

2) its showing illegal variable/name as an error
3)please tell me why my bind variables are not working
4)All connections to database is working fine.

**Comment by anthony-tuininga** [comment]
Unfortunately, you can't use bind variables for these kinds of statements. And doubly unfortunately the error message that is returned is the same as if you mistyped the bind variable name! You can always check to see what bind variables Oracle thinks are available by using this code:

```python
cursor.prepare(sql)
print(cursor.bindnames())
```

If you do that in this case you will see an empty array returned.

**Comment by anthony-tuininga** [comment]
I have added code to produce a better error message. You will now see this error: "DPI-1059: bind variables are not supported in DDL statements".

**Comment by nisha235** [comment]
Thanks.

On 14 Feb 2018 7:36 am, "Anthony Tuininga" <notifications@github.com> wrote:

I have added code to produce a better error message. You will now see this
error: "DPI-1059: bind variables are not supported in DDL statements".

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/oracle/python-cx_Oracle/issues/130#issuecomment-365471925>,
or mute the thread
