### ISSUE TITLE
Enhancement:  Connection.defaultarraysize

### ISSUE THREAD

**Issue by alberto-dellera** [oracle/python-cx_Oracle#132]
I propose to add a new "defaultarraysize" property to Connection, whose value is used 
to initialize the arraysize of every Cursor instance returned by Connection.cursor().

That would be the analogous of JDBC's Connection.defaultRowPrefetch.

The main rationale is to enable us to increase the arraysize of cursors managed
internally by applications/libraries that accept only Connections as entry points; 
one notable example is Panda's DataFrame read_sql_query (http://bit.ly/2A6cJqN).

A second rationale is sheer convenience: setting arraysize for every Cursor
is more error-prone and tedious then setting it for the Connection only.

Increasing arraysize is of paramount importance in DWH/BI/Data Science environments, where reading
millions of rows is the norm, especially when accessing Cloud systems with "high" 
(tens of milliseconds) latency.  In these scenarios, using arraysize of 10,000 or even more 
is mandatory to avoid waiting "on the network" for literally hours.

Thanks!

**Comment by anthony-tuininga** [comment]
Thanks for the suggestion. We'll consider it. Another option which you can consider: using a custom Connection class such as what I show here. It could be enhanced to reference your proposed defaultarraysize attribute instead of hard-coding the value 5000. This may be sufficient to your purpose?

```python
class Connection(cx_Oracle.Connection):

    def cursor(self):
        cursor = super(Connection, self).cursor()
        cursor.arraysize = 5000
        return cursor
```

**Comment by alberto-dellera** [comment]
Thanks for your answer - a couple of further considerations:

a) I cannot simply "downcast" the instance returned by cx_Oracle.connect() to that custom Connection;
may you elaborate on your proposed solution ? 

My understanding is that you were suggesting the usual way to "override" a method in these scenarios, that is, to wrap the original instance and then delegate:

```
import cx_Oracle
import pandas as pd

class Connection(cx_Oracle.Connection):
    def __init__(self, wrapped_conn):
      self.wrapped_conn = wrapped_conn

    def cursor(self):
        cursor = self.wrapped_conn.cursor()
        cursor.arraysize = 5000
        return cursor

    # possibly, delegation for all other methods used by Pandas
    # maybe delegation for __getattr__() / __setattr__()

wrapped_conn = cx_Oracle.connect("dellera", "dellera", "ora12c")
conn = Connection(wrapped_conn)

# prints 5000
print(conn.cursor().arraysize)

df = pd.read_sql_query("select object_id from dba_objects", conn)
```

The code above works for read_sql_query()  in the current version of Pandas (0.22.0) and cx_Oracle(6.0.3), but the technique is a bit fragile - e.g. what if a future Pandas tries to access a (new?) cx_Oracle.Connection method that I haven't delegated ? 

I know that the wrapper class can be automatically written by some "tools" (e.g. wrapt), but that is starting to become a bit complex ... 

b) In my experience, the need to increase arraysize arises when stress testing, or worse in production,
or sometimes several years after, when the network latency/workload/database size increases. At that time, refactoring the application is usually not an easy (or even possible) option - but increasing the proposed defaultarraysize would be both an extremely easy and almost zero-risk solution.

**Comment by anthony-tuininga** [comment]
> a) I cannot simply "downcast" the instance returned by cx_Oracle.connect() to that custom Connection;
may you elaborate on your proposed solution ?

It is much simpler, I think! This should work for you:

```python
import cx_Oracle
import pandas as pd

class Connection(cx_Oracle.Connection):

    def cursor(self):
        cursor = super(Connection, self).cursor()
        cursor.arraysize = 5000
        return cursor

conn = Connection("dellera", "dellera", "ora12c")

# prints 5000
print(conn.cursor().arraysize)

df = pd.read_sql_query("select object_id from dba_objects", conn)
```

The subclassed connection has all of the same attributes and functions that the base class has  -- except for cursor() which has been overridden. So you don't have to worry about wrapping anything!

I'll still consider your suggested enhancement -- but this should do what you want for now!

**Comment by alberto-dellera** [comment]
Oh, I have checked and that works perfectly - I didn't know that you could instantiate Connection() directly; I believed that you should always use the cx_Oracle.connect() factory function.  Now it makes sense, thanks!

**Comment by laxmikanthvattamwar** [comment]
""" I am fetching employees data from hr schema using cx_Oracle module, what i have observed during the fetch is for extracting 10K records of .823MB , approx 30% of CPU, 35MB of RAM and 3-4Mbps for writing to a file was utilized. 

Can someone let me know if we can get the data from database with minimal usage of CPU & RAM. I mean when .823MB is been fetched not more than 1MB of RAM should be used.

Python version: 3.6.4
cx_Oracle version: 6.3
Oracle Version  11.2.0.2.0
"""
import cx_Oracle
import csv
import time
conn=cx_Oracle.connect('hr/hr@xe')
cur=conn.cursor()
cur.arraysize=10000
cur.execute('select * from employees where rownum<1000000')
def gen():
    while True:
        res=cur.fetchmany()
        if not res:
            break
        else:
            yield res
def writer(gen_data):
    filename = 'sample.csv'
    file = open(filename, 'w', newline='')
    fd = csv.writer(file, dialect='excel')
    for rec in gen_data:
        print('{} employee records and size: {} '.format(len(rec),rec.__sizeof__()))
        for i in rec:
            fd.writerow(i)
if __name__=='__main__':
    start=time.time()
    gen_data=gen()
    writer(gen_data)
    print(time.time()-start)

![image](https://user-images.githubusercontent.com/5056900/39873490-b680663c-5488-11e8-8063-6e52cd640e95.png)

**Comment by anthony-tuininga** [comment]
Your comment has nothing to do with the request to add a default array size to the connection object. Can you create a new issue? Before you do so, you may also wish to examine the amount of RAM a plain Python script takes, then with the cx_Oracle module imported, then with the connection established to the database. I think you'll note that there isn't that much memory being used!

**Comment by anthony-tuininga** [comment]
After considering it further I am going to close this enhancement request since a custom cursor can implement this easily enough. Feel free to re-open if you feel otherwise!

**Comment by anthony-tuininga** [comment]
Note that in the new module (python-oracledb) that you can now do this:

```
oracledb.defaults.arraysize = 5000
```

That will set the default array size for all cursors created from that point forward.
