### ISSUE TITLE
"Permission Denied" error when trying to view release notes for version 6.0b1

### ISSUE THREAD

**Issue by piotr-dobrogost** [oracle/python-cx_Oracle#133]
Link to release notes for version 6.0b1 (http://cx-oracle.readthedocs.io/en/6.0b1/releasenotes.html#version-6-0-beta-1-april-2017) on page https://github.com/oracle/python-cx_Oracle/releases results in *Permission Denied* error.

**Comment by anthony-tuininga** [comment]
Corrected. Thanks for pointing it out!

**Comment by piotr-dobrogost** [comment]
Thanks for fixing.
