### ISSUE TITLE
cx_Oracle 6.1. Using oracle wallet with SessionPool 

### ISSUE THREAD

**Issue by mill9r** [oracle/python-cx_Oracle#134]
I tried to use oracle wallet in my python script. 
   `con = cx_Oracle.connect(user='',password='',dsn="ORCL")`
it works well with oracle db 11g. 
**tnsnames.ora**
   `ORCL=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=host_address)(PORT=1521))      (CONNECT_DATA=(SERVICE_NAME=orcl)))`

For my application i need session pool with oracle wallet:
`cx_Oracle.SessionPool(dsn='ORCL', min=1, max=20, increment=1, threaded=True, externalauth=True, user='',password='')`
As a result  > `cx_Oracle.DatabaseError: ORA-01017: invalid username/password; logon denied`

I also tried to change **tnsnames.ora** and add **pooled**. 
`ORCL=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=10.6.92.153)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=orcl)(SERVER=POOLED)))`
As a result >  `cx_Oracle.DatabaseError: ORA-24429: External authentication is not supported in this mode.`

Is it possible to use SessionPool with oracle wallet?

**Comment by anthony-tuininga** [comment]
It should indeed be possible. I'll find out what the correct incantation is and get back to you!

**Comment by anthony-tuininga** [comment]
Ok. The only argument you are missing in your session pool creation is the "homogeneous=False" argument. If you add that, it works as expected. I agree that the error message is a little unhelpful, though!

**Comment by mill9r** [comment]
Thank you! It works well 
`cx_Oracle.SessionPool(dsn='ORCL', min=1, max=20, increment=1, threaded=True, externalauth=True,homogeneous=False,user='',password='')`
