### ISSUE TITLE
CX_ORACLE for Oracle 9i

### ISSUE THREAD

**Issue by amitbht27** [oracle/python-cx_Oracle#135]
*Delete irrelevant parts of this template.*

### For general questions:

Describe exactly what you did and what you want to happen.
I want to connect python to Oracle 9i, is that possible?

I am getting this error when trying to connect python with oracle 9i
DatabaseError: DPI-1049: symbol OCIClientVersion not found in OCI library

#### Answer the following questions:

1. What is your version of Python? Is it 32-bit or 64-bit?
Python 2.7 32 bit
2. What is your version of cx_Oracle?
cx_Oracle-6.1 32 bit
3. What is your version of the Oracle client (e.g. Instant Client)?  How was it
   installed?  Where is it installed?
Oracle 9i, installed in a local folder

4. What is your version of the Oracle Database?
Oracle 9i

5. What is your OS and version?
Windows 7

6. What compiler version did you use?  For example, with GCC, run
   `gcc --version`.

7. What environment variables did you set?  How *exactly* did you set them?
I set tns_admin,oracle_home, added path for instant_client10_1 at the beginning of path variable

8. What *exact* command caused the problem (e.g. what command did you try to
   install with)?  Who were you logged in as?
Logged in as local admin

9. What error(s) you are seeing?

================= RESTART: C:\Amit\Python\conn to oracle.py =================

Traceback (most recent call last):
  File "C:\Amit\Python\conn to oracle.py", line 3, in <module>
    cx_Oracle.clientversion()
DatabaseError: DPI-1049: symbol OCIClientVersion not found in OCI library

**Comment by anthony-tuininga** [comment]
The current versions of cx_Oracle do not support Oracle 9i *client*. You need to use Oracle 11.2 client and then you should be able to connect to an Oracle 9i *database*.

**Comment by amitbht27** [comment]
Okay, thanks I'll try and let you know

Regards,
Amit

**Comment by alfa0ne** [comment]
OCI 11.2 very well connects to 9i. Only precaution is the matching of bit version (32/64) of OCI with OS and it shall be first item in the PATH variable.

**Comment by anthony-tuininga** [comment]
Excellent. I'll close this, then.
