### ISSUE TITLE
cx_Oracle.DatabaseError:DPI-1002: invalid dpiStmt handle with threaded connection

### ISSUE THREAD

**Issue by ashwiniadiga** [oracle/python-cx_Oracle#136]
1. What is your version of Python? Is it 32-bit or 64-bit?
Python 3.6.2 on Mac 3.

2. What is your version of cx_Oracle?
cx_Oracle 6.1
3. What is your version of the Oracle client (e.g. Instant Client)?  How was it
   installed?  Where is it installed?
Installed in Applications/oracle.  sqlplus : 12.1 and basic oracle version.  lib Path set up on local user home directory

4. What is your version of the Oracle Database?
Oracle Database 12c Enterprise Edition Release 12.1.0.1.0 - 64bit Production
5. What is your OS and version?
Macos Sierra 10.12.6

6. What compiler version did you use?  For example, with GCC, run
   `gcc --version`.
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin16.7.0
7. What environment variables did you set?  How *exactly* did you set them?
PYTHONPATH path to home directory
8. What *exact* command caused the problem (e.g. what command did you try to
   install with)?  Who were you logged in as?

```python
import cx_Oracle
constring = 'user/pass@db' 
for i in range(7):
   
    con = cx_Oracle.connect(constring, threaded=True)
    cur = con.cursor()
    cur.callproc("dbms_output.enable")
    create_thread(cur)
 
def create_thread(cur)
   // Creates threads and calls execute_sql   passes cur as parameter

def execute_sql(cur)    
     fileOBJ = open(fileName, 'r')
     query = str(fileOBJ.read()) 
     fileParam = open(ParamName, 'r')
     paramlist = params = yaml.safe_load(fileParam)
     res = cur.execute(query, paramlist )
     status = cur.var(cx_Oracle.NUMBER)
     msg = cur.var(cx_Oracle.STRING)
     cur.callproc("dbms_output.get_line", (status, msg))
```

9. What error(s) you are seeing?
cx_Oracle.DatabaseError:DPI-1002: invalid dpiStmt handle with threaded connection mostly on 3rd or 4th thread created

**Comment by anthony-tuininga** [comment]
Can you perhaps update your example so that it can be run in another environment? In particular, what SQL are you executing and what parameters are being passed? Without that information it will be difficult to know if it is your configuration, some particular SQL/parameters or an unusual bug!

**Comment by ashwiniadiga** [comment]
Thanks for helping hand. I solved the problem. cursor was used across the threads. instead I changed the code to get cursor in each thread.  

con = cx_Oracle.connect(constring, threaded=True)
    
    
 
def create_thread(con)
   // Creates threads and calls execute_sql   passes cur as parameter

def execute_sql(con)    
 cur = con.cursor()
     fileOBJ = open(fileName, 'r')
     query = str(fileOBJ.read()) 
     fileParam = open(ParamName, 'r')
     paramlist = params = yaml.safe_load(fileParam)
     res = cur.execute(query, paramlist )
     status = cur.var(cx_Oracle.NUMBER)
     msg = cur.var(cx_Oracle.STRING)
     cur.callproc("dbms_output.get_line", (status, msg))
