### ISSUE TITLE
set search path for oracle libraries as option

### ISSUE THREAD

**Issue by christianhaessler** [oracle/python-cx_Oracle#137]
I try to build a simple "package" including all necessary depencies to get some information from our oracle (12.2) database on windows, linux, aix with python, cx_oracle and the oracle instantclient. 

Cause i need to run this on a lot of different servers where no oracle client is installed i try to create a file structure like this:
```
$ tree
.
├── get_environment.py
├── instantclient_12_2_linux.x64
│   ├── adrci
│   ├── BASIC_LITE_README
│   ├── genezi
│   ├── libclntshcore.so.12.1
│   ├── libclntsh.so.12.1
│   ├── libipc1.so
│   ├── libmql1.so
│   ├── libnnz12.so
│   ├── libocci.so.12.1
│   ├── libociicus.so
│   ├── libocijdbc12.so
│   ├── libons.so
│   ├── liboramysql12.so
│   ├── ojdbc8.jar
│   ├── uidrvci
│   └── xstreams.jar
```

As mentioned before i am going to run this on a lot (~2000) different Linux Servers without a oracle client installed and it is not possible to set the LD_LIBRARY_PATH on every server.

My Idea was to patch the libclntsh.so to search the libraries local as described here:
https://gms.tf/ld_library_path-considered-harmful.html what worked:

Before patching with LD_LIBRARY_PATH=./
```
$ LD_LIBRARY_PATH=./ ldd libclntsh.so.12.1
        linux-vdso.so.1 (0x00007ffd6bf38000)
        libmql1.so => ./libmql1.so (0x00007f80f60c1000)
        libipc1.so => ./libipc1.so (0x00007f80f5c8e000)
        libnnz12.so => ./libnnz12.so (0x00007f80f5545000)
        libons.so => ./libons.so (0x00007f80f52f7000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f80f50f3000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f80f4df6000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f80f4bd9000)
        libnsl.so.1 => /lib64/libnsl.so.1 (0x00007f80f49c1000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f80f47b9000)
        libaio.so.1 => /lib64/libaio.so.1 (0x00007f80f45b7000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f80f43a0000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f80f3ffd000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f80f9ddd000)
        libclntshcore.so.12.1 => ./libclntshcore.so.12.1 (0x00007f80f3a2f000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f80f3818000)
```

Before patching without LD_LIBRARY_PATH set
```
$ ldd libclntsh.so.12.1
        linux-vdso.so.1 (0x00007fff7e6d9000)
        libmql1.so => not found
        libipc1.so => not found
        libnnz12.so => not found
        libons.so => not found
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f06507e0000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f06504e3000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f06502c6000)
        libnsl.so.1 => /lib64/libnsl.so.1 (0x00007f06500ae000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f064fea6000)
        libaio.so.1 => /lib64/libaio.so.1 (0x00007f064fca4000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f064fa8d000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f064f6ea000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f0654489000)
        libclntshcore.so.12.1 => not found
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f064f4d3000)
```

After patching with:
```
patchelf --set-rpath '$ORIGIN' libclntsh.so.11.1
```

```
get_env$ ldd libclntsh.so.12.1
        linux-vdso.so.1 (0x00007fffb7cc7000)
        libmql1.so => /home/my_user/get_env/instantclient_12_2_linux.x64/./libmql1.so (0x00007f48678da000)
        libipc1.so => /home/my_user/get_env/instantclient_12_2_linux.x64/./libipc1.so (0x00007f48674a7000)
        libnnz12.so => /home/my_user/get_env/instantclient_12_2_linux.x64/./libnnz12.so (0x00007f4866d5e000)
        libons.so => /home/my_user/get_env/instantclient_12_2_linux.x64/./libons.so (0x00007f4866b10000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f486690c000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f486660f000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f48663f2000)
        libnsl.so.1 => /lib64/libnsl.so.1 (0x00007f48661da000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f4865fd2000)
        libaio.so.1 => /lib64/libaio.so.1 (0x00007f4865dd0000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f4865bb9000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f4865816000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f486b669000)
        libclntshcore.so.12.1 => /home/my_user/get_env/instantclient_12_2_linux.x64/./libclntshcore.so.12.1 (0x00007f4865248000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f4865031000)
```

Unfortunally i am not able to tell cx_oracle to search the libclntsh.so in this directory: `instantclient_12_2_linux.x64` without setting the LD_LIBRARY_PATH.

```
$ python get_environment.py
LD_LIBRARY_PATH: not set
Traceback (most recent call last):
  File "get_environment.py", line 110, in <module>
    main()
  File "get_environment.py", line 71, in main
    connection = cx_Oracle.connect(db_user, db_pw, db_server + ":" + db_port + "/" + db_sid)
cx_Oracle.DatabaseError: DPI-1047: 64-bit Oracle Client library cannot be loaded: "libclntsh.so: cannot open shared object file: No such file or directory". See https://oracle.github.io/odpi/doc/installation.html#linux for help
```

Can you help to set this directory while loading cx_Oracle?

#### Answer the following questions:
1. What is your version of Python? Is it 32-bit or 64-bit?
```
$ python --version
Python 2.7.13
$ python -c 'import struct;print struct.calcsize("P") * 8'
64
$ python3 --version
Python 3.4.6
$ python3 -c 'import struct;print(struct.calcsize("P") * 8)'
64
```

2. What is your version of cx_Oracle?
```
$ pip list | grep Oracle
cx-Oracle (6.1)
$ pip3 list | grep Oracle
cx-Oracle (6.1)
```

3. What is your version of the Oracle client (e.g. Instant Client)?  How was it
   installed?  Where is it installed?
	
   Instant Client 12_2 64-bit
   Unpacked to a subdirectory called: `instantclient_12_2_linux.x64`

4. What is your version of the Oracle Database?
Oracle 12.2.0.1

5. What is your OS and version?
SLES 12 SP2

6. What compiler version did you use?  For example, with GCC, run
```
$ gcc --version
gcc (SUSE Linux) 4.8.5
```

7. What environment variables did you set?  How *exactly* did you set them?
I try not to use environment variables at all (this is the reason for this feature request)

8. What *exact* command caused the problem (e.g. what command did you try to
   install with)?  Who were you logged in as?
```
$ python get_environment.py
```

9. What error(s) you are seeing?
```
$ python get_environment.py
LD_LIBRARY_PATH: not set
Traceback (most recent call last):
  File "get_environment.py", line 110, in <module>
    main()
  File "get_environment.py", line 71, in main
    connection = cx_Oracle.connect(db_user, db_pw, db_server + ":" + db_port + "/" + db_sid)
cx_Oracle.DatabaseError: DPI-1047: 64-bit Oracle Client library cannot be loaded: "libclntsh.so: cannot open shared object file: No such file or directory". See https://oracle.github.io/odpi/doc/installation.html#linux for help
```

**Comment by anthony-tuininga** [comment]
Have you considered using a configuration file for ldconfig? As explained here: https://oracle.github.io/odpi/doc/installation.html#linux? Note item 4 in the list for instant client zip installation. That bypasses LD_LIBRARY_PATH. You also won't need to patch the instant client libraries if you do that.

**Comment by christianhaessler** [comment]
Thanks for reply. I have several systems where i would like to use this script. Some allready have an oracle client installed and i would to change as less as possible on system configuration.

**Comment by anthony-tuininga** [comment]
Understood. The only other way you can deal with it is to set RPATH on cx_Oracle.so *and* patch the libclntsh.so to set RPATH to $ORIGIN as you were already planning to do. That should do it for you. I've tried that myself and it works as expected, even if it isn't exactly a supported approach!

**Comment by jmcp** [comment]
When building cx_Oracle (prior to v6) for Solaris we set the RPATH to search for system-delivered Instant Client binaries (they're found in /usr/oracle/instantclient/$version). 

For v6 of cx_Oracle, we don't have to worry about it, because it's linked against libodpic.so.

We also burn the correct RPATH ($ORIGIN) into the Instant Client libraries themselves.

    $ elfdump -d /usr/lib/64/libodpic.so 2>&1 |grep RPATH
         [5]  RPATH           0x2f5a    $ORIGIN/../../oracle/instantclient/12.2/lib/amd64:$ORIGIN/../../oracle/instantclient/12.1/lib/amd64
    $ elfdump -d /usr/oracle/instantclient/12.2/lib/64/libclntsh.so |grep PATH
         [22]  RUNPATH      0x6d3c5    $ORIGIN


Incidentally, the blog post you mention is one of the best I've seen on the topic.

**Comment by christianhaessler** [comment]
Thanks for your help. After patching cx_Oracle.so it worked.
