### ISSUE TITLE
Unable to connect to the database！！

### ISSUE THREAD

**Issue by HelloCoode** [oracle/python-cx_Oracle#141]
My PL/SQL Developer is able to connect to the remote database,but the python script is unable to connect to the database with cx_Oracle！！
--------------------------------------------------------

Errors on Console:
cx_Oracle version: 6.0rc1
Oracle client version: (12, 1, 0, 2, 0)
Traceback (most recent call last):
  File "C:/Users/K.O/PycharmProjects/sams/sams_db/sams_db.py", line 32, in <module>
    connection=cx_Oracle.connect(user, password, dsn)
cx_Oracle.OperationalError: ORA-01034: ORACLE not available
ORA-27101: shared memory realm does not exist
Linux-x86_64 Error: 2: No such file or directory
Additional information: 3640
Additional information: 734153415
进程 ID: 0
会话 ID: 0 序列号: 0
Process finished with exit code 1

--------------------------------------------------------
Python version:
Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)] on win32

--------------------------------------------------------
db version:
Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production

--------------------------------------------------------
PL/SQL Developer version:
  Version 12.0.1.1814  (64 bit)
  01.226959 - Unlimited user license

--------------------------------------------------------
cx_Oracle version:
cx_Oracle-6.0rc1-cp36-cp36m-win_amd64.whl

**Comment by cjbj** [comment]
You are probably connecting to two different DB services.   Check with your DBA for the correct connect string to use.

**Comment by HelloCoode** [comment]
Thanks for your answer，the connect string in tnsnames.ora file is, i just masked the host string :
```
SAMSTEST =
  (DESCRIPTION =
    (ADDRESS_LIST =
      (ADDRESS = (PROTOCOL = TCP)(HOST = 10.1.xx.xxx)(PORT = 1521))
    )
    (CONNECT_DATA =
      (SERVICE_NAME = samstst)
    )
  ) 
```
--------------------------------------------------------------
My script is
```
# -*- coding:utf-8 -*-
import cx_Oracle
print("cx_Oracle version:",cx_Oracle.version)
print("Oracle client version:",cx_Oracle.clientversion())

host='10.1.xx.xxx'
user='sams'
password='sams'
port='1521'
db='samstst'

dsn=cx_Oracle.makedsn(host, port, db)
connection=cx_Oracle.connect(user, password, dsn)
cursor = connection.cursor()
print("Oracle database version:",connection.version)
print("db dsn:",connection.dsn)
cursor.close()
connection.close()
```
 ---------------------------------------------------------------
And i can use user='sams' password='sams' to log PL/SQL Developer succesfully.

**Comment by cjbj** [comment]
> ORA-01034: ORACLE not available
> ORA-27101: shared memory realm does not exist

Means you are trying to connect to something that doesn't exist.

Check your `makedsn()` usage.   See https://github.com/oracle/python-cx_Oracle/issues/105#issuecomment-340599699

**Comment by HelloCoode** [comment]
Thank you.
it works on 
`connection = cx_Oracle.connect("sams/sams@10.1.xx.xxx:1521/samstst")`
but not works on `makedsn()` 
Strangely，the other remote data base works on both `conn = cx_Oracle.connect("User/Pass@IP:Port/SID")` and `makedsn()`

**Comment by cjbj** [comment]
Let me interpret https://github.com/oracle/python-cx_Oracle/issues/105#issuecomment-340599699 for you:

`dsn = cx_Oracle.makedsn("10.1.xx.xxx",1521,service_name="samstst")`

You wrote:

> `"User/Pass@IP:Port/SID")`

That's technically incorrect, since you can only use service names not SIDs in the Easy Connect syntax.

Maybe your other DB uses the same name for the SID and servicename.

There's some info in the Node.js node-oracledb manual https://github.com/oracle/node-oracledb/blob/master/doc/api.md#connectionstrings that you may be able to glean info from.
