### ISSUE TITLE
DPI-1047: 32-bit Oracle Client library cannot be loaded - Loading on Virtual Machine

### ISSUE THREAD

**Issue by emarler7** [oracle/python-cx_Oracle#143]
1. What is your version of Python? Is it 32-bit or 64-bit?
- 32-bit

2. What is your version of cx_Oracle?
- 6.1

3. What is your version of the Oracle client (e.g. Instant Client)?  How was it
   installed?  Where is it installed?
- 12.2.0.1.0 - Unzipped to C:\Python27\oracle

4. What is your version of the Oracle Database?
- 12.1.0.2.0

5. What is your OS and version?
- Windows Server 2016 - Virtual Machine

7. What environment variables did you set?  How *exactly* did you set them?
- Added C:\Python27\oracle to "User Variables" (C:\Python27\Scripts;C:\Python27\;C:\Python27\oracle;)

8. What *exact* command caused the problem (e.g. what command did you try to
   install with)?  Who were you logged in as?
- cx_Oracle.connect creates the problem.

9. What error(s) you are seeing?
- DatabaseError: DPI-1047: 32-bit Oracle Client library cannot be loaded: "The specified module could not be found". See https://oracle.github.io/odpi/doc/installation.html#windows for help

I have been trying to fix this for hours, but to no prevail.

I have this code operating really well on a Windows 10 machine, but my virtual machine is not working.

Any ideas?

--Eric

**Comment by anthony-tuininga** [comment]
Did you check the link referenced in the error message? Specifically, do you have 32-bit Oracle Client libraries and do you have the correct VS redistributable installed?

**Comment by emarler7** [comment]
Yes, I have read everything I can on this site and stackoverflow. I have installed vc-redist.x86 AND VC_redist.x64 (Downloaded from here: https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) to test if either worked, but to no prevail.

I have installed the 32-bit Oracle Client libraries as well. I even tried using the same exact settings I have setup on both machines and it still will not work on my virtual machine with Windows Server 2016 on it.

**Comment by anthony-tuininga** [comment]
Which one did you download? You need to have VS 2013 to support Oracle 12.2 client.

**Comment by emarler7** [comment]
I had downloaded the newest (2017). I'll try the 2013 version and report back.

**Comment by emarler7** [comment]
Do you accept hugs as a form of appreciation? 

It totally worked after smashing my face on the keyboard for hours.

I appreciate it a lot.

**Comment by cjbj** [comment]
@emarler7 is there anything in the installation doc http://cx-oracle.readthedocs.io/en/latest/installation.html#installing-cx-oracle-on-windows that can be improved?

**Comment by emarler7** [comment]
Alot of the issue was my lack of knowledge with python in general. 

If you want to add a portion identifying the correct redistributals that go along with the Oracle versions, you can. 

But really its just a lack of my personal knowledge and pure oversight.

**Comment by cjbj** [comment]
@emarler7 there already is a section on the redistributables, see step 5 :)  Maybe this should be moved up and be made more definite?

**Comment by emarler7** [comment]
I saw it. Thats how I knew to install them. I just wasnt aware that I needed VS 2013 redistributals. I was using the VS 2017 redistributals and it wasnt working. I wasnt aware that the redistributals were specific on the version of Oracle.

**Comment by cjbj** [comment]
@emarler7 I'll try and improve the wording.  Thanks for your input.
