### ISSUE TITLE
cx_Oracle, Windows 10 - Unable to acquire Oracle environment handle

### ISSUE THREAD

**Issue by damjankuburovic** [oracle/python-cx_Oracle#144]
### For general questions:

I have a very specific issue and I have no more ideas :(

I'm using python embedded (version 2.6.9, 32-bit) in my application, to be able to run python test scripts.

I'm running 15-20 python test scripts and directly from last test script I'm trying to write data in Oracle database which is running on remote server (virtual machine in Linux).

To be able to access to Oracle database, I'm using cx_Oracle python module and Instant client.
 
 I have multiple computers (each with the same Application and embedded python) in the same network, but with different OS.
Computers running on Windows 8.1 Pro 64-bit work correctly.
Computers running on Windows 10 Pro, 64-bit sometimes work correctly and sometimes return error:
"Unable to acquire Oracle environment handle"
First execution after Windows restart usually return error. After a few tries start working correctly. And than occasionally fails.

It looks to me like I need to do some additional steps to configure environment for Windows 10, but couldn't find any working solution until now.

I set the PATH variable pointing to the folder where instant client is stored.
Oracle server version is 11_2_4.
Oracle instant client version: 11_2
cx_Oracle version: 5.0.2
Python version: 2.6.9

Additionally, I tried also combination:
Oracle instant client version: 12_1
cx_Oracle version: 5.0.4
, but without success.

#### Answer the following questions:

1. What is your version of Python? Is it 32-bit or 64-bit?

- 2.6.9

2. What is your version of cx_Oracle?

- 5.0.2 (5.0.4, same behavior)

3. What is your version of the Oracle client (e.g. Instant Client)?  How was it
   installed?  Where is it installed?

- Instant client 11_2, 32-bit (tried also Instant client 12_2, 32-bit)

- Zipped version unpacked on C partition

4. What is your version of the Oracle Database?

- 11_2_4

5. What is your OS and version?

- Windows 10 Pro

6. What compiler version did you use?  For example, with GCC, run
   `gcc --version`.

7. What environment variables did you set?  How *exactly* did you set them?

- Only PATH variable: C:\Oracle\instantclient_11_2

- I set it manually in System variables

8. What *exact* command caused the problem (e.g. what command did you try to
   install with)?  Who were you logged in as?

- connection = cx_Oracle.connect(DATABASE_USER + "/" + DATABASE_PASSWORD + "@" + DATABASE_HOST + "/" + DATABASE_NAME)

9. What error(s) you are seeing?

- "Unable to acquire Oracle environment handle"

**Comment by anthony-tuininga** [comment]
Are you able to test with cx_Oracle 6.1? If so, you might be able to find out a more useful error message. Version 6 added the ability to look up the error message instead of simply returning "unable to acquire Oracle environment handle".

**Comment by damjankuburovic** [comment]
I tried that, but it looks like cx_Oracle 6.1 is not compatible with Python 2.6.9. It would be really hard to move to latest python version at this point :(

It looks like issue with environment configuration, but based on what I found online I did everything correctly.
I was wondering if there is some additional configuration for Windows 10 Pro?

By the way, thanks for your quick answer!

**Comment by anthony-tuininga** [comment]
I have used cx_Oracle 6.1 with Python 2.6. Wheels are not created for Python 2.6 and you'll have to compile it yourself, but it should in fact work. Wheels are created for Python 2.7, too, so you don't have to go all the way to Python 3.6. :-)

There should be no additional configuration required for Windows 10 Pro. I would get cx_Oracle 6.1 compiled and see what it says -- a better error message is going to go a long way to solving the problem, I think!

**Comment by damjankuburovic** [comment]
I follow proposed steps. I build cx_Oracle 6.1 with python 2.6.

And you were right, I got different message this time:
"DPI-1050: Oracle Client library must be at version 11.2 or higher"

Even if I'm using 12_1 instant client, I got message from above.
I tried also instant client versions 11_2 and 12_2, but the message is the same.

By the way, this message pop-ups randomly, like previous one. So, usually everything is correct and all steps are executed without error, but still sometimes I get the message from above.

Any ideas?

**Comment by cjbj** [comment]
Are you sure you have a 'clean' machine and don't have clashes with different versions of Oracle libraries?  What's in your PATH?

**Comment by cjbj** [comment]
If you're compiling it yourself, you could debug through the ODPI-C layer and see what it is doing.
For example https://github.com/oracle/odpi/blob/master/src/dpiOci.c#L1539-L1542 loads the Oracle client library and then
https://github.com/oracle/odpi/blob/master/src/dpiOci.c#L1579 calls https://github.com/oracle/odpi/blob/master/src/dpiOci.c#L1598 to check the version number.

**Comment by damjankuburovic** [comment]
My machine should be 'clean'. I install everything from scratch, starting with Windows install.

I have only one version of Instant client on the PC. All I did was just copy files on C partition and add PATH in System variables. Please find attached pictures:

![instant client](https://user-images.githubusercontent.com/35232384/36590446-fe39d4d0-188e-11e8-86ae-ab8365e62bf7.png)
![path](https://user-images.githubusercontent.com/35232384/36590447-fe52b374-188e-11e8-8490-e79f02494219.png)

I will try to debug like yuo suggested.

**Comment by damjankuburovic** [comment]
I checked version number as you proposed.

In function https://github.com/oracle/odpi/blob/master/src/dpiOci.c#L1598
I get wrong values for dpiOciLibVersionInfo.versionNum and dpiOciLibVersionInfo.releaseNum (https://github.com/oracle/odpi/blob/d607062547bcd634fa00563cbfeeb2734c1b3224/src/dpiOci.c#L1615-L1617).

Log shows that:
versionNum = 0
releaseNum = 0

Do you have any idea what I'm doing wrong?
Thanks for support.

**Comment by cjbj** [comment]
Long shot thoughts are (i) not having the correct VS redistributables (ii) windows permission issues (iii) update windows to the latest patch level (iv) something in that java directory clashing (try putting Instant Client first in PATH)

**Comment by anthony-tuininga** [comment]
Do a search of your machine for OCI.DLL. Sometimes it gets shoved in C:\Windows\System32 for example!

**Comment by damjankuburovic** [comment]
@cjbj: I already tried:
(i) I install multiple versions of VS redistributable. I believe that it can't be conflicts between versions. Am I correct?
![image](https://user-images.githubusercontent.com/35232384/36738380-a8b417bc-1bdd-11e8-9059-ec1a54866eca.png)

(ii) There is only one administrator user on Windows. Is there any settings where I should configure some special permissions even for admins?

(iii) Already did this, before I open this issue on github. I didn't get anything.
(iv) I tried this already. Additionally, I removed java path from system env. Still getting issue sometimes.

@anthony-tuininga: I did this. There is no such a file on different location
![image](https://user-images.githubusercontent.com/35232384/36738732-8b6281ac-1bde-11e8-88ba-70b78bd76d5b.png)

I'm thinking of downgrading Windows to Windows 8, as other PCs (with Windows 8 Pro) in the same network are working wihtout this issue. 
What do you guys think about that idea? Is there anything else I can try before this step?

**Comment by cjbj** [comment]
Can you try connecting to the DB using SQL*Plus?

**Comment by damjankuburovic** [comment]
I would like just to point again, that I'm not getting problem every time, but once in a while.

I tried using SQL*Plus.

In both cases (when problem happens and when there is no problem) I'm not getting any error message.

I got this when error happened (the same as without error):
![sql plus1](https://user-images.githubusercontent.com/35232384/36804557-3b5b3392-1cbb-11e8-92c4-98dbe2eedcd8.jpg)

I didn't mentioned before that I'm also importing opencv library. Is it possible that we have some collision when importing both libs?

**Comment by anthony-tuininga** [comment]
How frequently does the error occur? How do you know there is a problem if you're not getting any error message? Can you try your code without opencv? Sounds like you're going to have to diagnose this issue by reducing it until the problem goes away. I try to avoid using Windows as diagnosing issues on that platform is painful...but its not impossible. Good luck!

**Comment by cjbj** [comment]
It may be time to check your hardware, too.

**Comment by anthony-tuininga** [comment]
Closing since lack of activity assumes the issue has been resolved.
