### ISSUE TITLE
Python crash selecting ROWID

### ISSUE THREAD

**Issue by shoyu63** [oracle/python-cx_Oracle#145]
Python 2.7.14 or 3.6.4 (64-bits) conda distrib
Windows 7 or Windows 2012
cx_Oracle 6.1 (pip install -U cx_Oracle).
Instant Client version 12.1.0.1 or 12.2.0.1
Oracle version 12.1.0.2.0

cx_Oracle worked perfectly (thank you) for years and we had not this problem with cx_Oracle <= 5.3.

Here, c is a Cursor, tra_posi is a big table, tra_posi.num_int_pos is the key. hep_params is a table with 11 rows.
If I execute these instructions :

```python
c.execute("SELECT p.num_int_pos, p.rowid FROM tra_posi p, hep_params x "
               " WHERE     p.num_int_pos=12345")
for rec in c:
    print(rec)
```
Two lines are printed and, then, Python **crashes**.
(12345, 'AAAZgMAAAAAKyTtAAM')
(12345, 'AAAZgMAAAAAKyTtAAM')

If, in a second example, I replace p.rowid by x.rowid, everything is OK :
```python
c.execute("SELECT p.num_int_pos, x.rowid FROM tra_posi p, hep_params x "
               " WHERE     p.num_int_pos=12345")
for rec in c:
    print(rec)
```
We got :
(12345, 'AAAZWIAAAAAJOHrAAH')
(12345, 'AAAZWIAAAAAJOHrAAG')
(12345, 'AAAZWIAAAAAJOHrAAA')
(12345, 'AAAZWIAAAAAJOHrAAI')
(12345, 'AAAZWIAAAAAJOHrAAJ')
(12345, 'AAAZWIAAAAAJOHrAAK')
(12345, 'AAAZWIAAAAAJOHrAAB')
(12345, 'AAAZWIAAAAAJOHrAAC')
(12345, 'AAAZWIAAAAAJOHrAAD')
(12345, 'AAAZWIAAAAAJOHrAAE')
(12345, 'AAAZWIAAAAAJOHrAAF')

For me, the difference is that in the second example, rowid is always different, not in the first one.

Cheers,

Stéphane.

**Comment by anthony-tuininga** [comment]
This may be a known issue. If you set the environment variable ORA_OCI_NO_OPTIMIZED_FETCH to the value 1 and rerun your test, does it work for you?

**Comment by shoyu63** [comment]
Hello,
Thank you for the answer.
With ORA_OCI_NO_OPTIMIZED_FETCH set to 1, I have no more crash.
Thanks again for all.
Best wishes.
Stéphane.
