### ISSUE TITLE
Getting en error while using cx_Oracle in Python. 

### ISSUE THREAD

**Issue by vp393001** [oracle/python-cx_Oracle#148]
1. What is your version of Python? Is it 32-bit or 64-bit? - 32 bit

2. What is your version of cx_Oracle?- 6.1

3. What is your OS and version? windows 10

4. What error(s) you are seeing?

> E:\JetBrains\Pycharm\tmp\venv\Scripts\python.exe E:/JetBrains/Pycharm/tmp/temp.py
> Traceback (most recent call last):
>   File "E:/JetBrains/Pycharm/tmp/temp.py", line 2, in <module>
>     con=cx_Oracle.connect('system/Oracle_1@localhost/xe')
> cx_Oracle.DatabaseError: DPI-1047: 32-bit Oracle Client library cannot be loaded: "E:\app\OracleHomeUser1\product\12.2.0\dbhome_1\bin\oci.dll is not the correct architecture". See https://oracle.github.io/odpi/doc/installation.html#windows for help
> 
> Process finished with exit code 1
>

**Comment by cjbj** [comment]
Sounds like you have 64-bit database but a 32-bit python.  

Try installing 32-bit Oracle Instant Client from http://www.oracle.com/technetwork/topics/winsoft-085727.html.  You'll need the noted VS Redistributable, and will need to have the Instant Client directory in PATH (before other Oracle directories) when you run Python.  Make sure that changing PATH doesn't stuff up any other tools using the Oracle DB libraries.

**Comment by anthony-tuininga** [comment]
@vp393001, in our conversation via e-mail you indicated that you were able to solve this issue by installing 64-bit Python. The other way is the one that Chris mentioned. Since you've already resolved the issue I'll close this.
