### ISSUE TITLE
Install from source

### ISSUE THREAD

**Issue by belast** [oracle/python-cx_Oracle#149]
*Delete irrelevant parts of this template.*

### For general questions:

Describe exactly what you did and what you want to happen.
Use the questions at the bottom of this template as a guide.

Use Markdown syntax, particularly for code blocks: see https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

### For security issues:

See https://www.oracle.com/support/assurance/vulnerability-remediation/reporting-security-vulnerabilities.html for how to report security issues.

### For installation issues:

Use a gist for screen output and logs: see https://gist.github.com/
**Do not paste long output into this issue**

Review the install instructions at
https://github.com/oracle/python-cx_Oracle#installation

Review your output and logs.  **Google any errors**

#### Answer the following questions:

1. What is your version of Python? Is it 32-bit or 64-bit?
64-bit
2. What is your version of cx_Oracle?
cx_Oracle-6.1

3. What is your version of the Oracle client (e.g. Instant Client)?  How was it
   installed?  Where is it installed?
Oracle 12c
4. What is your version of the Oracle Database?
12.1.0.2
5. What is your OS and version?
RedHat 7.4

6. What compiler version did you use?  For example, with GCC, run
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16

7. What environment variables did you set?  How *exactly* did you set them?
. oraenv

8. What *exact* command caused the problem (e.g. what command did you try to
   install with)?  Who were you logged in as?
I have installed cx_Oracle from source code , I have installed as root. The module works perfect as root user, If I run as oracle user I do get this error:

  File "build/bdist.linux-x86_64/egg/cx_Oracle.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/cx_Oracle.py", line 6, in __bootstrap__
ImportError: /home/oracle/.python-eggs/cx_Oracle-6.1-py2.7-linux-x86_64.egg-tmp/cx_Oracle.so: failed to map segment from shared object: Operation not permitted

9. What error(s) you are seeing?
  File "build/bdist.linux-x86_64/egg/cx_Oracle.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/cx_Oracle.py", line 6, in __bootstrap__
ImportError: /home/oracle/.python-eggs/cx_Oracle-6.1-py2.7-linux-x86_64.egg-tmp/cx_Oracle.so: failed to map segment from shared object: Operation not permitted

**Comment by anthony-tuininga** [comment]
That looks like a permissions issue. Make sure that the user that is going to execute your Python script has execute permissions on cx_Oracle.so!

**Comment by belast** [comment]
It seems to have the correct permissions.

oracle@vm-ttdb-90:~/python$  ls -l /usr/lib64/python2.7/site-packages/cx_Oracle-6.1/build/lib.linux-x86_64-2.7/cx_Oracle.so
-rwxrwxrwx 1 root root 1115024 Feb 22 14:42 /usr/lib64/python2.7/site-packages/cx_Oracle-6.1/build/lib.linux-x86_64-2.7/cx_Oracle.so

oracle@vm-ttdb-90:~/python$ ls -l /home/oracle/.python-eggs/cx_Oracle-6.1-py2.7-linux-x86_64.egg-tmp/cx_Oracle.so
-rwxr-xr-x 1 oracle oinstall 1115024 Feb 22 14:42 /home/oracle/.python-eggs/cx_Oracle-6.1-py2.7-linux-x86_64.egg-tmp/cx_Oracle.so

**Comment by cjbj** [comment]
Keep digging!  You have all the information and all we know is the error message you are getting.  We don't even know what commands you ran to install.

**Comment by belast** [comment]
Sure will try. 
Installed as root with the following commands, no errors:
python setup.py build
python setup.py install

**Comment by belast** [comment]
Hi, 
It seems like CA software does restrict that python-eggs are run form home catalog of oracle user. How can I tell python to use a different directory for hidden (.python-eggs)

ImportError: /home/oracle/.python-eggs/cx_Oracle-6.1-py2.7-linux-x86_64.egg-tmp/cx_Oracle.so: failed to map segment from shared object: Operation not permitted

**Comment by anthony-tuininga** [comment]
Can you run ldd on the shared library (cx_Oracle.so)? That may enlighten you further.

Also, I would suggest removing cx_Oracle.so from .python-eggs and instead running the command ``python -m pip install cx_Oracle`` instead.

**Comment by belast** [comment]
I did as you suggetsted , worked perfect. Thanks

**Comment by anthony-tuininga** [comment]
You're welcome. I presume you are satisfied, then. If not, let us know!
