### ISSUE TITLE
cx_Oracle.DatabaseError: ORA-12537: TNS:connection closed

### ISSUE THREAD

**Issue by laozi2** [oracle/python-cx_Oracle#152]
Hi,
When I access oracle service of aliyun (https://www.aliyun.com/rds_for_ppas) , by this code: 
`conn = cx_Oracle.connect('myusername','mypassword','aliyunxxxxxxxxxx.ppas.rds.aliyuncs.com:3433/db_xiaohe')`
but always failed:
`cx_Oracle.DatabaseError: ORA-12537: TNS:connection closed`,
and tcpdump shows:
> ..........(DESCR
IPTION=(CONNECT_
DATA=(SERVICE_NA
ME=db_xiaohe)(CI
D=(PROGRAM=pytho
n3)**(HOST=localho
st.localdomain)(
USER=root)**))(ADD
RESS=(PROTOCOL=T
CP)(HOST=119.30.
195.23)(PORT=343
3)))

it means that cx_Oracle lib never pass my username to server?
PS: I use command 'psql' to connenct will be success.

Is there any tips for me to fix this problem? thx

**Comment by cjbj** [comment]
First thing to try is to use SQL*Plus with exactly the same connection string, from exactly the same terminal as you experience the problem with cx_Oracle.

**Comment by laozi2** [comment]
ok, thanks.   there is something wrong with my environment
