### ISSUE TITLE
missin cxoModule.h

### ISSUE THREAD

**Issue by ghsalem** [oracle/python-cx_Oracle#155]
I tried to upgrade my 6.1 version to 6.2, on macOs high sierra. Got an error that cxoModule.h File not found upon compilation. When I downloaded the tar.gz from the Python repo, and unzipped it, I found that the file is missing in the src directory. When I got it from github, and put it there, setup.py install worked with no problem
So it seems the tarball need to be rebuilt.

**Comment by FrankEgan** [comment]
Same experience.

**Comment by anthony-tuininga** [comment]
Yes, a new file was added with a different extension....so MANIFEST.in needs to be adjusted. I'll take care of that and upload a new source package.

**Comment by anthony-tuininga** [comment]
MANIFEST.in has been adjusted. And a new source package has been uploaded so all should be well now. Apologies for the inconvenience!
