### ISSUE TITLE
cx_Oracle 6.2 pip install --upgrade issue on Windows

### ISSUE THREAD

**Issue by matthewtylerwood** [oracle/python-cx_Oracle#156]
### For installation issues:

I went to upgrade my cx_Oracle version from 6.1 to 6.2 today, and instead of downloading the wheel for python 36 64 bit on Windows, it downloaded the source.

After the failed installation, I was able to force installation by doing:
```
pip install --upgrade cx_Oracle==6.2
```
The correct wheel was downloaded installed successfully.  I think this might happen because of the extra "-2" in the source package name on pypi.  So pip believes the newest version is 6.2-2 and no wheel exists for the environment?

#### Answer the following questions:

1. What is your version of Python? Is it 32-bit or 64-bit?
64-bit

2. What is your version of cx_Oracle?
6.1

3. What is your version of the Oracle client (e.g. Instant Client)?  How was it
   installed?  Where is it installed?
12.1

5. What is your OS and version?
Windows Server 2012 R2

8. What *exact* command caused the problem (e.g. what command did you try to
   install with)?  Who were you logged in as?
pip install --upgrade cx_Oracle

9. What error(s) you are seeing?
Downloads source instead of wheel file.

**Comment by anthony-tuininga** [comment]
Someone else reported this issue as well. And it may indeed be due to the addition of the -2 for the new source package, although for some reason pip -v -v -v reports that none of the binary wheels are "for this Python", which seems strange. I am going to release 6.2.1 instead with a properly built source package (without the -2) and see if that resolves the issue.

**Comment by anthony-tuininga** [comment]
I just created the 6.2.1 release and my testing shows that it works as expected. Can you confirm?

**Comment by matthewtylerwood** [comment]
I can confirm this corrects my issue.  I tried an upgrade and a fresh install, and both download the correct wheel package and install correctly.

**Comment by anthony-tuininga** [comment]
Excellent. Thanks for following up. I'll close this now.
