### ISSUE TITLE
cx_oracle Database Error during cron job

### ISSUE THREAD

**Issue by prelator2** [oracle/python-cx_Oracle#160]
### For general questions:
I have a script that pulls information from an Oracle database. The code runs perfectly when I run it manually but when it is kicked off via a cron job, I get this error: 

**cx_Oracle.DatabaseError: DPI-1047: 64-bit Oracle Client library cannot be loaded: "libclntsh.so: cannot open shared object file: No such file or directory". See https://oracle.github.io/odpi/doc/installation.html#linux**

In my .bash_profile I have these established:
**export LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib
export ORACLE_HOME=/usr/lib/oracle/12.1/client64**

In the code itself I have it identify the os.environ.keys() and add the LD_LIBRARY_PATH and ORACLE_HOME if it is not there, which it is not.

**** The code that adds it ****
if 'ORACLE_HOME' not in os.environ.keys():
    print('error - home')
    os.environ['ORACLE_HOME'] = '/usr/lib/oracle/12.1/client64'
    os.putenv('ORACLE_HOME', "/usr/lib/oracle/12.1/client64")

if 'LD_LIBRARY_PATH' not in os.environ.keys():
    print('error-path')
    os.environ['LD_LIBRARY_PATH'] = "/usr/lib/oracle/12.1/client64/lib"
    os.putenv('LD_LIBRARY_PATH', "/usr/lib/oracle/12.1/client64/lib")

if 'LD_RUN_PATH' not in os.environ.keys():
    print('Error4')
    os.environ['LD_RUN_PATH'] = '/usr/lib/oracle/12.1/client64/lib' 
    os.putenv('LD_RUN_PATH', '/usr/lib/oracle/12.1/client64/lib')
****

When I have it print out the os.environ.keys() after this, the paths are all there. I'm unsure as to why it still cannot find the libclntsh.so. 

1. What is your version of Python? Is it 32-bit or 64-bit?
Python3.4/64 bit

2. What is your version of cx_Oracle?
6.1

3. What is your version of the Oracle client (e.g. Instant Client)? 12.1
    How was it installed? unknown, I didn't install it 
    Where is it installed? /usr/lib/

4. What is your version of the Oracle Database?
    Unknown

5. What is your OS and version?
    Ubuntu 14.04.5 LTS

**Comment by anthony-tuininga** [comment]
On Linux, the environment variable LD_LIBRARY_PATH is **only** examined upon process startup. You cannot change this variable in a running program and expect it to work! There are a few options to solve this, however:

1. Add an environment variable specification to your crontab on its own line (LD_LIBRARY_PATH=some_path)

2. Set the environment variable explicitly before running your command in cron (LD_LIBRARY_PATH=some_path your_command)

3. Create a shell script that sets the environment variable and then executes your command put this shell script in your crontab instead

4. Create an entry in /etc/ld.so.conf.d to include the path you need for your script (this is global)

Hopefully one of those options will work for you!

**Comment by prelator2** [comment]
That's fantastic. Option 3 worked for me. Basically just put what was in my .bash_profile into a bash script and cronned that to call the python. Thank you very much!

**Comment by anthony-tuininga** [comment]
Glad that worked for you!
