### ISSUE TITLE
Enhancement request : parametrize internal decode of VARCHAR2 data in Python 3

### ISSUE THREAD

**Issue by shoyu63** [oracle/python-cx_Oracle#162]
When there are corrupted data in a VARCHAR2 (for example `\x90 in a WINDOWS-1252 database`), we can't fetch the corrupted record because of a cx_Oracle internal decode error.
For example:
```
(<class 'UnicodeDecodeError'>, UnicodeDecodeError('charmap', b'ELLE REVIENDRA VE
RS NOUS - BIEN PLAC\x90\xc9S - ELLE ATTEND SON CLIENT', 36, 37, 'character maps
to <undefined>'), <traceback object at 0x0000000003C6B5C8>)
```
With Python 3, there is no way in cx_Oracle (v6.2) to specify the "errors" parameter to the decode() that takes place internally.

It might be nice to be able to
  1. set this parameter.
 and/or
  2. bypass the internal "decode" to have a direct access to the binary data of the STRING and FIXED_CHAR fields.

Thank you.
Stéphane

**Comment by shoyu63** [comment]
Hello,
It look great for me. I will use it as soon as the new version is available.
Thank you.
Stéphane.

**Comment by cjbj** [comment]
@anthony-tuininga is there any performance impact by having this always enabled?

**Comment by anthony-tuininga** [comment]
The default error handler is "strict" but there are other error handlers besides "replace" which can be seen here: https://docs.python.org/3/library/codecs.html#error-handlers. There is also the possibility of implementing your own error handler. So I'm not sure what "always enabled" would look like!

**Comment by anthony-tuininga** [comment]
cx_Oracle 6.4 has been released with this enhancement included in it.
