### ISSUE TITLE
Unable create pooled connection for remote db on aws with

### ISSUE THREAD

**Issue by sreesaikiran** [oracle/python-cx_Oracle#164]
*Delete irrelevant parts of this template.*

### For general questions:

Describe exactly what you did and what you want to happen.
Use the questions at the bottom of this template as a guide.

Use Markdown syntax, particularly for code blocks: see https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

### For security issues:

See https://www.oracle.com/support/assurance/vulnerability-remediation/reporting-security-vulnerabilities.html for how to report security issues.

### For installation issues:

Use a gist for screen output and logs: see https://gist.github.com/
**Do not paste long output into this issue**

Review the install instructions at
https://github.com/oracle/python-cx_Oracle#installation

Review your output and logs.  **Google any errors**

#### Answer the following questions:

1. What is your version of Python? Is it 32-bit or 64-bit? **python-3.6,  64 bit**

2. What is your version of cx_Oracle? **6.1**

3. What is your version of the Oracle client (e.g. Instant Client)?  How was it
   installed?  Where is it installed?'
 12.1 c;\oracle\

4. What is your version of the Oracle Database?
12.1
5. What is your OS and version?
windows 10
6. What compiler version did you use?  For example, with GCC, run
   `gcc --version`.

7. What environment variables did you set?  How *exactly* did you set them?
ORACLE_HOME, path - dir of oracle client
8. What *exact* command caused the problem (e.g. what command did you try to
   install with)?  Who were you logged in as?
admin
9. What error(s) you are seeing?

Normal connection works fine . But creating pooled conection is not working.

Traceback (most recent call last):
  File "D:/Users/SYaramat/Desktop/projects/api-rds-lambda/start_batch.py", line 17, in <module>
    dsn=dsn, pool = mypool, cclass="CJDEMO3", purity=cx_Oracle.ATTR_PURITY_NEW)
cx_Oracle.DatabaseError: DPI-1012: proxy authentication is not possible with homogeneous pools

**my code:**

import cx_Oracle

dsn = cx_Oracle.makedsn("testdb.ex.rds.amazonaws.com", "1521", "TESTDB")
print(dsn)
mypool = cx_Oracle.SessionPool(user='username', password='pwd', dsn=dsn,min=1,max=2,increment=1)
conn = cx_Oracle.connect(user='user', password='pwd',
      dsn=dsn, pool = mypool, cclass="CJDEMO3", purity=cx_Oracle.ATTR_PURITY_NEW)

def get_user(event, context):
    response = {}
    print(dsn)
    print("connection created")
    print("Oracle DB version = " + conn.version)
    cur = conn.cursor()
    cur.execute(
        "select  * from test_table WHERE ID=:1 ",(101,))
    columns = [i[0] for i in cur.description]
    response= [dict(zip(columns, row)) for row in cur]
    print response
    cur.close()
    conn.close()

**Comment by anthony-tuininga** [comment]
When you create the connection from the pool you should not specify the username/password. The simplest method for doing so is as follows:

```
pool.acquire()
```

See this [documentation](http://cx-oracle.readthedocs.io/en/latest/session_pool.html#SessionPool.acquire).

**Comment by anthony-tuininga** [comment]
Assuming that the issue has been addressed due to lack of activity.
