### ISSUE TITLE
ld: file not found: crt3.o on macos using python2.7.13

### ISSUE THREAD

**Issue by Elaoed** [oracle/python-cx_Oracle#165]
```
gcc -bundle -undefined dynamic_lookup build/temp.macosx-10.4-x86_64-2.7-12c/src/cx_Oracle.o -L/usr/local/oracle -lclntsh -o build/lib.macosx-10.4-x86_64-2.7-12c/cx_Oracle.so -shared-libgcc -Wl,-rpath,/usr/local/oracle
ld: file not found: crt3.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command 'gcc' failed with exit status 1
```
I'm using python2.7.13 on macos and i got this error when pip install cx_Oracle==5.2 
I have no idea where does this crt3.o belongs to. 

additional: 
Same error occured while i was installing cx_Oracle == 6.2.1  on python 2.7.13
Nothing wrong with installing cx_Oracle 6 or cx_Oracle 5 on python 3.6.2
The two version of python(2.7.13 and 3.6.2) was installed by source file on my laptop. 

Solution:  Replace gcc with gcc-7 installed by brew. and pip install cx_oracle.

**Comment by cjbj** [comment]
Have you tried cx_Oracle 6?

**Comment by cjbj** [comment]
Oh, and on macOS you need to install a python binary since the system python is locked down.  See http://cx-oracle.readthedocs.io/en/latest/installation.html#installing-cx-oracle-on-macos

Some details about what you've done and installed would be helpful.

**Comment by Elaoed** [comment]
@cjbj  Yes... Same error ocurred when i was installing cx_oracle 6.. and it's really wired that pip3 could make it.... but my project based on python2.  and i've tried those step on the website you've posted yesterday but it doesn't seem to work.
I just wondering where the crt3.o file exists?
Anyway thanks for replying me

**Comment by cjbj** [comment]
@Elaoed this is what I've got on High Sierra:
```
-rw-r--r--  1 wheel   9164 16 Jul  2017 /usr/lib/crt1.10.5.o
-rw-r--r--  1 wheel   8896 16 Jul  2017 /usr/lib/crt1.10.6.o
-rw-r--r--  1 wheel  10252 16 Jul  2017 /usr/lib/crt1.o
```

**Comment by Elaoed** [comment]
@cjbj  I found the solution. After i use find command in a global scope.  I found this /usr/local/Cellar/gcc/7.3.0_1/lib/gcc/7/gcc/x86_64-apple-darwin16.7.0/7.3.0/crt3.o
I guess maybe it's a problem with gcc. So i replace the /usr/bin/gcc with gcc i've installed with brew. and it just works!!!
I really appreciate with the way of thinking you've provide :)

**Comment by cjbj** [comment]
I'm glad you got it going.  I would still recommend using cx_Oracle 6.
