### ISSUE TITLE
Cannot run table update with bind parameters

### ISSUE THREAD

**Issue by msaron** [oracle/python-cx_Oracle#168]
*Delete irrelevant parts of this template.*

### For general questions:

Describe exactly what you did and what you want to happen.
Use the questions at the bottom of this template as a guide.

I want to update a table using bind parameters. The cx_Oracle driver works fine  except when I want to update a table using bind parameters. Without using bind parameters the update query works fine. I could not find an example using bind parameters in the examples directory to update a table.

#### Answer the following questions:

1. What is your version of Python? Is it 32-bit or 64-bit?
```
Version 3.6.5 
64-bit
```

2. What is your version of cx_Oracle?
```6.2.1 ```

3. What is your version of the Oracle client (e.g. Instant Client)?  How was it
   installed?  Where is it installed?
```
C:\oracle\instantclient_12_2
```
4. What is your version of the Oracle Database?
```12.2.0.1.0```

5. What is your OS and version?
```Windows 10 Professional```

6. What compiler version did you use?  For example, with GCC, run
   `gcc --version`.
```5.4.0```

7. What environment variables did you set?  How *exactly* did you set them?

8. What *exact* command caused the problem (e.g. what command did you try to
   install with)?  Who were you logged in as?
```
cur = con.cursor()
sql = "update table1 set name = :1, short_name = :1 where id = :2"
cur.execute(sql, ('test', 5)
```
9. What error(s) you are seeing?
```
   cur.execute(sql, ('test', 5))
cx_Oracle.DatabaseError: ORA-01484: arrays can only be bound to PL/SQL statements
```

**Comment by anthony-tuininga** [comment]
Performing an update is no different from performing an insert or delete. I tried your code. I get the following error instead: cx_Oracle.DatabaseError: ORA-01008: not all variables bound. If you are binding by position you have to specify all positions! If you want to bind by name you would need to do something like the following:

```python
sql = "update table1 set name = :name, short_name = :name where id = :id"
cur.execute(sql, name = 'test', id = 5)
```

OR

```python
sql = "update table1 set name = :name, short_name = :name where id = :id"
params = { "name" : "test", "id" : 5 }
cur.execute(sql, params)
```

The error you are getting is suggesting that you are attempting to pass an array for one of the bind positions -- which isn't what you have in your code. Can you supply the entire script?

**Comment by msaron** [comment]
Sorry, figured it out. I was passing in an array in one of the variables which is not allowed.
