### ISSUE TITLE
cx_Oracle unaware DB server gone away

### ISSUE THREAD

**Issue by skywaymsn** [oracle/python-cx_Oracle#17]
### For general questions:

Connected to Primary Oracle RAC with Active DataGuard (secondary is Read-Only)

If Primary listener goes away cx_Oracle will attempt a query, but time out after 180 seconds.  Can we reduce that?

In this case, a backhoe cut some fiber, but easily reproduced with: iptables -A OUTPUT -d xxx.xxx.xxx.xxx -j DROP

Ultimately we'd like to react more quickly if a server is dead.  When we do detect a reconnect scenario, SQLAlchemy's timeout does not appear to affect cx_Oracle connections so we perform a simple TCP connect first.  This is fine, but the larger issue is when a connection is established, but the DB server is gone.

#### Answer the following questions:

1. What is your version of Python? Is it 32-bit or 64-bit?

64-bit 3.5.3 and 3.6.1

2. What is your version of cx_Oracle?

cx-Oracle==5.2.1

3. What is your version of the Oracle client (e.g. Instant Client)?  How was it
   installed?  Where is it installed?
````
> rpm -qa|grep instantclient12
oracle-instantclient12.1-basic-12.1.0.2.0-1.x86_64
oracle-instantclient12.1-devel-12.1.0.2.0-1.x86_64
````
RPM defaults: /usr/lib/oracle/12.1/client64/

4. What is your OS and version?

> cat /etc/system-release
Oracle Linux Server release 6.5

5. What compiler version did you use?  For example, with GCC, run
   `gcc --version`.
````
gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-17)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
````

6. What environment variables did you set?  How *exactly* did you set them?
```
> cat .bashrc
# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

if [ -d ~/.bashrc.d ]; then
    for i in ~/.bashrc.d/*.sh ; do
        if [ -r "$i" ]; then
            if [ "${-#*i}" != "$-" ]; then
                . "$i"
            else
                . "$i" >/dev/null 2>&1
            fi
        fi
    done
fi

> cat .bashrc.d/oracle-instantclient.sh 
#!/bin/bash

export ORACLE_HOME=/usr/lib/oracle/12.1/client64/
export DYLD_LIBRARY_PATH=$ORACLE_HOME
export LD_LIBRARY_PATH=$ORACLE_HOME:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib:$LD_LIBRARY_PATH
```

8. What error(s) you are seeing?

 * Connection sits and waits.
 * After 180 seconds, we get the error we expect.  Can we get it sooner?

```
2017-04-26 21:36:23,111 ERROR: (cx_Oracle.OperationalError) ORA-03135: connection lost contact\nProcess ID: 26655\nSession ID: 20 Serial number: 48108
```

This is actually wrapped in sqlalchemy.exc.OperationalError, caught similar to this (simplified):
```
        try:
                result = self.Session.read_session.query(self.model).filter(*_f).all()

        except (sqlalchemy.exc.OperationalError, sqlalchemy.exc.UnboundExecutionError, sqlalchemy.exc.InterfaceError, sqlalchemy.exc.DatabaseError, cx_Oracle.InterfaceError) as e:

                emit(e, code=500, source='%s modelsearch.ModelSearch.run()' % (sid), extra="DB Query Failure.  Reconnecting.")

                ... etc.
```

**Comment by cjbj** [comment]
Sorry about lack of detail, but look at FAN or sqlnet.ora config like SQLNET.RECV_TIMEOUT and
SQLNET.SEND_TIMEOUT.  You may also want to at tuning OS TCP parameters.

**Comment by skywaymsn** [comment]
De-tuning the system's TCP TIME_WAIT timer seems like big hammer for something like this.

I'm not totally opposed to SQLNET.RECV_TIMEOUT, but that inhibits our ability to survive very large/complex queries or massively busy servers.

I guess I'm unclear if the Oracle client has some sort of heartbeat/noop/keepalive function under the hood.  If so, accessing the state of such a thing may be a way to detect a dead node.  It would be the difference between "I sent a query and nothing happened for X seconds" vs. "This connection hasn't had a heartbeat response in X seconds, don't bother with the query, reconnect/reject instead."

We can catch all kinds of cool stuff like ```(cx_Oracle.DatabaseError) ORA-16456: switchover to standby in progress or completed``` which makes me think there must be something buried in there about the state of the connection... maybe.

**Comment by cjbj** [comment]
Check FAN.  You should also talk to some RAC experts about service configuration.

**Comment by kikitux** [comment]
@skywaymsn does this work with a different client / driver?

There is a component that is cluster side that should be there.

**Comment by skywaymsn** [comment]
I think this discussion went a bit sideways.  The issue isn't about losing a node in a RAC cluster.  That's what FAN for.  This is about losing a closer (or standalone node) in a Dataguard environment when another site becomes Primary.  Or more specifically, about an active session simply going dark.

In the simplest form:
```[Site A READ/WRITE] --Active Dataguard--> [SITE B READ-ONLY]```

If Site A disappears, Site B becomes READ/WRITE and Site A, when back, will be READ-ONLY.  However, connections open to Site A don't know it disappeared, so they don't know to connect to Site B until a TCP Timeout occurs (typically 180 seconds).

Detecting the complete disappearance of Site A is the issue.  There is no notification (that I know of) that cx_Oracle can respond to.

**Comment by mrochford** [comment]
I am seeing this issue as well. Has there been any update to this?

**Comment by Rustem** [comment]
+1

**Comment by whoiswes** [comment]
+1

**Comment by cjbj** [comment]
Adding "+1's" here isn't going to help.  For a start, each situation is different, and then this isn't the forum to ask about networking, low level Oracle Net configuration, and complex Database service set ups.

**Comment by skywaymsn** [comment]
I thought the issue was pretty straight forward:

If an application is connected to Oracle via cx_Oracle and Oracle goes away, cx_Oracle will blissfully attempt to send queries to Oracle.

The timeout in this scenario is a TCP timeout because we have no way to know that Oracle is gone.  TCP timeouts generally come in around 180 seconds making dead-node detection very slow.

As a work-around we can attempt a TCP connection to port 1521 before every query, but that's brutally inefficient.

**Comment by cjbj** [comment]
@skywaymsn look at various Oracle Net options I mentioned above like SQLNET.RECV_TIMEOUT, SQLNET.SEND_TIMEOUT and the (ENABLE=BROKEN) option.

**Comment by cjbj** [comment]
@skywaymsn here's another interesting reference: https://github.com/oracle/odpi/issues/50#issuecomment-351128424

**Comment by whoiswes** [comment]
@cjbj - thanks for the note, I finally sat down and spent some time digesting the sqlnet config (I have zero Oracle background so this is/was all new), and came out the other end with something that resembles a workable config :grin: 

FWIW, TCP.CONNECT_TIMEOUT and SQLNET.OUTBOUND_CONNECT_TIMEOUT are the 2 values that seem to do the trick for detecting bad connections (utilizing SQLAlchemy's pre-ping event listener) without impacting query timeouts.  I haven't yet figured out if/how to limit the actual query, but SQLNET.SEND_TIMEOUT and SQLNET.RECV_TIMEOUT did not appear to have any effect when set.

**Comment by cjbj** [comment]
My todo list has an item on allowing cx_Oracle to set some of these values since there are OCI attributes for them.

**Comment by marksteward** [comment]
Another relevant scenario is an intervening firewall going away. And while it'll be helpful to be able to set the connect timeout, you need to be able to set TCP_KEEPIDLE and friends to use enable=broken effectively. Ideally instant client should expose these parameters, although I realise fixing that is probably out of cx_Oracle's remit.

[libkeepalive](http://libkeepalive.sourceforge.net/) helps but isn't ideal as it's per-process. The only "clean" solution I can suggest is to have a dedicated child process per connection and supervise them. This obviously needs special-casing for long queries.

**Comment by cjbj** [comment]
cx_Oracle is a layer on [ODPI-C](https://github.com/oracle/odpi) which is a layer on [OCI](https://docs.oracle.com/en/database/oracle/oracle-database/18/lnoci/toc.htm) which is a layer on [Oracle Net](https://docs.oracle.com/en/database/oracle/oracle-database/18/netrf/index.html) which talks to the DB.

When a cx_Oracle function or operation triggers an error, that error will propagate back up the stack, although each layer may potentially map it to another error number, or [handle it internally](https://github.com/oracle/odpi/blob/ba80d2546c5ef8f22da5ef76615c7f4bc4e511a7/src/dpiConn.c#L655-L657).

**Comment by anthony-tuininga** [comment]
Take a look at the SQL*Net configuration Chris mentioned earlier in this issue. The documentation can be found [here](https://docs.oracle.com/en/database/oracle/oracle-database/18/netrf/parameters-for-the-sqlnet-ora-file.html#GUID-4A19D81A-75F0-448E-B271-24E5187B5909).

**Comment by kyrick** [comment]
Thanks for the replies guys! 

So this is my exact sqlnet.ora configuration:
```
SQLNET.RECV_TIMEOUT=1
SQLNET.SEND_TIMEOUT=1
TCP.CONNECT_TIMEOUT=1
SQLNET.OUTBOUND_CONNECT_TIMEOUT=1
SQLNET.INBOUND_CONNECT_TIMEOUT=1
```

I don't think connect timeout does anything on the client side. But I was getting desperate so I set all the timeout related parameters. I even tried setting my keepalive setting to be very low and set (ENABLE=BROKEN) in tnsnames.ora. I think the presence of TNS-12535 in the sqlnet.log means that SQL*NET is configured to timeout right?

**Comment by cjbj** [comment]
Also look at `ENABLE=BROKEN` and tune client-side TCP keepalive timers.

**Comment by kyrick** [comment]
I came across TCP keepalive and enable=broken in my research on this problem. I tried both of those settings and saw no improvement. :/

I've configured (ENABLE=BROKEN) in tnsnames.ora

My keepalive settings are as follows (I'm running in a docker container)
```
  --sysctl net.netfilter.nf_conntrack_tcp_timeout_established=1 \
  --sysctl net.ipv4.tcp_keepalive_time=1 \
  --sysctl net.ipv4.tcp_keepalive_probes=3 \
  --sysctl net.ipv4.tcp_keepalive_intvl=1 \
```

Is there anything else I can try? Or any more logging I can turn on?

**Comment by cjbj** [comment]
@kyrick I asked a Network contact to take a look when he's back from vacation.
Can you give an executive summary here of the scenario(s) you are trying to handle?

**Comment by kyrick** [comment]
@cjbj hey that's awesome! I appreciate it.

**Summary:**
Our python app connects to an on prem Oracle database from a kubernetes cluster. The DNS routing back to on prem works well. Under ideal conditions, there are no issues connecting to and operating on the database. I'm trying to make the app robust against non-ideal scenarios. (i.e. exception handling)

I have python 2.7, instant client 18.3, and cx_oracle 7.0.0 connecting to an 11.2 Oracle database.
[More configuration details can be found here.](https://github.com/oracle/python-cx_Oracle/issues/259)

**There are three scenarios my client application needs to recover from:**
1. Oracle database goes down/offline due to an incident.
2. One node in the Oracle cluster fails (and it happens to be the one our app connected to).
3. Infrastructure events that disrupt the connection. (azure vnet goes down, the on prem infrastructure fails, etc.)

**What happens today:**
If an outage occurs after the connection is established, the next cursor execute will hang indefinitely.

**Comment by cjbj** [comment]
I reviewed this old thread and will close it now that more collateral is available.

The configuration for HA is done at the DB service level and Oracle Net level; and then some best-practice cx_Oracle usage helps.  This makes sure that cx_Oracle knows about DB service errors without waiting for TCP timeouts.

The cx_Oracle documentation that encompasses the discussion above: is in [High Availability with cx_Oracle](https://cx-oracle.readthedocs.io/en/latest/user_guide/ha.html).

There was a conference presentation on it at OOW, see [Scalability and High Availability for Oracle Database Python Applications](https://static.rainfocus.com/oracle/oow19/sess/155356052830600180DE/PF/DEV4625-Scalability-and-High-Availability-for-Oracle-Database-Python-Applications_1568931704636001Qx1H.pdf).

There is an Office Hours video at [Easy High Availability and More with cx_Oracle](https://asktom.oracle.com/pls/apex/f?p=100:551:::NO:RP,551:P551_CLASS_ID:6331&cs=1C158BAE3998ACE760304FBFAC0B0705D).
