### ISSUE TITLE
docstrings in cx_Oracle

### ISSUE THREAD

**Issue by xeviterr** [oracle/python-cx_Oracle#175]
I'm only have a question/suggestion.

Why the docstrings are not included in the cx_Oracle module, or I can't find them?

When I'm connecting oracle from ipython console using cx_Oracle, I'm not able to get the docstring of any object.  For example when I'm using a Cursor object.

```python
In [21]: cxOra.execute?
Docstring: <no docstring>
Type:      builtin_function_or_method
````

I always have to read the documentation, is not a very big problem but it will be wonderful if someday I can see the documentation on command line, or at least the function signature.

Thanks!

**Comment by anthony-tuininga** [comment]
Thanks for the suggestion. I'll figure out how to ensure that the documentation is not duplicated in the C code and Sphinx and then see how much effort is involved to migrate.

**Comment by quenck** [comment]
Would that also help for intellisense / autocompletion in VSCode / PyCharm?

**Comment by troyswanson** [comment]
Coming here for the same issue. No type hinting available on cx_Oracle in Visual Studio Code.

**Comment by cjbj** [comment]
Fixed in next version - due out soon.

**Comment by cjbj** [comment]
The new version is out, see the [release announcement](https://cjones-oracle.medium.com/open-source-python-thin-driver-for-oracle-database-e82aac7ecf5a).  It has good intellisense (but we can see room for improvement).
