### ISSUE TITLE
Select statement with sum

### ISSUE THREAD

**Issue by wajihmsedi** [oracle/python-cx_Oracle#179]
*Delete irrelevant parts of this template.*

### For general questions:

Describe exactly what you did and what you want to happen.
Use the questions at the bottom of this template as a guide.

Use Markdown syntax, particularly for code blocks: see https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

### For security issues:

See https://www.oracle.com/support/assurance/vulnerability-remediation/reporting-security-vulnerabilities.html for how to report security issues.

### For installation issues:

Use a gist for screen output and logs: see https://gist.github.com/
**Do not paste long output into this issue**

Review the install instructions at
https://github.com/oracle/python-cx_Oracle#installation

Review your output and logs.  **Google any errors**

#### Answer the following questions:

1. What is your version of Python? Is it 32-bit or 64-bit?

2. What is your version of cx_Oracle?

3. What is your version of the Oracle client (e.g. Instant Client)?  How was it
   installed?  Where is it installed?

4. What is your version of the Oracle Database?

5. What is your OS and version?

6. What compiler version did you use?  For example, with GCC, run
   `gcc --version`.

7. What environment variables did you set?  How *exactly* did you set them?

8. What *exact* command caused the problem (e.g. what command did you try to
   install with)?  Who were you logged in as?

9. What error(s) you are seeing?

**Comment by anthony-tuininga** [comment]
Yes, your issue is visible now. Your error suggests that the data in your EPE column is not a valid number, at least in one row. You should perform your query without the sum and examine the output. If the number of rows is significant, however, you can write a PL/SQL function that attempts the conversion and catches the exception and simply reports that the number is invalid -- so that you can find out which one.

Of course the other questions is -- if the data is supposed to be numeric, why store it in a string? Why not use a numeric column?

**Comment by wajihmsedi** [comment]
Yes I actually used a simple sql statement and it is only one row. It is working well. The sum query is BTW working well in sql developer.

It sounds awkward indeed and I have no power to change the datatypes unfortunately. 

@anthony-tuininga what will be your suggestion ?

**Comment by anthony-tuininga** [comment]
If it works in SQL Developer, it will work with cx_Oracle. The same underlying engine does the work in both cases! Can you create a standalone case that demonstrates the issue? Have it include the create table statement and the insert statements to populate the table and the Python script you are executing.

**Comment by wajihmsedi** [comment]
@anthony-tuininga I can't share the data or schema. They are corporate. How can I make myself sure the same underlying engine execute the work. 
Indeed the error is written in German : ORA-01722: Ungültige Zahl.
Whereas sql developer use english whenever there is an error.

**Comment by anthony-tuininga** [comment]
You said that it was only one row. Surely you can create a table and populate it with the row that is causing the problem? It doesn't have to be the exact table and data -- just one that replicates the issue. Sometimes building the problem independently reveals the issue, too. :-)

**Comment by wajihmsedi** [comment]
[insert.txt](https://github.com/oracle/python-cx_Oracle/files/1995901/insert.txt)
[export.txt](https://github.com/oracle/python-cx_Oracle/files/1995907/export.txt)

@anthony-tuininga  here it is :+1:

**Comment by anthony-tuininga** [comment]
Take a look at your NLS settings for numeric characters:

```sql
select value
from nls_session_parameters
where parameter = 'NLS_NUMERIC_CHARACTERS';
```
I suspect it will be different in the two environments since Europe usually uses the comma for a decimal separator and North America usually uses the period for a decimal separator. If that is indeed the case you can either do this

```sql
alter session set NLS_NUMERIC_CHARACTERS = '.,';
```
or you can follow the answer found [here](https://stackoverflow.com/questions/24571355/nls-numeric-characters-setting-for-decimal).

**Comment by wajihmsedi** [comment]
sql="SELECT ID , 
sum(to_number(EPEUNSCLD, '99999D99', 'NLS_NUMERIC_CHARACTERS='',.'''))  
  FROM githubexample
  GROUP BY MSAGRID"

So I executed the following and I still have invalid number.

@anthony-tuininga is the statement correct ?

**Comment by wajihmsedi** [comment]
No it doesn't work because the numerical data are not consistent. 
Is there a way to set the NLS parameter from the python session ?

**Comment by cjbj** [comment]
For the record, executing an ALTER SESSION requires a 'round-trip' to the database, which takes time and impacts overall system scalability.  A faster alternative is the set the environment variable NLS_NUMERIC_CHARACTERS before you run python.  If you set this, you must also set NLS_LANG.

**Comment by wajihmsedi** [comment]
@anthony-tuininga thank you for your suggestion. It worked like a charm :+1:

**Comment by anthony-tuininga** [comment]
Excellent. Glad to hear it!
