### ISSUE TITLE
[6.0b1] OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by felixxm** [oracle/python-cx_Oracle#18]
I think that there is regression in `cx_Oracle==6.0b1`. Passing number with 19 9's i.e. `9999999999999999999` to the cursor fails with `OverflowError: Python int too large to convert to C long` (18 9's works). Please find below regression test that fails in `cx_Oracle==6.0b1` and works in `cx_Oracle==5.3`:
```python
import cx_Oracle
connection = cx_Oracle.connect("user", "password", "TNS")
cursor = connection.cursor()
cursor.execute("select :arg0 from dual", {':arg0': -9999999999999999999})
```

* Python 3.4.3 (64-bit)

**Comment by anthony-tuininga** [comment]
I have verified that this is in fact a regression. A bug fix and an addition to the test suite will be coming shortly. Thanks for letting me know!
