### ISSUE TITLE
High RAM & CPU usage while using fetchmany()

### ISSUE THREAD

**Issue by laxmikanthvattamwar** [oracle/python-cx_Oracle#180]
""" I am fetching employees data from hr schema using cx_Oracle module, what i have observed during the fetch is for extracting 10K records of .823MB , approx 30% of CPU, 35MB of RAM and 3-4Mbps for writing to a file was utilized.

Can someone let me know if we can get the data from database with minimal usage of CPU & RAM. I mean when .823MB, nearly 15-20MB(35-13.2) and more than 30% CPU is been utilized. 

Python version: 3.6.4
cx_Oracle version: 6.3
Oracle Version 11.2.0.2.0

Observation:
![image](https://user-images.githubusercontent.com/5056900/40044840-3eeda514-5846-11e8-9368-73f84cf1fb84.png)

```python
import cx_Oracle
import csv
import time
conn=cx_Oracle.connect('hr/hr@xe')
cur=conn.cursor()
cur.arraysize=10000
cur.execute('select * from employees where rownum<1000000')
def gen():
    while True:
        res=cur.fetchmany()
        if not res:
            break
        else:
            yield res
def writer(gen_data):
    filename = 'sample.csv'
    file = open(filename, 'w', newline='')
    fd = csv.writer(file, dialect='excel')
    for rec in gen_data:
        print('{} employee records and size: {} '.format(len(rec),rec.sizeof()))
        for i in rec:
            fd.writerow(i)
if name=='main':
    start=time.time()
    gen_data=gen()
    writer(gen_data)
    print(time.time()-start)
```

![image](https://user-images.githubusercontent.com/5056900/40045331-a4d4ab06-5847-11e8-8258-87de1fde3da6.png)

**Comment by anthony-tuininga** [comment]
I have a couple comments/questions that may be of help.

- increasing array size will increase memory usage and reduce the number of round-trips to the database. You will need to determine what trade-off is more important to you!
- using a generator and cursor.fetchmany() is going to be less efficient than simply using the cursor itself as a generator. You can simply write "for rec in cur:" instead of "for rec in gen_data:" and reduce your code size at the same time! The way you've written it requires a 10,000 element list to be built whereas using the cursor as an iterator only requires a single row to be built at a time.

**Comment by laxmikanthvattamwar** [comment]
As per your suggestion i have changed the code, as "for rec in cur:" instead of "for rec in gen_data:", and i see RAM usage has been reduced, and the array size of 10K records seems pretty fine. But still the CPU utilization is very high.

Below is the observation:
![image](https://user-images.githubusercontent.com/5056900/40115181-33306242-592d-11e8-9e07-3e18deca0d2f.png)


```python
import cx_Oracle
import csv
import time
start=time.time()
conn=cx_Oracle.connect('hr/hr@xe')
cur=conn.cursor()
cur.arraysize=10000
cur.execute('select * from emp where rownum<1000000')
filename = 'new.csv'
file = open(filename, 'w', newline='')
fd = csv.writer(file, dialect='excel')
for rec in cur:
	fd.writerow(rec)
cur.close()
file.close()
print(time.time()-start)
```

**Comment by cjbj** [comment]
To narrow the factors down, see what the load is if you don't actually write to file, and secondly also try constructing the desired file output format in the query so you don't need the csv.writer to transform the returned rows.

**Comment by anthony-tuininga** [comment]
I was just going to say the same thing as @cjbj but he beat me to it. :-)

You might also be able to get a bit more performance by avoiding the iteration yourself. In other words use this instead:

```python
fd.writerows(cur)
```

**Comment by laxmikanthvattamwar** [comment]
I have ran the script with & without writing to a file, and here are the observations. 

![image](https://user-images.githubusercontent.com/5056900/40309337-b49b110e-5d26-11e8-83a6-021374927eea.png)
```Python
import cx_Oracle
import time
start=time.time()
conn=cx_Oracle.connect('hr/hr@xe')
cur=conn.cursor()
cur.arraysize=10000
cur.execute("""select EMPLOYEE_ID||'\t'||FIRST_NAME||'\t'||LAST_NAME||'\t'||EMAIL||'\t'||PHONE_NUMBER||'\t'||HIRE_DATE||'\t'||JOB_ID||
'\t'||SALARY||'\t'||COMMISSION_PCT||'\t'||MANAGER_ID||'\t'||DEPARTMENT_ID||'\n'||'' from employees where rownum<1000000""")
with open('new.txt','w') as fd:
    for rec in cur:
        pass
        #fd.writelines(rec)
cur.close()
print(time.time()-start)
```

Looks like a minimum of 10-12% of CPU usage is required by Python process to fetch data.
By transformation in SQL query it had increased the CPU usage of Oracle.

**Comment by laxmikanthvattamwar** [comment]
No, Thank you for guiding me to reduce the CPU and memory.

**Comment by cjbj** [comment]
@laxmikanthvattamwar out of interest, what are the database and client character sets - I'm interested to know if there was character size conversion that impacted memory usage?  Can you run these in python:

DB character set:
```
select value as db_charset from nls_database_parameters where parameter = 'NLS_CHARACTERSET';
```

Client character set:
```
select distinct client_charset from v$session_connect_info where sid = sys_context('USERENV', 'SID');
```
