### ISSUE TITLE
Implement context manager for Cursors

### ISSUE THREAD

**Issue by gvenzl** [oracle/python-cx_Oracle#190]
Implement context manager for Cursor object to enable `with` statement.
Currently the `with` statement can't be used for cursors because they don't implement a context manager, i.e. the `__enter__` and `__exit__` attributes meaning that the following code will fail:

```python
with conn.cursor() as c:
    c.execute("SELECT 'test' from dual")
    result = c.fetchall()
    print(result)

  File “/Users/gvenzl/test/test.py”, line 23, in test
    with conn.cursor() as c:
AttributeError: __exit__
```
It would make sense to enable cursor object to be used in `with` statements that take care of closing the cursors automatically.

**Comment by anthony-tuininga** [comment]
I agree that it would make sense to implement the context manager on cursors. Thanks @gvenzl.
