### ISSUE TITLE
Python crashes when trying to bulk load CLOBs

### ISSUE THREAD

**Issue by gvenzl** [oracle/python-cx_Oracle#192]
I'm trying to bulk insert 60 CLOBs with 2k bytes each. When calling `executemany` Python crashes with `Abort trap: 6`.

Here the simple test program:

```python
#!/bin/env python3

import cx_Oracle as db


print("Getting connection")
conn = db.connect("fifa", "worldcup", "localhost:1521/ORCLPDB1")
print("Getting cursor")
cur = conn.cursor()

print("Creating table")
try:
    cur.execute("CREATE TABLE TEST (data CLOB CONSTRAINT test_valid_json CHECK (data IS JSON))")
except db.DatabaseError as err:
    # Table already exists, truncate
    if err.args[0].code != 955:
        raise err

rows = []
print("Setting values")
for i in range(60):
    clob = cur.var(db.CLOB)
    clob.setvalue(0, "#"*2000)
    rows.append((clob,))
print("Execute insert")
cur.executemany("INSERT INTO TEST (data) VALUES (:1)", rows)
print("Commit")
conn.commit()
print("Closing cursor")
cur.close()
print("Closing connection")
conn.close()
print("Done")
```

On execution the following error occurs:

```bash
gvenzl-mac:bug gvenzl$ /usr/local/bin/python3 bug.py
Getting connection
Getting cursor
Creating table
Setting values
Execute insert
Abort trap: 6
gvenzl-mac:bug gvenzl$
```

#### Answer the following questions:

1. What is your version of Python? Is it 32-bit or 64-bit?
```
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 26 2016, 10:47:25)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
```

2. What is your version of cx_Oracle?
```
cx-Oracle  6.3.1
```

3. What is your version of the Oracle client (e.g. Instant Client)?  How was it
   installed?  Where is it installed?
```
12.2.0.1
Manually extracted into ~/lib
```

4. What is your version of the Oracle Database?
```
12.2.0.1
```

5. What is your OS and version?
```
Mac OS X 10.13.5
```

6. What compiler version did you use?  For example, with GCC, run
   `gcc --version`.
I didn't compile

7. What environment variables did you set?  How *exactly* did you set them?
None

8. What *exact* command caused the problem (e.g. what command did you try to
   install with)?  Who were you logged in as?
`executemany`

**Comment by gvenzl** [comment]
Indeed, the updates Instant Client version does produce the same error now without crashing the program:

```python
gvenzl-mac:Downloads gvenzl$ python3 bug.py
Getting connection
Getting cursor
Creating table
Setting values
Execute insert
Traceback (most recent call last):
  File "bug.py", line 26, in <module>
    cur.executemany("INSERT INTO TEST (data) VALUES (:1)", rows)
cx_Oracle.DatabaseError: DPI-1018: array size of 1 is too small
gvenzl-mac:Downloads gvenzl$
```

No, I don't need to, it was just to illustrate the bug and what I've found on the web.

I'm closing this as it has been identified that this is fixed within the latest version of Instant Client.

**Comment by anthony-tuininga** [comment]
@cjbj, if you create a variable and intend to use it in cursor.executemany() you need to specify the array size as in this:

```python
var = cursor.var(cx_Oracle.CLOB, arraysize = 60)
```

But, as Chris mentioned, you don't need to do that and in fact, shouldn't, as doing so will enforce the use of temporary CLOBs which won't perform very well at all!
