### ISSUE TITLE
cxOracle6.3.1 with numpy64float

### ISSUE THREAD

**Issue by tobymathieson** [oracle/python-cx_Oracle#194]
I am using the latest cx_Oracle 6.3.1 (python 2.7.10 / 64bit) with oracle12 instant client, running on redhat6 under linux . When entering data from 64bitfloats to a number(13, 6) or number(8,3) field the values are seemingly rounded to 1 or 0. 

I must be doing something wrong.  It worked fine with the identical set up but using cx_Oracle5.5.1

**Comment by anthony-tuininga** [comment]
Can you provide the code that is causing the difficulty? Also, there is no version cx_Oracle 5.5.1. The last version for cx_Oracle 5 was 5.3! Could you clarify that as well? Thanks.

**Comment by tobymathieson** [comment]
Apologies I meant cx_Oracle 5.1.1.

The code looks like this:

db = cx_Oracle.connect('yyyy/xxxx@xxxx')
cursor = db.cursor()

sql_sta = """insert into quantresult
        ( FOLDCHANGE, LEVELOFCONFIDENCEUPPER, LEVELOFCONFIDENCELOWER,
reference_id, importlog_ids)
         values ( :foldchange, :upperconf, :lowerconf, :reference_id,
:issameset, :importlog_ids)
        """

'data' =  {'importlog_ids': '350534', 'lowerconf': 0.5631423515530891,
'reference_id': 4147499, 'upperconf': 0.7091327250364661, 'foldchange':
0.6244499779795032}

cursor.execute(sql_sta, data)

db.commit()


The types are listed here:

importlog_ids 350534 <type 'str'>
lowerconf 0.563142351553 <type 'numpy.float64'>
reference_id 4147499 <type 'int'>
upperconf 0.709132725036 <type 'numpy.float64'>
foldchange 0.62444997798 <type 'numpy.float64'>

If I explicitly convert the numpy.float64's to python floats then the data
is inserted correctly.  Can it have something to do with the precision? I
could not see how to show the precision given for the numpy.float64's .

best

Toby

**Comment by anthony-tuininga** [comment]
Can you provide the code with numpy included? I haven't used numpy much!

**Comment by anthony-tuininga** [comment]
FYI, I just tried this code and it worked just fine. Please adjust as necessary to demonstrate your issue. Thanks!

```python
data = {
    'importlog_ids': '350534',
    'lowerconf': numpy.float64(0.5631423515530891),
    'reference_id': 4147499,
    'upperconf': numpy.float64(0.7091327250364661),
    'foldchange': numpy.float64(0.6244499779795032)
}

cursor.execute("""
        select :foldchange, :upperconf, :lowerconf, :reference_id,
                :importlog_ids from dual""", data)
for row in cursor:
    print(row)
```

**Comment by tobymathieson** [comment]
Hi Anthony,

The steps before the insert statement are quite long and written by a
colleague who's out of office for some months. I therefore cannot supply
you with code snippet to recreate the problem more generally (there are
several different kinds of Numpy manipulations).

Your example works for me too, and returns the values as one would expect
without issue.

however, when trying to debug this I noticed that if I explicitly set the
input sizes,the insert works correctly.
eg:
self.cursor.setinputsizes(foldchange=cx_Oracle.NUMBER,
upperconf=cx_Oracle.NUMBER, lowerconf=cx_Oracle.NUMBER)

Can you (or someone) comment on why this might be?

And thanks so much for your input so far.

best

Toby

**Comment by anthony-tuininga** [comment]
cx_Oracle will take the input value and attempt to determine the best type to use for that type of data. By using setinputsizes(), however, you are telling cx_Oracle what type to use and not letting it "guess". Its possible the "guess" isn't doing the trick for you for some reason. It would be nice to know what data is messing it up. If you can provide some code that demonstrates the problem I'd be happy to diagnose the issue; otherwise, if you're satisfied with the setinputsizes() band-aid, feel free to close the issue!

**Comment by anthony-tuininga** [comment]
Assuming your question has been answered due to lack of activity.
