### ISSUE TITLE
report a bug cause by a space

### ISSUE THREAD

**Issue by kingchenchina** [oracle/python-cx_Oracle#195]
oracle 11.2
cx_Oracle 6.3.1
python 3.6.5

bug: when sql has **distinct** key word and a space in paging setting, it will hit a bug, and cause dozens of time more than normal

detail:
sql 1:
SELECT distinct * FROM (select A.*, ROWNUM RN FROM (SELECT cb.*,cbp.prediction,cbp.probability,cbp.prediction_topn FROM combinevoice5test cb, combinevoice5testpredict cbp where cb.l_seq = cbp.l_seq and cb.remark != 'same') A WHERE ROWNUM < 5010) WHERE RN >=5000

sql 2:
SELECT distinct * FROM (select A.*, ROWNUM RN FROM (SELECT cb.*,cbp.prediction,cbp.probability,cbp.prediction_topn FROM combinevoice5test cb, combinevoice5testpredict cbp where cb.l_seq = cbp.l_seq and cb.remark != 'same') A WHERE ROWNUM < 5010) WHERE RN >= 5000

sql 2 need more about 80 times time  than sql 1

can anybody help me?

**Comment by cjbj** [comment]
If this is a pure SQL issue that reproduces in SQL*Plus or SQL Developer, the best place to ask is https://asktom.oracle.com/

If it only reproduces in cx_Oracle, please share a testcase that shows it.  Include the SQL to create the table so we know the column types.

**Comment by kingchenchina** [comment]
**it only happen in cx_Oracle**.

the first table constains about 800 thousand records, and the second table constains about 50 thousand records

below is the sql to create the table:
create table COMBINEVOICE5TEST
(
  l_seq                      NUMBER(20),
  partition_id               NUMBER(4) not null,
  l_legacy_system            VARCHAR2(256),
  l_legacy_version           VARCHAR2(256),
  l_subsequence              VARCHAR2(256),
  l_timestamp                VARCHAR2(256),
  l_servicekey               VARCHAR2(256),
  l_callingpartynumber       VARCHAR2(256),
  l_calledpartynumber        VARCHAR2(256),
  l_callingpartyimsi         VARCHAR2(256),
  l_calledpartyimsi          VARCHAR2(256),
  l_dialednumber             VARCHAR2(256),
  l_originalcalledparty      VARCHAR2(256),
  l_serviceflow              VARCHAR2(256),
  l_callforwardindicator     VARCHAR2(256),
  l_callingroaminfo          VARCHAR2(256),
  l_callingcellid            VARCHAR2(256),
  l_calledroaminfo           VARCHAR2(256),
  l_calledcellid             VARCHAR2(256),
  l_timestampofssp           VARCHAR2(256),
  l_timezoneofssp            VARCHAR2(256),
  l_bearercapability         VARCHAR2(256),
  l_chargingtime             VARCHAR2(256),
  l_waitduration             VARCHAR2(256),
  l_callduration             VARCHAR2(256),
  l_terminationreason        VARCHAR2(256),
  l_callreferencenumber      VARCHAR2(256),
  l_imei                     VARCHAR2(256),
  l_chargeduration           VARCHAR2(256),
  l_accessprefix             VARCHAR2(256),
  l_routingprefix            VARCHAR2(256),
  l_redirectingpartyid       VARCHAR2(256),
  l_brandid                  VARCHAR2(256),
  l_subcosid                 VARCHAR2(256),
  l_chargingpartynumber      VARCHAR2(256),
  l_chargepartyindicator     VARCHAR2(256),
  l_paytype                  VARCHAR2(256),
  l_billcycleid              VARCHAR2(256),
  l_chargingtype             VARCHAR2(256),
  l_calltype                 VARCHAR2(256),
  l_roamstate                VARCHAR2(256),
  l_resultcode               VARCHAR2(256),
  l_fphprefix                VARCHAR2(256),
  l_callinghomecountrycode   VARCHAR2(256),
  l_callinghomeareanumber    VARCHAR2(256),
  l_callinghomenetworkcode   VARCHAR2(256),
  l_callingroamcountrycode   VARCHAR2(256),
  l_callingroamareanumber    VARCHAR2(256),
  l_callingroamnetworkcode   VARCHAR2(256),
  l_calledhomecountrycode    VARCHAR2(256),
  l_calledhomeareanumber     VARCHAR2(256),
  l_calledhomenetworkcode    VARCHAR2(256),
  l_calledroamcountrycode    VARCHAR2(256),
  l_calledroamareanumber     VARCHAR2(256),
  l_calledroamnetworkcode    VARCHAR2(256),
  l_productid                VARCHAR2(256),
  l_servicetype              VARCHAR2(256),
  l_hotlineindicator         VARCHAR2(256),
  l_homezoneid               VARCHAR2(256),
  l_npflag                   VARCHAR2(256),
  l_npprefix                 VARCHAR2(256),
  l_callinggroupno           VARCHAR2(256),
  l_calledgroupno            VARCHAR2(256),
  l_userstate                VARCHAR2(256),
  l_subscriberid             VARCHAR2(256),
  l_opposenumbertype         VARCHAR2(256),
  l_chargeofitemsaccounts    VARCHAR2(256),
  l_chargeofdurationaccounts VARCHAR2(256),
  l_chargeoffundaccounts     VARCHAR2(256),
  l_chargefromprepaid        VARCHAR2(256),
  l_prepaidbalance           VARCHAR2(256),
  l_chargefrompostpaid       VARCHAR2(256),
  l_postpaidbalance          VARCHAR2(256),
  l_accountid                VARCHAR2(256),
  l_accountkey               VARCHAR2(256),
  l_currencycode             VARCHAR2(256),
  l_accounttype1             VARCHAR2(256),
  l_feetype1                 VARCHAR2(256),
  l_chargeamount1            VARCHAR2(256),
  l_currentacctamount1       VARCHAR2(256),
  l_accounttype2             VARCHAR2(256),
  l_feetype2                 VARCHAR2(256),
  l_chargeamount2            VARCHAR2(256),
  l_currentacctamount2       VARCHAR2(256),
  l_callingvpntopgroupnumber VARCHAR2(256),
  l_callingvpngroupnumber    VARCHAR2(256),
  l_callingvpnshortnumber    VARCHAR2(256),
  l_calledvpntopgroupnumber  VARCHAR2(256),
  l_calledvpngroupnumber     VARCHAR2(256),
  l_calledvpnshortnumber     VARCHAR2(256),
  l_callingnetworktype       VARCHAR2(256),
  l_callednetworktype        VARCHAR2(256),
  l_groupcalltype            VARCHAR2(256),
  l_grouppayflag             VARCHAR2(256),
  l_onlinetype               VARCHAR2(256),
  l_reserved                 VARCHAR2(256),
  l_addtionalinfo            VARCHAR2(256),
  l_starttimeofbillcycle     VARCHAR2(256),
  l_callingclusternumber     VARCHAR2(256),
  l_calledclusternumber      VARCHAR2(256),
  l_originalcallingparty     VARCHAR2(256),
  l_oppositepartynumber      VARCHAR2(256),
  l_diametersessionid        VARCHAR2(256),
  l_startcountrygroup        VARCHAR2(256),
  l_endcountrygroup          VARCHAR2(256),
  l_discountoflasteffproduct VARCHAR2(256),
  l_subscriberkey            VARCHAR2(256),
  l_accumulationchange       VARCHAR2(256),
  l_usageservicetype         VARCHAR2(256),
  l_sourceserialno           VARCHAR2(256),
  l_sourcesubsequence        VARCHAR2(256),
  l_acctbalchglist           VARCHAR2(256),
  l_subscribertype           VARCHAR2(256),
  l_origincdrfilename        VARCHAR2(256),
  l_curcdrlineno             VARCHAR2(256),
  l_ddsdiscountoff           VARCHAR2(256),
  l_tax                      VARCHAR2(256),
  l_secondsubscriberkey      VARCHAR2(256),
  l_secondproductid          VARCHAR2(256),
  l_setupfee                 VARCHAR2(256),
  l_opposetenantid           VARCHAR2(256),
  l_basictariffindex         VARCHAR2(256),
  l_favtariffindex           VARCHAR2(256),
  l_unround                  VARCHAR2(256),
  l_customerkey1             VARCHAR2(256),
  l_customercode1            VARCHAR2(256),
  l_customerkey2             VARCHAR2(256),
  l_customercode2            VARCHAR2(256),
  l_recchglist               VARCHAR2(256),
  l_ucbonetimefee            VARCHAR2(256),
  l_mscaddress               VARCHAR2(256),
  l_costnodiscount           VARCHAR2(256),
  l_localarea                VARCHAR2(256),
  l_costofbonus              VARCHAR2(256),
  l_costofdiscount           VARCHAR2(256),
  l_costoffinal              VARCHAR2(256),
  l_onnetindicator           VARCHAR2(256),
  l_tapname                  VARCHAR2(256),
  l_secondlocalarea          VARCHAR2(256),
  r_seq                      VARCHAR2(256),
  r_calling_number           VARCHAR2(256),
  r_called_number            VARCHAR2(256),
  r_charging_time            VARCHAR2(256),
  r_local_start_time         VARCHAR2(256),
  r_call_duration            VARCHAR2(256),
  r_charge_duration          VARCHAR2(256),
  r_main_offer_id            VARCHAR2(256),
  r_charge_offer_id          VARCHAR2(256),
  r_charge_offer_36          VARCHAR2(256),
  r_global_plan_id           VARCHAR2(256),
  r_std_event                VARCHAR2(256),
  r_flow_type                VARCHAR2(256),
  r_call_type                VARCHAR2(256),
  r_onet_flage               VARCHAR2(256),
  r_shortnumber_flag         VARCHAR2(256),
  r_roam_type                VARCHAR2(256),
  r_acct_type                VARCHAR2(256),
  r_charge_amount_pre        VARCHAR2(256),
  r_charge_amount_pos        VARCHAR2(256),
  r_total_amt                VARCHAR2(256),
  r_free_item_amt            VARCHAR2(256),
  r_free_duration_amt        VARCHAR2(256),
  r_free_flux_amt            VARCHAR2(256),
  r_free_spec_amt            VARCHAR2(256),
  r_free_unit_id             VARCHAR2(256),
  r_free_unit_type           VARCHAR2(256),
  r_free_charge_amt          VARCHAR2(256),
  r_callinghomecc            VARCHAR2(256),
  r_callinghomean            VARCHAR2(256),
  r_callinghomenc            VARCHAR2(256),
  r_callingroamcc            VARCHAR2(256),
  r_callingroaman            VARCHAR2(256),
  r_callingroamnc            VARCHAR2(256),
  r_calledhomecc             VARCHAR2(256),
  r_calledhomean             VARCHAR2(256),
  r_calledhomenc             VARCHAR2(256),
  r_calledroamcc             VARCHAR2(256),
  r_calledroaman             VARCHAR2(256),
  r_calledroamnc             VARCHAR2(256),
  r_result_code              VARCHAR2(256),
  r_charge_code              VARCHAR2(256),
  r_sub_id                   VARCHAR2(256),
  r_cust_id                  VARCHAR2(256),
  r_acct_id                  VARCHAR2(256),
  r_seq2                     VARCHAR2(256),
  row_id                     VARCHAR2(256),
  type                       VARCHAR2(256),
  reason                     VARCHAR2(256),
  remark1                    VARCHAR2(256),
  remark2                    VARCHAR2(256),
  remark3                    VARCHAR2(256),
  remark                     VARCHAR2(256),
  l_total_amt                VARCHAR2(256),
  r_offer_id                 VARCHAR2(256),
  r_total_fee                VARCHAR2(256),
  sub_id                     NUMBER(20),
  cust_id                    NUMBER(20),
  u_cust_id                  NUMBER(20),
  sub_class                  CHAR(1),
  network_type               CHAR(1),
  sub_pwd                    VARCHAR2(71),
  first_setpwd_flag          CHAR(1),
  sub_p_lang                 VARCHAR2(11),
  sub_w_lang                 VARCHAR2(11),
  sub_level                  CHAR(1),
  bs_dunning_flag            CHAR(1),
  bs_region_id               NUMBER(20),
  bs_be_id                   INTEGER,
  bs_status                  CHAR(1),
  bs_status_detail           VARCHAR2(27),
  bs_status_date             DATE,
  bs_eff_date                DATE,
  bs_exp_date                DATE,
  active_limit               DATE,
  active_time                DATE,
  tp_cust_key                VARCHAR2(67),
  cust_type                  CHAR(1),
  cust_segment               VARCHAR2(11),
  cust_class                 CHAR(1),
  cust_code                  VARCHAR2(35),
  p_cust_id                  NUMBER(20),
  cust_w_lang                VARCHAR2(11),
  cust_p_lang                VARCHAR2(11),
  bill_cycle_type            VARCHAR2(3),
  currency_id                INTEGER,
  cust_level                 CHAR(1),
  cust_loyalty               CHAR(1),
  bc_dunning_flag            CHAR(1),
  cust_status                CHAR(1),
  status_reason              VARCHAR2(11),
  bc_region_id               NUMBER(20),
  bc_be_id                   INTEGER,
  bc_eff_date                DATE,
  bc_exp_date                DATE,
  si_network_type            CHAR(1),
  sub_iden_type              VARCHAR2(7),
  sub_identity               VARCHAR2(67),
  primary_flag               CHAR(1),
  si_eff_date                DATE,
  si_exp_date                DATE,
  oi_cust_id                 NUMBER(20),
  oi_o_id                    NUMBER(20),
  oi_owner_type              CHAR(1),
  oi_owner_id                NUMBER(20),
  oi_eff_date                DATE,
  o_inst_id                  NUMBER(20),
  purchase_seq               VARCHAR2(67),
  oi_primary_flag            CHAR(1),
  oi_bundle_flag             CHAR(1),
  oi_o_class                 CHAR(1),
  p_o_inst_id                NUMBER(20),
  r_go_inst_id               NUMBER(20),
  r_group_id                 NUMBER(20),
  oi_active_mode             CHAR(1),
  oi_active_limit_time       DATE,
  oi_active_time             DATE,
  oi_trial_s_date            DATE,
  oi_trial_e_date            DATE,
  oi_status                  CHAR(1),
  oi_status_detail           VARCHAR2(27),
  oi_status_date             DATE,
  oi_exp_date                DATE,
  oi_create_time             DATE
)
;

create table COMBINEVOICE5TESTPREDICT
(
  l_seq           VARCHAR2(256),
  prediction      VARCHAR2(256),
  probability     VARCHAR2(256),
  prediction_topn VARCHAR2(256)
)
;

**Comment by cjbj** [comment]
Can you explain what this means "cause dozens of time more than normal"?  I don't understand.

Can you share the cx_Oracle code so we can see what's going on?  Please make it complete so it runs.

**Comment by kingchenchina** [comment]
sample code:
cx_Oracle.connect("username/password@host:port/database").cursor().execute(sql) 

when run sql 1, it takes about 0.5second
when run sql 2, it takes about 36seconds

**Comment by cjbj** [comment]
@kingchenchina Are you using bind variables?  Are you fetching data? Are you using the same version of the Oracle client libraries as for the DB?

**Comment by kingchenchina** [comment]
@cjbj sure, same version.
in both sql, no bind variables.
i seperate execute sql and fetch data in two steps, in this step, only time the execute duration.

**Comment by cjbj** [comment]
Have you checked the optimizer plans for both?

**Comment by cjbj** [comment]
By the way, can you check you cut & pasted the correct SQL statements.  They both contain DISTINCT.

**Comment by kingchenchina** [comment]
i check the execute plan in plsql, they are completely same.

both sql almost the same, **the only difference is a space after >=**

if no distinct, then the execute time will be the same

**Comment by cjbj** [comment]
Since cx_Oracle passes the whole SQL string to the DB, and its the DB that does the execute, I don't immediately see this as a cx_Oracle issue.

**Comment by kingchenchina** [comment]
@cjbj as the execute plan and the exact execute time is same in plsql, and different in cx_Oracle，so i think it's big probability cx_Oracle issue

**Comment by cjbj** [comment]
Running it in PL/SQL isn't a comparison with the same client libraries, so there are few things you could try: using SQL*Plus without PL/SQL.  Maybe try different versions.

But since whitespace is important, please supply a COMPLETE python file which has the two strings in it exactly as you are testing.  And some data is needed.

**Comment by cjbj** [comment]
And make sure the Python file has the calls to calculate the elapsed times.

And don't forget to use markdown, and/or gists as discussed [here](https://github.com/oracle/python-cx_Oracle/blob/master/.github/issue_template.md).

If you make it easy for people to help you, then they will help.

**Comment by kingchenchina** [comment]
i see, thanks @cjbj 
to make it clearly, summarize the issue as below.

oracle 11.2
oracle client 11.2
cx_Oracle 6.3.1
python 3.6.5
all are 64 bits,  oracle install in suse os, and oracle client in ubuntu.

the python code:
import cx_Oracle
import time

sql1=SELECT distinct * FROM (select A., ROWNUM RN FROM (SELECT cb.,cbp.prediction,cbp.probability,cbp.prediction_topn FROM combinevoice5test cb, combinevoice5testpredict cbp where cb.l_seq = cbp.l_seq and cb.remark != 'same') A WHERE ROWNUM < 5010) WHERE RN >=5000


sql2=SELECT distinct * FROM (select A., ROWNUM RN FROM (SELECT cb.,cbp.prediction,cbp.probability,cbp.prediction_topn FROM combinevoice5test cb, combinevoice5testpredict cbp where cb.l_seq = cbp.l_seq and cb.remark != 'same') A WHERE ROWNUM < 5010) WHERE RN >= 5000

start1=time.time()
cx_Oracle.connect("username/password@host:port/database").cursor().execute(sql1)
elapsed1 = time.time()-start1
print(elapsed1)
start2=time.time()
cx_Oracle.connect("username/password@host:port/database").cursor().execute(sql2)
elasped1 = time.time()=start2
print(elapsed2)

the print out is about 36seconds and 0.6second.


the first table constains about 800 thousand records, and the second table constains about 50 thousand records

below is the sql to create the table:
create table COMBINEVOICE5TEST
(
l_seq NUMBER(20),
partition_id NUMBER(4) not null,
l_legacy_system VARCHAR2(256),
l_legacy_version VARCHAR2(256),
l_subsequence VARCHAR2(256),
l_timestamp VARCHAR2(256),
l_servicekey VARCHAR2(256),
l_callingpartynumber VARCHAR2(256),
l_calledpartynumber VARCHAR2(256),
l_callingpartyimsi VARCHAR2(256),
l_calledpartyimsi VARCHAR2(256),
l_dialednumber VARCHAR2(256),
l_originalcalledparty VARCHAR2(256),
l_serviceflow VARCHAR2(256),
l_callforwardindicator VARCHAR2(256),
l_callingroaminfo VARCHAR2(256),
l_callingcellid VARCHAR2(256),
l_calledroaminfo VARCHAR2(256),
l_calledcellid VARCHAR2(256),
l_timestampofssp VARCHAR2(256),
l_timezoneofssp VARCHAR2(256),
l_bearercapability VARCHAR2(256),
l_chargingtime VARCHAR2(256),
l_waitduration VARCHAR2(256),
l_callduration VARCHAR2(256),
l_terminationreason VARCHAR2(256),
l_callreferencenumber VARCHAR2(256),
l_imei VARCHAR2(256),
l_chargeduration VARCHAR2(256),
l_accessprefix VARCHAR2(256),
l_routingprefix VARCHAR2(256),
l_redirectingpartyid VARCHAR2(256),
l_brandid VARCHAR2(256),
l_subcosid VARCHAR2(256),
l_chargingpartynumber VARCHAR2(256),
l_chargepartyindicator VARCHAR2(256),
l_paytype VARCHAR2(256),
l_billcycleid VARCHAR2(256),
l_chargingtype VARCHAR2(256),
l_calltype VARCHAR2(256),
l_roamstate VARCHAR2(256),
l_resultcode VARCHAR2(256),
l_fphprefix VARCHAR2(256),
l_callinghomecountrycode VARCHAR2(256),
l_callinghomeareanumber VARCHAR2(256),
l_callinghomenetworkcode VARCHAR2(256),
l_callingroamcountrycode VARCHAR2(256),
l_callingroamareanumber VARCHAR2(256),
l_callingroamnetworkcode VARCHAR2(256),
l_calledhomecountrycode VARCHAR2(256),
l_calledhomeareanumber VARCHAR2(256),
l_calledhomenetworkcode VARCHAR2(256),
l_calledroamcountrycode VARCHAR2(256),
l_calledroamareanumber VARCHAR2(256),
l_calledroamnetworkcode VARCHAR2(256),
l_productid VARCHAR2(256),
l_servicetype VARCHAR2(256),
l_hotlineindicator VARCHAR2(256),
l_homezoneid VARCHAR2(256),
l_npflag VARCHAR2(256),
l_npprefix VARCHAR2(256),
l_callinggroupno VARCHAR2(256),
l_calledgroupno VARCHAR2(256),
l_userstate VARCHAR2(256),
l_subscriberid VARCHAR2(256),
l_opposenumbertype VARCHAR2(256),
l_chargeofitemsaccounts VARCHAR2(256),
l_chargeofdurationaccounts VARCHAR2(256),
l_chargeoffundaccounts VARCHAR2(256),
l_chargefromprepaid VARCHAR2(256),
l_prepaidbalance VARCHAR2(256),
l_chargefrompostpaid VARCHAR2(256),
l_postpaidbalance VARCHAR2(256),
l_accountid VARCHAR2(256),
l_accountkey VARCHAR2(256),
l_currencycode VARCHAR2(256),
l_accounttype1 VARCHAR2(256),
l_feetype1 VARCHAR2(256),
l_chargeamount1 VARCHAR2(256),
l_currentacctamount1 VARCHAR2(256),
l_accounttype2 VARCHAR2(256),
l_feetype2 VARCHAR2(256),
l_chargeamount2 VARCHAR2(256),
l_currentacctamount2 VARCHAR2(256),
l_callingvpntopgroupnumber VARCHAR2(256),
l_callingvpngroupnumber VARCHAR2(256),
l_callingvpnshortnumber VARCHAR2(256),
l_calledvpntopgroupnumber VARCHAR2(256),
l_calledvpngroupnumber VARCHAR2(256),
l_calledvpnshortnumber VARCHAR2(256),
l_callingnetworktype VARCHAR2(256),
l_callednetworktype VARCHAR2(256),
l_groupcalltype VARCHAR2(256),
l_grouppayflag VARCHAR2(256),
l_onlinetype VARCHAR2(256),
l_reserved VARCHAR2(256),
l_addtionalinfo VARCHAR2(256),
l_starttimeofbillcycle VARCHAR2(256),
l_callingclusternumber VARCHAR2(256),
l_calledclusternumber VARCHAR2(256),
l_originalcallingparty VARCHAR2(256),
l_oppositepartynumber VARCHAR2(256),
l_diametersessionid VARCHAR2(256),
l_startcountrygroup VARCHAR2(256),
l_endcountrygroup VARCHAR2(256),
l_discountoflasteffproduct VARCHAR2(256),
l_subscriberkey VARCHAR2(256),
l_accumulationchange VARCHAR2(256),
l_usageservicetype VARCHAR2(256),
l_sourceserialno VARCHAR2(256),
l_sourcesubsequence VARCHAR2(256),
l_acctbalchglist VARCHAR2(256),
l_subscribertype VARCHAR2(256),
l_origincdrfilename VARCHAR2(256),
l_curcdrlineno VARCHAR2(256),
l_ddsdiscountoff VARCHAR2(256),
l_tax VARCHAR2(256),
l_secondsubscriberkey VARCHAR2(256),
l_secondproductid VARCHAR2(256),
l_setupfee VARCHAR2(256),
l_opposetenantid VARCHAR2(256),
l_basictariffindex VARCHAR2(256),
l_favtariffindex VARCHAR2(256),
l_unround VARCHAR2(256),
l_customerkey1 VARCHAR2(256),
l_customercode1 VARCHAR2(256),
l_customerkey2 VARCHAR2(256),
l_customercode2 VARCHAR2(256),
l_recchglist VARCHAR2(256),
l_ucbonetimefee VARCHAR2(256),
l_mscaddress VARCHAR2(256),
l_costnodiscount VARCHAR2(256),
l_localarea VARCHAR2(256),
l_costofbonus VARCHAR2(256),
l_costofdiscount VARCHAR2(256),
l_costoffinal VARCHAR2(256),
l_onnetindicator VARCHAR2(256),
l_tapname VARCHAR2(256),
l_secondlocalarea VARCHAR2(256),
r_seq VARCHAR2(256),
r_calling_number VARCHAR2(256),
r_called_number VARCHAR2(256),
r_charging_time VARCHAR2(256),
r_local_start_time VARCHAR2(256),
r_call_duration VARCHAR2(256),
r_charge_duration VARCHAR2(256),
r_main_offer_id VARCHAR2(256),
r_charge_offer_id VARCHAR2(256),
r_charge_offer_36 VARCHAR2(256),
r_global_plan_id VARCHAR2(256),
r_std_event VARCHAR2(256),
r_flow_type VARCHAR2(256),
r_call_type VARCHAR2(256),
r_onet_flage VARCHAR2(256),
r_shortnumber_flag VARCHAR2(256),
r_roam_type VARCHAR2(256),
r_acct_type VARCHAR2(256),
r_charge_amount_pre VARCHAR2(256),
r_charge_amount_pos VARCHAR2(256),
r_total_amt VARCHAR2(256),
r_free_item_amt VARCHAR2(256),
r_free_duration_amt VARCHAR2(256),
r_free_flux_amt VARCHAR2(256),
r_free_spec_amt VARCHAR2(256),
r_free_unit_id VARCHAR2(256),
r_free_unit_type VARCHAR2(256),
r_free_charge_amt VARCHAR2(256),
r_callinghomecc VARCHAR2(256),
r_callinghomean VARCHAR2(256),
r_callinghomenc VARCHAR2(256),
r_callingroamcc VARCHAR2(256),
r_callingroaman VARCHAR2(256),
r_callingroamnc VARCHAR2(256),
r_calledhomecc VARCHAR2(256),
r_calledhomean VARCHAR2(256),
r_calledhomenc VARCHAR2(256),
r_calledroamcc VARCHAR2(256),
r_calledroaman VARCHAR2(256),
r_calledroamnc VARCHAR2(256),
r_result_code VARCHAR2(256),
r_charge_code VARCHAR2(256),
r_sub_id VARCHAR2(256),
r_cust_id VARCHAR2(256),
r_acct_id VARCHAR2(256),
r_seq2 VARCHAR2(256),
row_id VARCHAR2(256),
type VARCHAR2(256),
reason VARCHAR2(256),
remark1 VARCHAR2(256),
remark2 VARCHAR2(256),
remark3 VARCHAR2(256),
remark VARCHAR2(256),
l_total_amt VARCHAR2(256),
r_offer_id VARCHAR2(256),
r_total_fee VARCHAR2(256),
sub_id NUMBER(20),
cust_id NUMBER(20),
u_cust_id NUMBER(20),
sub_class CHAR(1),
network_type CHAR(1),
sub_pwd VARCHAR2(71),
first_setpwd_flag CHAR(1),
sub_p_lang VARCHAR2(11),
sub_w_lang VARCHAR2(11),
sub_level CHAR(1),
bs_dunning_flag CHAR(1),
bs_region_id NUMBER(20),
bs_be_id INTEGER,
bs_status CHAR(1),
bs_status_detail VARCHAR2(27),
bs_status_date DATE,
bs_eff_date DATE,
bs_exp_date DATE,
active_limit DATE,
active_time DATE,
tp_cust_key VARCHAR2(67),
cust_type CHAR(1),
cust_segment VARCHAR2(11),
cust_class CHAR(1),
cust_code VARCHAR2(35),
p_cust_id NUMBER(20),
cust_w_lang VARCHAR2(11),
cust_p_lang VARCHAR2(11),
bill_cycle_type VARCHAR2(3),
currency_id INTEGER,
cust_level CHAR(1),
cust_loyalty CHAR(1),
bc_dunning_flag CHAR(1),
cust_status CHAR(1),
status_reason VARCHAR2(11),
bc_region_id NUMBER(20),
bc_be_id INTEGER,
bc_eff_date DATE,
bc_exp_date DATE,
si_network_type CHAR(1),
sub_iden_type VARCHAR2(7),
sub_identity VARCHAR2(67),
primary_flag CHAR(1),
si_eff_date DATE,
si_exp_date DATE,
oi_cust_id NUMBER(20),
oi_o_id NUMBER(20),
oi_owner_type CHAR(1),
oi_owner_id NUMBER(20),
oi_eff_date DATE,
o_inst_id NUMBER(20),
purchase_seq VARCHAR2(67),
oi_primary_flag CHAR(1),
oi_bundle_flag CHAR(1),
oi_o_class CHAR(1),
p_o_inst_id NUMBER(20),
r_go_inst_id NUMBER(20),
r_group_id NUMBER(20),
oi_active_mode CHAR(1),
oi_active_limit_time DATE,
oi_active_time DATE,
oi_trial_s_date DATE,
oi_trial_e_date DATE,
oi_status CHAR(1),
oi_status_detail VARCHAR2(27),
oi_status_date DATE,
oi_exp_date DATE,
oi_create_time DATE
)
;

create table COMBINEVOICE5TESTPREDICT
(
l_seq VARCHAR2(256),
prediction VARCHAR2(256),
probability VARCHAR2(256),
prediction_topn VARCHAR2(256)
)
;

**Comment by cjbj** [comment]
Please see my previous comments https://github.com/oracle/python-cx_Oracle/issues/195#issuecomment-400549185 and  https://github.com/oracle/python-cx_Oracle/issues/195#issuecomment-400549793.  We need a runnable Python script. Thanks!

**Comment by cjbj** [comment]
Oh, sorry missed it because you weren't using markdown.

**Comment by cjbj** [comment]
@kingchenchina we do appreciate you taking time on this, when you could have just used the workaround and not reported it.

**Comment by anthony-tuininga** [comment]
@kingchenchina, thanks for the create table statements and Python code, but as Chris mentioned, without the data we can't run it and confirm your findings. I also agree with Chris that this is very unlikely to be a cx_Oracle specific issue since cx_Oracle doesn't actually do anything with the SQL but passes it directly through to the database. So I suspect this is an optimiser issue, but if you can provide a means of getting the data (preferably by procedure not an actual dump with that much data!) then we can take a look.

**Comment by marksteward** [comment]
This is a regular nightmare with Oracle, but not cx_Oracle's fault. Get all the sql_ids (which will probably be different between cx_Oracle and sqlplus):

```
select distinct sql_id, child_number, first_load_time from gv$sql where sql_fulltext like '%same%5010) WHERE RN >= 5000%' and sql_fulltext not like '%v$sql%';
```

and then dump the plan for each:

```
select * from table(dbms_xplan.display_cursor('&sql_id', &child_number));
```

One of them will have the bad plan, and one the good plan. The make-up of the data may have changed since then, for better or worse. Make sure you've gathered stats on your tables, and hope it's not something where Oracle needs a hint or outline.

You should find that adding a random comment to the query will result in a new sql_id and so new plan, and purging the cursor or performing DDL on the table will invalidate the existing ones.

**Comment by anthony-tuininga** [comment]
I trust that Mark answered your question due to the lack of activity.
