### ISSUE TITLE
Python 3.7 manylinux1 wheel

### ISSUE THREAD

**Issue by mkai** [oracle/python-cx_Oracle#196]
Hi,

I am looking for a x86_64 manylinux1 compatible wheel for Python 3.7, similar to the one already provided on PyPI for Python 3.6.

If you could share your wheel build configuration I will be glad to help building one.

**Comment by anthony-tuininga** [comment]
Hi, I plan to release Python 3.7 wheels (and cx_Oracle 6.4) very soon. Stay tuned! As for the build configuration, I use the Docker image provided here: quay.io/pypa/manylinux1_x86_64.

**Comment by anthony-tuininga** [comment]
cx_Oracle 6.4 has been released with Python 3.7 wheels. Enjoy!

**Comment by mkai** [comment]
Thank you. Great work!
