### ISSUE TITLE
cx_Oracle.InterfaceError: Unable to acquire Oracle environment handle

### ISSUE THREAD

**Issue by desmondblue** [oracle/python-cx_Oracle#197]
I have been at google since morning. I have been able to succesfully install cx_Oracle with its appropriate version of python.
Now that all has been done. I get the error as mentioned in the header.
I want to eradicate that error. I want to create a table, insert rows into it and do the task.
I have to complete an assignment by day after. And I am tired of searching irrelevant answers online.
Please help me with my issue.

1. What is your version of Python? Is it 32-bit or 64-bit?
Python 3.5.0. 64 bit
Executable name : python-3.5.0-amd64
2. What is your version of cx_Oracle?
Executable name: cx_Oracle-5.2.1-11g.win-amd64-py3.5
64-bit version 5.2.1
3. What is your version of the Oracle client (e.g. Instant Client)?  How was it
   installed?  Where is it installed?
Oracle Database Express Edition 11g Release 2:June 4, 2014
It was installed by downloading from the site and using the setup. I have no idea what is an instant client since am a beginner.
It is installed in E:\Oracle11g
From command prompt:
echo %oracle_home%
E:\Oracle11g\app\oracle
4. What is your version of the Oracle Database?
11g release 2. I do not know how to check the version
5. What is your OS and version?
Microsoft windows 10 pro and Version	10.0.16299 
6. What compiler version did you use?  (For example, with GCC, run  `gcc --version`.)
I am using python on windows. I guess it utilises microsoft visual c++.
I have Microsoft Visual C++ 2010 X64 Redistributable - 10.0.40219
Also:
7. What environment variables did you set?  How *exactly* did you set them?
I went to environmental variables and added them directly.
ORACLE_HOME to E:\Oracle11g\app\oracle
PYTHONPATH to E:\Python\python.exe
8. What *exact* command caused the problem (e.g. what command did you try to
   install with)?  Who were you logged in as?
I guess I logged in as system.
Problem Code:
import cx_Oracle
con = cx_Oracle.connect("system/therockstar@localhost/xe")
cur = con.cursor()
#delete rows

statement = 'create table Employer( CompanyID VARCHAR2(5), CompanyName VARCHAR2(30),EmailId VARCHAR2(20), Mobile NUMBER(10),City VARCHAR2(20), IndustryType VARCHAR2(20),FunctionalArea VARCHAR2(20),MembershipPlan VARCHAR2(20),DateofSignup Date, DateofRenewal Date, RenewalStatus VARCHAR2(20))'

cur.execute(statement)

statement = "insert into Employer values('C1000','Infosys Limited', 'jobs@infosys.com',7986579875,'Chennai','IT','Accounting','Yearly','1-Jul-16','30-Jun-17','Active')"
cur.execute(statement)
con.close()
9. What error(s) you are seeing?

  File "E:\executables\python\module3\test.py", line 2, in <module>
    con = cx_Oracle.connect("system/therockstar@localhost/xe")
cx_Oracle.InterfaceError: Unable to acquire Oracle environment handle

**Comment by anthony-tuininga** [comment]
Please upgrade your copy of cx_Oracle to 6.3. That version contains code that should provide a better error message. For installation, see [here](http://cx-oracle.readthedocs.io/en/latest/installation.html) and examine it carefully to see if there is any step you missed or something you shouldn't have done. For example, on Windows you shouldn't be setting the environment variable ORACLE_HOME. You should only set the PATH environment variable.

**Comment by desmondblue** [comment]
Hey anthony. I felt it a coincidence to find you here since you were the one who answered my stackoverflow question too earlier this day.
I did not understand what you meant by path variable?

**Comment by anthony-tuininga** [comment]
Take a look at the installation [documentation](http://cx-oracle.readthedocs.io/en/latest/installation.html#id4)  and note the information on setting the PATH environment variable.

BTW, if cx_Oracle is installed in the "normal" place (as would be done by pip) then you don't need to set the environment variable PYTHONPATH either. Make sure that the version you are using is the right one by simply issuing these commands (in Python):

```python
import cx_Oracle
print("Location:", cx_Oracle)
print("Version:", cx_Oracle.__version__)
```

**Comment by desmondblue** [comment]
Hey So I came up with these:
>>> print("Location",cx_Oracle)
Location <module 'cx_Oracle' from 'E:\\Python\\lib\\site-packages\\cx_Oracle.cp35-win_amd64.pyd'>
>>> print("Version",cx_Oracle.__version__)
Version 5.2.1
>>> 
Anything helpful?
I have had my mind so stretched I think its behaving like a toddler's.

**Comment by anthony-tuininga** [comment]
LOL. Yes, that tells you that you have an older version of cx_Oracle installed (5.2.1). So you need to delete that file (the one pointed to by the location you printed). You should be able to do "python -m pip uninstall cx_Oracle" but if that doesn't work just delete the file directly. Then do an install again to make sure that the 6.3.1 version is installed.

**Comment by desmondblue** [comment]
Hey Anthony :D Thanks . I got past that. just to be stuck with
Traceback (most recent call last):
  File "E:\executables\python\module3\test.py", line 2, in <module>
    con = cx_Oracle.connect("system/therockstar@localhost/xe")
cx_Oracle.DatabaseError: Error while trying to retrieve text for error ORA-01804
Please help out

**Comment by anthony-tuininga** [comment]
That's a slightly better error message. :-) Effectively it is telling you your installation is messed up. Did you remove the environment variable ORACLE_HOME? You can also search your system for all copies of oci.dll. If you've got multiple installations that's going to be a potential issue. Make sure that your PATH environment variable has the one you want first.

**Comment by desmondblue** [comment]
As in I should create an environment variable named PATH and provide the location of the Oracle database to it?

**Comment by anthony-tuininga** [comment]
The environment variable PATH is already there, I'm sure and is a special environment variable. See the [documentation](http://cx-oracle.readthedocs.io/en/latest/installation.html#id4) and note the instructions there.

**Comment by desmondblue** [comment]
I have checked for multiple oci.dll, I have set the correct path still I keep getting the same error.
I just want cx_Oracle to work so I can finish up my 10 assignments real quick. 
And I appreciate your help very much Sir. If not for you I would have been wandering the internet aimlessly,

**Comment by desmondblue** [comment]
Okay . So I guess I made it through. I got to a new error.
cx_Oracle.DatabaseError: ORA-12514: TNS:listener does not currently know of service requested in connect descriptor

**Comment by anthony-tuininga** [comment]
Yes, you did manage to make it through. :-) Now you just need to check your listener configuration. What is the connect string you are using? And what is the output of "lsnrctl status"?

**Comment by desmondblue** [comment]
Connect string:
con = cx_Oracle.connect("system/therockstar@localhost/xe")
Output of lsnrctl:
LSNRCTL for 64-bit Windows: Version 11.2.0.2.0 - Production on 29-JUN-2018 23:34:42

Copyright (c) 1991, 2014, Oracle.  All rights reserved.

Welcome to LSNRCTL, type "help" for information.

I have just started into oracle database handling day before yesterday So I am trying my best to cope up.
How to check or edit or set listener configuration?

**Comment by desmondblue** [comment]
In listener.ora I added
LOCALDB =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = DESKTOP-9CL97GV)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = LOCALDB)
    )
  ) 
and under SID_LIST_LISTENER I added
(SID_DESC =
      (GLOBAL_DBNAME = LOCALDB)
      (ORACLE_HOME = E:\Oracle11g\app\oracle\product\11.2.0\database)
      (SID_NAME = LOCALDB)
    )
  )
while under tnsnames.ora I added:
LOCALDB =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = localhost)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = LOCALDB)
    )
  )
I was able to start the listener but I still am getting the error : 
cx_Oracle.DatabaseError: ORA-12514: TNS:listener does not currently know of service requested in connect descriptor

**Comment by anthony-tuininga** [comment]
I thought the database was called XE? Why do you have LOCALDB there? Also, you generally don't need listener.ora to be created and used. When you run "lnsrctl status" you should see a list of the services that it knows and understands. You should also avoid using SID_NAME and use SERVICE_NAME instead. The EZ connect syntax "user/pw@host/XE" where XE is the service name is the simplest to use, but you can use tnsnames.ora as well. You should be able to use the command "tnsping localdb" to see if your configuration is correct. If you started the listener *after* you started the database you can also issue the command "alter system register" as SYSDBA.

**Comment by desmondblue** [comment]
Okay So all that was done after researching on the internet. I have restored everything to default.
I have gotten way-way confused. Please just tell me the code I should probably enter in my connect statement, that will successfully let me connect with the local hosted database.
I just want to start coding as I am running out of time and being confused more and more with how to connect with the localhost is not helping. Please help.

**Comment by anthony-tuininga** [comment]
Can you connect using SQL\*Plus? If so, whatever you use there should also work within cx_Oracle. In other words, does this work for you?

sqlplus system/therockstar@localhost/XE

If not, you can check the output of "lsnrctl status".  Mine looks like the following:

```
LSNRCTL for Linux: Version 12.2.0.1.0 - Production on 29-JUN-2018 12:47:59

Copyright (c) 1991, 2016, Oracle.  All rights reserved.

Connecting to (ADDRESS=(PROTOCOL=tcp)(HOST=)(PORT=1521))
STATUS of the LISTENER
------------------------
Alias                     LISTENER
Version                   TNSLSNR for Linux: Version 18.0.0.0.0 - Production
Start Date                27-JUN-2018 00:15:09
Uptime                    2 days 12 hr. 32 min. 49 sec
Trace Level               off
Security                  ON: Local OS Authentication
SNMP                      OFF
Listener Log File         /usr/oracle/diag/tnslsnr/lobi7/listener/alert/log.xml
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=lobi7)(PORT=1521)))
Services Summary...
Service "T122" has 1 instance(s).
  Instance "T122", status READY, has 2 handler(s) for this service...
Service "T122XDB" has 1 instance(s).
  Instance "T122", status READY, has 1 handler(s) for this service...
The command completed successfully
```

Yours should look something like it -- with the banner being different of course since you are using 11g on Windows.

**Comment by desmondblue** [comment]
Sir
As I told you I just started working with oracle database day before yesterday so, I only have the knowledge of cx_oracle
Here I tried doing this:
con = cx_Oracle.connect("system/therockstar@localhost/xe")

error message:
    con = cx_Oracle.connect("system/therockstar@localhost/xe")
cx_Oracle.OperationalError: ORA-01034: ORACLE not available
ORA-27101: shared memory realm does not exist
Process ID: 0
Session ID: 0 Serial number: 0
listener.ora
(SID_DESC =
		(GLOBAL_DBNAME = XE)
		(ORACLE_HOME = E:\Oracle11g\app\oracle\product\11.2.0\server)
		(SID_NAME = xe)
	)
)
tsnnames.ora
XE =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = localhost)(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = XE)
    )
  )
lsnrctl status:
LSNRCTL for 64-bit Windows: Version 11.2.0.2.0 - Production on 30-JUN-2018 01:22:40

Copyright (c) 1991, 2014, Oracle.  All rights reserved.

Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC1)))
STATUS of the LISTENER
------------------------
Alias                     LISTENER
Version                   TNSLSNR for 64-bit Windows: Version 11.2.0.2.0 - Production
Start Date                30-JUN-2018 01:22:36
Uptime                    0 days 0 hr. 0 min. 6 sec
Trace Level               off
Security                  ON: Local OS Authentication
SNMP                      OFF
Default Service           XE
Listener Parameter File   E:\Oracle11g\app\oracle\product\11.2.0\server\network\admin\listener.ora
Listener Log File         E:\Oracle11g\app\oracle\diag\tnslsnr\DESKTOP-9CL97GV\listener\alert\log.xml
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(PIPENAME=\\.\pipe\EXTPROC1ipc)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=DESKTOP-9CL97GV)(PORT=1521)))
Services Summary...
Service "CLRExtProc" has 1 instance(s).
  Instance "CLRExtProc", status UNKNOWN, has 1 handler(s) for this service...
Service "PLSExtProc" has 1 instance(s).
  Instance "PLSExtProc", status UNKNOWN, has 1 handler(s) for this service...
Service "XE" has 1 instance(s).
  Instance "xe", status UNKNOWN, has 1 handler(s) for this service...
The command completed successfully

**Comment by anthony-tuininga** [comment]
I understand that it is a lot to take in so bear with me. :-)

So the error you got just indicated that the database hasn't been started. Start the database. On Windows this is usually a service that you can start. If that doesn't work its a bit more complicated, so hopefully that works for you. It may be set up to autostart so rebooting might "solve" it for you.

**Comment by desmondblue** [comment]
Oh. Yes I forgot to ask how to restart the database.
And please Sir you are too modest, I highly appreciate you taking the time to solve my problem if anything I should thank you heartily for bearing with me.
I will try finding the service to start.

**Comment by desmondblue** [comment]
Sir I found the service name. Oracle ServiceXE which belongs to Oracle database
I restarted it then restarted listener after it. 
Still I am getting the same error.

**Comment by desmondblue** [comment]
If I don't mention the below lines/service in **listener.ora** then I get the error (ORA-12514: TNS:listener does not currently know of service requested in connect descriptor)
(SID_DESC =
		(SID_NAME = xe)
		(GLOBAL_DBNAME = XE)
		(ORACLE_HOME = E:\Oracle11g\app\oracle\product\11.2.0\server)
	)
But when I do put these lines then I am encountering following error:
ORA-27101: shared memory realm does not exist
Process ID: 0
Session ID: 0 Serial number: 0

**Comment by anthony-tuininga** [comment]
You shouldn't restart the listener. Remove listener.ora and restart the listener, then restart the database. Then run 'lsnrctl status' and report back. It should show that a service is "READY".

**Comment by desmondblue** [comment]
As in I should delete listener.ORA?

**Comment by anthony-tuininga** [comment]
That looks like it might be okay. Do you still get the same error now? Run this command

```
sqlplus system/therockstar@localhost/XE
```

**Comment by desmondblue** [comment]
I should run this command on cmd or idle ?

**Comment by anthony-tuininga** [comment]
In the command prompt. And if you have XE you have SQLPlus as well.

**Comment by desmondblue** [comment]
Sir. I reinstalled the entire database.
lsnrctl status:

LSNRCTL for 64-bit Windows: Version 11.2.0.2.0 - Production on 30-JUN-2018 02:13:47

Copyright (c) 1991, 2014, Oracle.  All rights reserved.

Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC1)))
STATUS of the LISTENER
------------------------
Alias                     LISTENER
Version                   TNSLSNR for 64-bit Windows: Version 11.2.0.2.0 - Production
Start Date                30-JUN-2018 02:10:05
Uptime                    0 days 0 hr. 3 min. 41 sec
Trace Level               off
Security                  ON: Local OS Authentication
SNMP                      OFF
Default Service           XE
Listener Parameter File   E:\Oracle11g\app\oracle\product\11.2.0\server\network\admin\listener.ora
Listener Log File         E:\Oracle11g\app\oracle\diag\tnslsnr\DESKTOP-9CL97GV\listener\alert\log.xml
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(PIPENAME=\\.\pipe\EXTPROC1ipc)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=DESKTOP-9CL97GV)(PORT=1521)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=DESKTOP-9CL97GV)(PORT=8080))(Presentation=HTTP)(Session=RAW))
Services Summary...
Service "CLRExtProc" has 1 instance(s).
  Instance "CLRExtProc", status UNKNOWN, has 1 handler(s) for this service...
Service "PLSExtProc" has 1 instance(s).
  Instance "PLSExtProc", status UNKNOWN, has 1 handler(s) for this service...
Service "XEXDB" has 1 instance(s).
  Instance "xe", status READY, has 1 handler(s) for this service...
Service "xe" has 1 instance(s).
  Instance "xe", status READY, has 1 handler(s) for this service...
The command completed successfully

C:\WINDOWS\system32>

**Comment by anthony-tuininga** [comment]
That looks correct now. It shows that service "XE" is READY. :-)

**Comment by desmondblue** [comment]
import cx_Oracle
con = cx_Oracle.connect("system/therockstar@localhost/xe")
cur = con.cursor()
#delete rows

statement = 'create table Employer( CompanyID VARCHAR2(5), CompanyName VARCHAR2(30),EmailId VARCHAR2(20), Mobile NUMBER(10),City VARCHAR2(20), IndustryType VARCHAR2(20),FunctionalArea VARCHAR2(20),MembershipPlan VARCHAR2(20),DateofSignup Date, DateofRenewal Date, RenewalStatus VARCHAR2(20))'

cur.execute(statement)

statement = "insert into Employer values('C1000','Infosys Limited', 'jobs@infosys.com',7986579875,'Chennai','IT','Accounting','Yearly','1-Jul-16','30-Jun-17','Active')"
cur.execute(statement)
#statement = "insert into Employer values
statement1 = 'select *FROM Employer'
cur.execute(statement1)
con.close()

LOL. Now I have this error:
    cur.execute(statement)
cx_Oracle.DatabaseError: ORA-00955: name is already used by an existing object

**Comment by anthony-tuininga** [comment]
Of course. If the table exists then you'll get that error. Normally those commands are only executed once.

But it looks like your database is up and running now and you are able to connect. :) So I think we can close this issue!

**Comment by anthony-tuininga** [comment]
Well, you already connected to the database. :-) Ordinarily you would use sqlplus to create a new user instead of using "system" -- since that is generally reserved for the system itself! So

```
sqlplus system/therockstar@localhost/XE
```

Then within that you would use the following commands, replacing "myuser" with whatever content you would like:

```
create user myuser identified by mypassword;
grant create session, create table, create procedure, create sequence to myuser;
exit
```

But all of that gets into ordinary Oracle database administration and development and is nowhere close to on topic for this issue. ;-)
