### ISSUE TITLE
Unable to acquire Oracle environment handle

### ISSUE THREAD

**Issue by genomics-geek** [oracle/python-cx_Oracle#20]
I followed the instructions [here](http://www.oracle.com/technetwork/topics/intel-macsoft-096467.html#ic_osx_inst).  

I downloaded the instantclient and unzipped in `$HOME/Resources/oracle/`

After the installation I ran `sqlplus hr/welcome@localhost/orcl` and was able to connect using credentials for my database.

I then installed cx_Oracle with pip.  However, when I try to connect:

```python
import cx_Oracle
conn = cx_Oracle.connect('hr/welcome@localhost/orcl')
```

I get the following error:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
cx_Oracle.InterfaceError: Unable to acquire Oracle environment handle
```

I have looked online for a solution and have tried this:
[setting os env](http://stackoverflow.com/questions/13589683/interfaceerror-unable-to-acquire-oracle-environment-handle-oracle-home-is-corr).

```python
import os
import cx_Oracle

os.environ['DYLD_LIBRARY_PATH'] = '/Users/gonzalezma/Resources/oracle/instantclient_11_2'

conn = cx_Oracle.connect('hr/welcome@localhost/orcl')
```

Still does not work.  I have looked online, but have yet to find a solution.  

#### Answer the following questions:

1. What is your version of Python? Is it 32-bit or 64-bit? 
+ Python 3.5.2 64-bit

2. What is your version of cx_Oracle?
+ cx-Oracle==5.3

3. What is your version of the Oracle client (e.g. Instant Client)?  How was it
   installed?  Where is it installed?
+ It was installed from here: http://www.oracle.com/technetwork/topics/intel-macsoft-096467.html I Installed instantclient_11_2 and instantclient_12_1 -- both give me the same error.  I downloaded the sdk and basic files. They were installed to `$HOME/Resources/oracle/`

4. What is your OS and version?

+ MacOSX 10.11.6

5. What compiler version did you use?  For example, with GCC, run
   `gcc --version`.

```
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
````

6. What environment variables did you set?  How *exactly* did you set them?

```
export ORACLE_HOME="$HOME/Resources/oracle/instantclient_11_2"
export DYLD_LIBRARY_PATH="$ORACLE_HOME:$DYLD_LIBRARY_PATH"
export PATH=$PATH:/Users/gonzalezma/Resources/oracle/instantclient_11_2
```

7. What *exact* command caused the problem (e.g. what command did you try to
   install with)?  Who were you logged in as?

+ I was able to successfully install with pip.  This is the command that gave me the error.

```python
import cx_Oracle

conn_str = user + '/' + pw + '@' + host + ':' + port + '/' + service
conn = cx_Oracle.connect(conn_str)
```

8. What error(s) you are seeing?

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
cx_Oracle.InterfaceError: Unable to acquire Oracle environment handle
```

**Comment by cjbj** [comment]
In recent macOS versions, `DYLD_LIBRARY_PATH` doesn't work (in subshells).  Because of this restriction, use the 12.1 instant client which is linked differently to 11.2 on macOS.  Check you have the sym link correctly set.  Make sure the Instant Client files are accessible to the user executing Python.  Clean up and try again.  You might try setting the environment variable FORCE_RPATH=1 before installation.  I'll let @anthony-tuininga comment more.

**Comment by anthony-tuininga** [comment]
A few additional comments:

- You should not set the environment variable ORACLE_HOME for instant client installations
- If you compile cx_Oracle with 11.2 then you must use 11.2 client libraries; you cannot use 12.1 client libraries and vice versa (with one exception: read on)
- if you download and install cx_Oracle 6.0b1 then during compilation no environment variables need to be set at all and the resulting module will work against 11.2 or 12.1 without changes
- your instant client installation must be 64-bit if your Python installation is 64-bit and your instant client installation must be 32-bit if your Python installation is 32-bit; no mixing and matching!

Hopefully some of those along with the ones mentioned by Chris will help you out.

**Comment by anthony-tuininga** [comment]
Did any of the above answers resolve your issues?

**Comment by genomics-geek** [comment]
Yes, I got it working now.  Thanks!

**Comment by anthony-tuininga** [comment]
No problem. Thanks for letting me know.
