### ISSUE TITLE
libclntsh.so can not be loaded, although instllation instructions were followed

### ISSUE THREAD

**Issue by tkasparek** [oracle/python-cx_Oracle#203]
1. What is your version of Python? Is it 32-bit or 64-bit?
64 bit, tried both python2 and python3

2. What is your version of cx_Oracle?
6.4.1

3. What is your version of the Oracle client (e.g. Instant Client)?  How was it
   installed?  Where is it installed?
oracle-instantclient12.2-basic-12.2.0.1.0-1.x86_64

Installed files:
/usr/lib/oracle/12.2/client64/bin/adrci
/usr/lib/oracle/12.2/client64/bin/genezi
/usr/lib/oracle/12.2/client64/lib/libclntsh.so.12.1
/usr/lib/oracle/12.2/client64/lib/libclntshcore.so.12.1
/usr/lib/oracle/12.2/client64/lib/libipc1.so
/usr/lib/oracle/12.2/client64/lib/libmql1.so
/usr/lib/oracle/12.2/client64/lib/libnnz12.so
/usr/lib/oracle/12.2/client64/lib/libocci.so.12.1
/usr/lib/oracle/12.2/client64/lib/libociei.so
/usr/lib/oracle/12.2/client64/lib/libocijdbc12.so
/usr/lib/oracle/12.2/client64/lib/libons.so
/usr/lib/oracle/12.2/client64/lib/liboramysql12.so
/usr/lib/oracle/12.2/client64/lib/ojdbc8.jar
/usr/lib/oracle/12.2/client64/lib/xstreams.jar

4. What is your version of the Oracle Database?
Does not apply as cx_Oracle does not even start.

5. What is your OS and version?
Fedora 28

6. What compiler version did you use?
gcc (GCC) 8.1.1 20180502 (Red Hat 8.1.1-1)

7. What environment variables did you set?  How *exactly* did you set them?
Tried both solutions mentioned in the installation guide
sudo sh -c "echo /usr/lib/oracle/12.2/client64/lib > /etc/ld.so.conf.d/oracle-instantclient.conf"
sudo ldconfig

and

export LD_LIBRARY_PATH=/usr/lib/oracle/12.2/client64/lib:$LD_LIBRARY_PATH

8. What *exact* command caused the problem (e.g. what command did you try to
   install with)?  Who were you logged in as?

#!/usr/bin/python3
  
import cx_Oracle

connection = cx_Oracle.connect('tkasparek', '********', 'example.com')

9. What error(s) you are seeing?
Traceback (most recent call last):
  File "./query.py", line 5, in <module>
    connection = cx_Oracle.connect('tkasparek', '*********', 'example.com')
cx_Oracle.DatabaseError: DPI-1047: 64-bit Oracle Client library cannot be loaded: "libclntsh.so: cannot open shared object file: No such file or directory". See https://oracle.github.io/odpi/doc/installation.html#linux for help

**Comment by anthony-tuininga** [comment]
Can you examine the output of

`ls -l /usr/lib/oracle/12.2/client64/lib`

I'm wondering if the symbolic link `libclntsh.so` is missing.

**Comment by cjbj** [comment]
Check libnsl as discussed in https://github.com/oracle/node-oracledb/issues/892

**Comment by tkasparek** [comment]
Hello,

ls -l /usr/lib/oracle/12.2/client64/lib
total 216260
-rw-rwxr--. 1 root root   8033199 Jan 26  2017 libclntshcore.so.12.1
-rw-rwxr--. 1 root root  71638263 Jan 26  2017 libclntsh.so.12.1
-rw-rwxr--. 1 root root   2981501 Jan 26  2017 libipc1.so
-rw-rwxr--. 1 root root    539065 Jan 26  2017 libmql1.so
-rw-rwxr--. 1 root root   6568149 Jan 26  2017 libnnz12.so
-rw-rwxr--. 1 root root   2218687 Jan 26  2017 libocci.so.12.1
-rw-rwxr--. 1 root root 124771800 Jan 26  2017 libociei.so
-rw-rwxr--. 1 root root    158543 Jan 26  2017 libocijdbc12.so
-rw-rwxr--. 1 root root    380996 Jan 26  2017 libons.so
-rw-rwxr--. 1 root root    116563 Jan 26  2017 liboramysql12.so
-rw-r--r--. 1 root root   3984814 Jan 26  2017 ojdbc8.jar
-rw-r--r--. 1 root root     37494 Jan 26  2017 xstreams.jar

I've tried to created a symlink libclntsh.so -> libclntsh.so.12.1, however I am still facing the same issue.
