### ISSUE TITLE
I am a new Python user.  I am currently trying to get my environment setup correctly on a new laptop.  When I try to execut a script I get the following error.  Has anyone seen this ? - Traceback (most recent call last):   File "_missingdbal.py", line 227, in <module>     main()   File "_missingdbal.py", line 18, in main     dbconn = cx_Oracle.connect(cid + '/' + pw + '@oodbad01.world') cx_Oracle.DatabaseError: DPI-1047: 64-bit Oracle Client library cannot be loaded: "C:\Oracle_11G_ClientR2\product\11.2.0\client_1\bin\oci.dll is not the correct architecture". See https://oracle.github.io/odpi/doc/installation.html#windows for help

### ISSUE THREAD

**Issue by PCIII** [oracle/python-cx_Oracle#205]
*Delete irrelevant parts of this template.*

### For general questions:

Describe exactly what you did and what you want to happen.
Use the questions at the bottom of this template as a guide.

Use Markdown syntax, particularly for code blocks: see https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

### For security issues:

See https://www.oracle.com/support/assurance/vulnerability-remediation/reporting-security-vulnerabilities.html for how to report security issues.

### For installation issues:

Use a gist for screen output and logs: see https://gist.github.com/
**Do not paste long output into this issue**

Review the install instructions at
https://github.com/oracle/python-cx_Oracle#installation

Review your output and logs.  **Google any errors**

#### Answer the following questions:

1. What is your version of Python? Is it 32-bit or 64-bit?

2. What is your version of cx_Oracle?

3. What is your version of the Oracle client (e.g. Instant Client)?  How was it
   installed?  Where is it installed?

4. What is your version of the Oracle Database?

5. What is your OS and version?

6. What compiler version did you use?  For example, with GCC, run
   `gcc --version`.

7. What environment variables did you set?  How *exactly* did you set them?

8. What *exact* command caused the problem (e.g. what command did you try to
   install with)?  Who were you logged in as?

9. What error(s) you are seeing?

**Comment by hexaclock** [comment]
You must use a 32 bit version of the the Oracle instant client if you use a 32 bit version of Python. The same applies for a 64 bit version of Python. This is regardless of the OS architecture.

**Comment by cjbj** [comment]
@PCIII as @hexaclock says, you need the correct Oracle client libraries, and they must be in your PATH.  In this case you need 64-bit libraries but seem to have installed 32-bit libraries.  Check the [cx_Oracle installation instructions](http://cx-oracle.readthedocs.io/en/latest/installation.html#installing-cx-oracle-on-windows).

If you have any more issues, please answer the [template questions](https://github.com/oracle/python-cx_Oracle/blob/master/.github/issue_template.md) so we can help you better.

**Comment by PCIII** [comment]
Figured it out
