### ISSUE TITLE
DPI-1047: 64-bit Oracle Client library cannot be loaded MacOs version

### ISSUE THREAD

**Issue by alexguti** [oracle/python-cx_Oracle#206]
#### Answer the following questions:

1. What is your version of Python? Is it 32-bit or 64-bit?
Python 2.7.15
2. What is your version of cx_Oracle?
cx_Oracle 6.4.1
3. What is your version of the Oracle client (e.g. Instant Client)?  How was it
   installed?  Where is it installed?
instantclient_12_2 64 bits 
Unzipped
/Users/USER_X/opt/oracle/instantclient_12_2
4. What is your version of the Oracle Database?
instantclient_12_2
5. What is your OS and version?
macOS High Sierra 10.13.5
6. What compiler version did you use?  For example, with GCC, run
   `gcc --version`.
Apple LLVM version 9.1.0 (clang-902.0.39.2)
7. What environment variables did you set?  How *exactly* did you set them?
export ORACLE_HOME=/Users/USER_X/Applications/oracle/instantclient_12_2
export DYLD_LIBRARY_PATH=$ORACLE_HOME
export LD_LIBRARY_PATH=$ORACLE_HOME
export PATH=$ORACLE_HOME:$PATH
9. What error(s) you are seeing?
cx_Oracle.DatabaseError: DPI-1047: 64-bit Oracle Client library cannot be loaded: "dlopen(libclntsh.dylib, 1): image not found". See https://oracle.github.io/odpi/doc/installation.html#macos for help

I've been dealing with it for hours but I can not figure out how to solve it. I've installed 32-bit and 64-bit Oracle database versions without any effect.

**Comment by anthony-tuininga** [comment]
Did you follow all of the instructions noted in the [documentation](https://oracle.github.io/odpi/doc/installation.html#macos)? For instant client you do not need to set ORACLE_HOME and setting DYLD_LIBRARY_PATH and $LD_LIBRARY_PATH are not effective in most macOS installations. See the installation instructions for more details.

**Comment by alexguti** [comment]
I followed the instructions from the beginning to the end. 
I've changed /Users/USER_X/opt/oracle/instantclient_12_2 path to /opt/oracle/instantclient_12_2 but still have the same problem. Also I've unsetted the ORACLE_HOME, DYLD_LIBRARY_PATH and LD_LIBRARY_PATH variables. 
I don't know how to continue. I really appreciate any help.

**Comment by cjbj** [comment]
Saying you followed them doesn't help us identify if something was missed or where the problem is.

Here's my `~/lib` directory:

```
  /Users/cjones/lib:
  total used in directory 16 available 9223372036852657082
  -rw-r--r--@   1 cjones  staff  6148  7 Apr 07:38 .DS_Store
  lrwxr-xr-x    1 cjones  staff    43 19 Jul 11:43 libclntsh.dylib -> /Users/cjones/instantclient/libclntsh.dylib
```

That's it.  It was: unzip, create symlink, done.

**Comment by cjbj** [comment]
Don't forget the [first line of the installation instructions](http://cx-oracle.readthedocs.io/en/latest/installation.html#installing-cx-oracle-on-macos): "Make sure you are not using the bundled Python.  This has restricted entitlements and will fail to load Oracle client libraries. Instead use Homebrew or Python.org."

**Comment by alexguti** [comment]
That was my error, I was using the bundled Python. I've changed it by the homebrew version and now works fine. 
Many thanks guys!!!

**Comment by DeekshithMedikurti** [comment]
How to check if I'm using bundled python ?

**Comment by cjbj** [comment]
If you haven't explicitly installed Python, then you will be using the bundled python.  You can also check like:

```
$ which python
/usr/bin/python
```

**Comment by DeekshithMedikurti** [comment]
I'm using anaconda and the command
$which python
gives this /anaconda3/bin/python.

I keep getting the below error when I try connecting to Oracle database
through python:
DatabaseError: DPI-1047: 64-bit Oracle Client library cannot be loaded:
"dlopen(libclntsh.dylib, 1): image not found". See
https://oracle.github.io/odpi/doc/installation.html#macos for help

As far as I understand, anaconda or python has no knowledge of where the
dynamic libraries are, in order to make a connection.

Can you point me in the right direction?

Thanks for your help,
Deekshith.

**Comment by cjbj** [comment]
Follow the installation instructions https://cx-oracle.readthedocs.io/en/latest/installation.html#installing-cx-oracle-on-macos regarding Instant Client set up.  

Open a new issue if you still have problems.

**Comment by kamal972reddy** [comment]
> If you haven't explicitly installed Python, then you will be using the bundled python. You can also check like:
> 
> ```
> $ which python
> /usr/bin/python
> ```

Is this correct? I am getting the same error as in this thread. Can you please help.
M999:lib user_X$ which python
/usr/bin/python
M999:lib user_X$ which python3
/Library/Frameworks/Python.framework/Versions/3.8/bin/python3

**Comment by cjbj** [comment]
@kamal972reddy sounds like https://github.com/oracle/python-cx_Oracle/issues/428  If not, please open a new issue.  This one (206) is closed.
