### ISSUE TITLE
ORA-24338: statement handle not executed in PROCEDURE

### ISSUE THREAD

**Issue by welldone217** [oracle/python-cx_Oracle#207]
1. What is your version of Python? 
           64-bit?

2. What is your version of cx_Oracle?
    cx-Oracle           6.4.1

3. What is your version of the Oracle client (e.g. Instant Client)?  How was it
   installed?  Where is it installed?
         instantclient_12_2_64

4. What is your version of the Oracle Database?
        docker-oralce12c_R2

5. What is your OS and version?
   windows 10

6. What compiler version did you use?  For example, with GCC, run
    i am not sure.           Django              2.0.7
  
9. What error(s) you are seeing?

Request Method: | GET
-- | --
http://127.0.0.1/a/abc
django:2.0.7
DatabaseError
ORA-24338: statement handle not executed
E:\codes\zhuanjia\mysite\zhuanjia\views.py in callprod, line 52
E:\huanjing\python3.6\python.exe
3.6.5

10. my python3 code

```python
def callprod(pname, kw_in=""):
     if len(pname) < 2:
        return False
    sql = r'''
    DECLARE result SYS_REFCURSOR;
    BEGIN
        %(pname)s('%(kw)s', result);
    END;
    ''' % {"pname": pname, "kw": "keyword"}
    with connection.cursor() as cur:
        with cur.connection.cursor() as rawcur:
            **cur.callproc(pname, [kw_in, rawcur])
            #cur.execute(sql)                    #it show me not a query
            res = rawcur.fetchall()            #error ORA-24338:**
            for f in res:
                print(f)
```

#my procedure
```
create or replace PROCEDURE SITE_SEARCH 
(
  KWORDS IN VARCHAR2 ,
  results OUT sys_refcursor
) AS 
BEGIN
 OPEN results FOR select * from zhuanjia_zhuanjia where ZJNAME LIKE '%'||KWORDS||'%'  ;
 dbms_sql.return_result(results);
END SITE_SEARCH;
```

**Comment by anthony-tuininga** [comment]
If you're making use of dbms_sql.return_result() then I would suggest using the implicit result sets feature which you can see in this [sample](https://github.com/oracle/python-cx_Oracle/blob/master/samples/ImplicitResults.py).

**Comment by welldone217** [comment]
the working code is 
<code>    
def callprod(pname, kw_in=""):
      with connection.cursor() as cur:
        with cur.connection.cursor() as rawcur:
            cur.callproc(pname, (kw_in, rawcur))
            for f in enumerate(cur.getimplicitresults()):
                return f[1].fetchall()
<code> 

thank you,anthony-tuininga
