### ISSUE TITLE
cx_Oracle Package Not working inside Crontab

### ISSUE THREAD

**Issue by ishmnnit** [oracle/python-cx_Oracle#21]
I am using cx_Oracle library in my python script. My code works fine if I directly execute by python script from Linux terminal but when I put it in crontab I am getting following error.

!!DatabaseError: DPI-1047: Oracle Client library cannot be loaded: libclntsh.so: cannot open shared object file: No such file or directory. See https://oracle.github.io/odpi/doc/installation.html for help

 DPI-1005: unable to acquire Oracle environment handle
!!Traceback (most recent call last):
    import cx_Oracle
!!DatabaseError: DPI-1005: unable to acquire Oracle environment handle

I googled this issue and It seems some environment variable missing when it ran using crontab.
I try to export following in crontab but it does not work.

export  LD_LIBRARY_PATH='/usr/lib/oracle/11.2/client64/lib'

If I remove cx_Oracle package other code runs fine. I have only one version of python installed on my machine.

1. What is your version of Python? Is it 32-bit or 64-bit?
Python 2.6 . 64 bit

2. What is your version of cx_Oracle?
Version 6.0b1

3. What is your version of the Oracle client (e.g. Instant Client)?  How was it
   installed?  Where is it installed?
oracle-instantclient11.2-devel-11.2.0.4.0-1.x86_64.rpm

4. What is your OS and version?
CentOS 6.7

5. What environment variables did you set?  How *exactly* did you set them?
export LD_LIBRARY_PATH='/usr/lib/oracle/11.2/client64/lib'

**Comment by anthony-tuininga** [comment]
Note the link in the error message above. You may wish to create an entry in /etc/ld.so.conf.d instead. Do you have any other installations of Oracle that may be interfering?

**Comment by jmcp** [comment]
The usual way to address this problem is to write a wrapper script which sets LD_LIBRARY_PATH and then execs your python script. cron will sanitise your environment, which is why you're not able to dlopen libclntsh.so.

**Comment by anthony-tuininga** [comment]
Did those answers solve your issue? Or are you still experiencing difficulties?

**Comment by anthony-tuininga** [comment]
Closing due to lack of feedback. Please re-open if needed!

**Comment by jbanerje** [comment]
It's not working since its looking for the oracle instant client path.
In the shell script, add the export line and point it to your oracle client path. Next, keep writing your shell script. This will work!

    #!/bin/sh
    export LD_LIBRARY_PATH=/home/<user_name>/opt/oracle/instantclient_19_5:$LD_LIBRARY_PATH
    /usr/anaconda3/bin/python /home/<user_name>/test/src/test.py
