### ISSUE TITLE
loading several LOB objects at once

### ISSUE THREAD

**Issue by vince377** [oracle/python-cx_Oracle#211]
Hello,

I have an oracle table defined as:
```
CREATE TABLE "MYTABLE" 
   (	
	"ID" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	"CDATA" CLOB
)
```
and I run a basic query on it like:
```
import cx_Oracle

dsn_tns = cx_Oracle.makedsn("XXX", 1725, "SID")
connection = cx_Oracle.connect("user", "pass", dsn_tns)

sql = "SELECT CDATA FROM MYTABLE"

cursor = connection.cursor()
for result, in cursor.execute(sql):
    print(result.read())
```
each CDATA value is not very large, around 10k/100k bytes but a query returns around 10k/20k records.
If I run the client relatively close to the server, it all works out OK and it is reasonably fast.
But when I access my London Oracle server from New York the ".read()" command seem to do a network roundtrip on every .read() call and this is completely killing performance.

Is there a way to read all the LOB returns in one go?

I believe oracle natively has the function: OCILobArrayRead() but I don't see the equivalent available in cx_Oracle.
https://docs.oracle.com/cd/B28359_01/appdev.111/b28393/adlob_lob_ops.htm#BACGDAJF

Do I miss something in cx_oracle to prevent a round trip on each call to ".read()"
The same question applies to writes as well.

Thanks for your help!

#### Answer the following questions:

1. What is your version of Python? 
3.5

2. What is your version of cx_Oracle?
checked with 5.2.1 and 62.1
5. What is your OS and version?
Windows 10

**Comment by anthony-tuininga** [comment]
Yes, there is a much faster way of fetching LOBS, especially if you are using a remote database with a larger round-trip. Take a look at this [sample](https://github.com/oracle/python-cx_Oracle/blob/master/samples/ReturnLobsAsStrings.py). What will be returned is the full string and you will not need to do a read(), which indeed does require an additional round-trip.

**Comment by vince377** [comment]
That's great, thanks. It works like a charm when I follow your example!

**Comment by anthony-tuininga** [comment]
Excellent! Glad to hear it. :-)
