### ISSUE TITLE
Oracle Type 0 Not Supported

### ISSUE THREAD

**Issue by sekando273** [oracle/python-cx_Oracle#212]
I'm currently using Python 3.6.4 with cx_Oracle 6.4 in Windows Server 2012 R2 and i'm getting this error when i'm trying to Access a NUMERIC type attribute of my User Defined type, it Works with the rest of the attributes, but in this particular case i'm getting an "Oracle Type 0 Not Supported".

The rest of the attributes are NUMBER, VARCHAR, etc. But this one is NUMERIC with precision 'NUMERIC(18, 10)'.

```python
con = cx_Oracle.connect(connection_object.User, connection_object.Password, connection_object.Host)
cursor = con.cursor()
my_type = con.gettype("MY_TYPE")
custom_type = my_type.newobject()
params = (custom_type, ) # out param
reader = cursor.callproc("MY_PROCEDURE", params)

__table_type = reader[0].aslist()

for row in __table_type:
      print(row.ACOD) # NUMBER Works
      print(row.ANAME) # VARCHAR Works
      print(row.ALAT) # NUMERIC Raise an Exception
```

Thanks for your help.

**Comment by anthony-tuininga** [comment]
This should (hopefully!) not be too difficult to address. I'll let you know once I've had some time to take a look.

**Comment by sekando273** [comment]
Please, I need to fix this in the shortest time. Thank you a lot

**Comment by anthony-tuininga** [comment]
I took a quick peek and discovered that this is a "packed decimal" type (SQLT_PDN) which is not documented. I will see if I can find out about this type internally, but if you can change the type of the attribute to a regular number type instead -- that is number(18,10) -- that would make life considerably simpler for everyone!

**Comment by anthony-tuininga** [comment]
I have just pushed the code changes to correct this for you, I believe. Please give it a try and let me know. Thanks!

**Comment by anthony-tuininga** [comment]
This has been implemented in cx_Oracle 7 which is now released publicly.
