### ISSUE TITLE
DPI-1047 on Mac... please help!

### ISSUE THREAD

**Issue by mramsey4** [oracle/python-cx_Oracle#214]
I'm running into an issue when I execute my code that uses the cx_Oracle library. I was able to install the library, though with some difficulty. I used the instructions on the website to manually pull the zip from GitHub through the command line, unzip and build. I answered the templated questions below, hopefully that can shed some light on what the root issue is. Any help is greatly appreciated, as I'm fairly new to bash and using a Mac. 

Thanks in advance.

#### Answer the following questions:

1. What is your version of Python? Is it 32-bit or 64-bit?
64-bit

2. What is your cx_Oracle version?
The latest version as of today, I believe it's 6.4

3. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?

self.connection = cx_Oracle.connect(self.username, self.password, dsn) -> caused
dlopen(libclntsh.dylib, 1): image not found

logged in as an administrator

4. What error(s) you are seeing?

cx_Oracle.DatabaseError: DPI-1047: 64-bit Oracle Client library cannot be loaded

5. What OS (and version) is Python executing on?

macOS High Sierra, 10.13.4
python 2.7.10

6. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where is it installed?

Version 12.2
I installed it by unzipping it into a folder located at /opt/oracle/

7. What is your Oracle Database version?

Can't say at the moment, but I don't believe this is a big factor in troubleshooting at the moment. I can look deeper into this if it becomes a bigger issue.

8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?

BASIC_README			libocci.dylib.12.1
adrci				libociei.dylib
genezi				libocijdbc12.dylib
libclntsh.dylib			libons.dylib
libclntsh.dylib.12.1		liboramysql12.dylib
libclntshcore.dylib.12.1	network
liblntsh.dylib			ojdbc8.jar
libnnz12.dylib			uidrvci
libocci.dylib			xstreams.jar

9. What Oracle environment variables did you set?  How *exactly* did you set them?
ORACLE_HOME=/opt/oracle/

I set it with the export set command, per the instructions

10. Do you have a small, single Python script that immediately runs to show us the problem?

Yes

**Comment by cjbj** [comment]
On macOS you need to install Python too.  The system Python is not usable.  From http://cx-oracle.readthedocs.io/en/latest/installation.html#installing-cx-oracle-on-macos : 

> Make sure you are not using the bundled Python. This has restricted entitlements and will fail to load Oracle client libraries. Instead use Homebrew or Python.org.

**Comment by cjbj** [comment]
PS you don't need to set ORACLE_HOME.  That is not part of the instructions :)

**Comment by mramsey4** [comment]
Hi cjbj, thanks for the quick response! I have python 3.7.0 installed as well, however calling my python script using the python3 command instead of the python command results in the exact same issue. Is there a way to upgrade the default python version on macOS?

**Comment by cjbj** [comment]
If you have multiple versions of Python installed you need to really ensure that the right version is being used.   I ended up using pyenv from homebrew to make it easy to change python versions.

I doubt upgrading the default Python is feasible or would help.  Apple would probably enforce the same restrictions as they do in 2.7.10.

In case it helps, this is all that I have in `~/lib`:
```
$ ls -l ~/lib
total 0
lrwxr-xr-x  1 cjones  staff  43 19 Jul 11:43 libclntsh.dylib -> /Users/cjones/instantclient/libclntsh.dylib
```
