### ISSUE TITLE
ProgrammingError: positional and named binds cannot be intermixed (cx-Oracle==6.4.1)

### ISSUE THREAD

**Issue by mPyth** [oracle/python-cx_Oracle#216]
1. What is your version of Python? Is it 32-bit or 64-bit?
    Python 3.6.3, 64bit

2. What is your cx_Oracle version?
    cx-Oracle==6.4.1

3. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?
    Error is shown in a try to execute next command (from Django 2.0.7):
```
    with connections['ed'].cursor() as cursor:
        cursor.execute(query, {'query_param_val': 12345})
```
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Variable **query** from above code is quite long string, and I'll put it at the end of this post.

4. What error(s) you are seeing?
    ProgrammingError: positional and named binds cannot be intermixed
    
    This is exactly the same issue as [issue199](https://github.com/oracle/python-cx_Oracle/issues/199), but on that thread I'm told to open new ticket.
   
5. What OS (and version) is Python executing on?
    OS: CentOS (centos-release-7-5.1804.el7.centos.2.x86_64)
    Python is 3.6.3

6. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where is it installed?
    oracle client: oracle-instantclient18.3-basic-18.3.0.0.0-1.x86_64
    Installation: by using RPM installer, installation path: **/usr/lib/oracle/18.3/client64/**

7. What is your Oracle Database version?
   Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production

8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?
   LD_LIBRARY_PATH is not changed, alternative way is used (with command **sudo ldconfig**) .

9. What Oracle environment variables did you set?  How *exactly* did you set them?
   Oracle environment variables are not used.

10. Do you have a small, single Python script that immediately runs to show us the problem?

```
    with connections['ed'].cursor() as cursor:
        cursor.execute(query, {'query_param_val': 12345})
```
Remark: **query_param_val** is used 7 times in query.
Here is the value of **query** variable:
```
query='''
select
    (
    select
        p.col01
      from
        tbl1 p
      where
        p.col02 = :query_param_val
    ) potr_broj
  , (
    select
        case
          when p.col03 = 'R' then 'val01'
          else 'val02'
        end col16
      from
          tbl1 p
        where
          p.col02 = :query_param_val
    ) col16
  , (
    select
        case
          when p.col03 = 'R' then
            (
              select 
                  adr.col04
                from 
                  tbl2 adr
                where
                  adr.col05 = p.col05
            )
          else
            (
            select
                adr.col04
              from
                tbl3 kmm 
                inner join tbl4 mm
                  on    mm.col06 = kmm.col06
                inner join tbl2 adr
                  on adr.col05 = mm.col05
              where
                    kmm.col02 = p.col02
                and ( kmm.col06 is null )
            )
        end col17
      from
        tbl1 p
      where
        p.col02 = :query_param_val
    ) col17
  , (select
        sum(f.col07 - f.col08)
      from
        tbl5 f
      where
            f.col02 = :query_param_val
        and f.col11 = 'F'
        and f.col10 in ('0', '1', '31')
    ) trenutni_dug
  , (select
        max(f.col09)
      from
        tbl5 f
        inner join tbl6 vd
          on vd.col14 = f.col14
      where
            f.col02 = :query_param_val
        and vd.col13 in ('O', 'L', 'M')
        and f.col11 = 'F'
        and f.col10 = '0'
    ) col18
  , (select
        col09
      from
        (
        select
            f.col09
          from
            tbl5 f
            inner join tbl6 vd
              on vd.col14 = f.col14   
          where
                f.col02 = :query_param_val
            and vd.col12 = 'X'
            and f.col10 = '0'
            and f.col11 = 'F'
          order by
              f.col09 desc
            , f.col15 desc
        )
        where
          rownum = 1
    ) col19
  , (select
        col21
      from
        (
        select
            (f.col07 - f.col08) col21
          from
            tbl5 f
            inner join tbl6 vd
              on vd.col14 = f.col14   
          where
                f.col02 = :query_param_val
            and vd.col12 = 'X'
            and f.col10 = '0'
            and f.col11 = 'F'
          order by
              f.col09 desc
            , f.col15 desc
        )
        where
          rownum = 1
    ) col20
  from
    dual
'''
```

**Comment by cjbj** [comment]
@mPyth  Please post CREATE TABLE statement and any necessary INSERT statements.  It may help us if you could reduce the query size by removing uneccessary bits.  Thanks!

**Comment by mPyth** [comment]
Finally I manage to make easily reproducible case, problem is with running query in a loop, with named query parameter which is in form '**:queryParam**', and not in form '**%(queryParam)s**':

Database code:
```
create table tbl
(
    id number(3)
  , constraint tbl1_pk primary key (id)
);

insert into tbl (id) values (1);
insert into tbl (id) values (2);
```
Django code (the whole view function):
```
def vTestPage5(request):
    try:
        with connections['oracleConnection'].cursor() as cursor:
            tstQuery = '''select t.id from tbl t where t.id = :p_id'''
            retStr = ''
            for indI, p_idI in enumerate( [1,2] ):
                cursor.execute(tstQuery, {'p_id': p_idI})
                row = cursor.fetchone()
                retStr += (f'Rec {indI}: {row[0]}' + '<br>')        
    except Exception as e:
        errMsg = type(e).__name__ + ': ' + str(e)
        retStr = f"Encounter on error: {errMsg}"
        
    return HttpResponse(retStr)
```
Case <span>#</span>1:  if such code run with cx-Oracle==6.4.1 it will generate "ProgrammingError: positional and named binds cannot be intermixed" (it will be rendered on web page). I've checked - the same error is reported when code runs on Linux and on Windows machine.

Case <span>#</span>2: uninstall cx-Oracle and install version 6.3.1 (with '**pip**') and run previos code. Result: no error, web page is rendered with 2 rows (as expected).

Case <span>#</span>3: if previous code run with cx-Oracle==6.4.1, but with value 2 removed from '**for**' loop, or more precise, when '**for**' loop is replaced with following:
 `            for indI, p_idI in enumerate( [1,] ):`
Result: there is no exception, one row of text is shown (as expected).

Case <span>#</span>4: if Django code (for **loop** is unchanged - with 2 steps) run with cx-Oracle==6.4.1 , and if query param is specified in another way, by replacing **tstQuery** with following line:
```            tstQuery = '''select t.id from tbl t where t.id = %(p_id)s'''```
Result: there is no exception, two rows are shown (as expected).

Approach described in case <span>#</span>4 solves my problem, but it is quite unexpectable that case <span>#</span>3 works and case <span>#</span>1 doesn't work.

**Comment by anthony-tuininga** [comment]
Can you try the following code based on your example? This takes Django completely out of the picture 
and is a basic example. This does not fail for me. Let me know if it fails for you!

```sql
create table issue_216
(
    id number(3)
  , constraint issue_216_pk primary key (id)
);

insert into issue_216 (id) values (1);
insert into issue_216 (id) values (2);

commit;
```

```python
import cx_Oracle

conn = cx_Oracle.connect("user/pw@connect_string")
with conn.cursor() as cursor:
    tstQuery = '''select t.id from issue_216 t where t.id = :p_id'''
    for indI, p_idI in enumerate( [1,2] ):
        cursor.execute(tstQuery, {'p_id': p_idI})
        row = cursor.fetchone()
        print(f'Rec {indI}: {row[0]}')
```

**Comment by mPyth** [comment]
I've just tried your example and it works fine, there is no exception, both lines are printed to console. Seems the problem could be in Django (I'm using Django 2.0.8).

I made some more experiments with my code:
Case <span>#</span>5: if semicolon is added to query end, code works fine with cx-Oracle=6.4.1

**Comment by cjbj** [comment]
- Where exactly is the semicolon added?
- See if you can construct a failing testcase that doesn't use Django.
- Case 4 (without binds) is likely to be a scalability problem and it is subject to SQL Injection security problem,

**Comment by mPyth** [comment]
- I've just updated my previous post with more details about adding semicolon (for Case <span>#</span>5).
- For now I could not reproduce the problem with direct use of cx-Oracle, I'll make more tries, if I find something I'll let you know.
- Case <span>#</span>4 is alternative way to pass arguments to raw SQL query in Django, you can find more details on [this link](https://docs.djangoproject.com/en/2.0/topics/db/sql/#passing-parameters-into-raw). Appropriate name for such query parameters is named parameters, in the contrast to positional query parameters when placeholders of type **%s** are used. Seems that colon style **:queryParam** is Oracle specific and probably not advisable for use in Django. I've used style with colon because Sql Developer use that style, but I'll try to avoid it in a future. My Django application uses another connection to Postgres and in these queries I'm using exclusively named parameters in form **%(queryParam)s** .

**Comment by anthony-tuininga** [comment]
Hmm, I have used Django in the past and if I recall correctly the "cursor" that is returned is a wrapped cursor. You can, however, get access to a "raw" cx_Oracle cursor by using this phrase (yes, its a bit awkward):

```python
connections['oracleConnection'].cursor().connection.cursor()
```

That may have changed in more recent versions of Django (its been a few years since I've used it now) but I used that frequently in the past when I wanted to avoid Django's wrappers (which frequently caused problems when you weren't using Django models, views, etc.)

**Comment by mPyth** [comment]
I've already used direct connection to Postgres, code is similar to `cx_Oracle.connect(...)`, because in Django it is not possible to specify how many records to fetch (only fetch one, or all, which is not good enough if there is e.g. 100.000 records). For this purpose I've used **psycopg2's** cursor (psycopg2 is python connector for Postgres) with specified name, in this way database cursor is created which allows to specify the number of records to fetch. This was very handy for my application, although generally database cursors should be avoided in web applications (they are resource intensive for database machine).

As I've already said Case <span>#</span>4 already solved the problem I've encountered, so I will use such approach in the future. I would avoid Case <span>#</span>5 due to some problems that I had before with semicolon on the query end (I could not remember did I use with java, Oracle forms or some other programming language).

**Comment by anthony-tuininga** [comment]
Can you provide the complete code for your Case #4? I'm glad it works for you, but I want to make sure that you are using parameters. cx_Oracle only understands :1 and :name type parameters. The %s and %(name)s type parameters are exclusive to Django.

**Comment by mPyth** [comment]
Here is the complete Django view function for Case <span>#</span>4 (it renders page and print string to console) that works correctly with cx-Oracle 6.4.1 :

```
def vTestPage5(request):
    try:
        with connections['oracleConnection'].cursor() as cursor:
            tstQuery = '''select t.id from issue_216 t where t.id = %(p_id)s'''
            
            retStr = ''
            for indI, p_idI in enumerate( [1,2] ):
                cursor.execute(tstQuery, {'p_id': p_idI})
                row = cursor.fetchone()
                print(f'Rec {indI}: {row[0]}')
                retStr += (f'Rec {indI}: {row[0]}' + '<br>')
      
    except Exception as e:
        errMsg = type(e).__name__ + ': ' + str(e)
        retStr = f"Encounter on error: {errMsg}"
        print(retStr)
        
    return HttpResponse(retStr)
```
Python DB API v2.0 defines several ways for specifying query params (more details [here](https://www.python.org/dev/peps/pep-0249/#paramstyle)). Style Case <span>#</span>1 is '**named**'  and Case <span>#</span>4 is '**pyformat**' (used in this example).
Internally Django transforms '**pyformat**' to '**named**' (could be seen in debugger as `cursor.cursor.cursor.statement` after query is executed). It is interesting that transformed query does NOT have semicolon at the end (Case <span>#</span>5 which works fine with cx-Oracle 6.4.1).

In runtime debugger shows that `connections['oracleConnection'].Database.paramstyle` has value '**named**', but seems it accepts '**pyformat**' too.

**Comment by anthony-tuininga** [comment]
cx_Oracle itself doesn't accept pyformat, but if Django does and transforms it to named on your behalf, that's all good! I'm going to assume that this marks the end of your questions and will close this issue.
