### ISSUE TITLE
python Oracle connection issue

### ISSUE THREAD

**Issue by hjsdssz** [oracle/python-cx_Oracle#220]
1. What is your version of Python? Is it 32-bit or 64-bit?
Python 32-bit

2. What is your cx_Oracle version?
6.4.1 

3. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?
import cx_Oracle
conn_str = u'postpaid/ppaid4apc@CAMPPR-scan.corp.ads:41521/CAMPPRsv1.WORLD'
conn=cx_Oracle.connect(conn_str)

4. What error(s) you are seeing?
DatabaseError: DPI-1047: 32-bit Oracle Client library cannot be loaded: "The specified module could not be found". 

5. What OS (and version) is Python executing on?
Python 3.6

6. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where is it installed?
12.2
From Oracle website

7. What is your Oracle Database version?
Oracle Database 11g Enterprise Edition 

8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?
C:\Oracle\instantclient_12_2

9. What Oracle environment variables did you set?  How *exactly* did you set them?
PATH2

10. Do you have a small, single Python script that immediately runs to show us the problem?
no

**Comment by anthony-tuininga** [comment]
So did that correct your issue? If so, please close it! Thanks.

**Comment by hjsdssz** [comment]
Hi, sorry. I provided incorrect information, and looks like my Oracle Server is 64-bit, so I redownloaded 64-bit Python 3.6, but I still got the same error message.
Here is the update information:


1.What is your version of Python? Is it 32-bit or 64-bit?
 Python 64-bit


2.What is your cx_Oracle version?
 6.4.1 


3.What exact command caused the problem (e.g. what command did you try to install with)? Who were you logged in as?
 import cx_Oracle
 conn_str = u'postpaid/ppaid4apc@CAMPPR-scan.corp.ads:41521/CAMPPRsv1.WORLD'
 conn=cx_Oracle.connect(conn_str)


4.What error(s) you are seeing?
 DatabaseError: DPI-1047: 64-bit Oracle Client library cannot be loaded: "The specified module could not be found". 

5.What OS (and version) is Python executing on?
 Python 3.6 


6.What is your version of the Oracle client (e.g. Instant Client)? How was it installed? Where is it installed?
 18.3 64-bit
 From Oracle website
http://www.oracle.com/technetwork/database/database-technologies/instant-client/overview/index.html

7.What is your Oracle Database version?
 Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production


8.What is the PATH environment variable (on Windows) or LD_LIBRARY_PATH (on Linux) set to? On macOS, what is in ~/lib?
C:\Oracle\instantclient\instantclient_18_3


9.What Oracle environment variables did you set? How exactly did you set them?
 PATH2


10.Do you have a small, single Python script that immediately runs to show us the problem?
 no

**Comment by anthony-tuininga** [comment]
Please check the [cx_Oracle installation documentation](https://cx-oracle.readthedocs.io/en/latest/installation.html#installing-cx-oracle-on-windows) and confirm that you are doing everything there. In particular, did you install the relevant Visual Studio redistributable?

**Comment by hjsdssz** [comment]
Yes. I did follow each step and install Visual Studio redistributable.

**Comment by cjbj** [comment]
@hjsdssz you'll need to provide more details about what is set and what you are running.  We can't guess

**Comment by hjsdssz** [comment]
@cjbj hey the details has been provided here, baiscally the issue is my Oracle and Python are both 64-bit, but somehome I cannot connect to Oracle by using Python by showing 'DatabaseError: DPI-1047: 64-bit Oracle Client library cannot be loaded: "The specified module could not be found".' 
What else information do you need?
Let me know, thanks!

1.What is your version of Python? Is it 32-bit or 64-bit?
Python 64-bit

2.What is your cx_Oracle version?
6.4.1

3.What exact command caused the problem (e.g. what command did you try to install with)? Who were you logged in as?
import cx_Oracle
conn_str = u'postpaid/ppaid4apc@CAMPPR-scan.corp.ads:41521/CAMPPRsv1.WORLD'
conn=cx_Oracle.connect(conn_str)

4.What error(s) you are seeing?
DatabaseError: DPI-1047: 64-bit Oracle Client library cannot be loaded: "The specified module could not be found".

5.What OS (and version) is Python executing on?
Python 3.6

6.What is your version of the Oracle client (e.g. Instant Client)? How was it installed? Where is it installed?
18.3 64-bit
From Oracle website
http://www.oracle.com/technetwork/database/database-technologies/instant-client/overview/index.html

7.What is your Oracle Database version?
Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production

8.What is the PATH environment variable (on Windows) or LD_LIBRARY_PATH (on Linux) set to? On macOS, what is in ~/lib?
C:\Oracle\instantclient\instantclient_18_3

9.What Oracle environment variables did you set? How exactly did you set them?
PATH2

10.Do you have a small, single Python script that immediately runs to show us the problem?
no

**Comment by cjbj** [comment]
Show a screenshot where you do these in the same terminal window:

- `echo %PATH%` or `$Env.Path`
- run python and execute `import platform;platform.architecture()`

Also show the VC Redistributable(s) you have installed.

**Comment by hjsdssz** [comment]
![image](https://user-images.githubusercontent.com/42756618/45130327-2e7c4500-b156-11e8-8e39-c4ed1f6a6229.png)

**Comment by hjsdssz** [comment]
![image](https://user-images.githubusercontent.com/42756618/45130360-494eb980-b156-11e8-91f0-f95e0bcfe750.png)

**Comment by anthony-tuininga** [comment]
Looks like your Oracle client installation is missing from your PATH environment variable. That would definitely result in the error you are seeing. Can you adjust that?

**Comment by hjsdssz** [comment]
@anthony-tuininga I did set PATH environment variable as follows

![image](https://user-images.githubusercontent.com/42756618/45186950-22978e00-b1fd-11e8-8b3b-4dd4068529b1.png)

**Comment by anthony-tuininga** [comment]
You need to set PATH, not PATH2! Setting PATH2 will not have any effect, unfortunately. Try adjusting PATH (include the value you have in your PATH2 environment variable, but ensure there is a semicolon between it and the existing value).

**Comment by hjsdssz** [comment]
Thanks! It works!
But I have another question:
Since I need to use Python to connect to SAS and Oracle in my laptop, which means that I have to set two PATH environment variable for both SAS and Oracle, and that is why I used PATH2 instead of PATH in this case.
Is there any way to make both PATH environment variable exist?

**Comment by hjsdssz** [comment]
Thanks! They don't conflict with each other and the first way works!
I will close it.
Thanks! Again! @anthony-tuininga
