### ISSUE TITLE
Specifying truststore instead of using TNS wallet?

### ISSUE THREAD

**Issue by fwantastic** [oracle/python-cx_Oracle#222]
I was able to make an Oracle connection using TNS wallet. And I'm looking for a way to achieve connecting to Oracle with SSL without the wallet. This is possible with Apache's `BasicDataSource` which we can specify the truststore location and password, so I was wondering if cx_Oracle supports this feature at all?

**Comment by anthony-tuininga** [comment]
What you are asking may in fact work, but I would not know, unfortunately. Do you have any information on what would be needed to support this if it doesn't work today? Is there a reason you want to avoid the wallet?

**Comment by fwantastic** [comment]
@anthony-tuininga Thanks for the quick response!
It's just a requirement of the project I will be working on so I'm researching if this is possible at this point. I forgot to mention that Apache's datasource is in java, https://docs.oracle.com/cd/B19306_01/java.102/b14355/sslthin.htm#BABJIHFJ has an example of setting trustStore properties onto the datasource object (Oracle's implementation of the datasource). I'm not too sure how this works under the hood, I was guessing that if it's doable in java then there must be a similar way to set the property in C or python as well.

**Comment by anthony-tuininga** [comment]
Maybe. I'm sorry I can't help further. If you discover how to do this, please update this issue with your findings. If something is needed from cx_Oracle to make it work, let me know that, too. Thanks!

**Comment by fwantastic** [comment]
Okay. Thanks!

**Comment by cjbj** [comment]
@fwantastic I asked around and this seems to be Java only.

**Comment by fwantastic** [comment]
Gotcha. Thanks for the update
