### ISSUE TITLE
Cursor description attribute becomes stale

### ISSUE THREAD

**Issue by reverse42** [oracle/python-cx_Oracle#226]
I've had a problem with whats look like cursor description getting stale. I do have a workaround but I thought you may be interested.

I'm running a web server (uWSGI, flask) to serve a REST/json service. 

When a web server processes start up, it connects to oracle, and selects cursors are initialised.

I connect to Oracle like this:

```
    def connect(self):
        self.connection = cx_Oracle.connect(user      = config.oracle_username,
                                            password  = tools.decrypt(config.oracle_password),
                                            dsn       = config.oracle_dsn,
                                            encoding  ="UTF-8",
                                            nencoding ="UTF-8")
```

Example cursor initialisation:
```
        self.cache_lookup_by_retention_days_cursor = oracle_connection.connection.cursor()
        self.cache_lookup_by_retention_days_cursor.prepare("""select id_request_log_id,
                                                   created_date,
                                                   vat_region,
                                                   country_code,
                                                   business_id,
                                                   valid,
                                                   response_source,
                                                   response_receipt,
                                                   response_timestamp,
                                                   username,
                                                   ip_address
                                            from   id_request_cache_vw
                                            where  vat_region   = :vat_region
                                            and    country_code = :country_code
                                            and    business_id  = :business_id
                                            and    valid        = :valid
                                            and    created_date > sysdate - (:retention_days)""")

```

For convenience, after a cursor execute (and only after an execute, however 0 rows may be returned) I use the following generator to get the rows as dicts:

```
    def rows_as_dicts(self, cursor):
        """ returns cx_Oracle rows as dicts """
        colnames = [i[0] for i in cursor.description]
        for row in cursor:
            yield dict(zip(colnames, row))
```

It works splendidly, however, after a while (hours, even days), the cursor description attribute seemingly becomes stale. When calling `rows_as_dicts` an exception is thrown in. the line `colnames = [i[0] for i in cursor.description]`:

``` 
            try:
                self.cache_lookup_by_retention_days_cursor.execute(None,{
                                                          ':vat_region'    : config.country_vat_regions[request["shipTo"]["country"]],
                                                          ':business_id'   : request["shipTo"]["businessIdentificationNo"],
                                                          ':country_code'  : request["shipTo"]["country"],
                                                          ':valid'         : 'false',
                                                          ':retention_days': config.failed_id_cache_retention_days
                                                      })
                response_row = next(self.oracle_connection.rows_as_dicts(self.cache_lookup_by_retention_days_cursor))
            except StopIteration:
                # No rows found
                return { 'found': False }
```

```
Sep 28 06:51:34 taxmodule-glo-p03 uwsgi[13747]:   File "/app/uttax/lib/id_verifier.py", line 214, in verify_cache
Sep 28 06:51:34 taxmodule-glo-p03 uwsgi[13747]:     response_row = next(self.oracle_connection.rows_as_dicts(self.cache_lookup_by_retention_days_cursor))
Sep 28 06:51:34 taxmodule-glo-p03 uwsgi[13747]:   File "/app/uttax/lib/oracle.py", line 82, in rows_as_dicts
Sep 28 06:51:34 taxmodule-glo-p03 uwsgi[13747]:     colnames = [i[0] for i in cursor.description]
Sep 28 06:51:34 taxmodule-glo-p03 uwsgi[13747]: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xee in position 8: invalid continuation byte
```

The message is always the same, including '0xee' and 'position 8'. 

To work around it I use Cursor.fetchone() and just refer to response columns by indexes. This seems to work.

To me it looks like the cursor description attribute becomes stale, possibly due to some garbage collection going on. If the cursor is executed (possibly only when _not_ returning any rows), this attribute isn't refreshed.

1. What is your version of Python? Is it 32-bit or 64-bit?

3.6.5, 64 bit

2. What is your cx_Oracle version?

7.0.0 (also reproduced using 6.4.1)

3. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?

See above. Logged in as user 'uttax'.

4. What error(s) you are seeing?

See above.

5. What OS (and version) is Python executing on?

Ubuntu 18.04

6. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where is it installed?

11.2.0.4, installed in /usr/lib/oracle/11.2/client64/

7. What is your Oracle Database version?

11.2.0.3.6 (I don't control the server database version).

8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?

`LD_LIBRARY_PATH=/usr/lib/oracle/11.2/client64/lib:`

9. What Oracle environment variables did you set?  How *exactly* did you set them?

Pythons scripts runs  `os.environ["NLS_LANG"] = ".AL32UTF8"` on initialisation.

10. Do you have a small, single Python script that immediately runs to show us the problem?

Sorry, no.

**Comment by anthony-tuininga** [comment]
That's....intriguing! I don't know that the cursor description is "stale", unless you are keeping a statement open for a long period of time? The general approach is to simply create a new cursor for each execution (or batch of executions) in each web request, then allow the cursor to be destroyed. The statement cache implementation in the Oracle Client library will handle the caching of such statements for you. Can you clarify those few points on your implementation?

**Comment by reverse42** [comment]
Hi, thanks for responding.

Today, I create the cursors right after connecting and use these until I need to reconnect, for whatever reason. I've been using this approach in a variety of contexts (python and non-python) for years without issues.

However if this isn't in line with what you recommend, I'll take this _ad notam_ and just create a cursor for each web request, then allowing it to be destroyed.

**Comment by anthony-tuininga** [comment]
There isn't anything wrong with performing multiple executes on the same cursor. What I was asking about was the practice of keeping a cursor around for a lengthy period of time of inactivity. That at least isn't recommended. :-) But using a cursor multiple times as shown in the example you linked, that's perfectly fine and highly recommended!

**Comment by reverse42** [comment]
Thanks again. I'm following your recommendations and use short-lived cursors. For my sake you can close this issue now.

**Comment by anthony-tuininga** [comment]
Ok. I'll close it, then. Hopefully that does resolve your issue!
