### ISSUE TITLE
encoding/nencoding available options

### ISSUE THREAD

**Issue by bschwab003** [oracle/python-cx_Oracle#228]
Is there a listing of available `encoding` and `nencoding` string values that can be provided in `cx_Oracle.connect()` and how those values map to the values otherwise provided in NLS_LANG and NLS_NCHAR environment variables?

For e.g.

`UTF-8` is the equivalent to setting environment variable NLS_LANG = AMERICAN_AMERICA.AL32UTF8.

**Comment by anthony-tuininga** [comment]
This comment on another issue will give you the mapping. I'm not sure if this is documented anywhere but the query referenced in that comment will give you what you are looking for, I think!

https://github.com/oracle/python-cx_Oracle/issues/182#issuecomment-391035968

**Comment by bschwab003** [comment]
I can extract what I need from this comment chain.  Seems like we have the option of using Python   Thank you for pointing me to it.  If we are using UTF-8/AMERICAN_AMERICA.AL32UTF8 as the encoding and still getting the error `utf-8' codec can't decode byte 0xf7 in position 1: invalid start byte` do you have a suggestion on how to troubleshoot this?  While I know UTF-8 is pretty all encompassing, I assume we are hitting some characters that UTF-8 cannot handle?  Or maybe there are "bad" characters somehow?  

I remember asking previously if there was a way to "ignore" decoding errors, skipping over the characters or whatever and that answer was no.  

Is it just a matter of asking our client(s) if they are using an encoding other than UTF-8?

Thanks,

**Comment by anthony-tuininga** [comment]
This sounds like a decoding error. In cx_Oracle 6.4 support was added for specifying the encoding errors parameters for the internal decoding that takes place. You can see the enhancement request and other comments by looking [here](https://github.com/oracle/python-cx_Oracle/issues/162#issuecomment-398476948).

**Comment by bschwab003** [comment]
Amazing.  Thank you.  Closing the ticket.
