### ISSUE TITLE
AttributeError: PyCapsule_Import "datetime.datetime_CAPI" is not valid

### ISSUE THREAD

**Issue by campbelldavidj** [oracle/python-cx_Oracle#229]
My buddy's python code on the same box, works like a champ.
I get import errors.

Python 2.7 32 bit.  cx_Oracle 5.1.2.

Tried redoing my LD_LIBRARY_PATH and PYTHONPATH (Even though these were the same as his)
I have all the same exact imports in my script as his, but I'm getting this message:

This comes up on the "Import cx_Oracle" statement:
AttributeError: PyCapsule_Import "datetime.datetime_CAPI" is not valid

**Comment by anthony-tuininga** [comment]
Judging from similar issues reported by others this is due to a mixup of Python versions -- frequently between Python 2.6 and Python 2.7. Can you check that out?

**Comment by anthony-tuininga** [comment]
Assuming that you addressed this issue due to lack of activity.
