### ISSUE TITLE
SessionPool won't accept unicode

### ISSUE THREAD

**Issue by mechsin** [oracle/python-cx_Oracle#23]
Python 2.7 32 bit
cx_Oracle 5.3
Oracle instant client 12.1
Windows 7 64 bit
VCForPython27 Compiler

I have a case where it appears that the cx_Oracle.connect method will accept the login credentials as unicode strings but the cx_Oracle.SessionPool will not. 

I have check this simply by using the same login credentials with both functions. 

In my test case the user name, password, and dsn are all unicode strings. The exception I get when calling the session pool is below.

   sessionPool = cx_oracle.SessionPool(*r_pargs, **r_kwargs)
TypeError: argument 1 must be str, not unicode

I guess this isn't really a bug so much as inconsistent behavior if the connect method accepts Unicode strings I would expect the SessionPool to as well, at least for the fields that is has in common with connect.

**Comment by anthony-tuininga** [comment]
I agree that is inconsistent behaviour. I'll adjust that. Thanks for pointing it out!

**Comment by anthony-tuininga** [comment]
Changes made. I also adjusted connection.changepassword() which was behaving the same way.

**Comment by mechsin** [comment]
Great thanks. 

Can you comment on when this will be released?

**Comment by anthony-tuininga** [comment]
All I can say right now is soon. :-) It might be this week but it might be next week, too. It depends on what else is discovered in the next few days!
