### ISSUE TITLE
Is an Oracle wallet needed for connecting to a TLS 1.2 port?

### ISSUE THREAD

**Issue by mramsey4** [oracle/python-cx_Oracle#234]
Hello cx_Oracle support! The source system that I extract data from is upgrading their Oracle environment to TLS 1.2. To date, I've been using cx_Oracle to extract data against TLS 1.0 ports, which has worked well. However, with this recent upgrade, I keep hitting an error code of ORA-28759, which seems to be caused by a missing Oracle wallet. 

Could this be a caused by a configuration issue on my end, or do I need a wallet to connect? 

#### Answer the following questions:

1. What is your version of Python? Is it 32-bit or 64-bit?
64-bit

2. What is your cx_Oracle version?
7.0

3. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?
cx_Oracle.connect(), logged in as admin

4. What error(s) you are seeing?
ORA-28759

5. What OS (and version) is Python executing on?
tested from both OSX (running instant client 12.2) and Linux (running instant client 18.3)

6. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where is it installed?
12.2 for my local OSX environment, 18.3 for my ETL server. It's installed in the relevant directories as per the documentation

7. What is your Oracle Database version?
12.1.0.2.0

10. Do you have a small, single Python script that immediately runs to show us the problem?
yes

**Comment by anthony-tuininga** [comment]
Can you provide a few more details on your configuration? Can you provide a client side trace? I have no significant expertise on Oracle networking configurations, but I can certainly pass on the information to those who do!

**Comment by mramsey4** [comment]
Hi Anthony - really appreciate you getting back to me on this issue, thanks. 

In terms of configuration, my team doesn't own the Oracle dB installation, so the visibility into that is a bit limited. We use cx_Oracle in our extract layer for our ETL, to pull source data from Oracle into our data mart. To date, we've only ever needed the connection information and login credentials for the Oracle dB. 

I develop python scripts locally (on my Mac), then automate them by scheduling them to run from a Linux VM. Running my scripts from both places results in the ORA-28759 error, but only against the TLS 1.2 port. Other ports, using the older protocols, work fine. We're running on an internal network.

Here's the trace:
My-MacBook-Pro-2:python username$ python test_connection.py 
Traceback (most recent call last):
  File "test_connection.py", line 14, in <module>
    orcl = cx_Oracle.connect(ORACLE_CONNECT)
cx_Oracle.DatabaseError: ORA-28759: failure to open file

(ORACLE_CONNECT contains a string of connection information)

**Comment by anthony-tuininga** [comment]
Thanks for the explanation. It would be useful to include the additional network configuration you are using -- both the working and non-working configurations. What is the contents of your sqlnet.ora? Are you using tnsnames.ora or are you putting everything inside ORACLE_CONNECT. If you can specify what ORACLE_CONNECT is (with the username/password simply replaced by three stars) that might also be helpful.

**Comment by mramsey4** [comment]
Just checked the Linux VM. Those files don't exist there either.

**Comment by anthony-tuininga** [comment]
Ok. I'll see if someone who knows something more than I do about Oracle networking configuration can comment and get back to you.

**Comment by mramsey4** [comment]
Thank you!

**Comment by anthony-tuininga** [comment]
I am informed that using protocol TCPS requires a wallet and the error indicates that the wallet cannot be found. So you'll either need to use TCP or create a wallet and include its location in your sqlnet.ora file. I hope that helps!

**Comment by mramsey4** [comment]
Perfect, thanks Anthony! 

I went ahead and got an Oracle wallet and other full-client (not just instant client) files installed on my machine, such as tnsnames.ora, and was able to connect to the TLS 1.2 port.

Feel free to close this issue.

Thanks again,

-Morgan

**Comment by anthony-tuininga** [comment]
Great! Glad to hear it.

**Comment by cjbj** [comment]
@mramsey4 the libraries in Instant Client are the same as in the full client. You can use wallets with Instant Client easily.  Stick the wallet and tnsnames.ora etc files in a directory and set the `TNS_ADMIN` environment variable to that directory.  Or create a `network/admin` subdirectory under Instant Client and put the files in there.  In fact, the 18.3 Linux Instant Client precreates this directory.

**Comment by rishikesh12** [comment]
@cjbj This is what my customer has to do: 1- get server certificate 2- install Oracle Client -use mkstore/orapki (part of Oracle client) to create a wallet and store sever certificate in that wallet. 4- pass the location of the wallet to my application. But I want to eliminate the steps 2 and 3. Is there a way to programmatically create the wallet and store the server certificate.

**Comment by cjbj** [comment]
@rishikesh12 You should ask security experts at https://community.oracle.com/community/groundbreakers/database/database_security/database_security_-_general/content  

When I've tested wallets I've done it all on the DB server side before copying the wallet to the client, but I may not know all security implications, and you may have subtleties that other people will know about.
