### ISSUE TITLE
gettype issue with Oracle client 12 64bits

### ISSUE THREAD

**Issue by SebGt** [oracle/python-cx_Oracle#235]
I have (on Windows10 and sever 2012 R2) a Python script (3.6.1 64bits) using cx_oracle 6.0.3. to connect to Oracle 18c DB. Connection is working well. My problem is when I try to create Python variable from database type definition using gettype.

Here is my example:
```
db = cx_Oracle.connect("scott/tigger@oracle_18c")
res = db.gettype("type_employee").newobject()
```
Depending on the configuration, I have the following issue:

`2018-10-31 15:28:15,019 - ERROR - OCI-22303: type ""."type_employee" not found`

With Oracle 11g, the script is working well. With Oracle 18c that depends on the Oracle client I use.

I did following tests:
- Python 3.6.1 64bits, CX-ORACLE 6.0.3, Oracle client 11 64 bits => Ok
- Python 3.6.1 64bits, CX-ORACLE 7.0.0, Oracle client 11 64 bits => Ok
- Python 3.6.1 64bits, CX-ORACLE 7.0.0, Oracle client 12 64 bits => NOK
- Python 3.6.1 64bits, CX-ORACLE 6.0.3, Oracle client 12 64 bits => NOK
Using Oracle client 12 32 bits does not make sense as it is not compatible with my config.

Thanks in advance

**Comment by SebGt** [comment]
Issue is the command became case sensitive with Oracle Client 12.
If I change my code with 

    res = db.gettype("TYPE_EMPLOYEE").newobject()

It is working fine

**Comment by anthony-tuininga** [comment]
Thanks for following up. I wasn't aware that in Oracle 11g it **wasn't** case sensitive. That's good to know for others who might run into something similar. I assume this resolves your issue and will close it. If that isn't the case, please re-open!
