### ISSUE TITLE
DPI-1047 error on Linux, but not Windows

### ISSUE THREAD

**Issue by Aalmain** [oracle/python-cx_Oracle#239]
We have a mixed environment oracle verisons and scripting languages. To minimize conflicts, we attempted the setting ov environment variables inside the script. On Linux, when we try to connect to an oracle database, we receive an error (on windows, it workes fine). If we export the variables outside the script, the client works. I did see some of the files had .11.1/12.1 appended to the name. I tried creating symlinks (and even copy with rename) to have the files end with .so.

fyi, 
On Windows we did see performance issues if you use a different version of client form the database version (i.e. 12.2 client on an 11.2 DB). Thus the multiple client installations (along with other scripting languages needing them). 

1. What is your version of Python? Is it 32-bit or 64-bit?
	 **64-bit python 3.4.6 and 3.6.5**

2. What is your version of cx_Oracle?
     **Python 3.4.6 :: cx-Oracle==6.4.1
     Python 3.6.5 :: cx-Oracle==7.0.0**

3. What is your version of the Oracle client (e.g. Instant Client)? 
     **Basic-Lite (11.1, 11.2, 12.1, 12.2, 18.3)**
    How was it installed? 
	 **I downloaded the packages and unzipped the packages.**
    Where is it installed?
	 **/app/pyora/instantclient_11.1
	 /app/pyora/instantclient_11.2
	 /app/pyora/instantclient_12.1
	 /app/pyora/instantclient_12.2
	 /app/pyora/instantclient_18.3**

4. What is your version of the Oracle Database?
     **The database I have been testing on is 11.2**

5. What is your OS and version?
     **SLES 12 SP3**

6. What compiler version did you use? For example, with GCC, run gcc --version.
     **gcc (SUSE Linux) 4.8.5**

7. What environment variables did you set? 
         **PATH, LD_LIBRARY_PATH**
    How exactly did you set them?
	 **Inside the Python script:**
```
path = os.environ["PATH"]
os.environ["PATH"] = "/app/pyora/instantclient_18_3" + path
os.environ["LD_LIBRARY_PATH"] = "/app/pyora/instantclient_18_3"
```

8. What exact command caused the problem (e.g. what command did you try to install with)? 
`dbconn = cx_Oracle.connect(user=username,password=password,dsn=dsn)`

    Who were you logged in as?
	  **Myself, root, test user**

9. What error(s) you are seeing?
    **Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
cx_Oracle.DatabaseError: DPI-1047: 64-bit Oracle Client library cannot be loaded: "libclntsh.so: cannot open shared object file: No such file or directory". See https://oracle.github.io/odpi/doc/installation.html#linux for help**

10. Do you have a small, single Python script that immediately runs to show us the problem?

from base64 import b64encode, b64decode # used for excoding/decoding base64 data
```
import os
import sys
import cx_Oracle # used for accessing the Oracle databases

def decode_data(data):
   return b64decode(data).decode('ascii')

path = os.environ["PATH"]
os.environ["PATH"] = "/app/pyora/instantclient_18_3" + path
os.environ["LD_LIBRARY_PATH"] = "/app/pyora/instantclient_18_3"
print("PATH="+os.environ["PATH"]+"\n")
print("LD_LIBRARY_PATH="+os.environ["LD_LIBRARY_PATH"]+"\n")
username = decode_data("xxxx")
password = decode_data("xxxx")
hostname=decode_data("xxxx")
port=decode_data("xxxx")
schema=decode_data("xxxx")
dsn ="{hostname}:{port}/{schema}".format(hostname=hostname,port=port,schema=schema)
dbconn = cx_Oracle.connect(user=username,password=password,dsn=dsn)
cursor = dbconn.cursor()

```

**Comment by anthony-tuininga** [comment]
This is expected, actually. On Windows you can set the PATH environment variable and subsequent attempts to load a DLL or run an executable will use the modified PATH. On Linux, however, for security reasons LD_LIBRARY_PATH is *only* examined when the application starts. So you have to set it in a script before calling your Python script. There is no way around this -- deliberately!

**Comment by Aalmain** [comment]
Ok, thank you. I was not aware of the difference.  As I am not an oracle guy, may I ask what the security issue was that this compensates for?

**Comment by anthony-tuininga** [comment]
The difference isn't an Oracle thing, but a Linux (Unix) one. If LD_LIBRARY_PATH was examined at run-time malicious code could be injected much more easily. Note that LD_LIBRARY_PATH is ignored completely for setuid and setgid binaries, again for security reasons.

I'm assuming your questions has been answered so I'll close this now!
