### ISSUE TITLE
Information Request: v5.1.2 and Collect

### ISSUE THREAD

**Issue by bendodds** [oracle/python-cx_Oracle#246]
Hello, we are having some stability issues using cx_Oracle that we are investigating and having trouble pinning down. One thing that has been added around when we started having issues is the use of `collect` statements in our Oracle views:

```
 ( select cast(collect(osk.Key) as common.udt_KeyStringList)
    from possedata.ObjectKeys osk
    where osk.ObjectId = o.ObjectId
  ) ObjectKeys
```

This appears to work most of the time, but when we call `cx_Oracle.Cursor.execute` against views that contain the `collect` statements we are periodically receiving errors like
> ORA-24338: statement handle not executed

and

> Invalid handle!

and

> InterfaceError: query not executed

We are experiencing this issue in our hit-based multi-threaded applications that reuse connections and cursors over several hits. We are not, however, seeing this issue in our single-threaded command line application that can leverage the same classes and code.

In the release notes I see several indications that improvements were made to cx_Oracle since 5.1.2 regarding collections. Have stability issues with using this Oracle feature been fixed in later versions?

Windows Python version: 2.7.1
cx_Oracle version: 5.1.2
Oracle DB version: 11.2.0.4

Thanks,
Ben Dodds
Computronix Canada

**Comment by anthony-tuininga** [comment]
First, a few questions that might help narrow down the issue:

What is the type of data returned for the column "ObjectKeys"?

Are you using the same client as the database? Or a different client?

Is there a lot of activity going on at the same time in the client? How many cursors are open and how many are allowed to be open?

I would suggest trying to create a simple test case that demonstrates the issue, first in your environment (cx_Oracle 5.1.2 on Windows Python 2.7.1 against Oracle Database 11.2.0.4). It should also be one that I might be able to run as well. Then try with cx_Oracle 7 and newer versions of the Oracle Client and see if the problem persists.

**Comment by bendodds** [comment]
Wow, thanks for the quick reply!

The data type of `udt_ObjectKeys` is this:

```
create or replace type udt_Key as object (
  AccessGroupName            varchar2(60),
  ObjectId                   number(9)
);

create or replace type udt_KeyList as table of udt_Key;
```

The client and database oracle versions are both 11.2.0.4. There does not need to be a lot going on in the database for these errors to occur. Some developers are experiencing them in their local databases, some in our shared databases. Our multi-threaded apps do create multiple hits in one action, sometimes tens of hits, which will all use the set of cached cursors. There will typically be 2 worker processes with 8 threads each, each thread has its own connection. Each thread will have many connections, upward of 50 each, but it isn't strictly defined.

We have been working for some time to determine consistent replication steps. I will continue working on this.

Are you aware of any issue that have been fixed since version 5.1.2?

Thanks,
Ben

**Comment by anthony-tuininga** [comment]
> Are you aware of any issue that have been fixed since version 5.1.2?

There have been many enhancements and bugs fixed on objects support since version 5.1.2! I can't say if any of these would address your issues, though. You should be able to simply pop a new version of cx_Oracle in place, though, and see if you get the same issues. Unless you are using features (and "features", aka bugs) that were corrected in versions 6 and 7 you shouldn't have any difficulties. Take a look at the [release notes](https://cx-oracle.readthedocs.io/en/latest/releasenotes.html) to figure that out.

**Comment by bendodds** [comment]
I copied the wrong type for udt_KeyStringList, I've corrected it in the above post. I will continue to try to replicate the issue, and if I can do this reasonably, I will upgrade to 6 and try it there.

Thanks,
Ben

**Comment by anthony-tuininga** [comment]
Ok. Sounds good.

**Comment by bendodds** [comment]
Upgrading to cx_Oracle 6.4.1 has corrected the issue. Thank you very much for your help!

Ben

**Comment by anthony-tuininga** [comment]
Glad to hear it! Thanks for following up. I'll close this now.
