### ISSUE TITLE
Is it possible to provide 'rowtype parameters' for a procedure?

### ISSUE THREAD

**Issue by wancharle** [oracle/python-cx_Oracle#247]
Hello,

I would like to know if it is possible through python to call an oracle procedure with an argument of type rowtype (table%rowtype).

My procedure has several arguments, among them it has one that is rowtype of a table.
My script does some searches in the database and with each record of the result it should call this procedure with the registry as parameter.

I have already thought about modifying the procedure to not use rowtype. But there are many others in the database with the same problem that I can not change.

I looked in the documentation but I did not find an example ... So I suppose it is not possible to pass this type of parameter. If this is the case I would like to know if you intend to include this feature someday.

Thank you for your attention.

**Comment by anthony-tuininga** [comment]
Once you understand that TABLE%ROWTYPE is just a record then you'll be able to find this [sample](https://github.com/oracle/python-cx_Oracle/blob/master/samples/PLSQLRecord.py) which will show you how to use it. :-) So for example....

```
conn = cx_Oracle.connect("user/pw@dsn")
objType = conn.gettype("TABLE%ROWTYPE")
obj = objType.newobject()
obj.COLUMN1 = 5
obj.COLUMN2 = "A String"
```

I'll add a note in that sample indicating that TABLE%ROWTYPE is also acceptable as a source for record types.

**Comment by wancharle** [comment]
Hi,

That's what I needed.

Thank you!

**Comment by semakmillev** [comment]
> Once you understand that TABLE%ROWTYPE is just a record then you'll be able to find this [sample](https://github.com/oracle/python-cx_Oracle/blob/master/samples/PLSQLRecord.py) which will show you how to use it. :-) So for example....
> 
> ```
> conn = cx_Oracle.connect("user/pw@dsn")
> objType = conn.gettype("TABLE%ROWTYPE")
> obj = objType.newobject()
> obj.COLUMN1 = 5
> obj.COLUMN2 = "A String"
> ```
> I'll add a note in that sample indicating that TABLE%ROWTYPE is also acceptable as a source for record types.

Trying to use your advise, i'm getting cx_Oracle.DatabaseError: ORA-00911: invalid character
`out_rec = cursor.var(cx_Oracle.OBJECT, typename="DOCUMENTS%ROWTYPE")`
or
`type = db.connection.gettype("mbank.documents%rowtype")`
 
i m sure that problem in %-char, but i don't know how to fix it

**Comment by anthony-tuininga** [comment]
What version of cx_Oracle and the Oracle Client and Oracle Database are you using?

**Comment by semakmillev** [comment]
> What version of cx_Oracle and the Oracle Client and Oracle Database are you using?

cx_Oracle=7.1.2
Oracle_Version=12.2.0.1.0
client_version=11.2.0.3

**Comment by anthony-tuininga** [comment]
Your client version is too old. You need to be using 12.1 at least. Please upgrade your client and try again!

**Comment by semakmillev** [comment]
> Your client version is too old. You need to be using 12.1 at least. Please upgrade your client and try again!

Yeah, i tried on other machine with 12.1 client an it starts working.
Thanks!
