### ISSUE TITLE
Support for Alpine Linux

### ISSUE THREAD

**Issue by daveisfera** [oracle/python-cx_Oracle#249]
Alpine Linux is becoming a very common base for building containers. It would be nice to be able to use these same base images for connecting to Oracle database, so could the install instructions be updated to include how to do this with Alpine Linux?

**Comment by cjbj** [comment]
Oracle Client requires glibc so our recommendation is the use a container like oraclelinux-7:slim e.g. like https://github.com/oracle/docker-images/blob/master/OracleInstantClient/dockerfiles/18.3.0/Dockerfile
If you care about your applications running without hitting unexpected errors, don't use Alpine :)  I can't recommend using Alpine.

**Comment by daveisfera** [comment]
Could a version of Oracle Client be built with musl? Or Alpine linux also provides glibc, so could that be used?

**Comment by cjbj** [comment]
Building Oracle client for musl is a question for someone who is much higher in the company than me, and has a huge budget for building, testing, supporting and maintenance.  Every now and again, I mention the topic.  You should also contact your Oracle account people and tell them your business case.  Questions about what Alpine Linux provides are best asked to the Alpine developers.

**Comment by daveisfera** [comment]
We're not Oracle customers but our customers are and we need to support the Oracle driver, so is there a channel that I could communicate this need through?

**Comment by cjbj** [comment]
@daveisfera do you have contacts via, say, Oracle Partner network?   In general, as with any big architecture change request, contacting everyone you know at Oracle helps create a groundswell.  Ask your customers to contact their sales reps.  You will need to provide a very good business case.
