### ISSUE TITLE
cx_Oracle 6 Plans

### ISSUE THREAD

**Issue by anthony-tuininga** [oracle/python-cx_Oracle#25]
Thanks for all of the feedback so far on cx_Oracle 6 beta 1. The current plan is to make a release candidate next week containing the bug fixes made so far and, if nothing significant is found, to make the final release after I return from my vacation (likely mid June). Please comment here to provide feedback or create a new issue if you discover something that needs to be addressed. Thanks!

**Comment by jmcp** [comment]
That timing seems reasonable to me, thankyou.

**Comment by anthony-tuininga** [comment]
Thanks to a couple of unresolved issues that I need to track down, I am releasing a new beta shortly instead of a release candidate. When I return from my vacation we'll see if another release is warranted before the production release is made. Please continue to provide feedback. Thanks!

**Comment by truthbk** [comment]
Hi @anthony-tuininga 👋 

Any estimated timeline for the production release?

Thanks!

**Comment by anthony-tuininga** [comment]
Very soon! Barring unforeseen circumstances, sometime in the next week, actually. :-)

**Comment by anthony-tuininga** [comment]
cx_Oracle 6 has now been released!
