### ISSUE TITLE
Connection.close() stuck with "SQL*Net break/reset to client" on KeyboardInterrupt

### ISSUE THREAD

**Issue by gvenzl** [oracle/python-cx_Oracle#250]
When stopping a Python program with [Ctrl]+[C] and handling that correctly in the code via intercepting `KeyboardInterrupt` exception and closing the connection, the `.close()` method hangs and prevents the program from exiting. Even multiple times sending [Ctrl]+[C] doesn't work and the program needs to be killed.

Here a simple code snippet to reproduce the issue:

```python
import cx_Oracle

try:
    conn = cx_Oracle.connect("test",
                             "test",
                             "localhost/ORCLPDB1")
    cur = conn.cursor()
    cur.execute("select 1 from dual")
    input("Press Enter to continue")
    cur.close()
    conn.close()
except KeyboardInterrupt:
    print("Exiting program")
    conn.close()
```
The program will wait for the user to hit [Enter].
However, when you actually send a [Ctrl]+[C], nothing happens:

```bash
gvenzl-mac:Downloads gvenzl$ python3.7 python_test.py
Press Enter to continue^CExiting program
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C
```

You can see that the exception block has been reached and "Exiting program" printed.

When checking v$session the session is there inactive, waiting for `SQL*Net break/reset to client`:

```sql
select sid, serial#, username, status, event, p1, p2, p3, wait_class, state, blocking_session_status
from v$session s where username = 'TEST';

   SID    SERIAL# USERNAME STATUS   EVENT                         P1         P2         P3         WAIT_CLASS  STATE   BLOCKING_SE
------ ---------- -------- -------- ----------------------------- ---------- ---------- ---------- ----------- ------- -----------
   290      37267 TEST     INACTIVE SQL*Net break/reset to client 1413697536          0          0 Application WAITING NO HOLDER  
```

Even when killing the session, the session (in `KILLED` state) and the program remain:

```sql
alter system kill session '290,37267';

System KILL altered.

select sid, serial#, username, status, event, p1, p2, p3, wait_class, state, blocking_session_status
from v$session s where username = 'TEST';

   SID    SERIAL# USERNAME STATUS   EVENT                         P1         P2         P3         WAIT_CLASS  STATE               BLOCKING_SE
------ ---------- -------- -------- ----------------------------- ---------- ---------- ---------- ----------- ------------------- -----------
   290      37267 TEST     KILLED   SQL*Net break/reset to client 1413697536          0          0 Application WAITING             NO HOLDER  
```

Interestingly, without any `try/except` block the program exits just fine, but that might just be because the process is terminated altogether on the second [Ctrl]+[C]:

```python
import cx_Oracle

conn = cx_Oracle.connect("test",
                         "test",
                         "localhost/ORCLPDB1")
cur = conn.cursor()
cur.execute("select 1 from dual")
input("Press Enter to continue")
cur.close()
conn.close()
```

```bash
gvenzl-mac:Downloads gvenzl$ python3.7 python_test1.py
Press Enter to continue^CTraceback (most recent call last):
  File "python_test1.py", line 8, in <module>
    input("Press Enter to continue")
KeyboardInterrupt
^C
```

#### Answer the following questions:

1. What is your version of Python? Is it 32-bit or 64-bit?
```bash
gvenzl-mac:Downloads gvenzl$ python3.7
Python 3.7.0 (default, Aug 22 2018, 15:22:33)
[Clang 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
```

2. What is your cx_Oracle version?
```bash
gvenzl-mac:Downloads gvenzl$ pip list
Package                Version
---------------------- ---------
certifi                2018.8.24
cx-Oracle              7.0.0
pip                    18.0
pipenv                 2018.7.1
setuptools             40.2.0
six                    1.12.0
virtualenv             16.0.0
virtualenv-clone       0.3.0
wheel                  0.31.1
```

3. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?
`connection.close()`

4. What error(s) you are seeing?
method hangs with "SQL*Net break/reset to client"

5. What OS (and version) is Python executing on?
Mac OS X High Sierra (10.13.6)

6. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where is it installed?
12.2.0.1.0, installed in ~/lib/:

```bash
gvenzl-mac:Downloads gvenzl$ ls -al ~/lib/
total 613568
drwxr-xr-x@ 19 gvenzl  staff        608 Jun 25  2018 .
drwxr-xr-x+ 89 gvenzl  staff       2848 Jan  6 00:01 ..
-rw-rw-rw-@  1 gvenzl  staff        400 Jan 10  2018 BASIC_README
-rwxrwxrwx@  1 gvenzl  staff      10036 Jan 10  2018 adrci
-rwxrwxrwx@  1 gvenzl  staff      40360 Jan 10  2018 genezi
-rw-r--r--@  1 gvenzl  staff   68160048 Jun 25  2018 instantclient-basic-macos.x64-12.2.0.1.0-2.zip
lrwxrwxrwx   1 gvenzl  staff         20 Jun 25  2018 libclntsh.dylib -> libclntsh.dylib.12.1
-rwxrwxrwx@  1 gvenzl  staff   85621532 Jan 10  2018 libclntsh.dylib.12.1
-rwxrwxrwx@  1 gvenzl  staff    4685408 Jan 10  2018 libclntshcore.dylib.12.1
-r-xr-xr-x@  1 gvenzl  staff    8179072 Jun 29  2017 libnnz12.dylib
lrwxrwxrwx   1 gvenzl  staff         18 Jun 25  2018 libocci.dylib -> libocci.dylib.12.1
-rwxrwxrwx@  1 gvenzl  staff    1465312 Jan 10  2018 libocci.dylib.12.1
-rwxrwxrwx@  1 gvenzl  staff  124769196 Jan 10  2018 libociei.dylib
-r-xr-xr-x@  1 gvenzl  staff     151748 Aug  8  2017 libocijdbc12.dylib
-r-xr-xr-x@  1 gvenzl  staff     237780 Jan  8  2018 libons.dylib
-rwxrwxrwx@  1 gvenzl  staff      84988 Jan 10  2018 liboramysql12.dylib
-r--r--r--@  1 gvenzl  staff    4036257 Dec 13  2016 ojdbc8.jar
-rwxrwxrwx@  1 gvenzl  staff     146084 Jan 10  2018 uidrvci
-r--r--r--@  1 gvenzl  staff      74230 Jan 26  2017 xstreams.jar

gvenzl-mac:Downloads gvenzl$ cat ~/lib/BASIC_README
Basic Package Information
=========================

Tue Jan  9 23:52:43 PST 2018

Client Shared Library 64-bit - 12.2.0.1.0

System name:	Darwin
Release:	15.6.0
Version:	Darwin Kernel Version 15.6.0: Sun Jun  4 21:43:07 PDT 2017; root:xnu-3248.70.3~1/RELEASE_X86_64
Machine:	x86_64

Operating in ORACLE_HOME environment.

Small timezone file = timezone_26.dat
Large timezone file = timezlrg_26.dat
```
7. What is your Oracle Database version?
18.3.0-ee

8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?
The Instant Client

9. What Oracle environment variables did you set?  How *exactly* did you set them?
None

10. Do you have a small, single Python script that immediately runs to show us the problem?
Yup, already provided above.

**Comment by gvenzl** [comment]
Just noticed on database shutdown, and hopefully helpful, the program dies with:

```bash
gvenzl-mac:Downloads gvenzl$ python3.7 python_test.py
Press Enter to continue^CExiting program
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C
^C^C^C^C^C

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python_test.py", line 14, in <module>
    conn.close()
cx_Oracle.DatabaseError: ORA-12152: TNS:unable to send break message
```

**Comment by cjbj** [comment]
Sounds like the known SQL*Net "feature".  Your test doesn't hang for me with DISABLE_OOB=ON in sqlnet.ora.  It does hang if I don't have that setting..

**Comment by anthony-tuininga** [comment]
On my machine your code works perfectly without needing to set DISABLE_OOB=ON -- but I am running Linux, not macOS. As such, I would agree with @cjbj that this is "expected" behaviour. If you can verify that the issue goes away with the setting Chris mentioned I think we can safely close this issue.

**Comment by gvenzl** [comment]
I still would like to know why this happens, and only on Mac apparently.

I just tested on Linux as well, without setting `DISABLE_OOB=ON` and it works just fine.
That discrepancy between Linux and Mac makes me wonder what's different between those two environments. Shouldn't they behave the same?

There also seems no way to ever recover again from that state.
Closing the cursor, getting a new cursor and executing a statement, both have no effect on the behavior when trying to finally close the connection.
Killing the connection on the database server does also nothing, so the only workaround right now is to kill the program on the client from the outside, i.e. `kill ...`.

**Comment by anthony-tuininga** [comment]
I have no idea why that is the case. Perhaps @cjbj has some insight?

**Comment by cjbj** [comment]
I discussed this with @gvenzl the other day to the extent of my knowledge.  We can ask the Net team to comment further.

I don't understand the recent comment about having to kill the program, since the SQL*Net setting is available.

**Comment by gvenzl** [comment]
If `DISABLE_OOB` is not set to `ON` one has to kill the entire client application in order to get rid of that connection (or I assume, but not tested, the session process on the server). That's not quite enterprise class behavior in my opinion. That, alongside with that fact that it behaves differently on Linux (where the session doesn't hang even without having `DISABLE_OOB=ON`) and Mac OS X I believe deserves to have a closer look on what's going on there and why the sessions gets stuck.

**Comment by cjbj** [comment]
@gvenzl I already discussed the futures on this with you offline.  

I don't have any preconception that signal handling or network behavior on BSD should be the same as Linux.

Also, where is your DB?  When one of our testers was playing with something like this last year, there was a difference in a DB installed on hardware, vs in VirtualBox.

**Comment by gvenzl** [comment]
Yes indeed we talked about the futures but we still don't know whether this will be addressed by that or whether we found a bug or edge case. It seems logical to me to at least have a little closer look to explain what is happening and make sure that this is indeed addressed by the futures, no?

The DB is running inside a Docker container on the same machine.

**Comment by cjbj** [comment]
Closing this - there is an Oracle discussion about improvements.  The bottom line for the moment is to use DISABLE_OOB=ON
