### ISSUE TITLE
Parametrized values for the connection string 

### ISSUE THREAD

**Issue by Terizian** [oracle/python-cx_Oracle#255]
As a part of the security considerations of the project I'm working on, I have to deal with an encrypted connection string as a part of my configuration.

I read the connection string and convert it to a list in this format
`["user='username'", "password='password'", "dsn='dsn'"]`

I perform string splitting in order to fetch the values for each of the required values. However, it throws an ORA error when executing the code below

`connection = cx_Oracle.connect(user = values[0] , password = values[1], dsn = values[2])`

When I place the values as plaintext, the connection works. How can I make the code above work? Also, what does this function take as parameters?

**Comment by anthony-tuininga** [comment]
I'd check the contents of values[0]. If values[0] contains the string "user=" in addition to the user name that's not going to work out well for you! You'll need to strip that information out in that case.

**Comment by anthony-tuininga** [comment]
Something is apparently different. If the values that you pass directly match the values in your array, then it will work as expected! You can see the documentation for the function [here](https://cx-oracle.readthedocs.io/en/latest/module.html#cx_Oracle.connect).

So if you have this:

```python
values = ["myuser", "mypassword", "mydsn"]
```

then this

```python
cx_Oracle.connect(user=values[0], password=values[1], dsn=values[2])
```

will work just as well as

```python
cx_Oracle.connect(user="myuser", password="mypassword", dsn="mydsn")
```

**Comment by Terizian** [comment]
That's what I thought as well as I reviewed the documentation. The funny thing is that when I print out the values in my list and copy paste those values into the connection string, it works just fine. However, when I pass them using the list it throws an Oracle error.

**Comment by Terizian** [comment]
I have edited my earlier response to include the error. You were right about the addition of characters. The string value contained single quotes. I used the replace() function to get rid of them and the connection string worked! Thanks a lot for your guidance :)

**Comment by anthony-tuininga** [comment]
Excellent! Glad to hear you got it resolved. :-)
