### ISSUE TITLE
How to detect dropped database connection?

### ISSUE THREAD

**Issue by kyrick** [oracle/python-cx_Oracle#259]
**Description**
I'm trying to add robustness to my python code to guard against a node on the Oracle DB server going down unexpectedly. What I've found: if this occurs after a successful connection to the database my cursor.execute() will hang indefinitely.

I can reproduce this scenario in a simple test script that connects to the database and sleeps for 5 seconds. During the sleep I turn off wifi. The execute statement then hangs indefinitely. 

However, while cx_Oracle is hanging, instant client is logging timeout errors in sqlnet.ora. (see below)

**My questions are:**
1. Why is cx_Oracle unaware of these errors? 
2. How can I make the cursor timeout and raise an exception in Python?

**What is your version of Python? Is it 32-bit or 64-bit?**
Python 2.7 64 bit

**What is your cx_Oracle version?**
7.0.0

**What error(s) you are seeing?**
Errors in sqlnet.log:
```
TNS-12535: Message 12535 not found; No message file for product=network, facility=TNS
    ns secondary err code: 12609
    nt main err code: 0
    nt secondary err code: 0
    nt OS err code: 0
  Client address: (ADDRESS=(PROTOCOL=tcp)(HOST=XX.XX.XX.XX)(PORT=XXXX))
```

**What OS (and version) is Python executing on?**
Debian GNU/Linux 9 (stretch)

**What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where is it installed?**
* 18.3
* Installed from oracle-instantclient18.3-basiclite-18.3.0.0.0-1.x86_64.rpm.
* Installed in the default location: 

**What is your Oracle Database version?**
11.2.0.4

**What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?**
```
LD_LIBRARY_PATH=/usr/lib/oracle/18.3/client64/lib
```

**What Oracle environment variables did you set?  How *exactly* did you set them?**
All environment variables as setup in the Dockerfile via the ENV command.
```
ORACLE_HOME=/usr/lib/oracle/18.3/client64
LD_LIBRARY_PATH=$ORACLE_HOME/lib
PATH=$PATH:$ORACLE_HOME/bin
TNS_ADMIN=/usr/lib/oracle/18.3/client64/network/admin/
```

10. Do you have a small, single Python script that immediately runs to show us the problem?

```python
if __name__ == '__main__':
    user = 'user'
    password = 'pwrd'
    database_name = 'dbname'

    connection_string = "{0}/{1}@{2}".format(user, password, database_name)
    con = cx_Oracle.Connection(connection_string)
    cursor = con.cursor()

    raw_input('Disconnect internet now. Then press Enter')

    print('execute')
    cursor.execute('select * from some_table where some_condition')
    print('fetchall')
    res = cursor.fetchall()
    print('done', res)
```

**Comment by anthony-tuininga** [comment]
Take a look at issue #17 which looks to be very similar if not identical to your situation.
