### ISSUE TITLE
cx_Oracle-5.3-11g.win-amd64-py3.5-2.exe seems to be the wrong version

### ISSUE THREAD

**Issue by C0ppert0p** [oracle/python-cx_Oracle#26]
Hopefully, I'm just an idiot, but
when I run cx_Oracle-5.3-11g.win-amd64-py3.5-2.exe the console indicates I need to be running Python 3.4:
UnsatisfiableError: The following specifications were found to be in conflict:

cx_oracle 5.2* -> python 3.4*
python 3.5*
I'm running Anaconda and have Python 3.5 using the root environment
H:>python --version
Python 3.5.3 :: Anaconda custom (64-bit)

so, is cx_Oracle-5.3-11g.win-amd64-py3.5-2.exe really what it claims to be?

**Comment by anthony-tuininga** [comment]
Looks like it to me. I just downloaded it and it successfully finds Python 3.5. It is possible Anaconda is doing something that is preventing the installation from taking place. Can you try in an installation that doesn't have Anaconda to confirm that?

**Comment by C0ppert0p** [comment]
Luckily I'm just an idiot.
Python, was already installed on this machine, as a stand alone application and had made registry entries. Anaconda doesn't used the registry and as a result x_Oracle-5.3-11g.win-amd64-py3.5-2.exe put the new version of the cx_oracle data, under the original Python location.

**Comment by anthony-tuininga** [comment]
Glad to hear you got it figured out. I'm assuming this can be closed. If not, feel free to re-open!
