### ISSUE TITLE
DPI-1047 on CentOS with cx_Oracle and Oracle Instant Client 12.1 RPMs NGINX Gunicorn

### ISSUE THREAD

**Issue by Kumarjeet1990** [oracle/python-cx_Oracle#261]
Below is my configuration:-

Python - 3.7
Django - 1.18.118
cx_Oracle - 7
OS - Centos
Reverse Proxy Server:- NGINX
WSGI Server:- Gunicorn
Oracle Instant Client:- 12.1

When I open the application I constantly get the error DPI-1047: 64 bit Oracle client library cannot be loaded : 'libclntsh.so cannot open shared object file: No such file or directory ".

ORACLE_HOME is set in .bash_profile, and the file exists in ORACLE_HOME lib folder, with the symlink. Why doesnt the application get the file? The permissions for the file has been given as 777. The cx_Oracle works in the python3 shell.

#### Answer the following questions:

1. What is your version of Python? Is it 32-bit or 64-bit? 3.7.1 64 bit

2. What is your cx_Oracle version? cx_Oracle 7

3. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as? Django application with nginx, gunicorn.

4. What error(s) you are seeing?

5. What OS (and version) is Python executing on? Centos7

6. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where is it installed? 12.1

7. What is your Oracle Database version? 11g

8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`? /usr/lib/oracle/client64/lib

9. What Oracle environment variables did you set?  How *exactly* did you set them? $ORACLE_HOME, $TNS_ADMIN in .bash_profile

10. Do you have a small, single Python script that immediately runs to show us the problem?

**Comment by cjbj** [comment]
You need to make sure the Python process has the necessary environment configured correctly - web servers often need custom configuration and are unlikely to inherit a setting in `~/.bash_profile`. 
 Check the [installation instructions](https://cx-oracle.readthedocs.io/en/latest/installation.html#oracle-instant-client-rpms).    I'd recommend using `ldconfig`.  Also, when you are using Instant Client you don't set `ORACLE_HOME`.

**Comment by Kumarjeet1990** [comment]
The issue is resolved. You are right, i had to ldconfig. I updated the file /etc/ld.so.conf.d/oracle-instantclient.conf"
 with the instant client library path and it then ldconfigd it. That did the trick.

**Comment by Kumarjeet1990** [comment]
I am closing the issue.
