### ISSUE TITLE
Threaded python script throws OMP and ORA error

### ISSUE THREAD

**Issue by Terizian** [oracle/python-cx_Oracle#262]
I have created a python script that utilizes both the multiprocessing and threading libraries in Python. I have set the number of processes to be the total number of cores (32 in my case) and the number of threads to 2. Each thread connects to the Oracle DB to fetch data that is then processed and the records are updated in the database. However, at this current setting I get the following error:

```
OMP: Error #34: System unable to allocate necessary resources for OMP thread:
OMP: System error #11: Resource temporarily unavailable
OMP: Hint Try decreasing the value of OMP_NUM_THREADS.
ORA-24550: signal received: [si_signo=6] [si_errno=0] [si_code=-6] [si_int=0] [si_ptr=(nil)] [si_addr=0x3e8000057a0]
```

When I run the same script using 4 processes and 2 threads, no errors are thrown. What can I do to resolve the error?

**Comment by cjbj** [comment]
The first thing I'd look at is what system resources you need for threaded environments.

Since we don't know your code, there's not a lot more to be said.  We can Google just as easily as you about OMP_NUM_THREADS, but only you have the system in front of you :)

**Comment by Terizian** [comment]
> The first thing I'd look at is what system resources you need for threaded environments.
> 
> Since we don't know your code, there's not a lot more to be said. We can Google just as easily as you about OMP_NUM_THREADS, but only you have the system in front of you :)

Apologies for not being able to share the code. It's on an isolated network. I have looked at the system resources used by the code and there is a heavy consumption of computing power and memory. I do not think it is attributed to the cx_Oracle library. I was confused by the Oracle error thrown. Thanks a lot :) Will close this issue
