### ISSUE TITLE
cx_oracle not supporting we8dec in python 3

### ISSUE THREAD

**Issue by biskilled** [oracle/python-cx_Oracle#263]
*Delete unnecessary parts of this template.*

### For security issues:

See https://www.oracle.com/support/assurance/vulnerability-remediation/reporting-security-vulnerabilities.html for how to report security issues.

### For general questions:

Describe exactly what you did and what you want to happen.
Use the questions at the bottom of this template as a guide.

Use Markdown syntax, particularly for code blocks: see https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

### For installation issues:

Use a gist for screen output and logs: see https://gist.github.com/
**Do not paste long output into this issue**

Review your output and logs.  **Google any errors**
Try to install in a different way.  Try some potential solutions.

Review the install instructions at
http://cx-oracle.readthedocs.io/en/latest/installation.html

#### Answer the following questions:

1. What is your version of Python? Is it 32-bit or 64-bit?

2. What is your cx_Oracle version?

3. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?

4. What error(s) you are seeing?

5. What OS (and version) is Python executing on?

6. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where is it installed?

7. What is your Oracle Database version?

8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?

9. What Oracle environment variables did you set?  How *exactly* did you set them?

10. Do you have a small, single Python script that immediately runs to show us the problem?

**Comment by biskilled** [comment]
using : python 3.7.1, 64bit. cx_racle: 7.1 
while changing nls_lang to hebrew_israel.we8dec I receive an error : 
LookupError: unknown encoding: DEC-MCS

OS: windows 7 OS
Oracle client : 12.1.0

While using python 2.7.X - all works fine

**Comment by anthony-tuininga** [comment]
Python 2.7 doesn't use Unicode values but simply transfers the raw bytes to you directly. You'll get the same error with Python 2.7, though, if you try to use Unicode!

Is there a reason you want to use that encoding instead of one of the ones that Python knows about?

**Comment by biskilled** [comment]
yes. 
yes.
yes. I am trying to connect into installed oracle with NLS_CHARACTERSET equal to we8dec. 
While trying to use utf-8 encoding I cannot receive the data properly.
The only way I can extract data with the the right charset is by setting NLS_LANG to we8dec charset. 

In python 2.X there are no issues, but pythn 3.X failed.

Sample script:
import os, sys

print ("Default encoding %s" %sys.getdefaultencoding())
os.environ["NLS_LANG"] = "hebrew_israel.we8dec"
import cx_Oracle

conn = cx_Oracle.connect (User, Pass, conn ) 
print("Connection encoding %s" %conn.encoding)
sql = "SELECT XXXXX FROM SAPR3.YYYYYY "

curr = conn.cursor()
curr.execute(sql)

Python 2.X results:
Default encoding ascii
Connection encoding DEC-MCS

Python 3.X results:
Default encoding utf-8
Traceback (most recent call last):
Connection encoding DEC-MCS
  File "C:/test.py", line 12, in <module>
    curr.execute(sql)
LookupError: unknown encoding: DEC-MCS

**Comment by anthony-tuininga** [comment]
> The only way I can extract data with the the right charset is by setting NLS_LANG to we8dec charset.

That should not be the case, as far as I understand. What did you do in order to extract the data? You should be able to do something like this:

```
import cx_Oracle

conn = cx_Oracle.connect(user, password, connectString, encoding="UTF-8", nencoding="UTF-8")
cursor = conn.cursor()
cursor.execute("select XXXX from SAPR3.YYYYYY")
```

Can you try that and let me know if you get any errors doing so? Thanks.

**Comment by biskilled** [comment]
Hi, 
I did it, sample code : 
 
conn = cx_Oracle.connect (user, pass, connectionString,encoding="utf-8", nencoding="utf-8"  )
print("Connection encoding %s" %conn.encoding)

curr = conn.cursor()
curr.execute(sql)
results = curr.fetchall ()
print (results)
for r in results:
    print (r[0].encode("utf-8"))

Result : 
Connection encoding UTF-8
[('øîë-àéæå', 'îø-àéæå'), ('øîë-àéæå', 'îø-àéæå'), ('øîë-âñèø', 'îë-âñèø'), ('øîë-âñèø', 'îë-âñèø'), ('øî-ëàá', 'î-ëàá'), ('øî-ôìñ', 'î-ôìñ'), ('øî-ôñéëé', 'î-ôñéëé'), ('øî-ëàá', 'î-ëàá'), ('øî-ëàá', 'î-ëàá')]

b'\xc3\xb8\xc3\xae\xc3\xab-\xc3\xa0\xc3\xa9\xc3\xa6\xc3\xa5'
b'\xc3\xb8\xc3\xae\xc3\xab-\xc3\xa0\xc3\xa9\xc3\xa6\xc3\xa5'
b'\xc3\xb8\xc3\xae\xc3\xab-\xc3\xa2\xc3\xb1\xc3\xa8\xc3\xb8'
....

I cannot use the return data in any format. I tried to encode each column without a success. 

Another think - python 2.X functioning properly only after I change  system locale property at the language machine settings into Hebrew

**Comment by anthony-tuininga** [comment]
What is wrong with the first result? What is it supposed to look like?

**Comment by biskilled** [comment]
python 2.x:

Connection encoding DEC-MCS
result in list is stored at the right utf-8 format:
>> print (results)
	[('\xf8\xee\xeb-\xe0\xe9\xe6\xe5',), ('\xf8\xee\xeb-\xe0\xe9\xe6\xe5',), ('\xf8\xee\xeb-\xe2\xf1\xe8\xf8',), ('\xf8\xee\xeb-\xe2\xf1\xe8\xf8',)]


After decoding each word: 
>> for r in results:
>>     print (r[0].decode ("windows-1255"))

רמכ-איזו
רמכ-איזו
רמכ-גסטר
רמכ-גסטר
רמכ-איזו
רמכ-איזו
רמכ-גסטר
רמכ-גסטר

Result return at the right character format 
I tried to store the data in a different DB which using Collation : Hebrew_CI_AS and data is stored correctly (רמכ-איזו ..... )

python 3.x:
Connection encoding UTF-8
result in list is stored in an unknown format :
>> print (results)
	[('øîë-àéæå',), ('øîë-àéæå',), ('øîë-âñèø',), ('øîë-âñèø',)]
	
After encoding each word: 
>> for r in results:
>>     print (r[0], r[0].encode("utf-8"))

øîë-àéæå b'\xc3\xb8\xc3\xae\xc3\xab-\xc3\xa0\xc3\xa9\xc3\xa6\xc3\xa5'
øîë-àéæå b'\xc3\xb8\xc3\xae\xc3\xab-\xc3\xa0\xc3\xa9\xc3\xa6\xc3\xa5'
øîë-âñèø b'\xc3\xb8\xc3\xae\xc3\xab-\xc3\xa2\xc3\xb1\xc3\xa8\xc3\xb8'
øîë-âñèø b'\xc3\xb8\xc3\xae\xc3\xab-\xc3\xa2\xc3\xb1\xc3\xa8\xc3\xb8'

Result returned in a wrong character format 
I tried to store the data in a different DB which using Collation : Hebrew_CI_AS and data is not stored correctly (øîë-àéæå ..... )

**Comment by anthony-tuininga** [comment]
Ok. So try the following instead:

```python
conn = cx_Oracle.connect(user, password, dsn, encoding="WINDOWS-1255")
cursor = conn.cursor()
cursor.execute("your query")
for row in cursor:
    print(row)
```

Based on what you are doing above that should work for you. I'm still not sure why Oracle is not doing the transformation for you. I assume, however, that the data is stored in the database in the proper format and you are just doing a query? You aren't trying to store the data in the same script and then fetching it back out again?

**Comment by biskilled** [comment]
Regarding the data - it is stored in oracle properly (using hebrew_israel.we8dec charset)
I am just doing a simple select query. 
While using 3rd part IDE - I do get the result set properly. 
In the sample above - I printed to result from cursor.fatchall() directly. after the printing sample I stored the data 
 
I tried - using WINDOWS-1255 and it is still not working

result using WINDOWS-1255: 
Connection encoding WINDOWS-1255
[('???-????',), ('???-????',), ('???-????',), ('???-????',)]
???-???? b'???-????'
???-???? b'???-????'
???-???? b'???-????'
???-???? b'???-????'

I tried to use ISO-8859-8 which suppose to be Hebrew. In this case I received 
Connection encoding ISO-8859-8-I   --> do not know why oracle changed this encoding
And an Error massage : 

Traceback (most recent call last):
  File "C:/test.py", line 14, in <module>
    curr.execute(sql)
LookupError: unknown encoding: ISO-8859-8-I

**Comment by biskilled** [comment]
Another point : 
while using windows CMD - Hebrew characters can look at the wrong format as well 
To use CMD correctly I did need to add into reg-edit under HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Console\TrueTypeFont a new string value with the value Courier New - this enabled the option to see Hebrew characters properly

Also I did add NLS_LANG property into oracle client reg-edit properties in order to work properly with python 2.X

**Comment by biskilled** [comment]
Result:
NLS_CHARACTERSET -> WE8DEC
NLS_NCHAR_CHARACTERSET -> AL16UTF16
NLS_RDBMS_VERSION -> 11.2.0.3.0

**Comment by cjbj** [comment]
Also, what cx_Oracle version are you using with Python 2?

**Comment by biskilled** [comment]
Sorry for my late response, At my local time it was 01:30 at the morning ...

cx_oracle version on python 2.X --> 6.0(6.0rc1) 
cx_oracle version on python 3.X --> 7.0.0 . I did try to use 6.0, 6.1 and 7.1 as well (same results )  

Oracle client version - 12.1.0.2, 64Bit 
Python 2.X / Python 3.X - 64 bit as well 


While executing the query in Sql* plus I receive invalid characters as well 
Sample result (from Sql*Plus CLI) :

SQL> SELECT XXXX FROM SAPR3.NBEW where ROWNUM<5;

XXXX 
--------
°εδ-αΘµσ
°εδ-αΘµσ
°εδ-Γ±Φ°
°εδ-Γ±Φ°

This is not a valid character set.

Also, while I tried to change font setting at the CLI properties - to "Courier New" - it did not help and characters result did not change (not like regular CMD) 
while using a regular CMD - this font work properly (I had to add string value into reg-edit for that.. )      

Also, I changed NLS_LANG string value under HKEY_LOCAL_MACHINE\SOFTWARE\ORACLE\KEY_OraClient12Home1 to HEBREW_ISRAEL.WE8DEC

**Comment by anthony-tuininga** [comment]
Thanks, @biskilled. Based on that information I believe what is happening is that the database thinks that the data is stored in WE8DEC, but in fact you are actually storing data encoded in WINDOWS-1255. Because they are both single byte character sets, Oracle doesn't actually check to see if this is "what you really meant to store" -- which also explains why you're getting what you're getting with SQL*Plus.

Python 3 requires strings to be valid Unicode and will decode the bytes that are being passed back from the database. The Oracle character set WE8DEC (aka DEC-MCS) has been long superseded and is not known to Python (either 2.7 or 3.x). But telling the database that you want encoding WINDOWS-1255 instead will simply have Oracle perform a conversion for you from what it thinks is DEC-MCS (WE8DEC) and that will munge the data, which you've noted.

Thankfully, there should be a way to correct this. You can verify that by doing the following in SQL*Plus.

```sql
create table SAPR3.TEST_DATA (X varchar2(100));
```

Then, in Python 2.7 do something like the following (untested since I don't have your data):

```python
# first connect to the database using NLS_LANG to get the munged data
conn = cx_Oracle.connect(user, pw, dsn)
cursor = conn.cursor()
cursor.execute("select XXXX from SAPR3.NBEW")
mungedData = [x for x, in cursor]
goodData = [x.decode("WINDOWS-1255") for x in mungedData]

# print out the data to verify that it is good
print(goodData)

# now connect to the database using the UTF-8 encoding and store the good data
conn = cx_Oracle.connect(user, pwd, dsn, encoding="UTF-8", nencoding="UTF-8")
cursor = conn.cursor()
dataToInsert = [(x,) for x in goodData]
cursor.executemany("insert into SAPR3.TEST_DATA values (:1)", dataToInsert)
conn.commit()
```

Then, in SQL*Plus you should see the right data and if you run this in Python 3 you should see the correct data as well:

```python
conn = cx_Oracle.connect(user, pw, dsn, encoding="UTF-8", nencoding="UTF-8")
cursor = conn.cursor()
cursor.execute("select * from SAPR3.TEST_DATA")
for row in cursor:
    print(row)
```

Assuming this is an accurate analysis of your issue you'll need to perform a data conversion using something like the technique I showed above.

**Comment by biskilled** [comment]
Hi,

While using Python 2.X i did use decoding into WINDOWS-1255 and indeed it work properly. 
The customer I am working for, is a using SPAR3 in many places, each instance store few TB of data and the system is a legacy system (more than 20 years old) 
so the option to migrate the data is not possible.

I wanted to upgrade from python 2.X into python 3.X in order to support new functionalities at the overall integration processes.
for the specific case of using cx_oracle with WE8DEC char-set - i will stick to python 2.X engine. 

I would like to thank you all for your quick and professional help.
Thank you very much !

**Comment by anthony-tuininga** [comment]
Happy to hear that we were able to get to the bottom of your issue. I understand how you wouldn't want to perform a cobbled together data conversion as I suggested for such a large amount of data. Thankfully, there is another solution which Oracle provides, namely [Oracle Database Migration Assistant](https://www.oracle.com/database/technologies/appdev/oracle-database-migration-assistant.html). This free tool will allow you to migrate the entire database to a character set like AL32UTF8 (UTF-8) which will eliminate the character set confusion you have -- not just for Python 3 but for SQL*Plus as well. And I am informed that you can specify the true encoding of the data (windows-1255) and it will successfully transform the data for you. Something to consider anyway -- and if you don't want to do it yourself, someone else who reads this thread later on may wish to do so.
