### ISSUE TITLE
OCI8 SessionPool behavior across multiple processes

### ISSUE THREAD

**Issue by danizen** [oracle/python-cx_Oracle#264]
### General Question

I've used cx-Oracle for session pooling, and in fact got some changes added to https://github.com/JohnPapps/django-oracle-drcp to set initial threading parameters.

I am not deeply familiar with OCI8, but I remember enough C to be cautious.   If a SessionPool is initialized in a parent process, and then there is a fork, how will the Session Pool operate?

Is the state kept in mapped memory or shared memory?   Are semaphores used instead of pthread equivalent mutexes so that a lock by one process will not lock out the others?   e.g. if a process dies with the lock held, it will be released despite the potential damage to the shared/mapped memory?
Are there any memory barriers in place?

I recall this being a very tricky area of C-programming, and so have so far avoided using SessionPools across processes. This is easy to do with Phusion Passenger running our python applications, but if we switch to gunicorn, it may well initialize the database connection before forking.

**Comment by danizen** [comment]
I should add - my hope is that this would work *without* setting up DRCP.  We did this once to evaluate DRCP session pools, and then stopped as we saw no practical difference on the client side.

**Comment by cjbj** [comment]
I checked with the OCI session pool team: each thread has to do everything for that thread.  

The OCI session pool is independent of DRCP.  You can use one or both, but it is generally the case you want to use the session pool if using DRCP.

**Comment by cjbj** [comment]
Note I fixed a typo above.  Thanks @krismohan

**Comment by danizen** [comment]
@cjbj thanks for the response, I'll keep it in mind.
