### ISSUE TITLE
Distribution packaging not possible due to non-free dependencies

### ISSUE THREAD

**Issue by glaubitz** [oracle/python-cx_Oracle#266]
I am currently working on packaging the Python OCI SDK and OCI command line utilities for openSUSE/SLE.

Since command line utilities (https://github.com/oracle/oci-cli) depend on the ```python-cx_Oracle``` module, I started packaging this module as well. Unfortunately, the module requires a proprietary shared library called ```libclntsh.so``` which we cannot include in openSUSE/SLE during build:

```
[   45s] File: /home/abuild/rpmbuild/BUILD/cx_Oracle-7.0.0/build/lib.linux-x86_64-2.7/cx_Oracle.so
[   45s] Traceback (most recent call last):
[   45s]   File "setup.py", line 126, in <module>
[   45s]     classifiers = classifiers)
[   45s]   File "/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
[   45s]     return distutils.core.setup(**attrs)
[   45s]   File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
[   45s]     dist.run_commands()
[   45s]   File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
[   45s]     self.run_command(cmd)
[   45s]   File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
[   45s]     cmd_obj.run()
[   45s]   File "setup.py", line 53, in run
[   45s]     exec(open(fileName).read())
[   45s]   File "<string>", line 26, in <module>
[   45s] cx_Oracle.DatabaseError: DPI-1047: 64-bit Oracle Client library cannot be loaded: "libclntsh.so: cannot open shared object file: No such file or directory". See https://oracle.github.io/odpi/doc/installation.html#linux for help
[   45s] error: Bad exit status from /var/tmp/rpm-tmp.NrugEJ (%check)
[   45s] 
[   45s] 
[   45s] RPM build errors:
[   45s]     Bad exit status from /var/tmp/rpm-tmp.NrugEJ (%check)
[   45s] 
[   45s] suse-laptop failed "build python-cx_Oracle.spec" at Tue Feb 12 12:37:31 UTC 2019.
[   45s]
```

I understand that the Oracle DB client libraries are currently closed source and that it's unlikely for these to be open-sourced, so I'm not sure how one could proceed to resolve this problem.

But it would be desirable to be able to package ```oci-cli``` for openSUSE/SLE so these utilities will be available for OCI customers in the future when running openSUSE/SLE images in OCI.

**Comment by cjbj** [comment]
This specific request was discussed via email recently; refer to that thread. 
I'll close this since there is no further action to be taken.  It is a constraint we live with.
