### ISSUE TITLE
cx_Oracle for 10g and python 3.4 - win32

### ISSUE THREAD

**Issue by doudz** [oracle/python-cx_Oracle#268]
First, thanks for your work !

I have to migrate an old python code that use Python 2.7 running on Windows 2003 32bit and Oracle 10g to Python 3.x
Since I'm on Win2003 the only choice is Python 3.4 but I don't find any combo of cx_oracle 10g py34 win32
For some reason, I can't upgrade Oracle and I can't upgrade Windows too

So, is there someone who can build the windows binaries I need ?

**Comment by anthony-tuininga** [comment]
You can install an older version of cx_Oracle to go with your older version of the OS and Python. :-)

https://pypi.org/project/cx-Oracle/5.3/#files

Would that work for you?

**Comment by doudz** [comment]
oh ... I already ask for the same in 2017.... https://github.com/oracle/python-cx_Oracle/issues/76

@anthony-tuininga thanks but there's no 10g in the list.

Probably I  have to build it myself

**Comment by anthony-tuininga** [comment]
No, there is no 10g. That hasn't been supported for a long time already. :-) But you should be able to use a newer client without any problems. Or is the client locked down as well? If so, yeah, you'll have to build it yourself!

**Comment by doudz** [comment]
I'm afraid I can't upgrade the client because the database is on the same machine and I don't think it's a good idea to mix Oracle version

**Comment by anthony-tuininga** [comment]
The instant client can be used without too much trouble, generally. It is a simple unzip. You can also make sure that you only set the PATH to the location you unzipped in the script itself (not globally) in order to avoid any potential difficulties. But if that seems fraught with peril and you can build yourself, by all means go ahead and do so! Getting a plan together to upgrade would be a good idea, though. You're going to find it increasingly difficult to get such old software to work. :-)

**Comment by doudz** [comment]
yes I know...
I'll try to build it and if it fails I'll try to use a recent client :crossed_fingers: 

Thank you

**Comment by anthony-tuininga** [comment]
You're welcome. Good luck!

**Comment by doudz** [comment]
[cx_Oracle-5.2.1.win32.zip](https://github.com/oracle/python-cx_Oracle/files/2868563/cx_Oracle-5.2.1.win32.zip)
I manage to build it, I post it here just in case of ;)

**Comment by MHShetty** [comment]
> [cx_Oracle-5.2.1-10g.win32-py3.4.zip](https://github.com/oracle/python-cx_Oracle/files/2868572/cx_Oracle-5.2.1-10g.win32-py3.4.zip)
> 
> I manage to build it, I post it here just in case of ;)
> I don't be able to build a msi because bdist_msi doesn't embed cx_Oracle.pyd, I don't know why

How can one use it?
Sorry if it sounds silly, I am new to Python.

**Comment by cjbj** [comment]
@MHShetty This is a long-closed issue.  If you're new to Python and Oracle, read the [cx_Oracle documentation](http://cx-oracle.readthedocs.org/en/latest/index.html) and try the [cx_Oracle tutorial](https://oracle.github.io/python-cx_Oracle/samples/tutorial/Python-and-Oracle-Database-Scripting-for-the-Future.html).
