### ISSUE TITLE
Encoded GUID from Oracle Query

### ISSUE THREAD

**Issue by muddywaterous** [oracle/python-cx_Oracle#269]
Trying the following: 

import cx_Oracle
con = cx_Oracle.connect(my_connection_string, encoding='UTF-8', nencoding='UTF-8')
c = con.cursor()
stmt = "select OBJECT_ID FROM DATABASE.TABLE where OBJECT_ID = 'B5E86E65C2B92A48A55702ED0B779DE6'"
c.execute(stmt)
res = c.fetchone()
c.close()
con.close()
print(res)

I get this result:

c:\python>test
(b'\xb5\xe8ne\xc2\xb9*H\xa5W\x02\xed\x0bw\x9d\xe6',)
So, I think Python is encoding this into a byte code for some reason? Not sure why. I really just want the original Object_ID value. There are a couple of other GUID values in this DB and they're coming out the same way. 

Using a tool like TOAD and the same query, it comes back as the original GUID, I've tried a bunch of options, with and without the encoding and nencoding parameters. 

Running Python 3.6.1
Oracle is 11.2
Rhel on server
Windows 10 OS on client

I am guessing there is a simple answer, but it's eluding me entirely. Any help is greatly appreciated!

**Comment by anthony-tuininga** [comment]
If the database is using RAW to store the UUID then you will get back bytes. Python has a module that lets you transform those bytes into the string I think you are expecting. Like this:

```python
import uuid
u = uuid.UUID(bytes=b'\xb5\xe8ne\xc2\xb9*H\xa5W\x02\xed\x0bw\x9d\xe6')
print(u)
```

That yields the value "UUID('b5e86e65-c2b9-2a48-a557-02ed0b779de6')" which I think is what you are expecting?

You can use an outputtypehandler to have this done for you transparently.

**Comment by muddywaterous** [comment]
Hi Anthony,
Thanks for much for your help! The uuid function did the trick for me! One other thing that I wasn't aware of is that the data is coming back in a Python tuple from Oracle. I used this function from GeeksforGeeks to convert the tuple to a string.  
https://www.geeksforgeeks.org/python-program-to-convert-a-tuple-to-a-string/
That seems to have given me a way to convert the data into a more human friendly form.

This is the function. 
def convertTuple(tup):
	str = functools.reduce(operator.add, (tup))
	return str

Thanks!

**Comment by muddywaterous** [comment]
One more note this is all that is needed to convert the tuple returned from Oracle by Python to a GUID/UUID:
str(uuid.UUID(bytes=column_1))
b5e86e65-c2b9-2a48-a557-02ed0b779de6 is the output, which is as expected for my application. The convertTuple function is not necessary.

**Comment by cjbj** [comment]
@muddywaterous to make it really clear for future readers can you state the Oracle datatype of the OBJECT_ID column in your DATABASE.TABLE so no one has to guess?

**Comment by muddywaterous** [comment]
Also note that in my case the DB column in Oracle is defined as a RAW(16) data type.
