### ISSUE TITLE
cx_Oracle datetime doesn't accept virtualtime patching

### ISSUE THREAD

**Issue by ancc** [oracle/python-cx_Oracle#276]
Unable to use virtualtime module with cx_Oracle datetime. 

#### Answer the following questions:

1. What is your version of Python? Is it 32-bit or 64-bit?
64-bit

2. What is your cx_Oracle version?
7.1.1
3. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?

4. What error(s) you are seeing?

ValueError: year=1870 is before 1900; the datetime strftime() methods require year >= 1900

5. What OS (and version) is Python executing on?
Centos 6.7, python 2.7.13
6. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where is it installed?
instant client 12.2.0.1, 

7. What is your Oracle Database version?
12.2.0.1.0

8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?

9. What Oracle environment variables did you set?  How *exactly* did you set them?
export ORACLE_HOME=/opt/oracle/instantclient
export TNS_ADMIN=/opt/oracle/instantclient/network/admin
export NLS_LANG=AMERICAN_AMERICA.AL32UTF8

10. Do you have a small, single Python script that immediately runs to show us the problem?

```
import virtualtime
virtualtime.enable()
import cx_Oracle
con = cx_Oracle.Connection('user/pass@db)
cur = con.cursor()
cur.execute("select to_date('01.01.1870','DD.MM.YYYY') from dual")
date = cur.fetchone()[0]
date.strftime('%d.%m.%Y')
```

output

```
Traceback (most recent call last):
  File "virt.py", line 8, in <module>
    date.strftime('%d.%m.%Y')
ValueError: year=1870 is before 1900; the datetime strftime() methods require year >= 1900

```

Converting dates to characters already on sql side is not an option. Python 3 is also not an option.

How it works usually with other libraries which are using datetime
```
>>> import virtualtime
>>> virtualtime.enable()
>>> import datetime
>>> datetime.datetime(1876, 1, 1).strftime('%Y-%m-%d')
'1876-01-01'
```

**Comment by ancc** [comment]
I'll use outputtypehandler for workaround.

**Comment by anthony-tuininga** [comment]
cx_Oracle uses the C API for datetime, which is probably why virtualtime cannot intercept it. So the outputtypehandler may be your only option -- at least for now!

**Comment by anthony-tuininga** [comment]
Since this is not an issue for Python 3 and Python 2 support is ending January 1, 2020, the output type handler is the solution that is needed and nothing needs to be done to cx_Oracle.
