### ISSUE TITLE
set timeout condition on cursor.execute()

### ISSUE THREAD

**Issue by vamkaxifa** [oracle/python-cx_Oracle#277]
### For general questions:
Hi there, I have a project  which used to access oracle database using cx_Oracle. There are two kinds of operation one is for `QUERY` and the other one is for `IUD`(`INSERT`、`UPDATE`、`DELETE`).
Now I want to set a timeout condition on each accessing DB statment. In particularly, `IUD` will  trigger rollback  event automatically when it timeouts. Is there any way to achieve this? 

#### Answer the following questions:

1. What is your version of Python? Is it 32-bit or 64-bit?
   python 3.7.2    64-bit

2. What is your cx_Oracle version?
  cx-Oracle==7.0.0

3. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?

4. What error(s) you are seeing?

5. What OS (and version) is Python executing on?
   MacOS 10.13.1

6. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where is it installed?
   Oracle client instantclient_11_2 
   down load basic and sdk packages from [oracle](https://www.oracle.com/technetwork/cn/topics/intel-macsoft-102027-zhs.html) and configure ORACLE_HOME  on my MAC.

7. What is your Oracle Database version?
 11.2.0.3
   
8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?
/Users/vivian/Documents/soft/oracle/instantclient_11_2

9. What Oracle environment variables did you set?  How *exactly* did you set them?

10. Do you have a small, single Python script that immediately runs to show us the problem?

**Comment by anthony-tuininga** [comment]
If you upgrade your client to 18.3 then you could make use of the [call timeout](https://cx-oracle.readthedocs.io/en/latest/connection.html#Connection.callTimeout) feature available in that version. That allows you to specify the number of milliseconds you want to wait for each round-trip to the database.

If you can't upgrade, then your options are considerably more limited and involve changing the network parameters of sqlnet.ora -- which affects all activity on all connections.

**Comment by vamkaxifa** [comment]
@anthony-tuininga  `client to 18.3`, you mean   instantclient ? As far as I know,  the highest version is 12.2.0.1.0 for now from [oracle](https://www.oracle.com/technetwork/cn/topics/intel-macsoft-102027-zhs.html) . Is it convenient to give me a link?  ：）

**Comment by anthony-tuininga** [comment]
Sure. Here is the link that shows you 18.1 for macOS 18.1 instant client, which has this feature available: https://www.oracle.com/technetwork/topics/intel-macsoft-096467.html.

**Comment by anthony-tuininga** [comment]
I believe your question has been answered. If not, let us know!

**Comment by vamkaxifa** [comment]
Thanks a lot! For now, I solved the problem partially, for more information, you can refer to [issue 4 from DBUtils](https://github.com/Cito/DBUtils/issues/16).

**Comment by vamkaxifa** [comment]
@anthony-tuininga Hi, I'm here again.  I'm sorry that [call timeout](
https://cx-oracle.readthedocs.io/en/latest/connection.html#Connection.callTimeout) feature does't work.  As you know from [issue 4 from DBUtils](https://github.com/Cito/DBUtils/issues/16), I run it on instant client 12.2 on Mac, it throws exception `cx_Oracle.DatabaseError: DPI-1050: Oracle Client library is at version 12.2 but version 18.1 or higher is needed`, then I update my client to 18.1, the DPI-1050 exception disappeared. But the call time out exception did not appear either. For reference, the request timestamp is 2019-03-14 14:48:53.844018, response timestamp is 2019-03-14 14:48:53.844799 (time formate is %Y-%m-%d %H:%M:%S.%f), comparing with time_out,it is short enough to trigger call time out exception.

I also run it on docker with centOS 7、instant client 18.1 、python3.7.2 64bit under same `time_out= 0.000000000000000000000000000000000000000001 `, call time out exception remains disappear.

**Comment by anthony-tuininga** [comment]
Can you share the code that you used to perform your tests and the versions of all of the components you used? Thanks.

**Comment by vamkaxifa** [comment]
Sure, I write two pieces of code, one uses DBUtils proxying cx_Oracle to access oracle db, the other one  uses cx_Oracle to access oracle db directly. Both of them can't trigger call time out exception. 
First one:
```
# coding:utf-8
import cx_Oracle
import datetime
import traceback
from DBUtils.PooledDB import PooledDB


def test_call_time_out_feature():
    poll = PooledDB(cx_Oracle,
                    threaded=True,
                    user="user",
                    password="password",
                    dsn="xx.xx.xx.xx/xx",
                    mincached=1,
                    maxcached=1,
                    maxshared=2,
                    maxconnections=50)
    conn = poll.connection()
    time_out = 0.0000000000000000000000000000000000000001
    conn._con._con.callTimeout = time_out
    cursor = conn.cursor()
    sql = "insert into jys_syn_bill(ID,order_id) values(:ID,:order_id)"
    values = ["9300ecd2d9ae46d3819b0134e72b6325", "600000000000008316122600223247"]
    req_time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S.%f")

    try:
        cursor.execute(sql, values)
        res_time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S.%f")
        count = cursor._cursor.rowcount
        conn.commit()
        print("req_time = %s, res_time = %s, count = %s" % (req_time, res_time, count))
    except Exception as e:  # excepting callTimeOut exception
        conn.rollback()
        res_time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S.%f")
        print("req_time = %s, res_time = %s, e = %s, stack = %s" % (req_time, res_time, str(e), traceback.format_exc()))
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()


if __name__ == "__main__":
    test_call_time_out_feature()

```

Second one:
```
# coding:utf-8
import cx_Oracle
import datetime
import traceback


def test_call_time_out_feature():
    conn = cx_Oracle.connect("user/password@xx.xx.xx.xx/xx")
    time_out = 0.0000000000000000000000000000000000000001
    conn.callTimeout = time_out
    cursor = conn.cursor()
    sql = "insert into jys_syn_bill(ID,order_id) values(:ID,:order_id)"
    values = ["9300ecd2d9ae46d38194134e72b6325", "600000000000008316122600223247"]
    req_time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S.%f")
    try:
        cursor.execute(sql, values)
        res_time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S.%f")
        count = cursor.rowcount
        conn.commit()
        print("req_time = %s, res_time = %s, count = %s" % (req_time, res_time, count))
    except Exception as e:  # excepting callTimeOut exception
        conn.rollback()
        res_time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S.%f")
        print("req_time = %s, res_time = %s, e = %s, stack = %s" % (req_time, res_time, str(e), traceback.format_exc()))
    finally:
        if cursor:
            cursor.close()
        if conn:
            conn.close()


if __name__ == "__main__":
    test_call_time_out_feature()

```
DBUtils==1.3
cx_Oracle==7.1.1 
instantclient==18.1
OS==macOS High Sierra 10.13.1
python==3.7.2 64bit

**Comment by cjbj** [comment]
@vamkaxifa 

- Try a sensible timeout instead of '0.0000000000000000000000000000000000000001'.  The `callTimeout` unit is milliseconds.  This feature isn't for realtime (or out-of-this-world) programming.

- Test with 18.3 client on Linux.

I tried this on Linux with 18.3 Instant Client:
```
import cx_Oracle
import datetime

def test_call_time_out_feature():
    conn = cx_Oracle.connect("cj/cj@localhost/orclpdb")
    time_out = 1000  # milliseconds
    conn.callTimeout = time_out
    cursor = conn.cursor()
    sql = "begin dbms_session.sleep(5); end;"  # seconds
    req_time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S.%f")
    try:
        cursor.execute(sql)
        res_time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S.%f")
        print("req_time = %s, res_time = %s" % (req_time, res_time))
    except Exception as e:  # excepting callTimeOut exception
        res_time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S.%f")
        print("req_time = %s, res_time = %s, e = %s" % (req_time, res_time, str(e)))

if __name__ == "__main__":
    test_call_time_out_feature()
```
The output was:
```
$ python issue277.py 
req_time = 2019-03-15 16:43:11.961560, res_time = 2019-03-15 16:43:14.447189, e = DPI-1067: call timeout of 1000 ms exceeded with ORA-3136
```

**Comment by anthony-tuininga** [comment]
As noted by Chris, the callTimeout value is in milliseconds so the value you specified would become 0, which is the same as not being enabled. Generally you should pick a value that is at least long enough for a complete network round trip to your database as well as the length of time that the database requires to process the request. Fractional portions of the value are simply discarded. I've added a [sample](https://github.com/oracle/python-cx_Oracle/blob/master/samples/CallTimeout.py) to the samples directory which you can run if you have the sample schema built.

**Comment by vamkaxifa** [comment]
@anthony-tuininga @cjbj Thank you very much! I got this callTimeout feature works. Really because of the problem of decimals. Thank you guys again !

**Comment by cjbj** [comment]
Good to hear.

**Comment by skysaeed** [comment]
> * Test with 18.3 client on Linux.
> 
> I tried this on Linux with 18.3 Instant Client:
> 
> ```
> import cx_Oracle
> import datetime
> 
> def test_call_time_out_feature():
>     conn = cx_Oracle.connect("cj/cj@localhost/orclpdb")
>     time_out = 1000  # milliseconds
>     conn.callTimeout = time_out
>     cursor = conn.cursor()
>     sql = "begin dbms_session.sleep(5); end;"  # seconds
>     req_time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S.%f")
>     try:
>         cursor.execute(sql)
>         res_time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S.%f")
>         print("req_time = %s, res_time = %s" % (req_time, res_time))
>     except Exception as e:  # excepting callTimeOut exception
>         res_time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S.%f")
>         print("req_time = %s, res_time = %s, e = %s" % (req_time, res_time, str(e)))
> 
> if __name__ == "__main__":
>     test_call_time_out_feature()
> ```
> 
> The output was:
> 
> ```
> $ python issue277.py 
> req_time = 2019-03-15 16:43:11.961560, res_time = 2019-03-15 16:43:14.447189, e = DPI-1067: call timeout of 1000 ms exceeded with ORA-3136
> ```

@cjbj 
Hi, maybe as you noticed from output logs the timeout is around 2 sec and you have set callTimeout to be 1 sec. i was trying to timeout after 5 mins but it timed out after 10 mins
