### ISSUE TITLE
Function Returning Package Ref Cursor

### ISSUE THREAD

**Issue by Aetylus** [oracle/python-cx_Oracle#282]
Given the following database objects

```sql
drop table example_table;

create table example_table (
   id number,
   value varchar2(128)
);

insert into example_table values (1, 'Foo');
insert into example_table values (1, 'Bar');
insert into example_table values (2, 'Hello');
insert into example_table values (2, 'World');

create or replace package example_package as
   type example_type is record (
      id number,
      value varchar2(128)
   );

   type example_cursor is ref cursor return example_type;

   function f_get_cursor(i_id number) return example_cursor;

   function f_get_locked_cursor(i_id number) return example_cursor;
end;

create or replace package body example_package as
   function f_get_cursor(i_id number)
   return example_cursor
   is
      l_examples example_cursor;
   begin
      open l_examples for
      select id, value
      from example_table
      where id = i_id;
      return l_examples;
   end;

   function f_get_locked_cursor(i_id number)
   return example_cursor
   is
      l_examples example_cursor;
   begin
      open l_examples for
      select id, value
      from example_table
      where id = i_id
      for update;
      return l_examples;
   end;
end;
```

Is it possible to retrieve the return result of the `f_get_cursor` and `f_get_locked_cursor` using `cursor.callfunc`?

I've tried a few attempts things without any success.

## Cursor as Return Type

```py
cursor.callfunc('example_package.f_get_cursor', cx_Oracle.Cursor, [1])
```

raises an exception

```
cx_Oracle.NotSupportedError: Python type cx_Oracle.Cursor not supported.
```

## Retrieving Package Cursor Type

Based on some samples available, I've tried retrieving the cursor type from the package (`EXAMPLE_PACAGE.EXAMPLE_CURSOR`). However, it seems unable to retrieve the type:

```py
typeObj = connection.gettype('EXAMPLE_PACKAGE.EXAMPLE_CURSOR')
cursor.callfunc('example_package.f_get_cursor', typeObj, [1])
```

```py
cursor.callfunc('example_package.f_get_cursor', cursor.var(cx_Oracle.Object, typename='EXAMPLE_PACKAGE.EXAMPLE_CURSOR'), [1])
```

both return

```
cx_Oracle.DatabaseError: OCI-22303: type ""."EXAMPLE_PACKAGE.EXAMPLE_CURSOR" not found
```

## Implicit Result

Based on the [implicit result](https://github.com/oracle/python-cx_Oracle/blob/master/samples/ImplicitResults.py) sample, returning back an unlocked cursor does seem to work:

```py
cursor.execute('''\
    declare
        l_examples sys_refcursor;
    begin
        l_examples := example_package.f_get_cursor('1');
        dbms_sql.return_result(l_examples);
    end;
    ''')
for ix, resultSet in enumerate(cursor.getimplicitresults()):
    print(f'Result Set #{str(ix + 1)}')
    for row in resultSet:
        print(row)
```

Is this the only method of retrieving the cursor from the function?

Additionally, cursors opened with `FOR UPDATE` won't work on this method either. Trying to use `example_package.f_get_locked_cursor('1')` instead returns the following exception:

```
cx_Oracle.DatabaseError: ORA-01001: invalid cursor
```

#### Answer the following questions:

1. What is your version of Python? Is it 32-bit or 64-bit?
Python 3.7.2 64-bit

2. What is your cx_Oracle version?
cx-Oracle 7.1.0

3. What is your Oracle Database version?
12c 12.1.0.2.0

**Comment by anthony-tuininga** [comment]
If you want to return a REF cursor from a function you'll need to do something like this:

```python
refCursor = cursor.callfunc('example_package.f_get_cursor', cx_Oracle.CURSOR, [1])
for row in refCursor:
    print(row)
```

**Comment by Aetylus** [comment]
Thanks! Didn't realize there was a `cx_Oracle.CURSOR` type specifically, instead of the `cx_Oracle.Cursor` class!
