### ISSUE TITLE
cx_Oracle.DatabaseError: ORA-28040: No matching authentication protocol

### ISSUE THREAD

**Issue by pavelkup79** [oracle/python-cx_Oracle#283]
### For general questions:
Hi i'm trying to connect Oracle DB using  cx_Oracle , and getting following error 
cx_Oracle.DatabaseError: ORA-28040: No matching authentication protocol

Note: The same code is working for me on another oracle server 

#### Answer the following questions:

1. What is your version of Python? Is it 32-bit or 64-bit?
2.7.14  ( bot sure i think 64-bit)

2. What is your cx_Oracle version?
   7.0.0
3. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?
import cx_Oracle
 def __init__(self,dbHost,dbUser,dbPass,dbInstance,dbPort):
    self.db=None
    self.dsn = cx_Oracle.makedsn(dbHost, dbPort, dbInstance)
    self.db = cx_Oracle.connect(dbUser, dbPass, self.dsn)

4. What error(s) you are seeing?
 File "C:\Users\pavelkup\Documents\workspace\Python-tool-box\AutoToolBox\Class\OraDBConnect.py", line 11, in __init__
    self.db = cx_Oracle.connect(dbUser, dbPass, self.dsn)
cx_Oracle.DatabaseError: ORA-28040: No matching authentication protocol

5. What OS (and version) is Python executing on?
 Windows XP  ( 64-bit)

6. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where is it installed?
i  have client locally on my PC : 11.2.0 
7. What is your Oracle Database version?
 Not sure i thing Oracle 12 

8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?

9. What Oracle environment variables did you set?  How *exactly* did you set them?

10. Do you have a small, single Python script that immediately runs to show us the problem?

**Comment by pavelkup79** [comment]
Please advise

**Comment by cjbj** [comment]
That kind of error is generally from the network configuration, which is not really related to cx_Oracle. 

- search around on other Oracle forums.
- post more details about your network configuration, authentication setup, and Oracle Net configuration files.

**Comment by anthony-tuininga** [comment]
Closing - lack of activity
