### ISSUE TITLE
Parameterized query not working for NCHAR datatype column if parameter value length is less than column size

### ISSUE THREAD

**Issue by sidnaik03** [oracle/python-cx_Oracle#284]
Hi ,
I am using cx_oracle and sql alchemy to perform db operations. In my database table , I have one column which datatype is NCHAR and its size is 2 (eg consider column name as ABC). **When I am executing parameterised query with filter on ABC its gives incorrect result if I passed single character as a parameter value.**
Query returns proper result if I passed 2 character value as a params.
In my database table, ABC column has single as well as 2 characters value.
Plz help.

**Comment by cjbj** [comment]
Post the SQL and Python code to reproduce the problem.

**Comment by anthony-tuininga** [comment]
If you do not use ``cursor.setinputsizes()`` or create variable using ``cursor.var()`` using the type cx_Oracle.NCHAR, Oracle will bind the data as VARCHAR2 -- which is likely the source of your issue. As Chris mentioned, the SQL and Python code would be helpful to be certain.

**Comment by anthony-tuininga** [comment]
I assume by the lack of activity that your question has been answered. If not, feel free to re-open!
