### ISSUE TITLE
Connect.py not working - 

### ISSUE THREAD

**Issue by ravi2948** [oracle/python-cx_Oracle#286]
I wrote a connect.py script to execute in Python version 2.7 in our server. it's throwing an error below 
NameError: name 'connect' is not defined

Script (Connect.py)
```python
import cx_Oracle
import print_function
import sys
import db_config
conn_str='user/password@XXXd'
try:
    conn = cx_Oracle.connect(conn_str)
        c=conn.cursor()
        c.execute('select * from table where rownum < 10')
        for row in c:
    print(row)
conn.close()
except Exception as e:
    print(e)
```

output
```
>>> connect.py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'connect' is not defined
```

Environment: Exadata Oracle DB 12c. 
![Capture](https://user-images.githubusercontent.com/39999868/54848641-35b10d80-4cb8-11e9-9135-070959d67d36.PNG)

Client : Oracle 12.2 (64-bit)
Linux version: RHEL 7.1

**Comment by anthony-tuininga** [comment]
Hi, if you want to run the Python script you should use the following:

```
python connect.py
```

If you want to run the file interactively you need to do this instead:

```
execfile("connect.py")
```

**Comment by anthony-tuininga** [comment]
I assume based on the lack of a response that your question has been answered. If not, please re-open!
