### ISSUE TITLE
Connecting using effective UID

### ISSUE THREAD

**Issue by ReubenM** [oracle/python-cx_Oracle#289]
cx_Oracle-7.1.2 
python-2.7
OracleLinux 7.5

I'm trying to setup a local connection as sysdba:

```
conn = cx_Oracle.Connection( '/', mode   = cx_Oracle.SYSDBA )
```

The problem is not really with cx_Oracle itself, with the environment set correctly, the connection works fine. However the issue is I'm trying to do some sysdba tasks from a python script run from an orchestration system running as root. Access as sysdba requires user 'oracle'.

I can use os.setuid and everything works fine, except I can't reacquire root UID after closing the connection. Natural solution is to set effective UID using os.seteuid. But then the connection is refused with bad username/password.

Is there a reasonable way around this?

**Comment by anthony-tuininga** [comment]
I think the usual method for doing that sort of thing is (as root) to do the following:

```
su - <otheruser> -c 'somescript.sh'
```

That way its not running with root privileges, but with a DBA user's privileges. But perhaps there is a reason you're avoiding that solution? I'm not sure if there is any other reasonable way around the problem, though!

**Comment by ReubenM** [comment]
Ok, I've managed to work around it by using the multiprocessing module to fork the process and pass the forked process a queue object. The forked child process changes real uid/gid, accesses the local sysdba connection without any issue and dumps the query results into the queue object, and then exits. The parent process then gets it's data from the queue object, retaining root uid/gid. 

I wanted to avoid calling the function via "su" in a shell since passing data around using a shell as an intermediary between 2 python processes is less that desirable.

**Comment by anthony-tuininga** [comment]
Understood! Thanks for providing the solution you came up with. :-)

**Comment by cjbj** [comment]
I hesitate to mention it due to security issues with password management, but you should be able to use the SYS password when connecting, just like you would with SQL*Plus: `sqlplus -l "sys/syspassword@example.com/orclpdb as sysdba"` (Of course, you would never run SQL*Plus like this unless you wanted everyone to know your SYS password....)   I haven't tried setting up wallets for SYS.

**Comment by anthony-tuininga** [comment]
Ah yes, wallets are another solution. You can see the documentation for that [here](https://www.oracle.com/pls/topic/lookup?ctx=dblatest&id=GUID-E3E16C82-E174-4814-98D5-EADF1BCB3C37).

**Comment by ReubenM** [comment]
Yes, I've used the sys user and password in the past, but I wanted to be able to use a local connection where credentials are not required as long as the uid is correct. The reason is that if I store credentials in the orchestrations system, then I have to set up all the security components to make sure the credentials are encrypted and not easily accessible, and that is a real headache. I do already use the wallet for non-sysdba connections, and that is quite handy.
