### ISSUE TITLE
How to issue  `set role my_role` on connection?

### ISSUE THREAD

**Issue by caddac** [oracle/python-cx_Oracle#291]
We have a single oracle DB with multiple schemas configured in a multi tenant setup. That is, each schema is identical, but for an individual client. There are no cross schema FKs or anything like that. 

Our connection model is to connect with a global oracle user (iow same user regardless of tenant) that has no permissions to any schemas, however they do have permissions to assume roles (using the statement `set role some_tenant_role`). The role that is assumed then has permissions to the schema associated with it. 

I am able to execute the `set role tenant_role` statement when using a cursor, like:

    with closing(self.get_conn()) as conn:  # conn is a cx_oracle connection
        conn.current_schema = schema #the tenant schema associated with tenant_role below
        with closing(conn.cursor()) as cur:
            cur.execute(f'set role tenant_role')
            cur.execute(sql, params)
            # etc etc

However I'd like to be able to set this role at the connection or even engine (SqlAlchemy I know) level. We are using `Pandas.DataFrame.to_sql()` to bulk load a dataframe into oracle and the `to_sql()` function only takes a SqlAlchemy connection. 

Is there some other mechanism I can use to set the role in cases where I don't have access to a cursor to pre execute the `set role` sql statement?

#### Answer the following questions:

1. What is your version of Python? Is it 32-bit or 64-bit?
Python 3.6.8
2. What is your cx_Oracle version?
Cx Oracle 7.1.2
3. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?
na
4. What error(s) you are seeing?
na
5. What OS (and version) is Python executing on?
Docker image: python:3.6-slim 
6. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where is it installed?
12.2.0.1.0
7. What is your Oracle Database version?

8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?

9. What Oracle environment variables did you set?  How *exactly* did you set them?

10. Do you have a small, single Python script that immediately runs to show us the problem?

**Comment by anthony-tuininga** [comment]
You can use the dbms_session.set_role PL/SQL package as documented [here](https://docs.oracle.com/en/database/oracle/oracle-database/18/arpls/DBMS_SESSION.html#GUID-C4C84E06-96CD-4360-AB4F-E8D13DDFF35F). I'm not aware of any other way to set roles, but hopefully that will work for you!

**Comment by caddac** [comment]
@anthony-tuininga but how do I call this when I only have a cx_oracle connection?

**Comment by anthony-tuininga** [comment]
Well, you would have to have a cursor. There is no way around that. But you can do the following:

```
conn.cursor().callproc("dbms_session.set_role", (theRole,))
```

If you have to do it without a cursor I'm afraid you're out of luck!

**Comment by caddac** [comment]
will the connection maintain this role if I set the role via a cursor?

**Comment by anthony-tuininga** [comment]
Certainly. It will be maintained as long as the connection remains open and no further calls to dbms_session.set_role are made.

**Comment by caddac** [comment]
super helpful, thank you! I'll test this and report back that all works as expected, just for posterity.

**Comment by caddac** [comment]
Tested and setting the role on the cursor works perfectly. Thanks!
