### ISSUE TITLE
Receiving "source and target variable must match" with identical tables

### ISSUE THREAD

**Issue by antzucaro** [oracle/python-cx_Oracle#297]
I'm trying to copy table data from one connection to another via `fetchraw()` and `executemanyprepared()` as described [here][here]. On each side the same tables definitions exist such that the DDL of the "source" table is the same as that of its "target". I am essentially trying to do the equivalent of `insert into target select * from source` using direct connections instead of database links, but I keep getting the following error:

`cx_Oracle.ProgrammingError: source and target variable type must match`

Here is the relevant code:

````python
# list of (column position, bind variable name, is_a_lob_col boolean)
bind_var_xref = [(col_pos, column.name, False) for col_pos, column in enumerate(columns)]

# configure the "read" side
read_cursor = src_conn.cursor()
read_cursor.arraysize = arraysize
read_vars = read_cursor.execute(select_sql)
read_input_sizes = [elem[1] for elem in read_vars.description]

# configure the "write" side
write_cursor = tgt_conn.cursor()
write_cursor.bindarraysize = arraysize
write_cursor.prepare(insert_sql)
write_vars = write_cursor.setinputsizes(*read_input_sizes)

target_vars = [(read_input_sizes[col_pos], write_vars[col_pos], is_lob) 
			   for col_pos, col_name, is_lob in bind_var_xref]

# import pdb; pdb.set_trace()

while True:
	fetched = read_cursor.fetchraw()
	log.info("fetched {} rows".format(fetched))

	if not fetched:
		break

	# copy internal data from read cursor to write cursor
	for pos in range(fetched):
		for defined_var, bound_var, is_lob in target_vars:
			# TODO: special handling for LOB columns
			bound_var.copy(defined_var, pos, pos)
			
	write_cursor.executemanyprepared(fetched)
	tgt_conn.commit()
````

If I debug the values for the first two parameters passed into `copy()`, I see that the source side is a plain `cx_Oracle.STRING` while the target side comes out as `cx_Oracle.String with value[...]`. Why is this if I'm setting the input sizes of the write cursor with values from the read cursor? I'm stuck.

[here]: https://sourceforge.net/p/cx-oracle/mailman/message/2930785/ 

#### Other relevant data

1. What is your version of Python? Is it 32-bit or 64-bit?

Python2.7, 64 bit

2. What is your cx_Oracle version?

5.2.1

5. What OS (and version) is Python executing on?

RHEL 6.10 Santiago

7. What is your Oracle Database version?

11.2.0.4

**Comment by anthony-tuininga** [comment]
Its actually become simpler since then. :-) Here is an example that does what you want to do, I think.

This SQL creates a source table and target table and populates the source table with 1000 rows.

```
create table sourcetable (
  id                              number(9) not null,
  value                           varchar2(200) not null,
  dateadded                       date not null
);

create table targettable (
  id                              number(9) not null,
  value                           varchar2(200) not null,
  dateadded                       date not null
);

begin
    for i in 1..1000 loop
        insert into sourcetable values (i, 'Test ' || i, sysdate);
    end loop;
    commit;
end;
/
```

This code will read from the source table and populate the target table. It assumes the source and target are identical which I believe is what you want.

```
import cx_Oracle

conn = cx_Oracle.connect("cx_Oracle_bugs/welcome@localhost/DB18")

sourceCursor = conn.cursor()
sourceCursor.execute("select * from sourcetable")

targetCursor = conn.cursor()
targetCursor.prepare("insert into targettable values (:1, :2, :3)")
targetCursor.setinputsizes(*sourceCursor.fetchvars)

while True:
    fetched = sourceCursor.fetchraw()
    print("Fetched", fetched, "rows...")
    if fetched == 0:
        break
    targetCursor.executemany(None, fetched)
conn.commit()
```

**Comment by antzucaro** [comment]
@anthony-tuininga nice, that is quite the clarity improvement! I updated my code and re-ran with an example table. It is still complaining, unfortunately:

````
TypeError: argument 2 must be a list, not int
````

So `fetched` is an int, but it still wants a list (which I don't have since I've done `fetchraw`).

**Comment by anthony-tuininga** [comment]
Ah, that capability was added in cx_Oracle 6.4 and I see that you are still running cx_Oracle 5.2.1. I'd suggest an upgrade. :-) The cursor method executemanyprepared() is deprecated, but the only thing you can use in cx_Oracle 5. I'm not sure if you'll run into any other difficulties -- so upgrade if you can!

**Comment by antzucaro** [comment]
I'll see what I can do about upgrading (deployment issues - argh!). In the interim, changing to `executemanyprepared(fetched)` yields the following:

`cx_Oracle.DatabaseError: ORA-01008: not all variables bound`

However, on the SELECT side I have 5699 columns and on the INSERT side I have 5699 placeholder values (:1 through :5699).

**Comment by anthony-tuininga** [comment]
Perhaps do an upgrade in a virtual environment to verify that the new code works as expected for you? I'm guessing that the problems you are experiencing are due to the many enhancements and bug fixes introduced to the code over the past 3+ years. :-) Maybe start with a smaller data set like the one I used in my example to make sure that the code in general works, even with cx_Oracle 5.2.1?

**Comment by antzucaro** [comment]
Certainly! Thanks for all of your help thus far. If I hit paydirt I'll update this issue.

**Comment by antzucaro** [comment]
Update: it's working fine w/ v5.2.1. I had a bug in my code that does the reconciliation between the number of columns and number of bind vars. Thanks again!

**Comment by anthony-tuininga** [comment]
You're welcome! I'm assuming your question is answered then, and will close this issue.
