### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by premyslc** [oracle/python-cx_Oracle#298]
There is probably memory leak when using nested varray and call function which return ref cursor. Problem occur only if some of nested records are NULL.

Python 3.6.7 64 bit (windows 10 64bit  + linux Ubuntu 16.04 64bit)
cx_Oracle 7.1.3, 7.1.2
Oracle 12.2, 11.2

[cxtest.zip](https://github.com/oracle/python-cx_Oracle/files/3118645/cxtest.zip)

**Comment by anthony-tuininga** [comment]
Thanks for the test case. I see a large amount of memory being used. I'll look into it and get back to you on the source of the issue.

**Comment by anthony-tuininga** [comment]
I discovered the source of the issue and have patched master accordingly. With the patch memory is stable.

**Comment by premyslc** [comment]
Nice work. Really fast. Thanks a lot.

**Comment by anthony-tuininga** [comment]
You're welcome!

**Comment by anthony-tuininga** [comment]
I discovered one issue with the patch, which I have just corrected.

**Comment by anthony-tuininga** [comment]
This has been released with cx_Oracle 7.2.
