### ISSUE TITLE
Connection pooling with sharded db instance?

### ISSUE THREAD

**Issue by anothrNick** [oracle/python-cx_Oracle#30]
What would be the correct way to handle connection pooling with a sharded oracledb instance? 

Right now we are creating a new connection string with each request/query depending on the shard key... is there a way to use the existing connection pooling within cx_Oracle for this use case?

**Comment by anthony-tuininga** [comment]
There is no way to handle this currently other than by creating a new connection string with each request/query depending on the shard key. There are plans to add sharding support but not current plans!

**Comment by anothrNick** [comment]
Thanks for responding!
