### ISSUE TITLE
Using `executemany`  to insert `None` into a `SDO_GEOMETRY` field fails with ORA-00932

### ISSUE THREAD

**Issue by pogson** [oracle/python-cx_Oracle#301]
How do you insert `null` into a `SDO_GEOMETRY` field using `executemany`?
I expect this to work but it fails with an exception
```
data = None
cur = conn.cursor()
cur.executemany("INSERT INTO TEST_TABLE (GEOM_FIELD) VALUES (:1)", [[data]])
conn.commit()
```
**Error**
```
cx_Oracle.DatabaseError: ORA-00932: inconsistent datatypes: expected MDSYS.SDO_GEOMETRY got CHAR
```

I have a table:
```
create table TEST_TABLE
(
  GEOM_FIELD         MDSYS.SDO_GEOMETRY,
  TEXT_FIELD            VARCHAR2(4)
)
```

This works
```
data = 'foo!'
cur = conn.cursor()
cur.executemany("INSERT INTO TEST_TABLE (TEXT_FIELD) VALUES (:1)", [[data]])
conn.commit()
```

This also works
```
data = conn.gettype("SDO_GEOMETRY").newobject()
cur = conn.cursor()
cur.executemany("INSERT INTO TEST_TABLE (GEOM_FIELD) VALUES (:1)", [[data]])
conn.commit()
```

I've seen references to `setinputsizes` but am unsure how to use it in this situation.

- **Python** 2.7 64bit
- **cx_Oracle** 7.1.2
- **Ubuntu** 18.04.1 LTS
- **Oracle Instant client** 12.2 64bit

Any help would be greatly appreciated. Thanks.

**Comment by anthony-tuininga** [comment]
Oracle requires a type, even for null values, so cx_Oracle assumes STRING when you pass the value None. You can do the following, however:

```
typeObj = conn.gettype("SDO_GEOMETRY")
cursor = conn.cursor()
cursor.setinputsizes(typeObj)
cursor.execute("insert into issue_301 values (:1)", [None])
```

Bulk execution works the same way.

**Comment by pogson** [comment]
Hmm, that allow the code to work but it looks like it now creates an empty `SDO_GEOMETRY` object and inserts it into the field. No i was query `SELECT * FROM TEST_TABLE WHERE GEOM_FILED IS NULL`.
