### ISSUE TITLE
Clarify cx_Oracle forwards compatibility.

### ISSUE THREAD

**Issue by danizen** [oracle/python-cx_Oracle#303]
### General questions

(This comment](https://github.com/oracle/python-cx_Oracle/issues/210#issuecomment-410387264) on issue #210  states that cx_Oracle 7 is the first to officially support Oracle 18c.  Please explain why this is so, given that the compatibility matrix states that 12.1.0.1 supports 18c and cx_Oracle 6.4.1 appears to be *hard* linked with libclnt

Before our upgrade, I did an analysis of the OCI version built into cx_Oracle, and whether we were using shared libraries or whether it was statically linked.   

Looking at the Oracle compatibility matrix, the 12.1.0.1 OCI libraries are compatible with Oracle 18c and also backwards compatible.

Why then the statement about cx_Oracle 7 being needed for Oracle 18c in this other issue?

#### Answer the following questions:

1. What is your version of Python? Is it 32-bit or 64-bit?

64-bit, SCL /opt/rh/rh-python36

2. What is your cx_Oracle version?

6.4.1, usually, almost always the manylinux1 variety (e.g. hard-linked instantclient)

3. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?

Forward looking question about support

4. What error(s) you are seeing?

5. What OS (and version) is Python executing on?

CentOS 6.10

6. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where is it installed?

It is not the instantclient, but is copied there by the Oracle admins.   There is a shared read-only NFS drive, /usr/nlm/share:

$ echo $LD_LIBRARY_PATH
/opt/rh/rh-python36/root/usr/lib64:/usr/nlm/share/oracle/12.1.0.1/lib

$ echo $ORACLE_HOME
/usr/nlm/share/oracle/12.1.0.1

It is not the instantclient.

7. What is your Oracle Database version?

Oracle 18c

8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?

See above under question about instantclient.

9. What Oracle environment variables did you set?  How *exactly* did you set them?

Usually in .bashrc, I have the following code:

```
ORACLE_HOME=/usr/nlm/share/oracle/12.1.0.1
TNS_ADMIN=/usr/nlm/share/etc/tns_admin
NLS_LANG="AMERICAN_AMERICA.UTF8"

# Put oracle's pelr libraires into PERL5LIB
if [ -z "$ORAPERL" ]; then
    ORAPERL=/usr/nlm/share/oracle/12.1.0.1/perl
    PERL5LIB="$ORAPERL/lib/5.14.1:$ORAPERL/lib/site_perl/5.14.1";
    export PERL5LIB
fi
export ORACLE_SID
export ORACLE_HOME
export ORACLE_PERL
export PERL5LIB
export TNS_ADMIN
export NLS_LANG
```

10. Do you have a small, single Python script that immediately runs to show us the problem?

Not sure there is a problem to diagnose as yet.

**Comment by anthony-tuininga** [comment]
cx_Oracle 7 is the first version to **officially** support Oracle 18 client libraries. There is a good possibility that it will work with earlier versions of cx_Oracle but we haven't done any testing to confirm or deny that possibility. If you do your own testing and are satisfied it works, then feel free to use that combination!

**Comment by danizen** [comment]
Before our upgrade, I ran ldd on each version of cx_Oracle that is deployed across our organization, and saw that libclntshcore.so and libclntsh.so had explicit rpaths in the versions I'd built myself prior to manylinux1 PEP.

I also ran cx_Oracle.clientVersion() with each version and convinced myself that OCI12.1.0.1 was hard-linked into cx_Oracle 6.3.1, 6.4.1, and 7.1.3, etc.   Now I think that is not the case - reading https://oracle.github.io/odpi/doc/installation.html, it seems likely that ODPI itself does some level of dynamic linking and loading -  is that a correct interpretation of what is going on here?

Thanks,

-Dan

**Comment by anthony-tuininga** [comment]
Yes, ODPI-C attempts to dynamically load the Oracle Client libraries. It first tries libclntsh.so and then (depending on the version that is used) tries various versioned libclntsh.so files. It also looks for ORACLE_HOME which is set for full client and database installations. So one compiled binary of cx_Oracle works with all versions of the Oracle client libraries.

**Comment by danizen** [comment]
I have confirmed this - when the instantclient 18.5.0.0 is on the path, I get a different answer from cx_Oracle.clientversion().
