### ISSUE TITLE
Cannot dequeue XML data from a AQ

### ISSUE THREAD

**Issue by rafaelreuber** [oracle/python-cx_Oracle#304]
I'm getting the error "ORA-25215: user_data type and queue type do not match" when I try to dequeue raw data from an advanced queue.

```
Traceback (most recent call last):
  File "desenfileirar.py", line 12, in <module>
    data = queue.deqOne()
cx_Oracle.DatabaseError: ORA-25215: user_data type and queue type do not match
```

This is the script
```
import cx_Oracle

dsn_destino = cx_Oracle.makedsn('localhost', '1521', 'xe')
conn = cx_Oracle.connect('myuser', 'mypassword', dsn_destino)

queue = conn.queue('AQ_SAIDA_MATERIAIS')
queue.deqOptions.wait = cx_Oracle.DEQ_NO_WAIT
queue.deqOptions.navigation = cx_Oracle.DEQ_FIRST_MSG

# dequeue all existing messages.
while True:
    data = queue.deqOne()
    if not data:
        break
    print(data.payload.decode())
```
This is the queue DDL
```PLSQL
BEGIN DBMS_AQADM.CREATE_QUEUE_TABLE(
     Queue_table        => '"MVINTEGRA"."AQ_SAIDA_MATERIAIS"',
     Queue_payload_type => 'SYS.XMLTYPE',
     Sort_list          => 'ENQ_TIME',
     Compatible         => '8.1.3');
END;

BEGIN DBMS_AQADM.CREATE_QUEUE(
     Queue_name          => 'MVINTEGRA.AQ_SAIDA_MATERIAIS',
     Queue_table         => 'MVINTEGRA.AQ_SAIDA_MATERIAIS',
     Queue_type          =>  0,
     Max_retries         =>  5,
     Retry_delay         =>  0,
     dependency_tracking =>  FALSE);
END;
```

1. What is your version of Python? Is it 32-bit or 64-bit?
 64 bits

2. What is your cx_Oracle version?
7.2.0-dev 

3. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?
  pip install python-cx_Oracle-master.zip

4. What error(s) you are seeing?
   FileNotFoundError: [Errno 2] No such file or directory: 'odpi/src'

5. What OS (and version) is Python executing on?
   Fedora 29 (64Bits)

6. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where is it installed?
   The version used is 12.2.0.1.0. I installed using rpm files. Is installed on /usr/lib/oracle/12.2

7. What is your Oracle Database version?
   XE

8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?
  LD_LIBRARY_PATH: /usr/lib/oracle/12.2/client64/lib

**Comment by anthony-tuininga** [comment]
That error is expected. You've told cx_Oracle that you intend to enqueue/dequeue RAW data, but your queue is of type SYS.XMLTYPE. That's quite different. :-)

**Comment by anthony-tuininga** [comment]
I haven't tried it or even know if it is possible, but you could attempt to create a transformation?

**Comment by rafaelreuber** [comment]
I thought raw type was Number, String, Date etc.. but, of course, Oracle have the **RAW** data type! RAW is not a type that you I use or encounter very often. It’s useful when you need to deal with small amounts of binary data.

**Comment by rafaelreuber** [comment]
cx_Oracle is able to deal with queues that have XMLType as the datatype?

**Comment by rafaelreuber** [comment]
I foun a workaround: 

I created a function to deque the first message and return as CLOB value.

```plsql
  function dequeue_as_clob(queue_name varchar2) return clob 
  AS
    dequeue_options     DBMS_AQ.dequeue_options_t;
    message_properties  DBMS_AQ.message_properties_t;
    message_handle      RAW(16);
    message             XMLType;
    v_data                clob;
  BEGIN
    dequeue_options.navigation := DBMS_AQ.FIRST_MESSAGE;
    
    DBMS_AQ.DEQUEUE(
      queue_name          =>     queue_name,
      dequeue_options     =>     dequeue_options,
      message_properties  =>     message_properties,
      payload             =>     message,
      msgid               =>     message_handle
    );
    commit;
    v_data := message.getClobVal();
    RETURN v_data;
      
  END dequeue_as_clob;
```
My django model wrap this function and return the element as an XML object

```python
class SaidaMateriasAQ(models.Model):
    state = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'AQ_SAIDA_MATERIAIS'

    @classmethod
    def deque(cls):
        import cx_Oracle
        from xml.etree import ElementTree as ET
        if cls.is_empty():
            return None
        queue_table = cls._meta.db_table
        with connections['mv'].cursor() as cursor:
            data = cursor.callfunc('qa_util.dequeue_as_clob',
                                   cx_Oracle.CLOB, [queue_table])
            xml_data = data.read()
        xml_data = ET.fromstring(xml_data)
        return xml_data

    @classmethod
    def is_empty(cls):
        qset = cls.objects.filter(state=0)
        return qset.count() == 0
```

**Comment by anthony-tuininga** [comment]
That's about the only option at the moment as XMLType is only really usable within PL/SQL. I tried a few methods for using a transformation but none were successful. Thanks for following up with your solution. I'm assuming your question is answered for now, then!
