### ISSUE TITLE
Pickling of cx_Oracle objects

### ISSUE THREAD

**Issue by Bulva** [oracle/python-cx_Oracle#305]
Hi,

Could be possible add support for [pickling](https://docs.python.org/3/library/pickle.html) of cx_Oracle objects? If I want share the data with more processes in Python I have to extract the user defined type objects or geometry objects first. But this is the most time consuming part of the processing the data.

1. What is your version of Python? Is it 32-bit or 64-bit?
64-bit
2. What is your cx_Oracle version?
7.1.3
5. What OS (and version) is Python executing on?
Windows 10 and Ubuntu 18.04
7. What is your Oracle Database version?
12c
10. Do you have a small, single Python script that immediately runs to show us the problem?

**Comment by anthony-tuininga** [comment]
Just to be clear, you are referring to objects that are instances of the object types found by the connection method ``gettype()``?

**Comment by Bulva** [comment]
Thanks for your response. I am not sure if understand it completely but probably yes. Here is the part of the documentation - https://cx-oracle.readthedocs.io/en/latest/objecttype.html

Here is the code that has to be in the main process because if there is a `cx_oracle.Object` as `obj` argument the object can't be pickled.
```
def ObjectRepr(obj):
    if obj.type.iscollection:
        returnValue = []
        for value in obj.aslist():
            if isinstance(value, cx_Oracle.Object):
                value = ObjectRepr(value)
            returnValue.append(value)
    else:
        returnValue = {}
        for attr in obj.type.attributes:
            value = getattr(obj, attr.name)
            if value is None:
                continue
            elif isinstance(value, cx_Oracle.Object):
                value = ObjectRepr(value)
            returnValue[attr.name] = value
    return returnValue  
```

**Comment by anthony-tuininga** [comment]
Hmm, getting an object to be pickled would be fairly straightforward, but trying to have it unpickled would be problematic as a connection is required! So the best solution in your situation, I think would be to simply use introspection as shown in the ObjectRepr() method above and create a "plain" Python object. For collections, this is easily accomplished by calling ``obj.aslist()`` or ``obj.asdict()``. Of course, if you have nested objects, this would need to be performed recursively. For objects with attributes there is no method currently to transform into a plain Python object. Would adding such a method be helpful?

**Comment by Bulva** [comment]
I am using the ObjectRepr method but if I have main process and then 4 child processes where I am processing the data, the extracting the object (transforming to plain Python object) takes a pretty long time (if there is recursive object or geometry - SDO_GEOM). It takes few seconds (10 secs and more) on core with 1.6 GHz. It is much better with higher frequency on one core (for 3.4 GHz the extracting of the geometry or recursive objects takes about 1 second).

So the best solution for me is moving the extracting the objects (transforming to plain Python object) in the child processes. But how you said, it looks problematic now because of need of the connection object.

**Comment by anthony-tuininga** [comment]
Is there any reason you can't do some of the querying in the child processes? In other words, instead of extracting 30-40 thousand objects in the parent process, extract about 10 thousand objects in each child process and process them there. If you're dealing with geometry, there are other methods available to get it into well-known formats which the server can do on your behalf. For the user-defined objects, do you need all of the attributes? The fewer attributes you extract, the faster it will be.

**Comment by Bulva** [comment]
Yeah, we are processing millions of rows and it is much easier to have only one cursor because I think it is not possible to share cursor object between processes. 

Yeah there is and Oracle function TO_WKTGEOMETRY(). But this functions works so bad (there is uncaught exception if the geometry has vertices that are to close to each other and not working for complex geometries) and is so slow that after a half year we decided download the data and use our library for creating the WKT geometry format.

**Comment by anthony-tuininga** [comment]
No, you can't share connections or cursors between processes. But you can have separate connections perform independent queries in a coordinated fashion. If you're processing a large amount of data that's probably going to be the best option. If you're able to share some of the data you're processing and the code you're using to process it I might be able to find a way to improve the performance in a general fashion.

**Comment by dlapp** [comment]
Regarding the comment on TO_WKTGEOMETRY(), there were indeed issues with the function prior to 18c. From 18c onward, issues have been resolved and the function is roughly 100 times faster.

**Comment by Bulva** [comment]
@dlapp  Oh, very nice I am really glad for the improving TO_WKTGEOMETRY() function. Thank you very much 

@anthony-tuininga Thank you for your help. I think we know which way we should implement other functionality. Thanks a lot. I'll close that thread.
