### ISSUE TITLE
Tracking: Known issues with SODA

### ISSUE THREAD

**Issue by morgiyan** [oracle/python-cx_Oracle#309]
This is to track known [SODA](https://docs.oracle.com/en/database/oracle/simple-oracle-document-access/index.html) issues.

Client-libraries required for SODA production use: 18.5 and above.
Oracle Database: 18 and above.

**Known issues affecting SODA node.js are:**

(1) **Bug 28533043** - this is an issue at OCI level affecting performance of "finds" that return multiple documents. Due to lack of reliance on OCI array fetch, which allows fetching multiple documents in one round-trip, fetching each document requires a round-trip to the database. **Status:** fixed, now getting backported to 18.x and 19.x DBRU.

(2) **Bug 29607136** - this is an RDBMS-side bug is in index specification processing: when multiple varchar2 fields are indexed, an error is produced (instead of a successful index create). The error is in automatic computation of maxLength field of the index spec. **Status:** fixed, now getting backported to 18.x and 19.x DBRU. There's an easy workaround for this bug, which is to specify the maxLength field explicitly for each varchar2 field of the index spec. 

(3) **Bug 29523511** - this is an issue at OCI level. It's a memory leak when QBE is used and NLS_LANG specified client character set is other than AL32UTF8. **Status**: fixed, now getting backported to 19.x DBRU. 

(4) If you are creating collections with Oracle Database 21c, see the note in the cx_Oracle [SODA Requirements
](https://cx-oracle.readthedocs.io/en/latest/api_manual/soda.html#soda-requirements) documentation.

**Enhancement Requests**

- Case insensitive sorting. Requested for node.js driver, but the same issue applies to cx_Oracle as well. See node.js issue [1099](https://github.com/oracle/node-oracledb/issues/1099)

**Comment by cjbj** [comment]
Thanks @morgiyan.  We'll update the cx_Oracle doc regarding production use.

**Comment by cjbj** [comment]
I updated the initial post with a link that Oracle DB 21c users should take heed of.

**Comment by cjbj** [comment]
I'll close this now as stale.  Any new limitations can be logged in the new driver namespace https://github.com/oracle/python-oracledb
