### ISSUE TITLE
DPI-1047 on Windows the specified path is invalid

### ISSUE THREAD

**Issue by flummoxify** [oracle/python-cx_Oracle#312]
The error is:
DatabaseError: DPI-1047: Cannot locate a 64-bit Oracle Client library: "The specified path is invalid". See https://oracle.github.io/odpi/doc/installation.html#windows for help

This is very confusing because the first directory path in the PATH statement is a valid location to a 64bit oci.dll file.  If you give the ms-dos command "where oci.dll" you get this directory as the single output.

**My Environment:**
- Windows 64bit
- Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 ### **64 bit** (AMD64)]
- cx-Oracle    v 7.1.3

- PATH=C:\Program Files\Oracle12c\x64\product\12.1.0\client_1\bin;C:\Program Files\Java\jre1.8.0_212\bin;C:\Program Files\Anaconda3_520;....

- The **full** Oracle 64bit 12.1 Client has been installed (sqlplus, sqlldr, impdp, expdp, ...)
- Oracle Database 12.1
- The Windows Control Panel says that the Microsoft Visual C++ 2010 x64 Redistributable 10.0.40219 has been installed (along with similar versions for 2012, 1013, and 2015).

--------------
The python program:

import cx_Oracle
db1 = cx_Oracle.connect('Userid/Password@ptectlsoradb140:1600/PRODDB')
print(db1.version)

Thanks much!

**Comment by anthony-tuininga** [comment]
According to Google search, the error "The specified path is invalid" can occur if there is something invalid in the ``PATH`` environment variable -- perhaps quotes or some invalid characters. I'd check by setting the ``PATH`` environment variable to something very simple and see if you continue to get the same error.

**Comment by flummoxify** [comment]
Resolved.  The problem was that the Spyder IDE does not re-pull the PATH statement and I had made a change to the path statement and forgot about it.  I figured it out when I ran the python program from the cmd window and it worked.
Thanks.
