### ISSUE TITLE
Instant Client Question

### ISSUE THREAD

**Issue by GrimTheReaper** [oracle/python-cx_Oracle#316]
Is there any way to use this library without having the Instant Client installed in `/opt`/?

**Comment by anthony-tuininga** [comment]
An Oracle Client library of some kind is currently required. It does not have to be installed in ``/opt`` and it doesn't have to be the Instant Client, but that's generally the easiest Oracle Client library to install!

**Comment by GrimTheReaper** [comment]
@anthony-tuininga the issue I'm facing right now is that the Instant Client _has_ to be installed in `/opt`, which on some GCP utilities, cannot be done.

**Comment by anthony-tuininga** [comment]
If you download the Instant Client zip file you can unzip it anywhere. You simply have to set ``LD_LIBRARY_PATH`` accordingly. Take a look at the [installation directions](https://cx-oracle.readthedocs.io/en/latest/installation.html#oracle-instant-client-zip-files). I'm assuming here that you are using Linux.

**Comment by GrimTheReaper** [comment]
@anthony-tuininga I'll try that, and then close this.

**Comment by GrimTheReaper** [comment]
@anthony-tuininga I'm now running into `ORA-12170`, so I'm going to assume that this issue is resolved and now I need to bug our network admin? 

<details>

``` python   
Traceback (most recent call last)
  File "/usr/local/lib/airflow/airflow/models.py", line 1659, in _run_raw_tas
    result = task_copy.execute(context=context
  File "/usr/local/lib/airflow/airflow/operators/python_operator.py", line 95, in execut
    return_value = self.execute_callable(
  File "/usr/local/lib/airflow/airflow/operators/python_operator.py", line 100, in execute_callabl
    return self.python_callable(*self.op_args, **self.op_kwargs
  File "/home/airflow/gcs/dags/opsdag.py", line 11, in getDat
    hook.get_records(basicQuery
  File "/usr/local/lib/airflow/airflow/hooks/dbapi_hook.py", line 111, in get_record
    with closing(self.get_conn()) as conn
  File "/usr/local/lib/airflow/airflow/hooks/oracle_hook.py", line 65, in get_con
    conn = cx_Oracle.connect(conn.login, conn.password, conn.host
DatabaseError: ORA-12170: TNS:Connect timeout occurre
```

</details>

**Comment by anthony-tuininga** [comment]
Yes, it looks like it is installed and working for you. Check your connection parameters to make sure they are correct and any firewall between the client and the server.
