### ISSUE TITLE
Question - how should cx_Oracle SessionPool interoperate with Django, in an ideal world

### ISSUE THREAD

**Issue by danizen** [oracle/python-cx_Oracle#318]
### Does Django need to use a `cx_Oracle.Connection` objects per thread of execution

Most Django packages that make use of `cx_Oracle.SessionPool`, including:
* https://github.com/JohnPapps/django-oracle-drcp
* https://bitbucket.org/edcrewe/django-oraclepool/src/default/

appear to cache a `cx_Oracle.Connection` object in the Django object representing a connection, with the result that the same `cx_Oracle.Connection` object will be used per kernel thread for the length of a request.   I want to confirm that In order to make use of a pool then, Django needs to be configured not to hold onto the connection but to close it, e.g. avoid `CONN_MAX_AGE`.   More importantly, if multiple-threads are used to accelerate work, then the same `cx_Oracle.connection` will be used, which implies that `threaded` must be used, and also has some issues for the use of transactions.

### Background

Django's built-in Database backend makes a single connection and holds it is memory as an instance variable of an object.   The parent object will appear as `django.db.connection` within Django application's, but has an underlying connection, `django.db.connection.connection`, that is a true `cx_Oracle.Connection`:

```ipython
(nlmoccs-py36) λ manage.py shell --settings test_settings.oracle
Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from django.db import connection

In [2]: type(connection.connection)
Out[2]: NoneType

In [3]: connection.ensure_connection()

In [4]: type(connection.connection)
Out[4]: cx_Oracle.Connection

In [5]: type(connection)
Out[5]: django.db.DefaultConnectionProxy
```

Whether multiple threads or a event processing framework using user threads are used, Django must be configured to use a close to close a connection per request, e.g. to avoid the `CONN_MAX_AGE` setting.  This issue is about how to actually be able to use multiple kernel threads or green threads to accelerate some work.

### Is there any difference between `cx_Oracle.SessionPool` behavior between cx_Oracle<6, >=6?

A recent issue, #306, forces us to use an older version of cx_Oracle, but most likely the answers will apply to all versions, it is good to get this on the record as other users investigate related issues.

### Related issues

This question is related to #100, but goes into deeper detail on the work required to take advantage of session pooling in Django environments using multiple threads, both kernel threads and greenlet threads such as used in asynchronous I/O environments.

Issue #306 is also related because we must temporarily use an older architecture for cx_Oracle.

**Comment by anthony-tuininga** [comment]
> Is there any difference between cx_Oracle.SessionPool behavior between cx_Oracle<6, >=6?

As far as I know, there are no significant differences between cx_Oracle < 6 and cx_Oracle >=6 when it comes to session pools -- other than additions such as improved support for session tagging, closing session pools, dead session detection, etc. and the elimination of various bugs.

The main difference between cx_Oracle < 6 and cx_Oracle >= 6 has to do with the implementation of ODPI-C, which means that prior to cx_Oracle 6 whatever client version you compiled with is the only version you can use. With cx_Oracle 6 and later compilation does not require the Oracle Client SDK and any supported Oracle Client can be used.

Regarding your other question about Django, it looks like ``CONN_MAX_AGE`` is by default 0, which means that the connection will only remain alive for the duration of the request. That seems perfectly reasonable. Generally when using a pool, you want to acquire the connection, do what you need to do with it and then close it again (releasing it back to the pool). There is no need to retain it for any period of time whatsoever.

**Comment by anthony-tuininga** [comment]
Did your questions get answered?

**Comment by anthony-tuininga** [comment]
I am assuming this question has been adequately answered due to lack of activity.

**Comment by danizen** [comment]
Thank you this answers my questions.
