### ISSUE TITLE
'ascii' codec can't decode byte ** in position **

### ISSUE THREAD

**Issue by helatma1** [oracle/python-cx_Oracle#320]
the python code work fine from the PC where I develop the script
but when i generate the executable .EXE of my script and deploy it in another PC then 
I have this issue of encoding.
I don't have the issue in the original PC even with the .EXE !!!

The difference between the 2 PC are:
 The oracle client version and also the fact that are 2 PC :) so I don't know if there is any special setting for the character encoding !

Please advise 

1. What is your version of Python? Is it 32-bit or 64-bit?
2.7 32-bit

2. What is your cx_Oracle version?
7.1.0

3. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?

con = cx_Oracle.connect(****************)
cursor = con.cursor()
result = cursor.callproc(my_store_proc, paramters)

inside the paramters i have the variable type of : cursor.var(cx_Oracle.CURSOR)

the issue was raised when we do the call of callproc...

4. What error(s) you are seeing?

'ascii' codec can't decode byte ** in position **

5. What OS (and version) is Python executing on?

windows 7

6. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where is it installed?

oracle 11

7. What is your Oracle Database version?

oracle 11

**Comment by anthony-tuininga** [comment]
You haven't provided a lot of detail on the actual data, which in this case is highly important! With Python 2.7, the default encoding is 'ascii' which is very limited in capability. If you have any characters that exceed the ASCII range you will get that error. You will need to ensure that all of the data fits within the ASCII range or you will need to make sure you are using the "unicode" type in Python 2.7. Better yet, upgrade to Python 3. :-)

**Comment by helatma1** [comment]
Hi anthony,

As I said in my description it works fine with 2.7 as a puthon script .PY and also as an executable.
So there is no issue with the data.

The issue is when I deploy the .EXE to another PC that it happens.

In one of the comment in the issues someone suggest to debug the DPI.

So it crash at this level:

......
ODPI [05084] 2019-06-13 12:32:11.440: ref 044A5B60 (dpiConn) -> 2
ODPI [05084] 2019-06-13 12:32:11.440: ref 044A5B60 (dpiConn) -> 1
ODPI [05084] 2019-06-13 12:32:11.440: fn end dpiStmt_release(03AD2808) -> 0
**'ascii' codec can't decode byte 0xe8 in position 4: ordinal not in range(128)**

Thanks.

**Comment by anthony-tuininga** [comment]
Since this is happening in cx_Oracle the ODPI-C debugging won't help you much, unfortunately. Check the value of NLS_LANG on the working and non-working machines.  You can also see what cx_Oracle thinks is in place by looking at ``connection.encoding`` and ``connection.nencoding`` on the working and non-working machines.

**Comment by helatma1** [comment]
Hi, 
The NLS_LANG is different between the two so from that what I have to do and how to handle different NLS_LANG since the app can be deployed in different PC and settings ?
Thanks.

**Comment by anthony-tuininga** [comment]
What is the value of NLS_LANG on the "working" machine vs the "non-working" machine? You can override the encoding when you create the connection itself, as in the following code:

```
conn = cx_Oracle.connect("user/pw@host/service", encoding="UTF-8", nencoding="UTF-8")
```

The database then expects that all of your strings are UTF-8 encoded (or are unicode objects which cx_Oracle will turn into UTF-8 encoded strings as needed) and will return all of your data as UTF-8 encoded strings (or unicode objects). If you can't count on the configuration of the machines, then you'll want to do something like this.

**Comment by anthony-tuininga** [comment]
Did you get this resolved?

**Comment by helatma1** [comment]
Hi Anthony,
I found the issue coming not from cx_Oracle, I apologize for the miss-leading.
To share with the others the issue was at the level of the text element in the PySimpleGui library.
I opened an issue for that.
You can close this one.
Thanks.

**Comment by anthony-tuininga** [comment]
Thanks for following up and I'm glad you discovered the source of the issue!
