### ISSUE TITLE
UnicodeDecodeError when attempting to access a cursor's description attribute

### ISSUE THREAD

**Issue by hexaclock** [oracle/python-cx_Oracle#322]
1. What is your version of Python? Is it 32-bit or 64-bit?
Python 3.5.2 64-bit on RHEL 6.6 - Linux 2.6.32-504.3.3.el6.x86_64

2. What is your cx_Oracle version?
6.2.1

3. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?
Logged in as a normal user. When we tried to access cursor.description, the interpreter threw the error: 

```
File "/lib/python3.5/encodings/cp1252.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 5: character maps to <undefined>
```

This happened after we executed a relatively simple query.

4. What error(s) you are seeing?
See above

5. What OS (and version) is Python executing on?
 RHEL 6.6 - Linux 2.6.32-504.3.3.el6.x86_64

6. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where is it installed?
Oracle Instant Client 11.2.0 x64

7. What is your Oracle Database version?
Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit 

10. Do you have a small, single Python script that immediately runs to show us the problem?

Unfortunately, this appears to be a transient error. Upon retrying the query at a later point in the day, we experience no issues. We have not isolated the exact scenario that causes our script to fail. If need be, I can provide an example anyhow.

**Comment by anthony-tuininga** [comment]
If you are able to reliably reproduce the issue, that would be helpful! You can also try connecting to the database using the following code:

```python
connection = cx_Oracle.connect("user/pw@host/service", encoding="UTF-8", nencoding="UTF-8")
```

Can you also explain what you mean by "access cursor.description"? Can you also provide the full traceback?

**Comment by hexaclock** [comment]
```
  File "DBConnection.py", line 347, in execute
    result = _cursorWrapper(self.oraCursor)
  File "DBConnection.py", line 420, in __init__
    self.__build_map(oraCursor.description)
  File "/lib/python3.5/encodings/cp1252.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 5: character maps to <undefined>
```
I believe this error bubbles up from https://github.com/oracle/python-cx_Oracle/blob/master/src/cxoCursor.c#L597 which ultimately results in a call to `cxoPyString_fromEncodedString` @ https://github.com/oracle/python-cx_Oracle/blob/master/src/cxoCursor.c#L521 (defined as `PyUnicode_Decode(buffer, numBytes, encoding, errors)` )

This results in an that exception being set somewhere in the function defined at https://github.com/python/cpython/blob/master/Objects/unicodeobject.c#L3295


By "access cursor.description" I mean try to read the `description` variable as per https://cx-oracle.readthedocs.io/en/latest/cursor.html#Cursor.description

What is particularly strange about this issue is that it really doesn't seem to be predictable. We have an untouched application that will throw this error a couple of times per month, but when we try again later (usually on the same day the error occurs), we don't experience a problem.

**Comment by anthony-tuininga** [comment]
It would be helpful to know what ``__build_map(oraCursor.description)`` is doing, to know the exact code that is being used to process ``cursor.description``. The fact that it occurs randomly does seem a bit strange. Did you try the code I suggested as well?

**Comment by hexaclock** [comment]
Sure. The code is relatively simple:

```
class _cursorWrapper(list):
    def __init__(self, oraCursor):
        list.__init__(self)
        self.__oraCursor = oraCursor
        self.position_map = {}
        self.__build_map(oraCursor.description)

    def __build_map(self, description):
        if description is None:
            return None
        for cnt, values in enumerate(description):
            self.position_map[values[0]] = (cnt, values)
```
Based on the above, however, I don't think `__build_map` is the source of the issue as the error is thrown upon accessing `cursor.description`, prior to the actual call being made.

And yes, I gave that shot but via instantiating the `cx_Oracle.Connection` class instead:
`cx_Oracle.Connection(DBUsername, DBPassword, DBServer, threaded=False, events=True, encoding="UTF-8", nencoding="UTF-8")`. It successfully connected, and I'm able to run queries.

**Comment by anthony-tuininga** [comment]
> And yes, I gave that shot but via instantiating the cx_Oracle.Connection class instead:
cx_Oracle.Connection(DBUsername, DBPassword, DBServer, threaded=False, events=True, encoding="UTF-8", nencoding="UTF-8"). It successfully connected, and I'm able to run queries.

By doing this, though, you shouldn't get the error you mentioned about encoding 'charmap'. You might get a different error, but I don't think so. I agree that the error is likely occurring in the generation of cursor.description (not accessing it). If you print out the value of ``connection.encoding`` in the failing situation that can be confirmed.

One other thought: are you fetching data from a table or view? Or are you building your own query and not specifying the column aliases (letting Oracle build its own)? That might explain why it is happening "randomly" -- depending on what data you query the alias that Oracle is building might contain data that doesn't work with the charmap encoding.

**Comment by hexaclock** [comment]
Ok, I'll make this change but it will unfortunately take some time to verify whether or not this will do the trick as the error doesn't happen very often.

To be sure, we don't re-establish the connection after experiencing this error - we're able to force our application retry the query later in the day via the same connection. Can the `connection.encoding` attribute change on an existing connection? To add more information, we are even using the same cursor object in our retries.

We're fetching data from a couple of tables joined together - the following is an example:

```
rows = cursor.execute('''
    SELECT a.*,
           a.sequence as hist_sequence,
           b.SubOwnerName,
           b.SubOwnerDescription,
           b.Acronym,
           c.OwnerName
      FROM TableA a,
           TableB b,
           TableC c
     WHERE a.Unique_ID = :ident
       AND a.Sequence = (SELECT max(Sequence) - 1 FROM TableA_History WHERE Unique_ID = :ident)
       AND a.SubCode = b.SubCode
       AND a.OwnerID = c.OwnerID
''', ident=unique_key).fetchall()
```
This query does not change dynamically. It is hard-coded, and the only datapoint that changes is the value of the `unique_key` variable. Let me know if that clears things up.

**Comment by anthony-tuininga** [comment]
> Ok, I'll make this change but it will unfortunately take some time to verify whether or not this will do the trick as the error doesn't happen very often.

Sure. If you can include the contents of ``connection.encoding`` in some sort of log file you can see if the value is changing (it never should once the connection is established) and more importantly what the value is.

> To be sure, we don't re-establish the connection after experiencing this error - we're able to force our application to retry the query later in the day via the same connection. Can the connection.encoding attribute change on an existing connection? To add more information, we are even using the same cursor object in our retries.

As noted above, the ``connection.encoding`` attribute does not change once the connection is established. There should be no reason to reuse the same cursor object. There is very minimal overhead in creating a cursor object and the Oracle Client libraries take care of statement caching to avoid the overhead of preparing and executing a statement.

> This query does not change dynamically. It is hard-coded, and the only datapoint that changes is the value of the unique_key variable. Let me know if that clears things up.

Looking at the query you provided, there isn't anything obvious that stands out. Of course you are using ``a.*`` which could hide something interesting. :-) But since the only time the encoding is consulted is when creating the name of the column, unless you have names with "strange" characters in them that you aren't showing here, I'm not sure why you would even note the error at all! You could always hack at the cx_Oracle code and deliberately print out the contents of the name and the name length to a specific file somewhere and wait for the error to occur. Or examine the contents to see if anything is there that doesn't look like what you might expect (corruption?). I've not seen this sort of behaviour myself at any point, unfortunately.

**Comment by hexaclock** [comment]
Yes - we'll log `connection.encoding` on every query execution and see what we get.

> There is very minimal overhead in creating a cursor object and the Oracle Client libraries take care of statement caching to avoid the overhead of preparing and executing a statement.

Noted - we'll change this to use ephemeral cursors instead.

> But since the only time the encoding is consulted is when creating the name of the column, unless you have names with "strange" characters in them that you aren't showing here, I'm not sure why you would even note the error at all!

The column names are all standard ASCII, so this would be very strange indeed.

> Or examine the contents to see if anything is there that doesn't look like what you might expect (corruption?).

The data seems fine upon manually retrying the query. Could this possibly be a problem with the database or some intermediate layer corrupting the data in-transit? I'll try the few changes you noted above (thank you!), and then start introducing additional logging to the cx_Oracle code if our issue persists. I'll keep this thread updated with any findings/results.

**Comment by hexaclock** [comment]
I forgot to include - this issue started occurring when we switched/upgraded to Oracle 12c from 11g. Prior to that, our application did not exhibit any strange errors of this type.

**Comment by anthony-tuininga** [comment]
Thanks for the information and I look forward to hearing of further developments. :-)

**Comment by hexaclock** [comment]
@anthony-tuininga Upon taking a closer look, our database uses `WE8ISO8859P15` as its character set (`SELECT value$ FROM sys.props$ WHERE name = 'NLS_CHARACTERSET';`). Does it still make sense to set UTF-8 as the encoding/nencoding or might a different value be more applicable/correct?

**Comment by anthony-tuininga** [comment]
UTF-8 is an universal character set. As such, it can be used for all characters that can be stored in the database. The only consideration is going to be the cost of converting between the two character sets -- and that is going to depend on the data you have stored in your database. The overhead should generally be minimal, though.

**Comment by anthony-tuininga** [comment]
I am assuming this question has been adequately answered due to lack of activity.
