### ISSUE TITLE
Oracle type with attribute names that are invalid python identifiers

### ISSUE THREAD

**Issue by neilnsmith** [oracle/python-cx_Oracle#323]
Python version: 3.7.3150.1013 64bit 
cx_Oracle version: 7.1
OS: Windows 10 Enterprise
Oracle Client: 18C instant client
Oracle Database 12.2.0.2

We have existing types in the database:

    CREATE OR REPLACE TYPE RV_FIELD AS OBJECT (
        field_name      VARCHAR2(20),
        field_type      VARCHAR2(8),
        varchar2$$value VARCHAR2(4000),
        number$$value   NUMBER,
        date$$value     DATE
    );

If I try to use the type from python, 

    fieldType = con.gettype("RV_FIELD")
    field = fieldType.newobject()
    field.VARCHAR2$$VALUE = "Test"

I get an error because VARCHAR2$$VALUE is not a valid identifier, 

    Syntax Error: invalid syntax: field.VARCHAR2$$VALUE = "Test"

but if I look at the attributes

    print(fieldType.attributes)

that's what seems like is expected

    [
       <cx_Oracle.ObjectAttribute FIELD_NAME>, 
       <cx_Oracle.ObjectAttribute FIELD_TYPE>,  
       <cx_Oracle.ObjectAttribute VARCHAR2$$ VALUE>, 
       <cx_Oracle.ObjectAttribute NUMBER$$VALUE>, 
       <cx_Oracle.ObjectAttribute DATE$$VALUE>
    ]

so how do I reference the attributes that contain $$ in the names?  Is there any way that I can use the type via cx_Oracle without having to change the type itself (there are a lot of existing dependencies on it)?

Thanks.

**Comment by anthony-tuininga** [comment]
If the value is not a valid Python identifier you have to use the ``setattr()`` method as in the following code:

```
objType = conn.gettype("RV_FIELD")
obj = objType.newobject()
obj.FIELD_NAME = "Field Name"
setattr(obj, "VARCHAR2$$VALUE", "String Value")
```

**Comment by neilnsmith** [comment]
Excellent.  Thanks for that.
