### ISSUE TITLE
Connect to Remote Oracle DB via Python: DPI-1047: 64-bit Oracle Client library cannot be loaded

### ISSUE THREAD

**Issue by sfinkel5** [oracle/python-cx_Oracle#325]
#### Answer the following questions:

**1. What is your version of Python?** Is it 32-bit or 64-bit?  3.7 64 bit

**2. What is your cx_Oracle version?** 7.2

**3. What *exact* command caused the problem (e.g. what command did you try to install with)?**  **Who were you logged in as?**

Connecting to remote DB. The username/password credentials work in Oracle Client directly.
conn = cx_Oracle.connect(user=username, password= password, dsn=dsn_tns)
<br/>

**4. What error(s) you are seeing?**
<br/>DPI-1047: Cannot locate a 64-bit Oracle Client library: <br/>
"C:\Oracle\product\11.2.0\client_1\bin\oci.dll is not the correct architecture"<br/>

**5. What OS (and version) is Python executing on?**
<br/>Windows 10 64 bit<br/>

**6. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where is it installed?**
<br/>11.2 client<br/>

**8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?**
<br/>C:\Oracle\product\11.2.0\client_1\bin\OCI.dll <br/>

**Other**
<br/>MS Visual C++ 2005 Redistributable is installed <br/>
MS Visual C++ 2005 Redistributable (x64) is installed

**Comment by anthony-tuininga** [comment]
From your error message it looks like you have installed a 32-bit Oracle Client library. You either need to install a 64-bit Oracle Client library or a 32-bit Python. You can't mix and match!

**Comment by cjbj** [comment]
@sfinkel5 for the record, here are the installation instructions: https://cx-oracle.readthedocs.io/en/latest/installation.html#installing-cx-oracle-on-windows

**Comment by sfinkel5** [comment]
Thank you. I downloaded a 64bit client previously, but I think I have multiple Oracle versions on my computer so that was the issue. This made me double check this issue.
