### ISSUE TITLE
cx_Oracle continuous query notification callback function question. Bug or purposeful design?

### ISSUE THREAD

**Issue by ewingian** [oracle/python-cx_Oracle#326]
**What I am using:**
Python 3.7
Oracle 12c
RedHat 6
cx_Oracle 7
oracle_client 11.2.0

**What I am doing:**
My goal is setting up a listener on one of our databases to catch data changes, and handle data changes in various ways. I have created a listener as described in the following document: https://www.oracle.com/technetwork/articles/dsl/python-091105.html.

**My issue:**
My listener handler will perform operations and print notifications for up to 100 events per commit. Beyond 100 events the listener only hits my initial print statement once and does not perform operations beyond that. Is this by design or a bug?
 The listener works great; its performing faster than expected and writing out data to JSON files per event. 

Example: I cant put actual code in due to sensitivity of information, but it is essentially this.
```
import cx_Oracle
def DCNCallback(message): 
    print "Notification:" 
    for tab in message.tables: 
        print "Table:", tab.name
        for row in tab.rows: 
            if row.operation & cx_Oracle.OPCODE_INSERT: 
                - query based on rowid, append to file
            if row.operation & cx_Oracle.OPCODE_UPDATE: 
                -query based on rowid, write to JSON object, then file

con = cx_Oracle.Connection("private@private",
                           events = True) 
subscriptionInsDel = con.subscribe(callback = DCNCallback, 
       operations = cx_Oracle.OPCODE_INSERT | cx_Oracle.OPCODE_UPDATE, 
       rowids = True) 
subscriptionInsDel.registerquery('select * from <a certain table>')
raw_input("Hit Enter to conclude this demo\n") 
```

run 101 updates followed by a single commit and all I receive is Notification and table name.
run 100 or less updates followed by a single commit and I handle all information as expected.
 
Please advise.

Thank you
Ian

**Comment by cjbj** [comment]
I'll ask the CQN team.

**Comment by cjbj** [comment]
And a quick, brief comment from them.  Refer to [DBMS_CQ_NOTIFICATION.SET_ROWID_THRESHOLD](https://docs.oracle.com/en/database/oracle/oracle-database/19/arpls/DBMS_CQ_NOTIFICATION.html#GUID-16A5ABD4-2949-498D-ABE3-98AFF9AF3A5F).

**Comment by anthony-tuininga** [comment]
I can confirm that works using the basic cx_Oracle sample for database change notification. Hope that works for you!

**Comment by ewingian** [comment]
Thank you very much guys, I'll be trying it this week!

**Comment by ewingian** [comment]
worked great!
