### ISSUE TITLE
ORA-12638: Credential retrieval failed Bundling Python( pyQt + cx_Oracle) application using pyinstaller for Windows

### ISSUE THREAD

**Issue by raghav-kukreti** [oracle/python-cx_Oracle#328]
I'm building a GUI application on Windows using pyQt which queries an Oracle database using a connection string such as `username/password@host_ip:port/db_name`. Now when I run the application using `python3 gui.py`, it works, connects to the host and extracts the required information but when I compile it to an exe, it gives me the infamous `ORA-12638`.

I've scoured the interwebs for solutions ie: how to properly package cx_Oracle applications using pyinstaller and have done the following.
1. Add InstantClient and Qt DLLs to the path
2. Create a `tnsnames.ora` in the same folder as the exe

But to no avail.

The program works perfectly when I run it using `python3 gui.py` but somehow breaks when compiled. Am I missing something simple?

Any and all help would be appreciated. If I've left out something, do let me know I'll edit asap.

Thank you.

**Comment by raghav-kukreti** [comment]
Update; I think I wasn't clear above. Should've mentioned something crucial.  Apologies for that.
I have been working with WSL. Now on WSL; python3 gui.py works perfectly but on Windows it gives me `ORA-12638`. The main cause of this what I think is missing paths. 
To fix that I added InstantClient to the path, exactly how I did in Linux. There still seems to be something missing.

**Comment by anthony-tuininga** [comment]
To be clear, you are using "WSL" (Windows Subsystem for Linux)? Are you saying that it works within WSL but when you use a plain Windows command prompt it stops working? There are a number of incompatibilities between WSL and "regular" Windows and you may be running into one of those. Are you setting the environment variable ``TNS_ADMIN`` to point to the location of your ``tnsnames.ora`` file?

**Comment by raghav-kukreti** [comment]
Yes, the thing is all I've done is add InstantClient to path in WSL. Nothing more. 
I did the exact same thing on Windows. Should I set an env variable `TNS_ADMIN`?

**Comment by halfer** [comment]
Cross-posted without declaration here: https://stackoverflow.com/questions/56934760/ora-12638-credential-retrieval-failed-bundling-python-pyqt-cx-oracle-applic

**Comment by raghav-kukreti** [comment]
I did not know, even though it's a better practice and I apologize for this. Thank you for the pointer.

**Comment by anthony-tuininga** [comment]
> Yes, the thing is all I've done is add InstantClient to path in WSL. Nothing more.
I did the exact same thing on Windows. Should I set an env variable TNS_ADMIN?

I would set the environment variable ``TNS_ADMIN`` to see if that addresses your issue. Can you also be clear as to which environment is working and which one is not working? And what you've done in each environment? From what I understand WSL is fairly independent of the main Windows environment.

**Comment by raghav-kukreti** [comment]
I understand the differences between WSL and Windows, that's not the issue. I have done the following.

In WSL : 

1. Added InstantClient to path
2. Installed cx_Oracle using pip

Didn't add any extra environment variable, nothing else to PATH.
This works perfectly.

In Windows : 
1. Added InstantClient to PATH.
2. Installed cx_Oracle

Gives me ORA-12638.

Connecting to the remote DB works from Windows, but cx_Oracle raises the issue.

**Comment by raghav-kukreti** [comment]
Hello all,
thank you for all the help; I fixed it like the following. Guess my Oracle configuration wasn't correct.

In sqlnet.ora I changed the line
`SQLNET.AUTHENTICATION_SERVICES = (NTS)`
to 
`SQLNET.AUTHENTICATION_SERVICES = (NONE)`

**Comment by anthony-tuininga** [comment]
Thanks for following up!
