### ISSUE TITLE
How to user proxy user

### ISSUE THREAD

**Issue by praveenkanamarlapudi** [oracle/python-cx_Oracle#329]
Hi,

This may be a basic question. Can you please share an example for connecting using proxyuser and impersonate to another user while running query using this module?

**Comment by cjbj** [comment]
What's the context?  Pooled?  Non-pooled?  What kind of proxy?  How are the users configured in the DB?

Search the tests for 'proxy'.   At the risk of confusing you, you could also search for 'proxy' in the [node-oracledb documentation](https://oracle.github.io/node-oracledb/doc/api.html).

Here's one cx_Oracle example I have at hand:

For example, to allow a user called myproxy to access the HR schema::

    ALTER USER hr GRANT CONNECT THROUGH myproxy;

The example below demonstrates the usage of Proxy authentication in session pool::

    pool = cx_Oracle.SessionPool(dsn = "myhost.example.com/orclpdb1", homogeneous = False)
    connection = pool.acquire(user = "myproxy[hr]", password = userpwd)

**Comment by cjbj** [comment]
There are some more examples in https://github.com/oracle/python-cx_Oracle/issues/327#issuecomment-511991881
