### ISSUE TITLE
Document testing requirements

### ISSUE THREAD

**Issue by stefanseefeld** [oracle/python-cx_Oracle#33]
Running the test suite via `python setup.py test` appears to require a pre-existing database to work with.
Is there a subset of the tests that don't have that requirement, i.e. that either create and use a temporary database, or that perform some other simple checks just to verify that the build succeeded ?

I couldn't find any test instruction in https://github.com/oracle/python-cx_Oracle/blob/master/README.md or elsewhere.

Thanks,
       Stefan

**Comment by cjbj** [comment]
Did you see https://github.com/oracle/python-cx_Oracle/blob/master/test/SetupTest.sql ?
This creates a dedicated user for testing.

Yes, doc can be improved. Nudge, nudge @anthony-tuininga

**Comment by stefanseefeld** [comment]
It would be great if there was some scripting to set up the test database automatically so the tests could be run in a CI environment.

**Comment by anthony-tuininga** [comment]
Updated documentation and improved setup of objects required for test suite. See https://github.com/oracle/python-cx_Oracle/tree/master/test.
