### ISSUE TITLE
module 'cx_Oracle' has no attribute 'connect'

### ISSUE THREAD

**Issue by dereklee1993** [oracle/python-cx_Oracle#331]
import cx_Oracle as cx
conn=cx.connect(username,password,host)

**Comment by cjbj** [comment]
This is what I get:
```
Traceback (most recent call last):
  File "issue331.py", line 2, in <module>
    conn=cx.connect(username,password,host)
NameError: name 'username' is not defined
```
If I use 'real' values like:
```
import cx_Oracle as cx
conn=cx.connect('cj','cj','mdt.au.oracle.com/orclpdb1')
```
then the script executes without error.

Here are the installation instructions:  https://cx-oracle.readthedocs.io/en/latest/installation.html

If you still have problems, you need to give a LOT more context and information so we can help you.

**Comment by dereklee1993** [comment]
I used 'real' values. I just download cx_Oracle-7.2.0.tar.gz,then Unzip the file ,Put it in the site-packages folder and use it

**Comment by dereklee1993** [comment]
> This is what I get:
> Traceback (most recent call last):
>   File "issue331.py", line 2, in <module>
>     conn=cx.connect(username,password,host)
> NameError: name 'username' is not defined
> 
> If I use 'real' values like:
> import cx_Oracle as cx
> conn=cx.connect('cj','cj','mdt.au.oracle.com/orclpdb1')
> I used 'real' values. I just download cx_Oracle-7.2.0.tar.gz,then Unzip the file ,Put it in the site-packages folder and use it

**Comment by cjbj** [comment]
> I used 'real' values. I just download cx_Oracle-7.2.0.tar.gz,then Unzip the file ,Put it in the site-packages folder and use it

That is just the source code. 

Try installing cx_Oracle with pip just like any other Python package, see the previous link I gave.  Don't forget to install some Oracle Client libraries too.

**Comment by dereklee1993** [comment]
> I used 'real' values. I just download cx_Oracle-7.2.0.tar.gz,then Unzip the file ,Put it in the site-packages folder and use it
> 
> That is just the source code.
> Try installing cx_Oracle with pip just like any other Python package, see the previous link I gave.  Don't forget to install some Oracle Client libraries too.

The problem was solved, thank you very much.

**Comment by Sasikumar-Gunasekaran** [comment]
ckages/gunicorn/util.py", line 350, in import_app      __import__(module)    File "/srv/main.py", line 28, in <module>      cx_Oracle.init_oracle_client(lib_dir=r"/home/jupterbrothersds/Check/instantclient_21_4")  cx_Oracle.DatabaseError: DPI-1047: Cannot locate a 64-bit Oracle Client library: "/home/jupterbrothersds/Check/instantclient_21_4/libclntsh.so: cannot open shared object file: No such file or directory". See https://cx-oracle.readthedocs.io/en/latest/user_guide/installation.html for help


Can someone help?  I am trying to deploy the model in google cloud But am facing the issue no such file directory? I tried all  method but getting error kindly check and help.. How do i mention my library path
