### ISSUE TITLE
Unable to access files under odpi 

### ISSUE THREAD

**Issue by Swathi-Sridhar** [oracle/python-cx_Oracle#338]
Hi,

I'm trying to create an .egg file from this branch and when I download the contents as ZIP, odpi is empty. I faced the same issue with the 6.x version too but in that I was able to separately download the contents of odpi and copy/paste them. I ran into the [symlink issue](https://github.com/oracle/python-cx_Oracle/issues/210) with 6.x and hence, want to move to 7.x. 

I'm unable to open the odpi folder for the 7.x releases. Could you please help me out?

**Comment by anthony-tuininga** [comment]
Hi,

Take a look at the [installation documentation](https://cx-oracle.readthedocs.io/en/latest/installation.html#install-using-github) for installing from GitHub or for installing from the source package found on PyPI. If you download a zip file directly from GitHub it will not contain the ODPI-C source code. You'll need to go to the [ODPI-C GitHub page](https://github.com/oracle/odpi) to acquire a zip file from there and then unzip it within the odpi directory in your cx_Oracle source. I'd suggest one of the first two solutions, though. They are far easier to work with!

**Comment by anthony-tuininga** [comment]
Assuming question has been answered.
