### ISSUE TITLE
gbk codec can't decode byte 0xac in position 4: illegal multibyte sequence

### ISSUE THREAD

**Issue by dingziyang** [oracle/python-cx_Oracle#339]
*Delete unnecessary parts of this template.*

### For security issues:

See https://www.oracle.com/support/assurance/vulnerability-remediation/reporting-security-vulnerabilities.html for how to report security issues.

### For general questions:

Describe exactly what you did and what you want to happen.
Use the questions at the bottom of this template as a guide.

Use Markdown syntax, particularly for code blocks: see https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

### For installation issues:

Use a gist for screen output and logs: see https://gist.github.com/
**Do not paste long output into this issue**

Review your output and logs.  **Google any errors**
Try to install in a different way.  Try some potential solutions.

Review the install instructions at
http://cx-oracle.readthedocs.io/en/latest/installation.html

#### Answer the following questions:

1. What is your version of Python? Is it 32-bit or 64-bit?
  Python3.6.2-x64
2. What is your cx_Oracle version?
  cx-Oracle 7.2
3. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?
sql = 'select * from a_table where age > 22 'd
4. What error(s) you are seeing?
 `gbk codec can't decode byte 0xac in position 4: illegal multibyte sequence`
5. What OS (and version) is Python executing on?
 win10-x64
6. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where is it installed?
instanceclient  is 12_2 x64
7. What is your Oracle Database version?
 12c
8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?
 I am sure my `PATH` is fine!
9. What Oracle environment variables did you set?  How *exactly* did you set them?
 set  `NLS_LANG = AMERICAN_AMERICA.ZHS16GBK`  , and add it into PATH
10. Do you have a small, single Python script that immediately runs to show us the problem?
 No, this is a new OS I installed,   just one version of python in my pc. 
10. Problem Description
 I used cx-Oracle by `import cx_Oracle` in *.py, I got the oracle connection and run a select sql and **fetchall()**,  If the returned rows are few like 10000, it`s worked! But, If there are a lot of rows returned like 1 billion,  
I got the Exception : `gbk codec can't decode byte 0xac in position 4: illegal multibyte sequence`.

------

I don`t know why, help please!

**Comment by cjbj** [comment]
If some rows can be queried, but not others then it sounds like you have corrupt data. See `encodingErrors` in https://github.com/oracle/python-cx_Oracle/issues/162#issuecomment-398476948

Also check https://github.com/oracle/python-cx_Oracle/search?q=codec+can%27t+decode+byte&type=Issues

Instead of using NLS_LANG, it is easier & safer to set the character set in the `encoding` parameter at connection:

```
connection = cx_Oracle.connect("hr", userpwd, "dbhost.example.com/orclpdb1", encoding="ZHS16GBK")
```

**Comment by anthony-tuininga** [comment]
It might be helpful to know what the database character set is, too:

```sql
select property_name, property_value
from database_properties
where property_name in ('NLS_CHARACTERSET', 'NLS_NCHAR_CHARACTERSET')
```

Depending on the value, it might be wiser to use a universal character set, as in:

```python
connection = cx_Oracle.connect(userName, password, dsn, encoding="UTF-8",
        nencoding="UTF-8")
```

**Comment by dingziyang** [comment]
@anthony-tuininga I did what you said, it`s worked! thanks.
