### ISSUE TITLE
Python cx_Oracle error “DPI-1047: Cannot locate a 32-bit Oracle Client” #Python #Oracle

### ISSUE THREAD

**Issue by ulfahartinam** [oracle/python-cx_Oracle#340]
I have errors my code program I use Python 3.6.5(32 bit), cx_Oracle 7.2.1, And my OS windows 10(64 bit), how to fix it this error? 
this is my message erros:

  File "D:\bisa.py", line 3, in <module>
    con= cx_Oracle.connect('db_employees/root@localhost/orcl')
cx_Oracle.DatabaseError: DPI-1047: Cannot locate a 32-bit Oracle Client library: "C:\oraclexe\app\oracle\product\11.2.0\server\bin\oci.dll is not the correct architecture". See https://oracle.github.io/odpi/doc/installation.html#windows for help

I have installed the Oracle instant client 64 bits and 32 bits but still have errors

This is picture installed in 32 bit
![image](https://user-images.githubusercontent.com/49228909/62110859-8a553c80-b2d9-11e9-930f-d2c7239ed3c8.png)

this is picture installed in 64 bit
![image](https://user-images.githubusercontent.com/49228909/62110900-9ccf7600-b2d9-11e9-9d44-f007826aeae6.png)

**Comment by cjbj** [comment]
> DPI-1047: Cannot locate a 32-bit Oracle Client library: "C:\oraclexe\app\oracle\product\11.2.0\server\bin\oci.dll is not the correct architecture"

This is not Instant Client.  This is XE. (There is a newer XE, by the way, but that isn't relevant to your problem).

Your PATH is not set to the right thing at the right time.   You may need to set it differently each time you run Python, perhaps in a batch file.

Review https://cx-oracle.readthedocs.io/en/latest/installation.html#installing-cx-oracle-on-windows and https://cx-oracle.readthedocs.io/en/latest/installation.html#troubleshooting

You may find it easiest to install a 64-bit Python so it can immediately use the 64-bit Oracle XE libraries.

**Comment by ulfahartinam** [comment]
this is my PATH:

![image](https://user-images.githubusercontent.com/49228909/62115614-e7a1bb80-b2e2-11e9-9c25-906b9b5bc645.png)

**Comment by ulfahartinam** [comment]
This is worked, I need restart my computer and running again, thank you for help me.
