### ISSUE TITLE
Error: DPI-1047 using Instant Client on macOS Catalina 10.15

### ISSUE THREAD

**Issue by nchillal** [oracle/python-cx_Oracle#341]
I recently upgrade my mac to Mac OS Catalina Beta version. After that cx-Oracle is not working. Fails with error message below. 

cx_Oracle.DatabaseError: DPI-1047: Cannot locate a 64-bit Oracle Client library: "dlopen(libclntsh.dylib, 1): image not found". See https://oracle.github.io/odpi/doc/installation.html#macos for help

_Version_
Python 3.7.4
cx-Oracle 7.2.0

This looks to me due to Apple dropping support of 32-bit apps. Can you confirm?

**Comment by anthony-tuininga** [comment]
Did you install a 64-bit Oracle Instant Client? If you were running a 32-bit Python installation before the upgrade, the answer is probably no. :-) You'll need to do that, especially if macOS no longer has a 32-bit Python installation available for you to use! And 64-bit is a good idea in any case!

**Comment by nchillal** [comment]
Yes i did install 64-bit client. I have also reinstall just to make sure using below link.

https://download.oracle.com/otn/mac/instantclient/181000/instantclient-basic-macos.x64-18.1.0.0.0.zip

W.r.t python its 64-bit. 

I have following under ~/lib

libclntsh.dylib.18.1 -> ${HOME}/Downloads/instantclient_18_1/libclntsh.dylib.18.1
libclntshcore.dylib.18.1 -> ${HOME}/Downloads/instantclient_18_1/libclntshcore.dylib.18.1
libons.dylib -> ${HOME}/Downloads/instantclient_18_1/libons.dylib
libnnz18.dylib -> ${HOME}/Downloads/instantclient_18_1/libnnz18.dylib
libociei.dylib -> ${HOME}/Downloads/instantclient_18_1/libociei.dylib

<img width="532" alt="Screen Shot 2019-08-01 at 11 17 38 AM" src="https://user-images.githubusercontent.com/12175246/62317656-f7d6a980-b44e-11e9-8a49-33c2e0505965.png">

Note: everything was working fine before upgrading to mac os catalina.

**Comment by anthony-tuininga** [comment]
I don't own a machine running macOS, so I can't help directly. Perhaps @cjbj who does own a machine running macOS can help more.

Did you look at the cx_Oracle [installation documentation](https://cx-oracle.readthedocs.io/en/latest/installation.html#installing-cx-oracle-on-macos)? Take note of the first paragraph in that section.

**Comment by nchillal** [comment]
Yes i have followed installation documention. It worked before i installed Mac OS Catalina.

**Comment by cjbj** [comment]
Which Python are you actually using?  What is the output of `which python` ?

**Comment by nchillal** [comment]
I use python3. I don't use the built python version. Python3 is installed by homebrew package. 

➜ brew list python
/usr/local/Cellar/python/3.7.4/bin/2to3
/usr/local/Cellar/python/3.7.4/bin/2to3-3.7
/usr/local/Cellar/python/3.7.4/bin/easy_install-3.7
/usr/local/Cellar/python/3.7.4/bin/idle3
/usr/local/Cellar/python/3.7.4/bin/idle3.7
/usr/local/Cellar/python/3.7.4/bin/pip3
/usr/local/Cellar/python/3.7.4/bin/pip3.7
/usr/local/Cellar/python/3.7.4/bin/pydoc3
/usr/local/Cellar/python/3.7.4/bin/pydoc3.7
/usr/local/Cellar/python/3.7.4/bin/python3
/usr/local/Cellar/python/3.7.4/bin/python3-config
/usr/local/Cellar/python/3.7.4/bin/python3.7
/usr/local/Cellar/python/3.7.4/bin/python3.7-config
/usr/local/Cellar/python/3.7.4/bin/python3.7m
/usr/local/Cellar/python/3.7.4/bin/python3.7m-config
/usr/local/Cellar/python/3.7.4/bin/pyvenv
/usr/local/Cellar/python/3.7.4/bin/pyvenv-3.7
/usr/local/Cellar/python/3.7.4/bin/wheel3
/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/ (2914 files)
/usr/local/Cellar/python/3.7.4/IDLE 3.app/Contents/ (8 files)
/usr/local/Cellar/python/3.7.4/lib/pkgconfig/ (3 files)
/usr/local/Cellar/python/3.7.4/libexec/bin/ (7 files)
/usr/local/Cellar/python/3.7.4/libexec/pip/ (699 files)
/usr/local/Cellar/python/3.7.4/libexec/setuptools/ (346 files)
/usr/local/Cellar/python/3.7.4/libexec/wheel/ (38 files)
/usr/local/Cellar/python/3.7.4/Python Launcher 3.app/Contents/ (16 files)
/usr/local/Cellar/python/3.7.4/share/man/ (2 files)

**Comment by cjbj** [comment]
What does `which python` show or how do you know you are running the brew python?

Does SQL*Plus work?

**Comment by nchillal** [comment]
➜ head -1 $HOME/my_script.py
#!/usr/bin/env python3

➜ which python
/usr/bin/python

Note: This was working before in Mac OS Mojave after i upgrade to Mac OS Catalina Beta its not working.

**Comment by cjbj** [comment]
Does SQL*Plus work?  There have been several macOS versions in the past that broke Oracle client tools.

**Comment by cjbj** [comment]
Reading the message buried the screenshot (reminder to everyone: don't use screenshots!) It rang a bell with:
 - https://www.reddit.com/r/virtualbox/comments/bjwwvd/virtualbox_in_macos_mojave_10145_beta_4/
- https://forums.virtualbox.org/viewtopic.php?f=8&t=84092&p=448559#p448559

I don't have any other info at the moment specific to Instant Client.

**Comment by nchillal** [comment]
> Does SQL*Plus work? There have been several macOS versions in the past that broke Oracle client tools.

I have not tried it. Will try and let you know.

**Comment by cjbj** [comment]
Hmm. Notarization: https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution

**Comment by nchillal** [comment]
Latest release of catalina has fixed this issue.

**Comment by cjbj** [comment]
@nchillal thanks for checking.

**Comment by rrezino** [comment]
> Latest release of catalina has fixed this issue.

it's not solved, I have the final version and of Catalina, cx-oracle and instant client and it's not working

**Comment by cjbj** [comment]
@rrezino sorry to hear that.  What version of Instant Client did you try?

For various reasons, the group looking after the macOS Instant Client were not able to test pre-release Catalina before they shipped Instant Client 19.3 (so this is officially supported on Mojave and  High Sierra, as noted in the install instructions).  I understand any extra certification (notarization?) or packaging changes isn't going to be soon, and involves more than technical considerations.

**Comment by rrezino** [comment]
Mac = Catalina
Oracle instant client = 19.3
Cx_oracle = 7.2.3

**Comment by kindjacket** [comment]
Yep getting this too

**Comment by cjbj** [comment]
What a pain.  We had something similar back in the 11 timeframe when Apple broke compatibility. To be straightforward, I'm told there won't be any rebuilt/updated IC packages in the near term.  Start looking for workarounds.  I've yet to get my hands on Catalina.

**Comment by kindjacket** [comment]
<img width="427" alt="image" src="https://user-images.githubusercontent.com/7778402/66614354-997c2480-eb7d-11e9-9791-e818e0be051a.png">
I have the same setup as @rrezino.
OS = Catalina 10.15 (19A583)
Oracle instant client = 19.3
Cx_oracle = 7.2.3

**Comment by kindjacket** [comment]
@cjbj - this is a nightmare right now. Do you want me to raise a separate issue?

**Comment by NathanAtSafe** [comment]
I ran into the same issue with the 19.1 client, but downgrading to an older client (I tried 12.1) worked after trusting each lib in System Preferences.

**Comment by cjbj** [comment]
@kindjacket I'll just reopen this issue.  You should contact your Oracle sales contacts to let them know too.

**Comment by kindjacket** [comment]
yeah the app needs to notarized. Instructions here - https://developer.apple.com/documentation/xcode/notarizing_your_app_before_distribution/customizing_the_notarization_workflow?language=objc#3087734

**Comment by kindjacket** [comment]
I've found a workaround (based on this answer here - https://github.com/Jackett/Jackett/issues/5589#issuecomment-508560798). It's not pretty.. You have to manually set the quarantine flag the dylib

First you need to run this -
`xattr -p com.apple.quarantine libclntsh.dylib`

That should return something like this -
`0081;5d1bec70;Safari;0622FF31-4499-4EBA-954A-EDC879E4010A`

You then need to run the below code.  With the return string from above but replacing 0081 with 00c1
`xattr -w com.apple.quarantine "00c1;5d1bec70;Safari;0622FF31-4499-4EBA-954A-EDC879E4010A" *.dylib`

The real fix, however, is Oracle notarizing the instant client.

**Comment by chkeno** [comment]
A workaround I found when prompted with "...cannot be opened opened because the developer cannot be verified" is to navigate to Security & Privacy -> General. There, you should see the file you were just told you cannot open listed and an "Open anyway" button. https://support.apple.com/el-gr/guide/mac-help/mh40616/mac

I had to repeat this about 4 times for 4 different files, but my oracle instant client is now working fine.

**Comment by cjbj** [comment]
@chkeno Good info.

I'm not sure when I will be able to upgrade to Catalina to test it all myself.  There are other (3rd party) tools I need that also aren't yet supported on it.

**Comment by cawoodjm** [comment]
I had a similar with Catalina, trying to delete the oracle libs, but resolved the issue running the following line in terminal, sudo spctl --master-disable. Apparently Oracle is not classified as an approved developer and MacOS gets upset when you try to run a py script against the libs. Hope this helps.

**Comment by pdelporte** [comment]
> I've found a workaround (based on this answer here - [Jackett/Jackett#5589 (comment)](https://github.com/Jackett/Jackett/issues/5589#issuecomment-508560798)). It's not pretty.. You have to manually set the quarantine flag the dylib
> 
> First you need to run this -
> `xattr -p com.apple.quarantine libclntsh.dylib`
> 
> That should return something like this -
> `0081;5d1bec70;Safari;0622FF31-4499-4EBA-954A-EDC879E4010A`
> 
> You then need to run the below code. With the return string from above but replacing 0081 with 00c1
> 
> ```
> xattr -w com.apple.quarantine "00c1;5d1bec70;Safari;0622FF31-4499-4EBA-954A-EDC879E4010A" *.dylib
> ```
> 
> The real fix, however, is Oracle notarizing the instant client.

I had also to do 
`xattr -w com.apple.quarantine "00c1;5da44079;Opera;B38C0F6F-252F-4CC7-8A2D-236BAD20C035" *.dylib.*`

And now everything works perfectly. Thx.

**Comment by anthony-tuininga** [comment]
Thanks for sharing.

**Comment by Behrad3d** [comment]
> A workaround I found when prompted with "...cannot be opened opened because the developer cannot be verified" is to navigate to Security & Privacy -> General. There, you should see the file you were just told you cannot open listed and an "Open anyway" button. https://support.apple.com/el-gr/guide/mac-help/mh40616/mac
> 
> I had to repeat this about 4 times for 4 different files, but my oracle instant client is now working fine.

This was actually a quick easy fix for me. Tried several times (4 or 5 times) and then it is working fine now.

**Comment by dales** [comment]
I forced mac to "open the files" in iTerm, it asked for confirmation for opening the files. after saying yes to all the files it worked

**Comment by hugoabe** [comment]
I managed to solve the problem using the link:
https://support.apple.com/el-gr/guide/mac-help/mh40616/mac

**Comment by Sdcrow** [comment]
> > A workaround I found when prompted with "...cannot be opened opened because the developer cannot be verified" is to navigate to Security & Privacy -> General. There, you should see the file you were just told you cannot open listed and an "Open anyway" button. https://support.apple.com/el-gr/guide/mac-help/mh40616/mac
> > I had to repeat this about 4 times for 4 different files, but my oracle instant client is now working fine.
> 
> This was actually a quick easy fix for me. Tried several times (4 or 5 times) and then it is working fine now.

This worked for me too. Had to retry severally but it finally worked

**Comment by taoruifu** [comment]
xattr: libclntsh.dylib: No such xattr: com.apple.quarantine

**Comment by cjbj** [comment]
@taoruifu is that a statement or a question?

**Comment by akurnosov** [comment]
I have been disable sip in my macos catalina.
Its worked for me.

**Comment by appersonj** [comment]
I would do it this way:

To test:
` ls lib*.dylib | while read f ; do   n=$(xattr -p com.apple.quarantine $f | perl -pe "s/00c1/0081/");  echo  xattr -w com.apple.quarantine $n $f;  done
`

To actually perform:
`
 ls lib*.dylib | while read f ; do   n=$(xattr -p com.apple.quarantine $f | perl -pe "s/00c1/0081/"); echo "F: $f, N:$n";  xattr -w com.apple.quarantine $n $f;  done
`

To verify:
xattr -p com.apple.quarantine lib*.dylib

**Comment by jseabold** [comment]
None of these workarounds seem to work for me on 10.15.2. Are there plans from Oracle to get the clients notarized? As of right now, I can't connect to our Oracle databases, and I'm not wild about moving everything to docker.

**Comment by cjbj** [comment]
It's a known request, but no ETA.

**Comment by OraDanGus** [comment]
Hi,
I am facing the same question.
My High Sierra "server" holding Oracle 12c on Oracle Linux 7.4 as a guest of VirtualBox uses Instant Oracle Client 12.2 et cx_Oracle 7.3 for Python 3.7 and Anaconda 1.9.12.

It's running without any problem.
Today I tried with an extra MacBook Pro 15 2017 running Catalina to prepare a specific setup of everything I need and I have already seen potential "issues" with Python 3.8 have installed too quickly ... (still need to replace it by 3.7.x (?) more stable and compliant with Oracle too... so I stop and need to think.
I'lll come back in the future with more details ...
Keep in touch
Daniel

**Comment by uf-kelvin-low** [comment]
> It's a known request, but no ETA.

Are we able to follow up the request somewhere?

**Comment by cjbj** [comment]
@ufkl contacting your Oracle sales rep / account manager would be one way.

**Comment by OraDanGus** [comment]
Hi, I have installed Oracle Instant Client 18.1 on Catalina and it's working perfectly with sqlplus connection.
A nice youtube guy published he own installation here:
https://www.youtube.com/watch?v=2btVupGXRtM

I am continuing with Python and cx_Oracle ... 1) select the right version as I am using a 12c release 1...
Cheers

**Comment by giaca95** [comment]
Hi,
I installed the Oracle Instant Client version 19.3 on my Mac Os Catalina version 10.15.4
But i still have the same error:
Origine: (cx_Oracle.DatabaseError) DPI-1047: Cannot locate a 64-bit Oracle Client library: "dlopen(libclntsh.dylib, 1): no suitable image found.  Did find:
        file system relative paths not allowed in hardened programs". See https://oracle.github.io/odpi/doc/installation.html#macos for help
(Background on this error at: http://sqlalche.me/e/4xp6)

hear my installation:
$: ls-l ~/lib
ls -l ~/lib 
total 0
lrwxr-xr-x  1 giacomocallegaro  staff  58 22 Apr 09:13 libclntsh.dylib -> /Users/giacomocallegaro/instantclient_19_3/libclntsh.dylib

$: cat .zprofile

# Setting PATH for Python 3.8
# The original version is saved in .zprofile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.8/bin:${PATH}"
export PATH

# Setting PATH for Python 3.7
# The original version is saved in .zprofile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.7/bin:${PATH}"
export PATH=$PATH:~/instantclient_19_3
export PATH

$: echo $PATH

/Users/giacomocallegaro/.nvm/versions/node/v12.14.1/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Library/Apple/usr/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/giacomocallegaro/.nvm/versions/node/v12.16.1/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/opt/openssl/bin:/Users/giacomocallegaro/instantclient_19_3:/Users/giacomocallegaro/instantclient_19_3


$: which python:
/usr/bin/python

when I run sqlplus:

$: sqlplus -v

SQL*Plus: Release 19.0.0.0.0 - Production
Version 19.3.0.0.0

Do someone have the same problem?

**Comment by ufkl** [comment]
> Hi,
> I installed the Oracle Instant Client version 19.3 on my Mac Os Catalina version 10.15.4
> But i still have the same error:
> Origine: (cx_Oracle.DatabaseError) DPI-1047: Cannot locate a 64-bit Oracle Client library: "dlopen(libclntsh.dylib, 1): no suitable image found. Did find:
> file system relative paths not allowed in hardened programs". See https://oracle.github.io/odpi/doc/installation.html#macos for help
> (Background on this error at: http://sqlalche.me/e/4xp6)
> 
> hear my installation:
> $: ls-l ~/lib
> ls -l ~/lib
> total 0
> lrwxr-xr-x 1 giacomocallegaro staff 58 22 Apr 09:13 libclntsh.dylib -> /Users/giacomocallegaro/instantclient_19_3/libclntsh.dylib
> 
> $: cat .zprofile
> 
> # Setting PATH for Python 3.8
> # The original version is saved in .zprofile.pysave
> PATH="/Library/Frameworks/Python.framework/Versions/3.8/bin:${PATH}"
> export PATH
> 
> # Setting PATH for Python 3.7
> # The original version is saved in .zprofile.pysave
> PATH="/Library/Frameworks/Python.framework/Versions/3.7/bin:${PATH}"
> export PATH=$PATH:~/instantclient_19_3
> export PATH
> 
> $: echo $PATH
> 
> /Users/giacomocallegaro/.nvm/versions/node/v12.14.1/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Library/Apple/usr/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/giacomocallegaro/.nvm/versions/node/v12.16.1/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/opt/openssl/bin:/Users/giacomocallegaro/instantclient_19_3:/Users/giacomocallegaro/instantclient_19_3
> 
> $: which python:
> /usr/bin/python
> 
> when I run sqlplus:
> 
> $: sqlplus -v
> 
> SQL*Plus: Release 19.0.0.0.0 - Production
> Version 19.3.0.0.0
> 
> Do someone have the same problem?

According to @cjbj & the download page (around the bottom page of https://www.oracle.com/database/technologies/instant-client/macos-intel-x86-downloads.html), Oracle Instant Client is not yet supporting MacOS Catalina.

**Comment by casperle** [comment]
@kindjacket @cjbj 
Hi guys,
allowing to run apps downloaded from anywhere helped me fix the issue with this
![image](https://user-images.githubusercontent.com/8900497/81182777-8fed5a80-8fae-11ea-8f7a-b246579f0ddc.png)

Here you can find how to change your settings: https://www.imore.com/how-open-apps-anywhere-macos-catalina-and-mojave

**Comment by reybis** [comment]
All you need to do, before install everything type in terminal:
`sudo spctl --master-disable`
maybe you will have to go to System Preferences and set the correct security selection:
![Screen Shot 2020-05-06 at 20 46 15](https://user-images.githubusercontent.com/790392/81242320-cfca3700-8fda-11ea-81a9-97ec92fd37da.png)
and after that install **Oracle Instant Client**

**Comment by koobitor** [comment]
> Hi,
> I installed the Oracle Instant Client version 19.3 on my Mac Os Catalina version 10.15.4
> But i still have the same error:
> Origine: (cx_Oracle.DatabaseError) DPI-1047: Cannot locate a 64-bit Oracle Client library: "dlopen(libclntsh.dylib, 1): no suitable image found. Did find:
> file system relative paths not allowed in hardened programs". See https://oracle.github.io/odpi/doc/installation.html#macos for help
> (Background on this error at: http://sqlalche.me/e/4xp6)
> 
> hear my installation:
> $: ls-l ~/lib
> ls -l ~/lib
> total 0
> lrwxr-xr-x 1 giacomocallegaro staff 58 22 Apr 09:13 libclntsh.dylib -> /Users/giacomocallegaro/instantclient_19_3/libclntsh.dylib
> 
> $: cat .zprofile
> 
> # Setting PATH for Python 3.8
> # The original version is saved in .zprofile.pysave
> PATH="/Library/Frameworks/Python.framework/Versions/3.8/bin:${PATH}"
> export PATH
> 
> # Setting PATH for Python 3.7
> # The original version is saved in .zprofile.pysave
> PATH="/Library/Frameworks/Python.framework/Versions/3.7/bin:${PATH}"
> export PATH=$PATH:~/instantclient_19_3
> export PATH
> 
> $: echo $PATH
> 
> /Users/giacomocallegaro/.nvm/versions/node/v12.14.1/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Library/Apple/usr/bin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/giacomocallegaro/.nvm/versions/node/v12.16.1/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/opt/openssl/bin:/Users/giacomocallegaro/instantclient_19_3:/Users/giacomocallegaro/instantclient_19_3
> 
> $: which python:
> /usr/bin/python
> 
> when I run sqlplus:
> 
> $: sqlplus -v
> 
> SQL*Plus: Release 19.0.0.0.0 - Production
> Version 19.3.0.0.0
> 
> Do someone have the same problem?

I also got the same problem with your it just happen after i install 10.15.4.

**Comment by ideal22** [comment]
Hello!
I have also the same problem. Is anybody solved this issue? Would be glad, if smb helped me. I've tried everything even 18.1, 12.2 oracle client, but did not work.

Mac: Catalina
Version: 10.15.5

**Comment by cjbj** [comment]
Tried adding the Instant Client directory to the DYLD_LIBRARY_PATH environment variable?  It might help.  The users of the node-oracledb driver have found it helps them on Catalina.  But it would only help if you set the variable in the process/shell that directly invokes Python.

Also look at the current master branch and try out the new `init_oracle_client()` method, see the development documentation at https://github.com/oracle/python-cx_Oracle/blob/master/doc/src/user_guide/initialization.rst  The instructions [here](https://cx-oracle.readthedocs.io/en/latest/user_guide/installation.html#install-using-github) show how to compile & install from the GitHub source code.

**Comment by ideal22** [comment]
1. Step One is done:  export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:~/lib
2. I am new user of mac, just 3 weeks ago switched from windows to mac, I have some problems while installing from github:
    
python3 system.py install, while entering this command, i got an error:
/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/dist.py:475: UserWarning: Normalizing '8.0.0-dev' to '8.0.0.dev0'
  normalized_version,
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 2] No such file or directory: '/Library/Python/3.7/site-packages/test-easy-install-65425.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /Library/Python/3.7/site-packages/

This directory does not currently exist.  Please create it and try again, or
choose a different installation directory (using the -d or --install-dir
option).

**Comment by cjbj** [comment]
Step me through it. Where did you install Python from?

**Comment by ideal22** [comment]
I installed from https://www.python.org/downloads/mac-osx/

**Comment by ideal22** [comment]
Is there any problem Python?

**Comment by cjbj** [comment]
On Catlina with Python 3.8.3 from https://www.python.org/downloads/mac-osx/, perhaps the easiest thing to do is set DYLD_LIBRARY_PATH to your Instant Client directory.  I tested with cx_Oracle 7.3 and Instant Client 19.3.  Note that the environment variable won't propagate to sub-shells, so you need to set the environment variable in each terminal or process that starts Python.   With cx_Oracle 8 you can also use the new `cx_Oracle.init_oracle_client()` function - check the [dev doc](https://github.com/oracle/python-cx_Oracle/blob/master/doc/src/user_guide/initialization.rst).  To get over your directory error, perhaps try `python3 system.py install --user`. Keep an eye on where all the `cx_Oracle.cpython-38-darwin.so` files get installed in case you need to manually clean some up.

I could not see a way to get the system installed Python 3.7 to work.

**Comment by cjbj** [comment]
Here's a solution:

Update to cx_Oracle 8 and add something like this to your scripts:

    import platform

    if platform.platform()[:6] == 'Darwin':
	cx_Oracle.init_oracle_client(lib_dir="/Users/yourname/instantclient_19_3")

Other alternatives are discussed in the [cx_Oracle 8 Installation guide](https://cx-oracle.readthedocs.io/en/latest/user_guide/installation.html#installing-cx-oracle-on-macos) and the new [cx_Oracle 8 Initialization](https://cx-oracle.readthedocs.io/en/latest/user_guide/initialization.html) documentation.

For example, the file:
```
import sys
import os
import platform
import cx_Oracle

if platform.platform()[:6] == 'Darwin':
    cx_Oracle.init_oracle_client(lib_dir="/Users/cjones/instantclient_19_3")

print("- platform.platform:      ", platform.platform())
print("- sys.maxsize > 2**32:    ", sys.maxsize > 2**32)
print("- platform.python_version:", platform.python_version())

print("- cx_Oracle.version:      ", cx_Oracle.version)
print("- cx_Oracle.clientversion:", cx_Oracle.clientversion())

connection = cx_Oracle.Connection(os.environ.get("PYTHON_USERNAME"), os.environ.get("PYTHON_PASSWORD"), os.environ.get("PYTHON_CONNECTSTRING"))

print("- DB version:             ", connection.version)
print("- encoding:               ", connection.encoding)
print("- nenecoding:             ", connection.nencoding)
```
gives this for me:
```
- platform.platform:       Darwin-18.7.0-x86_64-i386-64bit
- sys.maxsize > 2**32:     True
- platform.python_version: 3.7.7
- cx_Oracle.version:       8.0.0
- cx_Oracle.clientversion: (19, 3, 0, 0, 0)
- DB version:              19.3.0.0.0
- encoding:                UTF-8
- nenecoding:              UTF-8

```

**Comment by ideal22** [comment]
I did all the steps. I installed cx_Oracle `python3 -m pip install cx_Oracle --upgrade --user` 
`nodir@MacBook-Pro-3 ~ % cd ./Library/Python/3.8/lib/python/site-packages 
  nodir@MacBook-Pro-3 site-packages % ls
  cx_Oracle-8.0.0-py3.8.egg-info	cx_Oracle.cpython-38-darwin.so	libclntsh.dylib`

Then, I run the code, It gives for me an error:
`nodir@MacBook-Pro-3 ~ % python3 test.py 
- platform.platform:       macOS-10.15.5-x86_64-i386-64bit
- sys.maxsize > 2**32:     True
- platform.python_version: 3.8.3
- cx_Oracle.version:       8.0.0
- cx_Oracle.clientversion: (19, 3, 0, 0, 0)
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    connection = cx_Oracle.Connection(os.environ.get("PYTHON_USERNAME"), os.environ.get("PYTHON_PASSWORD"), os.environ.get("PYTHON_CONNECTSTRING"))
cx_Oracle.DatabaseError: ORA-12162: TNS:net service name is incorrectly specified`

**Comment by cjbj** [comment]
That's a completely different problem.  Your install and configuration were fine.  Do some research into your connect string format.  Here's some doc that will help: https://cx-oracle.readthedocs.io/en/latest/user_guide/connection_handling.html#connection-strings

Open a new issue instead of posting to this one.  Thanks!

**Comment by rushramia** [comment]
SOLUTION:
I had this same problem after upgrading to Catalina.  The network admin at my company mentioned it was the Apple malware gatekeeper protection system in Catalina.  He suggested trying following command:

`sudo xattr -d com.apple.quarantine /path/to/library`

I had to run this for all of the oracle client libraries, so my commands looked like this
`sudo xattr -d com.apple.quarantine /usr/local/lib/libclntsh.dylib.19.1
sudo xattr -d com.apple.quarantine /usr/local/lib/libnnz19.dylib
sudo xattr -d com.apple.quarantine /usr/local/lib/libclntshcore.dylib.19.1
sudo xattr -d com.apple.quarantine /usr/local/lib/libociicus.dylib`

Hope this helps!

**Comment by gpietro** [comment]
Same problem with BigSur...
I think @Oracle here should do some work to make the library trustable by Apple OS...

**Comment by cjbj** [comment]
@gpietro Instant Client 19.8 DMGs are notarized so you shouldn't see a problem.  

https://blogs.oracle.com/opal/notarized-macos-oracle-instant-client-packages-make-installation-easier

https://cx-oracle.readthedocs.io/en/latest/user_guide/installation.html#install-oracle-instant-client
