### ISSUE TITLE
Oracle database connection error

### ISSUE THREAD

**Issue by selims54** [oracle/python-cx_Oracle#346]
1. What is your version of Python? Is it 32-bit or 64-bit?
Python 64 bit 
2. What is your cx_Oracle version?
7.1.3
3. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?
>>> dsn_tns = cx_Oracle.makedsn("localhost", PORT, sid="SID")
>>> conn = cx_Oracle.connect(user=r'username', password='pass', dsn=dsn_tns)

4. What error(s) you are seeing?
Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    conn = cx_Oracle.connect(user=r'---', password='---', dsn=dsn_tns)

cx_Oracle.DatabaseError: ORA-01804: failure to initialize timezone information
5. What OS (and version) is Python executing on?
Windows 7 64 bit
6. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where is it installed?
Oracle Client 12.0.1 64 but
7. What is your Oracle Database version?
10.2
8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?
$ORACLE_HOME/bin:$PATH

9. What Oracle environment variables did you set?  How *exactly* did you set them?
ORACLE_HOME =C:\FAST\Oracle_Base\product\12.1.0\client
TNS_ADMIN = $ORACLE_HOME/network/admin
LD_LIBRARY_PATH = $ORACLE_HOME/lib
ORA_TZFILE = $ORACLE_HOME/oracore/zoneinfo/timezdif.csv
PATH = $ORACLE_HOME/bin:$PATH
CLASSPATH = C:\FAST\Oracle_Base\product\12.1.0\client\jdk\bin\java

10. Do you have a small, single Python script that immediately runs to show us the problem?
>>> import cx_Oracle
>>> dsn_tns = cx_Oracle.makedsn("localhost", PORT, sid="SID")
>>> conn = cx_Oracle.connect(user=r'username', password='pass', dsn=dsn_tns)

I am trying to connect to database that is located in our server. I am having error about the initialization timezone information like below.
cx_Oracle.DatabaseError: ORA-01804: failure to initialize timezone information

**Comment by anthony-tuininga** [comment]
That error generally implies some sort of configuration issue. I there a reason you set the environment variable ``ORA_TZFILE``? If I set that environment variable to the value you specified I get the same error.

**Comment by selims54** [comment]
There is no specific reason for that. But even though I remove that variable I am having the same problem.

**Comment by anthony-tuininga** [comment]
You're very welcome.

**Comment by zaid894** [comment]
how do I find this variable in windows ? I have the same issue connecting to nodejs?

**Comment by zaid894** [comment]
> That error generally implies some sort of configuration issue. Is there a reason you set the environment variable `ORA_TZFILE`? If I set that environment variable to the value you specified I get the same error.

kindly help me

**Comment by anthony-tuininga** [comment]
If you have a similar error and this issue didn't help you, please create a new one and answer the information requested in the template. Thanks!
