### ISSUE TITLE
How to fix 'ORA-19011' error in Python cx_Oracle

### ISSUE THREAD

**Issue by KimHyeongGoo** [oracle/python-cx_Oracle#348]
HI~ I want to queryLONG_STRING data from Oracle db with cx_Oracle, but it doesn't work with Ora-19011 error message. I think size of query data is larger than string buffer, but i don't know how to solve this problem

Oracle DB is an external DB and it's not my own DB, So i can't access directly. Therefore, I want to fix my problem on my code and print query data on python terminal.

#### Answer the following questions:

1. What is your version of Python? Is it 32-bit or 64-bit? python 2.7 64bit

2. What is your cx_Oracle version? cx_oracle 7.2.2

3. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?
```console
Traceback (most recent call last): File "./test1.py", line 19, in <module>                                                                                for record in curs:                                                                                              
cx_Oracle.DatabaseError: ORA-19011: String buffer too small
```
4. What error(s) you are seeing? ORA-19011

5. What OS (and version) is Python executing on? Ubuntu 18.04.2 LTS(Linux)

6. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where is it installed?  oracle-instant client 19.3 64bit

10. Do you have a small, single Python script that immediately runs to show us the problem?
```python
conn = cx_Oracle.connect('id/passwd@ip:port/orcl')
print(conn.version)

curs = conn.cursor()
curs.execute('SELECT * FROM tablename')

for record in curs: #error occured
    print(record) 
```

**Comment by anthony-tuininga** [comment]
Can you provide a set of SQL statements that create the table and populate it with some data that demonstrates the problem?

**Comment by KimHyeongGoo** [comment]
> Can you provide a set of SQL statements that create the table and populate it with some data that demonstrates the problem?

Thanks for comment. The DB is not mine. So i can't know SQL_statements that create the table..
Can't this problem be fixed without SQL_statement that create the table??
When i got description of cursor while connetion to table, i got  [('COL_name', <type 'cx_Oracle.LONG_STRING'>, None, None, None, None, 1)] .

**Comment by cjbj** [comment]
This looks XML-ish so review the documentation about fetching XML: https://cx-oracle.readthedocs.io/en/latest/user_guide/xml_data_type.html

If that doesn't help then:
- Do a DESCRIBE on the table in SQL*Plus or SQL Developer to show us the DB column types.
- give us a Python example with SQL statement that has the problem.

**Comment by KimHyeongGoo** [comment]
Thanks!! I solve the problem.

**Comment by KimHyeongGoo** [comment]
> This looks XML-ish so review the documentation about fetching XML: https://cx-oracle.readthedocs.io/en/latest/user_guide/xml_data_type.html
> 
> If that doesn't help then:
> 
> * Do a DESCRIBE on the table in SQL*Plus or SQL Developer to show us the DB column types.
> * give us a Python example with SQL statement that has the problem.

Thank you! I solve the problem.
As you guessed, it's XML data. And i changed sql statement, data was printed in console.
Here is code i changed :
curs.execute("SELECT xmltype.getclobval(SYS_NC_ROWINFO$) FROM XDB.XDB$COMPLEX_TYPE")
for record in curs:
    print(record[0].read())

**Comment by cjbj** [comment]
If each SYS_NC_ROWINFO$ item is < 1GB, then consider using https://cx-oracle.readthedocs.io/en/latest/user_guide/lob_data.html#fetching-lobs-as-strings-and-bytes if your Python process can handle the memory requirements.  It will be faster than using `.read()`.
