### ISSUE TITLE
Broken date value handling

### ISSUE THREAD

**Issue by Dronablo** [oracle/python-cx_Oracle#35]
Dear Anthony
I have some old DB, which contains broken DATE values, with invalid format.
It looks like this:

Query:
```
SELECT
    r.request_id,
    usr_actual_start_date date_date,
    TO_CHAR(
        w.usr_actual_start_date,
        'DD.MM.YYYY HH24:MI:SS'
    ) char_date,
    dump(usr_actual_start_date) dump_date
FROM
    requests r
```
Oracle SQL Developer with JDBC driver:
![](https://habrastorage.org/web/6da/071/4ba/6da0714baf104c9ab2061be9b7f65018.png)
sqlplus from the latest instant client:
![](https://habrastorage.org/web/074/513/a20/074513a20780482f97343c5949636ce2.png)

As you can see, for request_id=46541 it returns different values for date, but they are near.

But if I try to get this data through cx_Oracle it throws "ValueError: hour must be between 0..23".

Don't you think that it'll be more user-firendly or more expected to get behaviour like SQL Developer or sqlplus?

Thank you!

Regards,
Andrey

**Comment by cjbj** [comment]
Can you post the version info indicated in the [issue template ](https://github.com/oracle/python-cx_Oracle/blob/master/.github/issue_template.md).

**Comment by Dronablo** [comment]
It's reproducible in 
Python 3.6.1 Windows x64 + cx_Oracle 5.3
Python 3.6.1 Windows x64 + cx_Oracle 6.02b
Python 3.6.1 Linux x64 + cx_Oracle 5.3

It's partially reproducible in:
Python 2.6.6 Linux x64 + cx_Oracle 5.1.2
It returns datetime.datetime(2008,11,1,255,0) which, in turn, leads to
```
str(res[1]) ==> '2008-11-01 255:00:00'
res[1].strftime('%d') ==> 'ValueError: hour out of range'
res[1].strftime('%Y') ==> 'ValueError: hour out of range'
```

If you guys decide to fix it somehow I could export this broken value through exp/expdp to help you play with it in-house. 
In fact I face such a broken values from time to time - some (unknown) old version of jdbc drivers cause such a values for some period of time about 5-7 years ago, and they are still reside in some systems.

**Comment by anthony-tuininga** [comment]
You can provide the data and I'll see if the problem can be resolved easily enough -- but is there a reason why you don't correct the data? That would seem to be the best solution!

**Comment by Dronablo** [comment]
Here is DataPump dump:
[bad_date.dmp.zip](https://github.com/oracle/python-cx_Oracle/files/1078792/bad_date.dmp.zip)
You should remap schema from ANDY to some existing one.

Reasons of not fixing date in DB are pretty simple: it's a surprise every time and it's not a single case.

**Comment by cjbj** [comment]
I'm really not in favour of hiding corrupt data.  That could lead to all sorts of strange things happening, and waste a lot of people's time.

**Comment by Dronablo** [comment]
There are two facts: we could not fix it in thousands DBs and we want to be able to get at least 'nearly accurate' data from that cells. Anyway, I don't even try to ask to fix cx_Oracle behavior, I just want to know would it be like JDBC and sqlplus or not.

**Comment by anthony-tuininga** [comment]
One last suggestion: use a PL/SQL function to adjust the data or have it converted to string and manipulated in Python. In any case, as Chris mentioned, the driver shouldn't hide corrupt data. It should get fixed in the database, if possible, but failing that, a site specific solution such as the ones I mentioned are going to be your best bet!
