### ISSUE TITLE
'utf-8' codec can't decode byte 0xe8

### ISSUE THREAD

**Issue by Rapiiidooo** [oracle/python-cx_Oracle#356]
1. What is your version of Python? Is it 32-bit or 64-bit?
Python3.7.1 - 32-bit

2. What is your cx_Oracle version?
From pip3 install - 32-bit I suppose 

3. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?

```
import cx_Oracle

dsn_tns = cx_Oracle.makedsn('localhost', '1526', sid='xxx')

with cx_Oracle.connect(dsn=dsn_tns, user='xxx', password='xxx', encoding='UTF-8', nencoding='UTF-8') as con:
    print('succes')
```
same error as :
```
import cx_Oracle

dsn_tns = cx_Oracle.makedsn('localhost', '1526', sid='xxx')

with cx_Oracle.connect(dsn=dsn_tns, user='xxx', password='xxx') as con:
    print('succes')
```

4. What error(s) you are seeing?
```
File "TESTORACLE.py", line 13, in <module>
    with cx_Oracle.connect(dsn=dsn_tns, user='xxx', password='xxx', encoding='UTF-8', nencoding='UTF-8') as con:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 122: invalid continuation byte
```

5. What OS (and version) is Python executing on?
AIX-7 64 bits

6. Oracle version ?
oracle12

I tried switch NLS_LANG to UTF8 but it doesnt change anything.
Actually I don't understand whitch file can not be decoded ?

**Comment by anthony-tuininga** [comment]
I don't have access to AIX but in theory it should work the same as other platforms! You can set the environment variable ``DPI_DEBUG_LEVEL`` to the value 12 and report back what it says. That will tell us what calls are being made and any errors that are being reported.

**Comment by Rapiiidooo** [comment]
I tried DPI_DEBUG_LEVEL=12 and DPI_DEBUG_LEVEL=31 but I get the exact same message error.

**Comment by anthony-tuininga** [comment]
Setting the environment variable will not change the error message. It should produce logging messages to stderr which may be helpful to diagnose the issue.

**Comment by Rapiiidooo** [comment]
Oh my bad I didn't know it.

Anyway I tried and the logging messages was the same one.
Any other idea ?

**Comment by cjbj** [comment]
How exactly did you set NLS_LANG?   

Can you connect with SQL*Plus with NLS_LANG set to ".AL32UTF8" (with the leading full stop)?

**Comment by Rapiiidooo** [comment]
The NLS_LANG is set in .profile. And it is already set to ".AL32UTF8".

**Comment by cjbj** [comment]
So, can you connect with SQL*Plus?

**Comment by Rapiiidooo** [comment]
```
xxx:/xxx> sqlplus xxx/xxx

SQL*Plus: Release 12.2.0.1.0 Production on Jeu. Sept. 12 09:51:51 2019

Copyright (c) 1982, 2017, Oracle.  All rights reserved.

Connecté à :
Oracle Database 12c Standard Edition Release 12.2.0.1.0 - 64bit Production

SQL> select DECODE(parameter, 'NLS_CHARACTERSET', 'CHARACTER SET',
  2  'NLS_LANGUAGE', 'LANGUAGE',
  3  'NLS_TERRITORY', 'TERRITORY') name,
  4  value from v$nls_parameters
  5  WHERE parameter IN ( 'NLS_CHARACTERSET', 'NLS_LANGUAGE', 'NLS_TERRITORY');

NAME
---------------------------------------
VALUE
--------------------------------------------------------------------------------
LANGUAGE
FRENCH

TERRITORY
FRANCE

CHARACTER SET
WE8ISO8859P1


SQL> exit
Déconnecté de Oracle Database 12c Standard Edition Release 12.2.0.1.0 - 64bit Production
xxx:/xxx> echo $NLS_LANG
FRENCH_FRANCE.AL32UTF8
```

**Comment by cjbj** [comment]
How are you going with this?  I had hoped you would test SQL\*Plus using the same set of Oracle client libraries that Python was using.   And make sure you invoke Python and SQL\*Plus from the same shell so they both inherit the same set of environment variables.  Since you have language issues, check all character set and locale settings on the system that you are having problems with.

**Comment by Rapiiidooo** [comment]
I'm actually giving up ... I'll try to compile python 64 bit from source but I need a new environnement of aix because a can not risk to break the dev env. This is taking while because there are others more important stuff to do now...
Yes I'm sure I was invoking they both from the same shell then they have the same var env. But the oracle base was configured 20 years ago in WE8ISO8859P1 and I can not change that without impacts.
All characters and locale settings are set to FRENCH_FRANCE.WE8ISO8859P1 or AMERICAN_AMERICA.WE8ISO8859P1. I tried to change it without success.

**Comment by anthony-tuininga** [comment]
If you set the environment variable ``NLS_LANG`` to the value ``FRENCH_FRANCE.WE8ISO8859P1`` then the value of ``connection.encoding`` and ``connection.nencoding`` will be ``ISO-8859-1`` -- assuming you don't pass anything to the ``encoding`` and ``nencoding`` parameters. If that's what you need, go ahead and use that.

Not that it is quite possible for the declared character set (encoding) to not actually match the stored character set (encoding) as happened in issue #263. Take a look at that and see if that fits your situation.

**Comment by anthony-tuininga** [comment]
I'm assuming we've answered your questions. If not, please re-open.
