### ISSUE TITLE
Can not fetch all records from Oracle table

### ISSUE THREAD

**Issue by 86mm86** [oracle/python-cx_Oracle#357]
Hi!

I am trying to retrieve 300k records from an Oracle table with 119 columns.
I can easily connect to the database but when I try to fetch the records I get only ca. half of them. Surprisingly: 

1) I do not receive any error message;
2) upon re-executing the following Python script 

```
import cx_Oracle
import pandas as pd

sql_query = 'select * from ...'

con = cx_Oracle.connect(user='...', password='...', dsn='...')

df = pd.read_sql(sql_query, con)

df.shape[0]
```
I do not get the same number of records (that is, I get different values for `df.shape[0]`).

Any clue on what the problem might be?

Here are some possibly useful info:

1. What is your version of Python? Is it 32-bit or 64-bit?
Python 3.7.0 64-bit

2. What is your cx_Oracle version?
7.2.2

4. What error(s) you are seeing?
None

5. What OS (and version) is Python executing on?
Windows 10

7. What is your Oracle Database version?
Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production

9. What Oracle environment variables did you set?  How *exactly* did you set them?
None

**Comment by cjbj** [comment]
Start by simplifying the testcase and removing all use of Pandas. Can you query the data using pure cx_Oracle?

**Comment by cjbj** [comment]
Give numbers.  What data sizes are we talking about?   How do you check the amount of memory?  What version of the Oracle Client libraries are you using?

**Comment by 86mm86** [comment]
Data size: 300k rows * 119 columns

Memory is checked just via task manager while running the script above

Oracle Client Version: 11.2.0.4.0

**Comment by cjbj** [comment]
Details matter.

Show us the output of a select count(*) from the table and the value of num_rows.

**Comment by 86mm86** [comment]
I have just realized this issue has nothing to do with cx_Oracle. There was a typo in a WHERE clause of my select statement. Indeed details matter! :)
