### ISSUE TITLE
The installation link isn't working

### ISSUE THREAD

**Issue by cc13com** [oracle/python-cx_Oracle#359]
Hello,

the installation link on the page isn't working.

br

**Comment by cjbj** [comment]
On https://github.com/oracle/python-cx_Oracle?  I just pushed the updated URL.
If you meant on any other page, let us know which page.

**Comment by cc13com** [comment]
looks good, thx

**Comment by cc13com** [comment]
cc

**Comment by cjbj** [comment]
@cc13com Thanks for reporting it.
