### ISSUE TITLE
how set cx_Oracle.connect timeout

### ISSUE THREAD

**Issue by 984958198** [oracle/python-cx_Oracle#361]
linux is set sqlnet.ora,  How to configure on windows?

windows 7 x64
python2.7
cx_Oracle version = '7.2.2'
instantclient-basic-windows.x64-11.2.0.4.0.zip

**Comment by anthony-tuininga** [comment]
The simplest approach is to create a directory and put sqlnet.ora in that directory, then set the environment variable ``TNS_ADMIN`` to point to that directory. Newer versions of the instant client will create the ``network/admin`` subdirectory and you can put sqlnet.ora in that directory instead and not have to set the environment variable.

**Comment by cjbj** [comment]
For people coming across this thread, config file location is documented in https://cx-oracle.readthedocs.io/en/latest/user_guide/connection_handling.html#optional-oracle-net-configuration-files

You can manually create the subdirectory instantclient_11_2/network/admin and put the files there.

For connection timeout parameters, consider [SQLNET.OUTBOUND_CONNECT_TIMEOUT](https://docs.oracle.com/en/database/oracle/oracle-database/19/netrf/parameters-for-the-sqlnet.ora.html#GUID-0857C817-675F-4CF0-BFBB-C3667F119176) or [TCP.CONNECT_TIMEOUT](https://docs.oracle.com/en/database/oracle/oracle-database/19/netrf/parameters-for-the-sqlnet.ora.html#GUID-A51F20BC-6493-49A5-A022-D4FBA1905AE5).
