### ISSUE TITLE
cx_Oracle Slides from the Oracle OpenWorld Conference

### ISSUE THREAD

**Issue by cjbj** [oracle/python-cx_Oracle#364]
Here are slide decks from the recent Oracle OpenWorld Conference. Check them out!

- [Python: The New Favorite Programming Environment for Oracle Database Applications](https://static.rainfocus.com/oracle/oow19/sess/1553560228118001VfFb/PF/DEV4624-Python-The-New-Favorite-Programming-Environment-for-Oracle-Database-Applications_1568841067658001o5D5.pdf)
- [Scalability and High Availability for Oracle Database Python Applications](https://static.rainfocus.com/oracle/oow19/sess/155356052830600180DE/PF/DEV4625-Scalability-and-High-Availability-for-Oracle-Database-Python-Applications_1568931704636001Qx1H.pdf)
- [Developing and Deploying Python and Node.js Applications in Docker](https://static.rainfocus.com/oracle/oow19/sess/1553560683840001mfXq/PF/DEV4626-Developing-and-Deploying-Python-and-Node.js-Applications-in-Docker_1568845042122001Vsfl.pdf)

**Comment by PRSantos-BR** [comment]
This documents is "Show de bola!".

**Comment by PRSantos-BR** [comment]
Python: The New FavoriteProgramming Environment for Oracle Database Applications[DEV4624]

Error in sheet 23.

Unresolved reference '**### cur**' 

Fetching Numbers as Decimals
defhandler(cursor, name, defaultType, size, precision, scale):
if defaultType== cx_Oracle.NUMBER:
return cursor.var(decimal.Decimal,
arraysize=cursor.arraysize)
cursor.outputtypehandler= handler
for value, in ### **cur**.execute("select Data from DecimalTab"):
print("Value:", value, "* 3 =", value * 3)

**Comment by cjbj** [comment]
Thanks for the attention to detail.  The actual doc looks OK https://cx-oracle.readthedocs.io/en/latest/user_guide/sql_execution.html#fetched-number-precision
