### ISSUE TITLE
how cx_Oracle.connect transfer zhs16gbk to utf-8

### ISSUE THREAD

**Issue by peakjun** [oracle/python-cx_Oracle#368]
*Delete unnecessary parts of this template.*

### For security issues:

See https://www.oracle.com/support/assurance/vulnerability-remediation/reporting-security-vulnerabilities.html for how to report security issues.

### For general questions:

Describe exactly what you did and what you want to happen.
Use the questions at the bottom of this template as a guide.

Use Markdown syntax, particularly for code blocks: see https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

#### Answer the following questions:

1. What is your version of Python? Is it 32-bit or 64-bit?
3.7.3 64bit
2. What is your cx_Oracle version?
7.1.3
3. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?

4. What error(s) you are seeing?

5. What OS (and version) is Python executing on?
Red Hat Enterprice Linux Server release 7.3(Maipo)

6. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where is it installed?
instantclient_18_3

7. What is your Oracle Database version?
10g

8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?
~/.local/lib/instantclient_18_3 on Linux

9. What Oracle environment variables did you set?  How *exactly* did you set them?
export NLS_LANG=.zhs16gbk

10. Do you have a small, single Python script that immediately runs to show us the problem?
My Oracle database NLS_CHARACTERSET = zhs16gbk 
If database have € , I load it from database using utf-8. And I want to write it to file using gbk, then errors occured.
```
-- sql 
create table Test (customer_id, varchar(200));
insert into Test values('€');
```
```
import cx_Oracle
connection = cx_Oracle.connect('')
cursor = connection.cursor()
cursor.execute("select * from Test")
customer_id = cursor.fetchone()[0]
with open('test', 'w', encoding='gbk') as f:
   f.write(customer_id)
```

**Comment by cjbj** [comment]
> then errors occured.

What errors?

Oracle globalization documentation indicates that  zhs16gbk doesn't support the euro symbol, see table A-4 in [Character Sets](https://docs.oracle.com/en/database/oracle/oracle-database/19/nlspg/appendix-A-locale-data.html#GUID-9529D1B5-7366-4195-94B5-0F90F3B472E1):

> 

Asian | ZHS16GBK | GBK 16-bit Simplified Chinese | MB, ASCII, UDC
-- | -- | -- | --


The key for the comment column of the character set tables is:

SB: single-byte encoding
MB: multibyte encoding
FIXED: fixed-width multibyte encoding
ASCII: strict superset of ASCII
EURO: euro symbol supported
UDC: user-defined characters supported

**Comment by peakjun** [comment]
Thanks for your help！

**Comment by peakjun** [comment]
My purpose is load data from database and write it to file. Using the same encoding.

My Oracle Database NLS_CHARACTERSET = zhs16gbk
When I create a connection to oracle, I use 
`connection = cx_Oracle.connect('dbuse/dbpass@dbtns', encoding='utf-8')`, 
and I can't use encoding='zhs16gbk', it is not supported. So I use encoding=utf-8, and it works.

Then load data from database and the data encoding utf-8 in memory.  In database, the data is encoded zhs16gbk. When load the data , how it transfer the data from zhs16gbk to utf-8?

I want write the data to file encode zhs16gbk. When I use
`with open ('test', 'w', encoding='zhs16gbk'` then error occured.
erros is "LookupError: unknown encoding: zhs16gbk".
I don't want to write to file using utf-8. 
If I use encoding='gbk' or 'gb2312' or 'gb18030', it doesn't work. 
erros is "Unicode encodeError: 'gbk' codec can't encode character '\u20ac' in positon 33: illegal multiibyte sequeence. "
\u20ac is € euro symbol. 
Euro symbol can insert to database , I tested it.
How should I do?

**Comment by anthony-tuininga** [comment]
I am not familiar with all of the intricacies involved in the various encodings, but it would seem that euro symbol (\u20ac) cannot be encoded using ``gbk``. See [this StackOverflow question](https://stackoverflow.com/questions/23998776/euro-symbol-in-gbk-encoded-chinese-language-page) for details. You will need to pick a different encoding if you want to encode the euro symbol.

**Comment by anthony-tuininga** [comment]
It looks like the encoding ``GB18030`` does encode the euro symbol and is a superset of ``gbk``` so might work for you? See [this Wikipedia page](https://en.wikipedia.org/wiki/GB_18030) for more details.

**Comment by peakjun** [comment]
It works.
Thanks
