### ISSUE TITLE
Error Installing cx_Oracle

### ISSUE THREAD

**Issue by Moataz-E** [oracle/python-cx_Oracle#37]
**OS:** Windows 7 64-bit
**cx_Oracle Version:** 5.3
**Oracle Database:**  Oracle Database 11g Enterprise Edition Release 11.2.0.3.0 - 64bit Production
**Oracle Instant Client:** 12.2.0.1.0

>Processing h:\work\code\serapis\dist\serapis-0.0.1.dev1-py2.py3-none-any.whl
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (from serapis==0.0.1.dev1)
Collecting cx-Oracle (from serapis==0.0.1.dev1)
  Using cached cx_Oracle-5.3.tar.gz
Requirement already satisfied: numpy in c:\programdata\anaconda3\lib\site-packages (from serapis==0.0.1.dev1)
Requirement already satisfied: python-dateutil>=2 in c:\programdata\anaconda3\lib\site-packages (from pandas->serapis==0.0.1.dev1)
Requirement already satisfied: pytz>=2011k in c:\programdata\anaconda3\lib\site-packages (from pandas->serapis==0.0.1.dev1)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2->pandas->serapis==0.0.1.dev1)
Building wheels for collected packages: cx-Oracle
  Running setup.py bdist_wheel for cx-Oracle: started
  Running setup.py bdist_wheel for cx-Oracle: finished with status 'error'
  Complete output from command C:\ProgramData\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\elmasm\\AppData\\Local\\Temp\\pip-build-xsy0ez73\\cx-Oracle\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\elmasm\AppData\Local\Temp\tmppmpw2e99pip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_ext
  building 'cx_Oracle' extension
  creating build
  creating build\temp.win-amd64-3.6-11g
  creating build\temp.win-amd64-3.6-11g\Release
  creating build\temp.win-amd64-3.6-11g\Release\src
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\oracle\ora11g_r2\oci\include -IC:\oracle\ora11g_r2\rdbms\demo -IC:\ProgramData\Anaconda3\include -IC:\ProgramData\Anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\winrt" -IC:\Sybase\OCS-15_0\include /Tcsrc/cx_Oracle.c /Fobuild\temp.win-amd64-3.6-11g\Release\src/cx_Oracle.obj -DBUILD_VERSION=5.3
  cx_Oracle.c
  c:\users\elmasm\appdata\local\temp\pip-build-xsy0ez73\cx-oracle\src\Connection.c(685): warning C4244: 'function': conversion from 'Py_ssize_t' to 'ub4', possible loss of data
  c:\users\elmasm\appdata\local\temp\pip-build-xsy0ez73\cx-oracle\src\Connection.c(697): warning C4244: 'function': conversion from 'Py_ssize_t' to 'ub4', possible loss of data
  c:\users\elmasm\appdata\local\temp\pip-build-xsy0ez73\cx-oracle\src\Connection.c(709): warning C4244: 'function': conversion from 'Py_ssize_t' to 'ub4', possible loss of data
  creating C:\Users\elmasm\AppData\Local\Temp\pip-build-xsy0ez73\cx-Oracle\build\lib.win-amd64-3.6-11g
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\oracle\ora11g_r2\bin /LIBPATH:C:\oracle\ora11g_r2 /LIBPATH:C:\oracle\ora11g_r2\oci\lib\msvc /LIBPATH:C:\oracle\ora11g_r2\sdk\lib\msvc /LIBPATH:C:\ProgramData\Anaconda3\libs /LIBPATH:C:\ProgramData\Anaconda3\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.15063.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.15063.0\um\x64" /LIBPATH:C:\Sybase\DataAccess64\ADONET\dll /LIBPATH:C:\Sybase\DataAccess\ADONET\dll /LIBPATH:C:\Sybase\OCS-15_0\lib oci.lib /EXPORT:PyInit_cx_Oracle build\temp.win-amd64-3.6-11g\Release\src/cx_Oracle.obj /OUT:build\lib.win-amd64-3.6-11g\cx_Oracle.cp36-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.6-11g\Release\src\cx_Oracle.cp36-win_amd64.lib
  cx_Oracle.obj : warning LNK4197: export 'PyInit_cx_Oracle' specified multiple times; using first specification
     Creating library build\temp.win-amd64-3.6-11g\Release\src\cx_Oracle.cp36-win_amd64.lib and object build\temp.win-amd64-3.6-11g\Release\src\cx_Oracle.cp36-win_amd64.exp
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCILobGetChunkSize
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIStmtExecute
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCILobFileClose
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIObjectPin
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIEnvNlsCreate
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIRawSize
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCITransCommit
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCITableNext
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIErrorGet
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIDescribeAny
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCILobTrim
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIPing
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIDescriptorFree
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCILobFreeTemporary
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCISubscriptionRegister
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIObjectNew
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCINumberToText
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCINlsCharSetNameToId
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCISessionPoolCreate
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIRawAssignBytes
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCISessionEnd
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCITransRollback
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCILobGetLength2
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIIterNext
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIHandleFree
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIObjectGetAttr
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIDateTimeConstruct
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCILobFileGetName
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIObjectSetAttr
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCISessionRelease
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCITransStart
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCITableLast
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIBindByPos
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIServerAttach
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIObjectFree
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCILobFileSetName
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCICollAssignElem
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIDBShutdown
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIObjectCopy
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIAQDeq
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIBindByName
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCISessionGet
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIAttrGet
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIRawResize
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIDescriptorAlloc
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCITablePrev
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCILobIsOpen
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCILobRead2
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCILobWrite2
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCINumberToInt
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIDateTimeGetDate
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCINumberFromText
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIEnvCreate
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIStmtGetBindInfo
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIStmtPrepare
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCISubscriptionUnRegister
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIStmtPrepare2
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCILobFileOpen
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIBindObject
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCISessionBegin
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCITableExists
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCILobClose
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIHandleAlloc
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIDefineByPos
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCINlsNameMap
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCILobOpen
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIServerDetach
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIDBStartup
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCINumberFromInt
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIStringPtr
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIParamGet
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIDefineObject
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIObjectUnpin
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCILobIsTemporary
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIIntervalGetDaySecond
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIClientVersion
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCINumberFromReal
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCINlsNumericInfoGet
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIAQEnq
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCINlsCharSetIdToName
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIPasswordChange
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIIterCreate
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIStmtFetch2
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCITransPrepare
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIIntervalSetDaySecond
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIAttrSet
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCITableDelete
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCISessionPoolDestroy
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIStringResize
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCINumberToReal
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCICollGetElem
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIStmtRelease
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCILobCreateTemporary
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCICollSize
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIDateTimeGetTime
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCITableFirst
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCILobFileExists
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCICollTrim
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIDateTimeCheck
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIStringAssignText
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIBreak
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIStringSize
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIObjectGetInd
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIRawPtr
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCILobTrim2
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCIIterDelete
  cx_Oracle.obj : error LNK2001: unresolved external symbol OCICollAppend
  build\lib.win-amd64-3.6-11g\cx_Oracle.cp36-win_amd64.pyd : fatal error LNK1120: 107 unresolved externals
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1120
 ----------------------------------------
 >Running setup.py clean for cx-Oracle
Failed to build cx-Oracle
Installing collected packages: cx-Oracle, serapis
  Running setup.py install for cx-Oracle: started
    Running setup.py install for cx-Oracle: finished with status 'error'
    Complete output from command C:\ProgramData\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\elmasm\\AppData\\Local\\Temp\\pip-build-xsy0ez73\\cx-Oracle\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\elmasm\AppData\Local\Temp\pip-x3sctwha-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'cx_Oracle' extension
    creating build
    creating build\temp.win-amd64-3.6-11g
    creating build\temp.win-amd64-3.6-11g\Release
    creating build\temp.win-amd64-3.6-11g\Release\src
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\oracle\ora11g_r2\oci\include -IC:\oracle\ora11g_r2\rdbms\demo -IC:\ProgramData\Anaconda3\include -IC:\ProgramData\Anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\winrt" -IC:\Sybase\OCS-15_0\include /Tcsrc/cx_Oracle.c /Fobuild\temp.win-amd64-3.6-11g\Release\src/cx_Oracle.obj -DBUILD_VERSION=5.3
    cx_Oracle.c
    c:\users\elmasm\appdata\local\temp\pip-build-xsy0ez73\cx-oracle\src\Connection.c(685): warning C4244: 'function': conversion from 'Py_ssize_t' to 'ub4', possible loss of data
    c:\users\elmasm\appdata\local\temp\pip-build-xsy0ez73\cx-oracle\src\Connection.c(697): warning C4244: 'function': conversion from 'Py_ssize_t' to 'ub4', possible loss of data
    c:\users\elmasm\appdata\local\temp\pip-build-xsy0ez73\cx-oracle\src\Connection.c(709): warning C4244: 'function': conversion from 'Py_ssize_t' to 'ub4', possible loss of data
    creating C:\Users\elmasm\AppData\Local\Temp\pip-build-xsy0ez73\cx-Oracle\build\lib.win-amd64-3.6-11g
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\oracle\ora11g_r2\bin /LIBPATH:C:\oracle\ora11g_r2 /LIBPATH:C:\oracle\ora11g_r2\oci\lib\msvc /LIBPATH:C:\oracle\ora11g_r2\sdk\lib\msvc /LIBPATH:C:\ProgramData\Anaconda3\libs /LIBPATH:C:\ProgramData\Anaconda3\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.15063.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.15063.0\um\x64" /LIBPATH:C:\Sybase\DataAccess64\ADONET\dll /LIBPATH:C:\Sybase\DataAccess\ADONET\dll /LIBPATH:C:\Sybase\OCS-15_0\lib oci.lib /EXPORT:PyInit_cx_Oracle build\temp.win-amd64-3.6-11g\Release\src/cx_Oracle.obj /OUT:build\lib.win-amd64-3.6-11g\cx_Oracle.cp36-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.6-11g\Release\src\cx_Oracle.cp36-win_amd64.lib
    cx_Oracle.obj : warning LNK4197: export 'PyInit_cx_Oracle' specified multiple times; using first specification
       Creating library build\temp.win-amd64-3.6-11g\Release\src\cx_Oracle.cp36-win_amd64.lib and object build\temp.win-amd64-3.6-11g\Release\src\cx_Oracle.cp36-win_amd64.exp
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCILobGetChunkSize
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIStmtExecute
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCILobFileClose
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIObjectPin
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIEnvNlsCreate
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIRawSize
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCITransCommit
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCITableNext
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIErrorGet
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIDescribeAny
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCILobTrim
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIPing
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIDescriptorFree
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCILobFreeTemporary
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCISubscriptionRegister
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIObjectNew
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCINumberToText
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCINlsCharSetNameToId
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCISessionPoolCreate
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIRawAssignBytes
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCISessionEnd
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCITransRollback
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCILobGetLength2
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIIterNext
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIHandleFree
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIObjectGetAttr
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIDateTimeConstruct
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCILobFileGetName
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIObjectSetAttr
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCISessionRelease
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCITransStart
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCITableLast
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIBindByPos
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIServerAttach
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIObjectFree
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCILobFileSetName
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCICollAssignElem
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIDBShutdown
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIObjectCopy
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIAQDeq
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIBindByName
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCISessionGet
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIAttrGet
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIRawResize
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIDescriptorAlloc
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCITablePrev
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCILobIsOpen
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCILobRead2
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCILobWrite2
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCINumberToInt
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIDateTimeGetDate
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCINumberFromText
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIEnvCreate
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIStmtGetBindInfo
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIStmtPrepare
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCISubscriptionUnRegister
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIStmtPrepare2
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCILobFileOpen
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIBindObject
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCISessionBegin
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCITableExists
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCILobClose
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIHandleAlloc
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIDefineByPos
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCINlsNameMap
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCILobOpen
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIServerDetach
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIDBStartup
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCINumberFromInt
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIStringPtr
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIParamGet
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIDefineObject
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIObjectUnpin
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCILobIsTemporary
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIIntervalGetDaySecond
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIClientVersion
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCINumberFromReal
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCINlsNumericInfoGet
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIAQEnq
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCINlsCharSetIdToName
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIPasswordChange
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIIterCreate
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIStmtFetch2
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCITransPrepare
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIIntervalSetDaySecond
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIAttrSet
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCITableDelete
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCISessionPoolDestroy
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIStringResize
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCINumberToReal
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCICollGetElem
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIStmtRelease
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCILobCreateTemporary
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCICollSize
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIDateTimeGetTime
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCITableFirst
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCILobFileExists
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCICollTrim
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIDateTimeCheck
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIStringAssignText
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIBreak
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIStringSize
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIObjectGetInd
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIRawPtr
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCILobTrim2
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCIIterDelete
    cx_Oracle.obj : error LNK2001: unresolved external symbol OCICollAppend
    build\lib.win-amd64-3.6-11g\cx_Oracle.cp36-win_amd64.pyd : fatal error LNK1120: 107 unresolved externals
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1120
    
    ----------------------------------------

**Comment by anthony-tuininga** [comment]
Those errors suggest that you may have a mixing of 32-bit and 64-bit? Python appears to be 64-bit so you need to make sure that your Oracle client is also 64-bit.

Another possibility is to use a pre-compiled version which you can get from [PyPI](https://pypi.python.org/pypi/cx_Oracle/5.3). Make sure you get the 64-bit version for the version of the Oracle client you are using. Or you can use the beta which is even easier to install (and handles the selection of the correct binary package automatically).

`python -m pip install cx_Oracle --pre`

**Comment by anthony-tuininga** [comment]
Closing due to lack of feedback.
