### ISSUE TITLE
cannot fetch all rows 

### ISSUE THREAD

**Issue by aliya1303** [oracle/python-cx_Oracle#370]
Good morning!

I have an issue with querying data from Oracle using Python. The thing is that the data is cutting somewhere. 

The problem occurs while executing following code:

```
import sqlalchemy as db
import pandas as pd
import cx_Oracle

engine = db.create_engine("oracle+cx_oracle://{user}:{pw}@{host}:{port}/{db}"
.format(user = "usr",
pw = "pwd",
host = "host",
port = "port",
db = "db"), encoding='utf8', echo=True)

metadata = db.MetaData()
connection = engine.connect()

connection.execute("ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS' NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS.FF'")

data = "select * from big_view"
df = pd.read_sql(data, connection)

print(df.shape)

connection.close()
```

Instead of geting 2 mil rows i get only about 200k rows.
We also created an issue in sqlalchemy library's repository : [issue](https://github.com/sqlalchemy/sqlalchemy/issues/4985)

Could you please help me to find out the solution?

**Comment by cjbj** [comment]
When I see "all rows" and "millions" in the same sentence I immediately think that you have run out of memory.  Google for how to work with large datasets in Pandas.

If you have a testcase that doesn't use Pandas (since this issue tracker is not for Pandas), let us know.

**Comment by aliya1303** [comment]
Thank you for answering me,

I tried to use only cx_Oracle, but it does not help. The following code also returns 200k rows instead of 2m:
```
import cx_Oracle 

dsn_tns = cx_Oracle.makedsn('host', 'port', service_name='service_name') 
conn = cx_Oracle.connect(user='user', password='pwd', dsn=dsn_tns) 

cur = conn.cursor()
cur.arraysize = 10000
cur.execute("ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS' NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS.FF'")
cur.execute("select count(*) from cxfocus_data")
df = []
for row in cur:
    df.append(row)

print(df)

conn.close()
```

What shoul i do to get all data?
Select from view in Sql developer returns about 2 m rows.

**Comment by cjbj** [comment]
Check you are connecting to the same DB and user as used by SQLDeveloper. As I said on the other issue, if `select count(*)` gives you 200K, then you only have 200K rows.

I'm going to close this issue. We can followup on the [other one](https://github.com/sqlalchemy/sqlalchemy/issues/4985).
