### ISSUE TITLE
Version number of cx_Oracle at runtime

### ISSUE THREAD

**Issue by walter-weinmann** [oracle/python-cx_Oracle#371]
It would be nice if you could get the cx_Oracle version number, e.g. v7.2.3 for documentation purposes at runtime.

**Comment by cjbj** [comment]
Like [cx_Oracle.version](https://cx-oracle.readthedocs.io/en/latest/api_manual/module.html#cx_Oracle.version) ?

**Comment by walter-weinmann** [comment]
This would be fine.

**Comment by cjbj** [comment]
I'm glad your problem is solved.  

You can also use [`cx_Oracle.clientversion()`](https://cx-oracle.readthedocs.io/en/latest/api_manual/module.html#cx_Oracle.clientversion) if you want to know what Oracle client libraries you have.

**Comment by cjbj** [comment]
And, for completeness to help future readers, the attribute I always have to look up due to the non-descriptive name, is [`Connection.version`](https://cx-oracle.readthedocs.io/en/latest/api_manual/connection.html#Connection.version) which gives the database version.
