### ISSUE TITLE
cx_oracle installation error

### ISSUE THREAD

**Issue by marjava** [oracle/python-cx_Oracle#373]
I am getting an error while installtion the cx_oracle in my windows 10 
python version 3.8 (win32)
oracle client 12.0
 this error i am getting while installing 
please note i am new to Python
error log

 WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x048CDC40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/cx-oracle/
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x048CD958>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/cx-oracle/
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x048CD8E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/cx-oracle/
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x048CD868>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/cx-oracle/
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x048CD088>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/cx-oracle/
  ERROR: Could not find a version that satisfies the requirement cx_Oracle (from versions: none)
ERROR: No matching distribution found for cx_Oracle

I have tried adding the proxy server also but getting this error after
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 404 Not Found'))': /simple/cx-oracle/
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 404 Not Found'))': /simple/cx-oracle/
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 404 Not Found'))': /simple/cx-oracle/
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 404 Not Found'))': /simple/cx-oracle/
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 404 Not Found'))': /simple/cx-oracle/
  ERROR: Could not find a version that satisfies the requirement cx_Oracle (from versions: none)
ERROR: No matching distribution found for cx_Oracle

**Comment by anthony-tuininga** [comment]
No binary packages for Python 3.8 are currently available for cx_Oracle. Version 7.3 will be released sometime soon and will contain binaries for Python 3.8. In the meantime, either use Python 3.7 or build a package yourself from the source.

**Comment by bjyuxiao** [comment]
hope new version for Python 3.8 release quickly.I also encounter this problem.

**Comment by marjava** [comment]
thank you guys.. I've downloaded the cx_Oracle-7.2.3.tar.gz manualy  and installed.Now its working fine.

**Comment by santoshpanigrahi** [comment]
Hey @santhukpdjango could you please provide link for  cx_Oracle-7.2.3.tar.gz. will this work for python 3.9 or higher.

**Comment by anthony-tuininga** [comment]
Why not use cx_Oracle 8.3 instead? That supports Python 3.6 and higher -- including Python 3.10.

**Comment by santoshpanigrahi** [comment]
yes that would also work. could you pls share the link for cx_Oracle 8.3

**Comment by anthony-tuininga** [comment]
Is there a  reason you don't just use pip? As in

```
python -m pip install cx_Oracle
```

You can also download the files from this location and install them manually: https://pypi.org/project/cx-Oracle/

**Comment by likhithpindi1** [comment]
Hi 
I am unavailable to install cx_Oracle  in my system.
it following error 


C:\Users\likhi>python -m pip install cx_Oracle --upgrade --user
Collecting cx_Oracle
  Using cached cx_Oracle-8.3.0.tar.gz (363 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: cx_Oracle
  Building wheel for cx_Oracle (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for cx_Oracle (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      C:\Users\likhi\AppData\Local\Temp\pip-build-env-kgcyv_rk\overlay\Lib\site-packages\setuptools\config\expand.py:144: UserWarning: File 'C:\\Users\\likhi\\AppData\\Local\\Temp\\pip-install-sdto4pzy\\cx-oracle_2bc65b49da384dbe9d744b3a8dd13932\\README.md' cannot be found
        warnings.warn(f"File {path!r} cannot be found")
      running bdist_wheel
      running build
      running build_ext
      building 'cx_Oracle' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cx_Oracle
Failed to build cx_Oracle
ERROR: Could not build wheels for cx_Oracle, which is required to install pyproject.toml-based projects

C:\Users\likhi>python -m pip install cx_Oracle --upgrade --user
Collecting cx_Oracle
  Using cached cx_Oracle-8.3.0.tar.gz (363 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: cx_Oracle
  Building wheel for cx_Oracle (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for cx_Oracle (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      C:\Users\likhi\AppData\Local\Temp\pip-build-env-dhcu9du5\overlay\Lib\site-packages\setuptools\config\expand.py:144: UserWarning: File 'C:\\Users\\likhi\\AppData\\Local\\Temp\\pip-install-9zkhba2l\\cx-oracle_e49480ea4b17428fbf7563548d950565\\README.md' cannot be found
        warnings.warn(f"File {path!r} cannot be found")
      running bdist_wheel
      running build
      running build_ext
      building 'cx_Oracle' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cx_Oracle
Failed to build cx_Oracle
ERROR: Could not build wheels for cx_Oracle, which is required to install pyproject.toml-based projects

C:\Users\likhi>python -m pip install cx_Oracle --upgrade
Collecting cx_Oracle
  Using cached cx_Oracle-8.3.0.tar.gz (363 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: cx_Oracle
  Building wheel for cx_Oracle (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for cx_Oracle (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      C:\Users\likhi\AppData\Local\Temp\pip-build-env-dlbb8ic1\overlay\Lib\site-packages\setuptools\config\expand.py:144: UserWarning: File 'C:\\Users\\likhi\\AppData\\Local\\Temp\\pip-install-dbb8ijuo\\cx-oracle_c0b92089238b49fcb7855281fb414877\\README.md' cannot be found
        warnings.warn(f"File {path!r} cannot be found")
      running bdist_wheel
      running build
      running build_ext
      building 'cx_Oracle' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cx_Oracle
Failed to build cx_Oracle
ERROR: Could not build wheels for cx_Oracle, which is required to install pyproject.toml-based projects

**Comment by sharadraju** [comment]
@likhithpindi1 Please provide us the platform and system information from where you are building the app. What is the instant client version that you are using for cx_Oracle?

Also as the error says you would need Microsoft Visual C++ redistributable v 14.0 or greater.
Please check the Instant client pre-requirements as shown in the cx_Oracle documentation [here](https://cx-oracle.readthedocs.io/en/latest/user_guide/installation.html?#id3).

**Comment by likhithpindi1** [comment]
Thank you got it

**Comment by PrathapMD** [comment]
python -m pip install cx_oracle --proxy http://proxy-2-apj.svcs.entsvcs.com:8088
Collecting cx_oracle
  Using cached cx_Oracle-8.3.0.tar.gz (363 kB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000025790C03A50>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/setuptools/
      WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000025793EE9810>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/setuptools/
      WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000025793EEAE10>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/setuptools/
      WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000025793EEB550>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/setuptools/
      WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000025793F04590>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/setuptools/
      ERROR: Could not find a version that satisfies the requirement setuptools>=40.6.0 (from versions: none)
      ERROR: No matching distribution found for setuptools>=40.6.0
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.




I'm getting this error,while installing cx_oracle in windows server 2022, I have installed the dependecy tools visual studio code and visual tool build also, can anyone help me on this issue, thanks in advance.

**Comment by cjbj** [comment]
@PrathapMD if you are upgrading your stack (i.e Windows & Python to new versions), then we would suggest you also upgrade cx_Oracle to the latest version.  The latest release is now called python-oracledb.  See the [release announcement](https://cjones-oracle.medium.com/open-source-python-thin-driver-for-oracle-database-e82aac7ecf5a) and the [upgrade documentation](https://python-oracledb.readthedocs.io/en/latest/user_guide/appendix_c.html#steps-to-upgrade-to-python-oracledb).

**Comment by PrathapMD** [comment]
> @PrathapMD if you are upgrading your stack (i.e Windows & Python to new versions), then we would suggest you also upgrade cx_Oracle to the latest version. The latest release is now called python-oracledb. See the [release announcement](https://cjones-oracle.medium.com/open-source-python-thin-driver-for-oracle-database-e82aac7ecf5a) and the [upgrade documentation](https://python-oracledb.readthedocs.io/en/latest/user_guide/appendix_c.html#steps-to-upgrade-to-python-oracledb).

@cjbj  Thank you so much, it worked.
