### ISSUE TITLE
ora-12571: tns:packet writer failure while inserting Bulk data into Oracle table

### ISSUE THREAD

**Issue by aannmaneni** [oracle/python-cx_Oracle#378]
Hi Team,

I am trying to insert bulk data into Oracle database  and got the 'ora-12571: tns:packet writer failure '  issue in python. But when I execute same to code to load  few records then it works fine.

Any suggestions please.?

Thanks,
Anil.

**Comment by anthony-tuininga** [comment]
You haven't provided many details. How many rows are you trying to insert at one time? Are the database and client local to each other? What versions of Python, cx_Oracle, Oracle Database and Oracle Client are you using on which platforms? Without that information we're stuck guessing. And I'm guessing that you are trying to insert too many rows at a time.

**Comment by aannmaneni** [comment]
Hi Anthony,

Thanks for your reply.!

I am reading the data from .csv file and inserting into oracle table. File has around 300k Records.

Database is in remote server(client server). Client (Python script running)is in my local system.

Python 3.7.3
Cx_oracle 7.0.0
Oracle database 12.1.0.2.0
Oracle client 11.2.0.1.0 - Not sure.I have 11g oracle client in my local system
DB server on Linux and client is my laptop( Windows 10 enterprise). Below is the code

import csv
import cx_Oracle
import datetime
def SDE_File_XXX():
    try:
        con=cx_Oracle.connect('DB')
        cur=con.cursor()
        cur.execute('TRUNCATE TABLE 'XXX')
        rows=[]
        d = datetime.datetime.today() 
               
        with open("file.csv",encoding="utf8") as GL_HIERARCHY:
            acf=csv.reader(GL_HIERARCHY,delimiter=',')
            next(acf)
            for row in acf:
               rows.append(row)
        cur.prepare('INSERT Statement')
        cur.executemany(None,rows)
        con.commit()    
        cur.close()
        con.close()
        print('main')
    except cx_Oracle.DatabaseError as e:
        print("Row", cur.rowcount, "has error", e)
SDE_File_XXX()

**Comment by anthony-tuininga** [comment]
I would not recommend attempting to insert 300k records at the same time. I would suggest using a smaller size of say 5k to start with and then increase it as needed to satisfy your performance and memory requirements. See [this documentation](https://cx-oracle.readthedocs.io/en/latest/user_guide/batch_statement.html#batch-execution-of-sql) for details. Note in particular the possible need to split an array of data into smaller chunks in order to process them. If this resolves your issue then you know what the issue is and can deal with it accordingly.

**Comment by aannmaneni** [comment]
Thanks Anthony for your help.

Let me go with inserting small data sizes.I am sure it works .

Thanks,
Anil.

**Comment by anthony-tuininga** [comment]
Sounds good. If it works as expected, can you close this issue?

**Comment by aannmaneni** [comment]
Sure
