### ISSUE TITLE
I don't understans this DPI-1047 Error 

### ISSUE THREAD

**Issue by Shraneid** [oracle/python-cx_Oracle#380]
1. I installed the cx_Oracle, I've tried everything I can but can't understand why I still get the 
"DPI-1047: Cannot locate a 64-bit Oracle Client library: "The specified module could not be found"."
where I can access it via cmd

`C:\Users\Quentin>oci.dll
The system cannot execute the specified program.`

2.
> print("platform.platform:", platform.platform())
platform.platform: Windows-10-10.0.18362-SP0
print("sys.maxsize > 2**32:", sys.maxsize > 2**32)
sys.maxsize > 2**32: True
print("platform.python_version:", platform.python_version())
platform.python_version: 3.7.5

3. Show the directory listing where your Oracle client libraries are installed (e.g. the Instant Client directory).  Is it 64-bit or 32-bit?
C:\oracle\instantclient_19_3 
Everything is 64 bits, I've checked like 10 times

4. Show what the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) is set to?  On macOS, show what is in `~/lib`.

`
C:\Users\Quentin>path
PATH=C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\Git\cmd;C:\Program Files\PuTTY\;C:\Users\Quentin\AppData\Local\Microsoft\WindowsApps;C:\oracle\instantclient_19_3;
`

5. Show any Oracle environment variables set (e.g. ORACLE_HOME, ORACLE_BASE).
N/A

my code looks like this : 

> hostname = ('adb.uk-london-1.oraclecloud.com').encode('utf8')
port = ('1522').encode('utf8')
db = ('dbID').encode('utf8')
user_pwd = ("pass").encode('utf8')
dsn = (cx_Oracle.makedsn(hostname, port, db)).encode('utf8')
user = ("usr").encode('utf8')
connector = cx_Oracle.connect(dsn=dsn, user=user, password=user_pwd)

Thanks for the help !
PS : sry for bad formatting I don't understand why the code markups aren't working properly

**Comment by anthony-tuininga** [comment]
See [this comment](https://github.com/oracle/python-cx_Oracle/issues/352#issuecomment-527964632). Hopefully that will help you track down what is missing.

**Comment by cjbj** [comment]
> Everything is 64 bits, I've checked like 10 times

Show us how you know instant Client is 64 bit?

Have you installed the VS redistributable?

**Comment by anthony-tuininga** [comment]
So what was the problem? Missing VS redistributable?

**Comment by Shraneid** [comment]
For some reason it didn't work with python 3.8 so I reverted back to 3.6.8 and now it works like a charm

**Comment by anthony-tuininga** [comment]
Hmm, interesting. I haven't had any other complaints about Python 3.8 and there have been a lot of downloads so far -- so possibly something else was causing problems for you. In any case, its resolved for you now!

**Comment by Shraneid** [comment]
@anthony-tuininga well it's the only thing that I changed on my machine so can't really think of anything else being the problem 
maybe it resolved when I reinstalled the python library ?

**Comment by anthony-tuininga** [comment]
Unknown, unfortunately! If you do discover the source, let us know; otherwise, we'll wait for additional feedback.
