### ISSUE TITLE
cx_Oracle raises ORA-12715 when trying to establish connection

### ISSUE THREAD

**Issue by delta-sine** [oracle/python-cx_Oracle#386]
Hi all,

I'm currently getting the following error when trying to establish a connection to the Oracle database from my python script.  I am running instant client basic lite 19.5, my python code is running inside a lambda along with my client library.  Here is the folder structure:

all code resides inside /var/task (where all lambda code is run from).

my LD_LIBRARY_PATH is set to /var/task/lib
and contains all the files included in the instant client basic light package:

Here is a look inside **/var/task**
bin                                        
lib
certifi                                    
libociicus.so
certifi-2019.11.28.dist-info               
__pycache__
chardet                                    
python_dateutil-2.8.1.dist-info
chardet-3.0.4.dist-info                    
pytz
cx_Oracle-7.3.0.dist-info                  
pytz-2019.3.dist-info
cx_Oracle.cpython-37m-x86_64-linux-gnu.so  
requests
cx_Oracle-doc                              
requests-2.22.0.dist-info
data                                       
six-1.13.0.dist-info
dateutil                                   
six.py
ddl                                        
sqlalchemy
idna                                       
SQLAlchemy-1.3.11-py3.7.egg-info
idna-2.8.dist-info                         
__init__.py                                
urllib3
inserts                                    
urllib3-1.25.7.dist-info
lambda_function.py

Here's a look at **/var/task/lib**
libaio.so.1            
libclntsh.so  
libocci.so.12.1  
libocijdbc12.so  
ojdbc8.jar  
uidrvci
libclntshcore.so.12.1  
libnnz12.so   
libocci.so.19.1  
libocijdbc19.so  
oracore     
xstreams.jar
libclntshcore.so.19.1  
libnnz19.so   
libociicus.so    
network          
ucp.jar

**Here are the environment variables set on the host machine which runs the lambda:**
ORACLE_HOME='/var/task'
LD_LIBRARY_PATH = '/var/task/lib'
NLS_LANG='AMERICAN_AMERICA.AL32UTF8'
ORA_TZFILE=/var/task/lib/oracore/zoneinfo/timezlrg_26.dat

**Here is the connection string:**

dsn= cx_Oracle.makedsn("VALID_IP_ADDRESS", 1521, sid="jd1")
c  = cx_Oracle.connect("USER", "PASSWORD", dsn, encoding="UTF-8", nencoding="UTF-8")

**Here is the stack trace from the logs:**
[ERROR] DatabaseError: Error while trying to retrieve text for error ORA-12715
Traceback (most recent call last):
  File "/var/lang/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/var/lang/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/task/lambda_function.py", line 9, in <module>
    from inserts import Structure
  File "/var/task/inserts/Structure.py", line 16, in <module>
    c  = cx_Oracle.connect("USER", "PASSWORD", dsn, encoding="UTF-8", nencoding="UTF-8")

Here are my database v$NLS_PARAMETERS, obtained via my sql client app:

query used:
SELECT * FROM V$NLS_PARAMETERS;

output:
**NLS_LANGUAGE**	AMERICAN
**NLS_TERRITORY**	AMERICA
**NLS_CURRENCY**	$
**NLS_ISO_CURRENCY**	AMERICA
**NLS_NUMERIC_CHARACTERS**	.,
**NLS_CALENDAR**	GREGORIAN
**NLS_DATE_FORMAT**	DD-MON-RR
**NLS_DATE_LANGUAGE**	AMERICAN
**NLS_CHARACTERSET**	AL32UTF8
**NLS_SORT**	BINARY
**NLS_TIME_FORMAT**	HH.MI.SSXFF AM
**NLS_TIMESTAMP_FORMAT**	DD-MON-RR HH.MI.SSXFF AM
**NLS_TIME_TZ_FORMAT**	HH.MI.SSXFF AM TZR
**NLS_TIMESTAMP_TZ_FORMAT**	DD-MON-RR HH.MI.SSXFF AM TZR
**NLS_DUAL_CURRENCY**	$
**NLS_NCHAR_CHARACTERSET**	AL16UTF16
**NLS_COMP**	BINARY
**NLS_LENGTH_SEMANTICS**	BYTE
**NLS_NCHAR_CONV_EXCP**	FALSE

I've been pulling my hair out for the past few days trying to solve this :) Any help will be appreciated :)

**Comment by cjbj** [comment]
/var/task/lib  looks like a munged set of Instant Client files.  It has both 12c and 19c libraries, which can only lead to problems, as also indicated by the fact the error message text isn't found.  Fix this problem -  keep the different versions in different directories.  

Don't set ORACLE_HOME when using Instant Client libraries.

Since you are using UTF-8 at connection, the DB character sets shouldn't be an issue.  But queries to find them are in https://cx-oracle.readthedocs.io/en/latest/user_guide/globalization.html#finding-the-database-and-client-character-set

**Comment by anthony-tuininga** [comment]
Closing - assuming problem has been resolved
