### ISSUE TITLE
DPI-1047: Cannot locate a 64-bit Oracle Client library:

### ISSUE THREAD

**Issue by pallavisrinivas** [oracle/python-cx_Oracle#387]
I am able to run this python script manually. Facing this issue while running on cronjob as the same user

 conn = cx_Oracle.connect(user=v_db_user, password=v_db_passwd, dsn=dsn_tns)
cx_Oracle.DatabaseError: DPI-1047: Cannot locate a 64-bit Oracle Client library: "libclntsh.so: cannot open shared object file: No such file or directory". See https://oracle.github.io/odpi/doc/installation.html#linux for help

But I do have this file in my instant client. Here are the list of files
sdk
bin
xstreams.jar
BASIC_README
libons.so
libocci.so
rdbms
libocijdbc12.so
adrci
libipc1.so
libmql1.so
SQLPLUS_README
libclntshcore.so.12.1
libocci.so.12.1
uidrvci
ojdbc6.jar
libociei.so
libsqlplus.so
libclntsh.so
libclntshcore.so
genezi
ojdbc7.jar
libsqlplusic.so
libnnz12.so
sqlplus
libclntsh.so.12.1
liboramysql12.so
glogin.sql

**Comment by pallavisrinivas** [comment]
Output of ldd libclntsh.so
![image](https://user-images.githubusercontent.com/18624242/72466159-f3ecd880-379d-11ea-9a7a-1e1bddeea258.png)

**Comment by cjbj** [comment]
Cron won't inherit your shell environment variables, e.g. LD_LIBRARY_PATH.  This is the kind of reason the [installation instructions](https://cx-oracle.readthedocs.io/en/latest/user_guide/installation.html#installing-cx-oracle-on-linux) recommend using ldconfig, where possible

**Comment by pallavisrinivas** [comment]
Thanks for the reply. I have got all the Oracle paths in to a file & used source to pass this file in a crontab. This helped me resolve the issue 

* * * * * source /home/user/.Oracle [path to python] [path to filename.py]

**Comment by sensub** [comment]
Or you can do something like this:

* * * * * . /home/xyz/.pyenv && /home/xyz/python-script.py
