### ISSUE TITLE
Python Office Hours "Using Continuous Query Notification (CQN) with cx_Oracle" January 21, 2020 at 20:00 - 20:30 UTC

### ISSUE THREAD

**Issue by OsBlaineOra** [oracle/python-cx_Oracle#388]
Our next cx_Oracle 'Office Hours' (for 30 minutes!) will be on January 21, 2020 at 20:00 - 20:30 UTC

Hop on the webcast for a quick presentation on "Using Continuous Query Notification (CQN) with cx_Oracle" then you can ask us your cx_Oracle questions.

The link you need is devgym.oracle.com/pls/apex/dg/office_hours/3701 (or http://tinyurl.com/pythonhours if you like to keep it short).

**Comment by cjbj** [comment]
The Office Hours recording is at https://asktom.oracle.com/pls/apex/f?p=100:551:::NO:RP,551:P551_CLASS_ID:6792&cs=1B4233660676B9B093CEB460BACF65790

We discussed CQN.
