### ISSUE TITLE
Bind Variables cannot come from Python dict()

### ISSUE THREAD

**Issue by jmcp** [oracle/python-cx_Oracle#390]
- Include a link to the documentation section or the example

https://cx-oracle.readthedocs.io/en/latest/user_guide/bind.html#binding-by-name-or-position

- Describe the confusion

From the example text:

```
# alternatively, the parameters can be passed as a dictionary instead of as
# keyword parameters
data = { dept_id=280, dept_name="Facility" }
```

This is not, however, a dict(). Attempting to create a variable `data` using this example gives this error (Python 3.7, cx_Oracle 7.3.0, Instant Client v19):

```
>>> data1 = { dept_id=280, dept_name="Facility" }
  File "<stdin>", line 1
    data1 = { dept_id=280, dept_name="Facility" }
                     ^
SyntaxError: invalid syntax
>>> data1 = { "dept_id"=280, "dept_name"="Facility" }
  File "<stdin>", line 1
    data1 = { "dept_id"=280, "dept_name"="Facility" }
                       ^
```

- Suggest changes that would help

Remove the suggestion, or implement support for bind variable data coming from Python dict(), or fix the example to use correct syntax

**Comment by anthony-tuininga** [comment]
I've pushed the changes to correct the documentation. Thanks, @cjbj!

**Comment by anthony-tuininga** [comment]
cx_Oracle 8 was just released with these changes.
