### ISSUE TITLE
Import error cx_Oracle: symbol _mcount: referenced symbol not found

### ISSUE THREAD

**Issue by alex1404** [oracle/python-cx_Oracle#394]
Hi all,
we are facing an issue while trying to import cx_Oracle,
 
 ```
Traceback (most recent call last):
     File "/opt/DWH/sh/ETL/eci_scheduler/main_job.py", line 2818, in <module>
       message='starting main job')
     File "/usr/lib/python3.5/site-packages/fw_log/table_log.py", line 37, in info
       self._log(**kwargs)
     File "/usr/lib/python3.5/site-packages/fw_log/table_log.py", line 86, in _log
       db_.connect()
     File "/usr/lib/python3.5/site-packages/fw_db/db_session.py", line 40, in connect
       self.engine = sqlalchemy.create_engine(self.engine_str)
     File "/usr/lib/python3.5/site-packages/sqlalchemy/engine/__init__.py", line 423, in create_engine
       return strategy.create(*args, **kwargs)
     File "/usr/lib/python3.5/site-packages/sqlalchemy/engine/strategies.py", line 87, in create
       dbapi = dialect_cls.dbapi(**dbapi_args)
     File "/usr/lib/python3.5/site-packages/sqlalchemy/dialects/oracle/cx_oracle.py", line 827, in dbapi
       import cx_Oracle
   ImportError: ld.so.1: python3.5m: relocation error: file /usr/lib/python3.5/site-packages/cx_Oracle.so: symbol _mcount: referenced symbol not found
``` 
 
OS info : 
                       Oracle Solaris 11.4 X86
 
Python info:
                     Python 3.5.6
 
Cx_Oracle :
                     cx-Oracle 7.3.0
 
compilation of cx_Oracle  finished with no errors.
 
 
Please advise.
Thanks
Alex

**Comment by cjbj** [comment]
I assume you built cx_Oracle yourself?  Did you do it on the exact same platform and same Python? 
Do you get the same error if you run one of the cx_Oracle samples directly (i.e, lets remove sqlalchemy from the discussion since it's likely to be irrelevant)?

@jmcp does this ring any bells with you?

**Comment by alex1404** [comment]
-  I assume you built cx_Oracle yourself?  yes
-  Did you do it on the exact same platform and use the same Python? yes same platform and same python
- Do you get the same error if you run one of the cx_Oracle samples directly (i.e, lets remove sqlalchemy from the discussion since it's likely to be irrelevant)?  can you please explain what do you mean by 'run one of the cx_Oracle samples directly'

**Comment by cjbj** [comment]
From googling _mcount, I see mention of Solaris and gcc.  Did you also build Python yourself?  I wonder if you need to add a library into the link.

Try running one of the [samples](https://github.com/oracle/python-cx_Oracle/tree/master/samples) directly: `python BindQuery.py` or similar.

**Comment by alex1404** [comment]
ok, tried  BindQuery.py and received the same error

**Comment by jmcp** [comment]
It appears that an optimisation level including profiling was used, and gcc was in $PATH when building sqlalchemy and all its dependencies, but no RPATH which contains the profiling library/ies was baked into the cx_Oracle shared object.

@alex1404 if you run 'pkg install library/python/cx_oracle-35'  and then re-install sqlalchemy, I think that would get you past the problem.

**Comment by alex1404** [comment]
Hi @jmcp ,
just to be clear the error occurs regardless to sqlalchemy.  we are not building the sqlalchemy, we are using the source code .

**Comment by jmcp** [comment]
@alex1404 In that case, you really should be using the OS-provided versions of the Instant Client libraries.

**Comment by sumanthupar** [comment]
Hi,

Regarding this we have done the following as mentioned in the site(Installation steps of instant client),

1. downloaded basic instant client package instantclient-basiclite-solaris.x64-19.5.0.0.0dbru.
2. Unzipped into directory "instantclient"
3. Set LD_LIBRARY_PATH to the directory "instantclient"

But still getting same error.. 
ImportError: ld.so.1: python3.5: relocation error: file /usr/lib/python3.5/site-packages/cx_Oracle.so: symbol _mcount: referenced symbol not found

**Comment by cjbj** [comment]
Are you able to use SQL*Plus from Instant Client to execute queries?
