### ISSUE TITLE
Rounding issues

### ISSUE THREAD

**Issue by dkarnows** [oracle/python-cx_Oracle#396]
We're getting rounding issues inserting data using v7 of cx_Oracle (up to and including 7.3.0). Version 6.4.1 works fine.

The code below tries to insert value -229.940351804913 into the database. The last line includes what we tried to insert and the number we got back when selecting the inserted value. i.e. the two values on the last line should be the same.

Our Oracle database server version is 11.2.0.4.0.

Results with cx_Oracle 7.3.0 (bad!):
```
('platform.platform:', 'Linux-4.1.10-202.fc22.x86_64-x86_64-with-fedora-22-Twenty_Two')
('sys.maxsize > 2**32:', True)
('platform.python_version:', '2.7.10')
('cx_Oracle.version:', '7.3.0')
('cx_Oracle.clientversion:', (12, 1, 0, 1, 0))
Val=-229.94035180491300707217, DB=-229.94035180500000592474
```

Results with cx_Oracle 6.4.1 (good!):
```
('platform.platform:', 'Linux-4.1.10-202.fc22.x86_64-x86_64-with-fedora-22-Twenty_Two')
('sys.maxsize > 2**32:', True)
('platform.python_version:', '2.7.10')
('cx_Oracle.version:', '6.4.1')
('cx_Oracle.clientversion:', (12, 1, 0, 1, 0))
Val=-229.94035180491300707217, DB=-229.94035180491300707217
```

We create our test table with:
`create table dktest (testval number(30,20));`

And here is our test script:
```
import cx_Oracle, sys, platform

username, password, dbhost, dbport, dbsid = 'username', 'password', 'hostname', 'port', 'dbsid'
 
DELETE_SQL = "delete from dktest"
INSERT_SQL = "insert into dktest(testval) values(:val)"
SELECT_SQL = "select * from dktest"

def main():
    print("platform.platform:", platform.platform())
    print("sys.maxsize > 2**32:", sys.maxsize > 2**32)
    print("platform.python_version:", platform.python_version())
    print("cx_Oracle.version:", cx_Oracle.version)
    print("cx_Oracle.clientversion:", cx_Oracle.clientversion())
    
    conn = cx_Oracle.connect(username, password, cx_Oracle.makedsn(dbhost, dbport, dbsid))
    cursor = conn.cursor()
    
    val = -229.940351804913
    
    cursor.execute(DELETE_SQL)
    cursor.execute(INSERT_SQL, [val])
    cursor.execute(SELECT_SQL)
    results = cursor.fetchall()
        
    print("Val={:.20f}, DB={:.20f}".format(val, results[0][0]))
    
    conn.rollback()
    cursor.close()
    conn.close()

if __name__ == '__main__':
    main()
```

**Comment by anthony-tuininga** [comment]
Thus far this appears to be a Python 2 specific issue. Can you try with Python 3 and confirm that the problem doesn't appear in that situation? I'll see if I can track down the source of the issue, but confirmation that it is specific to Python 2 would be helpful.

**Comment by anthony-tuininga** [comment]
Ok. I can verify that this is indeed a Python 2 specific issue. Note the following code:

```
f = -229.940351804913
print(str(f))
```

In Python 2, the result is ``-229.940351805`` whereas in Python 3 the result is ``-229.940351804913``.

Note the rounding that Python 2 is doing.

As far as I know there isn't anything I can do about this. If you are aware of anything that can control how Python 2 converts floats to strings, let me know. cx_Oracle 7 began using strings for converting numbers to/from Oracle database in order to eliminate any precision loss on numbers returned from the Oracle Database. Precision loss from Python when sending numbers to the Oracle Database was never noticed! You're the first person to take note of this. Since Python 2 is no longer supported, I'd suggest upgrading to Python 3. :-)

**Comment by dkarnows** [comment]
But v6.4.1 of cx_Oracle is fine.

**Comment by anthony-tuininga** [comment]
Yes, it transferred floats to Oracle database directly -- which had its own set of issues. You clearly didn't discover those. :-) You can use ``decimal.Decimal`` which doesn't have the issue you reported, or remain at cx_Oracle 6.4 until you upgrade to Python 3. I'm not sure if there are any other solutions at this point!

**Comment by anthony-tuininga** [comment]
Its probably important to realize that Oracle stores numbers in a *decimal* format, whereas Python floats are a *binary" format. So for seamless transfer you should use ``decimal.Decimal``. If you want to use floats you'll have to handle little idiosyncracies like this one.

**Comment by dkarnows** [comment]
Got it. Thanks @anthony-tuininga  for the explanation and quick turn-around
