### ISSUE TITLE
"DPI-1072: the Oracle Client library version is unsupported" on Linux without Instant Client

### ISSUE THREAD

**Issue by maaiika** [oracle/python-cx_Oracle#397]
useing cx_oracle verion 7.2.0 on python2.7
we have 150+oracle in production , version blow
oracle 11.2.0.3  5
oracle 11.2.0.4  99
oracle 12.2.0.1  15

```
        try:
            import cx_Oracle
            import traceback
            if cx_Oracle.__version__ < "7.2.0":
                self.log.warn(
                    "warn cx_Oracle version incurrect! installed version {}, require version >= 7.2.0 please reinstall cx_Oracle  https://pypi.org/project/cx-Oracle/#files".format(
                        cx_Oracle.__version__))
            if sid:
                dsn = cx_Oracle.makedsn(ip, port, sid=sid)
            elif service_name:
                dsn = cx_Oracle.c(ip, port, service_name=service_name)
            try:
                self.log.warn("Connected to Oracle {}:{}/@{} with user {} password :{}".format(
                    ip, port, sid if sid else service_name, username, '******'))
                db = cx_Oracle.connect(
                    username, password, dsn, encoding="UTF-8")
                yield db
            except Exception as db_connect_error:
                self.log.warn(
                    "error {} While Connect {} Oracle {}  ".format(
                        traceback.format_exc(),
                        ip,
                        str(sid) + str(service_name)))
                raise
            finally:
                if db:
                    db.close()
                    self.log.info('Closeing Oracle connection')
```

about 80+ oracle report DBI-1050 error
useing cx_Oracle 7.2.0:
DPI-1050: Oracle Client library is at version 0.0 but version 11.2 or higher is needed
useing cx_Oracle 7.3.0:
DPI-1072: the Oracle Client library version is unsupported

confirmd:
1.low version  oracle and hight version oracle installed in one host
all new install oracle not upgraded 

2.old lib file still exist 
i have looked https://github.com/oracle/python-cx_Oracle/issues/351
seems some old lib file still exist LD_LIBRARY_PATH
but i all ready confirm no old lib file still exist ......

images you provided are very hard to read!--sorry in production env i cant copy txt.

i am very confim the configuration is currert,could  you tell me how to print the " Oracle Client library" file which was in useing or loading

**Comment by anthony-tuininga** [comment]
Please copy/paste text. The images you provided are very hard to read!

**Comment by cjbj** [comment]
Search for all libclntsh.so and libclntsh.so.* files.

Open a terminal and show us LD_LIBRARY_PATH.  Also check for files in /etc/ld.so.conf.d that may contain a path to Oracle libraries.

**Comment by maaiika** [comment]
thank you for comment i find libclntsh.so ln to libclntsh.so.11.1
i used Oracle instance Client  to  replace Oracle 11gr2  so files，now it works！
