### ISSUE TITLE
Handle SMALLINT and FLOAT oracle db types

### ISSUE THREAD

**Issue by sashabaranov** [oracle/python-cx_Oracle#4]
cx_Oracle 5.x does not handle SMALLINT and FLOAT db types. I am unsure about v6, but fix for 5.x is in https://github.com/oracle/python-cx_Oracle/pull/3

**Comment by anthony-tuininga** [comment]
Thanks. Can you provide a test case that doesn't work before your patch but does afterwards? Thanks.

**Comment by sashabaranov** [comment]
Sorry, I cant really reproduce this now, but basically I've experienced inability to query SMALLINT and FLOAT columns via SQLAlchemy and this fix helped.

**Comment by anthony-tuininga** [comment]
Both 5.x and 6.x patches have now been applied.

**Comment by sashabaranov** [comment]
I'm still getting error message `cx_Oracle.NotSupportedError: Object_ConvertToPython(): unhandled data type 246` from branch v5.x
