### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 53: invalid configuration byte

### ISSUE THREAD

**Issue by denchik20071992** [oracle/python-cx_Oracle#40]
*Delete irrelevant parts of this template.*

### For general questions:

Describe exactly what you did and what you want to happen.
Use the questions at the bottom of this template as a guide.

Use Markdown syntax, particularly for code blocks: see https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

### For security issues:

See https://www.oracle.com/support/assurance/vulnerability-remediation/reporting-security-vulnerabilities.html for how to report security issues.

### For installation issues:

Use a gist for screen output and logs: see https://gist.github.com/
**Do not paste long output into this issue**

Review the install instructions at
https://github.com/oracle/python-cx_Oracle#installation

Review your output and logs.  **Google any errors**

#### Answer the following questions:

1. What is your version of Python? Is it 32-bit or 64-bit?
64
2. What is your version of cx_Oracle?
cx_Oracle-6.0b2-cp36-cp36m-win_amd64.whl
3. What is your version of the Oracle client (e.g. Instant Client)?  How was it
   installed?  Where is it installed?

4. What is your version of the Oracle Database?
Oracle Database 11g Enterprise Edition Release 11.2.0.3.0 - 64bit Producti
5. What is your OS and version?
windows 7

9. What error(s) you are seeing?
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 53: invalid configuration byte

10. Using Anaconda 4.3.0 (64bit), python 3.6.0, 64

**Comment by anthony-tuininga** [comment]
Please provide the code you are executing which is causing the error and the full traceback.

**Comment by denchik20071992** [comment]
@anthony-tuininga ,
just 
`import cx_Oracle`

**Comment by anthony-tuininga** [comment]
Hmmm, are you able to try without Anaconda? I'll see if I can replicate the issue with Anaconda myself.

**Comment by denchik20071992** [comment]
What do you mean "without Anaconda?"
 I can start python session from cmd, but it'will start also Anaconda's version of python. 
I just checked by launching python session from cmd, the same result

**Comment by anthony-tuininga** [comment]
I mean -- running a base Python installation, not Anaconda's version of Python.

**Comment by anthony-tuininga** [comment]
I just downloaded and installed Anaconda 4.4.0 (64-bit, Python 3.6) on my machine. I then ran the command prompt option and issued the command

`python -m pip install cx_Oracle --pre`

When I called Python (now 3.6.1) and imported cx_Oracle it worked as expected. I did not get the error you received. Are you able to download and install 4.4.0 as well to see if that resolves the issue for you?

**Comment by anthony-tuininga** [comment]
I have discovered the source of this issue. The problem is that the error message that Windows is providing is in a different encoding than the assumed UTF-8. The error message is that the Oracle client library cannot be found or is incompatible with Python and cx_Oracle. I am working on a solution so that the correct error message will be returned properly.

**Comment by anthony-tuininga** [comment]
I have pushed a commit that corrects this. If you are able to test this for yourself, please do so. Thanks!

**Comment by anthony-tuininga** [comment]
Change has been integrated into cx_Oracle 6.0rc2.
