### ISSUE TITLE
ORA-57000: Invalid value (1) for TypeMode connection attribute

### ISSUE THREAD

**Issue by okanaganrusty** [oracle/python-cx_Oracle#404]
**See https://www.oracle.com/corporate/security-practices/assurance/vulnerability/reporting.html for how to report security issues**.

For other issues:

1. Is it an error or a hang or a crash?

It is an error when connecting to a TimesTen database.

```bash
$ ttversion
TimesTen Release 11.2.2.8.13 (64 bit Linux/x86_64) (11.2.2.8.13:11201) 2016-06-13T05:55:59Z
  Instance admin: ttadmin
  Instance home directory: /usr/local/TimesTen/11.2.2.8.13
  Group owner: bwadmin
  Daemon home directory: /var/TimesTen/11.2.2.8.13
  PL/SQL enabled.
```

2. What error(s) you are seeing?
**Cut and paste text showing the command you ran.  No screenshots.  Use a gist for long screen output and logs: see https://gist.github.com/**.

```python
# test.py

from __future__ import print_function

import cx_Oracle

dsn = "(DESCRIPTION=(CONNECT_DATA=(SERVICE_NAME=MaintenanceClient)(SERVER=timesten_client)))"

try:
  # All three scenarios produce the same error
  #connection = cx_Oracle.connect("bwas", "bwas", dsn)
  #connection = cx_Oracle.connect("bwas/bwas@127.0.0.1/Maintenance:timesten_direct")
  connection = cx_Oracle.connect("bwas/bwas@127.0.0.1/MaintenanceClient:timesten_client")

  cursor = connection.cursor()
  cursor.execute("select 1 / 0 from dual")

except cx_Oracle.DatabaseError as exc:
    error, = exc.args
    print("Oracle-Error-Code:", error.code)
    print("Oracle-Error-Message:", error.message)
```

```bash
Oracle-Error-Code: 57000
Oracle-Error-Message: ORA-57000: Invalid value (1) for TypeMode connection attribute -- value must be (0) for OCI connections but data store was created with (1)
```

3. Include a runnable Python script that shows the problem.
Include all SQL needed to create the database schema.

4. Show the output of:

```python
>>> import sys
>>> import platform
>>>
>>> print("platform.platform:", platform.platform())
platform.platform: Linux-3.10.0-862.el7.x86_64-x86_64-with-centos-7.5.1804-Core
>>> print("sys.maxsize > 2**32:", sys.maxsize > 2**32)
sys.maxsize > 2**32: True
>>> print("platform.python_version:", platform.python_version())
platform.python_version: 3.6.8
>>>
```

And:

```python
>>> import cx_Oracle
>>> print("cx_Oracle.version:", cx_Oracle.version)
cx_Oracle.version: 7.3.0
>>> print("cx_Oracle.clientversion:", cx_Oracle.clientversion())
cx_Oracle.clientversion: (11, 2, 0, 2, 0)
```

5. What is your Oracle Database version?

TimesTen Release 11.2.2.8.13 (64 bit Linux/x86_64) (11.2.2.8.13:11201) 2016-06-13T05:55:59Z

**Comment by okanaganrusty** [comment]
Even If I change the `TypeMode` from `1` to `0` and restart the TimesTen server process I still see the error.

```plain
#####################################################################
# Data source for Maintenance
#####################################################################
[Maintenance]
Driver=/usr/local/TimesTen/tt_base/lib/libtten.so
DataStore=/var/broadworks/persistent/AppServer
AutoCreate=0
CkptFrequency=3600
CkptLogVolume=512
CkptRate=16
Connections=256
DurableCommits=0
ExclAccess=0
Isolation=1
LockLevel=0
Logging=1
LogBufMB=256
LogDir=/var/broadworks/persistent
LogFileSize=256
LogPurge=1
MatchLogOpts=0
MemoryLock=0
OverWrite=0
PermSize=24576
Preallocate=0
Temporary=0
TempSize=170
ThreadSafe=1
WaitForConnect=0
TypeMode=1
UID=bwas
PwdCrypt=[REDACTED]

#####################################################################
# Data source for AppServerClient
#####################################################################
[MaintenanceClient]
TTC_SERVER=localhost_domainsocket
TTC_SERVER_DSN=Maintenance
UID=bwas
PwdCrypt=[REDACTED]
```

**Comment by anthony-tuininga** [comment]
I had a chat with someone who knows. He told me that ``TypeMode = 1`` is not supported. If the database was already created with ``TypeMode = 1`` you'll have to recreate the database as that is a "sticky" option.

**Comment by ChrisJ60** [comment]
TypeMode=1 is a legacy setting which is deprecated in TimesTen 18.1. Also it has never been supported when accessing TimesTen via OCI (which is what cx_Oracle uses under the covers). The TypeMode of a TimesTen database is a creation time attribute so you cannot simply change it in the database parameters (you can try but then you will get lots of error until you revert the change). You need to drop the database (ttDestroy) and re-create it with TypeMode=0. If you decide to do that them be sure to (a) save your data first (if you wish to preserve it) and (b) test your application with TypeMode=0 since it may have issues and may need some changes.

**Comment by okanaganrusty** [comment]
Unfortunately, I don't have the option of changing the `TypeMode` in the database.  The application is Broadwork.  It has been running in production environments since at least 2005 on TimesTen.  It sounds like using cx_Oracle with TimesTen is out of the option for us and we'll have to revert to using ODBC/JDBC for access.  Thanks
