### ISSUE TITLE
Memory leak in multithreaded client using Oracle client 12 or 18

### ISSUE THREAD

**Issue by fvst** [oracle/python-cx_Oracle#408]
Memory leak was observed in a multi-threaded python client when connecting to a 12c database using cx_Oracle and Oracle client 12. Since the original case we have also checked client 18 and it shows the same problem.

This issue seems to have been reported before on the cx_Oracle bitbucket (before dev moved to github), but it was not resolved before this dev move and I have not found a reference to it on github (again, also not sure if cx_Oracle is the issue or not). The issue was opened here: https://bitbucket.org/anthony_tuininga/cx_oracle/issues/37/multithread-lead-to-leak-when-connect 
Please adjust the script as needed to connect to a test DB. Here is how it was called when by us (just to show the env used since actual paths are, I assume, irrelevant)
`# env LD_LIBRARY_PATH=sample TNS_ADMIN=sample ORA_TZFILE=sample ORA_NLS10=sample NLS_LANG=AMERICAN_AMERICA.UTF8 NLS_SORT=GENERIC_M /sample/python cxtest.py`

Sample script is available [here](https://gist.github.com/fvst/802d83607129adb8ffb76d66d12b209e) or at the previously linked bitbucket issue.

Running this script produces different results, depending on OS versions.

On RedHat Enterprise Linux 6.3 this is the result:
  ```
- scenario 1:
  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
23678 root      20   0 2415m 2.0g  11m S 57.3  6.5   1:24.48 python
- scenario 2:
  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
13856 root      20   0  219m  20m  11m S 15.3  0.1   0:29.00 python
- scenario 3
  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
14307 root      20   0  494m 216m  12m S 19.0  0.7   0:44.02 python
  ```

On RedHat Enterprise Linux 7.5 only test 3 produces a leak:
  ```
- scenario 1:
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
31080 root      20   0  382140  21880  12308 S  73.4  0.1   1:31.81 python
- scenario 2:
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 6777 root      20   0  234676  21448  12332 S  24.3  0.1   0:26.15 python
- scenario 3:
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
10344 root      20   0  381264 122704  12528 S  20.7  0.8   0:42.64 python
  ```

Test 1 is most problematic and was seen on a RHEL 6.6 as well (but not on 6.9) - unclear what the determining factor is here.

Version information (original versions where problem was found, other versions were checked with no improvement):

```
('platform.platform:', 'Linux-2.6.32-279.el6.x86_64-x86_64-with-redhat-6.3-Santiago')
('sys.maxsize > 2**32:', True)
('platform.python_version:', '2.7.10')
```

```
('cx_Oracle.version:', '7.2.0')
('cx_Oracle.clientversion:', (12, 1, 0, 2, 0))
```
(various cx_Oracle versions have been tried to no effect. The checked versions include: 7.3.0, 7.2.0, 6.4.1 and 6.0.3)

Oracle database version: 12c (12.1.0.2) but the bitbucket link shows the issue was present when connecting to 11g as well.

**Comment by anthony-tuininga** [comment]
I tried running these tests and I do not see any memory leaks using recent OS and Oracle Client and Database versions. As such, this suggests that this is not a problem with cx_Oracle itself but may be an issue with older versions of the Oracle Client libraries. You will likely need to contact Oracle Support instead, especially if you are unable to upgrade any of the components. @cjbj may have further comments when he is available.

**Comment by fvst** [comment]
> You will likely need to contact Oracle Support instead, especially if you are unable to upgrade any of the components

We did initially open a support ticket, but their reply was less than favorable
> There is no paid Oracle "Support" for Python's cx_Oracle. It is an open source project.

Regarding the component upgrade, I did try with Oracle Client versions 12.1, 12.2 and 18.5 without much improvement. 19.5 is not an option because of RHEL 6 glibc version.

I will do some more tests internally on a RHEL 6.10 and maybe try downgrading the Oracle Client libs. If these tests hint at the client libraries I will open a new support ticket.

I will post an update here once I collect more data from different OS/client libs combinations (might be a few days).

**Comment by cjbj** [comment]
You said there was a difference between RHEL 6.6 and 6.9.  I wonder if there is some issue with Python itself.  What does RH say?  Have you tried a more recent version of Python?

**Comment by fvst** [comment]
The python used isn't one provided by RH. It is a custom built 2.7.10 (with some CVE patches  backported from later 2.7.x releases).

> Have you tried a more recent version of Python?

I have tried 2.7.17 (clean sources, no extra patches) and the problem persists on RHEL 6.3. Test1 easily reaches 1g within a few minutes.

The short version of the story is we were using old versions of both cx_Oracle and the Oracle Client libraries - an "if it ain't broke don't fix it" policy - and there were no memory issues. cx_Oracle was some 4.x version iirc.
Due to various requirements, an update was performed for both cx_Oracle and the client libraries and some users started reporting application crashes caused by memory usage (python version used stayed the same).
The problems reported so far seem to be only for RHEL 6.

I will try to get my hands on a 6.10 server to test there as well and downgrade to older versions of the Oracle Client libraries (10, 11) if that makes a difference.

**Comment by fvst** [comment]
I managed to get a RHEL 6.10 and the problem doesn't seem to reproduce. In fact, we couldn't reproduce it internally from 6.7 upwards - if this really is the case an OS upgrade isn't absurd to ask for given the age of these systems.

Currently, 2 users reported memory problems, one on RHEL 6.6 and one on 6.10. The report on 6.10 is strange considering our own tests, but since the user isn't responding to queries about his environment there is little to go on here.
Since there are differences between two 6.10 systems it probably isn't cxOracle or it is a weird interaction between cxOracle/client libs and system libs.

As far as I'm concerned, this can be parked/closed and I'll reopen if I get more information from the user who reported problems on 6.10 and it points to cxOracle.

**Comment by anthony-tuininga** [comment]
Thanks for the update. I'll close it for now as suggested.
