### ISSUE TITLE
Oracle Client Library Problem

### ISSUE THREAD

**Issue by bchenault** [oracle/python-cx_Oracle#41]
I am using Python 3.6 x64 on Windows 10 in Spyder. I installed the cx_Oracle module but I am getting an error when I try to import it. It is giving me the error, 

>DatabaseError: DPI-1047: Oracle Client library cannot be loaded: %1 is not a valid Win32 application. See https://oracle.github.io/odpi/doc/installation.html for help

> 

What does it mean by "%1 is not a valid Win32 application" and does anyone have any suggestions on how to fix this. Thanks

**Comment by anthony-tuininga** [comment]
It would seem that you are trying to use 32-bit Oracle client libraries with a 64-bit Python/cx_Oracle setup. You need to use 64-bit Oracle client libraries. Check your PATH environment variable and determine which OCI.dll is being loaded -- and make sure it is 64-bit!

**Comment by bchenault** [comment]
Thanks -  that worked perfectly!
