### ISSUE TITLE
Getting ORA-29275: partial multibyte character

### ISSUE THREAD

**Issue by manickaraja** [oracle/python-cx_Oracle#411]
Hi,
 We are extracting data from Oracle to flatfile (CSV seperated) using cx_oracle. While extracting varchar from certain fileds query is getting aborted and below error is thrown.

ORA-29275: partial multibyte character

 Ex. Select col1 from tab1; -- col1 is varchar
 Upon googling I found the work around as doing || ' ' at the end of string. This does resolve the problem

Modified sql: select rtrim(col1 || ' ', ' ') from tab1.

 However problem comes when col1 is > 4000 characters since its a limitation with strings. So I am looking at alternate solution which can avoid ORA-29275 without doing rtrim. Please help us with possible solution here.

Thanks in advance.

Thanks,
Manick.

**Comment by cjbj** [comment]
I'm closing this as a duplicate of #405 - where you haven't yet given the requested testcase.
