### ISSUE TITLE
DBMS_OUTPUT.GET_LINES Example

### ISSUE THREAD

**Issue by Aetylus** [oracle/python-cx_Oracle#412]
[PL/SQL Execution#Using DBMS_OUTPUT](https://cx-oracle.readthedocs.io/en/latest/user_guide/plsql_execution.html#using-dbms-output)

It may be helpful to provide an example using `DBMS_OUTPUT.GET_LINES`, in case a large amount of output is expected:

```py
# Set no buffer limit to allow a large amount of output
cursor.callproc('dbms_output.enable', (None,))
cursor.execute('''
begin
    for i in 1..5000 loop
        dbms_output.put_line('Line ' || i);
    end loop;
end;
''')

chararr = connection.gettype('SYS.DBMS_OUTPUT.CHARARR')
lines = chararr.newobject()

chunk_size = 100
numlines = cursor.var(int)
numlines.setvalue(0, chunk_size)

while numlines.getvalue() == chunk_size:
    cursor.callproc('dbms_output.get_lines', (lines, numlines))
    for line in lines.aslist():
        if line:
            print(line)
```

This will print
```
Line 1
Line 2
Line 3
[...]
Line 5000
```

**Comment by cjbj** [comment]
Good idea.

**Comment by anthony-tuininga** [comment]
I've pushed the suggested patch made by @cjbj but without the `if line` part which appears to skip blank lines. If that was needed for something else, please let me know! Thanks.

**Comment by Aetylus** [comment]
I think in hindsight that could have read:
```py
if line is not None:
```
This is because the final line retrieved into the `CHARARR` (`lines`) is `None`. Without this, you end up printing in the example:
```
    This is the cx_Oracle manual
    Demonstrating use of DBMS_OUTPUT
    None
```
I want to say that if empty lines should come as empty strings (`''`) and so this should print them this way, but actually didn't test that. Let me get back on that.

**Comment by anthony-tuininga** [comment]
cx_Oracle 8 was just released with these changes.
