### ISSUE TITLE
File system relative paths not allowed in hardened programs

### ISSUE THREAD

**Issue by hyang57** [oracle/python-cx_Oracle#413]
Describe the problem

I found you've referenced `@rpath` while finding libraries, maybe it's not allowed in MacOS 10.15.4 and Python 3.8?

Here's my code under Python 3.8.

```
import cx_Oracle
connection = cx_Oracle.connect("username", "password", "address")
```

and I got following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
cx_Oracle.DatabaseError: DPI-1047: Cannot locate a 64-bit Oracle Client library: "dlopen(libclntsh.dylib, 1): no suitable image found.  Did find:
	file system relative paths not allowed in hardened programs". See https://oracle.github.io/odpi/doc/installation.html#macos for help
```

```
platform.platform: macOS-10.15.4-x86_64-i386-64bit
sys.maxsize > 2**32: True
platform.python_version: 3.8.2
```

And:

`cx_Oracle.version: 7.3.0`

I ran the same code under Python 3.7 and it could show my cx_Oracle client version:
```
>>> print("cx_Oracle.clientversion:", cx_Oracle.clientversion())
cx_Oracle.clientversion: (19, 3, 0, 0, 0)
```
Here's the screenshot.

![image](https://user-images.githubusercontent.com/46363237/78620489-bab29900-78b2-11ea-8acb-7798d6319533.png)

**Comment by cjbj** [comment]
Instant Client isn't officially supported on Catalina.  Some work arounds are in https://github.com/oracle/python-cx_Oracle/issues/341. This is out of our control :(

**Comment by hyang57** [comment]
I tried v18, v12 and v19, they all returned same error.

I've read #341 however it's not related with my problem.

I **could** load those lib files under Python 3.7 on my Mac. I think the only reason is that you use @rpath, which is a relative path and it's not allowed in hardend programs. I think there's nothing wrong with Apple.

**Comment by ttran189** [comment]
I tried all found on google but still cannot fix this issue.
