### ISSUE TITLE
File system relative paths not allowed in hardened programs

### ISSUE THREAD

**Issue by hyang57** [oracle/python-cx_Oracle#414]
**PLEASE READ CAREFULLY BEFORE YOU CLOSE MY ISSUE**

Describe the problem

I have `instantclient v19.3` and it works well on MacOS 10.15 with Python 3.7. However when I tried to load Oracle library in Python 3.8 there is an error:

Here's my code:

**Python 3.8**

```
import cx_Oracle
>>> print("cx_Oracle.clientversion:", cx_Oracle.clientversion())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
cx_Oracle.DatabaseError: DPI-1047: Cannot locate a 64-bit Oracle Client library: "dlopen(libclntsh.dylib, 1): no suitable image found.  Did find:
	file system relative paths not allowed in hardened programs". See https://oracle.github.io/odpi/doc/installation.html#macos for help
```
**Python 3.7**
```
>>> print("cx_Oracle.clientversion:", cx_Oracle.clientversion())
cx_Oracle.clientversion: (19, 3, 0, 0, 0)
```
I found you've referenced `@rpath` while finding libraries,seems that it's not allowed in hardened programs. It happens on instantclinet v12, v18 and v19. I tried all versions I had.

RStudio team met the same error, [https://github.com/rstudio/rstudio/issues/4597](https://github.com/rstudio/rstudio/issues/4597#issuecomment-518434002), and there's a solution at the end of the post.

Here's the screenshot.

![image](https://user-images.githubusercontent.com/46363237/78620489-bab29900-78b2-11ea-8acb-7798d6319533.png)

**Comment by cjbj** [comment]
I will pass on your comments to the developers who look after Instant Client on macOS, however since this GitHub repo is for only for cx_Oracle issues, I recommend you contact Oracle Support.  Thanks.

**Comment by cjbj** [comment]
See the solution in https://github.com/oracle/python-cx_Oracle/issues/341#issuecomment-650492007
