### ISSUE TITLE
SQL statement with Cast is not working as expected.

### ISSUE THREAD

**Issue by achavhantexada** [oracle/python-cx_Oracle#418]
**See https://www.oracle.com/corporate/security-practices/assurance/vulnerability/reporting.html for how to report security issues**.

For other issues:

1. Is it an error or a hang or a crash?
error
2. What error(s) you are seeing?
*cx_Oracle.DatabaseError: ORA-01861: literal does not match format string**.

3. Include a runnable Python script that shows the problem.
Include all SQL needed to create the database schema.
```
>>> conn = db.engine.raw_connection()
>>> cursor = conn.cursor()
>>> cursor.excute("SELECT CAST('20200101' AS DATE) AS anon_1 FROM DUAL")
```
4. Show the output of:

```
import sys
import platform

print("platform.platform:", platform.platform())
print("sys.maxsize > 2**32:", sys.maxsize > 2**32)
print("platform.python_version:", platform.python_version())
```
```
platform.platform: Linux-5.3.0-46-generic-x86_64-with-debian-buster-sid
sys.maxsize > 2**32: True
platform.python_version: 3.6.5
```
And:

```
import cx_Oracle
print("cx_Oracle.version:", cx_Oracle.version)
print("cx_Oracle.clientversion:", cx_Oracle.clientversion())
```
```
cx_Oracle.version: 6.3
cx_Oracle.clientversion: (12, 2, 0, 1, 0)
```

5. What is your Oracle Database version?
Oracle Database 12c Standard Edition   12.2.0.1.0  64bit Production

**Comment by anthony-tuininga** [comment]
This is not a bug. The NLS_DATE_FORMAT string must match the format you are using. So this, for example, will work as you expect:

```
cursor.execute("alter session set nls_date_format = 'YYYYMMDD')")
cursor.execute("select cast('20200101' as DATE) from dual")
```

**Comment by cjbj** [comment]
For future readers, executing ALTER takes a round trip, so you want to avoid it if possible.  There are various techniques, such as using TO_DATE in SQL, or setting the NLS_DATE_FORMAT environment variable, or running the ALTER in a connection pool [session callback](https://cx-oracle.readthedocs.io/en/latest/user_guide/connection_handling.html#session-callbacks-for-setting-pooled-connection-state).
