### ISSUE TITLE
executemany problem with Python3?

### ISSUE THREAD

**Issue by lastalda** [oracle/python-cx_Oracle#42]
I'm trying to insert bulk data into an oracle table using executemany(). I've done this countless times in Python2, but am encountering a weird behaviour under Python3:

I have created a test table manually to illustrate the problem:
```
CREATE TABLE TEST_DATA2
   ("SAMPLE" VARCHAR2(20 BYTE), 
	"KEY" VARCHAR2(10 BYTE), 
	"VALUE" NUMBER(8,0)
   )
```

When I insert data like this, I get the expected behaviour:
```
items = [['ABC', 'A', 1764], ['ABC', 'B', 23], ['ABC', 'C', 0]]  
query = "INSERT INTO test_data2 (sample, key, value) VALUES (:1, :2, :3)"    
cursor.prepare(query)  
cursor.executemany(None, items)  
conn.commit()  
```
| Sample | Key | Value |  
|---|---|---|  
| ABC | A | 1764 |  
| ABC | B | 23 |  
| ABC | C | 0 |  

However, when I change one of the keys to a longer string (note that the create statement allows for 10 characters!) I get this:
```
items = [['ABC', 'A', 1764], ['ABC', 'B', 23], ['ABC', 'CC', 0]]
``` 
| Sample | Key | Value |  
|---|---|---|  
| ABC | Null | 1764 |  
| ABC | Null | 23 |  
| ABC | CC | 0 |  

So some of the cells in the 'Key' column become Null for an unknown reason. I get no errors or warnings at all.

I have tested this with some other, similar tables (while creating this minimal example) - sometimes I can use a length of 3 characters but not 4 or more. When I insert more rows, sometimes some of them keep the right Key, some don't (usually the long Keys and some but not all of the short Keys get turned to Null). The last row always gets the right Key, though, no matter how long the Key.   
(This also happens with differently named columns, but not with all of them. So far, I've only seen one column per table behave this way, and never the first one. Actually, I think it was always the last VARCHAR column.)

The exact same code works fine under Python2. It also works fine under Python3 if I insert the rows individually instead of using executemany.

I'm using Python 2.7.1 and Python 3.6.1 as 32 bit versions on a Windows10 machine.  
The Oracle version is Oracle Database 11g Release 11.2.0.4.0 - 64bit Production.
Instantclient is 11_2

Can I do anything about this or is it a bug? Is there any hope to get around it by using a different version of cx_Orcale or Python3? (The script I'm writing is reqired to be in Python3, and performance is an issue, hence I need executemany().)

Thanks for any help!  
Lastalda

**Comment by lastalda** [comment]
Sorry, forgot the cx_Oracle version: 6.0b1

**Comment by anthony-tuininga** [comment]
That is corrected in cx_Oracle 6.0b2 -- but get cx_Oracle 6.0rc1 which corrects a few more issues, too!

**Comment by anthony-tuininga** [comment]
Simplest way to do that is to use the command

`python -m pip install cx_Oracle --upgrade --pre`

**Comment by lastalda** [comment]
Thanks a lot, both for the solution and the swift reply.
It's working now, horray! :-)
