### ISSUE TITLE
Error in rollback

### ISSUE THREAD

**Issue by yuta86** [oracle/python-cx_Oracle#424]
Hi, I can't understand why my program add a rows although I have exception 

```
connection.callTimeout = 1  # milliseconds

def insert(connection, device_id, version):
         statement = f'insert into MyTable( device_id, version) values ' \
                    '(:device_id,  :version)'

        try:
            cursor.execute(statement, {
                'device_id': device_id,
                'version': version})
            connection.commit()
            full_result['status'] = 'Success'
        except cx_Oracle.DatabaseError as e:
            print(e)
            connection.rollback()
```

cx_Oracle.version: 7.3.0
cx_Oracle.clientversion: (19, 6, 0, 0, 0)

**Comment by anthony-tuininga** [comment]
First, why are using setting the call timeout to 1 ms? Do you honestly expect all of your calls to take less than that period of time? If this value is set to less than the time it takes to send a message to and receive back an answer from the database you will see unexpected results. This may or may not be the source of your issue. You can certainly see by commenting out that code or setting it to some larger number like 100.

Second, can you supply the complete code you are using and the output you are seeing vs what you expect to see?

**Comment by yuta86** [comment]
Thank you for answer

I specially set such a short time to check the work
I wrote the code above

In my table 0 rows and after run script I see added row 
But exception I see to

How can I make that when an exception occurs, the row is not written to the database
How would you do that? Can you share an example?
Thanks

**Comment by anthony-tuininga** [comment]
Remove the code that sets `callTimeout` and make sure your code is working as expected first. After you know it works as expected then you can set such timeout parameters -- if that's needed.

As for ensuring that when an exception occurs the data is not written to the database:

(1) if you only have one statement in your transaction (such as in your case) and an error occurs, no data is written to the database anyway. You can call `connection.rollback()` if you'd like but there is no need

(2) if you have multiple statements in your transaction and one of them has already succeeded theen you would need to call `connection.rollback()` to ensure the previously written data is rolled back.

I'm not sure why you would see the behaviour you are reporting. It would help if you include the complete code of your test case.

**Comment by yuta86** [comment]
ok I write full code
`class DBHelper:
    """
    Класс для работы с БД Oracle
    """

    def __init__(self, config: dict, logger: Logger):
        """

        @param config:
        @param logger:
        """
        try:
            self.host = config['Database']['host']
            self.port = config['Database']['port']
            self.sid = config['Database']['sid']
            self.connection_string = f'{self.host}:{self.port}/{self.sid}'
            self.user = config['Database']['user']
            self.password = config['Database']['password']
            self.table_bio = config['Database']['table_bio']
            self.table_sample = config['Database']['table_sample']
            self.max_tries = config['Database']['max_tries']
            self.connect_sleep_try = config['Database']['connect_sleep_try']
            self.call_timeout = config['Database']['call_timeout']
            self.logger = logger
        except KeyError as e:
            raise InitializationError(f'Config error: {repr(e)}')

        if not self.db_connect():
            raise InitializationError(f'DB initialization error: {self.connection_string}')

    def db_connect(self) -> bool:
        """

        @return:
        """
        try:
            self.logger.info(f'Connecting to DB: {self.connection_string}...')
            self.connection = cx_Oracle.connect(self.user, self.password, self.connection_string, encoding="UTF-8")
            self.connection.outputtypehandler = output_type_handler
            self.connection.autocommit = False
            self.connection.callTimeout = self.call_timeout  # milliseconds
            pprint(self.connection)
            self.logger.info(f'Connected to DB: {self.connection_string}')
            print("cx_Oracle.version:", cx_Oracle.version)
            print("cx_Oracle.clientversion:", cx_Oracle.clientversion())
            return True
        except Exception as e:
            print(f'FATAL: unable to connect to DB: {self.connection_string}' + repr(e))
            self.logger.exception(f'FATAL: unable to connect to DB: {self.connection_string}' + repr(e))
            return False

    def get_cursor(self) -> Union[None, cx_Oracle.Cursor ]:
        tries = 0
        while tries < self.max_tries:
            try:
                cursor = self.connection.cursor()
                return cursor
            except Exception as e:
                self.logger.exception('ERROR querying DB\n' + repr(e))
                if not self.db_connect():
                    tries += 1
                    time.sleep(self.connect_sleep_try)
        return None

    def __del__(self):
        try:
            print('----del----')
            print(self.connection)
            self.connection.close()
        except AttributeError as e:
            print(e)

if __name__ == '__main__':
    config = {"Database": {
        "user": "...",
        "password": "...",
        "host": "1...",
        "port": ...,
        "sid": "..".,
        "table_bio": "...",
        "table_sample": "....",
        "max_tries": 3,
        "sleep_try": 0.1,
        "call_timeout": 1,
        "connect_sleep_try": 10,
    }}
    logger = logging.getLogger()
    samples = {'111': '1111', '222': '222'}
    db_helper = DBHelper(config, logger)
    for i in range(5):
        result_insert = db_helper.insert_sample(device_id='device_id', colonkish_id='colonkish_id', created=datetime.now(), samples=samples)
        print(result_insert)
`

**Comment by anthony-tuininga** [comment]
You are still setting the callTimeout attribute to the value 1. On my machine this value occassionally works but frequently does not. The issue is that even the rollback call might fail with a timeout! So the insert might fail or the rollback might fail or the commit might fail. You need to set the value higher to accommodate all calls or set it to 0 to disable it.

**Comment by yuta86** [comment]
out of 1000 entries there were 10 errors
I expected to see 1000-10 but there are 995

My code is 

` config = {"Database": {
        "user": "user",
        "password": "password",
        "host": "10.10.10.10",
        "port": 1521,
        "sid": "base",
        "table_bio": "my_table",
        "table_sample": "my_table_two",
        "max_tries": 3,
        "sleep_try": 0.1,
        "call_timeout": 10,
        "connect_sleep_try": 10,
    }}
    logger = logging.getLogger()
    samples = {'111': '1111'}
    db_helper = DBHelper(config, logger)
    error = 0
    for i in range(1, 1001):
        result_insert = db_helper.insert_sample(device_id='device_id', colonkish_id='colonkish_id', created=datetime.now(), samples=samples)
        print(result_insert)
        if result_insert['error']:
            error +=1
        print(i)
    print('end')
    print(f'error = {error}')`

**Comment by anthony-tuininga** [comment]
Have you removed the code to set `connection.callTimeout`?

**Comment by yuta86** [comment]
config = {"Database": {
        "user": "...",
        "password": "...",
        "host": "1...",
        "port": 1521,
        "sid": "...",
        "table_bio": ".....",
        "table_sample": ".....",
        "max_tries": 3,
        "sleep_try": 0.1,
        "call_timeout": 20,
        "connect_sleep_try": 10,
    }}
no, that part of the code remains the same

**Comment by anthony-tuininga** [comment]
I am asking you to remove it or at least set the value to 0 in order to disable it. After you have done that, try again and see if you are still experiencing the same problems.

**Comment by yuta86** [comment]
if I delete or set 0 then there are no errors.
But I want to create my code async

`  full_result = {'status': '', 'error': '', 'result': ''}
        count_try = 0
        while count_try < 3:
               try:

                    cursor.execute(statement, insert_data)
                    print('before commit')
                    self.connection.commit()
                    print('after commit')
                    full_result['status'] = 'Success'
                except cx_Oracle.DatabaseError as e:  # excepting callTimeOut exception
                    print('THIS IS EXCEPTION CALLTIMEOUT')
                    self.connection.rollback()
                     count_try += 1
                     await asyncio.sleep(0.01)
return full_result
`
        I try create my code asynchronous.  How do I make the code asynchronous?

Thank you

**Comment by yuta86** [comment]
Buddy i'm still waiting for an answer....

**Comment by anthony-tuininga** [comment]
So if you don't have a callTimeout value everything works as expected. That's good to hear. You can't set it to a low value and expect everything to work! You need to allow time for the network send and receive as well as any effort that is required by the database to perform the work. Note as well that if the execute() fails because of a low callTimeout value, there is a good possibility that the rollback() or the commit() will also fail!

As for creating asynchronous code, cx_Oracle itself doesn't support asyncio directly, but you can use the asyncio thread pool to simulate it. You can also just create a thread and have database work take place on that thread without using asyncio at all. It completely depends on what you are trying to accomplish! A course on asynchronous programming is beyond the scope of this issue so you'll need to find another source for that sort of help. If you have specific questions about cx_Oracle and how to use it we are happy to help, though!
