### ISSUE TITLE
alueError: could not convert string to float: '0.000000000000000000000000000000000030H222997'

### ISSUE THREAD

**Issue by jimbpm** [oracle/python-cx_Oracle#426]
This is an error.

This table has a long decimal value.
![image](https://user-images.githubusercontent.com/48131487/80242081-bddbb200-8632-11ea-93fe-187c97f4e0c9.png)

It is type NUMBER(*)

![image](https://user-images.githubusercontent.com/48131487/80242155-e663ac00-8632-11ea-8af3-77cb4306e56c.png)

```python
import cx_Oracle
import decimal


def test_float(config):

    core_config = config.connections.Core
    dsn = cx_Oracle.makedsn(core_config.hostname, core_config.port, core_config.instance)
    conn = cx_Oracle.connect(user=core_config.username, password=core_config.password, dsn=dsn, encoding="UTF-8")

    cursor = conn.cursor()

    def output_type_handler(cursor, name, defaultType,
                            size, precision, scale):
        return cursor.var(
            # using decimal.Decimal here on cx_Oracle 6.0.2 still breaks
            cx_Oracle.STRING,
            255,
            outconverter=decimal.Decimal,
            arraysize=cursor.arraysize)

#    cursor.outputtypehandler = output_type_handler

    cursor.execute("SELECT edm.NUMERIC_DATA \
    FROM EXPERIMENT_DATA edm \
    WHERE edm.EXPERIMENT_DATA_ID = 50346396")

    received = set([
        row[0] for row in cursor.fetchall()
    ])

    print("cx_Oracle version: %r" % cx_Oracle.__version__)
    print("Received: %r" % received)

    cursor.close()
    conn.close()
```

Output when no handler.
```
Traceback (most recent call last):
  File "/System/Volumes/Data/src/dev-ops/ddw_loader/Main.py", line 32, in <module>
    test_float(config)
  File "/System/Volumes/Data/src/dev-ops/ddw_loader/tests/TestFloat.py", line 32, in test_float
    row[0] for row in cursor.fetchall()
ValueError: could not convert string to float: '0.000000000000000000000000000000000030H222997'
```

Output when handler uncommented

```
cx_Oracle version: '7.3.0'
Received: {None}

Process finished with exit code 0
```

**Comment by jimbpm** [comment]
import cx_Oracle
import decimal


def test_float(config):

    core_config = config.connections.Core
    dsn = cx_Oracle.makedsn(core_config.hostname, core_config.port, core_config.instance)
    conn = cx_Oracle.connect(user=core_config.username, password=core_config.password, dsn=dsn, encoding="UTF-8")

    cursor = conn.cursor()

    def output_type_handler(cursor, name, defaultType,
                            size, precision, scale):
        return cursor.var(
            # using decimal.Decimal here on cx_Oracle 6.0.2 still breaks
            cx_Oracle.STRING,
            255,
            outconverter=decimal.Decimal,
            arraysize=cursor.arraysize)

    cursor.outputtypehandler = output_type_handler

    cursor.execute("SELECT edm.NUMERIC_DATA \
    FROM EXPERIMENT_DATA edm \
    WHERE edm.EXPERIMENT_DATA_ID = 50346396")

    received = set([
        row[0] for row in cursor.fetchall()
    ])

    print("cx_Oracle version: %r" % cx_Oracle.__version__)
    print("Received: %r" % received)

    cursor.close()
    conn.close()

**Comment by anthony-tuininga** [comment]
Can you provide the script to insert the data as well so that it is entirely standalone? Or at the very least copy/paste the relevant value as text instead of an image. Thanks!

**Comment by jimbpm** [comment]
Sorry.  

CREATE TABLE EXPERIMENT_DATA (EXPERIMENT_DATA_ID NUMBER(*), NUMERIC_DATA NUMBER(*));
INSERT INTO EXPERIMENT_DATA VALUES (50346396, 0.0000000000000000000000000000000000298622997);
SELECT * FROM EXPERIMENT_DATA;

**Comment by jimbpm** [comment]
`CREATE TABLE EXPERIMENT_DATA (EXPERIMENT_DATA_ID NUMBER(*), NUMERIC_DATA NUMBER(*));
INSERT INTO EXPERIMENT_DATA VALUES (50346396, 0.0000000000000000000000000000000000298622997);
SELECT * FROM EXPERIMENT_DATA;`

**Comment by anthony-tuininga** [comment]
I just tried this on Linux with Python 3.7 and all of the different Oracle client versions that are supported and didn't get the error you are getting. Can you provide details on the environment you are using?

**Comment by jimbpm** [comment]
Ok - looks like an issue with the Oracle data.  I ran the sql script to create a new table and it worked.  it was only when I did my original query against a 87millions row table that it failed.  

`
INSERT INTO EXPERIMENT_DATA_TEST VALUES (50346395, 0.0000000000000000000000000000000000298622997);

INSERT INTO EXPERIMENT_DATA_TEST
SELECT EXPERIMENT_DATA_ID, NUMERIC_DATA
FROM EXPERIMENT_DATA WHERE EXPERIMENT_DATA_ID = 50346396;
`
First one works, second one doesn't.  Something about how the number stored.

Apparently not an issue with cx_Oracle.  I need to figure out whats going on with the table.

**Comment by jimbpm** [comment]
`"EXPERIMENT_DATA_ID","NUMERIC_DATA"
50346395,0.0000000000000000000000000000000000298622997
50346396,0.0000000000000000000000000000000000298622997
`
First one works, not second one.

**Comment by anthony-tuininga** [comment]
Can you run this query on both?

`select dump(numeric_data) from experiment_data where experiment_data_id = 50346936`

That should indicate what's different internally about them.

**Comment by jimbpm** [comment]
`select EXPERIMENT_DATA_TEST.*, dump(numeric_data) from EXPERIMENT_DATA_TEST;
`

`"EXPERIMENT_DATA_ID","NUMERIC_DATA","DUMP(NUMERIC_DATA)"
50346395,0.0000000000000000000000000000000000298622997,"Typ=2 Len=6: 175,30,87,23,100,71"
50346396,0.0000000000000000000000000000000000298622997,"Typ=2 Len=6: 175,31,243,23,100,71"
`

**Comment by anthony-tuininga** [comment]
I believe that shows that the number is corrupted as the 2nd and 3rd bytes differ. The 3rd byte is not a valid value as far as I understand. I'll ask internally about it. In the meantime, you should be able to simply update the value in order to get rid of the corruption.

**Comment by jimbpm** [comment]
That did it!  Thanks so much for your help
