### ISSUE TITLE
Can't run Python 3.8 on macOS

### ISSUE THREAD

**Issue by Balky79** [oracle/python-cx_Oracle#428]
**See https://www.oracle.com/corporate/security-practices/assurance/vulnerability/reporting.html for how to report security issues**.

For other issues:

1. Is it an error or a hang or a crash?
Error

2. What error(s) you are seeing?
**Cut and paste text showing the command you ran.  No screenshots.  Use a gist for long screen output and logs: see https://gist.github.com/**.
connection = cx_Oracle.connect("USERNAME", "PASSWORD", "SRV")
cx_Oracle.DatabaseError: DPI-1047: Cannot locate a 64-bit Oracle Client library: "dlopen(libclntsh.dylib, 1): image not found". See https://oracle.github.io/odpi/doc/installation.html#macos for help

3. Include a runnable Python script that shows the problem.
Include all SQL needed to create the database schema.
connection = cx_Oracle.connect("USERNAME", "PASSWORD", "SRV")

4. Show the output of:

```
import sys
import platform

print("platform.platform:", platform.platform())
print("sys.maxsize > 2**32:", sys.maxsize > 2**32)
print("platform.python_version:", platform.python_version())
```

platform.platform: macOS-10.14.6-x86_64-i386-64bit
sys.maxsize > 2**32: True
platform.python_version: 3.8.2

And:

```
import cx_Oracle
print("cx_Oracle.version:", cx_Oracle.version)
print("cx_Oracle.clientversion:", cx_Oracle.clientversion())
```

cx_Oracle.version: 7.3.0
>>> print("cx_Oracle.clientversion:", cx_Oracle.clientversion())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
cx_Oracle.DatabaseError: DPI-1047: Cannot locate a 64-bit Oracle Client library: "dlopen(libclntsh.dylib, 1): image not found". See https://oracle.github.io/odpi/doc/installation.html#macos for help

5. What is your Oracle Database version?
Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
PL/SQL Release 12.1.0.2.0 - Production
"CORE	12.1.0.2.0	Production"
TNS for Linux: Version 12.1.0.2.0 - Production
NLSRTL Version 12.1.0.2.0 - Production

ls -all ~/lib/
drwxr-xr-x   7 istojako  MS\Domain Users        224 29 Apr 12:04 .
drwxr-xr-x+ 88 istojako  MS\Domain Users       2816 29 Apr 11:33 ..
lrwxr-xr-x   1 istojako  MS\Domain Users         66 29 Apr 11:55 libclntsh.dylib -> /Users/istojako/MyDev/oraclient/instantclient_19_3/libclntsh.dylib
-rwxr-xr-x@  1 istojako  MS\Domain Users   98137256 29 Apr 12:04 libclntsh.dylib.19.1
-rwxr-xr-x@  1 istojako  MS\Domain Users    4803832 29 Apr 12:04 libclntshcore.dylib.19.1
-rwxr-xr-x@  1 istojako  MS\Domain Users    8349944 29 Apr 12:04 libnnz19.dylib
-rwxr-xr-x@  1 istojako  MS\Domain Users  125518764 29 Apr 12:04 libociei.dylib

ls -all /usr/local/lib/libc*
ls -all /usr/local/lib/libclntsh.dylib
lrwxr-xr-x  1 istojako  admin  66 29 Apr 12:03 /usr/local/lib/libclntsh.dylib -> /Users/istojako/MyDev/oraclient/instantclient_19_3/libclntsh.dylib

I obviously tried to have it on all locations, removed on one, remove on the other one, but for some reason python insists on not being able to find the client. 

Python is 3.8 from python.org, x64, so not bundled 

Any useful tips are welcome

**Comment by cjbj** [comment]
In my ~/lib I just have:
```
  /Users/cjones/lib:
  total used in directory 0 available 9223372036852939131
  lrwxr-xr-x   1 cjones  staff    48 12 Nov 15:04 libclntsh.dylib -> /Users/cjones/instantclient_19_3/libclntsh.dylib
```
It wasn't clear whether you had actual libs as well?

Can you try an older Python?  It's possible that Python compilation has changed.  We've seen a similar issue with Node.js.

**Comment by Balky79** [comment]
Thank you. 

Reverted python to 3.6.8 and it works. 

Do you need this as a Python 3.8 specific ticket? Otherwise feel free to close it.

**Comment by cjbj** [comment]
A solution will likely need a new Instant Client release to be made by Oracle.

**Comment by cjbj** [comment]
See the solution in https://github.com/oracle/python-cx_Oracle/issues/341#issuecomment-650492007
