### ISSUE TITLE
UnicodeDecodeError appears when importing module

### ISSUE THREAD

**Issue by Keyreach** [oracle/python-cx_Oracle#43]
1. What is your version of Python? Is it 32-bit or 64-bit?
**3.6.1, 64-bit, package from Python.org, installed system-wide (for all users)**

2. What is your version of cx_Oracle?
**cx_Oracle-6.0rc1-cp36-cp36m-win_amd64.whl**

3. What is your version of the Oracle client (e.g. Instant Client)?  How was it
   installed?  Where is it installed?
**instantclient-basic-windows.x64-12.2.0.1.0, extracted to location - C:\Oracle\instantclient_12_2**

4. What is your OS and version?
**Windows 10.0.14393**

5. What environment variables did you set?  How *exactly* did you set them?
**Instant client location was added to PATH and set as ORACLE_HOME**

6. What *exact* command caused the problem (e.g. what command did you try to
   install with)?  Who were you logged in as?
`import cx_Oracle`

7. What error(s) you are seeing?
```
	File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcd in position 50: invalid continuation byte
```

**Comment by anthony-tuininga** [comment]
The environment variable ORACLE_HOME should not be set. Can you unset that environment variable? I don't know that it will make a difference but it is worth checking!

**Comment by Keyreach** [comment]
Same error occurs without ORACLE_HOME have been set.

**Comment by anthony-tuininga** [comment]
I just tried with the same configuration as you (except Windows 7, not Windows 10) and I am unable to replicate your issue, unfortunately. A similar [issue](https://github.com/oracle/python-cx_Oracle/issues/40) was reported, but that was with Anaconda. Do you have the environment variables NLS_LANG or NLS_NCHAR set? Are you able to build cx_Oracle yourself? If so, please do so with environment variable DPI_DEBUG_LEVEL set to the value 7.

**Comment by Keyreach** [comment]
NLS_NCHAR isn't set, i've tried NLS_LANG both set and unset. Yes, I run Python from command prompt, I've tried to run it both as administrator and as user.

**Comment by anthony-tuininga** [comment]
Are you able to build cx_Oracle yourself?

**Comment by Keyreach** [comment]
It seems that problem was caused by InstantClient.
I've tried 5.3 and it reported DLL errors, so I've checked dependencies of oci.dll and found that msvcr120.dll is missing. Installing Visual C++ Redistributable 2013 has solved this problem.

**Comment by cjbj** [comment]
Thanks for digging into it.  The VC Redistributable 2013 is a requirement for Oracle Client 12.2.  This is documented in various places such as the [ODPI-C install guide](https://oracle.github.io/odpi/doc/installation.html#windows).  

We need to improve cx_Oracle install doc to make this more visible.
