### ISSUE TITLE
cx_Oracle.NotSupportedError: Python value of type numpy.int64 not supported on executemany 

### ISSUE THREAD

**Issue by Sajaki** [oracle/python-cx_Oracle#430]
1. Is it an error or a hang or a crash?
an error running executemany

2. What error(s) you are seeing?
please see here: 
https://gist.github.com/Sajaki/f66e770c47e25f77f9d8f4ce7dfd1410

3. Include a runnable Python script that shows the problem.
Include all SQL needed to create the database schema.

```
import csv
import pandas as panda
import cx_Oracle as db

def dbimport_bikes():
    """ oracle import
    """
    location = pathmerged + 'bikes_merged.csv'
    f = open(location, mode="r", encoding="utf8").read()
    rider = panda.read_csv(filepath_or_buffer=location, sep=",", header=0, quotechar='"', engine='python')
    # package each dataframe row into a tuple
    records = rider.to_records(index=False)
    # wrap tuples in list
    result = list(records)
    print(result)
    be01conn = db.connect('user/password@tnsname')
    cursor=be01conn.cursor()
    cursor.execute("ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD'")
    cursor.execute("truncate table ORACLE.bikes")
    cursor.executemany("""
    INSERT INTO ORACLE.bikes (APPLICATIONID, POLICYNUMBER, POLICYVERSION, BRAND, TYPE, MODEL, 
    PURCHASE_AMOUNT, DATE_OF_PURCHASE, YEAR_OF_BUILD, BIKE_PRICE, ACCESSORIES_PRICE, LOCK_PRICE, LOCK_BRAND, 
    CHASSIS_NUMBER, KEY_NUMBER_1, KEY_NUMBER_2, BIRTHDATE_CUSTOMER, STATUS, INTEGRATIONDATE) 
    VALUES(:1,:2,:3,':4',':5',':6', :7, 
    to_date(:8,'RRRR-MM-DD'), :9, :10, :11, :12, ':13', ':14', ':15', ':16', 
    to_date(:17,'RRRR-MM-DD'), ':18', to_date(:19,'RRRR-MM-DD'))
    """, result, batcherrors=True)
    for error in cursor.getbatcherrors():
        print("Error", error.message, "at row offset", error.offset)
    be01conn.commit()


print(" csv Start")
pathin  = "\\\\share1503\\Datain\\"
dbimport_bikes()

```

table sql 
```
CREATE TABLE "ORACLE"."BIKES" 
   (	"APPLICATIONID" NUMBER NOT NULL ENABLE, 
	"POLICYNUMBER" NUMBER, 
	"POLICYVERSION" NUMBER, 
	"BRAND" NVARCHAR2(255), 
	"TYPE" NVARCHAR2(255), 
	"MODEL" NVARCHAR2(255), 
	"PURCHASE_AMOUNT" NUMBER, 
	"DATE_OF_PURCHASE" DATE, 
	"YEAR_OF_BUILD" NUMBER, 
	"BIKE_PRICE" NUMBER, 
	"ACCESSORIES_PRICE" NUMBER, 
	"LOCK_PRICE" NUMBER, 
	"LOCK_BRAND" NVARCHAR2(255), 
	"CHASSIS_NUMBER" NVARCHAR2(255), 
	"KEY_NUMBER_1" NVARCHAR2(255), 
	"KEY_NUMBER_2" NVARCHAR2(255), 
	"BIRTHDATE_CUSTOMER" DATE, 
	"STATUS" NVARCHAR2(255), 
	"INTEGRATIONDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
```

4. Show the output of:

```
import sys
import platform

print("platform.platform:", platform.platform())
print("sys.maxsize > 2**32:", sys.maxsize > 2**32)
print("platform.python_version:", platform.python_version())

platform.platform: Windows-10-10.0.14393-SP0
sys.maxsize > 2**32: True
platform.python_version: 3.7.5
```

And:

```
import cx_Oracle
print("cx_Oracle.version:", cx_Oracle.version)
print("cx_Oracle.clientversion:", cx_Oracle.clientversion())

cx_Oracle.version: 7.3.0
cx_Oracle.clientversion: (12, 2, 0, 1, 0)
```

5. What is your Oracle Database version?
11.2.0.4

**Comment by anthony-tuininga** [comment]
The error is fairly clear, I think: "cx_Oracle.NotSupportedError: Python value of type numpy.int64 not supported.". You will need to transform the values of type `numpy.int64` to something that cx_Oracle knows how to handle -- given the name I would suggest an integer. This is where an input type handler comes in handy as shown in this [sample](https://github.com/oracle/python-cx_Oracle/blob/master/samples/TypeHandlers.py). Something like the following would be needed:

```
def InConverter(value):
    return int(value)  # or whatever is needed to convert from numpy.int64 to an integer

def InputTypeHandler(cursor, value, num_elements):
    if isinstance(value, numpy.int64):
        return cursor.var(int, arraysize=num_elements, inconverter=InConverter)

cursor.inputtypehandler = InputTypeHandler
```

**Comment by Sajaki** [comment]
after adding the inputhandler i got past that issue. thanks for the explanation.

**Comment by cjbj** [comment]
@Sajaki what did your `InConverter` look like?  We can add a documentation example if we have the appropriate code.

**Comment by Blue-53Hz** [comment]
Excuse me, you solved the problem by adding InputHandler. I'd like to ask you how to add it. I'm looking forward to your answer

**Comment by larsklitzke** [comment]
Although this issue is quite old now, I stumbled across it while searching for a solution to this problem. Since I use the ORM part of SQLAlchemy, the comments above only partly solved the problem for me. So, here is my solution for anyone struggling with this.

Assuming you've initialized an engine entity, we can add an event listener for the *before_cursor_execute* event.

```python
from sqlalchemy import event

...
# initialize an engine with your database credentials
...

# register an event handler for the before_cursor_execute signal which will handle numpy values
event.listen(engine, "before_cursor_execute", add_numpy_converter)
```

The `add_numpy_converter` is a function adding the numpy value handler to the cursor. 

```python 

def add_numpy_converter(connection, cursor, *args, **kwargs):
    cursor.inputtypehandler = numpy_handler
```

The `numpy_handler` is also a function taking the cursor, the current value and the number of elements. That function needs to return a valid varianble as in https://github.com/oracle/python-cx_Oracle/issues/430#issuecomment-622577935. Since I just need it for integers and floating point numbers, they are convered by the handler.

```python

def numpy_handler(cursor, value, num_elements):
    dtype = None

    if isinstance(value, np.integer):
        dtype = int
    elif isinstance(value, np.inexact):
        dtype = float

    if dtype is not None:
        return cursor.var(dtype, arraysize=num_elements, inconverter=numpy_to_python)
```

Note that the `var` method needs a function performing the actual conversion from python given as `inconverter` parameter. In this case, the `numpy_to_python` is quite straightforward and just calls the `item()` method of the numpy value.

```python
def numpy_to_python(value):
    return value.item()
```
