### ISSUE TITLE
cx_Oracle.DatabaseError: DPI-1043: invalid number

### ISSUE THREAD

**Issue by Sajaki** [oracle/python-cx_Oracle#431]
1. Is it an error or a hang or a crash?
i need to do workarounds for nan values for insertions in varchar fields. if i don't then i get DPI-1043:

2. What error(s) you are seeing?

when i don't apply this workaround 

           # email
           if (isinstance(rec[16], (float))):
               rec[16] = 'NULL'

then i get error because of nan in the email address 
```

CONTEXT: dpiStmt_execute: check digits before decimal point
MESSAGE: DPI-1043: invalid number
Traceback (most recent call last):
  File "D:/sources/Andreas/Python/PyCSV/p1.py", line 401, in <module>
    print(dbimport_insuredpersons())
  File "D:/sources/Andreas/Python/PyCSV/p1.py", line 211, in dbimport_insuredpersons
    """, rec)
cx_Oracle.DatabaseError: DPI-1043: invalid number

```

3. Include a runnable Python script that shows the problem.

```
<snipped>
```

table sql 
```
<snipped>
```

4. Show the output of:

```
import sys
import platform

print("platform.platform:", platform.platform())
print("sys.maxsize > 2**32:", sys.maxsize > 2**32)
print("platform.python_version:", platform.python_version())

platform.platform: Windows-10-10.0.14393-SP0
sys.maxsize > 2**32: True
platform.python_version: 3.7.5
```

And:

```
import cx_Oracle
print("cx_Oracle.version:", cx_Oracle.version)
print("cx_Oracle.clientversion:", cx_Oracle.clientversion())

cx_Oracle.version: 7.3.0
cx_Oracle.clientversion: (12, 2, 0, 1, 0)
```

5. What is your Oracle Database version?
11.2.0.4

**Comment by cjbj** [comment]
What does it even mean to try to insert NAN into a VARCHAR2?  How this should be handled sounds like a data validation and filtering issue for the application.  It should be performed before you even get to cx_Oracle.  @anthony-tuininga may have other suggestions about input type handlers.

Pro tips:  
- don't post all your application code.  Although it's fun to see what people are using cx_Oracle for, it's better to post a minimal testcase.  This is easier for us to look at and doesn't give away your company information.
- use a connection pool if your app is being run as a service or web app.  You can set the date format with a [sessionCallback](https://cx-oracle.readthedocs.io/en/latest/user_guide/connection_handling.html#session-callbacks-for-setting-pooled-connection-state)
- Use a single PL/SQL block for your SQL statements to avoid all the round trips between the application and the database from all the `execute()` calls.  You can use `executemany()` with PL/SQL.

**Comment by Sajaki** [comment]
i think i got it. 
```
           if (isinstance(rec[16], (float))):
               rec[16] = None
```
this produces a proper null in the database.
