### ISSUE TITLE
Runtime issue: 'utf-8' codec can't decode byte 0xea invalid continuation byte

### ISSUE THREAD

**Issue by SpencerRP** [oracle/python-cx_Oracle#434]
I'm having an issue with downloading data from a corporate database. After a database change - that included upgrading the version and merging with an acquisition's database - I'm suddenly hitting decode errors. Most of the examples I've found of similar problems dealt with it by a) specifying a different character set like latin-1, b) throwing away the sample in question, c) editing the source to be workable, d) fixing a client / database character set mismatch. The first three aren't a solution for me, and I don't know if the latter applies in this case?

System info:
```platform.platform: Windows-10-10.0.14393-SP0
sys.maxsize > 2**32: True
platform.python_version: 3.6.5
cx_Oracle.version: 7.3.0
cx_Oracle.clientversion: (18, 5, 0, 0, 0)
```
Database version:
Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production

Results from running the queries on the globalization page:
```
SELECT value AS db_charset FROM nls_database_parameters WHERE parameter = 'NLS_CHARACTERSET'
[('AL32UTF8',)]
SELECT value AS db_ncharset FROM nls_database_parameters WHERE parameter = 'NLS_NCHAR_CHARACTERSET'
[('AL16UTF16',)]
SELECT DISTINCT client_charset AS client_charset FROM v$session_connect_info WHERE sid = SYS_CONTEXT('USERENV', 'SID')
[('AL32UTF8',)]
```

The code I ran is:
```
        def query(tabname, connection, sql):
            if (pd.isna(tabname)) or (tabname == None) or (len(str(tabname)) == 0):
                tabname = filename.rsplit('.')[0]
            
            con = cx_Oracle.connect(connection, encoding='UTF-8', nencoding = "UTF-16")
            cursor = con.cursor()
            cursor.arraysize = batch_size
            sql = sql.split("\nend;")
            sql = [sql[i] + "\nend;" if i < (len(sql) - 1) else sql[i] for i in range(len(sql))]
            for block in sql:
                cursor.execute(block)
            print('Connection established for "{}" with {} at: {}'.format(filename, connection, str(datetime.datetime.now())))
            
            data = []
            while True:
                records = cursor.fetchmany()
                if len(records) == 0:
                    break
                data.extend(records)
            df = pd.DataFrame(data, columns = [i[0] for i in cursor.description])
            print('Downloaded data for tab "{}" of file "{}" at {} '.format(tabname, filename, str(datetime.datetime.now())))
            
            for col in df.columns:
                if ('Date' in col) & ('datetime' not in str(df[col].dtype)):
                    #df[col] = pd.to_datetime(df[col])
                    print(col)
                    df[col] = df[col].astype(str)
                    df[col] = df[col].apply(lambda x: str(x))
                    
            print('Cleaned dataframe of tab "{}" for file "{}" at {} '.format(tabname, filename, str(datetime.datetime.now())))
            
            try:
                df.to_pickle(top + '\\pickle_files\\' + filename.rsplit('.')[0] + "_" + tabname + str(next(counter)) + "_output.pkl")
            except Exception as e:
                print(repr(e))
            
            print('Saved combined file for "{}" at {} '.format(filename, str(datetime.datetime.now())))
            return tabname, df
```
The error this outputs is:
```
"'utf-8' codec can't decode byte 0xea in position 22: invalid continuation byte /n UnicodeDecodeError('utf-8', b'[company name] Farmac\xeautica [company name]', 22, 23, 'invalid continuation byte')
```

What google suggests to resolve this:
1. Stack exchange says that if I set the connection to encode it to Latin-1 the problem will disappear. The client I'm coding this for has global branches who all use the same database for multiple languages and scripts, so I can't use that. (https://stackoverflow.com/questions/5552555/unicodedecodeerror-invalid-continuation-byte)
2. I could use Convert to shift strings into UTF-8. I don't know what complications this would add, however, and I'm not certain if the resulting string could be referenced back to the database easily. (https://www.oracletutorial.com/oracle-string-functions/oracle-convert/)
3. Your documentation on handling decode errors suggests using the outputtypehandler and setting it replace unreadable characters. As above, I'd rather not do that because someone may need to reference the result back against the database. (https://cx-oracle.readthedocs.io/en/latest/user_guide/sql_execution.html#codecerror)
4. I'm aware that there's more intricate handling I can do using outconverters, but your examples don't make it clear if they permit me to decode strings using them, e.g. a try and except method to use utf-8 and fall back on latin-1. I'd appreciate clarification/edification on that. (https://cx-oracle.readthedocs.io/en/latest/user_guide/sql_execution.html#outputtypehandlers) (https://github.com/oracle/python-cx_Oracle/blob/master/samples/TypeHandlers.py) (PS: I found the second link from a completely different website, maybe include a link to it in the first link or make it more noticeable if it's already there? You might also add a mention about outconverters in the codec error page.)

Any advice?

**Comment by cjbj** [comment]
- Can you confirm the same error occurs when you remove Pandas from the code?

- What's the query like? Are you splitting a string somehow?

- Can you confirm the datatype of the column with the problem?  (If it does happen to be NVARCHAR or similar, what happens if you set nencoding to UTF-8 ?)

- Have you tried [`SELECT DUMP()`](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/DUMP.html#GUID-A05793C9-B35D-4BA7-B68C-E3693BCF47A5) on the data to see if it looks valid?

- Point noted about the doc links - I'll add a link right now.  (A lot of ref guide sections need links to the user guide as well)

**Comment by SpencerRP** [comment]
Sorry, I could have sworn I replied to this yesterday.

My coworker tried just not specifying the encoding or nencoding when running it on the target computer, which I provided the information about, and it worked. It hadn't worked when I did this on my vdi. Possibly an update was pushed to match the database update, though I'm not sure. Any idea on why not specifying the encoding might have helped, for the record in case other people run into a similar issue?

You can close this ticket out, but to answer your questions:
- The problem occurred even when I removed pandas from the code.
- the query is pretty simple, and mostly consists of joins, rounding ints, and formatting dates.
- The datatype is varchar, and when the nencoding is set to UTF-8 it still breaks. UTF-8 was the original setting, actually, I set it to UTF-16 to see if that would fix anything.
- The data looks valid on previous extracts we've done, but when my coworker spun it to a csv two days ago it had a ? where the acute e should have been.

**Comment by anthony-tuininga** [comment]
If the data in the database is actually stored in `UTF-8` and your client character set is `UTF-8` then you should not get any errors at all. The fact that you are suggests that the data may not actually be stored in `UTF-8` at all but in some other encoding! When you do not specify the encoding you get the value of `NLS_LANG` which you can check by looking at the value of `connection.encoding` and `connection.nencoding` after the connection has been made. If you can find the source of the "bad" data you can do a `select dump(column)` on it as @cjbj suggested. You can also insert the results into another table and create a standalone test case that we can examine in greater detail if that's of interest.
