### ISSUE TITLE
Typo in cx_oracle.py docstring

### ISSUE THREAD

**Issue by thorstenkampe** [oracle/python-cx_Oracle#439]
Typo in line 103 of `cx_oracle.py`:
| In all cases however, the driver requires an explcit encoding configuration.
explcit -> explicit 

The typo has already spread via copy and paste to the [SQLAlchemy documentation](https://docs.sqlalchemy.org/en/13/dialects/oracle.html#ensuring-the-correct-client-encoding). I'll open a ticket with them, too.

**Comment by zzzeek** [comment]
I think the poster is referring to a file in SQLAlchemy, not in cx_oracle itself, so this can likely be closed.

**Comment by thorstenkampe** [comment]
Yes, my mistake. I didn't pay attention that `cx_oracle.py` belonged to the SQLAlchemy package. I'm closing the ticket.
