### ISSUE TITLE
dyld: lazy symbol binding failed: Symbol not found: _slzgetohorabase

### ISSUE THREAD

**Issue by shilohbradley** [oracle/python-cx_Oracle#443]
1. Review the [cx_Oracle Documentation](https://cx-oracle.readthedocs.io/en/latest/index.html).  Review your output and logs.  **Google any errors**

2. Describe the problem
Hello all. Sorry if I am doing any of this wrong. I have not opened a GitHub issue before. I'm having issues connecting to SQL through Python. When I run cx_Oracle.connect(), I get an error saying ```dyld: lazy symbol binding failed```. I'm not sure what I am doing wrong. I tried googling it. I am able to connect to Oracle through R just fine. Please advise and thank you for your time.

3. Include a runnable Python script that shows the problem.  Include all SQL needed to create the database schema.  Use Markdown syntax, see https://help.github.com/github/writing-on-github/basic-writing-and-formatting-syntax

```
>>> import cx_Oracle
>>> dsn_tns = cx_Oracle.makedsn('XXX', '1521', service_name='XXX') 
>>> conn = cx_Oracle.connect(user=r'XXX', password='XXX', dsn=dsn_tns) 
dyld: lazy symbol binding failed: Symbol not found: _slzgetohorabase
  Referenced from: /usr/local/oracle/instantclient12/libclntsh.dylib
  Expected in: flat namespace

dyld: Symbol not found: _slzgetohorabase
  Referenced from: /usr/local/oracle/instantclient12/libclntsh.dylib
  Expected in: flat namespace

Abort trap: 6
```

4. Show the output of:

```
platform.platform: Darwin-19.3.0-x86_64-i386-64bit
sys.maxsize > 2**32: True
platform.python_version: 3.6.5
```

And:

```
cx_Oracle.version: 8.0.0-dev

dyld: lazy symbol binding failed: Symbol not found: _slzgetohorabase
  Referenced from: /usr/local/oracle/instantclient12/libclntsh.dylib
  Expected in: flat namespace

dyld: Symbol not found: _slzgetohorabase
  Referenced from: /usr/local/oracle/instantclient12/libclntsh.dylib
  Expected in: flat namespace

Abort trap: 6
```

5. What is your Oracle Database version?
Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production

**Comment by shilohbradley** [comment]
I realized that my $ORACLE_HOME was pointing the wrong path. Once I updated this, the issue was resolved.

**Comment by cjbj** [comment]
It seems you are using Instant Client, so the advice we give is to never set ORACLE_HOME. It only causes problems, as you found.

**Comment by shilohbradley** [comment]
> It seems you are using Instant Client, so the advice we give is to never set ORACLE_HOME. It only causes problems, as you found.

Hi! Yes, I use Instant Client. This is good to know. Thanks!
