### ISSUE TITLE
SQLPlus runs but python script yields DPI-1047: Cannot locate a 64-bit Oracle Client library

### ISSUE THREAD

**Issue by fmnsantos** [oracle/python-cx_Oracle#446]
# Do these first

- Review and follow the [installation instructions](https://cx-oracle.readthedocs.io/en/latest/user_guide/installation.html)

- Review the [troubleshooting tips](https://cx-oracle.readthedocs.io/en/latest/user_guide/installation.html#troubleshooting)

- If you have a `DPI-1047`, `DPI-1050` or `DPI-1072` error, review both the above again before opening an issue.

- **Google any errors**

# Answer the following questions

1. Describe the problem and show the error you have.
**Cut and paste text showing the command you ran.  No screenshots.  Use a gist for long screen output and logs: see https://gist.github.com/**.

My PC has Windows 10 64-bit version 1903 installed.
I have performed the following actions:
- Installed Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019 - 64-Bit
- Installed Oracle Instant Client version 19.6 (64-bit) at C:\oracle\instantclient_19_6
- Set the PATH variable to point to: C:\oracle\instantclient_19_6
- Installed SQLPlus package at C:\oracle\instantclient_19_6
- Installed python 3.8.3 64-bit.
- Installed cx_Oracle with the following command: pip3 install cx_Oracle --upgrade

After running the following script with python3:

import cx_Oracle
con = cx_Oracle.connect("username/pasword@ip-address:1521/orcl")

I get the following error: DPI-1047: Cannot locate a 64-bit Oracle Client library.

I am able to run sqlplus to connect to the same machine, using the same connection string used in the above script without any issues:
sqlplus user/password@ip-address:1521/orcl

2. Show the output of:

```
import sys
import platform

print("platform.platform:", platform.platform())
print("sys.maxsize > 2**32:", sys.maxsize > 2**32)
print("platform.python_version:", platform.python_version())
```

The above script yields:
platform.platform: Windows-10-10.0.18362-SP0
sys.maxsize > 2**32: True
platform.python_version: 3.8.3

3. Show the directory listing where your Oracle client libraries are installed (e.g. the Instant Client directory).  Is it 64-bit or 32-bit?
The Oracle client libraries are 64-bit

Directory listing:
adrci.exe
adrci.sym
BASIC_LICENSE
BASIC_README
genezi.exe
genezi.sym
glogin.sql
oci.dll
oci.sym
ocijdbc19.dll
ocijdbc19.sym
ociw32.dll
ociw32.sym
ojdbc8.jar
oramysql19.dll
oramysql19.sym
orannzsbb19.dll
orannzsbb19.sym
oraocci19.dll
oraocci19.sym
oraocci19d.dll
oraocci19d.sym
oraociei19.dll
oraociei19.sym
oraons.dll
orasql19.dll
orasql19.sym
orasqlplusic19.dll
sqlplus.exe
sqlplus.sym
SQLPLUS_LICENSE
SQLPLUS_README
ucp.jar
uidrvci.exe
uidrvci.sym
xstreams.jar

4. Show what the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) is set to?  On macOS, show what is in `~/lib`.

Path=C:\oracle\instantclient_19_6;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Users\farma\AppData\Local\Microsoft\WindowsApps;C:\Users\farma\AppData\Local\Microsoft\WindowsApps;

5. Show any Oracle environment variables set (e.g. ORACLE_HOME, ORACLE_BASE).
ORACLE_HOME=C:\oracle\instantclient_19_6

**Comment by cjbj** [comment]
Are you running Python and SQL*Plus from the exact same cmd terminal?

*Do not set ORACLE_HOME when using Instant Client.*

The installation instructions are at https://cx-oracle.readthedocs.io/en/latest/user_guide/installation.html#installing-cx-oracle-on-windows

**Comment by fmnsantos** [comment]
Thanks for the quick reply.

I have unset ORACLE_HOME. The problem remains.

I have run Python and SQLPlus from the same cmd terminal.

**Comment by rignizio** [comment]
I am running into the same issue:

`> python .\test.py
sys.maxsize > 2**32: True
platform.python_version: 3.7.7
cx_Oracle.version: 7.3.0
Traceback (most recent call last):
  File ".\test.py", line 13, in <module>
    print("cx_Oracle.clientversion:", cx_Oracle.clientversion())
cx_Oracle.DatabaseError: DPI-1047: Cannot locate a 64-bit Oracle Client library: "The specified module could not be found`

**Comment by rignizio** [comment]
I installed Python 3.6.8 and it got it working. It had failed with 3.7.7 and 3.8.3.

**Comment by fmnsantos** [comment]
Thank you for your feedback, rignizio.
BR
