### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 631

### ISSUE THREAD

**Issue by DFrijmersum** [oracle/python-cx_Oracle#45]
Hi,

I'm trying to apply bag-of-Words to a text dataset by running the following code: 
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer().fit(text_train)
Xtrain = vect.transform(text_train)

But I get the following UnicodeDecodeError:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 631: invalid start byte

What does this mean and how can I fix this? What is position 631?

**Comment by cjbj** [comment]
If you search, you will see other have reported this but a decisive answer hasn't been found.  It may be related to the VS Redistributables.

You could help by letting us know some details.  Can you answer the questions in the Issue template? See https://github.com/oracle/python-cx_Oracle/blob/master/.github/issue_template.md#answer-the-following-questions

**Comment by DFrijmersum** [comment]
Answer the following questions:

  1.  What is your version of Python? 64-bit?
  2.  What is your version of cx_Oracle? Can’t install it? Get an error/exception
Exception:
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Program Files\Anaconda3\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "C:\Program Files\Anaconda3\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "C:\Program Files\Anaconda3\lib\site-packages\pip\req\req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "C:\Program Files\Anaconda3\lib\site-packages\pip\req\req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "C:\Program Files\Anaconda3\lib\site-packages\pip\wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "C:\Program Files\Anaconda3\lib\site-packages\pip\wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "C:\Program Files\Anaconda3\lib\shutil.py", line 115, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files\\Anaconda3\\Lib\\site-packages\\cx_Oracle.cp36-win_amd64.pyd'

  1.  What is your version of the Oracle client (e.g. Instant Client)? How was it installed? Where is it installed?
  2.  What is your version of the Oracle Database? Don’t have one
  3.  What is your OS and version? I have windows
  4.  What compiler version did you use? For example, with GCC, run gcc --version. No idea. Don’t know
  5.  What environment variables did you set? How exactly did you set them? I’m in python jupyter notebook
  6.  What exact command caused the problem (e.g. what command did you try to install with)? Who were you logged in as?

What error(s) you are seeing? In jupyter notebook I get the following error: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 631: invalid start byte



Van: Christopher Jones [mailto:notifications@github.com]
Verzonden: woensdag 5 juli 2017 11:55
Aan: oracle/python-cx_Oracle <python-cx_Oracle@noreply.github.com>
CC: DFrijmersum <Derk.frijmersum@outlook.com>; Author <author@noreply.github.com>
Onderwerp: Re: [oracle/python-cx_Oracle] UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 631 (#45)


If you search, you will see other have reported this but a decisive answer hasn't been found. It may be related to the VS Redistributables.

You could help by letting us know some details. Can you answer the questions in the Issue template? See https://github.com/oracle/python-cx_Oracle/blob/master/.github/issue_template.md#answer-the-following-questions

**Comment by anthony-tuininga** [comment]
This is the same issue as #40. The reason for the differences in the error message are simply due to whichever language/message is trying to be displayed!
