### ISSUE TITLE
Does cx_Oracle supports Advanced Queues with multiple consumers

### ISSUE THREAD

**Issue by rafaelreuber** [oracle/python-cx_Oracle#453]
Does cx_Oracle supports Advanced Queues with multiple consumers? I can't find any information about multiple consumers on the Advanced Queuing (AQ) [docs](https://cx-oracle.readthedocs.io/en/latest/user_guide/aq.html#oracle-advanced-queuing-aq).

**Comment by anthony-tuininga** [comment]
Yes, it does. I'll have to see if I can create an example for you -- and to make sure that it still works, of course!

**Comment by anthony-tuininga** [comment]
Here is an example with multiple subscribers using the existing raw AQ sample as a starting point. The SQL:

```sql
begin

    dbms_aqadm.create_queue_table('ISSUE_453_TAB', 'RAW',
            multiple_consumers => true);
    dbms_aqadm.create_queue('ISSUE_453_QUEUE', 'ISSUE_453_TAB');
    dbms_aqadm.start_queue('ISSUE_453_QUEUE');

    dbms_aqadm.add_subscriber('ISSUE_453_QUEUE',
            sys.aq$_agent('SUBSCRIBER_A', null, null));
    dbms_aqadm.add_subscriber('ISSUE_453_QUEUE',
            sys.aq$_agent('SUBSCRIBER_B', null, null));

end;
/
```

The Python code:

```python
import cx_Oracle

QUEUE_NAME = "ISSUE_453_QUEUE"
PAYLOAD_DATA = [
    "The first message",
    "The second message",
    "The third message",
    "The fourth and final message"
]

# connect to database
connection = cx_Oracle.connect("user/password@dsn")
cursor = connection.cursor()

# create queue
queue = connection.queue(QUEUE_NAME)
queue.deqOptions.wait = cx_Oracle.DEQ_NO_WAIT
queue.deqOptions.navigation = cx_Oracle.DEQ_FIRST_MSG

# enqueue a few messages
print("Enqueuing messages...")
for data in PAYLOAD_DATA:
    print(data)
    queue.enqOne(connection.msgproperties(payload=data))
connection.commit()
print()

# dequeue the messages for consumer A
print("Dequeuing the messages for consumer A...")
queue.deqOptions.consumername = "SUBSCRIBER_A"
while True:
    props = queue.deqOne()
    if not props:
        break
    print(props.payload.decode())
connection.commit()
print()

# dequeue the message for consumer B
print("Dequeuing the messages for consumer B...")
queue.deqOptions.consumername = "SUBSCRIBER_B"
while True:
    props = queue.deqOne()
    if not props:
        break
    print(props.payload.decode())
connection.commit()
print()

print("Done.")
```

This produces the following output:

```
Enqueuing messages...
The first message
The second message
The third message
The fourth and final message

Dequeuing the messages for consumer A...
The first message
The second message
The third message
The fourth and final message

Dequeuing the messages for consumer B...
The first message
The second message
The third message
The fourth and final message

Done.
```

Hope that's of help!

**Comment by rafaelreuber** [comment]
Thank you for your help @anthony-tuininga! Would be nice the have a recipes session on the https://cx-oracle.readthedocs.io. We can move all sample scripts to this recipes session.

**Comment by cjbj** [comment]
@rafaelreuber we are continually improving the doc, e.g. to add content, to add cross references between sections, and to link to appropriate samples in https://github.com/oracle/python-cx_Oracle/tree/master/samples. [Contributions](https://github.com/oracle/python-cx_Oracle/blob/master/CONTRIBUTING.md) are welcome.

**Comment by cjbj** [comment]
@rafaelreuber I just put @anthony-tuininga's script in a form suitable for adding the samples directory and sent it off to him for review.

**Comment by anthony-tuininga** [comment]
Its been uploaded and can be found [here](https://github.com/oracle/python-cx_Oracle/blob/master/samples/MultiConsumerAQ.py).
