### ISSUE TITLE
cx_Oracle 8.0 has been released

### ISSUE THREAD

**Issue by cjbj** [oracle/python-cx_Oracle#456]
Python cx_Oracle 8.0 is now Production on PyPI.  This release adds an API for specifying the location of the Oracle Client libraries and optional configuration files.  The default character set is now UTF-8.  A new prefetchrows attribute allows further tuning of query fetch performance.  And there’s more!  Note this release supports Python 3 only.  

My release blog post announcements is at: https://blogs.oracle.com/opal/the-new-cx_oracle-80-release-brings-easier-configuration

**Comment by rafaelreuber** [comment]
Good job folks!

**Comment by ThiefMaster** [comment]
Thanks for not adding [`python_requires`](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires) metadata. 😡

Now Python 2 users (yeah, I know, EOL and everything. but moving away takes some time) will get 8.0 as well just to fail in setup.py. And due to the way how python packaging works this is not something you can fix anymore (without yanking the released package which would be a bad idea for various reasons).

**Comment by cjbj** [comment]
There's no need to be rude about it.  If we didn't know about something and made a mistake, then we're sorry.  We don't like making things hard for users either.

If you want to share your knowledge and help keep the project in great shape throughout each development cycle [contributions](https://github.com/oracle/python-cx_Oracle/blob/master/CONTRIBUTING.md) are always welcome.

(For future readers coming across this, [here](https://cx-oracle.readthedocs.io/en/latest/user_guide/installation.html#installing-cx-oracle-in-python-2) are the notes on installing with Python 2.)

**Comment by ThiefMaster** [comment]
You are right, I was just a bit annoyed since it broke my build. Updated my comment to be nicer.

**Comment by anthony-tuininga** [comment]
I've added the necessary metadata. I wasn't aware that it existed so my apologies -- and thanks for bringing it to my attention! We can't fix the 8.0.0 build but if we make a 8.0.1 release that should resolve your issue, I believe? Please advise!

**Comment by ThiefMaster** [comment]
Unfortunately not, since `pip` will still see 8.0.0 as a valid version, so adding the metadata now will only result in newer versions being hidden from incompatible python versions.

**Comment by anthony-tuininga** [comment]
Ah. So it will see that versions later than 8.0.0 are invalid but there's this lovely 8.0.0 that you can upgrade to. Sigh. Again, my apologies.

**Comment by ThiefMaster** [comment]
Yeah, it's really annoying that this particular metadata cannot be added retroactively. :/

**Comment by anthony-tuininga** [comment]
Indeed!

**Comment by anthony-tuininga** [comment]
Hmm, looks like PyPI has the ability to "yank" a release. That means that it is ignored unless you explicitly ask for it as in

```
pip install cx_Oracle=8.0.0
```

This is documented in [PEP 592](https://www.python.org/dev/peps/pep-0592). That might resolve it for you, right?

**Comment by ThiefMaster** [comment]
Indeed. I hadn't realized that this was finally implemented!

**Comment by sharkguto-gmf-tech** [comment]
when will be available the asyncio driver??? We are in 2020 :)

**Comment by anthony-tuininga** [comment]
All I can say is that it is under consideration and that I have no idea if/when it will be available! Even though asyncio has been around for some time many of the frameworks are just starting to add support for it!

**Comment by anthony-tuininga** [comment]
@ThiefMaster, cx_Oracle 8.0.1 has been released with specific support for the metadata tag that tells Python 2 to leave it alone and cx_Oracle 8.0.0 has been yanked. So if you do `pip install cx_Oracle` with Python 2 you will now get version 7.3 directly. Apologies it took so long to get this done -- but its done now!

**Comment by wgwz** [comment]
I'm seeing this in a install process:

```
WARNING: The candidate selected for download or install is a yanked version: 'cx-Oracle' candidate (version 8.0.0 at https://files.pythonhosted.org/packages/4a/f2/a81884da5af209cfbde1ce1ea90c8f6b0497c7f475fefe5c43cb94610f8a/cx_Oracle-8.0.0-cp38-cp38-manylinux1_x86_64.whl#sha256=fb5beb3ad5a102d8276e0c7dac68fab6aa63cc49afe1ccc9e3709071a3b95c64 (from https://pypi.org/simple/cx-oracle/))
Reason for being yanked: <none given>
Collecting cx_Oracle==8.0.0
  Downloading cx_Oracle-8.0.0-cp38-cp38-manylinux1_x86_64.whl (781 kB)
```

Of course I can bump to the latest version. I suppose I just wanted to add it here. It did raise a red flag when I noticed it, i.e. was this pulled for a security vulnerability?

**Comment by anthony-tuininga** [comment]
The reason it was yanked is because Python 2 was trying to install it -- and Python 2 is incapable of running cx_Oracle 8. cx_Oracle 8.0.1 specifically adds the metadata necessary to tell Python 2 to ignore it but cx_Oracle 8.0.0 had to be yanked or Python 2 would continue to try to install it! Hope that makese sense to you! I would have put a reason but wasn't sure what would make sense there.

**Comment by wgwz** [comment]
That makes sense, I just wanted to check and add a comment here because I’m sure others will be curious as well. Google search will perhaps bring them here :-)
