### ISSUE TITLE
bind multiple of the same var

### ISSUE THREAD

**Issue by Syniex** [oracle/python-cx_Oracle#457]
1. Review the [cx_Oracle Documentation](https://cx-oracle.readthedocs.io/en/latest/index.html).  Review your output and logs.  **Google any errors**

2. Describe the problem
**I am trying to bind to a query var multiple time, but it never success
Is it possible?**.

3. Include a runnable Python script that shows the problem.  Include all SQL needed to create the database schema.  Use Markdown syntax, see https://help.github.com/github/writing-on-github/basic-writing-and-formatting-syntax

```import cx_Oracle
from app.core.config import (
    DATABASE_PASSWORD,
    DATABASE_URL,
    DATABASE_USERNAME,
    MAX_CONNECTIONS_COUNT,
    MIN_CONNECTIONS_COUNT,
)
from pprint import pprint

TEST_QUERY = """
SELECT :1,:2 FROM DUAL WHERE :1 = :2 OR :3
"""


pool = cx_Oracle.SessionPool(
    user=DATABASE_USERNAME,
    password=str(DATABASE_PASSWORD),
    dsn=DATABASE_URL,
    min=MIN_CONNECTIONS_COUNT,
    max=MAX_CONNECTIONS_COUNT,
    encoding="UTF8",
    threaded=True,
    getmode=cx_Oracle.SPOOL_ATTRVAL_TIMEDWAIT,
)

with pool.acquire() as conn:
    with conn.cursor() as cursor:
        cursor.execute(TEST_QUERY,("TEST","TEST","as"))
        cursor.rowfactory = lambda *args: dict(
                zip([d[0] for d in cursor.description], args)
            )
        results = cursor.fetchall()
        pprint(results)
```

4. Show the output of: cx_Oracle.DatabaseError: ORA-01008: not all variables bound

```
platform.platform: Linux-5.3.0-55-generic-x86_64-with-Ubuntu-19.10-eoan
platform.python_version: 3.7.5

```

And:

```
cx_Oracle.version: 8.0.0
cx_Oracle.clientversion: (19, 6, 0, 0, 0)

```

5. What is your Oracle Database version? 18c

**Comment by cjbj** [comment]
It's possible with a few small limitations and quirks to do with PL/SQL vs SQL, and with the RETURNING INTO statement. 

Your SQL syntax was invalid, and the binding needs some work too.

```
TEST_QUERY = """
SELECT :1,:2 FROM DUAL WHERE :1 = :2 OR :1 = :3
"""

with connection.cursor() as cursor:
    cursor.execute(TEST_QUERY,{"1": "TEST", "2": "TEST","3": "as"})
    results = cursor.fetchall()
    print(results)
```
The position of the array values corresponds to the position of the SQL bind parameters as they occur in the statement, regardless of their names.  This is still true even if the bind parameters are named like `:0`, `:1`, etc. 

Alphabetic names are recommended when using duplicate names due the confusion you hit:

```
TEST_QUERY = """
SELECT :a,:b FROM DUAL WHERE :a = :b OR :a = :c
"""

with connection.cursor() as cursor:
    cursor.execute(TEST_QUERY,{"a": "TEST2", "b": "TEST2","c": "as2"})
    results = cursor.fetchall()
    print(results)
```

If you want the details (which I've made a note to add to the documentation):

In the context of SQL statements, the input array position ‘n’ indicates the bind parameter at the n’th position in the statement. However, in the context of PL/SQL statements the position ‘n’ in the bind call indicates a binding for the n’th unique parameter name in the statement when scanned left to right.  It's easier to use named binds, as mentioned above.

In a DML statement with a `RETURNING` clause no duplication is allowed between bind parameters in the DML section and the `RETURNING` section of the statement.
