### ISSUE TITLE
Oracle instant client 19.3

### ISSUE THREAD

**Issue by sdamte0428** [oracle/python-cx_Oracle#458]
# Do these first

- Review and follow the [installation instructions](https://oracle.github.io/node-oracledb/INSTALL.html)

- Review the [troubleshooting tips](https://oracle.github.io/node-oracledb/INSTALL.html#troubleshooting)

- If you have a `DPI-1047`, `DPI-1050` or `DPI-1072` error, review both the above again before opening an issue.

# Answer the following questions

1. Describe the problem and show the error you have.
**Cut and paste text showing the command you ran.  No screenshots.  Use a gist for long screen output and logs: see https://gist.github.com/**.

2. What Node.js version are you using?  Run node and show the output of:

```
process.platform
process.version
process.arch
require('oracledb').versionString
require('oracledb').oracleClientVersionString
```

3. Are you installing into vanilla Node.js, or using something like Electron?

4. Show the directory listing where your Oracle client libraries are installed (e.g. the Instant Client directory).  Is it 64-bit or 32-bit?

5. Show what the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) are set to?  On macOS, show what is in `~/lib`.

6. Show any Oracle environment variables set (e.g. ORACLE_HOME, ORACLE_BASE).

**Comment by cjbj** [comment]
@sdamte0428 I've transferred this issue to the correct repo.   Please take care when logging issues - thanks!

The command you gave is effectively given in the instructions https://cx-oracle.readthedocs.io/en/latest/user_guide/installation.html#installing-cx-oracle-on-macos

I'm glad you are able to get cx_Oracle running now we've worked around the newer macOS restrictions.

**Comment by sdamte0428** [comment]
Yes, its given in the instruction.
used :
https://www.oracle.com/database/technologies/instant-client/downloads.html
first this one and was working fine for SQL Plus . Then followed the top
link by clearing out everything first



https://cx-oracle.readthedocs.io/en/latest/user_guide/installation.html#installing-cx-oracle-on-macos


Thanks,
Selam
