### ISSUE TITLE
6.0rc1: linux rpm 

### ISSUE THREAD

**Issue by az-z** [oracle/python-cx_Oracle#46]
#### Answer the following questions:

1. What is your version of Python? Is it 32-bit or 64-bit?
Python 3.5.3

2. What is your version of cx_Oracle?
rpm -qa | grep cx_
cx_Oracle-6.0rc1-1.x86_64

3. What is your version of the Oracle client (e.g. Instant Client)?  How was it
   installed?  Where is it installed?
rpm -qa | grep oracle
oracle-instantclient12.2-basic-12.2.0.1.0-1.x86_64
rpm -ql oracle-instantclient12.2-basic-12.2.0.1.0-1.x86_64
/usr/lib/oracle/12.2/client64/bin/

4. What is your version of the Oracle Database?
TimesTen 11g Release 2 (11.2.2.8.0)
5. What is your OS and version?
Linux 4.10.14-200.fc25.x86_64 ( Fedora 25 )

6. What compiler version did you use?  For example, with GCC, run
   `gcc --version`.
gcc (GCC) 6.3.1 20161221 (Red Hat 6.3.1-1)

7. What environment variables did you set?  How *exactly* did you set them?
export LD_LIBRARY_PATH=/opt/oracle/instantclient_12_2:$LD_LIBRARY_PATH

8. What *exact* command caused the problem (e.g. what command did you try to
   install with)?  Who were you logged in as?
as root:
dnf install /home/az/Downloads/cx_Oracle-6.0rc1-py35-1.x86_64.rpm

9. What error(s) you are seeing?
in python3.5 
import cx_Oracle
fails with wit "unable to import module"
upon digging it appears that the rpm installs the cx module in the non standard location - 
rpm -ql cx_Oracle-6.0rc1-1
/opt/rh/rh-python35/root/usr/lib64/python3.5/site-packages/

vs:
/usr/lib[64]/python3.5/site-packages/

the manual install of the wheel:
python3 install /home/az/Downloads/cx_Oracle-6.0rc1-cp35-cp35m-manylinux1_x86_64.whl
places the cx_ package into the standard - usr/lib64/python3.5/site-packages/

Also,
 i'm not sure of the wheel installs the samples and tests files provided by rpm ( /usr/share/doc/cx_Oracle-6.0rc1). If it doesn't, it would be great to add to the wheel, please.

**Comment by anthony-tuininga** [comment]
Oracle Linux (and Red Hat Enterprise Linux) are dated from 4-5 years ago which had Python 2 as the system Python installation. When they added support for Python 3 as an option, they decided to put it in a different location as you can see. Fedora uses the standard location instead. As such, the RPMs are really only usable by Oracle Linux and RHEL/CentOS -- at least without changes!

The wheels currently do not include the samples and tests. I'll take a look at what would be required to include them.

**Comment by az-z** [comment]
Maybe then it would be better to name rpms to indicate that they are for
RH only?
Or better else somehow pull the default library directory on the system?

**Comment by anthony-tuininga** [comment]
> Maybe then it would be better to name rpms to indicate that they are for RH only?

That's one possibility I'll consider.

> Or better else somehow pull the default library directory on the system?

I'm not sure if that is possible but I'll take a look. I agree this is a better option if it is possible.

**Comment by cjbj** [comment]
> The wheels currently do not include the samples and tests. I'll take a look at what would be required to include them.

@anthony-tuininga I wouldn't include samples & tests in Wheels.  For Node.js, we ended up taking  them out out of the node-oracledb install since they were getting big, and added a lot of cruft that most people don't use.

**Comment by anthony-tuininga** [comment]
Recently a [decision was made](https://www.python.org/dev/peps/pep-0527/) to remove the ability to upload RPM files to PyPI, so this issue is no longer relevant. If and when RPM files are produced they will be included in the repository for Oracle Linux and therefore it will be clear for which OS they are intended.
