### ISSUE TITLE
Unable to Startup Oracle DB Remotely using python

### ISSUE THREAD

**Issue by goyalsumeet31** [oracle/python-cx_Oracle#461]
Hi ,

I am creating python to bounce the remote Oracle DB ( DB Version : 12.2.0.1) . The shutdown Function is working without any error . 

However at the startup function it is giving below error . The password for sys is correct as it has worked for Shutdown function

Python Version :2.7
cx_Oracle Version : 7.3
Oracle Instant Client : 18c

Kindly looks into it

Error:
------
cx_Oracle.DatabaseError: ORA-01017: invalid username/password; logon denied

Code:
------------------

```
import cx_Oracle
import os

def SHUTDOWN_DB():
    print " = = = = = SHUTDOWN INITIATED = = = = = "
    conn.shutdown(mode=cx_Oracle.DBSHUTDOWN_IMMEDIATE)
    cur = conn.cursor()
    cur.execute('ALTER DATABASE CLOSE NORMAL')
    cur.execute('ALTER DATABASE DISMOUNT')
    conn.shutdown(mode=cx_Oracle.DBSHUTDOWN_FINAL)
    print " = = = = = SHUTDOWN COMPLETED = = = = = "
    cur.close()

def STARTUP_DB():
    print " = = = = = STARTUP INITIATED = = = = = "
    conn = cx_Oracle.connect(user='sys',password='manager@123',mode=cx_Oracle.SYSDBA | cx_Oracle.PRELIM_AUTH,dsn=tns)
    conn.startup()
    conn = cx_Oracle.connect(user='sys',password='manager@123',mode=cx_Oracle.SYSDBA,dsn=tns)
    cur = conn.cursor()
    cur.execute('ALTER DATABASE MOUNT')
    cur.execute('ALTER DATABASE OPEN')
    print " = = = = = STARTUP COMPLETED = = = = = "
    cur.close()

tns=cx_Oracle.makedsn('apps1159.in.corp.sa','1522',service_name='RAVDB.in.corp.sa')

print "Initiating DB bounce"
SHUTDOWN_DB()
STARTUP_DB()
print "DB bounce Completed"
```
-----------------------

**Comment by cjbj** [comment]
[I updated the formatting on your post - please review the markdown syntax for next time]

You probably need to configure the Oracle Net listener to use [static service registration](https://www.oracle.com/pls/topic/lookup?ctx=dblatest&id=GUID-0203C8FA-A4BE-44A5-9A25-3D1E578E879F) by adding a `SID_LIST_LISTENER` entry to the database listener.ora file.  Review that doc link for details.

**Comment by goyalsumeet31** [comment]
Thanks for the update  .

I have added static service Registration in Remote DB . 

However the initial error has gone and new error was observed which is below

ERROR:
ORA-28547: connection to server failed, probable Oracle Net admin error

After reviewing oracle support notes . They suggested to Remove the below line from the static registration under SID_LIST_LISTENER

 To be removed -->  (PROGRAM=extproc)))

The issue is now Fixed  after remove the above line

Regards,
Sumeet Goyal
