### ISSUE TITLE
ezconnect protocol as argument while connecting to the database

### ISSUE THREAD

**Issue by nchillal** [oracle/python-cx_Oracle#466]
19c onwards ezconnect support passing protocol while connecting to the database, please provide a way for passing protocol as an argument while connecting to database. Right now we need to define it in tnsnames.ora file if we need to connect to the database via TCPS. 

```
cx_Oracle.connect('hr', 'hrpwd', 'tcp', 'localhost:1567/orcl')
cx_Oracle.connect('hr', 'hrpwd', 'tcps', 'localhost:1521/orcl')
```

**Comment by cjbj** [comment]
You can pass the protocol as part of the EZ connect string when using 19c client.  See the tech article [Oracle Database 19c Easy Connect Plus Configurable Database Connection
Syntax](https://download.oracle.com/ocomdocs/global/Oracle-Net-19c-Easy-Connect-Plus.pdf):

```
tcps://salesserver1:1521/sales.us.example.com
```

Is this what you wanted?  

I don't think `connect()` should change.  Possibly `make_dsn()` could, but that is a bigger topic of discussion.

**Comment by nchillal** [comment]
Oops yes thanks connect works. I tried makedsn and assumed connect also doesn't work. Yes it would be nice to have makedsn also work but that's not what I raised this issue for. 

Thanks.
