### ISSUE TITLE
TimesTen: suggestion

### ISSUE THREAD

**Issue by az-z** [oracle/python-cx_Oracle#47]
Not an issue, since CX_ doesn't officially support TimesTen, but i figured it would be nice: 
a. either include the support into the roadmap
b. note that TT can be used with the cx_.

**Comment by az-z** [comment]
I'll take my suggestions to the mailing list. Please ignore the issue.

**Comment by cjbj** [comment]
@az-z the TimesTen team is (of course) keen for language APIs to be able to work with TimesTen.  There was a PHP effort a while back, see this very old article [Installing PHP and the Oracle TimesTen In-Memory Database on Linux](http://www.oracle.com/technetwork/articles/dsl/php-timesten-linux-1594604.html), and more recently we've had some talk about ODPI-C but no solid work.

Have you tried using the TT DSN as the connect string?

**Comment by az-z** [comment]
@christinabrashear 
Chirstopher,
 > .. Have you tried using the TT DSN as the connect string?
I haven't tried. But what worked for me is to use OCI with connect string like : 
`connection = cx_Oracle.Connection("user/pass@127.0.0.1/DB:timesten:direct")`
like in :
`connection = cx_Oracle.Connection("user/pass@127.0.0.1/TT_1122:timesten:direct")`

i haven't noticed any difference if i were to use :`timestendirect`
full disclosure - i just got this setup to work, so there maybe some differences i'm not aware of.
