### ISSUE TITLE
cx_Oracle with multiprocessing works on Windows 10 but doesn't work on CentOS 7.6

### ISSUE THREAD

**Issue by thiagodma** [oracle/python-cx_Oracle#470]
1. System
**Database version: 12c
platform.platform: Linux-3.10.0-957.5.1.e17.x86_64-with-centos-7.6.1810-Core
sys.maxsize > 2^32: True
platform.python_version: 3.6.9
cx_Oracle.version: 8.0.0
cx_Oracle.clientversion: (19,8,0,0,0)**

2. Is it an error or a hang or a crash? 
**Error**

3. What error(s) or behavior you are seeing?
**The connections generated by pool.acquire() are not working, the return from isOpen is _False_ sometimes. The problem only happens when using more than one cpu on multiprocessing.Pool. Also, when I run the exact same code on windows 10, there is no problem at all (even if multiprocessing.Pool(4))**

4. Include a runnable Python script that shows the problem.

```
import cx_Oracle, time
from multiprocessing import Pool

pool = cx_Oracle.SessionPool("user","password","dsn",min=4,max=10,increment=1)

def test(i):
    conn = pool.acquire()
    print(isOpen(conn)) #if conn is ok it prints True, else it prints False. If it is working it should always print True
    cur = conn.cursor()
    cur.execute("select * from flxstg.actb_daily_log")
    cur.close()
    conn.close()

def isOpen(conn):
    try:
        return conn.ping() is None
    except:
        return False

if __name__ == "__main__":
    p = Pool(4) #if I run with Pool(1) it works
    st = time.time()
    r = p.map_async(test,range(50))
    r.get()
    print(time.time()-st)
```

**The output I get from the code above is (I don't get the same output always though... That's why I believe the main problem is that the some of the connections acquired from pool are bad.):**

```
True
True
True
False
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/lib64/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/opt/rh/rh-python36/root/lib64/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "bla.py", line 26, in test
    r  = cur.execute("select * from flxstg.actb_daily_log")
cx_Oracle.DatabaseError: ORA-12592: TNS:bad packet
"""
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "bla.py", line 47, in <module>
    r.get()
  File "/opt/rh/rh-python36/root/lib64/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
cx_Oracle.DatabaseError: ORA-12592: TNS:bad packet
```

**Comment by anthony-tuininga** [comment]
The use of ``multiprocessing`` is not supported. A connection must be established and queried within the *same* process. Depending on how the processes are started and how much memory is "shared" between the two you might get partial success -- but that's just luck, unfortunately!

**Comment by thiagodma** [comment]
Hi @anthony-tuininga , thank you for your answer. 

I just don't understand why the exact same code works on windows 10. It is working perfectly fine, I'm not getting any issues related to connection and I'm getting the speed up because of multiprocessing. 

Do you really think there's not a way to make it work on CentOS?

**Comment by anthony-tuininga** [comment]
It might be working on Windows 10 currently but as I mentioned in my previous post -- that's just luck! I wouldn't count on it continuing to work that way. You can certainly use multiprocessing -- but each of the workers in the process pool needs to have its *own* connection which it established itself. You can't create a session pool in one process and then acquire a connection from that pool in a worker process.

**Comment by anthony-tuininga** [comment]
No, its never been supported. If you look carefully at that post you'll see that it is doing what I am suggesting you do: create a connection inside the worker process instead of creating the connections inside the main process!

**Comment by thiagodma** [comment]
Hi @anthony-tuininga , thank you for your help! Creating the connection inside the worker process was the right way to go.

**Comment by anthony-tuininga** [comment]
You're welcome! I'm assuming your question has been answered now and will close this. Feel free to reopen if needed, though!

**Comment by bestathena** [comment]
> 1. System
>    **Database version: 12c
>    platform.platform: Linux-3.10.0-957.5.1.e17.x86_64-with-centos-7.6.1810-Core
>    sys.maxsize > 2^32: True
>    platform.python_version: 3.6.9
>    cx_Oracle.version: 8.0.0
>    cx_Oracle.clientversion: (19,8,0,0,0)**
> 2. Is it an error or a hang or a crash?
>    **Error**
> 3. What error(s) or behavior you are seeing?
>    **The connections generated by pool.acquire() are not working, the return from isOpen is _False_ sometimes. The problem only happens when using more than one cpu on multiprocessing.Pool. Also, when I run the exact same code on windows 10, there is no problem at all (even if multiprocessing.Pool(4))**
> 4. Include a runnable Python script that shows the problem.
> 
> ```
> import cx_Oracle, time
> from multiprocessing import Pool
> 
> pool = cx_Oracle.SessionPool("user","password","dsn",min=4,max=10,increment=1)
> 
> def test(i):
>     conn = pool.acquire()
>     print(isOpen(conn)) #if conn is ok it prints True, else it prints False. If it is working it should always print True
>     cur = conn.cursor()
>     cur.execute("select * from flxstg.actb_daily_log")
>     cur.close()
>     conn.close()
> 
> def isOpen(conn):
>     try:
>         return conn.ping() is None
>     except:
>         return False
> 
> if __name__ == "__main__":
>     p = Pool(4) #if I run with Pool(1) it works
>     st = time.time()
>     r = p.map_async(test,range(50))
>     r.get()
>     print(time.time()-st)
> ```
> 
> **The output I get from the code above is (I don't get the same output always though... That's why I believe the main problem is that the some of the connections acquired from pool are bad.):**
> 
> ```
> True
> True
> True
> False
> multiprocessing.pool.RemoteTraceback:
> """
> Traceback (most recent call last):
>   File "/opt/rh/rh-python36/root/lib64/python3.6/multiprocessing/pool.py", line 119, in worker
>     result = (True, func(*args, **kwds))
>   File "/opt/rh/rh-python36/root/lib64/python3.6/multiprocessing/pool.py", line 44, in mapstar
>     return list(map(*args))
>   File "bla.py", line 26, in test
>     r  = cur.execute("select * from flxstg.actb_daily_log")
> cx_Oracle.DatabaseError: ORA-12592: TNS:bad packet
> """
> The above exception was the direct cause of the following exception:
> Traceback (most recent call last):
>   File "bla.py", line 47, in <module>
>     r.get()
>   File "/opt/rh/rh-python36/root/lib64/python3.6/multiprocessing/pool.py", line 644, in get
>     raise self._value
> cx_Oracle.DatabaseError: ORA-12592: TNS:bad packet
> ```
it seems  every subprocess has one pool ,  they are independent, not the same one

**Comment by bestathena** [comment]
> . You can't create a session pool in one process and then acquire a connection from that pool in a worker process.

thank you for your comment, but if I can't create a session pool in one process and then acquire a connection from that pool in a worker process,  what is the purpose of cx_oracle sessionpool ?   cx_oracle  object can't be pickled,  and I don't want to create a 
 new connection for every time I call a worker method

**Comment by cjbj** [comment]
Sessions pools are very, very common for multi-threaded apps.  Open a new issue and we can discuss your use case, your expected connection load, the DB config etc and advise you.

**Comment by bestathena** [comment]
> Sessions pools are very, very common for multi-threaded apps. Open a new issue and we can discuss your use case, your expected connection load, the DB config etc and advise you.

ok ，I open a new one    https://github.com/oracle/python-cx_Oracle/issues/541
