### ISSUE TITLE
Connection to an Oracle DB (or Oracle Cloud SQL) using Kerberos authentication

### ISSUE THREAD

**Issue by luigisaetta** [oracle/python-cx_Oracle#471]
some stack mandatory puts kerberos on top of oracle connectivity. It is, imho, not clear how make in this case a connection using cx_oracle (that is used, for example, in every Machine Learning Notebook if we want to pull data to train a model). 
I have seen that in the past an issue was opened... but the answer imho was not clear and didn't provide a solution, At least cx_oracle docs should provide a clear way for the configuration-

**Comment by cjbj** [comment]
I appreciate the desire for info.  Kerberos configuration just isn't in our area - it's several layers lower than cx_Oracle and is a speciality topic.  The info I have is captured in the other issue you mention, #61.

**Comment by cjbj** [comment]
How did you go with this?  Does any of the info in https://github.com/oracle/node-oracledb/issues/1296 help?  The cx_Oracle and node-oracledb drivers have commonality in use.
