### ISSUE TITLE
Is it possible to reinitialize the client?

### ISSUE THREAD

**Issue by dabrowne** [oracle/python-cx_Oracle#473]
1. What versions are you using?

```
platform.platform: Linux-5.4.0-42-generic-x86_64-with-debian-10.4
sys.maxsize > 2**32: True
platform.python_version: 3.6.11

cx_Oracle.version: 8.0.0
cx_Oracle.clientversion: (18, 5, 0, 0, 0)
```

2. Describe the problem

I'm writing an application that allows the user to connect to one of many Oracle databases (configured by the user). Some of these databases require an encrypted connection, so the user may also upload an Oracle wallet per connection.

When the user makes a request that requires a connection to one of these databases, prior to initiating the connection we set the `TNS_ADMIN` environment variable to point to a `sqlnet.ora` file which contains the location of the appropriate wallet for this connection. It is my understanding that this could also be replaced by `cx_Oracle.init_oracle_client(config_dir=path_to_tns_admin)`. So far so good.

My challenge is that the application server uses a process pool to handle requests, and `cx_Oracle` will only initialize the client library **once** per process. This means that for the first request, the `TNS_ADMIN` variable gets set, the client reads this variable, and is initialized correctly - the connection succeeds. However for subsequent requests that are delegated to that same worker process, the oracle client will not be reinitialized, so it fails to pickup the updated `TNS_ADMIN` path.

Is there some mechanism that would allow me to 'teardown' or 'dispose' of the oracle client once I am done with the connection? Allowing me to reinitialize multiple times with different `TNS_ADMIN` or by calling `cx_Oracle.init_oracle_client`?

**Comment by cjbj** [comment]
Have you seen https://github.com/oracle/python-cx_Oracle/issues/389#issuecomment-631769320 ?

**Comment by dabrowne** [comment]
No I hadn't, thank you. Just to clarify, the only workaround is to use the EZ Connect Plus feature, requiring version 20C?

**Comment by anthony-tuininga** [comment]
The script provided in that comment works with 19c client as well -- at least it did when I just tried it right now! I was able to connect to two distinct cloud databases in the same process using different wallets.

**Comment by dabrowne** [comment]
Ok, thanks for the info. We're currently on the 18.5 driver but I'll do some digging and check if we're clear to upgrade.
