### ISSUE TITLE
AttributeError: module 'cx_Oracle' has no attribute 'init_oracle_client'

### ISSUE THREAD

**Issue by sdelabra** [oracle/python-cx_Oracle#474]
AttributeError: module 'cx_Oracle' has no attribute 'init_oracle_client'

`import sys
import cx_Oracle

cx_Oracle.init_oracle_client(lib_dir = r"C:\oracle\instantclient_19_6")
sys.path.insert(0, 'C:/Users/***************/api')

from api import app as application
`

**Comment by cjbj** [comment]
At a guess you don't have cx_Oracle 8.

If you answer the template questions https://raw.githubusercontent.com/oracle/python-cx_Oracle/master/.github/ISSUE_TEMPLATE/general-questions-and-runtime-problems.md we can narrow down what you are doing.
