### ISSUE TITLE
Problem running SQL query having regexp using python

### ISSUE THREAD

**Issue by Shailesh-Pradhan** [oracle/python-cx_Oracle#476]
Hello 
Firstly i'm an entry level coder in python.
So basically i'm trying to query the oracle sql developer via python. I'm able to set up connections successfully with database.
Normal SQL query works totally fine. For e.g : select * from table_name
However, i have an SQL query that contains some special characters. Below is the code  

```
NAM_100 = """SELECT DISTINCT 'NAM100: Text Field Basename should only have legal characters' val_desc, pa.ISO_COUNTRY_CODE,
p.poi_id, p.cat_id, trim(n.name) poi_basename, n.name_id, 'Basename' attr_name, n.name attr, n.language_code, pl.link_id
FROM poi p
JOIN poi_names pn ON p.poi_id = pn.poi_id
JOIN poi_name n ON n.name_id = pn.name_id
JOIN poi_address pa ON pa.poi_id = p.poi_id
JOIN poi_location pl ON pl.location_id = pa.location_id
WHERE REGEXP_LIKE (n.name,'[°´–ªº¿•³Ÿ;®·¶«»^?]') ORDER BY 2,1 """

print("Running Query")                   
nam100 = NAM_100.encode('utf-8')
df = pd.read_sql(nam100,con=conn)
df.to_csv('nam_100.csv',index=False)
```

When i tried running it, the output results very less counts as compared to the counts that i get when i run the query directly over the oracle sql developer.  It looks like some characters are ignored.
For e.g 
O/p running sql via python : 50 rows
O/p running sql over oracle sql developer: 500 rows

Can someone help me this ?

**Comment by cjbj** [comment]
When you open an issue, use the green 'new issue' button https://github.com/oracle/python-cx_Oracle/issues/new/choose which will ask you to share useful information such as your cx_Oracle version.  E.g. https://raw.githubusercontent.com/oracle/python-cx_Oracle/master/.github/ISSUE_TEMPLATE/general-questions-and-runtime-problems.md

What cx_Oracle version do you have?  What character set are you using, see https://cx-oracle.readthedocs.io/en/latest/user_guide/globalization.html ?  Give us a runnable Python script that also creates the table and inserts data.
