### ISSUE TITLE
Error reflecting Oracle table but not database

### ISSUE THREAD

**Issue by charlesNumerator** [oracle/python-cx_Oracle#478]
```
platform.platform: Linux-4.19.76-linuxkit-x86_64-with-debian-9.13
sys.maxsize > 2**32: True
platform.python_version: 3.7.8
```
```
cx_Oracle.version: 8.0.0
cx_Oracle.clientversion: (19, 8, 0, 0, 0)
```

2. Is it an error or a hang or a crash?

> Error might be a hang or a crash, not sure.

3. What error(s) or behavior you are seeing?

https://gist.github.com/charlesNumerator/aa6a1cc88503789572aab1c4b2ae386a

4. Include a runnable Python script that shows the problem.

https://gist.github.com/charlesNumerator/f7219ab754ca1c6983fdff47e530ee61

5. sql for the table in question

[table_ddl.txt](https://github.com/oracle/python-cx_Oracle/files/5271802/table_ddl.txt)

**Comment by anthony-tuininga** [comment]
The error suggests that it is a crash and, more importantly, that the Oracle Client library crashed for some reason. You'll need to contact Oracle Support for this one, I thinkj! @cjbj may have other suggestions.

**Comment by charlesNumerator** [comment]
thanks @anthony-tuininga

**Comment by cjbj** [comment]
Check for Oracle client logs.  If you're using Instant Client, I often run something like `rm -rf $HOME/instantclient/log/diag/clients && mkdir -p $HOME/instantclient/log/diag/clients`

**Comment by charlesNumerator** [comment]
@cjbj it's kind of a partner's database and it's difficult for us to get them to get in there but i'm going to try.  any idea why it would be this one table on its own its crashing when reflecting but we have no problem reflecting the entire database and pulling the metadata we need that way?

**Comment by cjbj** [comment]
@charlesNumerator how did you go with this?

**Comment by charlesNumerator** [comment]
@cjbj thanks for following up.  unfortunately i wasn't able to get in there and see the logs.  we are reflecting the entire db for the one or two tables that are giving us issues.

**Comment by cjbj** [comment]
@charlesNumerator an annoying but practical workaround.  I will close this issue since it's been open for a while.  Ping us as needed.

**Comment by charlesNumerator** [comment]
ok thanks for the help
