### ISSUE TITLE
Get ORA-24399 when pool parameters max and min are equal

### ISSUE THREAD

**Issue by Kaveshnikov** [oracle/python-cx_Oracle#479]
Hi!
1. What versions are you using?
I use Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production Version 19.8.0.0.0
platform.platform: Linux-4.15.0-20-generic-x86_64-with-glibc2.27
sys.maxsize > 2**32: True
platform.python_version: 3.8.5
cx_Oracle.version: 8.0.0
cx_Oracle.clientversion: (12, 1, 0, 2, 0)

2. Is it an error or a hang or a crash?
It is an error.

3. What error(s) or behavior you are seeing?
`cx_Oracle.DatabaseError: ORA-24399: invalid number of connections specified`

4. Include a runnable Python script that shows the problem.
```python
import cx_Oracle
import threading

TNS = (
    '(DESCRIPTION = '
        '(ADDRESS = (PROTOCOL = TCP)(HOST = {HOST})(PORT = 1521))'
        '(CONNECT_DATA = '
        ' (SERVER = DEDICATED)'
        ' (SERVICE_NAME = MYSERVICE)'
        ')'
    ')'
)

pool = cx_Oracle.SessionPool(
    user={USER},
    password={PASSWORD},
    dsn=TNS,
    min=2,
    max=2,
    increment=0,
    threaded=True,
    encoding='UTF-8',
    nencoding='UTF-8',
    getmode=cx_Oracle.SPOOL_ATTRVAL_WAIT,
)

def worker():
    with pool.acquire() as conn:
        cursor = conn.cursor()
        cursor.execute('select 1 from dual')
        print('Executed', flush=True)

threads = (
    threading.Thread(target=worker),
    threading.Thread(target=worker),
    threading.Thread(target=worker),
    threading.Thread(target=worker),
)

for thread in threads:
    thread.start()

for thread in threads:
    thread.join()

```

If change "min" and "increment" to 1 everything works fine. Also if change "increment" to -1 it works and that's weird.

**Comment by cjbj** [comment]
It reproduces with 12.2 but is fine with a later client version:

```
cjones@localhost:~/j$ python v.py 
- platform.platform:       Linux-4.14.35-2025.400.9.el7uek.x86_64-x86_64-with-glibc2.17
- sys.maxsize > 2**32:     True
- platform.python_version: 3.8.5
- cx_Oracle.version:       8.0.1
- cx_Oracle.clientversion: (19, 8, 0, 0, 0)
- encoding:                UTF-8
- nenecoding:              UTF-8

cjones@localhost:~/j$ python issue479.py 
Executed
Executed
Executed
Executed
cjones@localhost:~/j$ 
```

We did get the session pool team to make their checks a little more 'do what I mean' at some stage, either in 18 or 19.

**Comment by Kaveshnikov** [comment]
Unfortunately we have Alpine environment in our production, so it is tricky to use the instant client higher than 12.*. We will better switch to non-static pools. Any way, I believe the mentioned behavior should be backported to the instant client 12.2.

**Comment by cjbj** [comment]
The pool change was an enhancement, so is not a candidate for a backport.

I cannot ever recommend using Alpine with Oracle Client libraries because Alpine / glibc is way too unstable.

**Comment by Kaveshnikov** [comment]
> The pool change was an enhancement, so is not a candidate for a backport

I disagree. 12.2 instant client users will not be able to use static pools, which is a feature of the client and static pools are recommended by [The Oracle Real-World Performance group](https://docs.oracle.com/en/database/oracle/oracle-database/19/adfns/connection_strategies.html#GUID-7DFBA826-7CC0-4D16-B19C-31D168069B54). So as instant client 12.2 is still supported the mentioned behavior should be backported.

**Comment by cjbj** [comment]
This works fine in 12.2 so static pools are defintely possible.

```
    min=4,
    max=4,
    increment=0,
```
It seems smaller values have an issue.

Backporting to 12.2 is out of my hands.  You can certainly contact Oracle Support and see what they can offer you, but we don't put out new Instant Client 12.2 (or 18) releases on OTN.

**Comment by Kaveshnikov** [comment]
You increased number of connections in pool but did't increase the number of simultaneous threads. The behavior occurs only when one ore more threads are waiting for the connection from the pool.

**Comment by cjbj** [comment]
Interesting. And excuse my distraction and for not getting back sooner. The OCI team say this was indeed fixed in the Oracle client libraries with the enhancement 26568177 in 18c.  You can check with Support.  To be clear: this isn't in the cx_Oracle code base.

**Comment by foogaz** [comment]
Hi!
Any updates?
Encountered the same problem.
Nevertheless, Oracle recommends using the same values for the min/max — [Connection Pool Sizing](https://cx-oracle.readthedocs.io/en/latest/user_guide/connection_handling.html#connection-pool-sizing)

**Comment by cjbj** [comment]
@foogaz Update in what direction?  You can follow up with Oracle Support on the bug if you need a backport of something.  Otherwise try a recent client version?

**Comment by foogaz** [comment]
@cjbj Thanks for quick response. Actually when i upgraded client version from 11r2 to 19c it had worked!

@Kaveshnikov Why issue still opened?

**Comment by Kaveshnikov** [comment]
I thought maintainers could close this issue themselves if they were not going to change the mentioned behavior. I don't know the workflow for this repository so excuse me if I should have closed it myself.

**Comment by cjbj** [comment]
The issue was still open mostly because I was waiting on an update from @foogaz.  Plus we often now let issues get autoclosed when they are inactive.

I think everyone knows the solution now :)
