### ISSUE TITLE
Cx_Oracle 8.0.1 -  `DPI-1057: buffer size too large` inserting into a CLOB

### ISSUE THREAD

**Issue by Fxztam** [oracle/python-cx_Oracle#480]
Hello,

I am trying to load GeoJSON data with Python37 & cx_Oracle 8.0.1 into my ALways Free 19c OracleATP (Frankfurt)
with module: **_load.load2table.py_**  from my `Ring of Oracle GeoJSON` : [https://github.com/Fxztam/roogeos](https://github.com/Fxztam/roogeos) and
get:

 `_$$$ Error load.load2table(insert into ldgeojson) : DPI-1057: buffer size of 1964808393 is too large (max 1073741822)
Traceback (most recent call last):
  File "..\orageojson\load\load2table.py", line 23, in load2table  values ( :clobdata )''', clobdata=geojson)
cx_Oracle.DatabaseError: DPI-1057: buffer size of 1964808393 is too large (max 1073741822)_ `

Is there a way or good tip to solve it?

Thanks and regards,
Friedhold

**Comment by cjbj** [comment]
Can you help us by giving more context - and a runnable example (with less data!)? Where/what is load2table? https://github.com/Fxztam/roogeos/search?q=load2table.py doesn't help, and neither does a google search.

**Comment by Fxztam** [comment]
Sorry for the delay: 

The GeoJSON file length is _**1,964,808,393**_ bytes (and I cannot cut it) and it means the:  

> cx_Oracle.DatabaseError: DPI-1057: buffer size of **_1,964,808,393_** is too large (max 1,073,741,822) 

The code source is from here: [https://github.com/Fxztam/roogeos/blob/master/RingOfOraGeo/orageojson/load/load2table.py ](URL) 

>         p_cursor.execute('''insert into ld_geojson (ldjson)  values ( :clobdata )''', clobdata=geojson)

so I cannot load this large GeoJSON Feature Collection into OracleATP CLOB with Cx_Oracle .. ?  

Thanks and regards,
Friedhold

**Comment by cjbj** [comment]
To insert (or read) data over a gig with LOB columns, you need to stream the data in chunks, see [Streaming LOBs (Write)](https://cx-oracle.readthedocs.io/en/latest/user_guide/lob_data.html#streaming-lobs-write).

**Comment by Fxztam** [comment]
Thanks, I will try it.

**Comment by avmcohen** [comment]
Seem that problem solved in 2.5.1 oracledb, and got back in oracledb 3.2.0:

oracledb.exceptions.DatabaseError: DPI-1057: buffer size of 1513242692 is too large (max 1073741822)

**Comment by cjbj** [comment]
For the record, data > 1 GB needs to be inserted via a lob locator as documented. https://python-oracledb.readthedocs.io/en/latest/user_guide/lob_data.html#simple-insertion-of-lobs
