### ISSUE TITLE
'windows.h': No such file or directory when installing cx_Oracle

### ISSUE THREAD

**Issue by githubaja** [oracle/python-cx_Oracle#481]
I have a clean Windows 10 Pro installed, with Python 3.9 x64, and the lates Visual Studio Code

platform.platform: Windows-10-10.0.18362-SP0
sys.maxsize > 2**32: True
platform.python_version: 3.9.0

I had cx_Oracle installed and running for a long time but after the C drive format I need to get things set up again. I'm having problems installing cx_Oracle using pip install.

Initially I tried to install cx_Oracle but got an error stating that I need Microsoft Visual C++ 14. I downloaded Visual Studio 2019 build tools and installed these features:
![image](https://user-images.githubusercontent.com/55830353/95183315-1a3c2380-07c6-11eb-835c-7b93313badc5.png)
After the reboot I tried to install cx_Oracle and I get the following error:
`Collecting cx_Oracle
  Using cached cx_Oracle-8.0.1.tar.gz (325 kB)
Using legacy 'setup.py install' for cx-Oracle, since package 'wheel' is not installed.
Installing collected packages: cx-Oracle
    Running setup.py install for cx-Oracle ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\nikola.pepic\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\nikola.pepic\\AppData\\Local\\Temp\\pip-install-z04rlvr9\\cx-oracle\\setup.py'"'"'; __file__='"'"'C:\\Users\\nikola.pepic\\AppData\\Local\\Temp\\pip-install-z04rlvr9\\cx-oracle\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\nikola.pepic\AppData\Local\Temp\pip-record-faz075zz\install-record.txt' --single-version-externally-managed --compile --install-headers 
'c:\users\nikola.pepic\appdata\local\programs\python\python39\Include\cx-Oracle'
         cwd: C:\Users\nikola.pepic\AppData\Local\Temp\pip-install-z04rlvr9\cx-oracle\
    Complete output (14 lines):
    running install
    running build
    running build_ext
    building 'cx_Oracle' extension
    creating build
    creating build\temp.win-amd64-3.9
    creating build\temp.win-amd64-3.9\Release
    creating build\temp.win-amd64-3.9\Release\odpi
    creating build\temp.win-amd64-3.9\Release\odpi\src
    creating build\temp.win-amd64-3.9\Release\src
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.27.29110\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DCXO_BUILD_VERSION=8.0.1 -Iodpi/include -Iodpi/src -Ic:\users\nikola.pepic\appdata\local\programs\python\python39\include -Ic:\users\nikola.pepic\appdata\local\programs\python\python39\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.27.29110\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt /Tcodpi\src\dpiConn.c /Fobuild\temp.win-amd64-3.9\Release\odpi\src\dpiConn.obj
    dpiConn.c
    C:\Users\nikola.pepic\AppData\Local\Temp\pip-install-z04rlvr9\cx-oracle\odpi\src\dpiImpl.h(45): fatal error C1083: Cannot open include file: 'windows.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\nikola.pepic\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\nikola.pepic\\AppData\\Local\\Temp\\pip-install-z04rlvr9\\cx-oracle\\setup.py'"'"'; __file__='"'"'C:\\Users\\nikola.pepic\\AppData\\Local\\Temp\\pip-install-z04rlvr9\\cx-oracle\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\nikola.pepic\AppData\Local\Temp\pip-record-faz075zz\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\nikola.pepic\appdata\local\programs\python\python39\Include\cx-Oracle' Check the logs for full command output.`

My prime suspect is this 'Cannot open include file: 'windows.h': No such file or directory error' but I could be on the wrong track.
Any advice on what should I do?

**Comment by githubaja** [comment]
Apparently, those features are not enough.
I've added Win 10 SDK, C++ Cmake, testing tools and C++ MFC. Probably an overkill but I got cx_Oracle running.

**Comment by cjbj** [comment]
The next cx_Oracle release should come with pre-built binaries for 3.9.
