### ISSUE TITLE
Python Cx_Oracle - Oracle DBCS Connection using Jump Host Sever

### ISSUE THREAD

**Issue by amittyagi27** [oracle/python-cx_Oracle#484]
Dear Experts

I need to access Oracle Database from my machine via Jump Host Server and do some DML operations.
Local Machine ---> Linux Jump Host Server ---> Oracle Database

I have tried so many codes using "sshtunnel.SSHTunnelForwarder" but nothing is working, everytime when I run the python code, it just Hangs.I will be really thanksful if you please provide suitable Python script for this scenario.

(I start with a code initially but now did so many changes to not in position to share)
Thanks
Amit

**Comment by amittyagi27** [comment]
Dear Experts

I will really appreciate if you please help on priority.

Thanks
Amit

**Comment by cjbj** [comment]
Can you give more detail?  What exactly have you tried? What have you got installed? What can your jump server proxy?

Have you seen https://github.com/oracle/python-cx_Oracle/issues/158?

By DBCS I presume you mean an Oracle Cloud DB.  Which kind?  If it's ADW or ATP have you looked at the doc about proxies?  See https://blogs.oracle.com/opal/how-connect-to-oracle-autonomous-cloud-databases

**Comment by amittyagi27** [comment]
Thanks a lot Chris for reply, I am trying to connect VM DBCS only.
I have seen #158 and tried this same code, but python scripts hangs every time.
Here I have one doubt, in remote_bind_address it is just giving DB IP address not passing User name and SSH Key of DB virtual box, so how it will work.

import os
os.chdir("C:\\Oracle\\instantclient_12_2")
import cx_Oracle
import sshtunnel

HOST = "10.12.123.123" #IP of jumping server
REMOTE_PORT = 1521
LOCAL_PORT = 1521
USER_NAME = "user" #User from jumping server
#The IP here is the IP of DB server
DSN = "sa/sa@(DESCRIPTION=(SOURCE_ROUTE=OFF)(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=10.222.33.44)(PORT=1521)))(CONNECT_DATA=(SID=DBNAME)(SRVR=DEDICATED)))"

#Here in remote_bind_address I am using again the DB IP address
with sshtunnel.SSHTunnelForwarder(HOST, ssh_username = USER_NAME,
        ssh_password="pass",
        remote_bind_address = ("10.222.33.44", REMOTE_PORT)) as server:

    conn = cx_Oracle.connect(DSN)

    cursor = conn.cursor()
    cursor.execute("select * from TestStrings")
    for row in cursor:
        print(row)

    print("Inserting into TestTempTable")
    cursor.execute("truncate table TestTempTable")
    data = [(i + 1, "Test String %d" % (i + 1)) for i in range(1000)]
    cursor.executemany("insert into TestTempTable values (:1, :2)", data)
    conn.commit()

    print("Checking connection version")
    print(conn.version)

print("Done!")

**Comment by cjbj** [comment]
Where does it hang?  

PS Instead of the chdir, in cx_Oracle 8 just use https://cx-oracle.readthedocs.io/en/latest/user_guide/initialization.html#using-cx-oracle-init-oracle-client-to-set-the-oracle-client-directory

**Comment by cjbj** [comment]
More importantly, can you connect with SQL*Plus?
