### ISSUE TITLE
Error when inserting data into VARCHAR2 and CHAR columns

### ISSUE THREAD

**Issue by thiagodma** [oracle/python-cx_Oracle#486]
1. System
**Database version: 12c
platform.platform: Linux-3.10.0-957.5.1.e17.x86_64-with-centos-7.6.1810-Core
sys.maxsize > 2^32: True
platform.python_version: 3.6.8
cx_Oracle.version: 8.0.1
cx_Oracle.clientversion: (19,8,0,0,0)**

2. Is it an error or a hang or a crash?
**Error**

3. What error(s) or behavior you are seeing?
**ORA-12899: value too large for column "COLUMN" (actual: 5, maximum: 4)**

Actually I already know what is the problem that is happening. I'm trying to insert a python string such as "área" into a column which is of type CHAR(4 byte). The string has 4 characters but 5 bytes (because the character 'á' needs two bytes in utf-8) and that is why I get the ORA-12899. I'd like to know if there's a way to solve this issue without having to redefine the columns to the type CHAR(4 char) (I also know that redefining the column types fixes the problem).

**Comment by thiagodma** [comment]
I forgot to mention that the value "área" already exists in the table. But when I try to insert it with cx_Oracle I get the ORA-12899

**Comment by thiagodma** [comment]
Someone? @anthony-tuininga @cjbj

**Comment by anthony-tuininga** [comment]
What is the database character set? This [documentation](https://cx-oracle.readthedocs.io/en/latest/user_guide/globalization.html#finding-the-database-and-client-character-set) should help you figure that out. If the database character set is one that only requires 4 bytes to store the string that might explain the situation. The database should really be smart enough to figure that out if that's the case -- but that's a different story!

**Comment by thiagodma** [comment]
I've checked the documentation, executed the queries and got these results:

1. Database character set: AL32UTF8
2. Database national character set: AL16UTF16
3. Current client character set used by cx_Oracle: AL32UTF8

Any suggestions? Thank you.

**Comment by anthony-tuininga** [comment]
If the database character set is AL32UTF8 then I don't know there's any way around the situation. You can use this to see the actual value stored in the database:

```
select dump(column) from thetable;
```

If you see there are actually 5 bytes stored and the column constraint is for 4 bytes then you managed to find a way to defeat the constraint! I don't know how that was accomplished -- but I wouldn't be trying to replicate it. :-) I'd just correct the constraint to 4 char and continue on. Why do you not want to do that?

**Comment by thiagodma** [comment]
I checked the actual value stored in the database and the number of bytes there is 4. Oracle is, somehow, storing the correct string but with less bytes... I understand that Python's UTF-8 is different to Oracle's AL32UTF8, but it shouldn't be, right? Is that a bug on cx_Oracle or on the Oracle database? 

I don't want to adjust the constraint to 4 char because I'm extracting data from a IBM database and inserting it on a Oracle database. Ideally, the columns metadata should be the same.

**Comment by thiagodma** [comment]
I found what was the problem. Actually it is related to trailing spaces in strings coming from the IBM database. It is not a problem with cx_Oracle. I'm closing the issue. Thank you!
