### ISSUE TITLE
ORA-00600: internal error code, arguments: [ktcsnp2kenv_inval_snapshot], [], [], [], [], [], [], [], [], [], [], []

### ISSUE THREAD

**Issue by RMeg1** [oracle/python-cx_Oracle#487]
After we adjusted max_string_size from STANDARD to EXTENDED in 12.2.0.1 Oracle Database we get ora00600 error: ORA-00600: internal error code, arguments: [ktcsnp2kenv_inval_snapshot], [], [], [], [], [], [], [], [], [], [], [].
We only get this error when we execute a SQL select query via the Python driver. When we execute it via eg. SQL Developer, we don't have this issue.
Is there someone who knows a solution?
Thanks,
Rob

**Comment by cjbj** [comment]
Do you have a runnable code sample that creates a table, inserts data, and then tries to query it back?

Can you fill in the issue template questions about versions of cx_Oracle, the Oracle client etc?

**Comment by RMeg1** [comment]
Hi, this is the query:
SELECT id, identifier, business_unit, status, event_name, event_description, nfr_id, nfr_category, creation_date,
close_date, root_event, root_cause_description, event_start_date, location, global_date_protection_event,
detailed_mitigation_actions, insurable_risk, assigned_to, legal_claim, immediate_event_procedure_followed, tokenized_simple,
tokenized, language, link_to_irisk, match_event10081203
FROM (SELECT events.id AS id, events.identifier AS identifier, events.business_unit AS business_unit, events.status AS
status, events.event_name AS event_name, events.event_description AS event_description, events.nfr_id AS nfr_id,
events.nfr_category AS nfr_category, events.creation_date AS creation_date,
events.close_date AS close_date, events.root_event AS root_event, events.root_cause_description AS
root_cause_description, events.event_start_date AS event_start_date, events.location AS location,
events.global_date_protection_event AS global_date_protection_event, events.detailed_mitigation_actions AS
detailed_mitigation_actions, events.insurable_risk AS insurable_risk, events.assigned_to AS assigned_to, events.legal_claim
AS legal_claim, events.immediate_event_procedure_followed AS immediate_event_procedure_followed,
events.tokenized_simple AS tokenized_simple, events.tokenized AS tokenized, events.language AS language,
events.link_to_irisk AS link_to_irisk, CASE WHEN (lower(:param_1 || events.tokenized_simple || :param_2) LIKE
lower(:param_3)) THEN events.identifier END AS match_event10081203
FROM events
WHERE events.business_unit IN (:business_unit_1, :business_unit_2, :business_unit_3, :business_unit_4, :business_unit_5,
:business_unit_6, :business_unit_7, :business_unit_8, :business_unit_9, :business_unit_10, :business_unit_11) AND
(lower(:param_1 || events.tokenized_simple || :param_2) LIKE lower(:param_4) OR lower(:param_5 || events.tokenized ||
:param_6) LIKE lower(:param_7)))
WHERE ROWNUM <= :param_8]

Be aware that reading and writing to Oracle does work. But it seems to fail with larger quantities of data. We’re using SQLAlchemy to connect to Oracle. This has a connection string like:

SQLALCHEMY_DATABASE_URI = "oracle+cx_oracle://system:oracle@localhost/xe"

From there, we simply query the tables. @Bhagwandin, R. (Rajen), don’t you have the exact SQL query on which it fails? As a start, we can just insert that into the following code snippet:

from sqlalchemy import create_engine

engine = create_engine('oracle+cx_oracle://system:oracle@localhost/xe"')

with engine.connect() as con:
    rs = con.execute('your query')

It’s most likely using cx_oracle 7.3.0 (technically, we’ve specified >=7.3, <8.0). To be sure, you’d have to check the server to which it is deployed.

**Comment by cjbj** [comment]
- What is your Oracle Client version? Try using Oracle Client 19c.  

- Reduce the SQL statement to the minimum, and share the SQL to create the tables, insert data, and a cx_Oracle  (not SQL Alchemy) script that shows the problem.

- Run the same query in SQL*Plus (Not SQL Developer)

- You mentioned 12.2 but your connection string is XE, which would be either 11.2 or 18.

**Comment by RMeg1** [comment]
Hi, when using sqlplus (oraclient 19c) we also get the error. As oraclient is supported, we've put this in the Service Request that we created for Oracle.
SQL*Plus: Release 19.0.0.0.0 - Production on Wed Nov 11 11:25:04 2020
Version 19.6.0.0.0

Copyright (c) 1982, 2019, Oracle.  All rights reserved.

Enter password:
Last Successful login time: Mon Oct 12 2020 13:45:42 +01:00

Connected to:
Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production

SQL>  SELECT id, identifier, business_unit, status, event_name, event_description, nfr_id, nfr_category, creation_date, close_date, root_event
, root_cause_description, event_start_date, location, global_date_protection_event, detailed_mitigation_actions, insurable_risk,
assigned_to, legal_claim, immediate_event_procedure_followed, tokenized_simple, tokenized, language, link_to_irisk, match_risk
FROM (SELECT events.id AS id, events.identifier AS identifier, events.business_unit AS business_unit, events.status AS status,
     events.event_name AS event_name, events.event_description AS event_description, events.nfr_id AS nfr_id, events.nfr_category AS nfr_category,
     events.creation_date AS creation_date, events.close_date AS close_date, events.root_event AS root_event, events.root_cause_description AS root_cause_description,
     events.event_start_date AS event_start_date, events.location AS location, events.global_date_protection_event AS global_date_protection_event,
     events.detailed_mitigation_actions AS detailed_mitigation_actions, events.insurable_risk AS insurable_risk, events.assigned_to AS
assigned_to,
     events.legal_claim AS legal_claim, events.immediate_event_procedure_followed AS immediate_event_procedure_followed, events.tokenized_simple AS tokenized_simple,
     events.tokenized AS tokenized, events.language AS language,
     events.link_to_irisk AS link_to_irisk,
     CASE WHEN (lower(xxx) THEN events.identifier END AS match_risk
FROM events
WHERE events.business_unit IN (xxx)  AND xxx) LIKE lower(xxx) OR lower(xxx)
WHERE ROWNUM <= 1000  2    3    4    5    6    7    8    9   10   11   12   13   14   15   16   17  ;
assigned_to, legal_claim, immediate_event_procedure_followed, tokenized_simple, tokenized, language, link_to_irisk, match_risk
                                                                                                      *
ERROR at line 3:
ORA-00600: internal error code, arguments: [ktcsnp2kenv_inval_snapshot], [],
[], [], [], [], [], [], [], [], [], []

**Comment by cjbj** [comment]
Thanks for following up. Since this isn't cx_Oracle and you are working on it with Oracle Support, I'll close this out.
