### ISSUE TITLE
Create Stub File for Type Annotation

### ISSUE THREAD

**Issue by diegostammer** [oracle/python-cx_Oracle#488]
Using VSCode with pylance plugin in strict mode generate a lot of errors about missing type annotation.
The request is to create a stub file (*.pyi) to document every type of contants, methods, functions, etc.

https://www.python.org/dev/peps/pep-0484/
https://www.python.org/dev/peps/pep-0561/

**Comment by anthony-tuininga** [comment]
Thanks for the suggestion. I don't know when it will get done but it seems like a reasonable request to me!

**Comment by cjbj** [comment]
Maybe there's some synergy with https://www.oracle.com/database/technologies/appdev/dotnet/odtvscodequickstart.html that we can make use of?

**Comment by vptimmy** [comment]
Any update on this?  Would be a great feature to add!

**Comment by anthony-tuininga** [comment]
The main update is the release of [python-oracledb](https://github.com/oracle/python-oracledb) which is the successor of cx_Oracle and has type annotations already included! See the [section](https://python-oracledb.readthedocs.io/en/latest/user_guide/appendix_c.html#upgrading83) on upgrading from cx_Oracle for details.
