### ISSUE TITLE
ORA-01036: illegal variable name/number

### ISSUE THREAD

**Issue by craigthecraigster** [oracle/python-cx_Oracle#492]
1. What versions are you using?
Oracle Database 12c Enterprise Edition 	12.2.0.1.0	64bit Production

platform.platform: Windows-10-10.0.18362-SP0
sys.maxsize > 2**32: False
platform.python_version: 3.7.1

cx_Oracle.version: 7.3.0
cx_Oracle.clientversion: (11, 2, 0, 1, 0)

2. Is it an error or a hang or a crash?
Error

3. What error(s) or behavior you are seeing?

ORA-01036: illegal variable name/number is encountered when I use a database table with a single column. If I add a second column to the table, it works fine.

4. Include a runnable Python script that shows the problem.

```
sql = "insert into my_table (my_column) values (:1)"
my_row = ('some_string')
my_row _list = [my_row]
cur.executemany(sql, my_row_list)
```

**Comment by anthony-tuininga** [comment]
You've made one simple mistake:

``('some_string')`` is not the same as

``('some_string',)``

The first will return just a string. The second will return a tuple. You can try this directly in a Python interpreter!

**Comment by craigthecraigster** [comment]
Ah.  Thank you!  I spent forever on this and you solved it right away!
