### ISSUE TITLE
login failure when password contains a reserved character?

### ISSUE THREAD

**Issue by DeepGeek** [oracle/python-cx_Oracle#494]
Many passwords are auto-generated when an account is set up and are required to have a certain number of special characters.
In the case of the one I was most recently given, this prevented logging in via cx_oracle 7.2.3
The workaround is simply to change the password in the db to a simpler one without that combination of special characters, then connection is successful.

Connection string: r'oracle+cx_oracle://someuser::%24jE?hpJ@SOME_TNS'
The password randomly assigned was :%24jE?hpJ
Note the leading colon character ':' in the password.

That password leads to the error:
sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-01017: invalid username/password; logon denied
(Background on this error at: http://sqlalche.me/e/4xp6)

Now, this might be SQLAlchemy doing the wrong thing not cx_oracle, I'm not sure about the boundary.
But I hope this helps. Keep up the good work.

**Comment by anthony-tuininga** [comment]
Yes, this is an issue with SQLAlchemy and you'll need to report this error there. This code, for example, works just fine:

```
cx_Oracle.connect("someuser/:%24jE?hpJ@SOME_TNS")
```

The connect string you provided is specific to SQLAlchemy and you may need some escape characters to pass that password -- but I don't know for sure!

**Comment by DeepGeek** [comment]
Thanks so much for looking into this. I've raised it with SQLAlchemy.
Appreciate everything you guys do.
