### ISSUE TITLE
cx_Oracle for HP-UX

### ISSUE THREAD

**Issue by yaodeyi** [oracle/python-cx_Oracle#495]
1. Describe your new request in detail
We are using legacy system on HP-UX B.11.31 U ia64 and would use cx_Oracle with python 2.7.18 and Oracle DB 12
I can not find such existing binary of cx_Oracle.
I tried to build from source, but failed.
Can this request be supported?
Thanks.

2. Give supporting information about tools and operating systems.  Give relevant product version numbers

**Comment by cjbj** [comment]
cx_Oracle binaries for HP-UX are not on our roadmap.

We may be able to help you troubleshoot your build issue if you can share details.

**Comment by yaodeyi** [comment]
Thanks!

Here are my steps to build:

#:/home/deyiyao> uname -a
HP-UX cbinsp91 B.11.31 U ia64 3402672265 unlimited-user license

#:/home/deyiyao> which aCC
/opt/aCC/bin/aCC

#:/home/deyiyao> aCC -V
aCC: HP C/aC++ B3910B A.06.27 [May 22 2012]

#:/home/deyiyao> python
Python 2.7.3 (default, Jun 19 2012, 17:11:17)
[GCC 4.4.3] on hp-ux11
Type "help", "copyright", "credits" or "license" for more information.

>>> import sys
>>> sys.version
'2.7.3 (default, Jun 19 2012, 17:11:17) \n[GCC 4.4.3]'
>>> sys.platform
'hp-ux11'

#:/home/deyiyao/cx_oracle> l
total 1696
-rw-r--r--   1 deyiyao    insps       232941 Nov 21 03:44 python-cx_Oracle-5.x.zip

#:/home/deyiyao/cx_oracle> unzip python-cx_Oracle-5.x.zip

#:/home/deyiyao/cx_oracle/python-cx_Oracle-5.x> l
total 64
-rw-r--r--   1 deyiyao    insps         4542 Nov 15  2017 BUILD.txt
drwxr-xr-x   2 deyiyao    insps         1024 Nov 15  2017 src
-rw-r--r--   1 deyiyao    insps        14698 Nov 15  2017 setup.py
drwxr-xr-x   2 deyiyao    insps         1024 Nov 15  2017 samples
drwxr-xr-x   3 deyiyao    insps           96 Nov 15  2017 doc
-rw-r--r--   1 deyiyao    insps          163 Nov 15  2017 README.txt
-rw-r--r--   1 deyiyao    insps         3656 Nov 15  2017 README.md
-rw-r--r--   1 deyiyao    insps          125 Nov 15  2017 MANIFEST.in
-rw-r--r--   1 deyiyao    insps         1805 Nov 15  2017 LICENSE.txt
-rw-r--r--   1 deyiyao    insps          682 Nov 15  2017 CONTRIBUTING.md
drwxr-xr-x   2 deyiyao    insps         1024 Nov 15  2017 test

#:/home/deyiyao/cx_oracle> export ORACLE_HOME=/opt/oracle/product/11.2.0/

#:/home/deyiyao/cx_oracle/python-cx_Oracle-5.x> python setup.py  build
running build
running build_ext
building 'cx_Oracle' extension
creating build
creating build/temp.hp-ux-B.11.31-ia64-2.7-11g
creating build/temp.hp-ux-B.11.31-ia64-2.7-11g/src
/opt/aCC/bin/aCC +DD64 -fno-strict-aliasing -g -DNDEBUG -g -O1 -Wall -Wstrict-prototypes -fPIC -I/opt/oracle/product/11.2.0/rdbms/demo -I/opt/oracle/product/11.2.0/rdbms/public -I/opt/iexpress/python/include/python2.7 -c src/cx_Oracle.c -o build/temp.hp-ux-B.11.31-ia64-2.7-11g/src/cx_Oracle.o -DBUILD_VERSION=5.3
aCC: warning 901: unknown option: `-fno-strict-aliasing': use +help for online documentation.
aCC: error 1914: bad form for `-W' option
error: command '/opt/aCC/bin/aCC' failed with exit status 1

**Comment by yaodeyi** [comment]
cx_Oracle does not officially support HP-UX, I take a workaround measure to fix errors in build.

I'd share my procedures below.

1. Build Server Env:
 - HP-UX B.11.31 U ia64
 - HP-UX aCC compiler: HP C/aC++ B3910B A.06.27 [May 22 2012]
 - download below depot.gz from http://hpux.connect.org.uk
  - python-2.7.18 (python-2.7.18-ia64_64-11.31.depot.gz)
  - dependency of Python-2.7.18 (expat-2.2.3-ia64_64-11.31.depot.gz, gettext-0.21-ia64_64-11.31.depot.gz, libiconv-1.16-ia64_64-11.31.depot.gz)
 - download Oracle 12.1.0 for HP-UX from Oracle web site
 - download cx_Oracle-4.3.1.tar.gz source code

2. Restrictions
 - no python 3 support, as it is not ready yet so far at http://hpux.connect.org.uk
 - cx_Oracle-4.3.1 only, because cx_Oracle-5.x has more than 100 errors to
   fix, but cx_Oracle-4.x has < 10 errors to fix
 - I did not try cx_Oracle-6.x, 7.x, 8.x
 - steps here are only for Oracle 12 + cx_Oracle-4.3.1 + python 2.7.18, it is veirified in my lab

3. How to fix build issues
 - original setup.py will fail because HP-UX aCC compiler does not support the default options.
 - I skipped setup.py and directly built cx_Oracle.so with aCC
 - there are aCC compilation/linking errors in source files. I fixed 7 .c files.

deyiyao@cbinsp91:/home/usra/deyiyao/cx_oracle/cx_Oracle-4.3.1> diff $odir/Callback.c Callback.c
48c48
<     var->indicator = indicator;
---
>     var->indicator = (sb2 *)indicator;


deyiyao@cbinsp91:/home/usra/deyiyao/cx_oracle/cx_Oracle-4.3.1> diff $odir/Variable.c Variable.c
167c167
<     var->indicator = PyMem_Malloc(numElements * sizeof(sb2));
---
>     var->indicator = (sb2 *)PyMem_Malloc(numElements * sizeof(sb2));
181c181
<         var->returnCode = PyMem_Malloc(numElements * sizeof(ub2));
---
>         var->returnCode = (ub2 *)PyMem_Malloc(numElements * sizeof(ub2));


deyiyao@cbinsp91:/home/usra/deyiyao/cx_oracle/cx_Oracle-4.3.1> diff $odir/NumberVar.c NumberVar.c
9c9
< static const char gc_NumberFormat[63] =
---
> static const char gc_NumberFormat[64] =
321c321
<     *textValue = valuePtr = PyMem_Malloc(length);
---
>     *textValue = valuePtr = (char *)PyMem_Malloc(length);
326c326
<     *format = formatPtr = PyMem_Malloc(length);
---
>     *format = formatPtr = (char *)PyMem_Malloc(length);


deyiyao@cbinsp91:/home/usra/deyiyao/cx_oracle/cx_Oracle-4.3.1> diff $odir/ObjectVar.c ObjectVar.c
95c95
<     self->objectIndicator =
---
>     self->objectIndicator = (dvoid**)
216c216
<                 self->data[pos], (PyObject*) self, self->objectType);
---
>                 (OCIColl *)self->data[pos], (PyObject*) self, self->objectType);


deyiyao@cbinsp91:/home/usra/deyiyao/cx_oracle/cx_Oracle-4.3.1> diff $odir/Transforms.c Transforms.c
8c8
< static udt_VariableType vt_Date;
---
> extern udt_VariableType vt_Date;


deyiyao@cbinsp91:/home/usra/deyiyao/cx_oracle/cx_Oracle-4.3.1> diff $odir/cx_Oracle.c cx_Oracle.c
4a5
> extern "C" {
472a474
> }

deyiyao@cbinsp91:/home/usra/deyiyao/cx_oracle/cx_Oracle-4.3.1> diff $odir/Connection.c Connection.c
35c35
<
---
> extern char *strchr(const char *, int);
278c278
<             (dvoid*) &self->handle, OCI_HTYPE_SVCCTX, 0, 0);
---
>             (dvoid**) &self->handle, OCI_HTYPE_SVCCTX, 0, 0);


4. Steps to build
 - install all .depot.gz files under $HOME

cd $HOME
gunzip $HOME/python-2.7.18-ia64_64-11.31.depot.gz
tar xf python-2.7.18-ia64_64-11.31.depot

gunzip $HOME/gettext-0.21-ia64_64-11.31.depot.gz
tar xf gettext-0.21-ia64_64-11.31.depot

gunzip $HOME/expat-2.2.3-ia64_64-11.31.depot.gz
tar xf expat-2.2.3-ia64_64-11.31.depot

gunzip $HOME/libiconv-1.16-ia64_64-11.31.depot.gz
tar xf libiconv-1.16-ia64_64-11.31.depot

Install Oracle 12.1.0 under $ORACLE_HOME, the oci header files are under $ORACLE_HOME/rdbms/public

mkdir $HOME/cx_oracle
cd $HOME/cx_oracle
gunzip cx_Oracle-4.3.1.tar.gz
tar xf cx_Oracle-4.3.1.tar

cd $HOME/cx_oracle/cx_Oracle-4.3.1

vi build.sh, add below lines

/opt/aCC/bin/aCC +DD64 +z -b -g -DBUILD_VERSION=4.3.1 \
-I. \
-I/usr/include \
-I$HOME/python/python-INC/usr/local/include/python2.7 \
-I$ORACLE_HOME/rdbms/public \
-L/usr/lib/hpux64 \
-L$HOME/expat/expat-RUN/usr/local/lib/hpux64 \
-L$HOME/python/python-RUN/usr/local/lib/hpux64 \
-L$HOME/gettext/gettext-RUN/usr/local/lib/hpux64 \
-L$HOME/libiconv/libiconv-RUN/usr/local/lib/hpux64 \
-L$ORACLE_HOME/lib \
-o build/cx_Oracle.so cx_Oracle.c \
-lpython2.7 -lclntsh -lintl -liconv -lexpat -lunwind -lCsup

chmod +x build.sh
./build.sh
cx_Oracle.so is under $HOME/cx_oracle/cx_Oracle-4.3.1/build


5. Verify the module
cd $HOME/cx_oracle/cx_Oracle-4.3.1/build

LD_LIBRARY_PATH=$HOME/libiconv/libiconv-RUN/usr/local/lib/hpux64
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/gettext/gettext-RUN/usr/local/lib/hpux64
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/python/python-RUN/usr/local/lib/hpux64
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/expat/expat-RUN/usr/local/lib/hpux64
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ORACLE_HOME/lib
export LD_LIBRARY_PATH

$HOME/python/python-RUN/usr/local/bin/python2.7
Python 2.7.18 (default, Apr 24 2020, 09:22:49) [C] on hp-ux11
Type "help", "copyright", "credits" or "license" for more information.
>>> import cx_Oracle
>>> dir(cx_Oracle)
['BFILE', 'BINARY', 'BLOB', 'Binary', 'CLOB', 'CURSOR', 'Connection', 'Cursor', 'DATETIME', 'DataError', 'DatabaseError', 'Date', 'DateFromTicks', 'Error', 'FIXED_CHAR', 'FNCODE_BINDBYNAME', 'FNCODE_BINDBYPOS', 'FNCODE_DEFINEBYPOS', 'FNCODE_STMTEXECUTE', 'FNCODE_STMTFETCH', 'FNCODE_STMTPREPARE', 'IntegrityError', 'InterfaceError', 'InternalError', 'LOB', 'LONG_BINARY', 'LONG_STRING', 'NCLOB', 'NUMBER', 'NotSupportedError', 'OBJECT', 'OperationalError', 'ProgrammingError', 'ROWID', 'SPOOL_ATTRVAL_FORCEGET', 'SPOOL_ATTRVAL_NOWAIT', 'SPOOL_ATTRVAL_WAIT', 'STRING', 'SYSDBA', 'SYSOPER', 'SessionPool', 'TIMESTAMP', 'Time', 'TimeFromTicks', 'Timestamp', 'TimestampFromTicks', 'UCBTYPE_ENTRY', 'UCBTYPE_EXIT', 'UCBTYPE_REPLACE', 'Warning', '_Error', '__doc__', '__file__', '__name__', '__package__', 'apilevel', 'buildtime', 'connect', 'makedsn', 'paramstyle', 'threadsafety', 'version']
>>> cx_Oracle.version
'4.3.1'

**Comment by cjbj** [comment]
Thanks for sharing!
@anthony-tuininga is there anything you should merge back to master?

**Comment by anthony-tuininga** [comment]
Unfortunately, the code referenced here is too old to be of use in master -- so no, nothing to merge back to master. It is, however, useful for those in the same situation as the poster!
