### ISSUE TITLE
Consider code-signing Oracle Instant Client Binaries on macOS 10.15.x and up

### ISSUE THREAD

**Issue by Blitz2145** [oracle/python-cx_Oracle#496]
1. Describe your new request in detail

When using cx_Oracle v8, python 3.6.9 and macOS 10.15.7 or greater, the first time I run a query with this library, I get a security popup from MacOS, about the instant client dylib's being from an "unknown developer". This is because the free instant client libraries distributed on the oracle website aren't being code signed for macOS. I am still able to use this library, because I can allow it to run by going to the Security & Preferences screen and allowing it to load the needed libs anyways. You can read more in detail about the issue and solutions here:
[Code Signing on macOS](https://github.com/mitchellh/gon#gon---cli-and-go-library-for-macos-notarization)

The developer experience would be more seamless, if code-signed binaries were distributed instead, just a suggested enhancement.

2. Give supporting information about tools and operating systems.  Give relevant product version numbers
cx_Oracle v8, python 3.6.9 and macOS 10.15.7

**Comment by cjbj** [comment]
The 19.9 DMGs are signed.  What are you using?

**Comment by Blitz2145** [comment]
Okay, awesome! Yea, my DMGs I installed are way older than October released ones linked, that explains my issue. Thanks for the help, you can close.
