### ISSUE TITLE
Oracle Client library has already been initialized

### ISSUE THREAD

**Issue by OakLi** [oracle/python-cx_Oracle#497]
1. What versions are you using?

    cx_Oracle：8.0.1
    Python：3.7
2. Describe the problem
    After the connection is disconnected, initialize again to report an error `Oracle Client library has already been initialized`
    How can I initialize it again?

**Comment by cjbj** [comment]
I assume you are calling `init_oracle_client()` You can't reinitialize the loading of libraries and config files. The initialization should be once per process.  This is the same as if you had set the system library search path and TNS_ADMIN variable before you started Python.

**Comment by brccabral** [comment]
Is there a way to check if init_oracle_client() has been called without just putting a `try` block?

**Comment by anthony-tuininga** [comment]
Not currently. The intent is to call this one time on startup of your application and then never again.

**Comment by anthony-tuininga** [comment]
An update is coming that will allow you to make the same call twice without exception -- so long as the parameters are identical. Stay tuned!

**Comment by brccabral** [comment]
Is there an issue number so I can follow?

**Comment by anthony-tuininga** [comment]
It was an internal issue that @cjbj raised based on feedback from others -- he probably has a record and can update you further when he wakes up.

**Comment by cjbj** [comment]
There's no single issue that comes to mind - searching might show some.  We had a number of people tripping on the behavior so we improved it.  When the new cx_Oracle release comes out you'll get it! Follow my blog or twitter feed or this repo to be notified of when that release is available.

**Comment by cjbj** [comment]
> Is there a way to check if init_oracle_client() has been called without just putting a `try` block?

Set a flag when you first call `init_oracle_client()` and don't recall the function if the flag is true.

**Comment by brccabral** [comment]
> > Is there a way to check if init_oracle_client() has been called without just putting a `try` block?
> 
> Set a flag when you first call `init_oracle_client()` and don't recall the function if the flag is true.

Streamlit reloads the pagea and the flag restarts. I've just read about "session_state", I'll try it tomorrow

**Comment by cjbj** [comment]
Session state is related to connections, not to how the Python process dynamically loads the Oracle Client library.  Stick with the try block for the moment.

**Comment by likhithpindi1** [comment]
cx_Oracle.ProgrammingError: Oracle Client library has already been initialized

how to solve this

**Comment by anthony-tuininga** [comment]
Two choices currently:

- stop calling init_oracle_client() twice 
- upgrade to python-oracledb which is more forgiving and doesn't raise an exception if you call it twice with the same parameters

**Comment by kalyandevopsengineer** [comment]
I was able to resolve the problem by adding `cx_Oracle.init_oracle_client` function line in a separate python file. I did not import the file into oracle connection creation file. This way, the init function is called one time. In the connection creation file, we just need to make dsn/create connection/create cursor and call cursor execute.
