### ISSUE TITLE
CQN stopped receiving message when inserting more than 100 records

### ISSUE THREAD

**Issue by kzhangkzhang** [oracle/python-cx_Oracle#498]
## Section A: Environment & Version

Python version     : 3.8.6 on Windows server 2012
cx_Oracle version : 8.0.1
Remote Oracle DB: 11GR2 (11.2.0.4)
Oracle instant client: 19.8

>>> print("platform.platform:", platform.platform())
platform.platform: Windows-2012ServerR2-6.3.9600-SP0
>>> print("sys.maxsize > 2**32:", sys.maxsize > 2**32)
sys.maxsize > 2**32: True
>>> print("platform.python_version:", platform.python_version())
platform.python_version: 3.8.6

>>> print("cx_Oracle.version:", cx_Oracle.version)
cx_Oracle.version: 8.0.1

## Section B: Case Study

We are exploring Continuous Query Notification (CQN) and try to capture DML (Insert) 
on a remote testing table. We found a weird case related magic number "100":

- if we are doing a batch insertion of Less or Equal 100 rows (<= 100) for a test table, we will receive CQN on terminal
- if we are doing  a batch insertion of more than 100 rows (> 100) for a test table, CQN will not been received and we noticed table.rows in the message of callback function is = 0

## Section C: Source Code

import cx_Oracle
import os
import pandas as pd
import time

registered = True

lib_dir = r"D:\Software\Oracle\instantclient_19_8"
os.environ["PATH"] = lib_dir+";"+os.environ["PATH"]
dsn_tns = cx_Oracle.makedsn('yyy', '9001', service_name='zzz')

if os.path.exists("kevin_records.csv"):
  os.remove("kevin_records.csv")
else:
  print("The file does not exist")

def CQNCallback(message):
    print("\n\n\n++++++++++++++++++++++++++\nStarting call back handler ...")
    print("++ type for message: " + str(type(message)))
    print("++ type for message.queries: " + str(type(message.queries)) + ": length=" + str(len(message.queries)))
    print("++ type for query.tables: " + str(type(message.queries[0].tables)) + ": length=" + str(len(message.queries[0].tables)))
    print("++ type for tab.rows: " + str(type(message.queries[0].tables[0].rows)) + ": length=" + str(len(message.queries[0].tables[0].rows)))
		
conn = cx_Oracle.connect(
    user='xxx', password='xxx', dsn=dsn_tns, events=True)
subscr = conn.subscribe(
            namespace   = cx_Oracle.SUBSCR_NAMESPACE_DBCHANGE,
            callback    = CQNCallback,
            operations  = cx_Oracle.OPCODE_INSERT | 
                          cx_Oracle.OPCODE_DELETE | 
                          cx_Oracle.OPCODE_UPDATE,
            qos         = cx_Oracle.SUBSCR_QOS_BEST_EFFORT | 
                          cx_Oracle.SUBSCR_QOS_QUERY | 
                          cx_Oracle.SUBSCR_QOS_ROWIDS 
        )
print("^" * 60)
print("cx_Oracle version: ", cx_Oracle.version)
print("Remote DB version:", conn.version)
print("Client version:", cx_Oracle.clientversion())
print("^" * 60)

print("\nmSubscription:", subscr)
print("--> Connection:", subscr.connection)
print("--> Callback:", subscr.callback)
print("--> Namespace:", subscr.namespace)
print("--> Protocol:", subscr.protocol)
print("--> Timeout:", subscr.timeout)
print("--> Operations:", subscr.operations)
print("--> Rowids?:", bool(subscr.qos & cx_Oracle.SUBSCR_QOS_ROWIDS))

queryId = subscr.registerquery("select * from kevin_cqn_user")
print("Registered query: ", queryId)

while registered:
    print("Waiting for notifications. Hit Ctl + C stop CQN demo\n ...")
    time.sleep(20)    

### Case A: Insert 100 rows 

DECLARE

    l_max_id        number  := NULL;
    l_insert_no     number  := 100;

BEGIN

    SELECT NVL(MAX(user_id), 0) INTO l_max_id FROM kevin_cqn_user;
    
    FOR x IN l_max_id + 1 ..l_max_id + l_insert_no 
    LOOP
        INSERT INTO kevin_cqn_user(user_id, user_name) VALUES (x, 'User '||x);
    END LOOP;
    
    COMMIT;
END;
/

Starting call back handler ...
++ type for message: <class 'cx_Oracle.Message'>
++ type for message.queries: <class 'list'>: length=1
++ type for query.tables: <class 'list'>: length=1
++ type for tab.rows: <class 'list'>: length=**100**

### Case B: Insert 101 rows 

DECLARE

    l_max_id        number  := NULL;
    l_insert_no     number  := 100;

BEGIN

    SELECT NVL(MAX(user_id), 0) INTO l_max_id FROM kevin_cqn_user;
    
    FOR x IN l_max_id + 1 ..l_max_id + l_insert_no 
    LOOP
        INSERT INTO kevin_cqn_user(user_id, user_name) VALUES (x, 'User '||x);
    END LOOP;
    
    COMMIT;
END;
/

Starting call back handler ...
++ type for message: <class 'cx_Oracle.Message'>
++ type for message.queries: <class 'list'>: length=1
++ type for query.tables: <class 'list'>: length=1
++ type for tab.rows: <class 'list'>: length=**0**                         <=== this is the issue

## Section E: Question

Can you explain why we can't receive CQN for more than 100 insertion? 
Anything is wrong for me code?

Thank you!

Kevin

**Comment by cjbj** [comment]
If I recall correctly there is a threshold. A CQN expert would be able to comment more.  I see in the [CQN doc](https://docs.oracle.com/en/database/oracle/oracle-database/12.2/adfns/cqn.html#GUID-52166555-C4AB-46F0-ABB6-6AD64093E19F) 'Too many rows were changed in a single registered object within a transaction (the upper limit is approximately 80).'.  Check with Oracle Support.

**Comment by kzhangkzhang** [comment]
Hi Jones:

I tested this against 2 different 11GR2 databases and symptom is exactly same: as soon as we insert > 100 rows, we stopped receiving CQN. 

when I reading cx_Oracle [documentation](https://cx-oracle.readthedocs.io/en/latest/api_manual/cursor.html?highlight=100#Cursor.arraysize), I keep seeing "cursor arraysize 100". 

"Due to the performance benefits, the default Cursor.arraysize is **100** instead of the 1 that the DB API recommends. This value means that 100 rows are fetched by each internal call to the database."

because "100" in cx_Oracle, I am thinking the issue is in cx_Oracle, not remote Oracle database. What do you think? Any idea how to troubleshooting root cause of this issue?

I am bit surprised that nobody else has reported this issue?

Thanks!

Kevin

**Comment by cjbj** [comment]
`arraysize` is not related to CQN.  Arraysize is used for fetching data from SQL queries.  (I've made a note to improve the doc.)  

If you are able to receive CQN notifications in some cases but not others, then the issue is likely to be a CQN feature/limitation.  Try removing SUBSCR_QOS_ROWIDS or play with the options in other ways.

I seem to recall some option that could be set to change the limit, but can't find my notes.  You should ask on a DBA forum or Oracle Support.

**Comment by cjbj** [comment]
And here's my note: https://github.com/oracle/python-cx_Oracle/issues/326#issuecomment-509495262

**Comment by kzhangkzhang** [comment]
Hi Chris:

Thanks for the note. We will review.

Kevin
