### ISSUE TITLE
How do I call the Oracle local_transaction_id function with "TRUE" as an argument and also get the return value?

### ISSUE THREAD

**Issue by zzzeek** [oracle/python-cx_Oracle#501]
cx_Oracle 8.1.0, oracle 11 XE, Python 3.8.3 linux

```python
>>> import cx_Oracle
>>> print("cx_Oracle.version:", cx_Oracle.version)
cx_Oracle.version: 8.1.0
>>> print("cx_Oracle.clientversion:", cx_Oracle.clientversion())
cx_Oracle.clientversion: (19, 3, 0, 0, 0)

```

The ultimate goal is to get the current selected isolation level.   This can only be done if a transaction is started.  The only way to start a transaction in Oracle without actually emitting DML seems to be to use the local_transaction_id function, critically passing "TRUE" as the argument.   Source: https://stackoverflow.com/a/16811953 (this seems to hold up under experimentation as well).

I've figured out how to call this function but it is not possible per cx_Oracle's usual APIs to pass the boolean True value.   Documented methods of getting at the return value of the funciton are not successful.

I can of course do what they're doing in that stackoverflow answer and just run a separate query but it seems wrong that this simple function cannot be invoked with arguments /return value directly in cx_Oracle.

The script below illustrates.  if there is something I'm missing perhaps this could be added to the docs since I'm at a loss.

```python
import cx_Oracle


def attempt_one(conn):

    with conn.cursor() as cursor:
        retval = cursor.callfunc(
            "dbms_transaction.local_transaction_id", str, [True]
        )
        return retval


def attempt_two(conn):
   # EDITED, I got this one, never mind
    with conn.cursor() as cursor:
        outval = cursor.var(str)
        cursor.execute(
            """
            declare
                trans_id Varchar2(100);
            begin
               trans_id:= dbms_transaction.local_transaction_id( TRUE );
            end;

        """,
            [outval],
        )

        return outval.getvalue()


def attempt_three(conn):

    with conn.cursor() as cursor:
        cursor.execute(
            """
            declare
                trans_id Varchar2(100);
            begin
               trans_id:= dbms_transaction.local_transaction_id( TRUE );
            end;

        """
        )

        return "Query succeeds, but how do I get the return value?"


conn = cx_Oracle.connect(user="scott", password="tiger", dsn="oracle1120")

for attempt in (attempt_one, attempt_two, attempt_three):
    try:
        return_value = attempt(conn)
    except cx_Oracle.Error as err:
        print("Attempt %s got error: %s" % (attempt.__name__, err))
    else:
        print("Attempt %s return value: %s" % (attempt.__name__, return_value))

```

output:

```
Attempt attempt_one got error: ORA-03115: unsupported network datatype or representation
Attempt attempt_two got error: ORA-01036: illegal variable name/number
Attempt attempt_three return value: Query succeeds, but how do I get the return value?

```

**Comment by zzzeek** [comment]
OK I got it:

```
def attempt_two(conn):

    with conn.cursor() as cursor:
        outval = cursor.var(str)
        cursor.execute(
            """
            begin
               :trans_id := dbms_transaction.local_transaction_id( TRUE );
            end;
        """, {"trans_id": outval}
        )
        return outval.getvalue()


```

this is documented and I didn't read enough to get there.    Still would want to know why callfunc() can't be used but I will go with the above for now.

**Comment by cjbj** [comment]
With 19c client libs to 21c DB using cx_Oracle 8.1:
```
with connection.cursor() as cursor:
    retval = cursor.callfunc(
        "dbms_transaction.local_transaction_id", str, [False]
    )
    print( retval)

    retval = cursor.callfunc(
        "dbms_transaction.local_transaction_id", str, [True]
    )
    print( retval)
```
gives:
```
None
2.21.10838
```

There have been various Boolean bind changes noted in the releasenotes.  @anthony-tuininga will know the details.

**Comment by zzzeek** [comment]
OK, I have 19.3.0.0.0 , I'm not even sure how i got this.  ill poke at oracle downloads.

**Comment by anthony-tuininga** [comment]
Database 11.2 didn't support binding PL/SQL booleans (thus the error ORA-3115). So you need to use a database of 12.x or (preferably) higher. Or use the workaround you decided to go with. :-)

**Comment by cjbj** [comment]
That too :)

**Comment by cjbj** [comment]
@zzzeek is this for sqlalchemy?

**Comment by zzzeek** [comment]
yes!    I will leave it at the workaround becasue I have users that are going back as early as oracle 8 :(   (our CI is still on 11 express).

**Comment by zzzeek** [comment]
thanks for the help!

**Comment by cjbj** [comment]
@zzzeek what is the code doing after you have started a transaction - querying v$ tables?  I'd like to see what we could ask the DB team to expose through to drivers.

**Comment by zzzeek** [comment]
so I'm not too comfortable with the whole situation that I can't retrieve the "isolation level" without actually starting a transaction, even though I am setting it at the SESSION level.    the whole flow is basically being able to set the isoaltion level and to retrieve it, so here's set:

```
            dbapi_connection.autocommit = False
            connection.rollback()
            with connection.cursor() as cursor:
                cursor.execute("ALTER SESSION SET ISOLATION_LEVEL=%s" % level)

```

and here's get:

```
        with connection.cursor() as cursor:
            outval = cursor.var(str)
            cursor.execute(
                """
                begin
                   :trans_id := dbms_transaction.local_transaction_id( TRUE );
                end;
                """,
                {"trans_id": outval},
            )
            trans_id = outval.getvalue()
            xidusn, xidslot, xidsqn = trans_id.split(".", 2)

            cursor.execute(
                "SELECT CASE BITAND(t.flag, POWER(2, 28)) "
                "WHEN 0 THEN 'READ COMMITTED' "
                "ELSE 'SERIALIZABLE' END AS isolation_level "
                "FROM v$transaction t WHERE "
                "(t.xidusn, t.xidslot, t.xidsqn) = "
                "((:xidusn, :xidslot, :xidsqn))",
                {"xidusn": xidusn, "xidslot": xidslot, "xidsqn": xidsqn},
            )
            row = cursor.fetchone()
            if row is None:
                raise exc.InvalidRequestError(
                    "could not retrieve isolation level"
                )
            result = row[0]

        return result

```

if cx_Oracle wanted to expose setting the isolation level, I think your best place to do it is in your begin() method.  this wouldn't exactly flow well with how SQLAlchemy has set it up because we set the "isolation level" independently of starting the transaction usually and that we don't generally send any explicit begin() to the DBAPI driver.   as for retrieving it, it's a hard problem if one wants to get it without starting a transaction unless there is some other way it happens that googling was not able to locate.

**Comment by cjbj** [comment]
FWIW I got the input from the asktom gurus and it seems there isn't a better solution.

**Comment by zzzeek** [comment]
yeah my approach above is obviously drawn from many toms asked :)
