### ISSUE TITLE
Important cursor methods are unavailable when connected via self-defined class.

### ISSUE THREAD

**Issue by bergen288** [oracle/python-cx_Oracle#502]
1. What versions are you using?

platform.platform: Windows-10-10.0.17763-SP0
sys.maxsize > 2**32: True
platform.python_version: 3.8.2
cx_Oracle.version: 8.1.0
cx_Oracle.clientversion: (19, 6, 0, 0, 0)

2. Is it an error or a hang or a crash?
Important cursor methods are unavailable via self-defined class.  Only dunders are available.
3. What error(s) or behavior you are seeing?
I wrote OracleDB class to connect to Oracle DB via cx_Oracle package.
```
ora_config = {
            'host':         'jxppoezi-scan.onefiserv.net',
            'port':         2501,
            "user":         "riskread",
            "password":     "xxxxxxxx",
            'service':      'pcedidbx_jxppoezi'
            }

with OracleDB(ora_config) as conn:
    cursor = conn.cursor
    for attr in dir(cursor):
        print(attr)
```

Below is the output.  The 1st line is the connection.  As you can see, some important cursor methods (such as execute, fetchall, close) are not available.  I have a similar connect_oracle_db function which gives me the complete list of cursor methods.
```
Oracle ODBC Connection established: <cx_Oracle.Connection to riskread@jxppoezi-scan.onefiserv.net:2501/pcedidbx_jxppoezi>
__call__
__class__
__delattr__
__dir__
__doc__
__eq__
__format__
__ge__
__getattribute__
__gt__
__hash__
__init__
__init_subclass__
__le__
__lt__
__module__
__name__
__ne__
__new__
__qualname__
__reduce__
__reduce_ex__
__repr__
__self__
__setattr__
__sizeof__
__str__
__subclasshook__
__text_signature__
```

4. Include a runnable Python script that shows the problem.

Include all SQL needed to create the database schema.

Below is my OracleDB class:

```
class OracleDB:
    def __init__(self, config) -> None:
        self.configuration = config

    def __enter__(self) -> 'conn':
        try:
            CONN_STR = '{user}/{password}@{host}:{port}/{service}'.format(**self.configuration)
            self.conn = cx_Oracle.connect(CONN_STR)
            # self.cursor = self.conn.cursor
            print('Oracle ODBC Connection established:',self.conn)
            return self.conn
        except cx_Oracle.InterfaceError as err:
            raise ConnectionError(err)
        except cx_Oracle.ProgrammingError as err:
            raise CredentialsError(err)

    def __exit__(self, exc_type, exc_value, exc_trace) -> None:
        self.conn.commit()
        # self.cursor.close()
        self.conn.close()
        if exc_type is cx_Oracle.ProgrammingError:
            raise SQLError(exc_value)
        elif exc_type:
            raise exc_type(exc_value)
```

**Comment by anthony-tuininga** [comment]
Why do you think those methods should be available? Your class doesn't inherit anything from cx_Oracle so it will only have whatever it has defined itself.

**Comment by bergen288** [comment]
Sorry, it's my fault.  I missed ().  It should be cursor = conn.cursor().  Now all missing methods are available.

Thanks.
