### ISSUE TITLE
Binding array like executemany

### ISSUE THREAD

**Issue by SergioBlnc** [oracle/python-cx_Oracle#506]
1. What versions are you using?

Python 3.8.6
Cx_oracle 8.0.1

2. Describe the problem

How to run query with multiple columns in where in clause.
For example:
WHERE (col1, col2) IN ((1,1),(2,2),(3,3),....)

3. Include a runnable Python script that shows the problem.

**Comment by anthony-tuininga** [comment]
What you are looking for cannot be done! Take a look at the [documentation](https://cx-oracle.readthedocs.io/en/latest/user_guide/bind.html#binding-multiple-values-to-a-sql-where-in-clause) which gives you a few alternatives that may be of help.

**Comment by cjbj** [comment]
@SergioBlnc for SQL questions, the best place to ask is https://asktom.oracle.com/
