### ISSUE TITLE
Get oracle data, occasionally getting stuck

### ISSUE THREAD

**Issue by Little-orange** [oracle/python-cx_Oracle#508]
**Describe your question**

I have a service that keeps getting oracle data

Sometimes it will suddenly get stuck, no error is reported, there is no response, 
and it stays in this state, but Oracle has already reported an error.
The process status is running, and the memory and cpu usage will always stay in the state when it is stuck

 I have found suggestions for read timeouts and disabling connection pools, but they have not been resolved

oracle error info：
```
***********************************************************************

Fatal NI connect error 12170.

  VERSION INFORMATION:
	TNS for 64-bit Windows: Version 11.2.0.1.0 - Production
	Oracle Bequeath NT Protocol Adapter for 64-bit Windows: Version 11.2.0.1.0 - Production
	Windows NT TCP/IP NT Protocol Adapter for 64-bit Windows: Version 11.2.0.1.0 - Production
  Time: 19-12-2020 20:06:41
  Tracing not turned on.
  Tns error struct:
    ns main err code: 12535
    
TNS-12535: TNS: Operation timeout
    ns secondary err code: 12560
    nt main err code: 505
    
TNS-00505: Operation timeout
    nt secondary err code: 60
    nt OS err code: 0
  Client address: (ADDRESS=(PROTOCOL=tcp)(HOST=**.**.**.**)(PORT=54306))
Sat Dec 19 20:06:42 2020
```

sqlalachemy info：
```
INFO sqlalchemy.engine.bash.Engine BEGIN (implicit)
INFO sqlalchemy.engine.bash.Engine SELECT * FROM ( SELECT A.*, ROWNUM RN FROM (SELECT * FROM "TABLE" ORDER BY ROWID ASC) A WHERE ROWNUM < 500000 ) WHERE RN > 1
log.py[line:110] INFO BEGIN (implicit)
log.py[line:110] INFO sqlalchemy.engine.bash.Engine SELECT * FROM ( SELECT A.*, ROWNUM RN FROM (SELECT * FROM "TABLE" ORDER BY ROWID ASC) A WHERE ROWNUM < 500000 ) WHERE RN > 1
INFO sqlalchemy.engine.bash.Engine {}
log.py[line:110] INFO {}
```

code：
```python
from sqlalchemy import create_engine， text
from sqlalchemy.pool import NullPool

engine = create_engine(f"oracle://{user}:{password}@{address}:{port}/{sid}", poolclass=NullPool)
sql = f'SELECT * FROM ( SELECT A.*, ROWNUM RN FROM (SELECT * FROM "{table}" ORDER BY ROWID ASC) A WHERE ROWNUM < :limit + :skip + 1 ) WHERE RN >= :skip + 1'

with engine.connect() as connection:
    with connection.begin():
        result = connection.execute(text(sql), skip=skip, limit=limit)
        fields = result.keys()
  
        for row in result:
            rows.append(tuple(row))
```
Before I disabled the connection pool, this problem appeared more frequently, 
about once in a day, 
after disabling it, it occurred once in 3 days now

There is no regularity in the databases and tables being acquired when the stuck

**Example - please use the [Minimal, Complete, and Verifiable](http://stackoverflow.com/help/mcve) guidelines if possible**

**Complete stack trace, if applicable**

**Versions**
 - OS:centos 8.2
 - Python:3.6
 - SQLAlchemy:1.3.17
 - Database:Oracle Database 11g Enterprise Edition Release 11.2.0.1.0 - 64bit Production
 - DBAPI:cx_oracle：8.0.1

**Additional context**

**Have a nice day!**

**Comment by anthony-tuininga** [comment]
From what I can see here this looks like a network issue, which you will need to resolve. @cjbj may have additional information that may be of help.

**Comment by cjbj** [comment]
It does have the hallmark of a network issue.  You could turn on tracing and ask Oracle Support to take a look?

By the way, now that Centos 8 has be EOL'd by RedHat, you may be interested in https://blogs.oracle.com/scoter/switch-from-centos-to-oracle-linux-example

**Comment by Little-orange** [comment]
In fact, oracle is not under my control, I just call the data as a client

What I forgot to say is that centos8 is my python script deployment environment, not oracle, oracle is deployed in windows server 2008 r2 datacenter

**Comment by cjbj** [comment]
Thanks for the extra info. Let us know how your network investigation goes.

**Comment by Little-orange** [comment]
Judging from the previous similar errors reported by Oracle, the operation timeout error cause my client to get stuck. Are there any other suggestions to further locate this problem, thanks.

**Comment by cjbj** [comment]
Upgrade Oracle?

**Comment by Little-orange** [comment]
Is there any parameter in cx_oracle that allows me to circumvent this problem?

**Comment by cjbj** [comment]
You need to identify the problem first.  We have suggested you start by examining your networking, since it seems an intermittent timeout issue.
