### ISSUE TITLE
Why is the connection working when setting LD_LIBRARY_PATH, but not when passing its location to `cx_Oracle.init_oracle_client`?

### ISSUE THREAD

**Issue by LucaMingarelli** [oracle/python-cx_Oracle#509]
I am able to connect with `cx_Oracle.connect(...)` by setting the appropriate LD_LIBRARY_PATH before starting my python session.

However, I would like python to set this path so one solution I thought would work was 
```python
cx_Oracle.init_oracle_client(lib_dir=LD_LIBRARY_PATH , config_dir=f"{LD_LIBRARY_PATH }/network/admin/")
```
This however returns an error:
```DatabaseError: DPI-1047: Cannot locate a 64-bit Oracle Client library: "/home/cdsw/.local/lib/python3.6/site-packages/pyoracleclient/instantclient/libclntsh.so: file too short". ```

I then tried reinstalling the client (same version, but also tried other versions): repeating the command obove now changes the error into 

```DatabaseError: DPI-1047: Cannot locate a 64-bit Oracle Client library: "libnnz19.so: cannot open shared object file: No such file or directory".```

I have checked and the file mention is in the folder I am linking (LD_LIBRARY_PATH).

What is going on? I don't understand what this error is telling me.

**Platform and version info**:
platform.platform: Linux-3.10.0-1127.19.1.el7.x86_64-x86_64-with-debian-stretch-sid
sys.maxsize > 2**32: True
platform.python_version: 3.6.1
cx_Oracle version 8.1.0
client version 19.3.0.0

**Comment by cjbj** [comment]
This is a documented limitation of the way that the Oracle Instant Client libraries are built on Linux.  See https://cx-oracle.readthedocs.io/en/latest/user_guide/initialization.html:

> Note on Linux this is only useful to force immediate loading of the libraries because the libraries must also be in the system library search path. 

We'd all like a solution too, but it isn't trivial.
