### ISSUE TITLE
Connect to the non-existent ip and enter the stuck state

### ISSUE THREAD

**Issue by Little-orange** [oracle/python-cx_Oracle#510]
1. What versions are you using?

```
platform.platform: Linux-4.18.0-193.el8.x86_64-x86_64-with-glibc2.28
sys.maxsize > 2**32: True
platform.python_version: 3.8.5

cx_Oracle.version: 8.0.1
cx_Oracle.clientversion: (19, 8, 0, 0, 0)
```

2. Describe the problem

Try to connect to the non-existent IP
3. Include a runnable Python script that shows the problem.
```
import cx_Oracle

for _ in range(10):
    try:
        connection = cx_Oracle.connect("c##user", "123456", "1.1.1.2/orcl", mode=cx_Oracle.SYSDBA, encoding="UTF-8")
    except Exception as e:
        print(e)
```

When I ping this ip, nothing is returned.

after running the script, there is no return

```
[root@manager tmp]# ps -axuf | grep python
root     1850473  0.0  0.3 388240 30144 pts/2    S+   22:36   0:00  |           \_ python oracle.py
```

After exiting through Ctrl + Z

```
[root@manager tmp]# ps -axuf | grep python
root     1850473  0.0  0.3 388240 30144 pts/2    T    22:36   0:00  |           \_ python oracle.py
```

**Comment by Little-orange** [comment]
https://docs.oracle.com/en/database/oracle/oracle-database/19/netrf/parameters-for-the-sqlnet.ora.html#GUID-53375272-7068-4400-8F2F-C32EDC471745

It seems that this problem can be solved by setting the sqlnet.ora file

**Comment by cjbj** [comment]
This is also mentioned in the cx_Oracle documentation: https://cx-oracle.readthedocs.io/en/latest/user_guide/ha.html#network-configuration
