### ISSUE TITLE
Create connection pool connect as sysdba without password

### ISSUE THREAD

**Issue by NamNDT** [oracle/python-cx_Oracle#511]
Hi every one,
 Can anyone help me how to create connection pool with sysdba without password?
I take a 2 day to read cx_Oracle connection pool document, but no get answer. 
I try with cx_Oracle standalone connecto OK
`connection = cx_Oracle.connect('/', mode=cx_Oracle.SYSDBA, encoding='UTF-8')`
but i don't know do that with cx_Oracle.SessionPool.

**Comment by anthony-tuininga** [comment]
There is no way to do this and it is not recommended either! SYSDBA should only be used for specific, targeted reasons. As such, it is best to create a standalone connection, do what you need to do and then close the connection. If you believe you have a legitimate reason for creating such a pool, please let us know!

**Comment by NamNDT** [comment]
> There is no way to do this and it is not recommended either! SYSDBA should only be used for specific, targeted reasons. As such, it is best to create a standalone connection, do what you need to do and then close the connection. If you believe you have a legitimate reason for creating such a pool, please let us know!

Happy new year!! 
You correct me, thank for your information. I will use standalone connection instead of pool connection.
