### ISSUE TITLE
Is it possible to run cx_Oracle on ubuntu ?

### ISSUE THREAD

**Issue by GoodManWEN** [oracle/python-cx_Oracle#512]
1. What versions are you using?
```
cx-Oracle 8.1.0 with Oracle database 19c

platform.platform: Linux-5.8.0-34-generic-x86_64-with-glibc2.31
sys.maxsize > 2**32: True
platform.python_version: 3.9.1
```

2. Describe the problem

I'm trying to connect to Oracle database on ubuntu system cause there're some services I'm trying to switch to oracle from mysql whilst rely on the specific system could not be easily changed.

As I followed instructions from [installation guide](https://cx-oracle.readthedocs.io/en/latest/user_guide/installation.html#install-cx-oracle) and try to install oracle client before I use cx-Oracle , since only rpm packges are aviable on official website which is not the supported formats on ubuntu .So I used a tool called alien to convert .rpm package into .deb package and installed it.

However after installation , when Im use cx-Oracle to connect to the database , it still shows the following error:
```
> import cx_Oracle
> connection = cx_Oracle.connect("system","123456","192.168.1.100/orcl")

cx_Oracle.DatabaseError: DPI-1047: Cannot locate a 64-bit Oracle Client library: 
"libaio.so.1: cannot open shared object file: No such file or directory". 
See https://cx-oracle.readthedocs.io/en/latest/user_guide/installation.html for help
```
It seems like the installation of oracle client was not success.

As far as I know the ubuntu system is not recommend to use oracle database cause the whole oracle system was built on a very different distribution route(redhat series) , so Im wondering if its possible to connect to oralce on ubuntu  , the only problem of connection error is I did something wrong, or it totally cant connect at all.  Thanks.

3. Show the directory listing where your Oracle Client libraries are installed (e.g. the Instant Client directory).  Is it 64-bit or 32-bit?

4. Show what the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) is set to?

5. Show any Oracle environment variables set (e.g. ORACLE_HOME, ORACLE_BASE).

**Comment by cjbj** [comment]
- You probably just need to install libaio1 manually. 

- If this doesn't work, show us the exact steps you used to download and install.  E.g. did you accidentally get 32-bit Oracle libraries?  How did you convert the RPMs?

- Why not just use the Instant Client ZIP files from the official website https://www.oracle.com/database/technologies/instant-client/linux-x86-64-downloads.html ?

**Comment by GoodManWEN** [comment]
@cjbj Thanks for reply.

Since Im still a fresher to oracle database , the reason why Im not using direct unziped files is because Im not quite sure where to put those files to make in order to make them work.

As mentioned above ,I've download the 64bit rpm client package from https://www.oracle.com/database/technologies/instant-client/linux-x86-64-downloads.html (with the package name of "oracle-instantclient-basic-21.1.0.0.0-1.x86_64.rpm") , and here re all the steps I did after download:

```
# newly installed ubuntu 20.04 system.
root@wen-pc:~# add-apt-repository universe
root@wen-pc:~# apt update
...
root@wen-pc:~# apt install alien
...
root@wen-pc:~# alien oracle-instantclient-basic-21.1.0.0.0-1.x86_64.rpm
oracle-instantclient-basic_21.1.0.0.0-2_amd64.deb generated
root@wen-pc:~# dpkg -i oracle-instantclient-basic_21.1.0.0.0-2_amd64.deb
```

**Comment by cjbj** [comment]
As mentioned, try installing the libaio1 package, probably with `apt install libaio1`

**Comment by GoodManWEN** [comment]
@cjbj Sussesfully connected after `apt install libaio1` , I'll close this issue , many thanks !
