### ISSUE TITLE
about fetch oracle date type data return error: year -5502 is out of range

### ISSUE THREAD

**Issue by Mr-Dada** [oracle/python-cx_Oracle#513]
![date](https://user-images.githubusercontent.com/22296017/103857341-4468ee80-50f1-11eb-928a-fdcb26ecab35.png)
when i try to use the method fetchall() to fetch all the date type data like the attachment  pic.it return an error,which is just like below:
rs = cr.fetchall()
ValueError: year -5502 is out of range

if you can not look at the pic,just look at the data like below
date	        date	         date	   date
0000/0/0	2012/7/2	2010/6/7	2010/9/30
0201/3/19 23:54:08	2016/3/20	2013/4/15	2013/4/24
0201/12/17	2014/12/17	2012/1/15	2013/2/27
0000/0/0	2012/8/4	2011/8/15	2012/9/28
0000/0/0	2012/8/4	2010/8/13	2010/12/31
0000/0/0	2012/8/4	2010/8/13	2010/8/31
0201/3/20	2014/3/20	2011/10/13	2012/11/26
0000/0/0	2014/9/27	2012/2/29	2012/6/30
0213/12/17 23:54:08	2099/12/31	2014/1/8	2014/2/16
0000/0/0	2012/8/4	2010/8/9	2010/11/30
0000/0/0	2012/8/4	2010/8/10	2011/12/31
0201/9/19	2014/9/18	2012/10/23	2013/3/31
1934/4/4	2016/4/6	2010/4/14	
0214/6/20	2020/6/20	2014/6/21	2015/2/28
0201/5/25	2014/5/24	2011/6/13	2012/4/30
1900/2/11	2013/5/24	2010/7/6	2010/12/31
0215/11/28	2018/11/27	2015/11/28	2016/9/30
0215/11/28	2018/11/27	2015/11/28	2016/5/31
1934/4/4	2016/4/6	2019/6/4

**Comment by cjbj** [comment]
Corrupt data?

Can you pinpoint the exact row that is giving problems?
