### ISSUE TITLE
Connection over Websocket Protocol

### ISSUE THREAD

**Issue by JanRoeSax** [oracle/python-cx_Oracle#514]
1. What versions are you using?

platform.platform: Windows-10-10.0.17763-SP0
sys.maxsize > 2**32: True
platform.python_version: 3.7.5

cx_Oracle.version: 8.1.0
cx_Oracle.clientversion: (19, 6, 0, 0, 0)

2. Describe the problem

Is it possible to connect to oracle database with Websocket and/or SecureWebSocket protocol?

```
import cx_Oracle
dsn = "(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=WS)(HOST=examplehost)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=exampleservice)))"
connection=cx_Oracle.connect('ec_sys','sys',dsn)

```
best regards
Jan

**Comment by cjbj** [comment]
According to the Net doc, yes: https://docs.oracle.com/en/database/oracle/oracle-database/19/netag/understanding-communication-layers.html#GUID-2C1FCF9D-0289-447F-9C19-F10615DF85B9

@onmp may have more comments.

**Comment by onmp** [comment]
Connection using WebSocket Protocol is supported.

**Comment by JanRoeSax** [comment]
Thanks for your help. I solved the problem,  I used the oracle Instant client to connect to the db, this does not work.

 I tried it with the database client and it works.

**Comment by cjbj** [comment]
What didn't work?

**Comment by JanRoeSax** [comment]
while using the instantclient you get the error,:
ORA-12557: TNS:protocol adapter not loadable

you get this error also, if you try to connect with sqlplus over command line. conclude from this, its not a CX_Oracle problem, its a instantclient problem.

**Comment by cjbj** [comment]
Can you describe the setup more, so I can work with whoever needs to be involved to make Instant Client work?
