### ISSUE TITLE
login failure when password contains a reserved character

### ISSUE THREAD

**Issue by fejao** [oracle/python-cx_Oracle#515]
## 1. What versions are you using?
```
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> import platform
>>> 
>>> print("platform.platform:", platform.platform())
platform.platform: Linux-5.4.0-58-generic-x86_64-with-glibc2.29
>>> print("sys.maxsize > 2**32:", sys.maxsize > 2**32)
sys.maxsize > 2**32: True
>>> print("platform.python_version:", platform.python_version())
platform.python_version: 3.8.5
```

```
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cx_Oracle
>>> print("cx_Oracle.version:", cx_Oracle.version)
cx_Oracle.version: 8.1.0
>>> print("cx_Oracle.clientversion:", cx_Oracle.clientversion())
cx_Oracle.clientversion: (21, 1, 0, 0, 0)
>>>
```

## 2. Is it an error or a hang or a crash?
ERROR

## 3. What error(s) or behavior you are seeing?
Unable to login to DB when using a special character on the password field, specially the _@_ character 

## 4. Include a runnable Python script that shows the problem.
Tests were done following [documentation](https://cx-oracle.readthedocs.io/en/latest/user_guide/connection_handling.html#oracle-net-connect-descriptor-strings) and the [example](https://github.com/oracle/python-cx_Oracle/blob/master/samples/tutorial/connect.py) provided
  ### 4.1. Test 1
```
import cx_Oracle
dsn = cx_Oracle.makedsn("10.10.0.10", 1521, service_name="TESTDB1")
conn = cx_Oracle.connect(
    user="test_user",
    password="password@",
    dsn=dsn, 
    encoding="UTF-8"
)
```
  ### 4.2. Test 2
```
import cx_Oracle
conn = cx_Oracle.connect(
    user="test_user",
    password="password@",
    dsn="(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=10.10.0.10)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=TESTDB1)))",
    encoding="UTF-8"
)
```
  ### 4.3. Test 3
```
import cx_Oracle
conn = cx_Oracle.connect(
    user="test_user",
    password="password@",
    dsn="10.10.0.10/TESTDB1",
    encoding="UTF-8"
)
```
  ### 4.4. Test 4
```
import cx_Oracle
conn = cx_Oracle.connect("test_user", "password@", "10.10.0.10/TESTDB1", encoding="UTF-8")
```
## 5. Tests outputs
All tests have the same outputs
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
cx_Oracle.DatabaseError: ORA-01017: invalid username/password; logon denied
```

**Comment by zzzeek** [comment]
I think you should also note that your cx_Oracle *does* connect when you send a connect string all at once.  otherwise people will think you are just using the wrong password.  can you illustrate that ?

**Comment by fejao** [comment]
Here is the only way that I can manage to connect using the cx_Oracle 
```
import cx_Oracle
conn = cx_Oracle.connect("test_user/password@//10.10.0.10:1521/TESTDB1")
conn.close()
```

**Comment by anthony-tuininga** [comment]
Can you provide a concrete example that fails? In other words:

```python
import cx_Oracle

USER = "test_user"
PASSWORD = "pass/word"
CONNECT_STRING = "localhost/TESTDB1"

DSN = f"{USER}/{PASSWORD}@{CONNECT_STRING}"

cx_Oracle.connect(user=USER, password=PASSWORD, dsn=CONNECT_STRING)
cx_Oracle.connect(DSN)
```

That code snippet works for me. Does it for you?

**Comment by anthony-tuininga** [comment]
Just to be clear, I tried the password `password@` as well and didn't run into any problems.

**Comment by anthony-tuininga** [comment]
Ah, I may have discovered the source of the issue -- which my example should also demonstrate. In your example you used the following connect string: `test_user/password@//10.10.0.10:1521/TESTDB1`. That means that the password is in fact `password` as everything after the `@` symbol is assumed to be the host/port/service name. So for your case you would need the following connect string: `test_user/password@@10.10.0.10:1521/TESTDB1`.

**Comment by zzzeek** [comment]
I think their password is "password' in that case.   the composed connect string works for them and not distinct arguments.

**Comment by anthony-tuininga** [comment]
If that's the case, why are they passsing `password@` when using the separate arguments?

**Comment by zzzeek** [comment]
my theory is this was a misinterpretation of the connection string they were using, but I'm sure they will let us know :).

**Comment by yechiel-optimalq** [comment]
we are experiencing the same issue.
Password that contains "@" and is not able to connect in SQLALchemy. (bad logon)

We tried all possible variants and are still getting errors.
We are now using a workaround that was https://github.com/sqlalchemy/sqlalchemy/issues/5715

**Comment by zzzeek** [comment]
> we are experiencing the same issue.
> Password that contains "@" and is not able to connect in SQLALchemy. (bad logon)

can you confirm using a plain sql-plus connection that the @ sign is indeed part of the password?    additionally run the test script given above at https://github.com/oracle/python-cx_Oracle/issues/515#issuecomment-759722202 .

**Comment by NadavkOptimalQ** [comment]
> > we are experiencing the same issue.
> > Password that contains "@" and is not able to connect in SQLALchemy. (bad logon)
> 
> can you confirm using a plain sql-plus connection that the @ sign is indeed part of the password? additionally run the test script given above at [#515 (comment)](https://github.com/oracle/python-cx_Oracle/issues/515#issuecomment-759722202) .

Yes. Connecting through sql-plus with the @ in the password does work

**Comment by cjbj** [comment]
@yechiel-optimalq since this repo is for cx_Oracle, can you confirm the problem exists with a non-SQLAlchemy script?

**Comment by zzzeek** [comment]
specifically using a DSN string as above

**Comment by NadavkOptimalQ** [comment]
Running this code:
```
dsn = cx_Oracle.makedsn(host, port, sid=sid)
conn = cx_Oracle.connect(user=user, password=password, dsn=dsn)
```

Raises this error:
```
Traceback (most recent call last):
  File "test.py", line 35, in <module>
    conn = cx_Oracle.connect(user=user, password=password, dsn=dsn)
cx_Oracle.DatabaseError: ORA-01017: invalid username/password; logon denied
```

All the details used are correct 100%

**Comment by cjbj** [comment]
Give us more details.  With cx_Oracle 8.1, the script below runs fine:
```
import cx_Oracle

import sys
import os
if sys.platform.startswith("darwin"):
    cx_Oracle.init_oracle_client(lib_dir=os.environ.get("HOME")+"/Downloads/instantclient_19_8")

username = "cj2"
password = "cj2@"
connect_string = "localhost/orclpdb1"

connection = cx_Oracle.connect(username, password, connect_string)

with connection.cursor() as cursor:
    sql = """select user from dual"""
    for r in cursor.execute(sql):
        print(r)
```
Outputs:
```
('CJ2',)
```

**Comment by fejao** [comment]
Sorry, the email went direct to forums folder...
I'm on another project at the moment, and the solution was fighting with the admins for making the password longer and removing all special charecters.
The system I was developing is some OracleXpress, I don't know the version from it.
I do remember as connecting to the regular sqlplus cli I do had to use the password with the @ symbol or it won't connect
```
sqlplus test_user/password@>//10.10.0.10:1521/TESTDB1
```
The only way I could connect over the python code was using the method
```
import cx_Oracle
conn = cx_Oracle.connect("test_user/password@//10.10.0.10:1521/TESTDB1")
conn.close()
```

**Comment by cjbj** [comment]
This has been open for a while and I we've either reached agreement that there is a way to connect, or a difference in that there are two ways to connect.  Either way, we don't see anything to fix so I'm going to close this.  Feel free to comment if you want to continue the discussion.

**Comment by cjbj** [comment]
@Kremzon thanks for the update.  What's your definition of 'database' and 'sid'?

In cx_Oracle (and Oracle in general), the Easy Connect syntax works with Service Names, not the older System Identifiers (SIDs).

**Comment by Kremzon** [comment]
@cjbj 
Not really an oracle expert but I think this explains it: https://stackoverflow.com/questions/43866/how-sid-is-different-from-service-name-in-oracle-tnsnames-ora

I'm going to say that generally when we used this it was on a client's database (on prem) so we worked with what was provided for us.

**Comment by cjbj** [comment]
Thank you.  I think we can conclude this discussion!
