### ISSUE TITLE
Using cx_Oracle onto Openshift, dependencies issues

### ISSUE THREAD

**Issue by dbrrt** [oracle/python-cx_Oracle#52]
Is it possible to raise the following message : `cx_Oracle.DatabaseError: DPI-1047: Oracle Client library cannot be loaded: libaio.so.1: cannot open shared object file`
Onto OpenShift, it's not possible to access the POD as a Root through OpenShift, and I don't know how to do the trick to use this driver. I configured LD_LIBRARY_PATH, but when I try to import cx_Oracle via python shell, I got this error.

#### Answer the following questions:

1. What is your version of Python? Is it 32-bit or 64-bit?
Python 2.7 64-bit

2. What is your version of cx_Oracle?
5.3

3. What is your version of the Oracle client (e.g. Instant Client)?  How was it
   installed?  Where is it installed?
Instant client 11.1 (manually by a custom script in a virtual environment)

4. What is your version of the Oracle Database?
11g

5. What is your OS and version?
CentOS

6. What compiler version did you use?  For example, with GCC, run
   `gcc --version`.
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11) 

7. What environment variables did you set?  How *exactly* did you set them?
`ORACLE_HOME`
`LD_LIBRARY_PATH`

I set them in an environment file (not with export), apparently set before deployment.

8. What *exact* command caused the problem (e.g. what command did you try to
   install with)?  Who were you logged in as?

developer account in Minishift (preview mono node version on OpenShift)

9. What error(s) you are seeing?
`cx_Oracle.DatabaseError: DPI-1047: Oracle Client library cannot be loaded: libaio.so.1: cannot open shared object file`

**Comment by cjbj** [comment]
Oracle client libraries depend on the OS libaio package (or libaio1 on Ubuntu).  You need to install this separately; it's not something Oracle provides.

**Comment by dbrrt** [comment]
Yes I finally got it working, I downloaded libaio precompiled for my distribution (CentOS) and the issue vanished.
