### ISSUE TITLE
Setting the lib_dir path in the init_oracle_client() function doesn't work correctly

### ISSUE THREAD

**Issue by jferradans** [oracle/python-cx_Oracle#522]
Hi All,

1. What versions are you using?
Ubuntu 20.04
Python 3.8.5
cx_Oracle 8.1.0
Oracle instantclient 12.1.0.2

platform.platform: Linux-5.8.0-36-generic-x86_64-with-glibc2.29
sys.maxsize > 2**32: True
platform.python_version: 3.8.5

2. Is it an error or a hang or a crash?
Is an error, i think.

3. What error(s) or behavior you are seeing?
When i use the function init_oracle_client() to set up the lib_dir parameter, cx_Oracle is still searching some of the libraries in the system path.
Oracle instantclient is installed on the folder instantclient_12_1 on the working directory.
```
$ python3
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cx_Oracle
>>> cx_Oracle.init_oracle_client(lib_dir='instantclient_12_1')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
cx_Oracle.DatabaseError: DPI-1047: Cannot locate a 64-bit Oracle Client library: "libmql1.so: cannot open shared object file: No such file or directory". See https://cx-oracle.readthedocs.io/en/latest/user_guide/installation.html for help
>>>
```
If i export the path before ejecuting the python script, it works.
```
$ export LD_LIBRARY_PATH=instantclient_12_1
$ python3
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cx_Oracle
>>> cx_Oracle.init_oracle_client()
>>> print("cx_Oracle.version:", cx_Oracle.version)
cx_Oracle.version: 8.1.0
>>> print("cx_Oracle.clientversion:", cx_Oracle.clientversion())
cx_Oracle.clientversion: (12, 1, 0, 2, 0)
>>>
```

4. Include a runnable Python script that shows the problem.
```python
import cx_Oracle
cx_Oracle.init_oracle_client(lib_dir='instantclient_12_1')
```

Thanks
Regards

**Comment by anthony-tuininga** [comment]
This is a known issue and is a limitation of the underlying Oracle Client libraries. There is nothing that can be done about this currently on Linux. You will have to set `LD_LIBRARY_PATH` or configure `ld.so.conf`. See the [documentation](https://cx-oracle.readthedocs.io/en/latest/user_guide/initialization.html#libinit) which explicitly states this, too! I wish this worked, too, and am pushing internally to have this limitation removed.

**Comment by jferradans** [comment]
> This is a known issue and is a limitation of the underlying Oracle Client libraries. There is nothing that can be done about this currently on Linux. You will have to set `LD_LIBRARY_PATH` or configure `ld.so.conf`. See the [documentation](https://cx-oracle.readthedocs.io/en/latest/user_guide/initialization.html#libinit) which explicitly states this, too! I wish this worked, too, and am pushing internally to have this limitation removed.

Oh, ok, i understand. Thanks for the explanation.

Regards
