### ISSUE TITLE
bug in documentation in relation to Object type objects

### ISSUE THREAD

**Issue by gtlawton** [oracle/python-cx_Oracle#523]
To my mind there is a discrepancy between the object type object as described in the documentation

ObjectType.element_type

with the actual object structure (e.g., for an arbitrary object)

>>> dir(PayloadType)
['__call__', '__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'attributes', 'elementType', 'iscollection', 'name', 'newobject', 'schema']

which references elementType **WITHOUT** the underscore.

Thought you should know ...

**Comment by anthony-tuininga** [comment]
What version are you using? That attribute was officially added in version 8.0. In versions prior to that it was undocumented (and was indeed called `elementType` and only was not None if it referred to an object type). It now follows the same pattern as the other `type` attributes -- either an object type or one of the DB_TYPE_* constants. If you are indeed using a version earlier than 8.0, please pretend it doesn't exist!

**Comment by gtlawton** [comment]
python -m pip install cx_Oracle --upgrade
Collecting cx_Oracle
  Downloading cx_Oracle-8.1.0-cp37-cp37m-win_amd64.whl (210 kB)
     |████████████████████████████████| 210 kB 939 kB/s
Installing collected packages: cx-Oracle
  Attempting uninstall: cx-Oracle
    Found existing installation: cx-Oracle 7.3.0
    Uninstalling cx-Oracle-7.3.0:
      Successfully uninstalled cx-Oracle-7.3.0
Successfully installed cx-Oracle-8.1.0

>>> dir(PayloadType)
['__call__', '__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'attributes', '**element_type**', 'iscollection', 'name', 'newobject', 'schema']
>

I will have to raise a bug about the state of my brain.
