### ISSUE TITLE
Discrepancy between functionality of attributes object and documentation

### ISSUE THREAD

**Issue by gtlawton** [oracle/python-cx_Oracle#524]
Given an object type "PayloadType" I can see the attributes.

PayloadType.attributes
[<cx_Oracle.ObjectAttribute ACTION>, <cx_Oracle.ObjectAttribute NAME>, <cx_Oracle.ObjectAttribute CURRENT_STATUS>, <cx_Oracle.ObjectAttribute NEXT_STATUS>, <cx_Oracle.ObjectAttribute TXN>, <cx_Oracle.ObjectAttribute AGENT_CONTROL>]
>>> PayloadType.attributes[0]
<cx_Oracle.ObjectAttribute ACTION>

According to the documentation, I should be able to expose the name and type:

https://cx-oracle.readthedocs.io/en/latest/api_manual/object_type.html#object-attribute-objects

>>> PayloadType.attributes[0].name
'ACTION'

>>> PayloadType.attributes[0].type
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'cx_Oracle.ObjectAttribute' object has no attribute 'type'

I cannot find the attribute in the object type (which is a shame because I would like to iterate over it):

>>> dir(PayloadType.attributes[0])
['__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'name']

**Comment by anthony-tuininga** [comment]
It is helpful if you include the version you are using. Once again, the attribute you are referencing was added in 8.0 and I suspect that you are not using version 8.x. Note that version added attribute in the documentation!

**Comment by cjbj** [comment]
If you scroll to the very bottom of the manual's menu, you can click the green 'v:latest' arrow :

<img width="323" alt="Screen Shot 2021-01-22 at 9 12 38 am" src="https://user-images.githubusercontent.com/200778/105418990-1b6c6000-5c92-11eb-8d8e-2cd62c9a80a3.png">

This will give you a  selector where you can select the appropriate manual version:

<img width="310" alt="Screen Shot 2021-01-22 at 9 14 25 am" src="https://user-images.githubusercontent.com/200778/105419103-4c4c9500-5c92-11eb-94f8-301b994be176.png">

**Comment by gtlawton** [comment]
Your suspicions were well founded.  The issue was indeed a difference between the installed version and the documentation I was reading.  An upgrade has "fixed" it.

Please close the issue at your earliest convenience.

Thanks.
