### ISSUE TITLE
cx_Oracle fails to build under PyPy

### ISSUE THREAD

**Issue by vnaydionov** [oracle/python-cx_Oracle#53]
I tried to `pip install` cx_Oracle with PyPy and got the following error:

```
error: ‘PyDateTime_Delta’ has no member named ‘seconds’
```

https://gist.githubusercontent.com/vnaydionov/93d2118233f6f890bd46afd52a0a4310/raw/ab114b4d35c7f8282d7ba3018345e1a34893a404/gistfile1.txt

With the latest cx_Oracle code from this repo the problem is essentially the same.

- PyPy version: Python 2.7.13 (d135217574a6, Jul 14 2017, 22:00:09) [PyPy 5.9.0-alpha0 with GCC 6.2.0 20160901]
- GCC version: x86_64-linux-gnu version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3)
- Oracle instant client: instantclient_12_1

**Comment by anthony-tuininga** [comment]
The pull request has been merged so I presume this is now fixed. If not, please re-open.
