### ISSUE TITLE
Please add PEP 484 type stubs

### ISSUE THREAD

**Issue by intgr** [oracle/python-cx_Oracle#533]
In recent years, there has been a large shift in Python towards stronger typing, static analysis, etc. There are many tools like PyCharm and mypy that can take advantage of type information (https://github.com/typeddjango/awesome-python-typing)

I'm using both cx_Oracle and mypy and it would be nice to be able to type-check code interacting with cx_Oracle.

https://www.python.org/dev/peps/pep-0561/ PEP 561 "Distributing and Packaging Type Information" explains how to define type stubs and include them in the package.

**Comment by anthony-tuininga** [comment]
This appears to be a duplicate of #488. Can you confirm?

**Comment by intgr** [comment]
Yes, thanks. I tried looking for duplicates prior to reporting but didn't find it.

**Comment by cjbj** [comment]
@intgr how about contributing the stubs to cx_Oracle!!  See https://github.com/oracle/python-cx_Oracle/blob/master/CONTRIBUTING.md
