### ISSUE TITLE
cx_Oracle Failed to install

### ISSUE THREAD

**Issue by wcrober** [oracle/python-cx_Oracle#534]
Please see the details related to my inability to install cx_Oracle until I implemented the workaround below. 

**Environment Details:**
1.) python version: Python 3.8.2
2.) uname: Darwin TDML-HY8MD6M 19.6.0 Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; root:xnu-6153.141.10~1/RELEASE_X86_64 x86_64
3.) pip version: 21.0

**Workaround:**
export ARCHFLAGS=“-arch x86_64” 

**Error Snippet:**
pip install cx_Oracle ….   fatal error: too many errors emitted, stopping now [-ferror-limit=]
  20 errors generated.
  error: command ‘clang’ failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for cx-Oracle
Failed to build cx-Oracle
ERROR: Could not build wheels for cx-Oracle which use PEP 517 and cannot be installed directly

**Comment by cjbj** [comment]
Thanks for posting.  I'll close it but I'm sure future readers will come across it.

This was also noted in https://github.com/oracle/python-cx_Oracle/issues/489#issuecomment-768190388
