### ISSUE TITLE
Session information (module, action, clientinfo, clientidentifier) not set without commit even if autocommit is on

### ISSUE THREAD

**Issue by gtlawton** [oracle/python-cx_Oracle#537]
1. What is the link to the documentation section that needs improving?
https://cx-oracle.readthedocs.io/en/latest/api_manual/connection.html

2. Describe the confusion
The fact that even though autocommit is on (True) , setting the session information is not effected to external sessions

3. Suggest changes that would help
Mention that these settings are committed only with an explicit or implicit (e.g., DDL) commit (or if relevant, fix the autocommit functionality so that these settings are set directly in the session itself).

Here is a test program that demonstrates this:
```
import cx_Oracle as ora
import time

ocon = ora.connect("", "", "TOM", encoding="UTF-8")
ocon.autocommit = True
ocur = ocon.cursor()
ocur.prepare("SELECT program, module, action, client_info, client_identifier FROM v$session WHERE username = USER AND program = 'python.exe'")
ocur.execute(None)
[print(row) for row in ocur.fetchall()]
ocon.module = "DEMO"
ocon.action = 'demonstrating'
ocon.clientinfo = 'my information' 
ocon.client_identifier = 'my identification'
time.sleep(7)
# perform above SELECT in separate SQL*Plus session
# client settings are NOT visible
ocur.execute(None)
[print(row) for row in ocur.fetchall()]
# perform above SELECT in separate SQL*Plus session
# client settings ARE now visible - looks like the execute actually exerts the settings
time.sleep(3)
ocon.action = 'hidden' 
# above modification IS NOT visible without the following
ocon.commit()
time.sleep(3)

ocur.close()
ocon.close()
```

**Comment by gtlawton** [comment]
I noticed that this issue arises also when using the queueing mechanisms.  Setting the session attributes and then directly binding to a queue to dequeue leaves the settings invisible to external sessions.

**Comment by cjbj** [comment]
Does `ocur.execute(None)` actually do a round-trip to the DB?  If not (and it may just be a local call), then the attributes don't have anything to piggyback onto.  You can check roundtrips with https://cx-oracle.readthedocs.io/en/latest/user_guide/tuning.html#finding-the-number-of-round-trips

Now that cx_Oracle uses the statement cache, the need for `cursor.prepare()` is not so great.

(PS I updated your post and added triple-backticks to format the code.  Can you check the indentation is correct?)

**Comment by gtlawton** [comment]
As regards the roundtrips, I will see if I can establish the facts but quite simply, the autocommit setting does not seem to work entirely as expected.

As regards cursor preparation, old habits die hard.

As regards code formatting, thank you and all code is non-indented.

**Comment by cjbj** [comment]
Now I see the formatted code, I see I was a bit off track about the `execute(None)` since you have a fetch afterwards.  But the point about round-trips is the same: there has to be a round-trip after you set the attributes otherwise they are not sent to the DB.  Also, any autocommit is piggy-backed during statement execution. Just setting the attribute doesn't initiate a round-trip; autocommit is not relevant unless a statement is executed.

**Comment by gtlawton** [comment]
Should this behaviour, i.e., that the session settings are not externally visible without an implicit/explicit commit,  be documented or not? There are plenty of cases in practise where code modifies its action, say, before entering a "wait situation" such as input or dequeueing and useful instrumentation is not visible.

**Comment by gtlawton** [comment]
The use of the client roundtrip SQL shows indeed that there is no roundtrip to the database after simply setting the session values. The OCI Programmer's Guide also clearly documents where roundtrips do occur (OCIStmtExecute() does perform a roundtrip, OCIStmtPrepare() apparently not in version 11.2).  OCIPing() enforces a roundtrip and using the ping() method on the connection constructor also enforces the settings to become externally visible.

My approach henceforth would be to accompany any modifications to the client settings with a ping to the connection in such cases where no further executions will take place, e.g., when listening to dequeue.

**Comment by cjbj** [comment]
Documentation on the round-trip requirements after setting end-to-end tracing attributes is in https://cx-oracle.readthedocs.io/en/latest/user_guide/tracing_sql.html :

> The attributes are sent to the database when the next round-trip to the database occurs, for example when the next SQL statement is executed.

I've added a To Do note about the API manual entries to my long list of where improvements can be made.  In the meantime, PR's for any doc improvements are welcome.

Good point about dequeueing. Also, I'm glad to see the attributes being used.  Are you finding them useful for tracing?

**Comment by gtlawton** [comment]
Yes, that is what I was looking for.  

As regards the attributes usage, always used them for instrumentation and they are very helpful, I find, to provide a DBA with runtime information.

Thanks for the help/support and as far as I concerned the issue can be closed.
