### ISSUE TITLE
Please include cx_Logging, cx_PyOracleLib, cx_PyGenLib, cx_OracleTools

### ISSUE THREAD

**Issue by oferchen** [oracle/python-cx_Oracle#543]
1. Describe your new request in detail
  Please include the following tools that were a part of an earlier cx_oracle snapshot and are now excluded,
  https://github.com/anthony-tuininga/cx_Logging
  https://github.com/anthony-tuininga/cx_PyOracleLib
  https://github.com/anthony-tuininga/cx_PyGenLib
  https://github.com/anthony-tuininga/cx_OracleTools

2. Give supporting information about tools and operating systems.  Give relevant product version numbers
 Tools have to be repackage as a large libraries or several dependent small libraries, Linux/Linux 64bit

**Comment by anthony-tuininga** [comment]
Those are separate projects and were never part of cx_Oracle. cx_PyOracleLib and cx_OracleTools use cx_Oracle itself. The other two (cx_PyGenLib and cx_Logging) have nothing to do with cx_Oracle! Can you explain further what you would like to see?

**Comment by oferchen** [comment]
I would like to see cx_OracleTools get the same level of support and maintenance as cx_Oracle since it's so useful.

**Comment by anthony-tuininga** [comment]
> I would like to see cx_OracleTools get the same level of support and maintenance as cx_Oracle since it's so useful.

Ah! If you add an issue there, I'll see that and respond to it. It won't the same level of support and maintenance, though, as I work on cx_Oracle in my day job and the others are in my spare time. ;-)
