### ISSUE TITLE
Need documentation of how to set the LOB prefetch length indicator

### ISSUE THREAD

**Issue by alexhenrie** [oracle/python-cx_Oracle#544]
The release notes for cx_Oracle 7.2 mention "Added support for setting the LOB prefetch length indicator in order to reduce the number of round trips when fetching LOBs". That sounds really useful! Unfortunately, I can't find any information on how to use that feature.

**Comment by cjbj** [comment]
Apologies for not picking up that confusing wording sooner.  The enhancement is always on so you don't need to change anything to take advantage of it.

**Comment by cjbj** [comment]
See https://github.com/oracle/odpi/commit/58e6a07ff5bb428a09068456ef5231884fcb77db
