### ISSUE TITLE
How to use cx_oracle for creating a script for backup and recovery??

### ISSUE THREAD

**Issue by brixial** [oracle/python-cx_Oracle#554]
trying to create a python script for oracledb backup and restore and need help on how to do so if possible using cx_oracle.

**Comment by cjbj** [comment]
Backup and restore is best done with dedicated Oracle tools.   Why reinvent the wheel?

cx_Oracle lets you query and insert data with great flexibility.  We can answer specific questions about the API use.  For anything such as understanding the Oracle DB views, there are better places to ask.

**Comment by anthony-tuininga** [comment]
What exactly are you trying to backup/restore? There are a bunch of [tools](https://github.com/anthony-tuininga/cx_OracleTools) that I wrote some time ago that could be useful for a number of reasons. Without more information, though, its hard to know if they will help you in any way!
