### ISSUE TITLE
trouble running Oracle_cx on macOS

### ISSUE THREAD

**Issue by kindjacket** [oracle/python-cx_Oracle#56]
I've been battling with this for a long while and have tried a large number of solutions with no success

**1. What is your version of Python? Is it 32-bit or 64-bit?**
Python 3.6.2 - 64bit

**2. What is your version of cx_Oracle?**
cx-Oracle-6.0rc2

**3. What is your version of the Oracle client (e.g. Instant Client)?**  
instantclient-basic-macos.x64-12.1.0.2.0.zip as specified in https://oracle.github.io/odpi/doc/installation.html

**4. What is your version of the Oracle Database?**
NA

**5. What is your OS and version?**
MacOS Sierra v10.12.6

**6. What compiler version did you use?  For example, with GCC, run**
python -m pip install cx_Oracle --pre 
(as mentioned in the readme)

**7. What environment variables did you set?  How *exactly* did you set them?**
?? I have followed the set up instructions for macOS here https://oracle.github.io/odpi/doc/installation.html. What am I missing?

**8. What *exact* command caused the problem (e.g. what command did you try to
   install with)?  Who were you logged in as?**
python3
>>> import cx_Oracle

**9. What error(s) you are seeing?**

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
cx_Oracle.DatabaseError: DPI-1047: 64 bit Oracle Client library cannot be loaded: dlopen(libclntsh.dylib, 1): image not found. See https://oracle.github.io/odpi/doc/installation.html#macos for help`

**Comment by anthony-tuininga** [comment]
Check out the cx_Oracle installation troubleshooting and let me know if that helps: http://cx-oracle.readthedocs.io/en/latest/installation.html#troubleshooting.

**Comment by kindjacket** [comment]
Hi @anthony-tuininga 

Thanks for responding. 

I have troubleshooted all of the things discussed in the docs.

1. I have tested putting `libclntsh.dylib.12.1` in  _/usr/local/lib_ instead of _~/lib_ but it doesn't help. ✅
2. Python 3.6.2 was installed using `brew install python3` ✅
3. Everything is running on 64-bit ✅

I still get the same error. 😔

**Comment by cjbj** [comment]
Check you are using the right versions - your install command used 'python' but you said you have python 3.  I need to execute 'python3'  and 'pip3' (perhaps because I have both Python 2 & 3 installed).

I just installed homebrew python3 and cx_Oracle:
```
cjones@mac:~$ pip3 install cx_Oracle --pre
```

It runs fine:
```
cjones@mac:~$ python3
python3
Python 3.6.2 (default, Jul 17 2017, 16:44:45) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cx_Oracle
import cx_Oracle
>>> db = cx_Oracle.connect("cj", "cj", "localhost/pdborcl")
db = cx_Oracle.connect("cj", "cj", "localhost/pdborcl")
>>> db.version
db.version
'12.2.0.1.0'
>>> 
```

You can see my Instant Client set up in https://github.com/oracle/python-cx_Oracle/issues/48#issuecomment-315880229 (from when I only had homebrew Python 2)

**Comment by kindjacket** [comment]
Hi @cjbj 

Yes I forgot to mention I ran 
`python3 -m pip install python cx_Oracle --pre` to install cx_Oracle

I just tries uninstalling this and reinstalling it using
`pip3 install cx_Oracle --pre`

I still get the same error.

Maybe having two version of python is confusing something somewhere

**Comment by cjbj** [comment]
I have two versions now.

Why not give us the `ls -l` of your instant client & ~/lib set up (and make sure to clean up /usr/local/lib, if you're not using that)

**Comment by kindjacket** [comment]
fixed it! The issue was because the instant client was not located in my /User folder. Therefore I think there may have been a permissions issue.

For future reference the documentation needs changing (see below) (from this webpage https://oracle.github.io/odpi/doc/installation.html#macos )

_To run ODPI-C applications with Oracle Instant Client zip files:

Download the 11.2 or 12.1 “Basic” or “Basic Light” zip file from here. Choose either a 64-bit or 32-bit package, matching your application architecture. Most applications use 64-bit.

Unzip the package into a single directory that is accessible to your application. For example:

mkdir -p ~~/opt/oracle~~ ~/opt/oracle
unzip instantclient-basic-macos.x64-12.1.0.2.0.zip
Add links to $HOME/lib to enable applications to find the library. For example:

mkdir ~/lib
ln -s /opt/oracle/instantclient_12_1/libclntsh.dylib.12.1 ~/lib/_

**Comment by cjbj** [comment]
Glad you resolved it.  Can you revisit what your directory permissions were in `/opt`? Were they readable by Python? I used to use `/opt/oracle` a lot - and just tested it again without problems. To use a concrete & consistent location for documentation and library detection, we've referenced this location for a while (e.g [back in 2015](https://github.com/oracle/node-oracledb/blob/v0.3.1/INSTALL.md#instosx)) and haven't heard any issues.

**Comment by kindjacket** [comment]
The permission for the folder are - `drwxr-xr-x`

Looks like python can read but not write to the directory -

```
>>> os.access('/opt/oracle', os.W_OK)
False
>>> os.access('/opt/oracle', os.R_OK)
True

**Comment by cjbj** [comment]
@kindjacket that should have been fine.  Hmm.  

At the moment I'm inclined to leave the doc referencing /opt/oracle, until we get more data points.

**Comment by kindjacket** [comment]
@cjbj Yeah makes sense. Thanks for the help 🙂

**Comment by johndifini** [comment]
I had the same issue, and @kindjacket's instructions (put opt/oracle in home dir) worked perfectly!

**Comment by cjbj** [comment]
@johndifini thanks for the feedback.  I still can't reproduce any problem.

Were you originally following the latest install doc?: http://cx-oracle.readthedocs.io/en/latest/installation.html#installing-cx-oracle-on-macos

**Comment by hanleyel** [comment]
Had the same issue as well and @kindjacket's instructions worked for me, too.

**Comment by amiteshri92** [comment]
+1, after following @kindjacket instructions.

**Comment by paniff** [comment]
I have the similar issue, I do have the instantclient in the home directory. 
cx_Oracle.DatabaseError: DPI-1047: Cannot locate a 64-bit Oracle Client library: "dlopen(libclntsh.dylib, 1): no suitable image found.  Did find:
      ~/Desktop/instantclient_12_2//libclntsh.dylib: mach-o, but wrong architecture

I'm running python3.9 and on M1 mac OS Big Sur 11.4

**Comment by cjbj** [comment]
@paniff this is a long closed issue.  For M1, see https://github.com/oracle/python-cx_Oracle/issues/569
