### ISSUE TITLE
Hang in SessionPool.acquire

### ISSUE THREAD

**Issue by mcejp** [oracle/python-cx_Oracle#560]
### What versions are you using?

```
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production

platform.platform: Linux-4.19.0-12-amd64-x86_64-with-debian-10.8
sys.maxsize > 2**32: True
platform.python_version: 3.7.3

cx_Oracle.version: 8.0.1
cx_Oracle.clientversion: (19, 9, 0, 0, 0)
```

### Is it an error or a hang or a crash?

Hang in `SessionPool.acquire`

### What error(s) or behavior you are seeing?

This might be similar to #440, or completely unrelated.

I am using `SPOOL_ATTRVAL_TIMEDWAIT` and setting `waitTimeout`, yet I sometimes get a hang in `acquire` after a previous query times out, raising DPI-1067 and ORA-24300.

### Include a runnable Python script that shows the problem.

I do not have a self-contained test case, but I believe the exact sequence to be the following:
- create pool:
```
self.pool = cx_Oracle.SessionPool(
            ....
            getmode=cx_Oracle.SPOOL_ATTRVAL_TIMEDWAIT,
            waitTimeout=5000
        )
```
- successfully execute many queries between pairs of `acquire`/`release`
- at some point a query times out (possibly due to some issue in the DB)
```
connection = self.pool.acquire()
connection.callTimeout = 5000

try:
    with connection.cursor() as cursor:
            cursor.execute(...)  <--- triggers cx_Oracle.DatabaseError: DPI-1067: call timeout of 5000 ms exceeded with ORA-3156
    # end of cursor's context manager here additionally triggers cx_Oracle.DatabaseError: ORA-24300: bad value for mode

finally:
    self.pool.release(connection)
```
- on the next iteration of the same code:
```
connection = self.pool.acquire() <--- hangs forever
connection.callTimeout = 5000    <--- on one of these lines
```

---

As the problems only occurs every few days, I cannot narrow it down more specifically at the moment.

In #440, some lower-level settings (`EXPIRE_TIME`, `DISABLE_OOB`) were brought up. Is it possible that a connection gets "poisoned" in a way that `waitTimeout` does not apply anymore and one of these low-level parameters need to be tuned?

For the moment, I have worked around by detecting `ORA-24300` specifically, and dropping the connection from the pool.

**Comment by cjbj** [comment]
Can you try with DPI_DEBUG_LEVEL=4 and share the trace?

**Comment by anthony-tuininga** [comment]
Looks to me like this is the same issue faced in #561. A patch has been released to address that issue. If you are able to build cx_Oracle yourself you can verify that your situation is also resolved. Or you can wait until cx_Oracle 8.2 is released which will contain this patch.

**Comment by mcejp** [comment]
Thanks for the heads-up! For the moment I am still waiting for the issue to re-occur with `DPI_DEBUG_LEVEL=4` -- but perhaps 8.2 will be out before it does 😄

**Comment by anthony-tuininga** [comment]
cx_Oracle 8.2 has just been released and contains the improved dead connection detection. You will now get the error `DPI-1080: connection was closed by ORA-3156` and subsequent attempts to use the connection will get the error `DPI-1010: not connected`. You should no longer need to capture the `ORA-24300: bad value for mode` exception. Let me know if this works for you!

**Comment by mcejp** [comment]
I have not been able to reproduce the issue since I have increased the logging debug level. It probably very dependent on the momentary state of the network.

In the interest of moving on, I will update to cx_Oracle 8.2 and close the issue now. Thank you for the fast fix.

**Comment by Exzentttt** [comment]
Hi, I'm using version 8.3.0 and faced a similar problem, after about 24 hours, a DPI-1080 error appears: connection was closed by ORA-2396 on some connections. 

It seems that there are broken connections, how can this be overcome?

`self.pool = cx_Oracle.SessionPool(min=10, max=10, increment=0, timeout=120)`

**Comment by cjbj** [comment]
@Exzentttt can you open a new issue?  Thanks.
