### ISSUE TITLE
SessionPool can not release connection after time out exception

### ISSUE THREAD

**Issue by chengchengbai** [oracle/python-cx_Oracle#561]
### 1. What versions are you using?

```
platform.platform: Linux-4.4.21-69-default-x86_64-with-centos-7.8.2003-Core
sys.maxsize > 2**32: True
platform.python_version: 3.7.9
cx_Oracle.version: 8.1.0
cx_Oracle.clientversion: (19, 11, 0, 0, 0)
```
### 2. Describe the problem

I set connection.callTimeout, and tigger the time out exception: DPI-1067, but after this, I ran into "ORA-24300: bad value for mode" exception when trying to release this connection using pool.release(connection)

### 3. Include a runnable Python script that shows the problem.
```
from time import perf_counter
import cx_Oracle
from cx_Oracle import DatabaseError

oracle_conn_pool = cx_Oracle.SessionPool(param['user'], param['password'], param['host'],
                                  min=1, max=1, increment=0, threaded=True,
                                  getmode=cx_Oracle.SPOOL_ATTRVAL_WAIT)

sql = 'SELECT * FROM very_huge_table'
connection = oracle_conn_pool.acquire()
connection.callTimeout = 2    # 2 milliseconds, short enough to trigger time out exception
cursor = connection.cursor()
tic = perf_counter()
try:
    cursor.execute(sql)
    ret = cursor.fetchall()
except DatabaseError as e:
    toc = perf_counter()
    print("time out exception: {} time :{}".format(e, toc-tic))
finally:
    # raise cx_Oracle.DatabaseError: ORA-24300: bad value for mode
    # connection.close() also dose not work
    oracle_conn_pool.release(connection)
```
I set pool size 1, to verify whether cx_Oracle would release the connection automatically when exception occurs, the result is it does not release the connection, it seems to be disconnected by database, because when I try to reuse the same cursor to execute sql, the disconnected exception raised, and then if I try to request a new connection from the pool, it will hang forever.

**Comment by anthony-tuininga** [comment]
First, connection.callTimeout must be an *integer*. The value 1 is the smallest value that can be given. I see that there is an implicit conversion to integer that is taking place, which effectively means 0 in your case. That effectively means that no call timeout is in effect! You can verify by printing out the value of connection.callTimeout immediately after you set it.

Second, I'm not sure what value for mode is unacceptable. I am not able to replicate the issue myself so it might be a specific configuration that causes this. @cjbj may have some ideas.

Finally, I just pushed some changes to improve dead connection detection. If the call timeout is set too small, the connection will be marked as dead and you will get the error `DPI-1080: connection was closed by ORA-3156`. Subsequent attempts to use the connection will give you the error `DPI-1010: not connected`.

**Comment by anthony-tuininga** [comment]
> Second, I'm not sure what value for mode is unacceptable. I am not able to replicate the issue myself so it might be a specific configuration that causes this. @cjbj may have some ideas.

I am actually able to replicate with 8.1 after all. This issue does not occur with the changes currently in master (planned for cx_Oracle 8.2). If you can build cx_Oracle yourself you can verify that is the case for you.

**Comment by chengchengbai** [comment]
> First, connection.callTimeout must be an _integer_. The value 1 is the smallest value that can be given. I see that there is an implicit conversion to integer that is taking place, which effectively means 0 in your case. That effectively means that no call timeout is in effect! You can verify by printing out the value of connection.callTimeout immediately after you set it.
> 
> Second, I'm not sure what value for mode is unacceptable. I am not able to replicate the issue myself so it might be a specific configuration that causes this. @cjbj may have some ideas.
> 
> Finally, I just pushed some changes to improve dead connection detection. If the call timeout is set too small, the connection will be marked as dead and you will get the error `DPI-1080: connection was closed by ORA-3156`. Subsequent attempts to use the connection will give you the error `DPI-1010: not connected`.



> First, connection.callTimeout must be an _integer_. The value 1 is the smallest value that can be given. I see that there is an implicit conversion to integer that is taking place, which effectively means 0 in your case. That effectively means that no call timeout is in effect! You can verify by printing out the value of connection.callTimeout immediately after you set it.
> 
> Second, I'm not sure what value for mode is unacceptable. I am not able to replicate the issue myself so it might be a specific configuration that causes this. @cjbj may have some ideas.
> 
> Finally, I just pushed some changes to improve dead connection detection. If the call timeout is set too small, the connection will be marked as dead and you will get the error `DPI-1080: connection was closed by ORA-3156`. Subsequent attempts to use the connection will give you the error `DPI-1010: not connected`.

oh, It was my mistake to write callTimeout 0.2 here, in my actual code the value is 2 milliseconds, I use 0.2 just to emphasize the time is short enough, I use 2 also can replicate this problem

**Comment by anthony-tuininga** [comment]
Ok, good. Then the issue you are experiencing is known and the current code resolves it for you. If you are able to build cx_Oracle yourself, you can verify that. It resolved it for me in any case!

**Comment by chengchengbai** [comment]
> Ok, good. Then the issue you are experiencing is known and the current code resolves it for you. If you are able to build cx_Oracle yourself, you can verify that. It resolved it for me in any case!

Thanks a lot  : )
