### ISSUE TITLE
Is cx_Oracle 8.1 compatible with Instant Client 12.1.0.2 ?

### ISSUE THREAD

**Issue by mkmoisen** [oracle/python-cx_Oracle#562]
Hello, this is just a question, not an issue.

I use cx_Oracle 6.4.1 and Oracle Instant Client 12.1.0.2.0.

I would like to upgrade cx_Oracle to 8.1, but am a bit confused on the interactions between cx_Oracle and the client libraries.

Will cx_Oracle 8.1 be compatible with Oracle 12.1 libraries?

If I do not upgrade my Oracle 12.1 libraries, will I be missing out on anything?

The database I connect to is actually Oracle 19. But it is non-trivial to upgrade the client libraries in the managed server we have.

Thank you.

**Comment by anthony-tuininga** [comment]
cx_Oracle 8.1 works with Oracle Client 11.2 and higher, so yes, it should work just fine with Oracle Instant Client 12.1.0.2.0.

**Comment by mkmoisen** [comment]
@anthony-tuininga Do you know if I might be missing out on any feature/optimization in cx_Orcacle if I do not upgrade my instant client to a later version?

**Comment by anthony-tuininga** [comment]
There are many features that have been added in 12.2, 18, 19 and 21. Take a look at the "new features" section of the documentation ([like this for 19c](https://docs.oracle.com/en/database/oracle/oracle-database/19/newft/new-features.html#GUID-5490FE65-562B-49DC-9246-661592C630F9)) and see if anything there piques your interest! The other reason for getting a newer client, though, is to take advantage of bug fixes and support for newer platforms. You can even use a 21 client with your 19 database. So yes, you are missing out -- but only you can answer whether that matters or not to your application(s). :-)

**Comment by mkmoisen** [comment]
Thank you.

**Comment by cjbj** [comment]
@mkmoisen although it doesn't mention versions, there might be some useful background in https://cx-oracle.readthedocs.io/en/latest/user_guide/introduction.html#architecture
