### ISSUE TITLE
Add support to release aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [oracle/python-cx_Oracle#565]
Problem
---------
On aarch64, ‘pip install cx-Oracle’ builds the wheels from source code and then installs it. It requires the user to have a development environment installed on his system. Also, it takes some time to build the wheels than downloading and extracting the wheels from pypi.

Resolution
-----------
On aarch64, ‘pip install cx-Oracle’ should download the wheels from pypi

@anthony-tuininga Please let me know your interest in releasing aarch64 wheels. I can help with this. To start with can you please suggest the steps you are using for building the wheel.

**Comment by cjbj** [comment]
We don't have immediate plans for aarch64 wheels, but I imagine demand will grow.

**Comment by cjbj** [comment]
The latest version of cx_Oracle, now called [python-oracledb](https://cjones-oracle.medium.com/open-source-python-thin-driver-for-oracle-database-e82aac7ecf5a) has aarch64 wheels, see https://pypi.org/project/oracledb/#files.
