### ISSUE TITLE
Build older versions of cx_Oracle for Python 3.8

### ISSUE THREAD

**Issue by danizen** [oracle/python-cx_Oracle#566]
**1. What versions are you using?**

Oracle instantclient 12.2.0.1
Oracle 19.1
cx_Oracle 6.4.1

platform.platform: Windows 10.10.0.17763-SP0
sys.maxsize > 2**32: True
platform.python_version: 3.8.8

**2. Describe the problem**

We are still using Django 2.2, and feel we should stay on cx_Oracle 6.4.1 therefore.  However, we've just updated our desktop version to Python 3.8.8.   I haven't had to build and distribute a binary version of cx_Oracle for years, but I did need to build cx_Oracle 6.4.1 with Python 3.8.8.   Would you guys consider going back and and building 6.4.1 through 7.2.3 for us and others in a similar situation?

**3. Show the directory listing where your Oracle Client libraries are installed (e.g. the Instant Client directory).  Is it 64-bit or 32-bit?**

This is not relevant to the issue.

**4. Show what the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) is set to?**

This is not relevant to the issue.

**5. Show any Oracle environment variables set (e.g. ORACLE_HOME, ORACLE_BASE).**

ORACLE_HOME=C:\Tools\instantclient_12_2
TNS_ADMIN=P:\Oracle\TNSNAMES
NLS_LANG=AMERICAN_AMERICA.UTF8

**Comment by anthony-tuininga** [comment]
I sincerely doubt that we will do so, but I'll let @cjbj our product manager weigh in on that question! I'd suggest instead upgrading cx_Oracle to a version that officially supported Python 3.8. I just released cx_Oracle 8.2.1 which does have that support -- and it should work just as well with Django 2.2 as cx_Oracle 6.4.1 did. :-) At least I know of no known issues and none that have been reported!

**Comment by cjbj** [comment]
@danizen we're definitely trying to keep momentum forwards.  Can you talk a little about why you "feel" you should stay with cx_Oracle 6?  Also, can you try with cx_Oracle 8.2.1?

**Comment by danizen** [comment]
The developers I support have many applications, some smaller, some bigger.  Some applications are stuck back on <6, because we have had an occasional incidence of https://github.com/oracle/python-cx_Oracle/issues/306 which occurs with cx_Oracle > 6.   Most applications are using cx_Oracle 6.4.1, but they probably could upgrade.

We are just now upgrading our Desktop/Development environment to Python 3.8, and will then upgrade our server environment to Python 3.8.

It is just hard to insist that everyone upgrade, and to manage the order of upgrades.

**Comment by danizen** [comment]
@cjbj , it really is not a big deal - by building it myself, and putting it in our local PyPI server.  This solves for us the chicken and egg problem of whether the application developers move to Python 3.8 or cx_Oracle 7+ first or Django 3.2LTS first.   DevOps would love to make them update, but my job is to help them with Python/Django, rather than make it harder :)

**Comment by danizen** [comment]
@cjbj, I figured out the original reason we could not upgrade beyond 6.4.1, beyond #306, which kept some of our applications on 5.3.   The reason was that the way we manage database passwords.  Many groups have to do something like use a DATABASE_URL set by DevOps, or a proxy server that knows the password.   We have some custom code that gets the password.  So, in Django 1.11 timeframe, if one looked at:

```python
settings.DATABASES['default']['PASSWORD']
```

Well, it was not a string, but the `__str__` method caused a password lookup and that was OK.

Django 2.0/2.2 forced us to fix that.    Now, settings.DATABASES['defaults'] is a subclass of dict, and looking up ['PASSWORD'] on the dict forces the password lookup.

So, that's why 7.2.3 and 8.2.1 are now working in my tests - which means that we can encourage people to upgrade to cx_Oracle 8.2.1 while upgrading to Django 3.2

**Comment by cjbj** [comment]
@danizen thanks for the detail - I'm glad that's sorted.   If you want to revisit the ORA-3124 issue, send me email (see my profile).
