### ISSUE TITLE
Is there plan to support  apple m1?

### ISSUE THREAD

**Issue by yinheli** [oracle/python-cx_Oracle#569]
```python
import cx_Oracle
cx_Oracle.init_oracle_client(lib_dir=r"/Users/yinheli/Downloads/instantclient_19_8")
```

```
      1 import cx_Oracle
----> 2 cx_Oracle.init_oracle_client(lib_dir=r"/Users/yinheli/Downloads/instantclient_19_8")
      3 
      4 # import dataset
      5 

DatabaseError: DPI-1047: Cannot locate a 64-bit Oracle Client library: "dlopen(/Users/yinheli/Downloads/instantclient_19_8/libclntsh.dylib, 1): no suitable image found.  Did find:
	/Users/yinheli/Downloads/instantclient_19_8/libclntsh.dylib: mach-o, but wrong architecture
	/Users/yinheli/Downloads/instantclient_19_8/libclntsh.dylib.19.1: mach-o, but wrong architecture". See https://cx-oracle.readthedocs.io/en/latest/user_guide/installation.html for help
```

I have sqlplus works fine with rosetta

![image](https://user-images.githubusercontent.com/235094/121770251-e3ab7980-cb9a-11eb-8b86-5f4bcc8e2c4e.png)

```
uname -a

Darwin 192.168.124.57 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 arm64
```

**Comment by cjbj** [comment]
I've heard the Intel Instant Client works with Rosetta.  Also look at the ARM client.

M1 is on many people's wish lists!

**Comment by platzhersh** [comment]
@cjbj is there any info / documentation how to get the Intel client working on a M1 using Rosetta? (trying to get a node project with node-oracledb running on a M1 here, building the npm package from source worked fine, but now stuck on the actual client)

**Comment by cjbj** [comment]
I don't have access to M1 so I don't have any doc.  If you look at the node-oracle repo issues someone pointed out you ca use the mac Intel node binary.  Ask there for guidance.

**Comment by drio** [comment]
> If you look at the node-oracle repo issues someone pointed out

@cjbj Do you mind pointing to the specific issue that you think can help with this? I am also trying to get oracle_cx working on osx m1. I'll be happy to update the docs once I figure it out. Thank you.

**Comment by domgiles** [comment]
Instant client works fine on M1 as it runs (starts) emulated under Rosetta Stone. cx_oracle appears to fail when running under python because the default python is a universal executable and so runs natively. It should be possible to get cx_oracle running if you install an x86 version of python. This approach is being used by other libraries. This obviously comes at the cost of performance but not much.

**Comment by wingfai** [comment]
>  It should be possible to get cx_oracle running if you install an x86 version of python. 
It works, I install python 3.7.9 which it is not an universal version. Then I set the python Interpreter to this version and it works
