### ISSUE TITLE
Automatically set path to Wallet directory for cloud wallets

### ISSUE THREAD

**Issue by AetherPrior** [oracle/python-cx_Oracle#570]
- While using `cx_oracle` to connect to a cloud database, it is required that we unzip the wallet to a directory and set the `init_oracle_client`'s `config_dir` parameter to the unzipped wallet directory.  
- We also have to change the `WALLET_LOCATION` parameter in the `sqlnet.ora` file manually from `?/network/admin` to reflect the same unzipped directory.  
Since we're anyways specifying the directory to the wallet, will it be possible to let `init_oracle_client` infer the directory of the wallet? SQLDeveloper can do so since we can directly send it the zip of the wallet without having to change anything.

**Comment by cjbj** [comment]
We know this is desired, however it all controlled by layers beneath cx_Oracle. We have made the ownders aware of the requirement.

Technically you don't have to edit sqlnet.ora, as long as you put the file in the default directory.

**Comment by anthony-tuininga** [comment]
You can take a look at this [comment](https://github.com/oracle/python-cx_Oracle/issues/485#issuecomment-729843502) as well which gives you a way of using Python to overcome the limitation.
