### ISSUE TITLE
DPI-1062 in Pooled connection

### ISSUE THREAD

**Issue by sinys15** [oracle/python-cx_Oracle#571]
1. What versions are you using?

Give your database version.

Oracle 19.3

Also run Python and show the output of:
platform.platform: Linux-5.8.0-50-generic-x86_64-with-glibc2.32
sys.maxsize > 2**32: True)
platform.python_version: 3.8.6

cx_Oracle.version: 8.1.0
cx_Oracle.clientversion: (19, 6, 0, 0, 0)

2. Is it an error or a hang or a crash?

I work with AQ and CLOBs inside the application. When I add "pooled" to connection string I can get 
cx_Oracle.DatabaseError: DPI-1062: unexpected OCI return value 1041 in function dpiObject_setAttributeValue

Is it any way to understand the reason and avoid this error?

Is it solved in version 8.2?

**Comment by cjbj** [comment]
Please give us a testcase!
