### ISSUE TITLE
Hello Team,

### ISSUE THREAD

**Issue by sachinmittal2212** [oracle/python-cx_Oracle#572]
I am facing an issue implementing callproc() method from cursor object as I am inputting the parameters correctly in stored procedure written in PL/SQL as per documentation and expecting a reference cursor as output( also passed in sequence to callproc(proc_name, parameters=[output, "input"]).

I am getting an error wrong number or type of arguments in call

1. What versions are you using?

2. Describe the problem

3. Include a runnable Python script that shows the problem.

**Comment by cjbj** [comment]
When you get a chance, update your post with answers to the 3 questions: most importantly share a script that creates your procedure and and tables used.  Thanks!

Also review https://github.com/oracle/python-cx_Oracle/blob/main/samples/ref_cursor.py

**Comment by sachinmittal2212** [comment]
The implementation is as below:

cursor.execute("select procedure_name from all_procedures where object_name = 'PK_IVZ_IFT_EXTRACT' ")
rows = cursor.fetchall()
for indexRow in range(0,len(list(rows))):
    proc = 'PK_IVZ_IFT_EXTRACT.'+list(rows[indexRow])[0]
    l_cur = cursor.var(cx_Oracle.CURSOR)
    ret_cursor  = cursor.callproc(proc,parameters = [l_cur,'TOUHI'])
    print(ret_cursor[0])       
cursor.close()
db.close()

Here, stored procedure format in PL/SQL is as below:
PROCEDURE SP_IVZ_IFT_EXTRACT_POSITION(
o_ReturnRecords IN OUT RefCursor,
i_AccountCode IN VARCHAR2
) AS

  l_AccountCode varchar2(20);
...

**Comment by cjbj** [comment]
It may really help us if you make it _runnable_.  Give us the CREATE PROCEDURE statement.  Give us a Python script that we can run by only changing the username & password. Also giving the cx_Oracle, Oracle client and Oracle DB versions is always helpful.

**Comment by sachinmittal2212** [comment]
The stored procedure is up and running and I am just extracting results from SP, because of confidentiality issues, I cannot share  the SP.
[Error.docx](https://github.com/oracle/python-cx_Oracle/files/6708910/Error.docx)
 
I am attaching the full code using which I am trying to pass parameters to SP and tried to store the data in cursor ref object. The code is up and running

**Comment by sachinmittal2212** [comment]
Hello Team,It would be great if someone can help me here, really appreciate!

**Comment by anthony-tuininga** [comment]
Please put *text only* in issues! Your PL/SQL procedure you quoted above is `SP_IVZ_IFT_EXTRACT_POSITION` but the one you are calling appears to be `SP_IVZ_IFT_EXTRACT_ACCOUNTS`. Please make sure they match. Even if you can't share the real code, you can create a procedure with the same arguments that only returns something innocuous like `select user from dual`. Without that sort of thing we are left guessing as to what you are trying to accomplish and why it isn't working for you!

**Comment by cjbj** [comment]
@sachinmittal2212 If you're not interested in following up, can we close this?  I see you've opened https://stackoverflow.com/questions/68149699/issue-implementing-the-python-code-around-cx-oracle-library
PS I hope that's not your real password there.

**Comment by sachinmittal2212** [comment]
Yes, please close the ticket as it is resolved
