### ISSUE TITLE
Is there a way to compress data during data transmission between cx_Oracle and the remote database to increase the transmission speed

### ISSUE THREAD

**Issue by qianxuanyon** [oracle/python-cx_Oracle#574]
I currently have a scenario where a csv.gz file needs to be written to a remote database
Two methods of operation are used
1. Directly read from cx_Oracle and then executemany to insert into the database
2. Upload the file to a server near the database and then use cx_Oracle

The second method plus the data upload time is much faster than the first method

So is it possible for us to compress data during the transmission of cx_Oracle to increase the transmission speed?

**Comment by cjbj** [comment]
If performance is important, why not use SQL*Loader with direct path loading?  It would be nice if cx_Oracle had a similar feature, but it currently does not.

For big uploads don't forget to tune your Oracle Net SDU size.  Here are some Oracle Net references:
- [Optimizing Performance](https://docs.oracle.com/en/database/oracle/oracle-database/21/netag/optimizing-performance.html#GUID-FC114CA9-4166-4195-8EFD-DB4FE8733D3F)
- [About the Advanced Connect Data Parameters](https://docs.oracle.com/en/database/oracle/oracle-database/21/netag/enabling-advanced-features.html#GUID-FEF9B98D-65D1-4F49-8355-112351670BB7)

Oracle does have network compression.  It appears to be part of the [Advanced Compression option](https://docs.oracle.com/en/database/oracle/oracle-database/19/dblic/Licensing-Information.html#GUID-AB56CEE3-955E-4E56-8B44-6075E889C283) but you might want to check that.

All this is off topic for cx_Oracle, so I'll close this issue.  Contact Oracle Support if you need more information.  

Thanks for using cx_Oracle and letting us know that loading performance is important.

**Comment by cjbj** [comment]
PS There is an old Technical Brief: [Advanced Network Compression](https://www.oracle.com/technetwork/database/enterprise-edition/advancednetworkcompression-2141325.pdf) showing some graphs.

**Comment by qianxuanyon** [comment]
...,t.    &^     , v )   .yb ..n.n   .b,..0   .  2021年7月6日 20:28，Christopher Jones ***@***.***>写道：

**Comment by WilliamStam** [comment]
ello. faced with an executemany that takes forever over a slow connection. i face similar issues as the original post. 

>All this is off topic for cx_Oracle, so I'll close this issue. 

if you have the advanced network compression  stuff setup on the server can cx_oracle use that? since both client and server need it enabled.
