### ISSUE TITLE
Calling sql function is taking lot of time

### ISSUE THREAD

**Issue by jam21** [oracle/python-cx_Oracle#578]
Platform: Windows-10-10.0.19041-SP0

sys.maxsize > 2**32: True

Python_version: 3.9.1

Database Version 12.1.0.2.0

cx_Oracle.version: 8.1.0
cx_Oracle.clientversion: (19, 10, 0, 0, 0)

I have sql function defined in oracle database. When I call it in "**Toad For Oracle**" using following statement "`select ccl_bal(1,2,0) from dual`" it take hardly 2 seconds. But when I call it from Django 3.2 it takes lot of time, almost 5 minuts. I am using cx_oracle oracle library 8.1.0 and Here is my code `result=connection.cursor().callfunc("ccl_bal",int,[1, 2, 0])` Any help??

**Comment by cjbj** [comment]
It doesn't seem likely to be a Python issue, but try a simple cx_Oracle script (no Django) to rule out Django.

Check you really are connected to the same DB and schema, and all data is the same (check data is committed before testing).

If you were querying multiple rows of data my suspicion would be that Toad wasn't fetching all rows.  But this doesn't seem the scenario you have.

**Comment by jam21** [comment]
I tried `result=connection.cursor().callfunc("ccl_bal",int,[1, 2, 0])` simply from shell, but same issue it took lot of time.
Yes I am connected to same Data base. Whole project is using are connected to same DB. I am running other RAW queriies and calling Stored proceedures all working fine but specifically this function (its not a proceedure) is making issue

**Comment by anthony-tuininga** [comment]
Although it *shouldn't* make any difference (at least in theory!) why don't you do the same thing you did with Toad for Oracle?

```python
result = list(connection.cursor().execute("select ccl_bal(1,2,0) from dual"))
```

This uses the SQL engine (which calls into the PL/SQL engine) whereas calling the function directly as you are doing in cx_Oracle is using the PL/SQL engine directly. As I said, it *shouldn't* make any difference, but better to know for sure!

**Comment by cjbj** [comment]
> Yes I am connected to same Data base

How are you checking this?

If all else fails, try looking at the SQL execution plans in both environments.
