### ISSUE TITLE
Python3.9.1 connect Oracle10.2 using cx_Oracle8.2 can not display chinese in SELECT results (grabled chinese characters)

### ISSUE THREAD

**Issue by Dinosaurlovetoeatgrass** [oracle/python-cx_Oracle#581]
1. What versions are you using?

 Oracle10.2

Also run Python and show the output of:

grabled chinese characters
（I've already tried all kinds of methods I could found but I could not  solve this problem）

2. Describe the problem

Python3.9.1 connect Oracle10.2 using cx_Oracle8.2 can not display chinese correctly in SELECT results (grabled chinese characters) 

3. Include a runnable Python script that shows the problem.

import cx_Oracle

db = cx_Oracle.connect(‘ygx’, 'password', '111.111.111.101:1521/orcl')
cursor = db.cursor()
SQL = """SELECT * FROM DEPT_DICT"""
cursor.execute(SQL)
result_list = cursor.fetchall()
print (result_list)
![image](https://user-images.githubusercontent.com/45684044/132125520-2f309b10-fb7c-4351-a4aa-6a71504a9c3d.png)

**Comment by Dinosaurlovetoeatgrass** [comment]
I have tried some solutions I found in google, such as
<1> con = cx.connect('xxx/xxxxxx@xxx.xxx.xxx.xxx:1521/xxxx',encoding="UTF-8",nencoding="UTF-8");
<2>os.environ['NLS_LANG'] = 'AMERICAN_AMERICA.US7ASCII';
<3>setting system variables and so on. But I still struggle with this problem deeply.

**Comment by Dinosaurlovetoeatgrass** [comment]
I will be greatful that the someone could help me solve this problem, many many thanks.

**Comment by cjbj** [comment]
If you use Python to insert data and then immediately select it back, is it OK?

**Comment by Dinosaurlovetoeatgrass** [comment]
> If you use Python to insert data and then immediately select it back, is it OK?
> 
> Also, what is the DB character set? See https://cx-oracle.readthedocs.io/en/latest/user_guide/globalization.html#finding-the-database-and-client-character-set

**Comment by Dinosaurlovetoeatgrass** [comment]
> > If you use Python to insert data and then immediately select it back, is it OK?
> > Also, what is the DB character set? See https://cx-oracle.readthedocs.io/en/latest/user_guide/globalization.html#finding-the-database-and-client-character-set

Dear cjbj, 

Thank you for responding to my question so quickly today, thanks.

If I use Python to insert data according to the following Python program, I found all my chinese characters is "????"  in my SELECT result but English character is updated correctly. And My  database character set is US7ASCII and the database ‘national character set’ used for NCHAR and related types is AL16UTF16.


###########################################################################################
"""
#This is my Python script to insert data.
import cx_Oracle

db = cx_Oracle.connect(‘ygx’, 'password', '111.111.111.101:1521/orcl')
cursor = db.cursor()
SQL = """INSERT INTO MIO_TABLE_LOG VALUES('TEST2', '测试测试')"""
cursor.execute(SQL)

db.commit()
cursor.close()
db.close()
"""

###########################################################################################
"""
#This is my Python script to select data and my SELECT result.
import cx_Oracle

db = cx_Oracle.connect(‘ygx’, 'password', '111.111.111.101:1521/orcl')
cursor = db.cursor()
SQL = """SELECT * FROM MIO_TABLE_LOG"""
cursor.execute(SQL)
result_list = cursor.fetchall()
print (result_list)
cursor.close()
"""
![image](https://user-images.githubusercontent.com/45684044/132377695-8486163e-23e9-44cc-a570-6377a195772f.png)

**Comment by Dinosaurlovetoeatgrass** [comment]
Does anyone have the same problem as me ?

**Comment by cjbj** [comment]
This is what I get:

<img width="274" alt="Screen Shot 2021-09-10 at 5 19 57 pm" src="https://user-images.githubusercontent.com/200778/132815624-0cd830a0-2c4b-492f-a438-c95842677ace.png">

Is it right?

This is the code I ran:
```
import cx_Oracle

import sys, os
if sys.platform.startswith("darwin"):
    cx_Oracle.init_oracle_client(lib_dir=os.environ.get("HOME")+"/Downloads/instantclient_19_8")


db = cx_Oracle.connect('cj', 'cj', 'mdt/orclpdb1')
cursor = db.cursor()

#cursor.execute("drop table MIO_TABLE_LOG")
cursor.execute("create table MIO_TABLE_LOG(c1 varchar2(30), c2 varchar2(30))")

SQL = """INSERT INTO MIO_TABLE_LOG VALUES('TEST2', '测试测试')"""
cursor.execute(SQL)
db.commit()

cursor = db.cursor()
SQL = """SELECT * FROM MIO_TABLE_LOG"""
cursor.execute(SQL)
result_list = cursor.fetchall()
print (result_list)
```

This is on macOS using cx_Oracle 8.2 with Instant Client 19.8 connecting to Oracle DB 21.3.  The DB character set is AL32UTF8.  Python cx_Oracle uses the client character set "UTF-8" by default.

**Comment by Dinosaurlovetoeatgrass** [comment]
This is what I get:
![image](https://user-images.githubusercontent.com/45684044/133779813-4bf63468-5333-4b63-9608-cdbccbe6286b.png)

I don't know why same code get different result.
This is the code I ran:

import cx_Oracle

import sys, os
if sys.platform.startswith("win32"):
    cx_Oracle.init_oracle_client(lib_dir="C:\\instantclient_19_12")


db = cx_Oracle.connect('ygx', 'ygx', '111.111.111.111:1521/orcl')
cursor = db.cursor()

cursor.execute("create table young_test(c1 varchar2(30), c2 varchar2(30))")

SQL = """INSERT INTO young_test VALUES('TEST6', '测试测试')"""
cursor.execute(SQL)
db.commit()

cursor = db.cursor()
SQL = """SELECT * FROM young_test """
cursor.execute(SQL)
result_list = cursor.fetchall()
print (result_list)

**Comment by Dinosaurlovetoeatgrass** [comment]
Cx_Oracle module has been successfully tested against Oracle Client 21c, 19c, 18c, 12c, and 11.2, and Python 3.6, 3.7, 3.8 and 3.9, but my Oracle version is 10.2. Is it because my Oracle version is 10.2 that all my chinese can not display correctly?

**Comment by cjbj** [comment]
Is that what you tested, or are you quoting our doc?   Either way, you should try and upgrade.

The data issue is probably because you are trying to store multibyte characters in VARCHAR2 columns, which will be US7ASCII.  You could try storing the data in NVARCHAR2 columns.

**Comment by Dinosaurlovetoeatgrass** [comment]
That's not what I tested and I quoted your doc when I read cx_Oracle doc, because I have been struggled with this problem for several days.

I tried storing the data in NVARCHAR2 columns but failed. My chinese characters still can not display normally.

**Comment by Dinosaurlovetoeatgrass** [comment]
That's not what I tested and I quoted your doc when I read cx_Oracle doc, because I have been struggled with this problem for several days.

I tried storing the data in NVARCHAR2 columns but failed. My chinese characters still can not display normally.

**Comment by cjbj** [comment]
(I deleted the duplicate)

We have many people storing Chinese characters in Oracle databases.   As you saw, even I managed to store them.

**Comment by Dinosaurlovetoeatgrass** [comment]
Thank you for you replay so quickly. Now I am online and try to use Python-3.8.10 and cx_Oracle-7.3.0-cp38-cp38-win_amd64. Is this a good idea?

**Comment by cjbj** [comment]
Install the latest version of cx_Oracle possible.  Currently that is 8.2.1.  See https://cx-oracle.readthedocs.io/en/latest/user_guide/installation.html#installing-cx-oracle-on-windows

**Comment by Dinosaurlovetoeatgrass** [comment]
I can not use pip command to install cx_Oracle from PyPI because  my computer is offline. Is there guideline for offline installation? Maybe my previous offline installation steps went wrong？

**Comment by cjbj** [comment]
Download the wheel and install from it: `pip install whatever.whl`.  Depending what other constraints you have, see https://stackoverflow.com/a/68668629/4799035 about manual extraction - but this may not be needed

**Comment by Dinosaurlovetoeatgrass** [comment]
Yes, This is what I had already done for my computer in offiline :
1. pip install cx_Oracle-8.2.0-cp39-win_amd64.whl; 
2. copy  instantclient-basic-windows.x64-19.12.0.0.0dbru.zip to my offline computer and unzip to dir then set lib_dir="C:\\instantclient_19_12" in cx_Oracle.init_oracle_client).
I get so confused why I always get this kind of "????" chinese characters in my SELECT results.

**Comment by Dinosaurlovetoeatgrass** [comment]
Oh, my God, this problem has bothered me for many days. 
How I wish you were in my office now and help me troubleshoot this problem.

**Comment by cjbj** [comment]
Is the problem Windows?  Do you need some locale set? 

Did you try creating a new DB with a better default character set, e.g. AL32UTF8?

Did you try upgrading Oracle DB, or if you can't upgrade that DB, by installing a newer version, such as with [Oracle XE](https://www.oracle.com/au/database/technologies/xe-downloads.html) and testing with that?

**Comment by Dinosaurlovetoeatgrass** [comment]
Yes, my computer is windows(64-bit operating system).

Maybe I will try creating a new DB for other data processing but now I am using DB that everyone is using in our company. All most of my colleagues like PowerBuilder9 to connect Oracle. I prefer to use cx_Oracle however.

I may have no permission to upgrade Oracle DB because company need to maintain database stability and I will install a newer version(Oracle XE) to test with my problem. 

Thanks！

**Comment by Dinosaurlovetoeatgrass** [comment]
Yes, my computer is windows(64-bit operating system).

Maybe I will try creating a new DB for other data processing but now I am using DB that everyone is using in our company. All most of my colleagues like PowerBuilder9 to connect Oracle. I prefer to use cx_Oracle however.

I may have no permission to upgrade Oracle DB because company need to maintain database stability and I will install a newer version(Oracle XE) to test with my problem later. 

Thanks！

**Comment by cjbj** [comment]
If your colleagues are inserting multibyte data into US7ASCII datatype columns, then you probably technically have data corruption and nothing can be guarenteed.

I suggest you confirm (and share) the exact set up: DB and Oracle client versions; run `SELECT value AS db_charset FROM nls_database_parameters WHERE parameter = 'NLS_CHARACTERSET'` and `SELECT value AS db_ncharset FROM nls_database_parameters WHERE parameter = 'NLS_NCHAR_CHARACTERSET'` and give us the DB character sets.

**Comment by Dinosaurlovetoeatgrass** [comment]
Many many thanks Mr. Jones. In order to show both parameters on one page I just ran SELECT * FROM  nls_database_parameters  and marked the two parameters as following pic.

![image](https://user-images.githubusercontent.com/45684044/134338598-737dea9f-1bdb-4163-805c-c000887b9b38.png)

**Comment by Dinosaurlovetoeatgrass** [comment]
My Python3.9 that is running on windows64 is not running on the same machine as the Oracle database (Oracle is remote on SUSE Linux).

 So, I still need to install Oracle Client libraries separately on SUSE Linux, or I just need to make sure that the Oracle Client libraries are installed on my windows system and set lib_dir="C:\\instantclient_19_12" in cx_Oracle.init_oracle_client()?
