### ISSUE TITLE
Possible memory leak?

### ISSUE THREAD

**Issue by alex-lt-kong** [oracle/python-cx_Oracle#583]
1. What versions are you using?

- Oracle database Version 19.4.0.0.0
- Oracle instantclient version: 21.3.0.0.0
- OS version: RHEL 7.9 x64

```
>>> print("platform.platform:", platform.platform())
platform.platform: Linux-3.10.0-1160.36.2.el7.x86_64-x86_64-with-glibc2.17
>>> print("sys.maxsize > 2**32:", sys.maxsize > 2**32)
sys.maxsize > 2**32: True
>>> print("platform.python_version:", platform.python_version())
platform.python_version: 3.9.5
>>> print("cx_Oracle.version:", cx_Oracle.version)
cx_Oracle.version: 8.2.1
>>> print("cx_Oracle.clientversion:", cx_Oracle.clientversion())
cx_Oracle.clientversion: (21, 3, 0, 0, 0)
```

2. Describe the problem

First please take a look at the code snippet in (3).

The issue is, the code can run, just it uses a LOT of memory. My guesstimate of the final resultant `rows` object should be no more than 2 GB in size but the script uses up all my 30 GB memory and gets terminated by OS (i.e., I don't know exactly how much memory the script would like to allocate since it is not given the chance). Before the script gets killed, it asks for about 200 MBytes of memory each second so my 30 GB memory does not last for too long...At the moment it is killed, usually it fetches no more than 50% of the rows needed.

Here comes the really strange thing--I can avoid the above issue by commenting out `rows.append(row)`. That is, if I don't save the fetched rows and just keeps reading and discarding, the script becomes totally fine...

One may say: would it be possible that there is a mismatch between rows' actual size and `cx_Oracle`'s idea of their size? This is unlikely, I tried printing `cursor.description` and the result is the following: `[('Date', <class 'cx_Oracle.DATETIME'>, 23, None, None, None, 0), ('ID', <class 'cx_Oracle.STRING'>, 9, 9, None, None, 0), ('KeyName', <class 'cx_Oracle.STRING'>, 53, 53, None, None, 0), ('ValueName', <class 'cx_Oracle.NUMBER'>, 127, None, 126, -127, 0)]`. Looks normal.

3. Include a runnable Python script that shows the problem.

```

dsn = cx_Oracle.makedsn(host=[host], port=[port], sid=[sid])
con = cx_Oracle.connect(user=[username], password=[password], dsn=dsn)
rows = []
with con.cursor() as cursor:
    cursor.arraysize = 100_000 # Only effective when using cx_Oracle
    sql = """
            SELECT "Date", "ID", "KeyName", "ValueName"
            FROM "A_Table"
            WHERE ("A_Table"."Date" >= '07-SEP-20' AND 
                   "A_Table"."Date" <= '07-SEP-21')
    """
    # So I just to get everything from the last year
    cursor.execute(sql)
    while True:
        fetched_rows = cur.fetchmany(num_rows)
        if not fetched_rows:
            break
         rows.extend(fetched_rows)
```

4. Extra Attempts

What if I do this instead:
```
while True:
    fetched_rows = cur.fetchmany(num_rows)
    if not fetched_rows:
        break
    dcfr = copy.deepcopy(fetch_rows) 
    fetch_rows = None # we keep a deepcopy of fetched_rows, hoping it can release the object reference and space.
    rows.extend(dcfr)
    gc.collect() # Manual garbage collection to avoid any delay
        
```
No, it won't solve the issue. I also tried using SQL*PLUS: https://dba.stackexchange.com/questions/299426/the-expected-read-speed-of-sqlplus .It does NOT suffer from the same issue and it can reach a local read speed at 50MBytes/s. 

Also, I am suspecting this is not a `cx_Oracle` bug since `pyodbc` suffers from the same issue. Can check out my question on StackExchange (mostly the same as this one): https://dba.stackexchange.com/questions/299444/possible-memory-leak-of-cx-oracle-pyodbc-oracle-instant-client

I canNOT rule out the possibility that it is some machine-specific settings that are wrong , feel free to ask me providing more info, such as content of `sqlnet.ora`, etc.

Any idea?...

**Comment by cjbj** [comment]
I presume `100_000` is a typo? There are other errors in the code.  Can you share something runnable so we are all looking at the same issue?  

With big datasets do you need to keep all rows in memory?  Your code is going to be duplicating data when it appends to rows.

How many rows does (should) the query return?

What is the behavior if you use a smaller arraysize value?

What is the behavior if you use the big arraysize value, but pass a smaller size to fetchmany()?

I'll let @anthony-tuininga comment more (when his week starts)

**Comment by alex-lt-kong** [comment]
(1) I presume 100_000 is a typo?  -> 100_000 is a new Python syntax which just means 100000.
(2) There are other errors in the code.  -> The code can run...perhaps you are thinking it will never quit due to --actually this does not matter, since it get killed every time. It looks like this because I tried many many combinations. But anyway, I revised it so it can quit if it is not get killed. 
(3) With big datasets do you need to keep all rows in memory -> Yes, at least during this test it is our intention to keep all rows in memory.
(4) Your code is going to be duplicating data when it appends to rows. -> Not sure what you mean, but I just revised my code, does the revision fix your concern?
(5) How many rows does (should) the query return? -> around 120,000,000 rows.
(6) What is the behavior if you use a smaller arraysize value? -> It becomes slower, but the issue is the same. Just the script gets terminated later. (In my original code, I tried a wide range of possible arraysize = [10, 100, 1_000, 10_000, 100_000, 1_000_000, 5_000_000, 10_000_000], some real large value may crash the code, but 1_000_000 should be fine)
(7) What is the behavior if you use the big arraysize value, but pass a smaller size to fetchmany()? -> The same.

**Comment by alex-lt-kong** [comment]
Before @anthony-tuininga starts his week, I get a few more observations:

(1) This issue seems irrelevant to `sqlnet.ora` or other settings I add--I tried my Python script on a new Linux machine and the behavior is the same;

(2) The new machine is much more powerful and the script can finish successfully:
    - fetch 5GB data from DB, the script needs 50GB memory;
    - fetch 10GB data from DB, the script needs 95GB memory;
    - fetch 15GB data from DB, the script needs 140GB memory;

**Comment by anthony-tuininga** [comment]
@alex-lt-kong, cx_Oracle uses an internal buffer (corresponding to `cursor.arraysize`) which will be retained so long as the cursor is open (and hasn't executed a different statement). If you truly want all rows in memory you can just use `list(cursor)` or `cursor.fetchall()`. If that is the case, however, you will need to have enough memory to support all of that data. Note that Python has an object structure which is used for all objects -- so that is going to explain why you need more memory than the raw data stored in the database! After fetching all rows you can close the cursor and connection and see the difference in memory used by the internal buffer. The biggest issues with the internal buffer are seen when you have a column of type varchar2(32767) but you only store a handful of bytes. The buffer is allocated based on the maximum possible length, not the actual length!

**Comment by alex-lt-kong** [comment]
Hey @anthony-tuininga ,good to see you here!
Regarding this `cx_Oracle uses an internal buffer (corresponding to cursor.arraysize) which will be retained so long as the cursor is open (and hasn't executed a different statement)`, my understanding is that, if I do `fetchmany()` a few times until I fetch everything, the memory I need should be more or less similar to the memory I need if I do `fetchall()` once, is this correct?

`Note that Python has an object structure which is used for all objects -- so that is going to explain why you need more memory than the raw data stored in the database! ` -> I understand that there is an overhead cost if I use Python, but my thought is, will a 10x memory usage be too much? Or you still consider it to be normal?

`The biggest issues with the internal buffer are seen when you have a column of type varchar2(32767) but you only store a handful of bytes`-> This was also my concern as well, but it turns out that `cx_Oracle` correctly understands the length of my data. This is my `cursor.description`: [('Date', <class 'cx_Oracle.DATETIME'>, 23, None, None, None, 0), ('ID', <class 'cx_Oracle.STRING'>, 9, 9, None, None, 0), ('KeyName', <class 'cx_Oracle.STRING'>, 53, 53, None, None, 0), ('ValueName', <class 'cx_Oracle.NUMBER'>, 127, None, 126, -127, 0)]. They look okay, right?

Or do you mean that, the buffer of `cx_Oracle` always asks for MAXIMUM length, i.e., varchar2(32767), even if it know that I am only using varchar2(32)??

**Comment by anthony-tuininga** [comment]
The use of `cursor.fetchmany()` is intended for batch processing. This is intended to reduce the amount of memory required. Since you seem to need all of the rows there is no benefit to using that approach. There should be no meaningful difference in memory use -- but it will run slower!

cx_Oracle does read the metadata and will only create buffers large enough to hold the data. The metadata you displayed looks fine to me.

As for your question regarding Python memory usage -- I don't know how you are calculating the 15 GB of data from the database vs the 140 GB of memory. It seems a little off, though. As mentioned, you can simply close the cursor (which will free the internal buffers) and close the connection. At that point memory usage will be all your application and will have nothing to do with cx_Oracle itself.

**Comment by alex-lt-kong** [comment]
> The use of cursor.fetchmany() is intended for batch processing. This is intended to reduce the amount of memory required. Since you seem to need all of the rows there is no benefit to using that approach. There should be no meaningful difference in memory use -- but it will run slower!
No problem. The current use of `fetchmany()` a few times is just one way I tried...

> cx_Oracle does read the metadata and will only create buffers large enough to hold the data. The metadata you displayed looks fine to me.
Emmm...but this makes the issue more complicated, since the problem is not here.

> As for your question regarding Python memory usage -- I don't know how you are calculating the 15 GB of data from the database vs the 140 GB of memory. 
Well I converted `rows` to a dataframe is `pickle()`ed the df. Then I just check the size of the uncompressed pickle file. I thought about the accuracy of pickle file--since it is not compressed, I think it can only be bigger than real data size so this measurement should be okay.

> As mentioned, you can simply close the cursor (which will free the internal buffers) and close the connection. At that point memory usage will be all your application and will have nothing to do with cx_Oracle itself.
Let me give it a try and post the result back here later.

**Comment by alex-lt-kong** [comment]
Just get the result, I added an `input()` at the end of the script, my script still uses 40GB memory...but this is just a very minimal script so this is exactly what I was asking in the very beginning--will this be a memory leak...

**Comment by anthony-tuininga** [comment]
Share the full script. It will only be considered a memory leak if after destroying all of the objects that you created to fetch the data you have memory memory used than when you started. Calculate memory just after connecting to the database, then again after fetching all rows, and finally after destroying the rows that you fetched. Include this calculation in the script that you share. I have fetched large numbers of rows without noting any memory leaks. We also perform stress tests that check for memory leaks regularly. So we definitely need something that demonstrates the problem you are experiencing!

**Comment by alex-lt-kong** [comment]
Please take a look:

```
dsn = cx_Oracle.makedsn(host=, port=, sid=)
con = cx_Oracle.connect(user=, password=, dsn= dsn )
 
pfr = [100_000]
ars = [100_000]
 
for i in range(len(pfr)):
    for j in range(len(ars)):
 
        with con_hk_axioma.cursor() as cursor:
            start = time()
            cursor.arraysize = ars[j]
            print(f"{cursor.arraysize=:,}")
            rows = []
            df = pd.DataFrame(columns = ["Date", "ID", "KeyName", "ValName"])
            sql = """
            SELECT "Date", "ID", "KeyName", "ValName"
            FROM "TABLE"
            WHERE ("TABLE"."Date" >= '11-SEP-20' AND "TABLE"."Date" <= '11-SEP-21')
            """
            cursor.execute(sql)
            print(f"{cursor.description=}")
            while True:
                fetch_rows = cursor.fetchmany()
                if not fetch_rows:
                    break
                rows.extend(fetch_rows)
                print(f'{len(rows)=:,}, size(rows)={sys.getsizeof(rows)/1024/1024:,.0f} MB, {len(rows) / (time() - start):,.0f}/sec')
        print(f"fetch time={time() - start:,.0f} sec;", end=" ")
        print('Converting rows to dataframe')
        df = pd.DataFrame(rows, columns=["Date", "ID", "KeyName", "ValName"])
        print('Serializing dataframe to pickle file')
        df.to_pickle('/tmp/data.pickle')
        print(f"rows={df.shape[0]:,}; overall time={time() - start:,.0f} sec; speed={df.shape[0] / (time() - start):,.0f}/sec")
input()
```

**Comment by alex-lt-kong** [comment]
In case you want to recreate some dummy data to test. Here are some extra info:
(1) We get 5 years of daily data, each day has around 450,000 rows;
(2) We set `Date`, `ID` and `KeyName` for some reason...also the current table uses the reserved keyword `Date` as a column name...
(3) For other characteristics of the table, perhaps the description is good enough: [('Date', <class 'cx_Oracle.DATETIME'>, 23, None, None, None, 0), ('ID', <class 'cx_Oracle.STRING'>, 9, 9, None, None, 0), ('KeyName', <class 'cx_Oracle.STRING'>, 53, 53, None, None, 0), ('ValueName', <class 'cx_Oracle.NUMBER'>, 127, None, 126, -127, 0)]

**Comment by anthony-tuininga** [comment]
I see you are using the `pandas` module. Try just using plain cx_Oracle. I don't know how much additional memory is required for data frames and the pickling process.

**Comment by alex-lt-kong** [comment]
I commented out the last four lines and run the code again, the result is the same. The new code is:
```
dsn = cx_Oracle.makedsn(host=, port=, sid=)
con = cx_Oracle.connect(user=, password=, dsn= dsn )
 
pfr = [100_000]
ars = [100_000]
 
for i in range(len(pfr)):
    for j in range(len(ars)):
 
        with con.cursor() as cursor:
            start = time()
            cursor.arraysize = ars[j]
            print(f"{cursor.arraysize=:,}")
            rows = []
            df = pd.DataFrame(columns = ["Date", "ID", "KeyName", "ValName"])
            sql = """
            SELECT "Date", "ID", "KeyName", "ValName"
            FROM "TABLE"
            WHERE ("TABLE"."Date" >= '11-SEP-20' AND "TABLE"."Date" <= '11-SEP-21')
            """
            cursor.execute(sql)
            print(f"{cursor.description=}")
            while True:
                fetch_rows = cursor.fetchmany()
                if not fetch_rows:
                    break
                rows.extend(fetch_rows)
                print(f'{len(rows)=:,}, size(rows)={sys.getsizeof(rows)/1024/1024:,.0f} MB, {len(rows) / (time() - start):,.0f}/sec')
        print(f"fetch time={time() - start:,.0f} sec;", end=" ")
        print('Converting rows to dataframe')
        # df = pd.DataFrame(rows, columns=["Date", "ID", "KeyName", "ValName"])
        # print('Serializing dataframe to pickle file')
        # df.to_pickle('/tmp/data.pickle')
        # print(f"rows={df.shape[0]:,}; overall time={time() - start:,.0f} sec; speed={df.shape[0] / (time() - start):,.0f}/sec")
input()
```
How about this.

**Comment by anthony-tuininga** [comment]
I still see use of pandas data frames. I also don't see where you are calculating memory use?

**Comment by anthony-tuininga** [comment]
You can use `psutil` to do so, as follows:

```python
import psutil
process = psutil.Process()
print(process.memory_info().rss)  # in bytes 
```

**Comment by ak-clsa** [comment]
This is another account I use. The revised code is:
```python
import cx_Oracle
import pandas as pd
from time import time
import psutil

import copy
import gc
import pickle
import sys
import pyodbc
import threading

dsn = cx_Oracle.makedsn(host='', port='', sid='')
con = cx_Oracle.connect(user='', password='', dsn=dsn)

prefetch, arraysize = 500_000, 500_000
process = psutil.Process()
with con.cursor() as cursor:
    start = time()
    cursor.arraysize = arraysize
    print(f"{cursor.arraysize=:,}")
    rows = []
    sql = """
    SELECT "Date", "ID", "KeyName", "ValName"
    FROM "TABLE"
    WHERE ("TABLE"."Date" >= '05-SEP-20' AND 
           "TABLE"."Date" <= '11-SEP-21')
    """
    cursor.execute(sql)
    print(f"{cursor.description=}")
    while True:
        fetch_rows = cursor.fetchmany()
        if not fetch_rows:
            break
        rows.extend(fetch_rows)
        print(f'{len(rows)=:,}, getsizeof(rows)={sys.getsizeof(rows)/1024/1024:,.0f} MB, '
                f'memory_info()={(process.memory_info().rss/1024/1024):,.0f}MB, {len(rows) / (time() - start):,.0f}/sec')
print(f"fetch time={time() - start:,.0f} sec;", end=" ")
con.close()
print(f'{len(rows)=:,}, getsizeof(rows)={sys.getsizeof(rows)/1024/1024:,.0f} MB, '
      f'memory_info()={(process.memory_info().rss/1024/1024):,.0f}MB, {len(rows) / (time() - start):,.0f}/sec')
input("End of script, press Enter to exit...")
print(f'{len(rows)=:,}, getsizeof(rows)={sys.getsizeof(rows)/1024/1024:,.0f} MB, '
      f'memory_info()={(process.memory_info().rss/1024/1024):,.0f}MB, {len(rows) / (time() - start):,.0f}/sec')

```
A few selected stdout lines:
```bash
len(rows)=40,000,000, getsizeof(rows)=313 MB, memory_info()=12,045MB, 748,914/sec
len(rows)=80,000,000, getsizeof(rows)=661 MB, memory_info()=23,691MB, 475,434/sec
len(rows)=123,636,590, getsizeof(rows)=948 MB, memory_info()=36,400MB, 527,885/sec
fetch time=234 sec; len(rows)=123,636,590, getsizeof(rows)=948 MB, memory_info()=36,073MB, 527,863/sec
End of script, press Enter to exit...
len(rows)=123,636,590, getsizeof(rows)=948 MB, memory_info()=36,073MB, 397,415/sec
```
Selected part from `top`:
```bash
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 4953 [username]  20   0   37.6g  35.2g   0.0g S   0.0  9.3   2:01.03 python3 0916_test_psutil.py
```
(after pressing Enter the script quits and OS reclaims all the space of course...)

**Comment by alex-lt-kong** [comment]
[keep-alive message]

**Comment by ak-clsa** [comment]
[keep-alive message]

**Comment by ak-clsa** [comment]
[4th keep-alive message]

**Comment by ak-clsa** [comment]
[5th keep-alive message]

**Comment by anthony-tuininga** [comment]
If you still want us to look into this, please provide a script that creates the table and populates data that results in the issue you are seeing. I haven't found any memory leaks and we do have an internal stress testing team that checks for these things regularly, too!

**Comment by alex-lt-kong** [comment]
We migrated to another tech stack to avoid this issue given that it has not been solved for a while.

**Comment by cjbj** [comment]
Sorry to hear that.
