### ISSUE TITLE
ORA-29275 is occurring when referencing a record using cx_oracle.

### ISSUE THREAD

**Issue by dmoracle** [oracle/python-cx_Oracle#585]
1. What versions are you using?
-DataBase:  Oracle 12.1.0.2
-cx_oracle version:  cx_Oracle 8.1.0

2. Describe the problem
ORA-29275 is occurring when referencing a record using cx_oracle.
(If you run again, ORA-29275 may not occur and the process may end normally. Also, we have confirmed that there is no data corruption in the table.)
I would like to know how to prevent the occurrence of this ORA-29275.
If the cause is cx_oracle or DB settings, please tell me how to change it.
Information on our environment is below.
-DB character code:　SJIS
-cx_oracle Character code:　SJIS
-Search method:　Search by SELECT * XXX and fetch
-Table column type to search:　varchar, number, Date
　(The maximum length of varchar is 512 bytes, and the maximum length of nuber is 8 bytes)

3. Include a runnable Python script that shows the problem.
-Source code for cx_oracle that seems to be returning an error：
    while 1:
    serial + = 1
    result_dtl = cursor.fetchmany (num_rows)
    logger.debug (f "[{prefix}] fetch {serial} finished")
    if len (result_dtl) == 0:
        break

**Comment by cjbj** [comment]
We'll need a full set of scripts including SQL to create the records, and a complete Python script showing how you connect.

Also give us the Oracle Client (e.g. Instant Client) version.

**Comment by dmoracle** [comment]
>We'll need a full set of scripts including SQL to create the records, and a complete Python script showing how you connect.

Since all the Python code is large and requires permission to post, it can not be described, so I will describe the necessary part

・SQL to create
※The comment will be in the original text.
        #Read the section list from the target file
        # At that time, rename the target file for subsequent processing
        # Stop processing if the target file does not exist
        target_file = f"{prefix}_target.lst"
        target_path = os.path.join(LIST_DIR, target_file)
        if os.path.isfile(target_path):
            logger.info(f"[{table}({line + 1}/{len(data)})]Since there is a target file, the extraction process will be restarted.")
            with open(target_path, mode = 'r+') as f:
                target_list = [line.strip() for line in f.readlines()]
        else:
            logger.info(f"[{table}({line + 1}/{len(data)})]Since there is no target file, skip it.")
            continue

        if target_list is None:
            logger.error(f"[{table}({line + 1}/{len(data)})]Since an error occurred in the section acquisition process, the process is skipped.")
            result_list.append(1)
            continue
        elif len(target_list) == 0:
            logger.warning(f"[{table}({line + 1}/{len(data)})]Since the cross section cannot be found, the process is skipped.")
            result_list.append(1)
            continue

        #Error target file definition
        error_target_file = f"{prefix}_error_target.lst"
        error_target_path = os.path.join(LIST_DIR, error_target_file)
        if os.path.isfile(error_target_path):
            os.rename(target_path, f"{error_target_path}_bak")

        # Zero target file definition
        zero_target_file = f"{prefix}_zero_target.lst"
        zero_target_path = os.path.join(LIST_DIR, zero_target_file)
        if os.path.isfile(zero_target_path):
            os.rename(target_path, f"{zero_target_path}_bak")

        results = []
        for target_num, target in enumerate(target_list):
            # If the interruption flag file exists, fill in the section item in the target file and skip the process.
            if os.path.isfile(BREAK_FLG):
                if os.path.isfile(target_path):
                    os.rename(target_path, f"{target_path}_bak")
                with open(target_path, mode = 'at', encoding='utf-8') as f:
                    f.write(f"{target}\n")
                logger.warning(f"[{table}({line + 1}/{len(data)})][{target}({target_num + 1}/{len(target_list)})]Since the interruption flag file exists, add the section item to the target file.")
                results.append(2)
                continue

            # When the section item is NULL
            if target is None or target == 'None':
                query = f"select /*+ NOCACHE(T) */ T.* from {table} T where {column} is NULL"
                if nvl is None:
                    if date_format == 'YYYYMMDD':
                        target_time = datetime.strptime(min(target_list), conf['DateFormat'][date_format]) - timedelta(days = 1)
                    else:
                        target_time = datetime.strptime(min(target_list), conf['DateFormat'][date_format]) - relativedelta(months = 1)
                else:
                    target_time = datetime.strptime(nvl, conf['DateFormat'][date_format])
            # When the section item is "        "
            elif target == 'space':
                query = f"select /*+ NOCACHE(T) */ T.* from {table} T where {column} = '        '"
                if nvl is None:
                    if date_format == 'YYYYMMDD':
                        target_time = datetime.strptime(min(target_list), conf['DateFormat'][date_format]) - timedelta(days = 1)
                    else:
                        target_time = datetime.strptime(min(target_list), conf['DateFormat'][date_format]) - relativedelta(months=1)
                else:
                    target_time = datetime.strptime(nvl, conf['DateFormat'][date_format])
            else:
                target_time = datetime.strptime(target, conf['DateFormat'][date_format])
                from_target = f"{target_time.strftime('%Y%m')}01"
                to_target = f"{(target_time + relativedelta(months=1)).strftime('%Y%m')}01"
                query = f"select /*+ NOCACHE(T) */ T.* from {table} T where {column} >= '{from_target}' and  {column} < '{to_target}'"

            #Create output directory
            if date_format == 'YYYYMMDD':
                time_prefix = target_time.strftime('%Y%m%d')
            else:
                time_prefix = f"{target_time.strftime('%Y%m')}01"
            out_dir = os.path.join(conf['Output']['OUT_DIR'], prefix, target_time.strftime('%Y%m'), time_prefix)

            #Delete the output directory if it already exists
            if os.path.isdir(out_dir):
                logger.info(f"[{table}({line + 1}/{len(data)})][{target}({target_num + 1}/{len(target_list)})]The output destination directory exists, so delete it.({out_dir})")
                shutil.rmtree(out_dir)
            os.makedirs(out_dir, exist_ok = True)

            parallel = int(conf['Multiprocess']['PARALLEL_NUM'])
            process_list = []
            pipe_list = []
            return_lists = []
            for parallel_rem in range(parallel):
                recv_end, send_end = multiprocessing.Pipe(False)
                prefix_parallel = f"{prefix}_{parallel_rem}"
                query_parallel = f"{query} and mod(ora_hash(rowid),{parallel}) = {parallel_rem}"
                process = multiprocessing.Process(target = _common_fetch.exadata_to_csv_multi, args = (conf, query_parallel, out_dir, prefix_parallel, logger, send_end))
                process_list.append(process)
                pipe_list.append(recv_end)
                process.start()


・connect
    try:
        with cx_Oracle.connect(conf['Exadata']['USER'], conf['Exadata']['PASSWORD'], f"{conf['Exadata']['HOST']}:{conf['Exadata']['PORT']}/{conf['Exadata']['DB']}") as connection :
            connection.outputtypehandler = output_type_handler
            cursor = connection.cursor()



>Also give us the Oracle Client (e.g. Instant Client) version.

Oracle Client version 12.1.0.2

**Comment by cjbj** [comment]
By "record" did you mean a row, and not a [PL/SQL record](https://cx-oracle.readthedocs.io/en/latest/user_guide/bind.htm#binding-pl-sql-records)?  What did you mean by 'referencing'?

The code you shared doesn't help explain what problem you are seeing.  Or what code is failing.

Concatenating data (the dates) into SQL statements instead of using bind variables is a concern.

Overall, you'll need to construct an example that runs, and that you can share with us.

**Comment by dmoracle** [comment]
I checked with the person in charge.
The part that was previously linked becomes the problem part.
Details are given below.

-Every day, the following SQL is executed in cx_Oracle for about 300 tables by changing the table name and date conditions, and the data is output to the CSV file.
The table and timing are undefined, but the ORA-29275 error occurs and CSV output fails about two or three times a week.
By re-executing the SQL that caused the error, the data can be output to the CSV file without any error.
SELECT / * + NOCACH (T) / T. * from <TABLE name> WHERE "date" ='YYYYMMDD' AND mod (ora_hash (rowid), 8) = 0 {~ 7};

**Comment by cjbj** [comment]
Sorry to hear you are still facing issues. 

Is the table being dropped and recreated during the life of the app's connection?  If so, try turning off the statement cache in cx_Oracle by setting the size to 0.

**Comment by dmoracle** [comment]
Thank you for the information.
confirm.

**Comment by cjbj** [comment]
@dmoracle do you need any more help on this?
