### ISSUE TITLE
Dataframe query is throwing error after closing the DB-conection, if read from CLOB

### ISSUE THREAD

**Issue by lmocsi** [oracle/python-cx_Oracle#589]
Hi,

If I read any data into a dataframe from a CLOB field through pd.read_sql() and close the database connection, then upon accessing the dataframe, I get "cx_Oracle.DatabaseError: DPI-1040: LOB was already closed" error.

cx_Oracle: 8.2.1

```
import cx_Oracle
import pandas as pd

dsn = 'my_database'
user = 'my_user'
pw = 'my_password'

conn = cx_Oracle.connect(user, pw, dsn)
sql = "select sql_text from sys.SQL$TEXT where rownum <= 5"  # read data from any CLOB field
df_ora = pd.read_sql(sql, con=conn)
print(df_ora) # prints correctly

conn.close()

print(df_ora) # throws "cx_Oracle.DatabaseError: DPI-1040: LOB was already closed" error
```

Can someone fix this?
[ora_error.txt](https://github.com/oracle/python-cx_Oracle/files/7391078/ora_error.txt)

Thanks

**Comment by lmocsi** [comment]
Can this output_type_handler be made the default outputtypehandler in cx_Oracle?

**Comment by anthony-tuininga** [comment]
It could, but doing so would break existing code that assumes that LOBs are being fetched! I have been working on an enhancement that will allow for setting default values like this more easily -- at that point it would be as easy as this:

```
import cx_Oracle as oracledb
oracledb.defaults.fetch_lobs = False
```

This would eliminate the need for the output type handler. Something you can do today, if you have a mind, is as follows:

```
import cx_Oracle as oracledb
class Connection(oracledb.Connection):

    def outputtypehandler(cursor, name, default_type, size, precison, scale):
        if default_type == oracledb.CLOB:
            return cursor.var(oracledb.LONG_STRING, arraysize=cursor.arraysize)
        if default_type == oracledb.BLOB:
            return cursor.var(oracledb.LONG_BINARY, arraysize=cursor.arraysize)

conn = Connection("user/password@host/service_name")
```

Use of such a connection would have the new default that you desire. If you didn't want to use it for one particular connection (or cursor) you could always set the attribute `outputtypehandler` to None on that particular connection or cursor. Make sense?
