### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '0b2

### ISSUE THREAD

**Issue by ying-w** [oracle/python-cx_Oracle#59]
Using version  6.0b2 from conda on python3 64-bit on windows.

On initialization, the following line has an error:

```py
        if hasattr(self.dbapi, 'version'):
            self.cx_oracle_ver = tuple([int(x) for x in
                                        self.dbapi.version.split('.')])
        else:
            self.cx_oracle_ver = (0, 0, 0)
```
This is line 708-712 on my version of cx_Oracle.py

since version is 6.0b2, the error occurs when trying to call int('0b2')

#### Answer the following questions:

1. What is your version of Python? Is it 32-bit or 64-bit?

python 3.6 64-bit

2. What is your version of cx_Oracle?

6.0b2

3. What is your version of the Oracle client (e.g. Instant Client)?  How was it
   installed?  Where is it installed?

instant client

4. What is your version of the Oracle Database?

12

5. What is your OS and version?

windows 10 64-bit enterprise

6. What compiler version did you use?  For example, with GCC, run
   `gcc --version`.

MSC?

7. What environment variables did you set?  How *exactly* did you set them?

8. What *exact* command caused the problem (e.g. what command did you try to
   install with)?  Who were you logged in as?

create_engine() on using sqlalchemy

9. What error(s) you are seeing?

  File "C:\ProgramData\Miniconda3\lib\site-packages\sqlalchemy\dialects\oracle\cx_oracle.py", line 710, in __init__
    self.dbapi.version.split('.')])
  File "C:\ProgramData\Miniconda3\lib\site-packages\sqlalchemy\dialects\oracle\cx_oracle.py", line 709, in <listcomp>
    self.cx_oracle_ver = tuple([int(x) for x in
ValueError: invalid literal for int() with base 10: '0b2'

**Comment by anthony-tuininga** [comment]
This issue was raised earlier: https://github.com/oracle/python-cx_Oracle/issues/27. There's already a solution in place, too!
