### ISSUE TITLE
pip install for cx_Oracle-8.2.1 fails on MacOS 12.0.1

### ISSUE THREAD

**Issue by michaellewis-faa** [oracle/python-cx_Oracle#591]
Command run: pip3 install -r requirements.txt

Building wheels for collected packages: cx-Oracle
  Building wheel for cx-Oracle (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python3 /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /var/folders/d2/wtpwr5_x0rbg4f4079hy98c00000gn/T/tmphsc9ph_z
       cwd: /private/var/folders/d2/wtpwr5_x0rbg4f4079hy98c00000gn/T/pip-install-1pf1t3bd/cx-oracle_26573c96c8354a0bbe8918e16aa299b2
  Complete output (12 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'cx_Oracle' extension
  creating build
  creating build/temp.macosx-10.9-x86_64-3.7
  creating build/temp.macosx-10.9-x86_64-3.7/src
  creating build/temp.macosx-10.9-x86_64-3.7/odpi
  creating build/temp.macosx-10.9-x86_64-3.7/odpi/src
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -DCXO_BUILD_VERSION=8.2.1 -Iodpi/include -Iodpi/src -I/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c src/cxoApiType.c -o build/temp.macosx-10.9-x86_64-3.7/src/cxoApiType.o
  clang: error: invalid version number in 'MACOSX_DEPLOYMENT_TARGET=11'
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for cx-Oracle

I tried exporting MACOSX_DEPLOYMENT_TARGET=12 with same failure.

('platform.platform:', 'Darwin-21.1.0-x86_64-i386-64bit')
('sys.maxsize > 2**32:', True)
('platform.python_version:', '2.7.18')

1. What versions are you using?

2. Is it an error or a hang or a crash?

3. What error(s) or behavior you are seeing?

4. Include a runnable Python script that shows the problem.

**Comment by cjbj** [comment]
Is your [tool chain up to date](https://developer.apple.com/forums/thread/682598)?

**Comment by michaellewis-faa** [comment]
It appears this may be related to an issue compiling with gcc on Monterey
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=102992

**Comment by cjbj** [comment]
@michaellewis-faa did you get any further with this?

**Comment by AykCanDem** [comment]
any solution to this?
```
Building wheel for cx_oracle (pyproject.toml) did not run successfully.
```
