### ISSUE TITLE
Use scrollable cursor, execute “select * from all_ triggers where owner='SYS'”  report errors

### ISSUE THREAD

**Issue by caiyi0923** [oracle/python-cx_Oracle#592]
```
>>> import cx_Oracle

>>> conn = cx_Oracle.connect(user="sys", password="xxxx", dsn="1.2.3.57:1521/LEADER", mode=cx_Oracle.SYSDBA)
>>> cur = conn.cursor()
>>> cur.execute("select * from  all_triggers where owner='SYS'")
>>> cur.scroll(1, mode='absolute')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
cx_Oracle.DatabaseError: ORA-24390: Unsupported scrollable cursor operation

```
The same mistake occurs in “SELECT * FROM  ALL_VIEWS WHERE OWNER='HR'”

I don’t understand the cause of the error, because it’s no errors to execute a normal "select * from xxx" statement

**Comment by cjbj** [comment]
The `TRIGGER_BODY` column is a `LONG`.  The [OCI doc](https://docs.oracle.com/en/database/oracle/oracle-database/21/lnoci/using-sql_statements-in-oci.html#GUID-1728D572-BED3-4F80-BDC3-E6F9A66046B2) says:
> A cursor cannot be made scrollable if the LONG data type is part of the select list.

**Comment by caiyi0923** [comment]
Thanks for your answer, I want to implement the function of jumping pages, and need to use "scroll".
Is there any good solutions?

**Comment by cjbj** [comment]
Simple offset/fetch-next paging works for many things, see https://cx-oracle.readthedocs.io/en/latest/user_guide/sql_execution.html#limiting-rows and https://cx-oracle.readthedocs.io/en/latest/user_guide/tuning.html#tuning-fetch-performance

However if you need a read-consistent view, you can do things like use a flashback query with the `AS OF` clause.  Refer to DB doc and resources.

**Comment by cjbj** [comment]
Or maybe don't select the TRIGGER_BODY column in the initial page of results?

**Comment by caiyi0923** [comment]
> Simple offset/fetch-next paging works for many things, see https://cx-oracle.readthedocs.io/en/latest/user_guide/sql_execution.html#limiting-rows and https://cx-oracle.readthedocs.io/en/latest/user_guide/tuning.html#tuning-fetch-performance
> 
> However if you need a read-consistent view, you can do things like use a flashback query with the `AS OF` clause. Refer to DB doc and resources.

Okay. It works. Thank you so much.
