### ISSUE TITLE
output type handler for cursor.callproc()

### ISSUE THREAD

**Issue by abilashrg** [oracle/python-cx_Oracle#599]
1. What versions are you using?
cx_Oracle.version: 8.3.0

Give your database version.
Oracle 19c

Also run Python and show the output of:

    import sys
    import platform

    print("platform.platform:", platform.platform())
    print("sys.maxsize > 2**32:", sys.maxsize > 2**32)
    print("platform.python_version:", platform.python_version())

platform.platform: Windows-10-10.0.18363-SP0
sys.maxsize > 2**32: True
platform.python_version: 3.8.10

And:

    import cx_Oracle
    print("cx_Oracle.version:", cx_Oracle.version)
    print("cx_Oracle.clientversion:", cx_Oracle.clientversion())

cx_Oracle.version: 8.3.0
cx_Oracle.clientversion: (19, 3, 0, 0, 0)

-->

2. Describe the problem

I have a Oracle stored procedure which I'm calling from python using cursor.callproc(). Procedure returns CLOB as data type and in python it is converted as cx_Oracle.LOB.

I'm trying to read lob as string using cursor.outputtypehandler. Sample code below.

def output_type_handler(cursor, name, default_type, size, precision, scale):
    if default_type == cx_Oracle.DB_TYPE_CLOB:
        return cursor.var(cx_Oracle.DB_TYPE_LONG, arraysize=cursor.arraysize)
    if default_type == cx_Oracle.DB_TYPE_BLOB:
        return cursor.var(cx_Oracle.DB_TYPE_LONG_RAW, arraysize=cursor.arraysize)

I have couple of questions
1. Does outputytypehandler work for cursor.callproc()?
2. If no, is there a way we can read lob as string from procedure

**Comment by sharadraju** [comment]
Ans to Qn 1:
outputtypehandler does not affect the values returned from cursor.callfunc() or cursor.callproc().(Documentation [here](https://cx-oracle.readthedocs.io/en/latest/user_guide/sql_execution.html#outputtypehandlers)).

Ans to Qn2:
One workaround is to convert the LOB object obtained from _callproc()_ to a string by using the LOB object's [read()](https://cx-oracle.readthedocs.io/en/latest/api_manual/lob.html#LOB.read) method.

I will also keep you updated, if there are any other solutions.

**Comment by abilashrg** [comment]
thanks @sharadraju. Kindly keep me posted if there is any other solution.

**Comment by cjbj** [comment]
We should update the cx_Oracle doc to note the special case of REF CURSOR bind variables returned from callproc & callfunc. Since these are queries, they are affected by output type handlers, see https://github.com/oracle/python-cx_Oracle/issues/590#issuecomment-956358448 for an example.

**Comment by cjbj** [comment]
I'll close this as answered.  I've noted where the doc can be improved.
