### ISSUE TITLE
General question - does cx_Oracle support Py_LIMITED_API?

### ISSUE THREAD

**Issue by danizen** [oracle/python-cx_Oracle#6]
When I build cx_Oracle with Python 3.4.x, I end up with a wheel named:

cx_Oracle-5.3-cp34-cp34m-linux_x86_64.whl

I would like a way to build cx_Oracle so it will be compatible with all versions Python 3.4.   Same issue is true on Windows.

It is OK if this is a somewhat manual process - e.g. I'm already building the wheel myself.   If I need to pass obscure `--global-option` parameters to pip wheel, then this is OK, but the only time I tried to do this myself I ended up trying to modify `setup.py`, and I don't want to do that.

**Comment by danizen** [comment]
I'm looking to get a version that if compiled with Python 3.4.6 will work with Python 3.4.2 as well.   I guess my understanding is that if `Py_LIMITED_API` is not specifically set, the current HEX version of the ABI is assumed.  So, having some setting I can give to pip to set `-DPy_LIMITED_API=0x03040000`.   I hope I said that right ;)

Up until now, this has bit me just on the Windows client side.   When I built cx_Oracle 5.2 for Windows, I ended up with `cx_Oracle-5.2-cp35-none-win_amd64.whl`, but when I built 5.2.1, I had already upgraded to Python 3.5.1, and ended up with `cx_Oracle-5.2.1-cp35-cp35m-win_amd64.whl`.   pip would not install the latter on Python 3.5.0.

Now, my systems folks have updated to Python 3.4.6 on the server side on the never development server.  I'm afraid if I build a package with Python 3.4.6 in development, and put it into a repository, it will not be able to install safely in QA and Production.   This is for more reason than just the ABI, but the ABI is my main worry.

One level of my question is purely mechanical, and has nothing specifically to do with cx-Oracle - I just don't know how to make `setup.py` or `pip wheel` even change CFLAGS for extensions.   If it doesn't work, I'm pretty sure it is too much to make it work just for me.  I think I tried export CFLAGS, maybe I should try again.

**Comment by anthony-tuininga** [comment]
I believe I understand what you are saying. Right now, it doesn't matter if you can get pip to change the flags as it won't compile! I'll look into the effort required to set that flag.

In theory, the module built with Python 3.4.6 should install safely into earlier versions of Python 3.4. If pip is being annoying, however, you can simply ignore it and copy the file cx_Oracle.pyd wherever it needs to go -- since that is the only file that cx_Oracle requires.

**Comment by danizen** [comment]
Thanks for looking into this.

**Comment by danizen** [comment]
@anthony-tuininga , this is back from before cx_Oracle 6, and so I think closing is the best idea.   We've moved on to 3.6.3 on the server and 3.6.8 on our clients, and I don't even remember why I wanted to do this ;)

**Comment by danizen** [comment]
Actually, the manylinux1 PEP solved this issue for me much more generally.

**Comment by anthony-tuininga** [comment]
Thanks for following up. I had reached much the same conclusion, too. :-)
