### ISSUE TITLE
ImportError: ld.so.1: python2.7: wrong ELF class: ELFCLASS64

### ISSUE THREAD

**Issue by CXKOracle** [oracle/python-cx_Oracle#600]
1. What versions are you using?

2. Describe the problem

import cx_Oracle

ImportError: ld.so.1: python2.7: wrong ELF class: ELFCLASS64

so I downloaded cx_Oracle-5.1.3.tar.gz it is 32-bit, where can I get 64-bit as this is what is giving me error. Or I will be obliged if you can please suggest workaround. else I will not be able carry on with python scripting for Oracle migration. 

3. Show the directory listing where your Oracle Client libraries are installed (e.g. the Instant Client directory).  Is it 64-bit or 32-bit?
64-bit

4. Show what the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) is set to?

[oracle]$  echo $LD_LIBRARY_PATH
/u01/app/oracle/product/11.2.0/db/lib

5. Show any Oracle environment variables set (e.g. ORACLE_HOME, ORACLE_BASE).
[oracle]$  echo $ORACLE_HOME
/u01/app/oracle/product/11.2.0/db

**Comment by anthony-tuininga** [comment]
Please review the [installation documentation](https://cx-oracle.readthedocs.io/en/latest/user_guide/installation.html).

If you use pip it will automatically install the correct architecture for you. If you download the source then you will need to build it yourself using either a 32-bit of 64-bit compiler -- and that is completely in your control! For simplicity I would use pip. :-)
