### ISSUE TITLE
Reusing object type from an already closed session for another session: OCI-21710

### ISSUE THREAD

**Issue by robingie** [oracle/python-cx_Oracle#604]
Hello there,

lately, I'm dealing with the objects types from the oracle database within Python.

I'm fetching a resultset with one or more object types (collections + inner objects types) in a different session. After a few processing steps, I would like to reuse the cx_Oracle.Object. 

If I reuse the object from the old session within a new session I get the following error:
_error code: 21710 - error_message: OCI-21710: argument is expecting a valid memory address of an object_

In the new session, I'm calling the cursor.callproc() method.

Is there any way to reuse the object without rebuilding it from scratch?
The different sessions are a requirement by the application design.

**Comment by cjbj** [comment]
Sorry, this is a behavior-by-design of the Object model in the Oracle Client libraries.  But thanks for letting us know this is important to you.  We'll continue to highlight the demand with the Oracle team looking after this area.
