### ISSUE TITLE
How to connect to Oracle database with both username/password and wallet?

### ISSUE THREAD

**Issue by tinglixing** [oracle/python-cx_Oracle#605]
<!--
1. What versions are you using?
Oracle Client 18 home 1 SQL Developer- 

platform.platform: Windows-10-10.0.18362-SP0
sys.maxsize > 2**32: True
platform.python_version: 3.8.8

cx_Oracle.version: 8.0.1
cx_Oracle.clientversion: (18, 3, 0, 0, 0)

2. Describe the problem

I am using cx_Oracle to connect to Oracle database. The Oracle database has 2 factor authentication, one is using user name and password, another one is using wallet. I also set TNS_ADMIN environment variable pointing to where sqlnet.ora is.  Code is simple

```
import cx_Oracle
import os

os.environ.get('ORACLE_HOME')
os.environ.get('TNS_ADMIN')
conn = cx_Oracle.connect(user='user', password='password', dsn='database_name')
```
I get error:
DatabaseError: ORA-28759: failure to open file

Any insight would be appreciated!

**Comment by cjbj** [comment]
Review https://cx-oracle.readthedocs.io/en/latest/user_guide/connection_handling.html#connecting-to-oracle-cloud-autononmous-databases which shows how to configure the network files so the wallet is referenced.  If you have further questions, please post details.
