### ISSUE TITLE
Typo in CQN documentation

### ISSUE THREAD

**Issue by ancc** [oracle/python-cx_Oracle#607]
1. What is the link to the documentation section that needs improving?
https://github.com/oracle/python-cx_Oracle/blob/main/doc/src/user_guide/cqn.rst

2. Describe the confusion
"An example script to receive query notifications when the 'CUSTOMER' table data changes is:"

3. Suggest changes that would help
Based on example the table is region not customer.

**Comment by cjbj** [comment]
This was fixed in the major release (which was renamed to python-oracledb): https://python-oracledb.readthedocs.io/en/latest/user_guide/cqn.html#registering-queries

Thanks for helping make the doc better.
