### ISSUE TITLE
Unable to execute PKG_BUSINESS_AREA.SP_Initialize_BA pakcage, this package is part of oracle life science which is built on to of Oracle Pl/sql.

### ISSUE THREAD

**Issue by joehumingtec** [oracle/python-cx_Oracle#609]
1. What versions are you using?
cx_Oracle.clientversion: (21, 3, 0, 0, 0)

2. Describe the problem
import cx_Oracle
import OC_db_config

try:
    con = cx_Oracle.connect(OC_db_config.user, OC_db_config.pw, OC_db_config.dsn)
    cur = con.cursor()
    cur.execute("""declare
   result number;
begin
   -- Call the function
   result := csdw_global.PKG_BUSINESS_AREA.SP_Initialize_BA('BA_C0251005_SRDMT_PROD',NULL,'NA/Dummy');
end;
            """)
    
except Exception as e:
    print("There was an issue connecting to Oracle: ", e)

3. Include a runnable Python script that shows the problem.

the following is the error i get
There was an issue connecting to Oracle:  ORA-06550: line 5, column 14:
PLS-00222: no function with name 'SP_INITIALIZE_BA' exists in this scope
ORA-06550: line 5, column 4:
PL/SQL: Statement ignored
------
i run in Toad connected to oracle as 
Execute PKG_BUSINESS_AREA.SP_Initialize_BA('BA_C0251005_SRDMT_PROD',NULL,'NA/Dummy')
it works, but the same in cx_Oracle does not work. kindly help resolve

**Comment by cjbj** [comment]
- Check your connection credentials and connection string match those used by Toad?
- Run the exact same code in Toad _including_ the DECLARE 
- Run the same PL/SQL block in SQL*Plus (not Toad or SQL Developer)
- Google the error numbers; ORA-06550 looks like a problem wth the PL/SQL block
- Ask the Life Science people about it

**Comment by anthony-tuininga** [comment]
In Toad you appear to be calling a *procedure* but in Python you are calling a *function*. Which one is it? If a procedure you can just do this:

```
cursor.callproc("PKG_BUSINESS_AREA.SP_Initialize_BA", ['BA_C0251005_SRDMT_PROD', None, 'NA/Dummy'])
```

That code is the closest you are going to get to the code you used in Toad that works.

**Comment by joehumingtec** [comment]
Cursor.callproc () worked for me thanks for responds to my query

**Comment by joehumingtec** [comment]
> * Check your connection credentials and connection string match those used by Toad?
> * Run the exact same code in Toad _including_ the DECLARE
> * Run the same PL/SQL block in SQL*Plus (not Toad or SQL Developer)
> * Google the error numbers; ORA-06550 looks like a problem wth the PL/SQL block
> * Ask the Life Science people about it

Cursor.callproc() worked for me
