### ISSUE TITLE
Kerberos Support by cx_Oracle

### ISSUE THREAD

**Issue by inkitm** [oracle/python-cx_Oracle#61]
Hello

If I want to login to oracle database using an External Kerberos Authenticated user from cx_oracle, what would be the code look like. 
Is that even supported by cx_oracle? 
How does the Kerberos Ticket management happens at the server where cx_oracle runs?

Best Regards

**Comment by cjbj** [comment]
Kerberos is configured in a code layer below cx_Oracle so it's not something cx_Oracle is aware of.  See https://docs.oracle.com/database/122/DBSEG/configuring-kerberos-authentication.htm#DBSEG060  

I believe once you have Kerberos configured, then you connect in cx_Oracle using normal external authentication like:

```
import cx_Oracle
conn = cx_Oracle.connect(dsn = "the_tns_entry_name")
```

(as mentioned by @anthony-tuininga  in https://stackoverflow.com/a/44060556/4799035)

I've not had to configure Kerberos.  Questions on it would be better asked on OTN.

**Comment by tonykoval** [comment]
I tried this, but I get error: `ORA-01017: invalid username/password; logon denied` (with SQL developer connection works)
```
import cx_Oracle
import krbcontext

with krbcontext.krbContext(
        using_keytab=True,
        principal="xxx",
        keytab_file='xxx.keytab',
        ccache_file='/tmp/krb5cc_pid_appname'
        ):

    dsn_tns = cx_Oracle.makedsn("xxx", 1521, service_name="xxx")

    con = cx_Oracle.connect(dsn=dsn_tns)

    print(con.version)
```
Any idea?

**Comment by cjbj** [comment]
Have you tried linking cx_Oracle with the full Oracle Client ?  I seem to recall the group that owns the relevant area of the Oracle code opening an enhancement request against themselves to add Kerberos support to Instant Client.

**Comment by cjbj** [comment]
If it helps, check Oracle Support's 'Master Note For Kerberos Authentication (Doc ID 1375853.1)'

**Comment by tonykoval** [comment]
> Have you tried linking cx_Oracle with the full Oracle Client ? I seem to recall the group that owns the relevant area of the Oracle code opening an enhancement request against themselves to add Kerberos support to Instant Client.

Yes (oracle-instantclient18.3-basic-18.3.0.0.0-1.x86_64.rpm).

**Comment by cjbj** [comment]
Using instant client could be a problem - though I did dig up that you should be able to use Kerberos tools from MIT or a JDK if you have Instant Client.  Sorry for the trickle of information - this is not our area of expertise.

**Comment by tonykoval** [comment]
> Using instant client could be a problem - though I did dig up that you should be able to use Kerberos tools from MIT or a JDK if you have Instant Client. Sorry for the trickle of information - this is not our area of expertise.

Thank you. I found out workaround with JDBC:

```
import jaydebeapi
import krbcontext

with krbcontext.krbContext(
        using_keytab=True,
        principal="xxx",
        keytab_file='xxx.keytab',
        ccache_file='/tmp/krb5cc_pid_test'
        ):

    conn = jaydebeapi.connect(
        "oracle.jdbc.OracleDriver",
        "jdbc:oracle:thin:@//xxx",
        {'oracle.net.authentication_services': "(KERBEROS5)"},
        "/usr/lib/oracle/18.3/client64/lib/ojdbc8.jar")

    curs = conn.cursor()
    curs.execute("SELECT 1 FROM DUAL")
    
    print(curs.fetchall())
    
    curs.close()
    conn.close()
```

**Comment by cjbj** [comment]
Thanks for sharing.  This seems to be NOT using cx_Oracle, but it if it works for you...

**Comment by cordularaecke** [comment]
is there anyone that can publish a simple example of connecting to an Oracle database using Kerberos authentication.  I cannot find instructions how to make such a connection.  Please help.

**Comment by cjbj** [comment]
@cordularaecke since the setup is not specific to cx_Oracle, perhaps you can ask on another forum?

**Comment by cordularaecke** [comment]
@cjbj thanks for replying.  I'm sorry but I've no idea who/where to ask.  I've checked stackoverflow etc. and cannot find a set of steps to check where the issue may be. Without a solution, I will no longer be able to use cx_oracle in my data extraction analysis work. If i use sqldeveloper, I must select a drop down box to specify what 'authentication type' is being used. How does cx_oracle determine what type of authentication to apply with the connection if there is no parameter to specify it?

![image](https://user-images.githubusercontent.com/63249992/78771705-e7d57900-7990-11ea-81f0-5fa41123582d.png)

**Comment by cjbj** [comment]
In cx_Oracle and other command line drivers, you indicate external authentication as I mentioned above in https://github.com/oracle/python-cx_Oracle/issues/61#issuecomment-320121457.

Also see https://cx-oracle.readthedocs.io/en/latest/user_guide/connection_handling.html#connecting-using-external-authentication

**Comment by cordularaecke** [comment]
Thanks for your feedback. It appears that the only way is to create an Oracle Wallet per dsn.  I have over 20 connections to manage, so this seems to be rather difficult to maintain, e.g. our domain pwds must be changed every 8 weeks.  

I would prefer not to use oracle.jdbc.OracleDriver as a solution but seems more straightforward.  Is there no plans to add a simplified approach for Kerberos authentication support?

**Comment by cordularaecke** [comment]
Just found this:
https://stackoverflow.com/questions/44020986/cx-oracle-with-windows-authentication/44060556#44060556

I have tried this too, and i cannot make this work. So, will try jdbc workaround.
![image](https://user-images.githubusercontent.com/63249992/78789402-650ee700-79ad-11ea-88ba-eea5faa40652.png)

**Comment by cjbj** [comment]
Tell us what you have tried, what errors you get, and how you've set up Kerberos?
