### ISSUE TITLE
Some results are byte strings

### ISSUE THREAD

**Issue by niharsalunke** [oracle/python-cx_Oracle#610]
1. What versions are you using?

platform.platform: Windows-10-10.0.18362-SP0
sys.maxsize > 2**32: True
platform.python_version: 3.7.4

cx_Oracle.version: 8.3.0
cx_Oracle.clientversion: (21, 3, 0, 0, 0)

2. Describe the problem

Let's say I ran a complex query in Oracle sqldeveloper client. The result was all readable as below:

col A | col B
    a   |    b
    c   |    d

Now, when I try fetch the same results via python cx_Oracle,
I get some results as byte strings:

col A | col B
    a   |    b'==\xba\xc2\xc7\xf49\x04'
    c   |    b'==\xba\xc2\xc7\xf5r|'

If there are 10 columns, around 2-3 columns have this issue. I suspect the values in these columns might be a reference string to the actual object in the DB. I did not find any solution to this issue online.  

3. Include a runnable Python script that shows the problem.

Example Code (for syntax and functions reference):
```
import cx_Oracle
result = cursor.execute('''select * FROM  A_TABLE '').fetchall()
print(result)
```

**Comment by niharsalunke** [comment]
Hello, 
The problem has been solved for me.
Solution:
The byte string was actually RAW data in Oracle. Hence it needs type casting.
Adding **UTL_RAW.CAST_TO_VARCHAR2(utl_raw.cast_to_raw())** method solved my problem.

`cursor.execute('''select UTL_RAW.CAST_TO_VARCHAR2(utl_raw.cast_to_raw(<Raw Data Column Name>))  FROM   Table Name'').fetchall()
`

**Comment by anthony-tuininga** [comment]
That is certainly one solution. You could also decode the raw bytes into a string in Python, as in this:

```
value_from_database.decode()
```

That assumes the RAW data is UTF-8 encoded. If it is some other encoding, use the appropriate encoding as the argument to the ``decode()`` function.
