### ISSUE TITLE
Error types and descriptions are too generic (at least when working with temporary tables)

### ISSUE THREAD

**Issue by benyaming** [oracle/python-cx_Oracle#615]
1. What versions are you using?

DB version: Oracle Database 19c Standard Edition 2 Release 19.0.0.0.0 - Production

Also run Python and show the output of:

```
platform.platform: Darwin-21.1.0-x86_64-i386-64bit
sys.maxsize > 2**32: True
platform.python_version: 3.7.11
#
cx_Oracle.version: 7.3.0
cx_Oracle.clientversion: (19, 8, 0, 0, 0)
```

2. Is it an error or a hang or a crash? - Neither 

3. What error(s) or behavior you are seeing?

I've tried to work with private temporary tables. There were multiple errors I got, like invalid table name or insufficient permissions, but all that cx_oracle said -- "ORA-14451: unsupported feature with temporary table".

4. Include a runnable Python script that shows the problem.

```
>>> import cx_Oracle
>>> connection = cx_Oracle.connect('user', 'pass', 'localhost:9967/TESTDB')
>>> connection.version
'19.12.0.0.0'
>>> cursor = connection.cursor()
>>> cursor.execute('CREATE PRIVATE TEMPORARY TABLE name_with_error (id NUMBER(10)) ON COMMIT DROP DEFINITION')

Traceback (most recent call last):
  File "/Users/benyaming/.pyenv/versions/3.7.11/lib/python3.7/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
cx_Oracle.DatabaseError: ORA-00903: invalid table name

```

But if I run this query in sql console, here is what I got:
```
> CREATE PRIVATE TEMPORARY TABLE name_with_error (id NUMBER(10)) ON COMMIT DROP DEFINITION;

[42000][903] ORA-00903: invalid table name. Position: 0
```

**Comment by cjbj** [comment]
ORA errors are generated by Oracle Database or Oracle client libraries. They are out of scope of the cx_Oracle project.  The 'offset' of the problem is also sent back to cx_Oracle - you can access it easily, see the user doc https://cx-oracle.readthedocs.io/en/latest/api_manual/module.html#cx_Oracle._Error.offset
