### ISSUE TITLE
M1 Mac (e.g ARM64) version of Oracle InstanceClient

### ISSUE THREAD

**Issue by wshayes** [oracle/python-cx_Oracle#617]
Can you please build a MacOS ARM64 version of the Oracle InstantClient natively compatible with the new M1 Macs? 

There are now build targets in several CI/CD build systems for Mac ARM64 architectures.

It's the only library that is keeping me from using native development on the M1 Mac.

**Comment by cjbj** [comment]
I'm sure it will be well received.  I'm told it is planned but no ETA.

Since the question is out of scope of the cx_Oracle project, I'll close this issue.

**Comment by wshayes** [comment]
Can you tell me which repo it's in scope? I couldn't find a github repo or feedback for the Oracle Instant Client.

**Comment by cjbj** [comment]
@wshayes Oracle Client libraries are part of the Oracle Database product family so feedback should be directed at Oracle Support. However, since I do the "product management" for Instant Client's overall packaging (but not for all the products included), I have already got your feedback.  The development organization who do the porting are aware there is demand.  I'd like to hurry it along but that team handles lots of products on lots of platforms ie. has lots of priorities to juggle.

**Comment by rachitpant** [comment]
@cjbj Can its priority be bumped up please. Apple is already out with M2 chip and its frustrating to say the least. Every other library has transitioned to the new chip.

**Comment by anthony-tuininga** [comment]
Are you able to make use of thin mode in the new driver: [python-oracledb](https://oracle.github.io/python-oracledb/)?

**Comment by rachitpant** [comment]
We want to connect with ruby ( ruby-oci8 ). And we have several ( around 30 existing rails apps : pointing to oracle db ) and now all developers have upgraded their machines to M1 macs.

**Comment by anthony-tuininga** [comment]
Not much I can do to help, then! I'll leave it to @cjbj to comment further -- but it is out of his hands, too.

**Comment by cjbj** [comment]
> Every other library has transitioned to the new chip.

From what I'm told, that would be every library except the third-party libraries needed by Oracle Client.

But I do feel your pain.  Until there is a solution, you will have to use Rosetta or fiddle with the ARM Linux Instant Client, see https://github.com/oracle/docker-images/issues/2447

**Comment by cjbj** [comment]
@ilyas-gx you can now use the new version of cx_Oracle [renamed to python-oracledb](https://cjones-oracle.medium.com/open-source-python-thin-driver-for-oracle-database-e82aac7ecf5a) since it doesn't need Instant Client.

Or you could use the [ARM Linux Instant Client in a Docker container](https://github.com/oracle/docker-images/issues/2447#issuecomment-1233446837).

**Comment by brytonbeesley** [comment]
@cjbj is Oracle still planning to build a MacOS ARM64 version of the Oracle InstantClient natively compatible with the M1 Macs?  Or is python-oracledb the only intended solution?

I ask because I've explored python-oracledb with my team and it won't work with our configuration.  We're hitting this issue: https://github.com/oracle/python-oracledb/issues/26.

In short, the thin mode driver requires that the sec_case_sensitive_logon parameter be set to TRUE, and our DBA's won't change it, saying that they've set it to FALSE per Oracle's instruction in Doc ID 2530680.1

**Comment by cjbj** [comment]
Instant Client for Apple Silicon is still planned.  I can't tell you any ETA.

Can you use the Intel Instant Client with Rosetta in the meantime?  Or the ARM Linux Instant Client in a container https://github.com/oracle/docker-images/issues/2447#issuecomment-1233446837 ?

**Comment by triscuitcircuit** [comment]
Any update on this?

**Comment by cjbj** [comment]
@triscuitcircuit no update.  But with the upgrade to python-oracledb you don't necessarily need Instant Client.  See the [release announcement](https://cjones-oracle.medium.com/open-source-python-thin-driver-for-oracle-database-e82aac7ecf5a).

**Comment by triscuitcircuit** [comment]
Thanks! 

However, I did come accross the need for M1 Mac version of Oracle Instant Client while trying to build a project with `node` that uses `oracledb`. This even occured with a `npm oracledb` driver from source

```
Failed to sync db: DPI-1047: Cannot locate a 64-bit Oracle Client library: "dlopen(libclntsh.dylib, 0x0001): tried: 'libclntsh.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibclntsh.dylib' (no such file), '/usr/local/lib/libclntsh.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/libclntsh.dylib' (no such file), '/usr/lib/libclntsh.dylib' (no such file, not in dyld cache), 'libclntsh.dylib' (no such file), '/usr/local/lib/libclntsh.dylib' (no such file), '/usr/lib/libclntsh.dylib' (no such file, not in dyld cache)". See https://oracle.github.io/node-oracledb/INSTALL.html for help
Node-oracledb installation instructions: https://oracle.github.io/node-oracledb/INSTALL.html
You must have the arm64 Oracle Instant Client Basic or Basic Light package libraries in
/usr/local/lib or set by calling oracledb.initOracleClient({libDir: "/my/instant_client_directory"}).
Oracle Instant Client can be downloaded from https://www.oracle.com/database/technologies/instant-client.html
```

I realize now that I should've posted this on a seperate issue, but it seemed relavent. Is there a way to circumvent the need Orcale Instant Client for this issue?

**Comment by cjbj** [comment]
@triscuitcircuit For node-oracledb 5.x not yet.  You still need Oracle client libs.  But see https://github.com/oracle/node-oracledb/issues/1349#issuecomment-1397366434

**Comment by brytonbeesley** [comment]
> Instant Client for Apple Silicon is still planned. I can't tell you any ETA.
> 
> Can you use the Intel Instant Client with Rosetta in the meantime? Or the ARM Linux Instant Client in a container [oracle/docker-images#2447 (comment)](https://github.com/oracle/docker-images/issues/2447#issuecomment-1233446837) ?

Hi @cjbj, thanks for your attentive replies to this thread.  I'm embarrassed that as yet I have not shown appreciation by at least replying to your question--Can [I] use the Intel Instant Client with Rosetta?  The answer as far as it concerns my local development on an M1 Mac is probably yes, if there is no better option.  I've been hoping it would not come to that.  Meanwhile I've been biding time and getting along by retaining an older MacBook issued by my employer that runs on an Intel chip, but I'm eager to relinquish the Intel MacBook.

Here's to hoping that a MacOS ARM64 version of the Oracle InstantClient natively compatible with the M1 Macs will be prioritized soon!  One can dream.

**Comment by cjbj** [comment]
Me too.

**Comment by marct83** [comment]
Me three.

**Comment by dimitrius-ion** [comment]
Me 4

**Comment by ferben** [comment]
Me (high) five

**Comment by lorint** [comment]
> (high) five

(Doing my best Borat impression here...)
_Very niiiice!_

And +1 on the hope for a native Apple Silicon driver -- open source what you currently have if you like and the community can port it over.

Or -- go the route that Github and Shopify have done with **[Trilogy](https://github.com/github/trilogy)** -- create a purpose-built Ruby driver!

**Comment by cjbj** [comment]
@lorint in case it isn't known, the latest generation of cx_Oracle (now called python-oracledb) is a Thin Python driver that doesn't need Instant Client.  See the [release announcement](https://cjones-oracle.medium.com/open-source-python-thin-driver-for-oracle-database-e82aac7ecf5a).  It works very nicely on Apple Silicon.

**Comment by Tash2610** [comment]
@cjbj I'm working on an existing playwright automation framework on my MAC M2 machine, which has "oracledb": "5.5.0" as dependencies in the package.json While running yarn install, I face the error "oracledb ERR! NJS-067: a pre-built node-oracledb binary was not found for darwin arm64". I tried a lot of the things that you mentioned in this issue or any other issue as well, but nothing worked. Do you have any specific steps that can resolve this issue?

**Comment by cjbj** [comment]
@Tash2610 because there is no Apple Silicon Instant Client (we're all waiting for this), you will need to use the Intel Instant Client, which means you need to use the Intel Node.js binaries and let Rosetta do its work.  Since there is a node-oracledb binary for Apple Intel, you won't need to compile.  Look at https://github.com/oracle/node-oracledb/issues/1349#issuecomment-1466602181 for steps.

Or you can wait until node-oracledb 6.0 with a Thin mode is released.

**Comment by Tash2610** [comment]
@cjbj rather than waiting for node-oracledb 6.0, Is there a way I can configure oracledb on the latest node version on my MAC M2 machine?

**Comment by cjbj** [comment]
@Tash2610 I just realized you are asking on the wrong forum.  But yes, see the links above.  I'll also post a blog post in a few minutes.

**Comment by cjbj** [comment]
@Tash2610 see https://medium.com/@cjones-oracle/how-to-install-node-oracledb-5-5-and-oracle-database-on-apple-m1-m2-silicon-941fccda692f

**Comment by jonahharris** [comment]
> @Tash2610 I just realized you are asking on the wrong forum.  But yes, see the links above.  I'll also post a blog post in a few minutes.


Any timing estimates on the thin Node driver availability?

**Comment by cjbj** [comment]
@jonahharris I'd say first half of this year, subject to approvals and functionality.

**Comment by Tash2610** [comment]
@cjbj Thank you for sharing the link of the blog. I tried following same steps but getting error on npm install oracledb :- ERR! notsup Unsupported platform for node-darwin-arm64@18.9.0: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"darwin","arch":"x64"}). Do you have any workaround for this? Thanks.

**Comment by cjbj** [comment]
@Tash2610 please open an issue on the node-oracledb repo (and from the error message, you'll need to use a different version of Node.js)

**Comment by byudanb** [comment]
Any Updates?

**Comment by staticdev** [comment]
I also rely on thick client even with the new library. Also just commenting to get notification it case someone has an update.

**Comment by ferben** [comment]
> @jonahharris I'd say first half of this year, subject to approvals and functionality.

Does „1st half of this year“  mean exactly „from 1st January to 30 June 2023“?
If yes, times up 👎

**Comment by cjbj** [comment]
@ferben that was an answer to a side question about node-oracledb, which has been delivered as promised.

**Comment by ferben** [comment]
> @ferben that was an answer to a side question about node-oracledb, which has been delivered as promised.

Oh, I thought it is time for oracle-client library (used in thick client).

So we are still waiting…

**Comment by nickborovik** [comment]
I mean... It's a big software company with a lot of money. M1 chips on market since 2021. And yet we still need to wait for arm architecture driver to be delivered... I'm not saying Oracle is slow, but I thin Gorge RR Martin could finish his book while we are waiting)

**Comment by anthony-tuininga** [comment]
Can you clarify what is preventing you from using the thin driver which runs just fine on ARM? That will help us prioritize work. The thick driver for ARM is not something we can do anything about -- beyond stating that we know those who are requesting it!

**Comment by nickborovik** [comment]
> Can you clarify what is preventing you from using the thin driver which runs just fine on ARM? That will help us prioritize work. The thick driver for ARM is not something we can do anything about -- beyond stating that we know those who are requesting it!

I'm using Oracle 11 version, which is refusing to work with thin driver. I researched everything about this driver as best as I could, but everything is telling me use x64 and Rosetta... but it is a big slow down for my laptop, and impossible to do anything in time.

I've tried anything to get any performance, but there's only one solution for my project start to work - use intel x86 and docker.

I have m1 chip laptop, and thin driver used in python-oracledb always states that i need to use thick driver to be able to connect to database with version 11. Maybe you know other ways to make it work?

**Comment by lorint** [comment]
> what is preventing you from using the thin driver?

How about I do Ruby and no thin driver yet exists for it?

If you want to move this forward, just open-source the ARM64 driver you have already written for Linux, and let the open source community rally around it and make an M1 version from this.

Or -- laison with open source peeps and it can happen post-haste.

**Comment by anthony-tuininga** [comment]
Both the Python and Node.js thin drivers are open source. So you should be able to build an equivalent thin driver for Ruby based on them. If you need help with that we are willing to answer any questions you might have but we are focused on improving the Python and Node.js drivers and don't have the bandwidth to add another driver at this time! I'll let @cjbj comment further as he is the product manager and has more knowledge of internal projects.

**Comment by nickborovik** [comment]
I may be wrong, but Apple is currently planning to do more M chips, and will produce even more Macs with ARM64 architecture. Many companies will soon buy new macs, because of old macs getting out of use. And when this wave of new macs will hit hard, i think here will be more people writing you under this issue.. so i hope this helps you to make some priorities to this driver in workspace

**Comment by anthony-tuininga** [comment]
If you are using Python (the target language for this repository) then a thin driver exists and works just fine with any sort of M chip. If there is a limitation in the thin driver that you are experiencing, please open an issue in python-oracledb and we will prioritize that.

If you are using a *different* language than Python, then my comments above apply and complaining in this repository won't do much good! :-)

**Comment by mborovyk** [comment]
@anthony-tuininga i'm using python (tried 3.6 and 3.8 versions). i keep getting error after successfully running
`pip install oracledb`
error message:
`DPY-3010: connections to this database server version are not supported by python-oracledb in thin mode`
My database version is 11.2 (if i'm not mistaken)

**Comment by anthony-tuininga** [comment]
Yes, Oracle Database 12.1 and higher is required for thin mode. Since 11g is near (or already at?) the end of support it is unlikely that we will spend time adding such support. You are encouraged to upgrade your database to a supported version -- either 19 or the forthcoming 23. :-)

**Comment by cjbj** [comment]
For database issues that require contacting Oracle Support, 11gR2 (and 12.1) are in '[upgrade support](https://support.oracle.com/epmos/faces/DocumentDisplay?id=742060.1)' phase, leaving 19c and 21c as the only DBs that are current. Obviously there are still 11g users, but supporting 11g connectivity in python-oracledb Thin mode wasn't a simple thing so we focused on moving forward.  (For readers not scanning the whole thread: the solutions are to use Thick mode or to upgrade the DB).

Other than the technical blocking issues about the 3rd party libraries not being available, the resourcing of Instant Client on macOS Silicon is a business decision taken several pay grades above me.

**Comment by cjbj** [comment]
@brytonbeesley I have sent in a query to the doc creators to clarify whether this is an absolute requirement for E-Bus, or just a reminder to reset the value in case anything the user has done depends on it.

**Comment by musasoftlabx** [comment]
@cjbj,  My sentiments very much like @brytonbeesley . 
Am using a Mac M1 with node-oracle version 6.1.0. 
Oracle DB version 19c.

Our DBAs too refused to change `sec_case_sensitive_logon` to TRUE so thin mode refuses to work.
Yes, alternative is to use thick mode but check out this link:
[https://www.oracle.com/database/technologies/instant-client/downloads.html]
Instant Client for Mac M chips (ARM) not available.

If there is a way u guys can put an exception in the node-oracledb driver to bypass `sec_case_sensitive_logon: FALSE` or allow previous password versions, that will save u tons of connection related issues since I understand re-writing the InstantClient from Mac ARM might take sometime.

For context, here is the error
<img width="799" alt="image" src="https://github.com/oracle/python-cx_Oracle/assets/13678931/1aaa6dcf-200e-4b72-8bff-759ab29e7739">

**Comment by cjbj** [comment]
@trueWD I'm sorry you feel that way.

**Comment by anthony-tuininga** [comment]
> I mentioned earlier on this thread that "the thin mode driver requires that the sec_case_sensitive_logon parameter be set to TRUE, and our DBA's won't change it, saying that they've set it to FALSE per Oracle's instruction in Doc ID 2530680.1"

I looked through the instructions in the referenced document and I don't see where it says that you need to set `sec_case_sensitive_logon` to FALSE. Can you highlight the particular section that is being referred to? I see in that document that if it *was* set to FALSE that it will be removed (aka cleared so the default value of TRUE takes effect). Maybe you are referring to a different document? The 10g password verifier isn't particularly secure and its use should be discontinued as soon as feasible.

**Comment by lorint** [comment]
> I'm sorry you feel that way.

At this point there really is no other way to feel.

It is obvious that Oracle does not care in the least about offering compatibility for their products.

I will never understand.

**Comment by cjbj** [comment]
> It is obvious that Oracle does not care in the least about offering compatibility for their products.

Personally I object to this statement and could give many counter examples.

**Comment by mariadb-JonahHarris** [comment]
> > It is obvious that Oracle does not care in the least about offering compatibility for their products.
> 
> Personally I object to this statement and could give many counter examples.

Yeah. I've just been lurking on this issue but, as a longtime Oracle user, there are countless examples of Oracle's portability initiatives. It's fine to be upset but, from a business perspective, Apple silicon does not presently reflect a considerable subset of Oracle's client-based market in terms of development-oriented ROI.

**Comment by lorint** [comment]
> could give many counter examples

I'm not interested in this being drawn out to this extent -- now over a year.

I am interested in arriving upon a workable solution.

Please open source the ARM thing you have so that the open source community can work along side you.

**Comment by ferben** [comment]
Interesting opinion.
> It's fine to be upset but, from a business perspective, Apple silicon does not presently reflect a considerable subset of Oracle's client-based market in terms of development-oriented ROI.

In other words, Oracle didn't make Apple Silicon native libs unless Apple discontinue Rosetta2 emulation in macOS?
We did't want macOS Apple Silicon whole Oracle DB solution, only clients libs! 

On-one, even Oracle has real data about number of Devs on macOS which use OracleDB.
So even Oracle can only guess how abandon macOS platform can affect their business.

Until then, lot of people will prefer truly cross-platform solutions like PostgreSQL or MicrosoftSQL, which support macOS Apple Silicon clients seamless.

**Comment by CInglez-STC** [comment]
I have another case where the thin client cannot be used. I need to connect to an instance at Oracle OCI (Database Service) and it has native network encryption enabled. I don't think it is feasable to disable it on database side. So what are my options?

**Comment by anthony-tuininga** [comment]
That restriction is well-known. The only option currently available is to use thick mode. I will mention it again to management.

**Comment by Physium** [comment]
its 2024, does oracle still have arm64 as a priority ?

**Comment by CInglez-STC** [comment]
It's really odd that Oracle ignores an entire community of developers

**Comment by mcwyau** [comment]
Is there any ETA for it yet?

**Comment by chandler-barlow** [comment]
Bumping this due to needing it as well....

**Comment by adunin** [comment]
Seriously? its been two almost two years since this thread was opened.

**Comment by chandler-barlow** [comment]
> Seriously? its been two almost two years since this thread was opened.

They need to just make a M1 client

**Comment by anthony-tuininga** [comment]
Just a reminder that the thin mode of python-oracledb is quite capable of running on macOS today. There are a number of restrictions but for the vast majority this is a perfectly acceptable solution. I do realize that for those affected by those restrictions it can be rather painful. We continue to bring this forward to management and are actively working on removing the restrictions from thin mode, too.

**Comment by chandler-barlow** [comment]
> Just a reminder that the thin mode of python-oracledb is quite capable of running on macOS today. There are a number of restrictions but for the vast majority this is a perfectly acceptable solution. I do realize that for those affected by those restrictions it can be rather painful. We continue to bring this forward to management and are actively working on removing the restrictions from thin mode, too.

I'm bumping this not because of the python client issues. We are working on bindings for the oracle client in haskell. The thin python client isn't really an option for us. We are trying to use odpi-c but it depends on the client ( which is not compatible with arm mac ). Thank you for continuing to bring it up to management though.

**Comment by CInglez-STC** [comment]
Well, as I mentioned before, thin client does not work for me. We were about to move our development instances to Oracle OCI, but it requires thick client. Will we move away from the macs? Sure not, we will stay at AWS fow now. Thanks Oracle!

**Comment by drewanderson17** [comment]
Hi,
Came to this forum as a result of needing to connect to Oracle 11.2 from my M2 mac (which isn't compatible in Thin mode) I was wondering if it was in Oracle plan to create backwards compatibility for older versions of Oracle in the python library?

**Comment by anthony-tuininga** [comment]
@drewanderson17, Oracle Database 11.2 is very old and is no longer supported. As such there are no plans to add support for this in python-oracledb. You really need to look into upgrading your database!

**Comment by aberezin** [comment]
@cjbj  +1 for the M1/M2 OCI driver and thanks for putting up with all of us!  Though I did the get the thin working for my needs.

**Comment by mfvetter** [comment]
+1 for the M1, M2, M3, etc, Apple Silicon OCI driver. I tried to compile the [OCI8 PECL PHP extension](https://pecl.php.net/package/oci8) without success. This is the only thing forcing me to use a Linux virtual machine for the PHP OCI8 driver to work. Ditto: "thanks for putting up with all of us!"

**Comment by ferben** [comment]
Interesting.

Around 03/2021 Oracle release OCI 19.8 (for macOS 10.13+), now (11/2023) Oracle has latest version 19.16 (for macOS 12,0+) as signed&notarized libs on the web.

So there are some effort to support macOS as platform. But still Intel only.

It's hard to believe that compile+test it for Apple Silicon is so much difficult then do it for Intel only.

**Comment by CInglez-STC** [comment]
> Interesting.
> 
> Around 03/2021 Oracle release OCI 19.8 (for macOS 10.13+), now (11/2023) Oracle has latest version 19.16 (for macOS 12,0+) as signed&notarized libs on the web.
> 
> So there are some effort to support macOS as platform. But still Intel only.
> 
> It's hard to believe that compile+test it for Apple Silicon too is so much difficult then do it for Intel only.

Yeah, I know lots of people who rely on macs for development, it's a shame that Oracle does not care.

**Comment by cjbj** [comment]
If you have questions about Instant Client on macOS ARM, please contact your Oracle sales representative.  (If I could do more about it, I would - however the lack of required 3rd party libraries has been a blocker).

This Git repo is for python-oracledb.

**Comment by cjbj** [comment]
And we have liftoff: Instant Client 23.3 for macOS ARM is available https://www.oracle.com/database/technologies/instant-client/macos-arm64-downloads.html. 

As a general reminder, you should be heading from cx_Oracle towards [python-oracledb](https://cjones-oracle.medium.com/open-source-python-thin-driver-for-oracle-database-e82aac7ecf5a) which succeeded it a couple of years back.  If you haven't heard by now, [python-oracledb](https://github.com/oracle/python-oracledb) is a 'thin' driver by default and doesn't need to have Instant Client installed for most uses.

**Comment by sharadraju** [comment]
Please check out the [macOS ARM64 Instant Client announcement blog](https://medium.com/@sharad-chandran/oracle-instant-client-macos-arm64-for-apple-m1-m2-m3-platforms-is-now-available-950f1bc041f9) for more details.

**Comment by mfvetter** [comment]
This is awesome @cjbj!

I was able to compile the PHP PECL [OCI8 extension](https://pecl.php.net/package/oci8) with this instantclient version.

Thank you so much!

**Comment by cjbj** [comment]
@CInglez-STC sorry to hear that. I'll pass that onto the development group that own it.  

[For everyone's general information, since Instant Client is off-topic for this repo,  the best place to raise packaging issues is either to Oracle Support, or https://forums.oracle.com/ords/apexds/domain/dev-community/category/application-development (and ping @sharadraju so he can alert the dev group)].

**Comment by sharadraju** [comment]
@CInglez-STC 
The impdp trap issue with macOS ARM Instant Client has been fixed in the latest Instant Client tools package for ARM64:
https://download.oracle.com/otn_software/mac/instantclient/233023/instantclient-tools-macos.arm64-23.3.0.23.09-1.dmg
