### ISSUE TITLE
cx-Oracle intermittent errors followed by exp/imp errors

### ISSUE THREAD

**Issue by jimmy5589** [oracle/python-cx_Oracle#62]
1. What is your version of Python? Is it 32-bit or 64-bit?
Python 2.7.13 :: Anaconda 4.3.1 (64-bit)

2. What is your version of cx_Oracle?
cx-Oracle (5.3)

3. What is your version of the Oracle client (e.g. Instant Client)?  How was it
   installed?  Where is it installed?
Server side install, full version.
Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production

4. What is your version of the Oracle Database?
Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production

5. What is your OS and version?

Redhat 6
Linux brubl030 2.6.32-696.1.1.el6.x86_64 #1 SMP Tue Mar 21 12:19:18 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

6. What compiler version did you use?  For example, with GCC, run
   `gcc --version`.

gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-18)

7. What environment variables did you set?  How *exactly* did you set them?
export NLS_LANG=AMERICAN_AMERICA.AL32UTF8
export LD_LIBRARY_PATH=$ORACLE_HOME/lib:$ORACLE_HOME/network/lib:$ORACLE_HOME/rdbms/lib
export SHLIB_PATH=$ORACLE_HOME/lib32:/usr/lib
export PATH=/opt/oracle/product/anaconda2/bin:$PATH

8. What *exact* command caused the problem (e.g. what command did you try to
   install with)?  Who were you logged in as?

        cursor.executemany(None, M)

9. What error(s) you are seeing?

Not frequent, when we rerun sometimes doesn't happen.

"Exception:ORA-01458: invalid length inside variable character string"

Data frame of 1+ million rows. We have inspected it and no variables exceed column length in the database. Database fields are either VARCHAR2(10 CHAR) or FLOAT(126).

Today we had copied the schema from one database to another and we faced errors during the import performed with "impdp".
Errors were:

KUP-11007: conversion error loading table "EXP_FC"."Features_Daily"
ORA-01722: invalid number

KUP-11009: data for row: dx_avg_sameDowLastYear6weeks : '-~'

In many of the rows and columns.

Oracle support has the Doc ID  2046832.1 related with this issue.

"12c DataPump Import Fails With ORA-02374 ORA-01722 ORA-02372 Errors. (Doc ID 2046832.1)"

"If we select from the (11g) source table:
col dump format a30
select LEXPLINEID, MDEBIT, DUMP(MDEBIT,16) dump from amexpenseline;

LEXPLINEID     MDEBIT DUMP
---------- ---------- ----------------
32309451           -~ Typ=2 Len=1: 0
32309452           -~ Typ=2 Len=1: 0
32316032           -~ Typ=2 Len=1: 0
32316033           -~ Typ=2 Len=1: 0
32319558           -~ Typ=2 Len=1: 0
32319559           -~ Typ=2 Len=1: 0
32340291           -~ Typ=2 Len=1: 0
32340292           -~ Typ=2 Len=1: 0
32340293           -~ Typ=2 Len=1: 0
32340294           -~ Typ=2 Len=1: 0
32340295           -~ Typ=2 Len=1: 0

We can see, the value '0' is not a valid number (neither FLOAT nor NUMBER or another Oracle number type). We suspect the data could have been inserted from third party tools which used binary types (IEEE 754 format).

The import errors are reported as the result of a new verification check introduced in 12c which was not present in earlier versions like 11g .

This is a behavioral change and it is not a bug . This behavioral check for characters introduces through external application is not verified on lower versions ."

**Note the following**:
"We suspect the data could have been inserted from third party tools which used binary types (IEEE 754 format)"

Is this the case in this driver cx-Oracle ?? it seems to be ...
If so, how to avoid it ? 

I start thinking that the error that happnened with the import shows that the data is not stored with the supported format into the table "Features_Daily", causing some times the intermittent errors in the Python script and later the problem in the Import.

This is an ML app developed in Python running currently in Production.
Appreciated any support.

Thank you.
Best,
AH

**Comment by cjbj** [comment]
Thanks for the detail and for trying various solutions.  Your comment that impdp is failing points to invalid data.  From the support note "This behavior is correct in 12c and it is not a normal behavior in 11g to allow the invalid numbers."  Work with Oracle Support to resolve the invalid data & data pump issues first.

Once that is sorted out, if there is still an issue with cx_Oracle, then isolate some problem data and give us a testcase.  If you're using executemany() to insert data, look at the batcherrors feature to see if this isolates problem values; see http://cx-oracle.readthedocs.io/en/latest/cursor.html#Cursor.getbatcherrors

**Comment by jimmy5589** [comment]
Thanks for the link. The error returned from the executemany() when happens because doesn't always happen is "Exception:ORA-01458: invalid length inside variable character string".
On Oracle Support I found  "Bug 8617180  ORA-1458 error with large batch sizes using JDBC OCI driver", the description says:
"Description

    ORA-1458 can occur with large batch sizes using JDBC OCI driver an
     Oracle batching
     
    Rediscovery Notes:
     When using Oracle batching with lots of bind type changes and the first 
     batch sent is not be of the size set by setExecuteBatch() then ORA-1458
     can occur.
     
    Workaround
      Make sure the first batch send has the same size set by setExecuteBatch()
"
I'm using oracle 12.1.0.2. The Bug above suppose to be fixed with Oracle 12.1.0.1.
Just wondering if the cx-Oracle I have installed that is version 5.3 has been linked with a faulty Oracle library.

A few questions:
1- Is there a way to manipulate or trace the values set by  "setExecuteBatch()" when calling the Oracle Interface from a executemany() call ?

2- Is cx-Oracle Version 6.0rc2 any better in these respects ?

Our ML application is now in Production but I can always do some tests in a Test environment.

Any suggestion or help would be appreciated.

Thank you.
AH

**Comment by anthony-tuininga** [comment]
Regarding cx_Oracle 6, it loads the OCI library dynamically so you can test 12.1 and 12.2 without having to rebuild the binary. It would be worth testing with those combinations. As @cjbj mentioned, please provide a test case that demonstrates the problem and we'll be happy to look into it further.

**Comment by anthony-tuininga** [comment]
Closing due to lack of feedback. Please reopen with additional information if needed. Thanks!
