### ISSUE TITLE
Execute or Connect with multi_statements

### ISSUE THREAD

**Issue by hvardhan20** [oracle/python-cx_Oracle#620]
1. What versions are you using?
8.3.0

2. Describe the problem
I'm trying to execute this query script in one go using cursor.execute() but I get ORA-00922: missing or invalid option:
```
CREATE USER new_user IDENTIFIED BY somepassword;
GRANT CREATE SESSION TO new_user;
GRANT SELECT ON dba_users TO new_user;
```
I'm able to do this using SQL Developer. Running all 3 statements executed at once.
How I do achieve the same result using cx_oracle and using only 1 cursor.execute call? Am I missing something here?
Is it possible like with pymysql's MULTI_STATEMENTS flag? 
executemany doesn't help either.

3. Include a runnable Python script that shows the problem.
```
import cx_Oracle
query = """
CREATE USER new_user IDENTIFIED BY somepassword;
GRANT CREATE SESSION TO new_user;
GRANT SELECT ON dba_users TO new_user;
"""
connection = cx_Oracle.connect(user=user, password=pass, dsn=dsn)
with connection:
    with connection.cursor() as cursor:
        cursor.execute(query)
```
ORA-00922: missing or invalid option

**Comment by cjbj** [comment]
> I'm able to do this using SQL Developer. Running all 3 statements executed at once.

SQL Developer did not really execute them at once.  It executed them one at a time.

Unless you wrap statements inside a PL/SQL block, no client tool or language in Oracle supports executing multiple SQL statements at once.  And even with PL/SQL, it's the PL/SQL code that is executing each SQL statement one at a time.
