### ISSUE TITLE
Possible memory leak when using rowfactory

### ISSUE THREAD

**Issue by robingie** [oracle/python-cx_Oracle#623]
1. OracleDB version
Oracle 11.2.1

2. Commands
* print("sys.maxsize > 2**32:", sys.maxsize > 2**32)
True
* print("platform.platform:", platform.platform())
platform.platform: Linux-4.18.0-348.7.1.el8_5.x86_64-x86_64-with-glibc2.28
* print("platform.python_version:", platform.python_version())
platform.python_version: 3.9.6
* print("cx_Oracle.version:", cx_Oracle.version)
cx_Oracle.version: 8.3.0
* print("cx_Oracle.clientversion:", cx_Oracle.clientversion())
cx_Oracle.clientversion: (19, 6, 0, 0, 0)

3. Is it an error or a hang or a crash?
Hang because the system can run out of memory.

5. What error(s) or behavior you are seeing?
The Python application grows in memory size after a while. Each time a new cursor is created and the cursor.rowfactory is used, the memory requirement increases.

6. Include a runnable Python script that shows the problem.
```py
with conn.cursor() as cur:
        cur.execute(query2, start_id=start_id)

        # This line causes a growing memory footprint
        cur.rowfactory = lambda *args: dict(zip([d[0] for d in cur.description], args))

        # This line avoids the memory leak
        data = [dict((cur.description[i][0], value) for i, value in enumerate(row)) for row in cur.fetchall()]
```

![image](https://user-images.githubusercontent.com/76411323/166246912-48db42df-e68b-4321-88f9-67413ccfd4bd.png)

**Comment by lime-n** [comment]
I too have been having the same issue when running this. I have experienced black-screen as well as blue-screen because of the growing memory size.

What's the progress on this?

**Comment by sharadraju** [comment]
@lime-n  Please upgrade cx_Oracle to the new version, now called python-oracledb, see the [release announcement](https://cjones-oracle.medium.com/open-source-python-thin-driver-for-oracle-database-e82aac7ecf5a) and run your test case.

**Comment by lime-n** [comment]
Hi @sharadraju,

I have been using python-oracledb and this issue will regardlessly persist. When I have some time, I'll upload a reproducible example.

**Comment by CharlesChen0823** [comment]
@cjbj thank you quick response, but currently I don't have right to upgrade `cx_Oracle` to `python-oracledb`. I have to think other method to deal with this problem.

**Comment by cjbj** [comment]
@CharlesChen0823 let us know how you go.

**Comment by CharlesChen0823** [comment]
I have two plan
- long term, when next product release, I can modify code `cursor.rowfactory = lambda *args: dict(zip([i[0] for i in cursor.description], args))` to `column = [i[0] for i in cursor.description]; cursor.rowfactory = lambda *args: dict(zip(column, args))`.
- short term. According pracitical using, I have to manully break circle reference after [line](https://github.com/oracle/python-cx_Oracle/blob/70cbc4375275d84323b4b462539a70ba1a8c635b/src/cxoCursor.c#L1553C16-L1553C35), using `Py_CLEAR(cursor->rowFactory)`; as hacky method.
