### ISSUE TITLE
semicolons in Python code examples

### ISSUE THREAD

**Issue by Gudmundset** [oracle/python-cx_Oracle#629]
1. What is the link to the documentation section that needs improving?
https://github.com/oracle/python-cx_Oracle/blob/main/doc/src/user_guide/initialization.rst

2. Describe the confusion
There are semicolons after print statements for python code in three places:
```
print(err);
sys.exit(1);
```

3. Suggest changes that would help
Remove semicolons and it should be good to go!

**Comment by anthony-tuininga** [comment]
Thanks for reporting that. These have been removed in the new driver as can be seen here:

https://python-oracledb.readthedocs.io/en/latest/user_guide/initialization.html

I'll make the same changes here!
