### ISSUE TITLE
cx_oracle library erring in databricks since this monday - DatabaseError: (cx_Oracle.DatabaseError) DPI-1047: Cannot locate a 64-bit Oracle Client library: "libclntsh.so: cannot open shared object file: No such file or directory". See https://cx-oracle.readthedocs.io/en/latest/user_guide/installation.html for help

### ISSUE THREAD

**Issue by aravindk777** [oracle/python-cx_Oracle#634]
Hi,

I have been using this library for very long in AWS databricks and it used to work without any issues, but since this Monday (7/25) I started to get the below error. I could not find any reason myself behind this error and wonder if any recent upgrades have this side effect. 

I tried restarting my cluster to see if this would get re-installed but still seeing this issue. This was installed using PyPI for Databricks. 
```
DatabaseError: (cx_Oracle.DatabaseError)
 DPI-1047: Cannot locate a 64-bit Oracle Client library: "libclntsh.so: cannot open shared object file: No such file or directory". 
See https://cx-oracle.readthedocs.io/en/latest/user_guide/installation.html for help
```
Can someone help on how to resolve this?

**Comment by cjbj** [comment]
If an AWS friendly reader can't help you work out your AWS library loading issue, you could try the new version of cx_Oracle, since it doesn't necessarily need the Oracle Client libraries, see the [release announcement](https://cjones-oracle.medium.com/open-source-python-thin-driver-for-oracle-database-e82aac7ecf5a).

**Comment by cjbj** [comment]
Closing - no update or additional info is available.

**Comment by aravindk777** [comment]
Hey sorry for getting back to this so late, but we literally got to know
the root cause and found a workaround solution for that.

Cause: databricks was somehow losing the init scripts we have and that has
the library configs including env variables setup.

Why and how did it lose: not sure, but working with Databricks support
internally as first step.

Solution: had to restore the init script setup and restarting the cluster
solves this issue.

**Comment by cjbj** [comment]
@aravindk777 thanks for sharing the solution.  I'm glad you got it working.
