### ISSUE TITLE
Continuous fuzzing by way of OSS-Fuzz

### ISSUE THREAD

**Issue by DavidKorczynski** [oracle/python-cx_Oracle#636]
1. Describe your new request in detail

I was wondering if you would like to integrate continuous fuzzing by way of OSS-Fuzz? Fuzzing is a way to automate test-case generation and can be used to find unexpected exceptions in Python and memory corruption issues in native code. In this PR https://github.com/google/oss-fuzz/pull/8420 I did an initial integration into OSS-Fuzz. The fuzzer does a simple connection request following by a query execution. The goal is to find memory corruption issues that may exist, and I think there is room to extend the fuzzing and would be happy to do so down the line.

OSS-Fuzz is a service run by Google for important open source projects. If you would like to integrate, the only thing I need is a list of email(s) that will get access to the data produced by OSS-Fuzz, such as bug reports, coverage reports and more stats. Notice the emails affiliated with the project will be public in the OSS-Fuzz repo, as they will be part of a configuration file.

**Comment by DavidKorczynski** [comment]
It would also be nice to fuzz https://github.com/oracle/python-oracledb so if you're happy to integrate then I'd be happy to do that project as well

**Comment by cjbj** [comment]
This is a question for our governance team.  @spavlusieva any comments?

**Comment by cjbj** [comment]
Closing - no updates.
