### ISSUE TITLE
Possible memory leak when using fetchone or fetchall  

### ISSUE THREAD

**Issue by qwertyue** [oracle/python-cx_Oracle#637]
- OracleDB version
   11.2.1
- Python version
    3.10

- Code:

       cursor = cx_Oracle.connection(conn_str)

       # use fetchone to get data 
       res = cursor.execute(select sql statment).fetchone() 
       del res  
       cursor.close()  

       # use fetchall to get data
        res = cursor.execute(select sql statment).fetchall()
        del res  
        cursor.close()  

Description:
Even such simple code, 
it will leave the data returned by the fetchone(fetchone) function unable to be recycled, 
i even use gc.collection  function.
Or do I need to execute specific methods to prevent memory leaks?

**Comment by cjbj** [comment]
Can you include a complete, runnable script with the exact SQL statement? Also include the CREATE TABLE statement.
Show us how you are measuring the memory use and what results you are seeing.
Finally, what are the versions of cx_Oracle and of the Oracle client libraries used? You can get these by run the script shown in the [issue template](https://raw.githubusercontent.com/oracle/python-cx_Oracle/main/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by qwertyue** [comment]
> Can you include a complete, runnable script with the exact SQL statement? Also include the CREATE TABLE statement. Show us how you are measuring the memory use and what results you are seeing. Finally, what are the versions of cx_Oracle and of the Oracle client libraries used? You can get these by run the script shown in the [issue template](https://raw.githubusercontent.com/oracle/python-cx_Oracle/main/.github/ISSUE_TEMPLATE/bug_report.md).

I will upload this information in a few hours
But I may not be able to give you such information as exact SQL statement, CREATE TABLE statement.
I passed memory_profile plug-in to prints the memory usage line by line
I noticed that the fetchone function will use 0.3mb of memory each time it gets data, and will not release
The fetchall function retrieves 50MB of data each time, and deleting the res reference will release 30MB

Finally, I will try the latest python oracle db

**Comment by qwertyue** [comment]
here are my system info :

platform.platform: Windows-10-10.0.19044-SP0
sys.maxsize > 2**32: True
platform.python_version: 3.10.7
cx_Oracle.version: 8.3.0
cx_Oracle.clientversion: (11, 2, 0, 4, 0)

and some running message:
   104     53.2 MiB      0.0 MiB           1       sql = '''select * from apd.apd_customer_t'''    
   105
   106     53.3 MiB      0.1 MiB           1       res = cursor.execute(sql).fetchone()
   107     53.3 MiB      0.0 MiB           1       print(f'res = {len(res)}, size = {sys.getsizeof(res) / 1024}')
   108     53.3 MiB      0.0 MiB           1       cursor.close()
   109                                             # del conn
   110     53.3 MiB      0.0 MiB           1       print('ref = ', sys.getrefcount(res))
   111     53.3 MiB      0.0 MiB           1       del res

 and the res data unable to released.

**Comment by anthony-tuininga** [comment]
I assume that since you closed the issue the problem is resolved? What solved your problem?

**Comment by qwertyue** [comment]
> I assume that since you closed the issue the problem is resolved? What solved your problem?

I ran the simulation code ( fetchone, and  increase 0.1mb each time ) 2000 times, and the memory increased by 220MB.

Then gc.collect() was called by me, which reduced my memory by 160MB,  only added 50MB of memory.

So I don'tthink the memory leaked, And now I have a new question (sqlalchemy, cx_oracle and multithreading are used) is OCI-21500: internal error code, arguments: [17099], [], [], [], [], [], [], []

**Comment by anthony-tuininga** [comment]
If you are using multthreading, you need to ensure that the `threaded` parameter is set to `True`. This is done automatically in the new python-oracledb driver.

**Comment by qwertyue** [comment]
> If you are using multthreading, you need to ensure that the `threaded` parameter is set to `True`. This is done automatically in the new python-oracledb driver.

If I use sqlalchemy to connect oracle, the `threaded` parameter will be set to `True` automatically in python-oracledb driver?

**Comment by anthony-tuininga** [comment]
Yes, take a look at the [documentation](https://python-oracledb.readthedocs.io/en/latest/user_guide/appendix_c.html#python-frameworks-sql-generators-and-orms) to help during the transition. SQLAlchemy 2.0 (when it is released) will have native support for python-oracledb.

**Comment by qwertyue** [comment]
Setting 'threaded' does not solve the problem of OCI-21500: internal error code, arguments: [17099], [], [], [], [], [], [], [].

**Comment by qwertyue** [comment]
> Yes, take a look at the [documentation](https://python-oracledb.readthedocs.io/en/latest/user_guide/appendix_c.html#python-frameworks-sql-generators-and-orms) to help during the transition. SQLAlchemy 2.0 (when it is released) will have native support for python-oracledb.


Setting 'threaded' does not solve the problem of OCI-21500: internal error code, arguments: [17099], [], [], [], [], [], [], [].

**Comment by anthony-tuininga** [comment]
Open a new issue, then, and give as much detail as you can -- including a runnable test case if at all possible!

**Comment by cjbj** [comment]
Also see the blog posts:
- [Using python-oracledb 1.0 with SQLAlchemy, Pandas, Django and Flask](https://levelup.gitconnected.com/using-python-oracledb-1-0-with-sqlalchemy-pandas-django-and-flask-5d84e910cb19)
- [Using SQLAlchemy 2.0 (development) with python-oracledb](https://medium.com/oracledevs/using-the-development-branch-of-sqlalchemy-2-0-with-python-oracledb-d6e89090899c).
