### ISSUE TITLE
The arguement "python_requires" is not set in correct position

### ISSUE THREAD

**Issue by PyVCEchecker** [oracle/python-cx_Oracle#639]
Hello!
I noticed that your **"python_requires"** has no effect
you set that behind the section **[metadata]** in setup.cfg
```
[metadata]
name = cx_Oracle
description = Python interface to Oracle
long_description = file: README.md
long_description_content_type = text/markdown
keywords = Oracle, database
...
python_requires = >=3.6
...
```
However, it  should belong be the **[options]** section, the more appropriatie way to declare "python_requires" is 
```
[metadata]
name = cx_Oracle
description = Python interface to Oracle
long_description = file: README.md
long_description_content_type = text/markdown
...
[options]
python_requires = >=3.6
```
In this way, “pip install” can check python version on the fly during distribution selection , and  " check minimum supported Python version" is needless 
```python
# check minimum supported Python version
if sys.version_info[:2] < (3, 6):
    raise Exception("Python 3.6 or higher is required. " +
            "For python 2, use 'pip install cx_Oracle==7.3'")
```
Thanks for your attention.
Best regrads,
PyVCEchecker

**Comment by cjbj** [comment]
Thanks for the report.  It is already moved to `[option]` in the most recent release of the driver, which is now at https://github.com/oracle/python-oracledb/blob/main/setup.cfg  Can you review that file and let us know if you have any issues?

I'll leave this open in case @anthony-tuininga wants to make any change to cx_Oracle's cfg when he does a minor version release.

**Comment by PyVCEchecker** [comment]
It's a good job. I don't think there was any mistake. ;-)

**Comment by cjbj** [comment]
Closing as fixed in python-oracledb.  Thanks for reporting it.
