### ISSUE TITLE
importing problem

### ISSUE THREAD

**Issue by likhithpindi1** [oracle/python-cx_Oracle#643]
1. What versions are you using?  11g

3. Describe the problem

D:\DBS>python -m pip install cx_Oracle --upgrade
Requirement already satisfied: cx_Oracle in c:\users\likhi\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (8.3.0)

problem: 
>>> import cx_Oracle
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'cx_Oracle'
>>>

4. Show the directory listing where your Oracle Client libraries are installed (e.g. the Instant Client directory).  Is it 64-bit or 32-bit?
   C:\oraclexe\app\oracle\product\11.2.0\server

6. Show what the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) is set to?
   path :C:\oraclexe\app\oracle\product\11.2.0\server

8. Show any Oracle environment variables set (e.g. ORACLE_HOME, ORACLE_BASE)
    
C:\oraclexe\app\oracle\product\11.2.0\server

**Comment by cjbj** [comment]
Can you show us two consecutive python calls in the same terminal window, the first doing the install and the second where you call 'import cx_Oracle'.  If you are not running the second python call in the same terminal, please share how you are running it.

Other comments:
- it's time to upgrade cx_Oracle to the new version, now called python-oracledb, see the [release announcement](https://cjones-oracle.medium.com/open-source-python-thin-driver-for-oracle-database-e82aac7ecf5a).
- it's time to upgrade Oracle XE to version 21, https://www.oracle.com/database/technologies/xe-downloads.html
