### ISSUE TITLE
Connecting to Oracle Wallet using cx_Oracle

### ISSUE THREAD

**Issue by priyuganesan** [oracle/python-cx_Oracle#653]
1. What versions are you using?

platform.platform: Windows-10-10.0.19045-SP0
sys.maxsize > 2**32: True
platform.python_version: 3.9.13
cx_Oracle.version: 8.3.0
cx_Oracle.clientversion: (12, 2, 0, 1, 0)

2. Describe the problem

<I am trying to connect to Oracle Wallet configured on a server by our DBA's. I have the alias and the wallet location as well. I created a tnsnames.ora file and created an entry for the connect alias 
mynetalias =
    (DESCRIPTION =
        (ADDRESS = (PROTOCOL = TCP)(HOST = dbhost.example.com)(PORT = 1521))
        (CONNECT_DATA =
            (SERVER = DEDICATED)
            (SERVICE_NAME = orclpdb1)
        )
    )
I also created an entry in the sqlnet.ora for the wallet location
WALLET_LOCATION =
    (SOURCE =
        (METHOD = FILE)
        (METHOD_DATA =
            (DIRECTORY = location)
        )
    )
SQLNET.WALLET_OVERRIDE = TRUE

I then went into the python module where we cx_Oracle to establish a connection to the database and included a line of code that said
self.connector = cx_Oracle.Connection(dsn="mynetalias")

I get an error message
<html>
<body>

DatabaseError: ORA-12154: TNS:could not resolve the connect identifier specified |  
Can someone please help me understand what I could be missing here ?
 >

3. Include a runnable Python script that shows the problem.

**Comment by cjbj** [comment]
Did you set TNS_ADMIN?

Review https://cx-oracle.readthedocs.io/en/latest/user_guide/connection_handling.html#connecting-to-oracle-cloud-autonomous-databases

(PS, upgrade from cx_Oracle to [python-oracledb](https://cjones-oracle.medium.com/open-source-python-thin-driver-for-oracle-database-e82aac7ecf5a))

**Comment by priyuganesan** [comment]
> Did you set TNS_ADMIN?
> 
> Review https://cx-oracle.readthedocs.io/en/latest/user_guide/connection_handling.html#connecting-to-oracle-cloud-autonomous-databases
> 
> (PS, upgrade from cx_Oracle to [python-oracledb](https://cjones-oracle.medium.com/open-source-python-thin-driver-for-oracle-database-e82aac7ecf5a))

Yes, I set that to the folder that has the tnsnames.ora and sqlnet.ora. (yes, will look to upgrade to python-oracledb soon)

**Comment by cjbj** [comment]
Can SQL*Plus connect?

If so, share more details about the exact cx_Oracle code and network file configuration so we can check you have correct values and environment.

**Comment by priyuganesan** [comment]
> Can SQL*Plus connect?
> 
> If so, share more details about the exact cx_Oracle code and network file configuration so we can check you have correct values and environment.

I tried SQLPlus and see the same error there too

Z:\>sqlplus /@QAATUTOMATIONAPUB_APUBT

SQL*Plus: Release 19.0.0.0.0 - Production on Wed May 17 09:48:49 2023
Version 19.3.0.0.0

Copyright (c) 1982, 2019, Oracle.  All rights reserved.

ERROR:
ORA-12154: TNS:could not resolve the connect identifier specified

My tnsora looks like this
![image](https://github.com/oracle/python-cx_Oracle/assets/133822140/f6330152-7e9e-407b-a9d4-7ec9743d1f12)

My sqlnet
![image](https://github.com/oracle/python-cx_Oracle/assets/133822140/bd521dd4-60cc-4301-939e-6c52171f8ee0)

My python code that tries to establish connection with the db
self.connector = cx_Oracle.Connection(dsn="mynetalias")

Please let me know if I am missing anything else here....

**Comment by priyuganesan** [comment]
> Have you set the environment variable `TNS_ADMIN` to point to the location of your sqlnet.ora and tnsnames.ora files? The error you are getting suggests that it can't find your tnsnames.ora or the alias found within it!

I think I do...here's where my .ora files are
![image](https://github.com/oracle/python-cx_Oracle/assets/133822140/7011aa82-89db-420b-952a-de7f09914713)

Here's my env variable
![image](https://github.com/oracle/python-cx_Oracle/assets/133822140/40fe3ef3-587d-459b-8dc8-cea5ea1f9380)
