### ISSUE TITLE
Installaing on Python3.11

### ISSUE THREAD

**Issue by doronz88** [oracle/python-cx_Oracle#656]
I noticed no `.whl` files are created for Python3.11 - making especially windows installations much more difficult. I believe just adding `311` into [`tox.ini`](https://github.com/oracle/python-cx_Oracle/blob/main/tox.ini) should be enough to solve that.

**Comment by cjbj** [comment]
The latest version of cx_Oracle was renamed python-oracledb.  This does have Python 3.11 packages, see https://pypi.org/project/oracledb/#files. Please upgrade!

The new doc is at https://python-oracledb.readthedocs.io/en/latest/index.html
