### ISSUE TITLE
cx-Oracle cannot be installed

### ISSUE THREAD

**Issue by kamalcse** [oracle/python-cx_Oracle#659]
× Building wheel for cx-Oracle (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      <string>:6: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      C:\Users\ibbluser\AppData\Local\Temp\pip-build-env-0m9p12uo\overlay\Lib\site-packages\setuptools\config\expand.py:134: SetuptoolsWarning: File 'C:\\Users\\ibbluser\\AppData\\Local\\Temp\\pip-req-build-fsjv6mni\\README.md' cannot be found
        return '\n'.join(
      running bdist_wheel
      running build
      running build_ext
      building 'cx_Oracle' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]
note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cx-Oracle
Failed to build cx-Oracle
ERROR: Could not build wheels for cx-Oracle, which is required to install pyproject.toml-based projects

**Comment by anthony-tuininga** [comment]
The error tells you everything you need to know: you need Microsoft Visual C++ 14.0 or greater and you can get it by downloading and installing "Microsoft C++ Build Tools".

That said, pre-compiled binaries are available for cx_Oracle up to Python 3.10. For Python 3.11 (and soon Python 3.12) you can get pre-compiled binaries for [python-oracledb](https://oracle.github.io/python-oracledb/), which is the replacement for cx_Oracle.
