### ISSUE TITLE
DatabaseChangeNotification.py sample does not work

### ISSUE THREAD

**Issue by markfinn** [oracle/python-cx_Oracle#66]
1. What is your version of Python? Is it 32-bit or 64-bit?
Python 2.7.13 64 bit

2. What is your version of cx_Oracle?
Tried cx_Oracle 6.0b1, rc2, and final

3. What is your version of the Oracle client (e.g. Instant Client)?  How was it
   installed?  Where is it installed?
/opt/oracle/instantclient_12_2 from zip

4. What is your version of the Oracle Database?
11xe in a docker container on linux

5. What is your OS and version?
ubuntu 14.04

6. What compiler version did you use?  For example, with GCC, run
   `gcc --version`.
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4

7. What environment variables did you set?  How *exactly* did you set them?
none

8. What *exact* command caused the problem (e.g. what command did you try to
   install with)?  Who were you logged in as?
using the sample code, logged in as a user I created (and gave the change notification grant to).

9. What error(s) you are seeing?
the callback is never called.  I watched with wireshark and do see traffic on the notification socket when I insert a row, and I tried a PL/SQL socket sender that was able to send out to netcat, so I don't think docker is the issue.  I believe at one point I also tried a vagrant install and didn't see a difference.  The socket message doesn't seem to get through OCI/cx_Oracle.

Also, I noticed that there doesn't seem to be a unit test for change notification, although maybe I'm missing it.

**Comment by anthony-tuininga** [comment]
You are correct that there is no unit test currently for change notification. Network issues can indeed prevent the messages from getting through. I don't have the expertise to know what you might check so I'll see if someone else can help answer this question for you.

**Comment by anthony-tuininga** [comment]
Is the docker container one that I can get as well so that we can test and see if we can replicate your issue?

**Comment by markfinn** [comment]
`docker pull alexeiled/docker-oracle-xe-11g`

`docker run -name oracle -d --shm-size=2g -p 1521:1521 -v ~/local-oracle-sql:/etc/entrypoint-initdb.d alexeiled/docker-oracle-xe-11g`

the sql file in `~/local-oracle-sql/create-user.sql` is:

`CREATE TABLESPACE tbs_perm_01 DATAFILE 'tbs_perm_01.dbf' SIZE 10M AUTOEXTEND ON;
CREATE TEMPORARY TABLESPACE tbs_temp_01 TEMPFILE 'tbs_temp_01.dbf' SIZE 5M AUTOEXTEND ON;
CREATE USER mytestuser IDENTIFIED BY mytestuserpw DEFAULT TABLESPACE tbs_perm_01 TEMPORARY TABLESPACE tbs_temp_01;
GRANT create session, alter session, create table, create view, create any trigger, create any procedure, create sequence, create synonym, change notification, unlimited tablespace TO mytestuser;


When I ran the demo code I tried connecting to the database on localhost and on my real hostname.  neither helped.

**Comment by markfinn** [comment]
found it: 11.2 Client Unable To Receive Notifications From 11.2 Database [ID 1310859.1]

http://www.databaseusers.com/article/7707671/OracleDependency%3A+OnChangeEvent+not+raised

cx_Oracle isn't the problem.  I need to wait for 11.2.0.3 or use the workaround of `alter system set events '10867 trace name context forever, level 1'` for now.

**Comment by anthony-tuininga** [comment]
Thanks for following up.
