### ISSUE TITLE
ORA-12560: TNS:protocol adapter error (Python x Oracle DataBase)

### ISSUE THREAD

**Issue by jorgemoura** [oracle/python-cx_Oracle#662]
--------------------------------------------------------------------------------------------------------------------------------
Hi there!

I'm having problems to connect my Jupyter Notebook with my database Oracle.
In the true, I don't know how to do it and I am trying .. but while one of this attempt, I see the error belew:

ORA-12560: TNS:protocol adapter error

For your knowledge, my code below:

import cx_Oracle
connection = cx_Oracle.connect('server_ip:port/database')
cursor = connection.cursor()
cursor.execute('select * from any_table')
for result in cur:     
    print (result)  
    cur.close() 
    con.close()

-----------------------
| Oracle version: 12   |
-----------------------

Can anyone help me with this error?

Best Regards from Brazil.
Jorge Moura
--------------------------------------------------------------------------------------------------------------------------------

**Comment by jorgemoura** [comment]
teste

**Comment by anthony-tuininga** [comment]
May I suggest you try [python-oracledb](https://oracle.github.io/python-oracledb/) instead? It is intended to replace cx_Oracle and has a thin mode which may work better for you.

In the code you provided I don't see a user name and password. Are you trying to use external authentication?
