### ISSUE TITLE
Update PyPI Listing to Increase Visibility of Deprecation/Replacement

### ISSUE THREAD

**Issue by darkroastcreative** [oracle/python-cx_Oracle#664]
1. What is the link to the documentation section that needs improving?

https://pypi.org/project/cx-Oracle/ (PyPI Package Listing)

2. Describe the confusion

Currently, the [PyPI listing for cx_Oracle](https://pypi.org/project/cx-Oracle/) does not mention that the package was renamed/replaced by [python-oracledb](https://pypi.org/project/oracledb/). Given the popularity of the package (and the presence of third-party guides on how to use the package that may not reference python-oracledb), it's possible that developers may choose to use cx_Oracle in their projects without gaining an awareness that they should likely be using python-oracledb, or that python-oracledb exists (resulting in refactoring work that could've been avoided and potential security risks).

3. Suggest changes that would help

Update cx_Oracle PyPI package listing to add messaging to call out that the package was replaced/renamed with a link to python-oracledb. In addition, if cx_Oracle is no longer being maintained (including security updates), make this more apparent (perhaps by using the `Development Status :: 7 - Inactive` classifier).

**Comment by darkroastcreative** [comment]
The content of the "News" section in [this version of README.md](https://github.com/oracle/python-cx_Oracle/blob/6766bcaf27bf52c314219c21ffbf82d75b9a7602/README.md) seems like it would be a good fit for the messaging on the package's PyPI listing, particularly if you could format the text in a way that stands out.

**Comment by anthony-tuininga** [comment]
Unfortunately PyPI does not allow for the package listing to be modified *without* making a new release. This is [deliberate](https://github.com/pypi/warehouse/issues/2170#issuecomment-326271729) and a source of grief to many. Making a new release is not planned at this point so we're kind of stuck with what we have. The documentation and GitHub have been modified to point to the new driver which is the best that can be done at this point.
