### ISSUE TITLE
execute memory leak

### ISSUE THREAD

**Issue by kkivi** [oracle/python-cx_Oracle#69]
Repeated execution of the query via existing cursor ( possibly with different parameters) causes huge memory leak

The stripped down example is attached.

Two variants of query execution - mleak1 and mleak2, with and without prepare work the same way

The same problem exists in both python3 and python2

Reopening cursor after each query fixes the leak

The problem was reproduced on two completely different machines 

> logname@machine1(ubuntu_16.04):~> python3
> Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
>     [GCC 5.4.0 20160609] on linux
>     Type "help", "copyright", "credits" or "license" for more information.
>     >>> import cx_Oracle
>     >>> cx_Oracle.__version__
>     '6.0rc2'
>     >>> 
> 

> [logname@machine2]$ python3
> Python 3.5.1 (default, Oct 22 2016, 08:10:47) 
>     [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux
>     Type "help", "copyright", "credits" or "license" for more information.
>     >>> import cx_Oracle
>     >>> cx_Oracle.__version__
>     '6.0'
> >>> 

```python
import cx_Oracle
import psycopg2

sql_text="select 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' from dual"
def mleak1(connect_string_ora ):
    with cx_Oracle.connect(connect_string_ora) as dbo:
        ora_cursor=dbo.cursor()


        for i in range(0,10000000):

            ora_cursor.execute(sql_text) 

            for r in ora_cursor:
                print (r) 

def mleak2(connect_string_ora ):
    with cx_Oracle.connect(connect_string_ora) as dbo:
        ora_cursor=dbo.cursor()

        ora_cursor.prepare(sql_text)
        for i in range(0,10000000):

            ora_cursor.execute(None) 

            for r in ora_cursor:
                print (r)

def no_mleak(connect_string_pg ):

    with psycopg2.connect(connect_string_pg) as dbp:
        pg_cursor=dbp.cursor()
        pg_cursor.execute("create table dual(f) as select 1")    #to mimics oracle sql text query

        for i in range(0,10000000):

            pg_cursor.execute(sql_text) 

            for r in pg_cursor:
                print (r) 

mleak1('scott/tiger')

#mleak2('scott/tiger')

#no_mleak('password=xxx dbname=mydb user=myuser')
```

**Comment by anthony-tuininga** [comment]
As noted [on StackOverflow](https://stackoverflow.com/questions/45798475/python-cx-oracle-memory-leak) this bug has already been fixed. Thanks for reporting it!

**Comment by anthony-tuininga** [comment]
The correction for this issue was included in 6.0.2, which was just released.

**Comment by pfortin-urbn** [comment]
@anthony-tuininga we are using django 1.9.7 which is not compatible with cxOracle 6.X.X is there a plan to fix the memory leak in the 5.X.X branch?

**Comment by anthony-tuininga** [comment]
@pfortin-urbn, the memory leak referenced in this bug was introduced in the initial betas of cx_Oracle 6 so cx_Oracle 5 should not be affected by this. I wasn't aware that Django 1.9.7 is not compatible with cx_Oracle 6. Do you have a link to the issue in Django that you can share? Or did you encounter this yourself, in which case perhaps you can share the incompatibility directly? Please create another issue in that case. Thanks!
