### ISSUE TITLE
cannot execute query "SHOW PARAMETER AUDIT_TRAIL"

### ISSUE THREAD

**Issue by anma241** [oracle/python-cx_Oracle#72]
Dear guys,
When I execute query "SHOW PARAMETER AUDIT_TRAIL" like below:
`connection = cx_Oracle.connect("/", mode=cx_Oracle.SYSDBA)`
`cursor = connection.cursor()`
`res = cursor.execute("SHOW PARAMETER AUDIT_TRAIL")`
It always alerts _cx_Oracle.DatabaseError: ORA-00900: invalid SQL statement_
How can I create query "SHOW PARAMETER AUDIT_TRAIL" with cx_Oracle?
Tks!

**Comment by jmcp** [comment]
What version of Oracle DB are you connecting to?
What version of cx_Oracle are you using?
If you connect to the DB using sqlplus as the same user, and execute the same query, do you get the same error?

**Comment by anma241** [comment]
Dear @jmcp, 
I'm using Oracle DB 11g release 2, cx_Oracle 6.0.1.
When I connect to the DB using sqlplus with _sqlplus / as sysdba_, I get the result:

![image](https://user-images.githubusercontent.com/29242626/29703245-ef30fb32-899e-11e7-970b-55d5ae93bb11.png)

**Comment by Dronablo** [comment]
And this behaviour is absolutely correct, isn't it? "SHOW PARAMETER" is not an SQL statement, it's just client command which is supported by sqlplus and some other clients (like SQL Developer and sqlcl).
Your actual code should be like:
```
connection = cx_Oracle.connect("/", mode=cx_Oracle.SYSDBA)
cursor = connection.cursor()
res = cursor.execute("select name, value from v$parameter where name like lower('%'||:x||'%')", ['AUDIT_TRAIL'])
```

Real sqlplus query:
```
SELECT NAME NAME_COL_PLUS_SHOW_PARAM,DECODE(TYPE,1,'boolean',2,'string',3,'integer',4,'file',5,'number',        6,'big integer', 'unknown') TYPE,DISPLAY_VALUE VALUE_COL_PLUS_SHOW_PARAM FROM V$PARAMETER WHERE UPPER(NAME) LIKE UPPER(:NMBIND_SHOW_OBJ) ORDER BY NAME_COL_PLUS_SHOW_PARAM,ROWNUM
```

**Comment by anma241** [comment]
@Dronablo , it works :) thanks
