### ISSUE TITLE
cx_Oracle.connect failing because library cannot be loaded

### ISSUE THREAD

**Issue by sikrut** [oracle/python-cx_Oracle#73]
#### Answer the following questions:

1. What is your version of Python? Is it 32-bit or 64-bit?
**Python 2.7.13 , 32-bit**

2. What is your version of cx_Oracle?
**cx_Oracle 6.0.1 32-bit**

3. What is your version of the Oracle client (e.g. Instant Client)?  How was it
   installed?  Where is it installed?
**C:\instantclient-basic-nt-12.1.0.2.0**
**32-bit**

4. What is your version of the Oracle Database?
**Oracle Database 12c Enterprise Edition 	12.1.0.2.0	64bit Production**

5. What is your OS and version?
**Windows 7**

6. What compiler version did you use?  For example, with GCC, run
   `gcc --version`.
**pip 9.0.1 for download and install**

7. What environment variables did you set?  How *exactly* did you set them?
**System > Advanced Settings > Environment Variable > System Variables > PATH
_added_  ;C:\instantclient-basic-nt-12.1.0.2.0**

8. What *exact* command caused the problem (e.g. what command did you try to
   install with)?  Who were you logged in as?
**cx_Oracle.connect(user,pass,dsn)**

9. What error(s) you are seeing?
**DPI-1047: 32-bit Oracle Client library cannot be loaded: "The specified module could not be found".**

**Comment by sikrut** [comment]
I've followed the advice of the other posts, but i still cannot get the connection to go through.

**Comment by anthony-tuininga** [comment]
After setting the environment variable, did you restart your command prompt? Verify that the environment variable is set (command: set PATH)? Verify that the DLL is located in the expected location (command: dir C:\instantclient-basic-nt-12.1.0.2.0\oci.dll)? Verify that the correct redistributable has been installed? Reviewed and followed the [instructions](https://oracle.github.io/odpi/doc/installation.html#windows) for installation?

**Comment by sikrut** [comment]
@anthony-tuininga That was it. I set my PATH to the folder too high in the hierarchy. Once i set to **C:\instantclient-basic-nt-12.1.0.2.0\instantclient_12_1**, then it worked, because the child folder stores the _dll_.

Thank you!
