### ISSUE TITLE
Incompatible with Oracle 10g

### ISSUE THREAD

**Issue by doudz** [oracle/python-cx_Oracle#76]
I'm porting a application from python 2 to python 3 to connect to an Oracle 10g database (Baan IVc4 ERP) but cx_Oracle doesn't support Oracle 10g !
Because of remaining Windows XP, I have to use Python 3.4 (Python 3.5 and later doesn't support Windows XP) BUT there is no compatible combinaison of Python 3.4 and Oracle 10g in previous cx_Oracle version
On Linux I use cx_Oracle 5.2.1 with success but I can't find any cx_Oracle 5.2.1 Windows binaries

**Comment by cjbj** [comment]
What about these https://pypi.python.org/pypi/cx_Oracle/5.2.1 ?

**Comment by doudz** [comment]
But there's no windows binaries for 10g

I found a workaround, Oracle instantclient 12 is compatible with Oracle 10g database so I can use cx_Oracle 6 with Oracle Instantclient 12 with Python 3.4
It works on Windows 7 and 10
Now I have to check that solution on Windows XP

**Comment by anthony-tuininga** [comment]
cx_Oracle 5.2 and higher only supports Oracle Client 11.2 and higher. As you indicated, you can use a newer client to access an Oracle 10g database. You should also be able to use the 11.2 instant client if necessary.

**Comment by anthony-tuininga** [comment]
If you can build cx_Oracle yourself, you should be able to use the source for 5.1.2 as well.
