### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 100: invalid continuation byte

### ISSUE THREAD

**Issue by drno-reg** [oracle/python-cx_Oracle#8]
Hello,

**I have Python 3.6.1 64 bit,
Oracle client 12.2 x64,
OS windows 10 x64,
compiler MS C/C++ 19.10.25017 x64**

Tried install 

**pip install cx_Oracle**

end got error

```
Collecting cx_Oracle
  Using cached cx_Oracle-5.3.tar.gz
Installing collected packages: cx-Oracle
  Running setup.py install for cx-Oracle ... error
Exception:
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 100: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python36\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\python36\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\python36\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\python36\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "c:\python36\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "c:\python36\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 100: invalid continuation byte

```
How to solve this problem?

**Comment by anthony-tuininga** [comment]
From the exception it looks like something is happening within pip itself. Perhaps try downloading the source package manually (or grabbing it from the pip cache) and try running these commands directly:

```
python setup.py build
python setup.py install
```

Sometimes there is a discrepancy as well between the pip shortcut and the module installed in your Python distribution. You can get around that potential issue by issuing this command instead:

`python -m pip install cx_Oracle`

Hopefully one of those will help you out. I just tried a brand new installation of Python 3.6.1 64-bit on Windows myself and it worked as expected.

**Comment by drno-reg** [comment]
Anthony, Thank you for your reply.

I tried to run python -m pip install cx_Oracle, 
the problem was reproduced again and I got the same error.

After I tried to uninstall Visual Studio 2017 and this after next try cx_Oracle installed OK.

> C:\Windows\system32>python -m pip install cx_Oracle
> Collecting cx_Oracle
>   Using cached cx_Oracle-5.3.tar.gz
> Installing collected packages: cx-Oracle
>   Running setup.py install for cx-Oracle ... done
> Successfully installed cx-Oracle-5.3

Thank You!!!

**Comment by anthony-tuininga** [comment]
You're welcome. So the installation of Visual Studio 2017 was a problem. Interesting! Thanks for following up.

**Comment by fengzhao** [comment]
I have installed Visual Studio 2017 ,when I use "pip install scrapy", I got the same problem  UnicodeDecodeError  , so how can I solve the problem if I wan't to unistall Visual Studio 2017 ?

**Comment by zenogears** [comment]
Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)] on win32

Type "copyright", "credits" or "license()" for more information.

>>> import cx_Oracle

Traceback (most recent call last):

  File "<pyshell#0>", line 1, in <module>

    import cx_Oracle

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 53: invalid continuation byte

 Install cx_Oracle from wheel: https://pypi.python.org/packages/d4/1c/661d044f6f776dcd2f6748598d40ce773f03d7e9c4da60d004e445a132c1/cx_Oracle-6.0b2-cp36-cp36m-win_amd64.whl#md5=7576311cf8478cecd998b34e10cc89de
i can't install Visual Studio for build cx_Oracle from src. 
i have not any Visual Studio. So i can't even delete Visual Studio 17...
Have any solution?

**Comment by anthony-tuininga** [comment]
Please open a new issue instead of piggybacking on an old one!
