### ISSUE TITLE
DPI-1049 symbol OCIClientVersion not found in OCI library

### ISSUE THREAD

**Issue by nmmassey2** [oracle/python-cx_Oracle#80]
I've installed Python, Oracle Instant Client (12.2) and cx_Oracle (using pip) onto a 32-bit windows 7 machine and am trying to connect my python instance to my Oracle database. When I try to connect using the following code
```
import cx_Oracle
cx_Oracle.clientversion()

db1 = cx_Oracle.connect('username/pw//hostURL:port/serviceName')
```
, I receive the following error:
"DatabaseError: DPI-1049: symbol OCIClientVersion not found in OCI library"

I've installed the appropriate instant client containing the .dll files needed. I've set the PATH variable to point to this folder. Could you please advise how to connect?

Thank you!

**Comment by cjbj** [comment]
- Do you have other (older) Oracle software on the machine?  Make sure Instant Client is first in PATH when you actually run Python.  Restarting the terminal or similar may be necessary.

- While you're checking, verify you installed the [correct VS redistributable for 12.2](https://support.microsoft.com/en-us/kb/2977003#bookmark-vs2013).

**Comment by nmmassey2** [comment]
I rearranged the PATH variable to point to the Instant Client 12.2 first, and have installed the VS 2013 distributable per documentation. Still receiving the same error code.

I do have OraClient11g installed on my computer, but I only use the latest version of Oracle SQL Developer. Should I uninstall the older version?

**Comment by crisansou** [comment]
I got the same error, I've installed the Oracle Developer Suite, so I don't need a client. Do you know what is the problem? Below are the settings:

**1)** Environment variables

**a)** PATH: "D:\DevSuiteHome\bin"
**b)** TNS_ADMIN: "D:\DevSuiteHome\NETWORK\ADMIN"

**2)** Code

import cx_Oracle

uid = "user"  
pwd = "password" 
db  = "IP:1530" 

connection = cx_Oracle.connect(uid + "/" + pwd + "@" + db)
cursor = connection.cursor()

cursor.execute("SELECT * FROM TABLE") 
result = cursor.fetchone()  
if result == None:
    print("No results")
    exit
else:
    while result:
        print(result)
        result[0]
        result = cursor.fetchone()

cursor.close()
connection.close()

After execution was displayed this message:

"Traceback (most recent call last):
line 8, in <module> connection = cx_Oracle.connect(uid + "/" + pwd + "@" + db)
cx_Oracle.DatabaseError: DPI-1049: symbol OCIClientVersion not found in OCI library

Process finished with exit code 1"

**Comment by anthony-tuininga** [comment]
What version of the Oracle Developer Suite do you have installed? cx_Oracle requires an Oracle client of 11.2 or higher. Can you install an instant client and ensure that it is first in the PATH environment variable?

**Comment by crisansou** [comment]
Anthony, thank you for your answer but unfortunately didn't work.

I use Oracle Developer Suite 10g and database 11.2.0.4.0, as you suggested I downloaded an client ("instantclient-basic-windows.x64-11.2.0.4.0.zip") and unzip in directory C:\.

I changed the environment variables and restarted the machine, but the problem continues:

**a)** PATH: "**C:\instantclient_11_2**;D:\DevSuiteHome\bin;C:\ProgramData\Oracle\Java\javapath;c:\Rtools\bin;"
**b)** TNS_ADMIN: "**C:\instantclient_11_2**"

**Comment by anthony-tuininga** [comment]
Did you confirm that the environment variables are set as expected before running Python and importing cx_Oracle? If you set the environment variables in the GUI, you have to restart your command prompt to ensure that the new values are in place.

Also, are you using 32-bit Python or 64-bit Python?

**Comment by crisansou** [comment]
Yes, first I changed the environment variables and then restarted the system. I use 32-bit Python, but the machine is 64-bit.

**Comment by anthony-tuininga** [comment]
If you are using 32-bit Python, then you also must use a 32-bit instant client. But the instant client you downloaded was 64-bit! That will get ignored. Either use 64-bit Python or download a 32-bit instant client. You can't mix and match 32-bit and 64-bit software!

**Comment by anthony-tuininga** [comment]
BTW, you can use a 12.2 client to connect to an 11.2 database. You don't have to use the 11.2 client!

**Comment by crisansou** [comment]
Thanks for the information! I'll reinstall the Python, in the first time I chose the main site option (python-3.6.3.exe).

**Comment by anthony-tuininga** [comment]
You're welcome. Let us know if you are able to get the issue resolved. Thanks!

**Comment by crisansou** [comment]
Anthony,

I installed Anaconda 64 bits to study Data Science and after changing the code as below I was able to connect in the database, thanks!

import cx_Oracle

uid = "user"  
pwd = "password" 
dsnStr = cx_Oracle.makedsn("IP", "1530","dbdev01") 

connection = cx_Oracle.connect(user=uid, password=pwd, dsn=dsnStr)

**Comment by anthony-tuininga** [comment]
Glad you got it figured out. I'll mark this as closed, then!

**Comment by hfrog713** [comment]
Hi, quick question. I am getting the same Error. 
I am on a 32 bit machine with 32 bit everything. 
I have set modified the PATH environement variable to include the location of C:\oracle\instantclient_12_2
My question is, The environement variables that need to be modified/added are these system or user environement variables?
Below are the ones the previous user said she modified.

------
a) PATH: "C:\instantclient_11_2;D:\DevSuiteHome\bin;C:\ProgramData\Oracle\Java\javapath;c:\Rtools\bin;"
b) TNS_ADMIN: "C:\instantclient_11_2"

**Comment by anthony-tuininga** [comment]
The best way to ensure that you are using the right values is to simply go into a command prompt and display the values there. Then you need to check each entry in your PATH environment variable to see if an OCI.DLL file can be found in it. If it can, you need to verify that it is the right version and number of bits (32-bit or 64-bit). Sometimes OCI.DLL can be found in the system directories -- this is especially true of older installations.

**Comment by hfrog713** [comment]
I am getting the same error, i have already installed the Instant Client zip. 
I am on a 32 bit machine, 32 bit python 3.4.0, 32 bit oracle sql developer installed. 
I have made sure to put the path to OCI.dll first in the PATH user variable. 
I installed cx-Oracle directly from PIP. I have version 6.2.1 installed. 
Not sure what else to try. 

This is the message i am receiving.
cx_Oracle.DatabaseError: DPI-1049: symbol OCIClientVersion not found in OCI library

**Comment by hfrog713** [comment]
Sorry about posting twice, when i refreshed the page it didnt have the initial comment. 
The oci.dll file i am trying to read is located in this directory C:\Oracle\instantclient_12_2. 
I have added that to my PATH user variable and my Path system variable and i have also installed the 32 bit VS 2013 Redistributable.

**Comment by hfrog713** [comment]
I have found 3 directories in my PATH that contain a oci.dll file. 

C:\Oracle\product\10.1.0\Client_1\BIN
C:\Oracle\ORA92\bin
C:\Oracle\instantclient_12_2

As i mentioned above i have placed the C:\Oracle\instantclient_12_2 path in my PATH user environment variable and Path system environment variable. I pasted it in there as the first directory so i am sure that it is there before the other directories.

Any other thoughts?

**Comment by anthony-tuininga** [comment]
Did you open a command prompt and examine the PATH environment variable?

**Comment by hfrog713** [comment]
yes i did, the first directory listed is C:\Oracle\instantclient_12_2

**Comment by anthony-tuininga** [comment]
Search your machine and see if there are any other OCI.DLL files found anywhere. Windows might have already loaded one found in system directories, for example, which might be conflicting. If you find one in your system directories, move it somewhere else or rename it so it doesn't conflict. If you do that, you'll also need to reboot.

**Comment by hfrog713** [comment]
Do you know if i do that can it/will it break my SQL Developer installation?
My current version of oracle sql developer is .....3.1.07
My install location is......C:\sqldeveloper-3.1.07.42\sqldeveloper

Not sure what you mean by system directories? Is there a specific directory i should check?

**Comment by hfrog713** [comment]
Do you know if there is a way to check what is being loaded if any and where that oci.dll file is located?

**Comment by hfrog713** [comment]
Also, do you know if the environment variable ORACLE_HOME would affect which OCI.DLL file is being loaded?

**Comment by anthony-tuininga** [comment]
Doing a search will not break anything. You can do that using this command in the root of each drive:

dir /s OCI.DLL

SQL Developer generally uses JDBC to connect, which is independent of OCI.DLL, so it shouldn't affect it at all.

If you're comfortable with making changes to the code, you could add a call to GetModuleFileName() at the beginning of the method dpiOci__loadLibValidate() and print out the results.

The environment variable ORACLE_HOME should not be used on Windows.

**Comment by hfrog713** [comment]
ok great i will try tomorrow and let you know.
Not really sure how i can modify the file. I found the pyd file for cx_Oracle but not sure what to do next. I would need to update the .py file right? but i am not able to find it.
I will look into it further and let you know how it goes. 

Thanks for all your help

**Comment by anthony-tuininga** [comment]
You would have to download the source and modify the file odpi/src/dpiOci.c and then build it. But if that isn't something you're comfortable with an alternative can be found. Hopefully your search for OCI.DLL turns up the location without having to make those changes to the source!

**Comment by hfrog713** [comment]
ok i will try the search first thing tomorrow morning, if that doesnt work then i will try downloading the source and modifying the file.

Thanks, 
Hernando

**Comment by hfrog713** [comment]
Hi Anthony, that seems to have releaved the error i was getting but i am getting another error now. 

cx_Oracle.DatabaseError: ORA-12705: Cannot access NLS data files or invalid environment specified

From what i was able to find, this is related to language settings in oracle? Are you able to confirm this and recommend a potential solution. I saw somewhere online that i need to clean up my Oracle keys in the registry but i would have no idea what keys to modify or remove.

Can you please assist?

Again i appreciate all the help.

**Comment by anthony-tuininga** [comment]
Yes, that is due to NLS settings. The output from the "oerr" command on Linux is as follow:

12705, 00000, "Cannot access NLS data files or invalid environment specified"
// *Cause: Either an attempt was made to issue an ALTER SESSION command
//         with an invalid NLS parameter or value; or the environment
//         variable(s) NLS_LANG, ORA_NLSxx, or ORACLE_HOME was incorrectly
//         specified, therefore the NLS data files cannot be located.
// *Action: Check the syntax of the ALTER SESSION command and the NLS
//          parameter, correct the syntax and retry the statement, or
//          specify the correct directory path/values in the environment
//          variables.

I'm not sure about Oracle keys in the registry so wouldn't know what to suggest there! I only occasionally use Windows and then only use the instant client. :-)

**Comment by hfrog713** [comment]
:) aprecciate the help, what i did to solve the NLS message was add a system environment variable called NLS_LANG.

I used the following query to get the language from Oracle SQL Developer. 
`select userenv('LANGUAGE') from dual`
Then i plugged that in NLS_LANG environment variable. 
Thanks for all your help i have got the connection working.

**Comment by anthony-tuininga** [comment]
Glad you got it going. You shouldn't need to set the NLS_LANG environment variable, but if it was set incorrectly in a registry key then setting it may have corrected it. For example, you should be able to do this as well when you connect (substitute as necessary for your environment):

select userenv('LANGUAGE') from dual;

results in the value

AMERICAN_AMERICA.AL32UTF8

The value AL32UTF8 is Oracle's name for the standard encoding UTF-8. You can use either of those values in the connection encoding parameter:

conn = cx_Oracle.connect("user/pw@dsn", encoding="UTF-8", nencoding="UTF-8")
