### ISSUE TITLE
cx_oracle Database error line in get_new_connection

### ISSUE THREAD

**Issue by ekatsaros** [oracle/python-cx_Oracle#81]
I get an error  in get connection 
```
File "/root/.virtualenvs/dashboard/lib/python2.7/site-packages/django/db/backends/oracle/base.py", line 214, in get_new_connection
    return Database.connect(conn_string, **conn_params)
DatabaseError: ORA--0001: Message -1 not found;  product=RDBMS; facility=ORA
```

The error happened after months of working with no problems at all and unexpectally every now and then and lately quite often error in get connection with error Message -1 not found appears that is fixed by reloading Web Server(Apache). 

For Python 2.7.5, Django 1.8.15 cx_oracle 6.0.2  with Oracle version 11.2.04 

Any ideas what might be wrong?

Thank you.

**Comment by ckhmer1** [comment]
I get the same error and I don't know how to fix it too.
It happens randomly for a period of time, and in this period 90% of connections result in this error. After a while, suddenly disappear.

I use Python 2.7.9 , Django 1.7.8 cx_oracle 5.3 with Oracle version 11.2.0.2.0.

**Comment by anthony-tuininga** [comment]
Intermittent errors are hard to diagnose, especially on other people's systems! :-) Can you find a way to reliably replicate this issue? Can you use DPI_DEBUG_LEVEL=8 to figure out which part of the code is causing the problems? Are you using "threaded = True" for your connections?

**Comment by anthony-tuininga** [comment]
Closing this due to lack of a response. Feel free to re-open if you can provide some additional information using DPI_DEBUG_LEVEL=8, for example.

**Comment by ckhmer1** [comment]
Hi,
sorry for the late response.
It seems that the "threaded = True" solved the problem.
We haven't the problem anymore since the 28th of november.
Thanks for your help.
Claudio
