### ISSUE TITLE
cx_Oracle RPMs are  now available on yum.oracle.com

### ISSUE THREAD

**Issue by cjbj** [oracle/python-cx_Oracle#87]
The Oracle Linux group have posted cx_Oracle RPMs for Oracle Linux 6 & 7 on http://yum.oracle.com Check the blog post: https://blogs.oracle.com/linux/cx_oracle-rpms-have-landed-on-oracle-linux-yum-server

Update: Also see https://blogs.oracle.com/opal/python-cx_oracle-rpms-for-oracle-linux-6-and-oracle-linux-7

This is handy now that PyPI no longer allows RPMs to be uploaded.

**Comment by rafaelreuber** [comment]
When it will be available for Oracle 8?

**Comment by cjbj** [comment]
@rafaelreuber two things have to happen: (i) the DB group has to certify the DB (which includes the Oracle client libraries) on OL8 (ii) the Linux group have to release Instant Client RPMs and cx_Oracle RPMs.  I don't have a timeline on either, but I know testing for the first is in progress.
