### ISSUE TITLE
TimesTen: ORA- Datetime field overflow. executemany failes against same dataset, but execute works

### ISSUE THREAD

**Issue by az-z** [oracle/python-cx_Oracle#90]
This is really odd, but the error can only be reproduced when "executemany" runs **without** "execute". In other words, code below works. And "execute" portion also works, if i take out "executemany" part. If i take out "execute" portion of the code, only then the code fails with the

Oracle-Error-Code: 932
Oracle-Error-Message: ORA-00932: Datetime field overflow

```
class DB:
        DEFAULT_DB = '127.0.0.1/TT_1122:timesten:direct'
	DEFAULT_DB_USER = "user"
	DEFAULT_DB_USER_PASSWD = "pass"
	def __init__(self, db=None, user=None, passw=None):
		if db is None:
			db = self.DEFAULT_DB
		if user is None:
			user = self.DEFAULT_DB_USER
		if passw is None:
			passw = self.DEFAULT_DB_USER_PASSWD
               self.connection = cx_Oracle.Connection(user + "/" + passw + "@" + self.DEFAULT_DB)
def flushTicks(self, data: list):
		try:
			cursor = self.connection.cursor()
			for i in data:
				# cursor.setinputsizes(ts=cx_Oracle.TIMESTAMP)
				print(current_fn_name()," i - {}".format(i))
				cursor.execute("insert into ticks(reqid, tick_type_id,tick_value, ts) values( :ti, :tt, :tp, :ts ) ", ti=i[0],tt=i[1],tp=i[2],ts=i[3])
				self.connection.commit()
			cursor.close()

			print(current_fn_name(),'ExecuteMany')
			cursor = self.connection.cursor()
			cursor.executemany("insert into ticks(reqid, tick_type_id,tick_value, ts) values( :ti, :tt, :tp, :ts ) ", data)
			self.connection.commit()
			cursor.close()
		except cx_Oracle.DatabaseError as exc:
                    blah
```

The table is:
```
create table TICKS (
        REQID        NUMBER NOT NULL,
        TICK_TYPE_ID NUMBER NOT NULL,
        TICK_VALUE   NUMBER NOT NULL,
        TS           TIMESTAMP(6) NOT NULL);
```

Data sample:
flushTicks  i - [2, 4, 55.73, datetime.datetime(2017, 10, 4, 19, 30)]
flushTicks  i - [2, 4, 55.73, datetime.datetime(2017, 10, 4, 19, 31)]
flushTicks  i - [2, 4, 55.73, datetime.datetime(2017, 10, 4, 19, 32)]
flushTicks  i - [2, 4, 55.73, datetime.datetime(2017, 10, 4, 19, 33)]
flushTicks  i - [2, 4, 55.73, datetime.datetime(2017, 10, 4, 19, 34)]
flushTicks  i - [2, 4, 55.745, datetime.datetime(2017, 10, 4, 19, 35)]
flushTicks  i - [2, 4, 55.745, datetime.datetime(2017, 10, 4, 19, 36)]
flushTicks  i - [2, 4, 55.745, datetime.datetime(2017, 10, 4, 19, 37)]
flushTicks  i - [2, 4, 55.74, datetime.datetime(2017, 10, 4, 19, 38)]
flushTicks  i - [2, 4, 55.74, datetime.datetime(2017, 10, 4, 19, 39)]
flushTicks  i - [2, 4, 55.75, datetime.datetime(2017, 10, 4, 19, 40)]
flushTicks  i - [2, 4, 55.75, datetime.datetime(2017, 10, 4, 19, 41)]

this is a data feed from a server. If i manually create the list with this same data, "executemany" works fine.

#### Answer the following questions:

1. What is your version of Python? Is it 32-bit or 64-bit?
3.5 x64
2. What is your version of cx_Oracle?
cx-Oracle (6.0.2)

3. What is your version of the Oracle client (e.g. Instant Client)?  How was it
   installed?  Where is it installed?
got 11.2 from the oracle site.

4. What is your version of the Oracle Database?
TimesTen 11.2
5. What is your OS and version?
fedora 24x64

6. What compiler version did you use?  For example, with GCC, run
   `gcc --version`.
gcc (GCC) 6.3.1 20161221 (Red Hat 6.3.1-1)

[code Markdown formatting fixed - cj]

**Comment by cjbj** [comment]
Our TimesTen team is going to take a look; it might be their side.

**Comment by anthony-tuininga** [comment]
Our TimesTen team tried the below test case. It did not result in an error for both TimesTen 12 and 11.2. Can you provide a complete test case that does fail? We can look again if you can provide that. Thanks.

import cx_Oracle
import datetime

# connect to database
con = cx_Oracle.Connection('cx_Oracle/welcome@somedsn')
cursor = con.cursor()

# populate table
data = [
    (2, 4, 55.73, datetime.datetime(2017, 10, 4, 19, 30)),
    (2, 4, 55.73, datetime.datetime(2017, 10, 4, 19, 31)),
    (2, 4, 55.73, datetime.datetime(2017, 10, 4, 19, 32)),
    (2, 4, 55.73, datetime.datetime(2017, 10, 4, 19, 33)),
    (2, 4, 55.73, datetime.datetime(2017, 10, 4, 19, 34)),
    (2, 4, 55.745, datetime.datetime(2017, 10, 4, 19, 35)),
    (2, 4, 55.745, datetime.datetime(2017, 10, 4, 19, 36)),
    (2, 4, 55.745, datetime.datetime(2017, 10, 4, 19, 37)),
    (2, 4, 55.74, datetime.datetime(2017, 10, 4, 19, 38)),
    (2, 4, 55.74, datetime.datetime(2017, 10, 4, 19, 39)),
    (2, 4, 55.75, datetime.datetime(2017, 10, 4, 19, 40)),
    (2, 4, 55.75, datetime.datetime(2017, 10, 4, 19, 41))
]

cursor.executemany("""
        insert into ticks (reqid, tick_type_id, tick_value, ts)
        values(:ti, :tt, :tp, :ts )""", data)
con.commit()

**Comment by az-z** [comment]
unfortunately, thats all i have. The same data causes the exception if i use "executemany", but with "Execute" works fine. I obtained the data sample by logging the data to the stdout prior to "Executemany". if you can think of any other ways i can assist - please let me know.

**Comment by cjbj** [comment]
@az-z can you try the same that @anthony-tuininga created?

**Comment by anthony-tuininga** [comment]
Yes, please try with the simple test case I provided above which contains the sample data you provided. If that works for you, too, please find another set that doesn't. Thanks!

**Comment by az-z** [comment]
ok, give me a minute..

**Comment by az-z** [comment]
Sample test case works like a charm.

**Comment by az-z** [comment]
@cjbj , @anthony-tuininga 
 i m hitting this issue everytime i run the code:
```
	def flushTicks(self, data: list):
		try:
			log.info(" Start ")
			connection = self.pool.acquire()
			cursor = connection.cursor()
			# for i in data:
			# 	# cursor.setinputsizes(ts=cx_Oracle.TIMESTAMP)
			# 	# print(current_fn_name()," i - {}".format(i))
			# 	cursor.execute("insert into ticks(reqid, tick_type_id,tick_value, ts) values( :ti, :tt, :tp, :ts ) ",
			#                    ti=i[0],tt=i[1],tp=i[2],ts=i[3])

			cursor.executemany("""
			        insert into ticks (reqid, tick_type_id, tick_value, ts)
			        values(:ti, :tt, :tp, :ts )""", data)

			connection.commit()
			cursor.close()
			log.info(" Done ")

		except cx_Oracle.DatabaseError as exc:
...
```

I hoped that this bug is due to the other issue i had ( re: multithreading). Unfortunately i was wrong.
the data for TS column has only minutes.. 
i can't think of any good way to test this..

**Comment by cjbj** [comment]
- I think it's fair to say we really need a standalone test case from you.  Try cutting down your app to a minimum standalone file with the problem
- try cx_Oracle 5.3
- try different data types to see if this narrows down the problem
- try connecting to Oracle Database instead of TimesTen

**Comment by az-z** [comment]
that will take some time to do.

**Comment by anthony-tuininga** [comment]
Any progress on this?

**Comment by az-z** [comment]
None. I still have no good ideas on how to replicate the problem. I tried
reading from files, memory - all work as expected.

**Comment by anthony-tuininga** [comment]
Hmm, that's unfortunate. Did you want me to leave it open for a while so you can search for a way to replicate the problem for us?

**Comment by az-z** [comment]
The only idea i have, is to share my account login with you and most of
code, so you can replicate on your end.

I think you should close this one - i think its very specific to my case
(even if we assume that there is no mistake in my code) - involves async,
3rd party apis etc...

On Nov 27, 2017 13:12, "Anthony Tuininga" <notifications@github.com> wrote:

Hmm, that's unfortunate. Did you want me to leave it open for a while so
you can search for a way to replicate the problem for us?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/oracle/python-cx_Oracle/issues/90#issuecomment-347273106>,
or mute the thread

**Comment by anthony-tuininga** [comment]
Ok, I'll close it. I appreciate the offer to share your account login and code, but I don't think that would be a wise plan for either of us! You'll need to find a consultant or open a case with Oracle Support.
