### ISSUE TITLE
TimesTen: OCI-21500: internal error code, arguments: [17099], [], [], [], [], [], [], []

### ISSUE THREAD

**Issue by az-z** [oracle/python-cx_Oracle#94]
TimesTen: 11.2
cx -Oracle 6.0.2
gcc - [az@hp src]$ gcc -v
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/6.3.1/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,objc,obj-c++,fortran,ada,go,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --disable-libgcj --with-isl --enable-libmpx --enable-gnu-indirect-function --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 6.3.1 20161221 (Red Hat 6.3.1-1) (GCC)

With the increase of frequency of calls to the function below, it started to fail consistently. Usually it fails after 2-3 minutes of execution. In previous testing i used about 1-10 calls per second, today it increased to 50 ( calls per second). The DB has not been modified.

	def writeTicks(self, tickId: int, tickType: int, value: float, timestmp=None):
		""" Insert a line into TICKS
			Ticks type verification is done on DB level
			Time - as a timestamp with microseconds, or empty to get the datetime.now()
			"""
		log.info(" start writeTicks ")
		log.debug(" timestmp -  ".format(timestmp))
		if timestmp is None:
			timestmp = datetime.now()
		elif isinstance(timestmp, str):
			if len(timestmp) > 19:
				timestmp = datetime.strptime(timestmp, '%Y/%m/%d %H:%M:%S.%f')
			else:
				timestmp = datetime.strptime(timestmp, '%Y/%m/%d %H:%M:%S')
			log.debug(" timestmp -  ".format(timestmp))
		try:
			cursor = self.connection.cursor()
			cursor.setinputsizes(ts=cx_Oracle.TIMESTAMP)
			log.debug(" start Execute cursor ")
			cursor.execute("insert into ticks(reqid, tick_type_id,tick_value, ts) values( :ti, :tt, :tp, :ts ) ",
			               ti=tickId, tt=tickType, tp=value, ts=timestmp)
			log.debug(" end Execute cursor ")
			self.connection.commit()
			cursor.close()
			log.info(" Done ")

		except cx_Oracle.DatabaseError as exc:
			log.info(" Error : can't insert into table ")
			print('ERROR: Unable to insert values. tickId {}, tickType_id {}, Value {}, Timestamp {} '.format(tickId,
			                                                                                                  tickType,
			                                                                                                  value,
			                                                                                                  timestmp))
			error, = exc.args
			print("Oracle-Error-Code:", error.code)
			print("Oracle-Error-Message:", error.message)
			raise Exception("Unable to insert values")

LOG:
```
INFO - 2017-10-16 15:41:55,767 - writeTicks() 238 -  start writeTicks 
Errors in file :
OCI-21500: internal error code, arguments: [17099], [], [], [], [], [], [], []
OCI-21500: internal error code, arguments: [17099], [], [], [], [], [], [], []
��\��\��\����������������������������������������������������������������������������������������������������������������������A8�Ÿ��������������������������������������������������x'n&�������������������������������������������������x'n&�������������������������������������������������x'n&�Errors in file :
OCI-21500: internal error code, arguments: [17099], [], [], [], [], [], [], []
OCI-21500: internal error code, arguments: [17099], [], [], [], [], [], [], []
��\��\��\����������������������������������������������������������������������������������������������������������������F0032590����������������������������������������������������x'n&�������������������������������������������������x'n&�������������������������������������������������x'n&�Errors in file :
��\��\��\����������������������������������������������������������������������������������������������������������������F00325900����������������������������������������������������x'n&�������������������������������������������������x'n&�������������������������������������������������x'n&�
Process finished with exit code 1

```
-----------------------------------------------
tterrors.log:
```

15:39:49.40 Warn:    :  1900: 1906/0x7fbb1af92350: sbOLUndoByConn: oplog stack for connid 2 (python3.5) pid 9006: <none>
15:42:17.23 Warn:    :  1900: 9129 exited while connected to data store '/home/az/TimesTen/tt1122/info/TT_1122' shm 486672335 count=1
15:42:17.32 Warn:    :  1900: 1906/0x7fbb1af92350: sbOLUndoByConn: oplog stack for connid 1 (python3.5) pid 9129: <none>


The ttmesg.log:
15:42:17.23 Info:    :  1900: maind 36: socket closed, calling recovery (last cmd was 655)
15:42:17.23 Info:    :  1900: Starting daRecovery for 9129
15:42:17.23 Info:    :  1900: 9129 ------------------: process exited
15:42:17.23 Warn:    :  1900: 9129 exited while connected to data store '/home/az/TimesTen/tt1122/info/TT_1122' shm 486672335 count=1
15:42:17.23 Info:    :  1900: Examining /home/az/TimesTen/tt1122/info/TT_1122...
15:42:17.27 Info:    :  1905: hello
15:42:17.27 Info:    :  1900: Telling subdaemon 1000001 to evaluate /home/az/TimesTen/tt1122/info/TT_1122
15:42:17.27 Info:    :  1905: evaluate
15:42:17.27 Info:    :  1905: subd got #8.16, evaluate: name=/home/az/TimesTen/tt1122/info/TT_1122 shmKey=%cf%07%02%1d pid=%a9#%00%00
15:42:17.27 Info:    :  1905: subd: evaluate '/home/az/TimesTen/tt1122/info/TT_1122' pid 9129
15:42:17.27 Info:    :  1905: subd: OK rc=0
15:42:17.27 Info:    :  1900: marking subdaemon #1000001 (pid 1905) idle
15:42:17.27 Info:    :  1900: Rolling back transactions for pid 9129
15:42:17.27 Info:    :  1905: subd: done with request #8.16
15:42:17.32 Info:    :  1906: hello
15:42:17.32 Info:    :  1906: rollback
15:42:17.32 Info:    :  1906: subd got #33.66, rollback: name=/home/az/TimesTen/tt1122/info/TT_1122 shmKey=%cf%07%02%1d pid=%a9#%00%00
15:42:17.32 Info:    :  1906: subd: rollback pid 9129
15:42:17.32 Info:    :  1906: subd: found 1 connection belonging to pid 9129
15:42:17.32 Info:    :  1906: 9129 doRollbackWork: Calling sbOLUndoByConn for connid 1 (python3.5)
15:42:17.32 Warn:    :  1900: 1906/0x7fbb1af92350: sbOLUndoByConn: oplog stack for connid 1 (python3.5) pid 9129: <none>
15:42:17.32 Info:    :  1900: 1906/(nil): 1906 sbXactRollbackXcb started for connid 1 (python3.5)
15:42:17.34 Info:    :  1900: 1906/(nil): 1906 sbXactRollbackXcb finished for connid 1
15:42:17.34 Info:    :  1906: 9129 doRollbackWork: sbOLUndoByConn for connid 1 (python3.5) returned 0
15:42:17.34 Info:    :  1900: 1906/0x8c2b30: subd: ttProcessDeathCleanupByPidPhase1 pid 9129 
15:42:17.34 Info:    :  1900: 1906/0x8c2b30: ttHeapRecoverByPid(9129) entered 
15:42:17.34 Info:    :  1900: 1906/0x8c2b30: ttHeapRecoverByPid: conn 1 
15:42:17.34 Info:    :  1900: 1906/0x8c2b30: ttHeapRecoverByPid(9129): exits 
15:42:17.34 Info:    :  1900: 1906/0x8c2b30: kgttulcuByPidPhase1(9129) starts 
15:42:17.34 Info:    :  1900: 1906/0x8c2b30: kgttuGetLatch 0x7fa0006a98 0x7fbb0c05a350 0 666 returns 
15:42:17.34 Info:    :  1900: 1906/0x8c2b30: kgttulcyByPidPhase1 ends 
15:42:17.34 Info:    :  1900: 1906/0x8c2b30: subd: ttProcessDeathCleanupByPidPhase1 pid 9129 ends 
15:42:17.34 Info:    :  1900: 1906/0x8c2b30: subd: ttProcessDeathCleanupByPidPhase2 pid 9129 
15:42:17.34 Info:    :  1900: 1906/0x8c2b30: kgttulcuByPidPhase2(9129) starts 
15:42:17.34 Info:    :  1900: 1906/0x8c2b30: ttsCleanSessionState: calling ttsClearMutexSessionState 0x7fa0151ed0 
15:42:17.34 Info:    :  1900: 1906/0x8c2b30: ttsCleanSessionState: calling kglMutexCleanup 0x7fa1f8f418 
15:42:17.34 Info:    :  1900: 1906/0x8c2b30: ttsCleanSessionState: return 
15:42:17.34 Info:    :  1900: 1906/0x8c2b30: ttksurus: cag (nil) seg 0x7fa1f8f330 
15:42:17.34 Info:    :  1900: 1906/0x8c2b30: KSS: kssdch: so 0x7fa1f8f330 = session (0), child count = 0, pass = 0 
15:42:17.34 Info:    :  1900: 1906/0x8c2b30: kgttulcuByPidPhase2 pass 1 begins 
15:42:17.34 Info:    :  1900: 1906/0x8c2b30: calling kgttulcuByConnidPhase2(1) 
15:42:17.34 Info:    :  1900: 1906/0x8c2b30: kgttulcuByConnidPhase2: Cleaning state tree for connid 1 
15:42:17.34 Info:    :  1900: 1906/0x8c2b30: ttsCleanSessionState: calling ttsClearMutexSessionState 0x7fa00763f8 
15:42:17.35 Info:    :  1900: 1906/0x8c2b30: ttsCleanSessionState: calling kglMutexCleanup 0x7fa1f1e0d0 
15:42:17.35 Info:    :  1900: 1906/0x8c2b30: ttsCleanSessionState: return 
15:42:17.35 Info:    :  1900: 1906/0x8c2b30: kgttulcuByConnidPhase2 calling ttkssxdl 0x7fa1f1dfe8 
15:42:17.35 Info:    :  1900: 1906/0x8c2b30: kgttulcuByConnidPhase2 session deleted 
15:42:17.35 Info:    :  1900: 1906/0x8c2b30: kgttulcuByConnidPhase2 deleting process 9129 0x7fa1f1e120 
15:42:17.35 Info:    :  1900: 1906/0x8c2b30: ttkssxdl: deleting children of 0x7fa1f1e120 
15:42:17.35 Info:    :  1900: 1906/0x8c2b30: KSS cleanup: kssdch: so 0x7fa1f1e120 = process (1), child count = 0, pass = 0 
15:42:17.35 Info:    :  1900: 1906/0x8c2b30: ttkssxdl: children deleted rc 1 
15:42:17.35 Info:    :  1900: 1906/0x8c2b30: kgttudlpr(0x7fa1f1e120) connid id: 1 
15:42:17.35 Info:    :  1900: 1906/0x8c2b30: kgttulcuByConnidPhase2 process deleted 
15:42:17.35 Info:    :  1900: 1906/0x8c2b30: kgttulcuByConnidPhase2: clean for connid 1 complete 
15:42:17.35 Info:    :  1900: 1906/0x8c2b30: kgttulcuByConnidPhase2 returns 
15:42:17.35 Info:    :  1900: 1906/0x8c2b30: ttsCleanSessionState: calling ttsClearMutexSessionState 0x7fa0151ed0 
15:42:17.35 Info:    :  1900: 1906/0x8c2b30: ttsCleanSessionState: calling kglMutexCleanup 0x7fa1f8f418 
15:42:17.35 Info:    :  1900: 1906/0x8c2b30: ttsCleanSessionState: return 
15:42:17.35 Info:    :  1900: 1906/0x8c2b30: ttksurus: cag (nil) seg 0x7fa1f8f330 
15:42:17.35 Info:    :  1900: 1906/0x8c2b30: KSS: kssdch: so 0x7fa1f8f330 = session (0), child count = 0, pass = 0 
15:42:17.35 Info:    :  1900: 1906/0x8c2b30: kgttulcuByPidPhase2 finished cleanup pass 1. 
15:42:17.35 Info:    :  1900: 1906/0x8c2b30: kgttulcuByPidPhase2 no process objects for pid 9129, cleanup complete 
15:42:17.35 Info:    :  1900: 1906/0x8c2b30: subd: ttProcessDeathCleanupByPidPhase2 pid 9129 ends 
15:42:17.35 Info:    :  1906: subd: OK rc=0
15:42:17.35 Info:    :  1900: Decrementing nUsers by 1 from 12 to 11 for pid 9129, ds /home/az/TimesTen/tt1122/info/TT_1122, panicked=-1, trashed=-1, shmSeq=30
15:42:17.35 Info:    :  1900: Finished daRecovery for pid 9129.
15:42:17.35 Info:    :  1906: subd: done with request #33.66

```

**Comment by anthony-tuininga** [comment]
Can you provide a complete test case that demonstrates this issue? Something that I can run myself to replicate the issue? Thanks.

**Comment by az-z** [comment]
Anthony,
 I dont really know... the app is ingesting a data feed from a server. It
is a private server, i cant really share the account...
Maybe if there is a way to enable some sort of debug to produce more
information than it provides now?

**Comment by anthony-tuininga** [comment]
@az-z it doesn't have to be fancy. If you can generate a script that simply has a couple hundred calls to your writeTicks() function -- generated by logging the output from the real application? Or simply make up calls to writeTicks() that demonstrate the problem. Perhaps random data? Without the data that is causing the problem, though, it might take some time to replicate the issue on our own -- and we have other issues to address, too!

**Comment by az-z** [comment]
Let me work on this. Thank you Anthony

**Comment by az-z** [comment]
Anthony,
 i ran a few simple tests, and none of them confirms my suspicion that
increased frequency caused the crash.  Or at least it (increased in
frequency of executions) was not the root cause. I think that the having
set Connection(.., threaded=True) will be a better approach in asyncio
driven application.
It will take  me a few days to get the confirmation. Please keep the ticket
open for now.
Thank you for your help.

**Comment by az-z** [comment]
now, i'm occasionally get cx_Oracle.DatabaseError: ORA-01002: Function sequence error, while having a call to sql selct running in the asyncio executor:
```
cursor = self.connection.cursor()
		cursor.setinputsizes(t=cx_Oracle.TIMESTAMP)
		log.debug(" start Cursor execute ")
		row=cursor.execute(
			"""select ts_mi, norm_spread, stddev_240 from v_Sigma_240 
					where trunc(cast(ts_mi as date),'MI') = 
														(select trunc(cast(greatest(a.dt, b.dt) as date),'MI') from 
														    (select max(ts_mi) dt from v_sigma_240) a,
														    (select :t dt from dual) b
														)
			""", t = ts).fetchone()
		log.debug(" stop Cursor execute ")
		cursor.close()
```
and these objects are views.

the connection is : 
self.connection = cx_Oracle.Connection(user + "/" + passw + "@" + self.DEFAULT_DB,threaded=True)
i'm not sure why i'm getting this - i don't have any DML in this function.

**Comment by az-z** [comment]
@anthony-tuininga 
which one of the approaches is correct in case of multithreaded app:
a. use of the connection with "threaded=true" - http://www.oracle.com/technetwork/articles/vasiliev-python-concurrency-087536.html
b.use of the SessionPool - https://github.com/oracle/python-cx_Oracle/blob/master/samples/Threads.py

documentation questions:
a. For the SessionPool - i have trouble locating the documentation that explains it's init parameters, for example - cx_Oracle.SessionPool(SampleEnv.MAIN_USER, SampleEnv.MAIN_PASSWORD,
SampleEnv.CONNECT_STRING, 2, 5, 1, threaded = True). That line is from the examples, but i can see there are other parameters that can be provided.. but what are they?
(http://cx-oracle.readthedocs.io/en/latest/session_pool.html)

b. Same issue (no documentation) is for Connection().

**Comment by anthony-tuininga** [comment]
> which one of the approaches is correct in case of multithreaded app:
a. use of the connection with "threaded=true" - http://www.oracle.com/technetwork/articles/vasiliev-python-concurrency-087536.html
b.use of the SessionPool - https://github.com/oracle/python-cx_Oracle/blob/master/samples/Threads.py

If you are running a multi-threaded app you must specify threaded=True for either standalone connections or session pools. Which one you use depends on your application. If you are going to be acquiring/releasing connections many times over the course of the application, a session pool is the best option.

> documentation questions:
a. For the SessionPool - i have trouble locating the documentation that explains it's init parameters, for example - cx_Oracle.SessionPool(SampleEnv.MAIN_USER, SampleEnv.MAIN_PASSWORD,
SampleEnv.CONNECT_STRING, 2, 5, 1, threaded = True). That line is from the examples, but i can see there are other parameters that can be provided.. but what are they?
(http://cx-oracle.readthedocs.io/en/latest/session_pool.html)

You're looking in the wrong place! You want this for session pools: http://cx-oracle.readthedocs.io/en/latest/module.html#cx_Oracle.SessionPool and this for connections: http://cx-oracle.readthedocs.io/en/latest/module.html#cx_Oracle.Connection.

**Comment by az-z** [comment]
>...if you are going to be acquiring/releasing connections many times over the course of the application, a session pool is the best option.
is there a good way to measure an expense of acquire/release ?

> ... You're looking in the wrong place!
doh. thank you!

**Comment by anthony-tuininga** [comment]
> ...if you are going to be acquiring/releasing connections many times over the course of the application, a session pool is the best option.
is there a good way to measure an expense of acquire/release ?

You can use the Python module timeit to perform some measurements. In general, though, if the answer is more than a handful, I'd use a session pool. It has other advantages as well in terms of high availability, for example.

**Comment by az-z** [comment]
thank you @anthony-tuininga . Let me work on this. I'll report back.

**Comment by az-z** [comment]
Summary:
 this is not a bug, this is my lack of understanding about use of multithreaded app with cx_oracle.
Thank you for your help @anthony-tuininga .
