### ISSUE TITLE
cx_Oracle application not working in another database

### ISSUE THREAD

**Issue by beachoil** [oracle/python-cx_Oracle#95]
*Delete irrelevant parts of this template.*

### For general questions:

I have a simple application that is supposed to listen for database notifications and send a http message.
The application works fine when I connect to a Oracle database running in Oracle VM VirtualBox Manager. When I try to connect into another database in another machine in internal network, the notification listener is registered but change notification is not triggered. The database contents of my local database and server database can be considered similar.

So far I have tried:
A) The database user X has following grants on both systems:
GRANT EXECUTE ON DBMS_CQ_NOTIFICATION TO X; 
GRANT CHANGE NOTIFICATION TO X;
B) When I log into the database with user X using SQL Developer, I can execute the notification query.
C) The JOB_QUEUE_PROCESSES parameter is not set to a nonzero value in both environments. 
D) dml_locks is set to 1088 value in both environments.
E) There are no errors or trace files created in the server. 
F) Application is not throwing any error messages.
G) When I run the following SQL query as user X, it is returning expected three tables. The notification listener is registered in both of the environments:
SELECT REGID, TABLE_NAME FROM USER_CHANGE_NOTIFICATION_REGS;
H) User X is not owning the schema used in the queries. I tried also by granting schema owner user Y to use the notification queries but this is not working either.

Firewall might not be accepting connections from database server to my local machine. Could this be the issue?

#### Answer the following questions:

1. What is your version of Python? Is it 32-bit or 64-bit?
Python 3.6.2 32bit

2. What is your version of cx_Oracle?
cx_Oracle 6.0.2

3. What is your version of the Oracle client (e.g. Instant Client)?  How was it
   installed?  Where is it installed?
Oracle Client 11.2.0.1.0 32bit
Installation directory C:\Oracle\ora112

4. What is your version of the Oracle Database?
Oracle Database 11g Enterprise Edition 11.2.0.4.0 64bit

5. What is your OS and version?
Windows 10 Enterprise

6. What compiler version did you use?  For example, with GCC, run
   `gcc --version`.
I used precomplied cx_Oracle package.

7. What environment variables did you set?  How *exactly* did you set them?
N/A

8. What *exact* command caused the problem (e.g. what command did you try to
   install with)?  Who were you logged in as?

I trigger an event in the database that is supposed to be noticed by the CQN listener. The event is not triggered when using a database running on another machine.

9. What error(s) you are seeing?
I don't see any error messages.

**Comment by anthony-tuininga** [comment]
The firewall may indeed be the issue. Are you saying your code works when run on the same machine as the database and does not work when run on another machine?

**Comment by beachoil** [comment]
Yes, the code works on the same machine but does not work from another machine.

**Comment by anthony-tuininga** [comment]
Have you checked the firewall? See if you can connect to the database using SQL*Plus. Once you can do that cx_Oracle should also work.

**Comment by beachoil** [comment]
As I wrote in the original post, I can see that the application can register listener with the remote database, so connection to the database can be established.

**Comment by anthony-tuininga** [comment]
You'll need to check your network configuration. This question and answer from StackOverflow may be of help: https://stackoverflow.com/questions/36610463/cx-oracle-cqn-callback-usage-across-a-router.

**Comment by anthony-tuininga** [comment]
If you need to specify a particular port, you can do so using the port parameter when creating the subscription. There was a problem with this which was corrected in the cx_Oracle 6.1 release that was just made. Closing this for now but feel free to re-open if you have additional questions.
