### ISSUE TITLE
From 5.0.3 to 5.2.1 max size of a character decrease.

### ISSUE THREAD

**Issue by eliatou** [oracle/python-cx_Oracle#96]
We recently upgrade cx_Oracle from 5.0.3 to 5.2.1 and have problem with execution of oracle procedure.
Se size of the max input character  cas lowered from 32k to 4000 bytes.

Here a simple example:

in Oracle

```
create table test_load(a clob ,coment varchar2(256), dalog date default sysdate);

create or replace procedure load_test (z varchar2,zz varchar2)
as
begin  
  insert into test_load(a,coment) values(z,zz);
  commit;
end;
/
```

and in python:

```
import cx_Oracle
conn = cx_Oracle.connect('', threaded=False)
cur = conn.cursor()
com=cx_Oracle.version
msgxxk="a"*4000
cur.callproc('load_test',(msgxxk,com))
```

We have the ORA-01460 error when size of msgxxk is 4001 character in 5.2.0.1 and 32768 in 5.0.3

```
SQL> select max(dbms_lob.getlength ((a))) z,coment
  2  from test_load
  3  group by coment
  4  ;
         Z COMENT
---------- --------------------------------------------------------------------------------
     32767 5.0.3
      4000 5.2.1

SQL> 
```

Is the new comportement normal or not?

#### Answer the following questions:

1. What is your version of Python? Is it 32-bit or 64-bit?
we migrate our system from

```
Python 2.7.1 (r271:86832, Oct  7 2013, 11:56:55)
[GCC 4.4.6 20120305 (Red Hat 4.4.6-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
```
to

```
Python 2.7.13 (default, Aug 30 2017, 14:27:58)
[GCC 5.2.1 20150902 (Red Hat 5.2.1-2)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
```

2. What is your version of cx_Oracle?
we migrate our system from 

```
>>> cx_Oracle.version
'5.0.3'

```
to

```
>>> cx_Oracle.version
'5.2.1'
```

3. What is your version of the Oracle client (e.g. Instant Client)?  How was it
   installed?  Where is it installed?

11.2.0.4

4. What is your version of the Oracle Database?

Reproduced in 11.2.0.4 and 12.1.0.2

5. What is your OS and version?
Linux  2.6.32-642.6.2.el6.x86_64 #1 SMP Mon Oct 24 10:22:33 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux

6. What compiler version did you use?  For example, with GCC, run
   `gcc --version`.
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-17)

7. What environment variables did you set?  How *exactly* did you set them?
None

8. What *exact* command caused the problem (e.g. what command did you try to
   install with)?  Who were you logged in as?
See above

9. What error(s) you are seeing?
ORA-01460

**Comment by cjbj** [comment]
Can you try with cx_Oracle 5.3 and 6.0?  Thanks.

```
SQL> select max(dbms_lob.getlength ((a))) z,coment from test_load group by coment;

	 Z
----------
COMENT
--------------------------------------------------------------------------------
     32767
6.0.2
```

**Comment by eliatou** [comment]
Hello,
I made differents test for you.
Here are the output:
```

         Z COMENT
---------- --------------------------------------------------------------------------------
     32767 5.0.3
      4000 5.2.1
      4000 5.3
     32767 6.0b2
     32767 6.1.0-dev

SQL> 
```

Thank for your help

**Comment by anthony-tuininga** [comment]
I just tried with 5.0.3, 5.2.1, 5.3 and 6.1.0-dev as well. In all cases I was able to insert 32767 characters.
