### ISSUE TITLE
v6.0.2 Issue 68 Redux?

### ISSUE THREAD

**Issue by bschwab003** [oracle/python-cx_Oracle#98]
Hello,

Python 3.5.1 64 bit
cx_oracle v 6.0.2
windows 64 bit

Recently upgraded from 5.2.1 to 6.0.2.  We did so, specifically, to address the fix associated with Issue #68.

The truncation was resolve as expected.  However, we are seeing small differences in the values being returned from cx_Oracle vs. what is in the actual system.  It is always the last digit in these cases but it is also the digit that was previously being truncated.   Here is an example:

**Result from cx_Oracle 5.2.1:** 454208758447380.9
**Result from cx_Oracle 6.0.2:** 454208758447380.94
**Result from source system:** 454208758447380.91

Right now, its just a penny difference.   We haven't run into any values that are larger than the example provided here but I worry that more significant digits maybe impacted by this potential bug if/when we encounter large numbers.

**Comment by anthony-tuininga** [comment]
Are you using floating point numbers? I would strongly recommend the use of decimal.Decimal wherever accuracy is required. Normal Oracle numbers are stored in a decimal format and these can never be perfectly converted to a floating point number. Unless you're using NATIVE_FLOAT in Oracle I'd definitely suggest the use of decimal.Decimal.

**Comment by anthony-tuininga** [comment]
Note the information on this page: https://en.wikipedia.org/wiki/Double-precision_floating-point_format. Only 15 digits are guaranteed to be useful in a C double type. You have 16 digits so that explains the fluctuation. You'll definitely need to use a more capable number format in your case.

**Comment by bschwab003** [comment]
Thanks for the quick response.  Excuse my ignorance....But when you suggest the use of decimal.Decimal, I am assuming I need to configure my cx_oracle.Cursor object to store NUMBERS as a Python decimal.Decimal data types as opposed to the default Python float data type?

If so, how would I got about doing that?  In looking back at your comments for Issue #68, would I set make this change with the following line?

`cursor.setinputsizes(x=decimal.Decimal)`

Thank you again for help.

**Comment by bschwab003** [comment]
```
def output_type_handler(cursor, name, defaultType,
                        size, precision, scale):
    if defaultType == cx_Oracle.NUMBER:
        return cursor.var(
            cx_Oracle.STRING,
            255,
            outconverter=decimal.Decimal,
            arraysize=cursor.arraysize)


```

**Comment by bschwab003** [comment]
Researched more...

I am using an output handler as follows...

```
def NumbersAsDecimal(cursor, name, defaultType, size, precision,
        scale):
    if defaultType == cx_Oracle.NUMBER:
        return cursor.var(str, 100, cursor.arraysize,
                outconverter = decimal.Decimal)
```
And later...

`cursor.outputtypehandler = NumbersAsDecimal`

But still have not had any luck....

**Comment by bschwab003** [comment]
ah.....i was applying output handler to cursor.  should do it on connection object.

`conn.outputtypehandler = NumbersAsDecimal`

**Comment by anthony-tuininga** [comment]
If you put it on the connection then it affects every cursor created by that connection. Also, you can use a simpler output handler. I should adjust my sample to use the simpler code!

```python
def NumbersAsDecimal(cursor, name, defaultType, size, precision, scale):
    if defaultType == cx_Oracle.NUMBER:
        return cursor.var(decimal.Decimal, arraysize=cursor.arraysize)
```

**Comment by anthony-tuininga** [comment]
And, one other note: you can bind decimal.Decimal objects directly. You don't have to call cursor.setinputsizes() before you do!
