### ISSUE TITLE
TNS:Could not resolve the connect identifier specified

### ISSUE THREAD

**Issue by jamesmf** [oracle/python-cx_Oracle#99]
### For general questions:

Describe exactly what you did and what you want to happen.
Use the questions at the bottom of this template as a guide.

Cannot resolve a TNS identifier using cx_Oracle. However testing a connection to that TNS name works using both ODBC and pyodbc. The same syntax (using the same TNSnames file in the same location with matching TNS_ADMIN and ORACLE_HOME env vars) worked on another machine running Windows 7.

#### Answer the following questions:

1. What is your version of Python? Is it 32-bit or 64-bit?
Python 3.5 64-bit bundled with Anaconda 4.2

2. What is your version of cx_Oracle?
6.0.2

3. What is your version of the Oracle client (e.g. Instant Client)?  How was it
   installed?  Where is it installed?
Oracle 12.1, Full local install, installed (on Windows) to my non-primary drive (E:\... not C:\...) using a binary installer

4. What is your version of the Oracle Database?
12.1

5. What is your OS and version?
Windows 10 Enterprise

6. What compiler version did you use?  For example, with GCC, run
  installed with binary using `pip install cx_Oracle --upgrade`

7. What environment variables did you set?  How *exactly* did you set them?
I set the following environment variables using the Windows GUI (edit environment variables...)
- TNS_ADMIN (System var) = `E:\app\......\product\12.1.0\client_1\Network\Admin\`
- ORACLE_HOME (System var) = `E:\app\......\product\12.1.0\client_1`
- PATH (System var) += `E:\app\client\g623829\product\12.1.0\client_1\bin`
- I also tried PATH having `...\client_1\Network\Admin`, and just `..\client_1\`
- I also tried simultaneously adding the registry key `HKEY_LOCAL_MACHINE\SOFTWARE\ORACLE\TNS_ADMIN` and setting it to string value `E:\app\.....\product\12.1.0\client_1\Network\Admin`

8. What *exact* command caused the problem (e.g. what command did you try to
   install with)?  Who were you logged in as?
`cnxn = cx_Oracle.connect('USERXX/PWXX@NAMEXX')` logged in as USERXX

9. What error(s) you are seeing?
TNS: Could not resolve the connect identifier specified

NOTE: mysqlnet.ora file contains the line 
`NAMES.DIRECTORY_PATH= (TNSNAMES, EZCONNECT)`
I have also tried removing EZCONNECT.

**Comment by anthony-tuininga** [comment]
Are you able to use SQL\*Plus to connect to the database? As in

sqlplus userxx/pwxx@namexx

ODBC uses a different approach but SQL\*Plus uses the same libraries and connection protocols so if that one doesn't work you may get enough information to solve the problem. Let us know! Thanks.

**Comment by jamesmf** [comment]
That produces the same error. Seems like good confirmation that it isn't cx_Oracle - closing issue. 
Does any of the above info point to an incorrect setup? I couldn't find a way to confirm the correct tnsnames.ora file is being used. Thanks for the quick response.

**Comment by anthony-tuininga** [comment]
In a command prompt, perform the command

set TNS_ADMIN
dir %TNS_ADMIN%

The first command should show you the value of the TNS_ADMIN environment variable and you can confirm it is correct. The second command will show you the contents of that directory. If you can show the contents of sqlnet.ora and tnsnames.ora I might be able to help you further. Otherwise, you can look at Oracle configuration documentation and see if you can figure it out that way. Oracle does have tools to help you create those files, too (netca), which may be of help.

**Comment by jamesmf** [comment]
Looks like the sqlnet.ora file didn't exactly match the sqlnet.ora on the other machine. Replacing with the other version of sqlnet.ora makes it work, so I can research what made the difference. Thanks for your help!
